### ISSUE TITLE
Broken video on English site

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#1000]
### Description

Video does not display correctly. Shows HTML.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings#support-videos
2. Scroll to [Support videos] section

### Expected behavior

Video displays correctly and plays

### Screenshots

<img width="892" alt="Screen Shot 2021-02-25 at 9 53 36 PM" src="https://user-images.githubusercontent.com/71030271/109348417-bd530f80-7831-11eb-9f6e-6e28c07e43bc.png">

### Additional context

N/A

### Environment

N/A

**Comment by jerelmiller** [comment]
Looks like this was fixed with #1011
