### ISSUE TITLE
Issue: Add and edit monitors

### ISSUE THREAD

**Issue by cmijaresb** [newrelic/docs-website#10017]
## How can we make our docs better?
I think the "custom header" information is not clear at all, there's not enough details of how to get it

* Is something confusing? N/A
* Is something inaccurate or missing? Add instructions on how to customize the header using REST API call https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors/#simple
* Were you unable to complete a task? (What task?) No, add a custom header

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for letting us know @cmijaresb! I'm tagging @akristen as she's working on the synthetic docs :)

**Comment by cmijaresb** [comment]
Hey @bradleycamacho,
Thank you so much,
Let me know if there's anything I can help you with :)
Regards!

**Comment by akristen** [comment]
@cmijaresb Hi! I'm bringing this up with the synthetics PM I work with. It's a top priority doc to improve, so thanks for bringing this our way!

**Comment by cmijaresb** [comment]
Thank you @akristen

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
