### ISSUE TITLE
Issue: Collector for Confluent Cloud & Kafka monitoring

### ISSUE THREAD

**Issue by blissd** [newrelic/docs-website#10051]
## How can we make our docs better?

The problem:
* The documentation mentions both a Confluent Cloud API keys and a Confluent Resource API keys, but it is unclear where to use either in the config file because they are the same name in the example text. Namely `CONFLUENT_API_ID` and `CONFLUENT_API_SECRET`.
* The example `config.yaml` file does _not_ use the same names, but instead prefixes names with `INSERT_`.
* The example `config.yaml` has a config key at `receivers.kafkametrics.brokers`, but shows a single blank list entry. It is not clear if this list should be left blank or if actual Kafka broker endpoints should be entered.

Solution:
* Give the Confluent Cloud API key/secret and Confluent resource API key/secret different names.
* Use the matching names in the right places in the example `config.yaml`.
* Fix the broker list config to be clearer.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-kafka-confluentcloud/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Could you have a look at this one, @rhetoric101? Thanks!

**Comment by blissd** [comment]
I think the example `config.yaml` is missing a `metric_path` config:

```yaml

  prometheus:
    config:
      scrape_configs:
        - job_name: "confluent"
          metrics_path: /v2/metrics/cloud/export
          ...
```

And I've also had trouble with the NewRelic endpoint of `https://otlp.nr-data.net:4317`. I had to use the EU endpoint which is `https://otlp.eu01.nr-data.net:4317`.

**Comment by blissd** [comment]
I have to say, ideally the company I'm working with really doesn't want to have to run this connector and would much rather NewRelic provided a native Confluent Cloud integration like DynaTrace and DataDog.

**Comment by rhetoric101** [comment]
@blissd thanks for your helpful feedback! I've contacted our SME on this document, and we'll be making some updates!
