### ISSUE TITLE
Issue: Data privacy with New Relic

### ISSUE THREAD

**Issue by ferdinand-p** [newrelic/docs-website#10057]
## How can we make our docs better?

* Is something inaccurate or missing? GDPR Link is broken

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/security/security-privacy/data-privacy/data-privacy-new-relic/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 106.0.0.0
* **Device**: Unknown

**Comment by akristen** [comment]
I've updated this link at this PR: https://github.com/newrelic/docs-website/pull/10063
