### ISSUE TITLE
Link to language specific sites from the Japanese site in the global header and footer

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#1012]
### Description

Certain links across the docs site send the user to English properties while there are Japanese properties: newrelic.com, integrations page, etc.

### Steps to reproduce

1. clicking on the New Relic icon in the header leads to newrelic.com

### Expected behavior

Link sends user from Japanese doc site to Japanese doc site.

### Screenshots

N/A

### Additional context

It would be great to programmatically build re-directs so that if a Japanase property exist, we can automatically send the use to that property.

### Environment

N/A

**Comment by jpvajda** [comment]
@jmiraNR is the only Japanese property  we'd do this for newrelic.com? None of the other sites in our nav have language specific sites yet. Just checking also the footer behaves the same way, all urls point to english sites. Are there language specific sites for the footer links we need to think about here?

https://newrelic.com/about/careers
https://newrelic.com/termsandconditions/terms
https://newrelic.com/termsandconditions/dmca
https://newrelic.com/termsandconditions/services-notices
https://newrelic.com/termsandconditions/cookie-policy
https://newrelic.com/termsandconditions/uk-slavery-act

**Comment by jmiraNR** [comment]
@jpvajda it's not just about header or footer it's also about links within articles. within an article, there could be a link to newrelic.com/integrations. There is a Japanese version of that page. Translators do no see actual URLs just the text. If there is a way to take all the integrations links under /jp/ and direct them to the Japanese page, that would facilitate the user's journey.
integrations is an example. there could be more, including any links to newrelic.com in header/footer or within article bodies.

**Comment by jerelmiller** [comment]
@jmiraNR All links within docs themselves should automatically direct to their Japanese counterparts. If this is not happening for some reason, that is a bug we'll need to look at. In my testing, this was happening correctly.

There is a minor bug on auto generated index pages that don't currently redirect to the Japanese URL, but otherwise this should be good to go. Hopefully that + the other header/footer links that we know have Japanese pages should be all we need to update.

**Comment by jmiraNR** [comment]
@jerelmiller This is lower priority for today but as I mentioned, it's not just header and footer. The below only pertain to **non-docs links**.
There are links within the doc/article itself that send the user to the sign-up page [https://newrelic.com/signup](url), the Integrations page [https://newrelic.com/integrations](url), [https://newrelic.com](url) and maybe more. We have Japanese properties for these and some others. It would be great if we could ID these URLS and redirect users to the Japanese properties when they exist.

**Comment by jpvajda** [comment]
@jmiraNR We understand all of these related issues are on our list of things to resolve this week.
