### ISSUE TITLE
Broken Link - Okta link takes you to a sign up page

### ISSUE THREAD

**Issue by mrytower05** [newrelic/docs-website#10153]
## Description

There is a link when you click Okta [HERE](https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more/#requirements) that takes you to the wrong section in Okta. It is taking me to a sign up page on Okta, which I don't believe is correct. 
## Steps to reproduce

1. Visit the link above. 
2. From the list of SAML SSO support providers click on Okta

## Expected behavior

Should take you to the docs in Okta that align with setting up New Relic, not a sign up page. 

## Screenshots

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/91172434/199837424-f7822dd3-cc6b-4d22-b772-7f081ac8d418.png">

**Comment by zuluecho9** [comment]
these aren't actually meant to give you links to places to set up NR. the instructions for SAML are meant to be farther down on the page. i think for this I will just make it the general Okta website, which might be less confusing. @mrytower05

**Comment by zuluecho9** [comment]
actually, on second thought, I think I might remove the links entirely, as that is confusing. ideally they'd just keep reading to read the actual instructions.

**Comment by zuluecho9** [comment]
changing this in https://github.com/newrelic/docs-website/pull/10154
