### ISSUE TITLE
azure-integrations-list page leads to a 404 page on Japanese site

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#1016]
### Description

Page renders 404.

### Steps to reproduce

1. Go to: https://docs-preview.newrelic.com/jp/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/

### Expected behavior

Page displays correctly in english as an page in JP that doesn't have a translation counterpart, should display in English

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

**Comment by jmiraNR** [comment]
@jpvajda @jerelmiller FYI.

**Comment by jpvajda** [comment]
I'm not seeing  an actual translated version of this page in our JP content.

https://github.com/newrelic/docs-website/tree/develop/src/i18n/content/jp/docs/infrastructure

**Comment by jmiraNR** [comment]
@jpvajda 
According to @jerelmiller it's an auto generated page. If not translated, it should still display in English under /JP/

**Comment by jpvajda** [comment]
@jmiraNR. gotcha.
