### ISSUE TITLE
Japanese [For more help] section links send to US Docs site

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#1017]
### Description

All the links sending to docs articles in the [For more help] section send the user to the US docs site.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/jp/docs/using-new-relic/welcome-new-relic/get-started/get-outage-information-statusnewreliccom
2. Click on any docs link within the [For more help] section (not developer link)

### Expected behavior

User is being linked to Japanese pages or pages on Japanese site.

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

**Comment by jmiraNR** [comment]
@jpvajda @jerelmiller FYI.

**Comment by jpvajda** [comment]
We can look at this next week after GA.
