### ISSUE TITLE
Redesigning Best Practices

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#10203]
## How can we make our docs better?
https://docs.newrelic.com/docs/new-relic-solutions/best-practices-guides/full-stack-observability/infrastructure-monitoring-best-practices-guide/

There is no longer a Health Map.

Another way to understand the relationship between APM and Infrastructure
For example, it must be Explorer, Related Entity, etc.

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

**Comment by austin-schaefer** [comment]
@akristen : Is this still an active issue? Should we add this to a sprint instead perhaps?

**Comment by qryuu** [comment]
Yes, this description still appears in the documentation.

> 6. View infrastructure data alongside APM data
The integration between [APM](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/welcome-new-relic-apm) and [infrastructure](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/getting-started/welcome-new-relic-infrastructure) monitoring lets you see your APM data and infrastructure data side by side, so you can find the root cause of problems more quickly, no matter where they originate. This allows users to view the performance relationship of your hosts and the applications running on them, allowing for quicker diagnosis of the issue and impact on the business' health.

> **Use health maps** to quickly spot any issues or alerts related to the health of your applications and how that connects to the supporting infrastructure. The first boxes starting from the top left are those that require your attention.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
