### ISSUE TITLE
Go Agent: Clarify ConfigFromEnvironment()

### ISSUE THREAD

**Issue by sdbedi** [newrelic/docs-website#10255]
It appears that not all Go Agent settings can be set from ConfigFromEnvironment() - TransactionEvents.MaxSamplesStored is one example. 

Can our docs clarify what settings are and are not available to be set this way? I believe the Node Agent's documentation does so.

**Comment by rhetoric101** [comment]
@sdbedi I am checking with our Go SMEs to see if they have some ideas about how to clarify what you can set with ConfigFromEnvironment().

**Comment by nr-swilloughby** [comment]
I'll review and update the docs to give the exact list of what can be configured via environment variables, but at the same time I'll review the code and work to get support for the ones that are missing unless there's some reason they can't or shouldn't be settable via the environment.

**Comment by nr-swilloughby** [comment]
On the issue of adding support for additional environment variables and/or a config file, we'd like to know if there's a need for either or both of those from our customers. Do you have any idea if that's the case and to what extent?

**Comment by sdbedi** [comment]
The context is that a customer reading the existing Go Agent documentation
might not know that ConfigFromEnvironment() doesn't work with everything.
The workaround is easy enough - set an environment variable manually, then
read it with Os.Getenv.

As such, I don't think it's necessary to actually change the functionality
- merely clarifying the documentation would be enough.

**Comment by rhetoric101** [comment]
@sdbedi we are going to be publishing an update to the Go configuration doc that should explain these functions (in https://github.com/newrelic/docs-website/pull/10264). So, I'm going to close this GitHub issue. If you have any questions, you can always reopen this issue.
