### ISSUE TITLE
Workflow Variables do not work in Teams referencing the example provided. 

### ISSUE THREAD

**Issue by richyta** [newrelic/docs-website#10305]
## How can we make our docs better?

* Is something confusing? Yes using the documentation provided  for deploying workflow variables in Teams doesn't not provide the outcome expected. Also followed a blog post put out by one of your engineers here https://newrelic.com/blog/how-to-relic/how-to-send-alerts-from-new-relic-to-microsoft-teams).

* Is something inaccurate or missing? Using provided info Variables does not achieve the expected results.

* Were you unable to complete a task? (What task?) That task was not completed because the workflow notification does not out the proper information in Microsoft Teams. Sending alerts to our Microsoft Teams channel does not work properly. 

Please see attached of what I see in our Microsoft Teams channel verses what I should see.

![Screenshot 2022-11-14 at 4 03 57 PM](https://user-images.githubusercontent.com/39923752/201793650-df20b313-ca40-4bc6-b0d7-c5ff11247943.png)

<img width="693" alt="Screen Shot 2022-10-28 at 6 35 46 PM" src="https://user-images.githubusercontent.com/39923752/201793502-ea9dc1e6-9763-4900-8ad3-9989851b7037.png">

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
