### ISSUE TITLE
Unable to add framework to multiple targets.

### ISSUE THREAD

**Issue by eeshwar-eventogy** [newrelic/docs-website#10348]
I'm using new relic for iOS Swift: [github.com/newrelic/newrelic-ios-agent-spm](https://github.com/newrelic/newrelic-ios-agent-spm)

After successfully adding it via SPM to one of my targets. I would usually (With other libraries such as Alamofire), go to the other target and add the framework under 'General' > 'Frameworks, Libraries and Embedded Content'. But for some reason, New Relic does not show up in this list, so It's impossible to use it on multiple targets.

Is there any way to fix this?

**Comment by x8a** [comment]
Hey, @eeshwar-eventogy! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
