### ISSUE TITLE
The doc on NRQL limits needs to be updated

### ISSUE THREAD

**Issue by EricCapponi** [newrelic/docs-website#10350]
From @zuluecho9: looking into this one. 

## Limits on number of data points inspected

The limits were changed but part of the doc was not updated:

300 billion data points inspected (equivalent to a sustained rate of 10 billion data points inspected per minute)

should read

300 billion data points inspected (equivalent to a sustained rate of _**20**_ billion data points inspected per minute)

**Comment by zuluecho9** [comment]
think we fixed this with https://github.com/newrelic/docs-website/pull/10388. thanks for raising that @EricCapponi !
