### ISSUE TITLE
Clarify Agent Update Policy v EOL

### ISSUE THREAD

**Issue by sdbedi** [newrelic/docs-website#10385]
## How can we make our docs better?

There is an update policy that recommends updating New Relic agents every 90 days or so:
https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/install-configure/update-new-relic-agent/

There is also an EOL policy, which describes when specific version are unsupported; here is the Java Agent for example: 
https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/java-agent-eol-policy/

These are different things, but it is possible to get confused between the two. Can we clarify both docs to highlight the distinction?

**Comment by rhetoric101** [comment]
@sdbedi thanks for your comment about the relationship between the EOL doc and the agent upgrade doc. Our docs team will take a look at how we might clarify these.

**Comment by bradleycamacho** [comment]
Hiya @sdbedi, I'm actively working on these docs and this is a great callout. I'm not going to make any changes at this exact moment as things are in flight, but I will take note on this and make sure we implement a fix when things go live. Thank you!
