### ISSUE TITLE
Translate Nav string

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#10414]
## Description

The "See our 500+ quickstarts" in the Nav is not translated. Could we make that string translatable?

## Steps to reproduce

1. Go to ['https://docs.newrelic.com/kr/'](https://docs.newrelic.com/kr/)
2. Check the bottom of the Nav panel

## Expected behavior

Message is translated on all global sites.

## Screenshots

<img width="430" alt="Screen Shot 2022-11-21 at 2 18 10 PM" src="https://user-images.githubusercontent.com/71030271/203162528-d21faec9-b6c1-4ebc-84c1-bac2ff92adc7.png">

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
