### ISSUE TITLE
Feedback: Introduction to dashboards - test

### ISSUE THREAD

**Issue by mb-newrelic** [newrelic/docs-website#1056]
### Tell us more about your feedback

We're glad to hear this doc was helpful! We've recorded your feedback. Help us 
improve other content by telling us what worked and what didn't:

* What worked well in this doc?
* How could we make this doc even better?
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

Just testing the live site.

**Comment by bradleycamacho** [comment]
Closing test issue
