### ISSUE TITLE
This is a bug! Please fix!

### ISSUE THREAD

**Issue by calex53** [newrelic/docs-website#1058]
### Steps to reproduce

1. Go to '...' https://github.com/newrelic/docs-website/blob/develop/README.md
2. Click on '....' LINK TO STYLE GUIDE
4. See error 404 error: https://github.com/newrelic/docs-website/blob/readme-update/STYLE_GUIDE.md

### Expected behavior
I expected to be taken to the Style Guide.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by bradleycamacho** [comment]
@calex53 Thanks for the bug report! I just pushed a PR fixing this issue, it should be get merged in a few minutes!
