### ISSUE TITLE
The navigation to the Duplicate Transaction page no longer exists

### ISSUE THREAD

**Issue by mcaronnewrelic** [newrelic/docs-website#10605]
## Description

We need to change the text on the page that refers to how to navigate to an old Insights page. 
"To avoid duplicate events, disable collection for each of the duplicate app names:

Go to [one.newrelic.com](https://one.newrelic.com/all-capabilities), then select More > Manage Insights Data.
Toggle data collection on/off for duplicate app names, then save."

## Steps to reproduce

1. Go to '[(https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/app-naming/use-multiple-names-app/#events/)]'

## Expected behavior

I believe Drop Rules is the new preferred method of removing duplicate transactions. The Insights page is still accessible if you know the direct URL to use, but the method of navigating to the page described in this doc page no longer exists. We should either update the method of navigating to the Insights page (not easy, perhaps we can refer to a URL pattern template to use and ask the user to input their account number, https://insights.newrelic.com/accounts/<accountnumber>/manage/summary) or remove the reference to the page and favor the Drop Rules as a GraphQL mutation for accomplishing this same task.

**Comment by zuluecho9** [comment]
thanks @mcaronnewrelic. if you want to see some of the work I did for this, it's in https://github.com/newrelic/docs-website/pull/10949/files
