### ISSUE TITLE
NRQL math page needs updates

### ISSUE THREAD

**Issue by thezackm** [newrelic/docs-website#10652]
context: [NRQL math](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-math-using-select/) page

 * In the `clamp` and `rounding` sections, we're showing an old Seldon chart image
 * Throughout this document; there are multiple functions that are not documented on the more verbose [NRQL clauses and functions](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/) page. I think it would make sense to ensure the functions are all documented in a single page and pages like this are treated more like "example / best-practice" type of documentation. It's confusing to try and piece together a NRQL query using functions from multiple pages.

**Comment by jeff-colucci** [comment]
Hi @thezackm, thanks for your feedback! I agree about the disjointed state of some of the docs. I'm currently revamping the NRQL docs and I plan on fixing both the syntax and math pages once I get to that phase. As far as the screenshots, I can make the changes to update those easily. If you can provide screenshots that you think should be there I can get it done and merged in the same day, otherwise I will put it on my list of things to do on a future sprint and get it done there.

**Comment by thezackm** [comment]
@jeff-colucci - thanks for the info; here's a few shots using the current UI in both light and dark; hope that helps!

```sql
FROM SystemSample SELECT
average(cpuPercent) AS 'raw',
round(average(cpuPercent), .01) AS 'rounded',
floor(average(cpuPercent)) AS 'floor',
ceiling(average(cpuPercent)) AS 'ceiling'
TIMESERIES
```

![round-floor-ceil-dark](https://user-images.githubusercontent.com/30831476/206735994-0fe15412-0360-473f-b097-1e8cb1db9424.jpg)
![round-floor-ceil-light](https://user-images.githubusercontent.com/30831476/206736007-c86b6bf0-4ca6-4a8f-8891-3fb32e88083e.jpg)


```sql
FROM SystemSample SELECT
average(cpuPercent) AS 'raw',
clamp_min(clamp_max(average(cpuPercent), 98), 96) AS 'clamped'
TIMESERIES
```

![clamp-light](https://user-images.githubusercontent.com/30831476/206736012-390512e6-d4a1-4f19-9594-f59226151d62.jpg)
![clamp-dark](https://user-images.githubusercontent.com/30831476/206736018-5438bcf7-772a-4e2c-a77b-38c7683f5446.jpg)

**Comment by jeff-colucci** [comment]
@thezackm I'm going to go ahead and change the screenshots out as part of [this ticket](https://github.com/newrelic/docs-website/pull/10690). If you can just review to make sure I got the screenshots right I can merge it in and close both these tickets with a future indicator to look at the Math and Syntax docs in an upcoming sprint.

**Comment by thezackm** [comment]
@jeff-colucci - thanks! added my review with some notes on the other PR
