### ISSUE TITLE
Collapsers do not automatically open through anchor links

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#1065]
### Description

Clamshell collapsers should automatically open if someone navigates to a page through a URL with an anchor link. For example: 
`https://docs.newrelic.com/docs/integrations/kubernetes-integration/troubleshooting/get-logs-version#logs-pod-kubestatemetrics`

These collapsers are not opening when they should. 

### Steps to reproduce

1. Go to [this page](https://docs.newrelic.com/docs/integrations/kubernetes-integration/troubleshooting/get-logs-version#logs-pod-kubestatemetrics)
2. One of the collapsers should automatically open.

**Comment by austin-schaefer** [comment]
Lot of links relying on this pattern. And support uses this heavily to direct users to look at specific sections of a doc. This would be a nice one to prioritize soon-ish.

**Comment by austin-schaefer** [comment]
Miiiight be able to re-use some stuff from @jerelmiller 's work on #155 ?

**Comment by jerelmiller** [comment]
This one requires a bit of tweaking to the collapser state when rendered. I might try and hit this one since I'm already doing some work in the theme.
