### ISSUE TITLE
Issue: Install the Kubernetes integration using Helm

### ISSUE THREAD

**Issue by mosen** [newrelic/docs-website#1080]
### Tell us what you need

There are a few misspelt key names in the documentation for the Helm chart

* Incorrect spelling for keys used in Kubernetes Integration using Helm:
* **serviveAccount.create** should be **serviceAccount.create**
* **serviveAccount.name** should be **serviceAccount.name**
* **serviveAccount.annotations** should be **serviceAccount.annotations**

Validated against Helm chart newrelic-infrastructure @ 2.3.1

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/install-kubernetes-integration-using-helm
* **OS**: Mac OS 10.15
* **Browser**: Firefox 86.0
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey @mosen sorry for the late response. Looks like this has been resolved, so I'm closing this issue. Feel free to let us know if you have any other issues!
