### ISSUE TITLE
"Baseline" → "Anomaly" in screenshots

### ISSUE THREAD

**Issue by founddrama** [newrelic/docs-website#10803]
## How can we make our docs better?

On: https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/other-condition-types/create-anomaly-alert-conditions/

There are two screenshots that have two problems:

1. They have "Baseline" for the threshold type (it should have "Anomaly")
2. They still show "Outlier" (which have been deprecated for some time now)

**Comment by homelessbirds** [comment]
Thank you for flagging! This has been done in the PR: https://github.com/newrelic/docs-website/pull/10882

**Comment by founddrama** [comment]
@homelessbirds 👋🏼 I'm unsure why this was closed? The specific images cited in this issue do not appear to be part of PR #10882 ... which itself is still showing open and unmerged. The out-of-date images are still showing here: https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/other-condition-types/create-anomaly-alert-conditions/
