### ISSUE TITLE
Issue: Debian icon broken - Requirements for the infrastructure agent

### ISSUE THREAD

**Issue by josemore** [newrelic/docs-website#1082]
* Debian icon appears broken / missing in this link: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent
* **OS**: Mac OS 11.2.1
* **Browser**: Chrome 88.0.4324.192
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Fixed in #1086. Thanks for reporting this, @josemore!
