### ISSUE TITLE
doc: AWS Lambda Extensions Telemetry API Integration is not actually an integration

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/docs-website#10824]
# Summary

The [AWS Lambda Extension Telemetry API Integration](https://github.com/newrelic/docs-website/blob/5c6698032dca0a5ef4638f889b5d0b382b1b150e/src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-telemetry.mdx) doc contains some discrepancies.

## Issues

- In step 4, the mentioned layer, AwsLambdaExtension, does not exist in the [list of layers](https://layers.newrelic-external.com/).
- In step 5, the `LICENSE_KEY` environment variable does not match the format of our [other layers](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/#env-var) which use a `NEW_RELIC_LICENSE_KEY` environment variable.
- The **Find your data** section references the old UI.
- MELT data is not tied to an entity. It should be tied to an existing Serverless -> Lambda function entity, which does depend on an AWS integration (either api polling or metric streams) to do the entity synthesis for the AWS/Lambda service.

## Expected Behavior

Since this doc exists in the AWS integrations list section, one would expect that it [connects an AWS service to New Relic](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/connect-aws-new-relic-infrastructure-monitoring/) on an API polling integration.

Since this doc deals with layers, I expect to find it as a subsection of the [Step 4: Instrument your own functions](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/) doc.

## Current Behavior

[No AWS service exists](https://aws.amazon.com/products/?aws-products-all.sort-by=item.additionalFields.productNameLowercase&aws-products-all.sort-order=asc&awsf.re%3AInvent=*all&awsf.Free%20Tier%20Type=*all&awsf.tech-category=*all&aws-products-all.q=lambda&aws-products-all.q_operator=AND) for Lambda Extensions Telemetry API, so this doc is not connecting an AWS service to New Relic via an API polling integration. No AwsLambdaExtension layer exists, so it is impossible to proceed with the installation steps.

**Comment by 4demos** [comment]
"In step 4, the mentioned layer, AwsLambdaExtension, does not exist in the [list of layers](https://layers.newrelic-external.com/)." - currently it is not indeed since it didn't went through official release procedure. But we're working on that and expect it to be there in a nearby future. @a-sassman, may be we still need to put **To be done** ?

**Comment by 4demos** [comment]
LICENSE_KEY -> NEW_RELIC_LICENSE_KEY replaced (in both the docs and the code, the code still needs to be released)

**Comment by 4demos** [comment]
"The Find your data section references the old UI" - made adjustments for the new UI

**Comment by 4demos** [comment]
"MELT data is not tied to an entity. It should be tied to an existing Serverless -> Lambda function entity, which does depend on an AWS integration (either api polling or metric streams) to do the entity synthesis for the AWS/Lambda service." - here we're very different. Data come not just from a lambda function but also platform and extension. The extension is stand alone (no api polling or metric streams), it's a new "integration". We eventually could add it to Serverless as a new category but it's not there yet.

**Comment by keegoid-nr** [comment]
Thanks @4demos for considering the issues raised here.

Looks like there is already a [PR related to this issue](https://github.com/newrelic/docs-website/pull/10822#discussion_r1053874316). Ongoing discussions are also happening in Slack about how this could be an integration. It is making more sense assuming we can add a "Lambda Telemetry API" service to the integration list.

**Comment by rhetoric101** [comment]
I am closing this GitHub issue because it seems to have been addressed in this PR: https://github.com/newrelic/docs-website/pull/10822#discussion_r1053874316
