### ISSUE TITLE
Search result for Data Dictionary takes you to a 404.

### ISSUE THREAD

**Issue by maju6406** [newrelic/docs-website#1087]
### Description

I wanted to look up an entry in the Data/Attribute Dictionary. So I searched for dictionary in the docs search. The search result took me to a 404.

### Steps to reproduce

1. Go to docs.newrelic.com
2. Click on the search bar at the top of the page.
3. Search for "dictionary"
4. Click on the second result "New Relic data dictionary"
5. It takes you to https://docs.newrelic.com/attribute-dictionary/pageview (404 error).

### Expected behavior

I should be taken to the Data Dictionary https://docs.newrelic.com/attribute-dictionary

**Comment by jerelmiller** [comment]
Good catch! It seems we forgot to add redirects for events.

**Comment by mmfred** [comment]
@jerelmiller - is that something you need the tech writers to do, or will Devex handle that?

**Comment by jerelmiller** [comment]
@mmfred DevEx will need to handle this as we'll want to automatically create redirects for all events, which we will do under the hood. It seems we did it only for attributes, but not events themselves 😅

**Comment by mmfred** [comment]
Great - thanks @jerelmiller!
