### ISSUE TITLE
Wrong labels, duplicate header on "Create issue" button

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1096]
### Description

Two (possibly three?) issues with the *Create issue* button on each page:

* It doesn't apply the `feedback` and `content` labels, which we need to ensure writers are tracking against the right issues.
* It seems to bring in environment info somewhat inconsistently (might be due to user ad-blockers or similar though)
* It's got a duplicate header
![image](https://user-images.githubusercontent.com/55203603/109712519-facadc00-7b54-11eb-9fee-97254da46e5a.png)

### Steps to reproduce

1. Go to any doc
2. Click on *Create issue*

### Expected behavior

* Apply `feedback` and `feedback-issue` labels label to issues created from docs site.
* Don't duplicate header
* Include environment info where possible

**Comment by austin-schaefer** [comment]
FYI @jpvajda

**Comment by jpvajda** [comment]
I'll look into this one, as I think we need to change the theme component here: 

https://github.com/newrelic/gatsby-theme-newrelic/blob/e818cc0f9a767d79e0054e81c1b[…]kages/gatsby-theme-newrelic/src/components/CreateIssueButton.js

**Comment by jpvajda** [comment]
@austin-schaefer so at this stage of filing an issue we don't know if the user is actually reporting a content bug or a code bug, so can we just be more generic and add a feedback label to these issues triggered from click of this button?

**Comment by jpvajda** [comment]
@jerelmiller it seems the developer site isn't using the global theme component for the createIssuebutton? Is there a reason for that?

dev site is on "@newrelic/gatsby-theme-newrelic": "^1.25.0", and docs site is on "@newrelic/gatsby-theme-newrelic": "^1.32.3" can i bump the theme on the dev site? or do we do this for a reason? 

I'd like to fix this problem reported by Austin and have both sites use the newest `createIssuebutton` component version

**Comment by austin-schaefer** [comment]
@jpvajda : I'm fine just starting with a `feedback` label. If we find that 90% of the feedback or something is for content, we can always add that as a second pre-filled label in future.

**Comment by jerelmiller** [comment]
> Is there a reason for that?

Mostly just that we were focused on the docs launch, so we didn't focus energy on the developer site. We should get this upgraded as well.

**Comment by jerelmiller** [comment]
@austin-schaefer just to confirm, we want both the feedback buttons AND the create issue button to add a `feedback` label when opening issues correct?

Once updated, the labels would look like this. Can you confirm this is correct?

**Feedback "yes"**
- `content`
- `feedback`
- `feedback-positive`

**Feedback "no"**
- `content`
- `feedback`
- `feedback-negative`

**Create issue**
- `content`
- `feedback`

My personal take on this is that with the updated labels, it really muddies the difference between the create issue and feedback buttons since this is now all feedback (in terms of labels). We had initially designed the create issue button to be more of a bug report button so that people can tell us something that looked wrong or off, where the feedback buttons were really meant for that: feedback on what was good/bad for the page they were viewing.

I'm totally happy to make this change, but just wanted to call out that now we've got 3 buttons that serve more or less the same purpose after this. Is this correct?

**Comment by austin-schaefer** [comment]
@jpvajda Yep, I think that's all correct. I agree it muddies the waters, but I'm already seeing users not really process those distinctions. Might mean we want to reconsider this down the line, but I think for now I'm fine just updating labels and seeing how things sort out over the next month or so.

**Comment by jpvajda** [comment]
Create Issue should not be labeled content and feedback it's not just about content issues or gathering feedback

The Create issue should be:

- `bug` 
- `content`
- `eng`

As it's purpose is to report an issue with the site, after triage the label can be corrected if it's just a content problem, but this isn't site feedback, it's bug triaging.

**Comment by austin-schaefer** [comment]
@jpvajda : I think content issues are going to dramatically outnumber site issues, particularly for issues that start from the docs sidebar. I'm fine, though, if we just want to go with a `feedback` label. I do need that label, though, because this is how I'm going to monitor and report on issues.

**Comment by austin-schaefer** [comment]
We have `feedback-positive` and `feedback-negative` to help differentiate issues started from the yes/no buttons.

**Comment by jpvajda** [comment]
how about: 

The Create issue has one label then, based on `type`

`feedback-issue`

**Comment by austin-schaefer** [comment]
That works. Can we do both `feedback` and `feedback-issue`, just so I can see allll the feedback in one place?

**Comment by jpvajda** [comment]
@austin-schaefer oh yeah, that works!

**Comment by jerelmiller** [comment]
FYI, the duplicate headers have been fixed (https://github.com/newrelic/gatsby-theme-newrelic/pull/301). Once we have the updated labels, we can close this issue.

**Comment by jpvajda** [comment]
@jerelmiller `and my ax` currently working on that now. 😄

**Comment by jpvajda** [comment]
As a note:  I was able to get system data testing:

```
* https://developer.newrelic.com/build-apps/set-up-dev-env
* **OS**: Mac OS 10.15
* **Browser**: Firefox 86.0
* **Device**: Unknown
```

**Comment by jpvajda** [comment]
https://github.com/newrelic/gatsby-theme-newrelic/pull/311/
