### ISSUE TITLE
Clarify Transaction Naming When Segments

### ISSUE THREAD

**Issue by sdbedi** [newrelic/docs-website#10965]
It appears that when viewing a transaction breakdown, any time that is not attributable to a specific segment will be labelled with the overall transaction name - this is the case even when only some of the transaction is represented by segments. As such, the transaction name is simply a residual in this instance, rather than a true total.

However, the documentation on transaction naming does not clarify this, and this can be a possibility for confusion:
https://docs.newrelic.com/docs/apm/transactions/intro-transactions/transactions-new-relic-apm/

**Comment by x8a** [comment]
Hey, @homelessbirds! Could you have a look at this issue? Thanks!

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. We've created a Jira ticket to address this issue.
