### ISSUE TITLE
Clarify key types and expected response from sending custom events

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/docs-website#11033]
## How can we make our docs better?

Please see this feedback from a user of the Events API. Goal is to clarify required key types in the 'starting' section of the documentation.

* Is something confusing?

Attempting to send custom events to the endpoint with a USER key failed silently. API returns `{}` and there is nothing in `NrIntegrationError`.

* Is something inaccurate or missing?

First, it should show what a success response looks like in the example. That would have made it clear to me that getting a {} response meant that it probably failed.

Here is a successful send with an ingest key, along with the expected response:
```
% gzip -c sample-event.json | curl --data-binary @- -X POST -H "Content-Type: application/json" -H "Api-Key: ${NEW_RELIC_API_KEY}" -H "Content-Encoding: gzip" https://insights-collector.newrelic.com/v1/accounts/${NEW_RELIC_ACCOUNT_ID}/events
{"success":true, "uuid":"UUID"}
```

What I should've done next was to try "curl -i", which I didn't think of at the time. If I had done that, I would've seen a 403 response code, which would have led me to 403 in the "troubleshooting" section, where I would have seen it call out that user keys do not work.

I think the documentation should a) suggest using `curl -i` if you don't get a "success" response, and b) also more specifically call out the key type in the basic "How to use" section. 

Where it now says "1. Get a license key for the account you want to report data to" it could say "1. Get a key of type ingest - license for the account you want to report data to. User keys will not work."

* Were you unable to complete a task? (What task?)

Could not send to Events API until the key type issue was worked out.

**Comment by gitcos** [comment]
Hello, I'm the user who submitted the above feedback.  Documentation improvements I suggested above would have saved me a lot of time when I first tried to use this API a few weeks ago.  Commenting here so that I will see when you update this issue.

**Comment by homelessbirds** [comment]
@gitcos thanks for submitting this feedback! We created a ticket for this and have added it to our backlog. We appreciate you bringing this to our attention.
