### ISSUE TITLE
Is this a typo?

### ISSUE THREAD

**Issue by EricCapponi** [newrelic/docs-website#11088]
Should:
If stopCurrentInteraction:  is called, the return value is an interactionIdentifier that must be passed to stopCurrentInteraction: . But it's not required to call stopCurrentInteraction:  after calling start because startInteractionWithName:  will eventually complete intelligently.

Read:
If **_startInteractionWithName_**:  is called, the return value is an interactionIdentifier that must be passed to stopCurrentInteraction: . But it's not required to call stopCurrentInteraction:  after calling start because startInteractionWithName:  will eventually complete intelligently.

**Comment by akristen** [comment]
Hi @EricCapponi, what doc is this text found in?

**Comment by EricCapponi** [comment]
This is the document:
https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/start-interaction/

**Comment by akristen** [comment]
Thanks for providing this doc! I'll look into this and get it updated for you!

**Comment by akristen** [comment]
Hi @EricCapponi Wanted to let you know that this was addressed in this PR: https://github.com/newrelic/docs-website/pull/11406 :)
