### ISSUE TITLE
Issue: Violation event attributes

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#1109]
### Tell us what you need

* If you've found something inaccurate, what is it?

The name of the event type is missing in this section. 

Please update the docs to include the name of the eventType:  NrAiIncident

**Comment by rhetoric101** [comment]
@dralph3344, thanks for entering this issue. With this new routine, it looks like the name of the document is not automatically included in the in the request. Could you add the name of the document that needs to be updated?

**Comment by rhetoric101** [comment]
This is part of the work in https://newrelic.atlassian.net/browse/DOC-6559.

**Comment by zuluecho9** [comment]
Closing this because we have this jira. https://newrelic.atlassian.net/browse/DOC-6559

**Comment by austin-schaefer** [comment]
Reopening since linked Jira is still open
