### ISSUE TITLE
Instrumentation > Ability to track where the sign-up clicks occurred

### ISSUE THREAD

**Issue by tariqahmed** [newrelic/docs-website#1113]
We'd like to make sure that either through Google Analytics or Tessen, we can accurately detect where on the page someone clicks on the sign-up link.

At a basic level in the header or body. But even better, when present, ID of the button/link/text/container.

**Comment by tariqahmed** [comment]
Clinton Langosch:
"believe we do capture the signup_click in the global header via a PageAction"

That assumes the signup_click only occurs from the header. Thinking about it - that's likely to lead to confusion as one will assume the signup_click event is the authoritative way of tracking all sign-up clicks by virtue of it's name.

Just need to know where that click occurs.

Thx.

**Comment by jpvajda** [comment]
@tariqahmed Can you clarify what data is currently available to you and where you are viewing it?  You can review what is currently instrumented here: https://github.com/newrelic/docs-website/wiki/Event-Data--and--Instrumentation

It sounds like we are tracking the sign-up button ciick as a page action but reading the wiki I'm not 100% sure what is being tracked, It would be helpful to look at this from the analysis side of things then diiscuss what is missing.  cc @caylahamann

**Comment by jpvajda** [comment]
Making a `P1` Bug as tracking sign ups is very important and that was something that was in scope for our GA.

**Comment by jpvajda** [comment]
changing to a P2, as this isn't mission critical functionality, but we'll want to take a look at it this week
