### ISSUE TITLE
Attribute name has changed

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#11199]
On this [usage queries page](https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts/#estimated-cost) there is a reference to `FullUsersBillable`. I believe this attribute is now called `FullPlatformUsersBillable`. 

The queries and refernces need updating (assuming im correct of course!)

**Comment by zuluecho9** [comment]
thank you @jsbnr , fixing that

**Comment by zuluecho9** [comment]
fixing in https://github.com/newrelic/docs-website/pull/11202
