### ISSUE TITLE
Custom URL for the site on Amplify

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#114]
## Description
We would like to add a custom domain for the new docs site: [docs-preview.newrelic.com](docs-preview.newrelic.com). This will require some DNS work in _Amplify_ and, possibly, some cross-team collaboration.

**Comment by jpvajda** [comment]
Confirmed this is the correct URL to use with @austin-schaefer

**Comment by zstix** [comment]
We have the site properly building on Amplify: https://main.d1vx4w5vgyla4s.amplifyapp.com/

I've started working with our ELB team to set up the domain. Will update here when that work is complete!

**Comment by zstix** [comment]
https://docs-preview.newrelic.com/
