### ISSUE TITLE
[NR1 Help XP] Handle missing components in nr1-help-xp and rendering inline jsx

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#1142]
## Summary 
Handle TechTiles and TechTile grid components in the nr1-help-xp. 
Additionally, render the inline jsx for components. There's support for this in a PR open #1081 to render jsx as children. This captures the work that needs to be done to support that change.

**Comment by jpvajda** [comment]
@caylahamann can you explain the impact to the user on this one? Also it seems like it's in progress based on #1081 is that correct?

**Comment by caylahamann** [comment]
Yeah! The impact is that TechTiles are not rendering (we only use these on a few pages, but if the user goes to that page they just won't see them) and for areas where we use jsx for titles in Collapsers, we currently only extract the text. The reason why this was occurring is because for `TechTiles` we weren't handling them, so when they got turned into HTML they just disappeared because the parser didn't understand what they were. For the Collapsers, it would turn that jsx into an object, and then we would get something that looks like this appearing: 
<img width="689" alt="109527533-c508f300-7a81-11eb-972b-0bd1fe460423" src="https://user-images.githubusercontent.com/38332422/110004997-06014180-7ce6-11eb-8039-7b78d0605610.png">
We provided a temporary fix for the Collapser titles by just extracting the text in #1040 

So there's two parts to the problem: 
1. We have to make sure the way that we generate our HTML that we keep that inline JSX and it gets put into a format that can be rendered in the help-xp
2. We have to support the changes in the HTML that is being served from the docs site in the help-xp and make sure it's rendering the way we want

That PR that is up and has been approved addresses the first part of the problem, which takes that inline jsx and makes it a child of the component with a special class on it. But before we merge it in we gotta make sure that the help-xp is able to take those child components and turn them into titles. Additionally, we want to make sure that the TechTiles

### TechTiles not rendering 
#### Help XP
<img width="849" alt="Screen Shot 2021-03-04 at 12 23 38 PM" src="https://user-images.githubusercontent.com/38332422/110003970-ec132f00-7ce4-11eb-95f6-dca6ec757a14.png">

#### Docs Site
<img width="770" alt="Screen Shot 2021-03-04 at 12 23 44 PM" src="https://user-images.githubusercontent.com/38332422/110003981-ef0e1f80-7ce4-11eb-8a7d-95fd797dd69c.png">

### Collapser Inline JSX 
#### Help XP
<img width="631" alt="Screen Shot 2021-03-04 at 12 26 06 PM" src="https://user-images.githubusercontent.com/38332422/110004120-14029280-7ce5-11eb-9309-c72caf7c4dc4.png">

#### Docs Site
<img width="759" alt="Screen Shot 2021-03-04 at 12 26 25 PM" src="https://user-images.githubusercontent.com/38332422/110004135-1664ec80-7ce5-11eb-87f7-c35a4d40ebf9.png">

That PR (#1081) the first part of the problem, but before I can merge it in we need to handle the second part of the problem, because otherwise we'll get some really wonky looking stuff in the help-xp for Collapsers and TechTiles. This ticket is meant to capture that work! I've already begun working on it, but it's all in the help-xp repository!

Hope that helps!
