### ISSUE TITLE
Mention of expert services - do we still have this service?

### ISSUE THREAD

**Issue by northyg** [newrelic/docs-website#11435]
## How can we make our docs better?

* This page references expert services but it was my understanding we don't have that team anymore. I could be wrong, but this is potentially misleading. This part could use clarification and adjustment if required. 

> Generally Available products are fully tested with the compatible environments outlined in New Relic Documentation, and we're here to help you through issues that may arise with our Products within these compatible environments and frameworks. We cannot support installation or configuration of our Products in environments or frameworks that do not meet established compatibility requirements. If you're looking for help customizing New Relic for your particular environment, [New Relic's Expert Services](https://newrelic.com/expertservices) is a team of highly skilled consultants that can assist with unique configurations or environments.

https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings/#enviros

https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings/#consult

**Comment by ashutosh887** [comment]
I would like to work on this

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.

**Comment by paperclypse** [comment]
It looks like we still have expert services on some level, as mentioned on our public site here: https://newrelic.com/expertservices
