### ISSUE TITLE
Why are you so cool?

### ISSUE THREAD

**Issue by tangollama** [newrelic/docs-website#1144]
TBH, I just wanted a way to publicly recognize how cool this work is. Ya'll rock for making this happen. Well. Done. Truly.

![image](https://user-images.githubusercontent.com/929261/109906405-6eacd780-7c6e-11eb-94a3-51c29607ad6d.png)

**Comment by jerelmiller** [comment]
@tangollama!!!!! So great to hear from you! I hope life is treating you well in your new gig.

Thanks so much! This brought me some much needed joy today 🙂

**Comment by austin-schaefer** [comment]
Nice to see you @tangollama and I hope you're doing real well!

**Comment by urbiz-nr** [comment]
Thank you @tangollama ! :)

**Comment by jpvajda** [comment]
Getting props via a PR is my new favorite thing! Thanks @tangollama I hope you are well!
