### ISSUE TITLE
Data dictionary not filtering to specific event

### ISSUE THREAD

**Issue by urbiz-nr** [newrelic/docs-website#1147]
### Description

(Reported by Ramon Guiu).

In the [monitoring data doc](https://docs.newrelic.com/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data), the events' links take you to the top of the [dictionary](https://docs.newrelic.com/attribute-dictionary/) instead of the specific event description.

This worked just fine in the old site (confirmed by Ramon).

We should check if this is happening someplace else.

**Comment by austin-schaefer** [comment]
A bit more on this: The URL parameters have changed for events. For example, to permalink to the SystemSample event:

* Old site: https://docs.newrelic.com/attribute-dictionary?attribute_name=&events_tids%5B%5D=8407
* New site: https://docs.newrelic.com/attribute-dictionary/?event=SystemSample

@DevEx: If there's a way to do redirects for this, that would be lovely.

If not, let us know and we can do a site sweep to fix links manually. That wouldn't account for off-site links but it would solve much of it.

**Comment by jerelmiller** [comment]
@austin-schaefer unfortunately we don't have the old event ids, which look like are needed from the old site (I see `events_tids` query param used). Because of this, we unfortunately won't be able to resolve those links automatically. We'll need to do a site sweep and get those updated.

**Comment by jpvajda** [comment]
so I'm trying to understand:

is the proposed solution that an engineer  does this our a docs content person?

>  we can do a site sweep to fix links manually

I think in this issue we need more articulation around if this is an eng-only problem.

**Comment by jpvajda** [comment]
sounds like a content issue, adding to the docs team project board.

**Comment by zuluecho9** [comment]
I fixed some links in prominent docs today and made a jira to fix the remainder https://newrelic.atlassian.net/browse/DOC-6784
