### ISSUE TITLE
Screenshot and topic in docs not related - Wrong screenshot 

### ISSUE THREAD

**Issue by mferry557** [newrelic/docs-website#11483]
The3rd  screenshot in the Dashboard overview is a duplicate screenshot of the Baseline reports rather than the Browser tab being referred to.  FYI  See the text description above the image and the footnote text below the image.

![image](https://user-images.githubusercontent.com/124806481/218190112-bc8a1b6a-6247-471c-a547-51ecbdeea581.png)

**Comment by rhetoric101** [comment]
@mferry557 I created this internal Jira (NR-87982) to track the progress on this issue. I'm going to close this GitHub issue since we'll track this in Jira.
