### ISSUE TITLE
A link in the "forcast your ingest data" in the first paragraph is broken. 

### ISSUE THREAD

**Issue by mferry557** [newrelic/docs-website#11482]
![image](https://user-images.githubusercontent.com/124806481/218189787-54d6b8df-235f-4f81-aea0-e45fda74a297.png)

**Comment by rhetoric101** [comment]
@mferry557 I just tried the "Forecast your ingest data" link on the "Baseline your data ingest" page. The link loaded as I'd expect: https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/operational-efficiency/data-governance-forecast-ingest-guide/

Could you try this again?
