### ISSUE TITLE
Confluent quickstart reference for Kubernetes

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/docs-website#11538]
## How can we make our docs better?

For the Confluent quickstart at https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/collector-configuration-examples/opentelemetry-collector-kafka-confluentcloud/, it would be helpful to have directions for deployment to Kubernetes.

**Comment by rhetoric101** [comment]
@maxlemieux thanks for the suggestion! I'm looking around to find someone who can supplement this doc with Kubernetes information.

**Comment by rhetoric101** [comment]
@maxlemieux due to personnel changes, this has been sidelined, but I've created this Jira to keep track of your request: NR-152636)
