### ISSUE TITLE
Issue: PHP agent installation: Non-standard PHP (advanced)

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#1154]
### Tell us what you need

I have found a broken link that would allow customers to download the script to manually install the PHP Agent.

The link https://docs.newrelic.com/sites/default/files/atoms/files/PHP-manual-install-script-master_0.zip is bringing the customers to a 404 page.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/php-agent/advanced-installation/php-agent-installation-non-standard-php-advanced
* **OS**: iOS
* **Browser**: Chrome
* **Device**: Mac

**Comment by mmfred** [comment]
Thank you for letting us know @rodrigo-corgozinho - we'll try to get that fixed.

**Comment by mmfred** [comment]
I looked into this and filed this ticket: https://github.com/newrelic/newrelic-php-agent/issues/117

We'd prefer that the PHP agent team hosts this script. However, I'll attach it here so you can use it as needed. The link will be broken until I hear back from them.
[PHP-manual-install-script-master_1.zip](https://github.com/newrelic/docs-website/files/6087024/PHP-manual-install-script-master_1.zip)

**Comment by mmfred** [comment]
I heard back from the PHP agent team. The script is no longer supported and they recommend removing it, and references to it, from the page. That fix is in the works. Thanks for reporting this. It helps us keep the docs up to date.
