### ISSUE TITLE
Issue: Enable serverless monitoring using the Lambda layer

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#1158]
Would be helpful that the documentation highlights all the available environment-variables for configuring and controlling module behavior.  While the helper-cli might be used by some clients; most enterprises will have their own CI/CD process and explicit definition of available controls would be helpful.

**Required Config:**
NEW_RELIC_LICENSE_KEY  ||  NEW_RELIC_LICENSE_KEY_SECRET
NEW_RELIC_LAMBDA_HANDLER
NEW_RELIC_ACCOUNT_ID

**Optional Config:**
NEW_RELIC_LAMBDA_EXTENSION_ENABLED            (defaults true, false activates legacy cloudwatch-log-output)
NEW_RELIC_EXTENSION_SEND_FUNCTION_LOGS   (defaults false)
NEW_RELIC_EXTENSION_LOG_LEVEL                          (defaults INFO)
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED         (defaults false)

**Open Question:  Are these environment variables still required in the deployment of DT within Serverless?**
NEW_RELIC_PRIMARY_APPLICATION_ID
NEW_RELIC_TRUSTED_ACCOUNT_KEY

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-using-lambda-layer
* **OS**: Mac OS 11.2.2
* **Browser**: Chrome 88.0.4324.192
* **Device**: Unknown

**Comment by jpvajda** [comment]
stale bot closed this so re opening and added a content label for the docs team to scope this out.

**Comment by rhetoric101** [comment]
@GaPeppy, we are looking at some ways to improve the environment variables for those who don't use the CLI-helper. We're going to track our work in DOC-7242.

**Comment by urbiz-nr** [comment]
Docs are being updated in #3758.

**Comment by urbiz-nr** [comment]
Closed #1158 via #3758.
