### ISSUE TITLE
Support <var>, <mark>, and <a> tags inside code blocks

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#116]
## Summary

Some of the pages in the docs site include code blocks with embedded `<var>`, `<mark>` `<a>` and `<pre>` tags. Unfortunately our `CodeBlock` component, nor the fenced code blocks support the additional HTML tags, since these render as actual text inside the code block. We need a way to allow these kinds of nested elements so we can style them appropriately. 

## Useful links

* [Code block with a var, and a tag](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial)
* [MDXv2 Umbrella Issue](https://github.com/mdx-js/mdx/issues/1041)

**Comment by paperclypse** [comment]
Are we going to support <pre> tags as well?

**Comment by paperclypse** [comment]
Does the new site currently support <var>, <mark>, and <pre> tags or not? I realize on rereading that this issue might be addressing a slightly different thing (whether you can use these tags in codeblocks or not). Thanks!

**Comment by austin-schaefer** [comment]
Example of a doc where the lack of formatting is very visible. Compare https://docs-preview.newrelic.com/docs/agents/java-agent/api-guides/java-agent-api-instrument-using-annotation with https://docs.newrelic.com/docs/agents/java-agent/api-guides/java-agent-api-instrument-using-annotation .

![image](https://user-images.githubusercontent.com/55203603/101090030-e33a8200-356a-11eb-98db-43334af2e0ae.png)

![image](https://user-images.githubusercontent.com/55203603/101090038-e6ce0900-356a-11eb-95b3-49a316d3fe55.png)
