### ISSUE TITLE
Issue: Troubleshoot password, email address, and login issues

### ISSUE THREAD

**Issue by rkwanyuyeung** [newrelic/docs-website#1165]
### Tell us what you need

When logging in on https://login.newrelic.com, it always showed a message
  _Multiple accounts found. Verify your email to view all your accounts._

and after entering the password and click `Log in ` button, it always logged-in to a wrong account.  it does not have an option for me to choose which one to login on that UI, until I click on the link to `verify your email` , then wait for the email to arrive, and click on the link to verify then I have a chance to select the account that I want to login to . 

I want to seek help  to
1. improve the login flow with multiple accounts 
2. fix the default account - so everytime when I login, it will be logging into the correct account, without going through the email address verification flow

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems
* **OS**: MACOS 10.14.6
* **Browser**: Version 88.0.4324.192 (Official Build) (x86_64)
* **Device**: Macbook Pro

**Comment by zuluecho9** [comment]
Note that on login page it says at top 'verify your email to view all accounts'. We also mention that in a clamshell under 'Asked to verify email during login' in https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems. We also mention this in https://docs.newrelic.com/docs/accounts/accounts-billing/general-account-settings/factors-affecting-access-features-data#account-access, including a link to an explorer's hub about it. 

Not to say this couldn't be improved (it can) but just noting where things are for later.

**Comment by barbnewrelic** [comment]
This seems more like a problem with the user experience in the UI. I've asked wizards-user-management to weigh in.

**Comment by barbnewrelic** [comment]
From the wizards: 
In this case, the user needs to select the "remember me" checkbox and then they shouldn't have this problem going forward. This really isn't a bug ticket that I want to move to the backlog.  If there are more concerns with the login flow after the user knows about the remember-me feature, then it should go into an Aha feature request.  Thanks!
I'll tweak the doc in question.

**Comment by barbnewrelic** [comment]
I verified the "remember me" info is in https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems/#verify-email so I have closed this issue, so I'm closing this issue.
