### ISSUE TITLE
Transparent PNGs showing weird blurriness

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#1166]
When uploading transparent PNGs, getting this weird background color blurriness. This was on preview site so maybe only an issue there? 
<img width="1196" alt="Screen Shot 2021-03-04 at 9 32 27 AM" src="https://user-images.githubusercontent.com/9435570/110009714-3d65f300-7cd2-11eb-9a2b-720f3a2feb8b.png">

**Comment by bradleycamacho** [comment]
This might have something to do with #728

**Comment by jerelmiller** [comment]
This should have been fixed a while ago. Could you add a link to the relevant page so we can check into this further? If this is meant for the preview site, would you mind moving this issue over there?

**Comment by jerelmiller** [comment]
> this was on the preview site

D'oh, should have read closer. This was fixed yesterday (PR 24). If you're seeing this locally, its possible you don't have that code merged in. Could you make sure your branch is updated with `develop`?
