### ISSUE TITLE
Structural issue with data dictionary

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#1167]
### Description

In data dictionary, for views of specific attributes (like this https://docs.newrelic.com/attribute-dictionary/?event=Transaction&attribute=accountId), it’s now displaying the data type that the attribute was first added to, which wasn't done on previous drupal site. It would be preferred IMO to just display the attribute and not the data type, considering there’s no logical reason to display the first-used data type also. (I’m assuming this is a tech limitation: that an attribute view requires something in the “Event type” field on right.)

### Steps to reproduce

1. Go to data dictionary and select an attribute that has multiple data types associated with it. You will see it display the first-added data type at top. 
<img width="865" alt="Screen Shot 2021-03-04 at 10 17 41 AM" src="https://user-images.githubusercontent.com/9435570/110010173-de54ae00-7cd2-11eb-8bff-17009e5bfb67.png">

**Comment by jerelmiller** [comment]
@zuluecho9 just to clarify, when you say "data type" are you referring to the event name? (i.e. `Transaction` and `TransactionError` in this case)

**Comment by jpvajda** [comment]
Definitely need some clarification here to better understand the problem, is `datatype` = to what is classified in the events column in the table? and if so, why not show this information? Does it cause confusion? I guess having a better primer on what this association means, is a good place to start.

**Comment by zuluecho9** [comment]
@jerelmiller @jpvajda "data type" is the preferred way to refer to what we previously (and sometimes still internally and in codebase) refer to "event". Because we now have MELT data types, so we wanted to avoid calling all of these "events" when we have a specific "event" data type. If that makes sense. So that explains some of the reasons for my wording yeah.

**Comment by zuluecho9** [comment]
@jpvajda Currently, for an attribute entry, it is showing just a single "data type" (aka "event type") above the attribute, even if an attribute is attached to multiple event/data types. So this is pretty arbitrary because it is just showing the first-associated data type that attribute was added with. There's no specific reason to show that single data/event type. For example, an attribute might be attached to 5 data types (eg, Transaction, TransactionError, Span, etc.)

**Comment by zuluecho9** [comment]
I'm going to close this. It seems related to https://github.com/newrelic/docs-website/issues/626; we need a way to search for and expose attribute entries independent of data type.
