### ISSUE TITLE
Dashboard for top Relic contributors, outside our teams

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1169]
### Is your feature request related to a problem? Please describe

We'd like to be able to find and recognize top Relic contributors to the docs site!

### Describe the solution you'd like

* Analytics on this across sites
* Analytics on this for docs site specifically

@jpvajda Shared a query that seems to do this, but looks like it may not include everyone on our teams?

**Comment by jpvajda** [comment]
I `think` @caylahamann determined the issue with the board we made... I'm still checking into one issue I saw.

**Comment by caylahamann** [comment]
made a dashboard to show what I mean to get the top contributors in NR: https://staging.one.nr/0VKQXO51jax this is a count for all githubEvents ('push', 'fork', 'pull_request', ect.) I did tried for just `push` events but we haven't had any outside our group pushes or commits yet. The two big things to look for in this query are those two arrays. The first one is all the logins for NR members (as of end of February) and the second one is the list of logins for people we want to exclude who are part of our group. I attempted to group it by count of interaction (like a table showing the number of commits, number of forks, number of ect for each 
```
sender.login not in ('jerelmiller','caylahamann', 'zstix', 'jpvajda', 'mmfred', 'LizBaker', 'roadlittledawn', 'paperclypse', 'bradleycamacho', 'rhetoric101', 'mmfred', 'zuluecho9', 'urbiz-nr', 'dbarnesbrownNR', 'barbnewrelic', 'Broseberg', 'austin-schaefer', 'nr-opensource-bot', 'tariqahmed', 'CLAassistant', 'djsauble', 'theletterf', 'MattWhelan')
```
I did my best guess of who's a contributor part of the docs team and who is not, but double-check it just to make sure! 

This is right now our only reliable method of telling who is a contributor in our group / who is not. We should look into expanding https://github.com/newrelic-experimental/newrelic-serverless-github-webhook to be able to get data in about the people contributing (whether they are outside certain orgs or not).

**Comment by jpvajda** [comment]
@austin-schaefer this seems like a tough nut to crack, the arrays we are using statically generate values so as team members change this query becomes inaccurate. We "could" spend more time on this but at this point I think this give you some data and I encourage your team to get more versed in building and managing these NRQL queries so you don't have to rely on DevEn to manage queries on your behave. This example query can be added to which ever dashboard you want to track this on.

**Comment by jpvajda** [comment]
Moved widget to this primary dashboard: https://staging.one.nr/06vjA424RPG
