### ISSUE TITLE
Validating Google Docs Instrumentation > Understanding the discrepancy

### ISSUE THREAD

**Issue by tariqahmed** [newrelic/docs-website#1176]
Since GA - the page view data on the new site is significantly different than the old site.

I can see the browser is calling the GA JS using the right ID. 

In GA the old docs site gets about  6X-7X pageviews/day over the new docs site. For the specific numbers please refer to GA.

Through New Relic Browser Aent, I can see we're recording the expected amount of traffic so that's in line with expectations.

**Thus the goal of this ticket is to be able to at least understand the discrepancy as to why GA only recognizes a small subset of page views.**

![2021-03-04_12-28-13](https://user-images.githubusercontent.com/1187068/110026329-5b891e80-7ce5-11eb-896c-df8f444fc06e.png)

@austin-schaefer

**Comment by jpvajda** [comment]
@caylahamann may have insights here.

**Comment by jpvajda** [comment]
in NR it's correct, in GA it's not , so we are still looking into it.

**Comment by jpvajda** [comment]
From @caylahamann 

```
Figured out what’s going on with Google Analytics: tessen isn’t tracking page views between clicks on our site. It is only tracking when we first load the site. You can see this if you go to our network tab…. i’m not sure what’s exactly not causing it to fire. It must be something with our tessen config, but you can also see that none of the properties that we attach to tessen are loading (for example, location, env ) in our createTessen() function.
```

**Comment by jpvajda** [comment]
![DocsSite-Analytics](https://user-images.githubusercontent.com/1395158/110374346-d2882500-800d-11eb-9026-3a416f44307c.png)

**Comment by jpvajda** [comment]
adding a diagram so I can get a hosted image URL to put in the wiki. 😃

**Comment by caylahamann** [comment]
Hey! an update on this: we actually figured out why the page views weren't tracking. We were only tracking the first page view when the user loaded the site, and note subsequent page views. This was because of something with our Tessen initialization that was causing us a bunch of downstream errors. I created over the weekend to solve this: https://github.com/newrelic/gatsby-theme-newrelic/pull/315 and was released onto the docs site by upgrading the theme three hours ago: https://github.com/newrelic/docs-website/pull/1221. This should close as soon as we can validate that the data matches.

**Comment by caylahamann** [comment]
That being said, it may be a day before we can validate this change is taking affect. The PR was just released on amplify an hour ago, but caching and what not make take a while for the scripts to change on everybody's page. I can see a slow increase in the Tessen doc views already, but I'd wait a day before making a true comparison.

**Comment by jpvajda** [comment]
@caylahamann so once we bump the theme on Docs Site, this "should" be fixed?

**Comment by jpvajda** [comment]
it does look like docs site is on the latest theme now but it might be a little while before we can confirm that the page views are now all being recorded (due to caching / it would need a hard page reload)

**Comment by jpvajda** [comment]
Let's check the NR browser data in comparison, also give it a few more days for GA to catch up

**Comment by roadlittledawn** [comment]
so far, I:
* updated [GA view settings](https://analytics.google.com/analytics/web/#/a3047412w90042879p95485075/admin/view/settings) to account for `q` query param. may need to do same for attribute dictionary params. 
* unchecked `Exclude all hits from known bots and spiders` for now
* there's a lot of filtering like i saw in older GA views, buuuut not sure filtering New Relic office IPs would account for difference right now. [View filters](https://analytics.google.com/analytics/web/#/a3047412w90042879p95485075/admin/view/filters/)

**Comment by jpvajda** [comment]
one other thing to consider @LizBaker brought up was the cookies disabling we allow users to do very easily now, previously this was all done in intercom and it was done once across all sites, so now 1st visitors are being asked for cookie consent on every visit until they accept / deny. Many users are very aware of trackers and why disabling them is a good thing for them. So it's possible many users are doing just that. I'm not sure if we've instrumented the cookie acceptance button click yet, but if we did or do, we can look at that data to see how many users are actually doing that.

also, enable GA anonymous tracking could be an option if it OK with GDPR. 

https://infotrust.com/articles/intro-to-cookieless-anonymous-tracking-in-google-analytics/

**Comment by jpvajda** [comment]
GA have filters applied as well, could this be causing any issues?

**Comment by jpvajda** [comment]
After talking through it, we believe the decrease in page views is related to the new GDPR cookie acceptance process a user goes through when they first visit the site. Given many users already accepted the cookie for the old process (Intercom) when visiting the new site they need to accept these cookies again. 

Look at NR browser data, for the same time period there is a similar pattern that may prove this assumption correct. However I think our next logical step is to request an analytics audit from someone at New Relic who has expertise in GA and NR Browser data to ensure that are assumptions are correct.

Also we'll want to look into anonymous data tracking in GA as well so we can anonymized analytics for page views and sessions in GA and NR Browser for those users that don't accept cookies.

**Comment by jpvajda** [comment]
closing as the work is done, and the next steps are outlined in #1331
