### ISSUE TITLE
This is an enhancement request!

### ISSUE THREAD

**Issue by Santosh-Kumar-Perumal** [newrelic/docs-website#11767]
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is.
I can see Google cloud Interconnect contains lots of metrics as given in the below document but New Relic integration to GCP support's only few of them why so ? I am looking for "network/interconnect/operational" this is not supported by New Relic.
https://cloud.google.com/monitoring/api/metrics_gcp#gcp-interconnect

New Relic support only 
https://docs.newrelic.com/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-direct-interconnect-monitoring-integration/

## Describe the solution you'd like
I would like the metrics "network/interconnect/operational"  to be available in New relic so that I can use it set my uptime check for Direct Interconnect outage.

A clear and concise description of what you want to happen. What is the expected outcome?
I would like the metrics "network/interconnect/operational"  to be available in New relic so that I can use it set my uptime check for Direct Interconnect outage.

## Describe why this important to you
It is a key metrics that I am interested to be enabled as part of my project.

Why should we work on this? What use cases does it support?
It helps the users to configure and understand when the GCP service Direct Interconnect is unable to connect to the other end we will get notified using this alert saying the connection is lost.

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. This is a product feature request and not related to our docs repo. Please add this feature request to the feedback form in one.newrelic.com. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.
