### ISSUE TITLE
Configure up-time check for the outage of GCP 

### ISSUE THREAD

**Issue by Santosh-Kumar-Perumal** [newrelic/docs-website#11766]
## How can we make our docs better?

* Is something inaccurate or missing?
I was trying to see if I can get any option to configure  Up- time check for the outage of my Google cloud Dedicated interconnect service but I couldn't find anywhere in the doc's section that can guide me.The do have a document that guides for all the GCP services but this particular thing that I mentioned is missing.

Below are the pages that I am referring to
https://github.com/newrelic/newrelic-quickstarts/tree/main/quickstarts/gcp/gcp-dedicated-interconnect
https://docs.newrelic.com/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-direct-interconnect-monitoring-integration/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/google-cloud-platform-integrations/
* **OS**: Linux x86_64
* **Browser**: Chrome 110.0.0.0
* **Device**: Unknown

**Comment by ashutosh887** [comment]
I would like to work on this

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. We've created a Jira ticket for our backlog to address this. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.
