### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by northyg** [newrelic/docs-website#11761]
## Description

Broken link on this page https://docs.newrelic.com/docs/alerts-applied-intelligence/overview/#detect-intro

This is the broken link https://docs.newrelic.com/docs/alerts/new-relic-alerts/defining-conditions/create-anomaly-alert-conditions/

**Comment by x8a** [comment]
Hey, @nbaenam! Could you have a look at this one, please? Thanks!

**Comment by nbaenam** [comment]
Fixed in [11789](https://github.com/newrelic/docs-website/pull/11789)
