### ISSUE TITLE
Inaccurate NerdGraph query

### ISSUE THREAD

**Issue by hwilkalis-nr** [newrelic/docs-website#11825]
## How can we make our docs better?

At https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-api-nrql-condition-alerts/#description, the query shown under "1. Get all the conditions for a policy:" is incorrect and will fail. I believe it should be something like this but that should be confirmed:

{
  actor {
    account(id: YOUR_ACCOUNT_ID) {
      id
      alerts {
        nrqlConditionsSearch(searchCriteria: {policyId: YOUR_POLICY_ID}) {
          nrqlConditions {
            id
            name
            description
            enabled
            nrql {
              query
            }
            signal {
              aggregationDelay
              aggregationMethod
              aggregationTimer
              aggregationWindow
            }
            policyId
            runbookUrl
            terms {
              operator
              thresholdDuration
            }
          }
        }
      }
    }
  }
}

**Comment by rhetoric101** [comment]
@hwilkalis-nr thanks for bringing this to our attention! I'm closing this GitHub issue since we're using your suggestions over in this PR: https://github.com/newrelic/docs-website/pull/11829
