### ISSUE TITLE
Include message to Japanese users to prevent Japanese PR.

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#1187]
### Description

Insert a message to alert Japanese users trying to create a PR from the Japanese site that we do not at the time handle Japanese PR.
**English:** If you find any problems in our Japanese docs, you can submit an issue. We try to improve our docs based on your issue. However, we are not ready to merge a Japanese PR directly at this moment.
**Japanese:** 日本語訳されたドキュメントに問題を見つけた場合は、issueを提出することができます。issueをもとにドキュメントの改善に努めています。しかしながら、日本語訳のPRを直接マージする準備はまだできていないためご了承ください。

### Steps to reproduce

N/A

### Expected behavior

Show message in Japanese and possibly in English to alert users.

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

**Comment by jpvajda** [comment]
This is a good idea, and I remember we discussed this. so as we expand languages, will we just add each message for every language we support that we don't accept PRs for that specific lanuage site @jmiraNR
