### ISSUE TITLE
AWS integration list - wrong redirect

### ISSUE THREAD

**Issue by urbiz-nr** [newrelic/docs-website#1188]
As [reported by Paras Wadhera](https://newrelic.slack.com/archives/C0DSGL3FZ/p1614928513207600) in #documentation, the [AWS integration list doc](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list ) gets redirected to the metrics doc. This did not happen before the migration.

**Comment by urbiz-nr** [comment]
There's a redirect that shouldn't be there, creating branch to fix this. See https://github.com/newrelic/docs-website/pull/1190

**Comment by mmfred** [comment]
Closing as fixed.
