### ISSUE TITLE
Download images and store them locally

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#119]
## Description

In order to migrate images, we'll need to download them from the docs site and store them locally. Once the images are downloaded, we will need to update the image path in the markdown files to the relative path on the file system.

Some considerations on approaches:

1. * Do we want to store all images in the `src/images` folder? This means very-nested pages will require a pretty hefty import path (e.g. `../../../../../src/images/path/to/image.jpg`)
2. * Should we store the images in the same directory as the page? This makes relative imports easier, but may clutter content directories
3. * Should we create a subfolder in directories for images? (i.e. `src/content/whats-new/images/image.jpg` where a page in `whats-new` would reference `./images/image.jpg`)

## Acceptance criteria

* [ ] Download images locally
* [ ] Update the markdown path to reference the local path to the image

**Comment by jpvajda** [comment]
@austin-schaefer  The team opted for option 3 but wanted to get your opinion on the approach to storing of images as content creators will have the most interaction with images.

**Comment by jpvajda** [comment]
Austin confirmed Option 3 as well.
