### ISSUE TITLE
 English homepage search generates Japanese search results

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#1191]
### Description

I just noticed today some new behavior: If I search starting from an English language page, the results include Japanese listings. The search result links take me to the Japanese site.

### Steps to reproduce

1. Go to https://docs.newrelic.com/ (English site)
2. In the search bar, enter "Kubernetes" (this also worked for "Prometheus")
  NOTE: The results include Japanese characters.
3. Click any of the results, which take you to the Japanese site.

### Expected behavior

I would expect to get English search results if I start from the English site.

### Related Issue

#1204 

Due to a few issues with language tags on pages and a site map problem, we were having issues rendering pages in the product help, to fix it, we black listed the jp site in Swiftype, until we fixed those other issues, in doing this the current problem is persisting search terms in Japanese still need to be enter in English on the JP site

Once we resolve the issues mention above we can remove the JP black list entry from swiftype

## Eng work
- We need to differentiate jp namespaced docs pages from english namespaced docs pages via the swiftype meta tag `type`. We'll do that via the theme, because we can apply that globally and it already has the logic in place to work with locales.
- Once that is in the theme, we need to bump the theme version for each site to take advantage of that, docs being first because it's the only site with translations available right now.
- Once the relevant meta tags are in place for jp namespaced pages, we need to remove the crawl rule in swiftype to allow indexing pages with `/jp/docs/` in the url. 
- Once swiftype indexes all translated pages under their new `type`, we can update the theme search to account for searching with japanese characters against `docs-jp`. See caveat below.

### Caveats
If a locale namspaced page only has English, we tell swiftype to not index it. However, a few pages have some translations but are mostly in English (ex: `jp/attribute-dictionary`, `jp/whats-new`). So instead of just adding `docs-jp` to the list of site `type` values to query against, we may need to add some affordance to the search UI to account for that and avoid what will look like duplicate records when a user searches using English.

The work to bump the theme is straight forward on the docs site. The develop site requires some more refactor because it wasn't using the theme's SEO component. And I assume opensource will require similar if not more effort to bump the theme, since it's on a fairly old version.

**Comment by bradleycamacho** [comment]
Someone also stated "docs.newrelic.com is redirecting me to docs.newrelic.com/jp incognito". I couldn't replicate this, but it may be related?

**Comment by jmiraNR** [comment]
Expected behavior:
and expect Japanese results (first) if starting from the Japanese site.

**Comment by jpvajda** [comment]
I couldn't reproduce this.

**Comment by jpvajda** [comment]
Now I can. :)
