### ISSUE TITLE
SystemSample `status` definition request

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#1193]
### Tell us what you need
SystemSample has an attribute `status` in the event, but I couldnt find a definition for the attribute. 

Please include it in https://docs.newrelic.com/attribute-dictionary/?event=SystemSample

**Comment by barbnewrelic** [comment]
I'm checking with help-infra-platform slack channel.

**Comment by barbnewrelic** [comment]
Thanks again for your patience! Several days ago I checked with our infra heroes, and today they replied that currently `status` is not in the code base. They suggested you could try using `hostStatus` but they will need to test and confirm functionality before being able to add a new `status` attribute. I hope this workaround is satisfactory for now!
