### ISSUE TITLE
Route localhost search results to the localhost instead of public site

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#1197]
### Is your feature request related to a problem? Please describe

Currently search results on a locally built site route the user to the public site. This isn't a big deal, but it would be nice if we could find a way to route local search results to the local site itself. 

No need to prioritize this, this is just a nice to have.

**Comment by bradleycamacho** [comment]
@paperclypse Brought up a good point: this may even be impossible since the search is handled by Swifttype.

**Comment by jerelmiller** [comment]
@bradleycamacho I can weigh in here. This is definitely possible with our magic `<Link />` component in the theme. That `Link` component will convert any absolute URL that matches the current site to a relative one.

There are a couple things that need to happen for this to work:

1. Make sure the search experience use our theme's `Link` component. Right now this is not the case and treats all links as "external" (which unfortunately opens the results in a new tab, even for the current site)
2. Update the UX to ensure routing to a URL in the same site closes the search overlay.

@caylahamann and I have been working on an innovation project to overhaul the search experience, and we plan to build this functionality into it. Stay tuned!

**Comment by jerelmiller** [comment]
One more thing to add! When this change is made, this will also work locally as well. We have the site URL configured so we are able to make this work even if you're on localhost.
