### ISSUE TITLE
Complete the list of APM timeslice metrics

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#12028]
Filing this issue on behalf of the customer.

## How can we make our docs better?

Some APM timeslice metrics are described on this page but it's not all.

https://docs.newrelic.com/docs/data-apis/understand-data/metric-data/query-apm-metric-timeslice-data-nrql/

Could you add the description of all the APM timeslice metrics reported by the Agent?

**Comment by paperclypse** [comment]
@tanaka-takayoshi We've created a Jira ticket for this issue. If you'd like a more immediate response in future, please reach out to our hero in the help documentation Slack channel. Thanks!
