### ISSUE TITLE
Prevent double build on release PRs

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#1209]
### Description

When opening release PRs from `develop` -> `main`, both the action to build and cache the site + the PR validation workflow is run. This results in 2 builds for any release PR. Seeing as we are already building the site when caching the merges, I'm not sure we need to also build the site for the PR. This can slow down release PRs because depending on when the validate PR workflow is run, it might add quite a bit of time before a PR can be merged.

Let's try and consolidate to a single build to allow us to merge the release PRs a bit quicker.

**Comment by jpvajda** [comment]
Remove the build step from the `validate PR build` and adjust the workflow to remove that build step.

**Comment by jpvajda** [comment]
keep jest test and eslint checks, but skip build step.
