### ISSUE TITLE
Enhancements to 2 attributes in Data Dictionary

### ISSUE THREAD

**Issue by thezackm** [newrelic/docs-website#12123]
## Summary

There are 2 fields in our `SystemSample` event that are missing details for Windows platform environments. In essence, the current definitions are only applicable to Linux environments and we need to be more descriptive.

## Attributes

Both of these are in the `Infrastructure` data source, `SystemSample` data type:

[processorCount](https://docs.newrelic.com/attribute-dictionary/?event=SystemSample&attribute=processorCount)

[coreCount](https://docs.newrelic.com/attribute-dictionary/?event=SystemSample&attribute=coreCount)

### processorCount

Current:

>The total number of cores in all CPUs. This corresponds with the 'processor' entry in /proc/cpuinfo in Linux.

Suggested change:

>Linux: [`/proc/cpuinfo`: 'processor'] The total number of cores in all CPUs.
>Windows: [WMI `win32_processor`: 'NumberOfCores'] The number of physical processors on the integrated circuit.

### coreCount

Current:

>The number of cores within a single CPU. This corresponds with the 'cpu cores' field in /proc/cpuinfo in Linux.

Suggested change:

>Linux: [`/proc/cpuinfo`: 'cpu cores'] The number of cores within a single CPU.
>Windows: [WMI `win32_processor`: 'NumberOfLogicalProcessors'] The number of logical processors, including cores divided by hyperthreading.

**Comment by ally-sassman** [comment]
Thanks @thezackm , I created this PR to merge your suggestion: https://github.com/newrelic/docs-website/pull/12128
