### ISSUE TITLE
Issue: New Relic Flex: 独自のインテグレーションを構築する

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#1212]
In the English version of the Requirements, it says that you can use it if you have an infrastructure agent.
However, in the Japanese version, New Relic Infrastructure Pro license is required.

I would like to see the Requirements in Japanese updated.

**Comment by paperclypse** [comment]
Hi @qryuu! Thanks for letting us know about this. I've asked around and I've learned from our translation expert that this Japanese doc will be updated to match the English version as part of our regular translation maintenance. 

The New Relic Infrastructure Pro license is no longer required for New Relic Flex.
