### ISSUE TITLE
Issue: SNMP monitoring integration

### ISSUE THREAD

**Issue by josemore** [newrelic/docs-website#1215]
### Tell us what you need
We released SNMP integration 1.3.0 which adds support for Windows (.msi package released). 
We should revert this commit where we recently removed Windows support from docs: https://github.com/newrelic/docs-website/commit/2cde37d82c916c729ef6e4da9098dbddd93b0997#diff-115dc1e27de57ea7d6afdb9cbe37bad88776d2b8ddc4da14cba0d84c7623b959

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/snmp-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @josemore! I've created a PR to revert this change. Thanks for letting us know!

**Comment by josemore** [comment]
Thanks @paperclypse, looks it's ready to be merged, I'll keep an eye when ready to share with customers

**Comment by paperclypse** [comment]
Hi @josemore! Please let us know when this will be ready to share with customers. Thanks!

**Comment by josemore** [comment]
Sorry, I meant let's merge this so it's available for customers, release 1.3.0 added support for Windows and it has been released already

**Comment by paperclypse** [comment]
Sorry for the confusion, @josemore! I've merged the PR in and it will be published to our site a bit later today. Thanks!
