### ISSUE TITLE
Issue: Factors affecting access to features and data

### ISSUE THREAD

**Issue by jameschan2** [newrelic/docs-website#1216]
### Tell us what you need
The following text is very ambiguous and does not clearly state what information a user may or may not have access to. It also does not differentiate between v1 and v2 users.

"New Relic One gives a cross-account view of data from accounts within the same organization. But there can be boundaries between accounts that result in some data being obfuscated. For example, in a master/sub-account account structure, a user on a sub-account may see data from the master account or from another sub-account that has been obfuscated."

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/general-account-settings/factors-affecting-access-features-data/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 89.0.4389.82
* **Device**: Unknown

**Comment by zuluecho9** [comment]
I created a pull request based on this: https://github.com/newrelic/docs-website/pull/1229. 

Some of that wording is purposefully ambiguous to cover some confusing complexity. But saw some room for improvements there.
