### ISSUE TITLE
Slight Suggestion for Log Pipeline Diagram

### ISSUE THREAD

**Issue by JimHagan** [newrelic/docs-website#1223]
### Log Pipeline Diagram Could Use Some Improvement

* The "New Relic Logs" stage (just after applications) blurs the line between log forwarder and log backend.
* I think it would be best to be clear about the dividing line between the NR1 SaaS backend and the upstream data center.

Image URL: https://github.com/newrelic/docs-website/blob/develop/src/content/docs/logs/log-management/ui-data/images/NRDB2.png

I've attached an annotated screenshot:

![LogPipelineSuggestion](https://user-images.githubusercontent.com/8333200/110353179-c0ee4f80-8004-11eb-8338-2449eb72a23a.jpg)

**Comment by paperclypse** [comment]
Hey @JimHagan, thanks for the suggestion! 

I've created a Jira for this issue: DOC-6633.

**Comment by bradleycamacho** [comment]
@barbnewrelic Is there an update on this? Seems like the Jira is closed.

**Comment by barbnewrelic** [comment]
Yes Jira is now https://newrelic.atlassian.net/browse/DOC-6731 . For short term with previous Jira mentioned, I added some explanatory text before I was OOO. https://docs.newrelic.com/docs/logs/log-management/ui-data/drop-data-drop-filter-rules/#how-it-works
