### ISSUE TITLE
Investigate constant redirect loop on original product pricing doc

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#1227]
[Internal SME] found a page that's in a constant redirect loop. Can we check if this is a content issue and then report to dev team if not? https://docs.newrelic.com/docs/accounts/original-accounts-billing/product-pricing/product-based-pricing/

**Comment by bradleycamacho** [comment]
Page loads correctly for me in Firefox and chrome. @austin-schaefer says it reloads every few minutes on Edge.

**Comment by roadlittledawn** [comment]
FWIW: I'm seeing the redirect loop behavior in Chrome  Version 88.0.4324.192

**Comment by roadlittledawn** [comment]
looks like the URL of the page is also in the redirects
