### ISSUE TITLE
Scripted API monitor errors explanations use webdriver syntax

### ISSUE THREAD

**Issue by Leels** [newrelic/docs-website#12397]
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/troubleshooting/simple-scripted-or-scripted-api-non-ping-errors/#job-timed-out-api

https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/troubleshooting/simple-scripted-or-scripted-api-non-ping-errors/#script-timeout-error-api

Both of these explanations use webdriver syntax that is not available to API test monitors. 

Ex. "For example, changing $browser.findElement(locator: $driver.Locator) to $browser.waitForAndFindElement(locator: $driver.Locator [, timeout: number) would assigned the task its own configurable timeout."

These explanations use the same explanations as the scripted browser examples above and are not edited specifically for Scripted API test monitors. The solutions given in the examples will not work for API test monitors.

**Comment by zuluecho9** [comment]
Talked to submitter about this, am closing.
