### ISSUE TITLE
Find replacements for font-awesome icons

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#124]
## Description

As a part of our migration process, we are updating icons from font awesome to feather icons. There are a few icons that we are unable to map. They include:

* [`caret-up`](https://fontawesome.com/icons?d=gallery&q=caret-up) - [source](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-error-profiles-find-error-causes)
* [`quote-left`](https://fontawesome.com/icons/quote-left?style=solid) - [source](https://docs.newrelic.com/docs/browser)
* [`quote-right`](https://fontawesome.com/icons/quote-right?style=solid) - [source](https://docs.newrelic.com/docs/browser)
* `android` - [source](https://docs.newrelic.com/docs/mobile-monitoring)
* `apple` - [source](https://docs.newrelic.com/docs/mobile-monitoring)

**NOTE:** 

This will be a running list that will change over time as we discover more icons that don't have a direct equivalent. 

The links above refer to the latest version of fontawesome. The docs site is currently using fontawesome v4 which have some variance in the styles.

## Design input 

Identify the feather icons to use for ones that cannot be currently mapped.

* [`quote-left`](https://fontawesome.com/icons/quote-left?style=solid) >> Curious about what context this appears in. Perhaps [`message-square`](https://feathericons.com/?query=message-square)?
* [`quote-right`](https://fontawesome.com/icons/quote-right?style=solid) >> Why do we need separate `quote-left` and `quote-right` replacements?
* `android` >> Suggest keeping the existing icon from FontAwesome
* `apple` >> Suggest keeping the existing icon from FontAwesome

**Comment by caylahamann** [comment]
Question: does this only include the icons in the current migrated docs? / will we have to expand this when we decide to migrate more docs?

**Comment by jerelmiller** [comment]
@jpvajda @djsauble Would love for you to look at this and provide recommendations as we migrate the docs.

**Comment by djsauble** [comment]
@jerelmiller It would be helpful to see an example of the context in which these icons appear.

**Comment by paperclypse** [comment]
@djsauble Let me know if you need help tracking down examples of icon examples on the docs site.

**Comment by djsauble** [comment]
@paperclypse That'd be awesome! I left some questions in the description above, basically I'm uncertain about the context of use for some of these icons, which is important in finding adequate substitutions for them.

**Comment by jerelmiller** [comment]
@djsauble I've updated the comment to reflect the icons that are missing and provided links to pages that use them.

Thanks for providing help on those others! We are able to map almost all of the icons, which is great news! We have only about ~500 docs left to migrate, so I feel pretty good about where we're at. Once we pull in the rest of the docs, I'll make sure to update this one more time in case we are missing any more.

**Comment by jpvajda** [comment]
@jerelmiller is there anything I can help to decide on to unblock this? I'm happy to provide a font recommendation to move this along.

**Comment by zstix** [comment]
This is blocked until we pull in the remaining content.
