### ISSUE TITLE
Incorrect Japanse translation in left nav bar

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#1242]
### Tell us what you need

The left nav bar has an incorrect Japanese translation.

![image](https://user-images.githubusercontent.com/846156/110417352-c87f2880-80d8-11eb-9418-7757537d4eb1.png)

"クエリビルダーの概要" means "summary of query builder"

The correct word is "Get started"

![image](https://user-images.githubusercontent.com/846156/110417445-febca800-80d8-11eb-8947-ad320f29984b.png)

I wonder the following JSON causes an issue but not sure how to fix nav bar transalation.

https://github.com/newrelic/docs-website/blob/develop/src/i18n/nav/jp.json#L1322-L1326

### Doc information (don't delete this section)

* https://docs.newrelic.com/jp/docs/infrastructure/
* **OS**: Mac OS 11.2.2
* **Browser**: Chrome 88.0.4324.192
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
@jmiraNR , can you have a look at this?
