### ISSUE TITLE
Windows Installer for Infra, is it possible to default the logging to C:\ProgramData 

### ISSUE THREAD

**Issue by sbhakta99** [newrelic/docs-website#12430]
## Is your feature request related to a problem? Please describe

We are using the msi installer latest, see Describe why this important to you

## Describe the solution you'd like

see Describe why this important to you

## Describe why this important to you

For the Windows Installer for Infra, is it possible to default the logging location that comes with installer/yaml to C:\ProgramData rather than C:\Program Files"
Almost all modern win32 application writes it's logs to C:\ProgramData\ since that is the System Accounts "AppData"

Anyway we can get this updated?
https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/configure-infrastructure-agent/
> https://github.com/newrelic/infrastructure-agent/blob/master/assets/examples/infrastructure/newrelic-infra-template.yml.example

We noticed if we change the log location directory in the newrelic-infra.yml it doesn't create logs directory in that location or infra doesn't start, do we always have to create logs directory if we do not use default?  

log:
file: 'C:\programdata\New Relic\newrelic-infra\logs\newrelic-infra.log'

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. We've created a Jira ticket for our team to investigate this further. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.
