### ISSUE TITLE
Issue: Get data into New Relic - Link to Metrics API 404's

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#1245]
### Tell us what you need

The link to Metrics API goes to a 404.

Link is currently:
https://docs.newrelic.com/docs/data-ingest-apis/get-data-new-relic/metric-api/

But should be (I think):
https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/introduction-metric-api/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/get-data-new-relic/getting-started/introduction-new-relic-data-ingest-apis-sdks/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Fixed in PR #1246.
