### ISSUE TITLE
Issue: Introduction to New Relic for Ruby

### ISSUE THREAD

**Issue by hroseross** [newrelic/docs-website#1250]
### Tell us what you need

This link 404s: https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/ruby-agent-compatibility-requirements/.

It's the last link in this paragraph:
The Ruby agent supports many of the most common Ruby frameworks and platforms. You can also use the Ruby agent in a Google App Engine (GAE) flexible environment. Before you install the Ruby agent, ensure your system meets the system requirements.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/ruby-agent/getting-started/introduction-new-relic-ruby/
* **OS**: Mac OS 11.2.1
* **Browser**: Chrome 89.0.4389.72
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Fixed in #1268
