### ISSUE TITLE
Feedback: Compatibility and requirements of AWS Lambda monitoring

### ISSUE THREAD

**Issue by jmm** [newrelic/docs-website#1252]
Hello,

This says:

> For complete Lambda instrumentation, you must use one of the language-specific AWS SDKs. If an AWS SDK is not used, Lambda data will appear as external service calls in the UI, with minimal detail.

What does it mean -- use the SDK for what?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring/

**Comment by urbiz-nr** [comment]
Checking this with Adam Newman and Chris Taylor.

**Comment by urbiz-nr** [comment]
Closing since Chris says: "Hi @aurbiztondo we are actually in the process of completely reworking the Lambda docs, so probably doesn’t make a lot of sense to make this change just now." Work's being done in #1111.
