### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by MichaelOsowski** [newrelic/docs-website#12544]
unable to find -javaagent config option

**Comment by homelessbirds** [comment]
Hi @MichaelOsowski. Thanks for flagging! I reached out to my team to look into this and will let you know when I get this resolved.

**Comment by homelessbirds** [comment]
@MichaelOsowski--what specifically are you looking to do? Does [this doc](https://docs.newrelic.com/install/java/?deployment=appServer&framework=springboot#pass-your-argument) help?
