### ISSUE TITLE
Suggestion: omit the license key in the generated newrelic.ini file.

### ISSUE THREAD

**Issue by jonwolski** [newrelic/docs-website#1261]
The documentation on https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/new-relic-license-key/ suggests that the License Key needs to be maintained as a secret, however the guided "setup" generates a `newrelic.ini` with the license key _in_ the file.

This can lead my teams to accidentally pushing license keys to version control. It appears that there is no way of rotating this key if it is compromised, so this is a very sensitive secret.

Instead, I recommend omitting the license key from the ini file, and recommending setting the license key in an env var (or secrets management solution of choice)

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/new-relic-license-key/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Reaching out to #security.

**Comment by urbiz-nr** [comment]
Fixing this in #1290.
