### ISSUE TITLE
Release notes RSS feed guid's are changing/regenerated, breaking some RSS readers

### ISSUE THREAD

**Issue by dogsbody-josh** [newrelic/docs-website#1271]
### Description

The docs website Java Agent release notes RSS feed includes a guid field. This guid field is used by some RSS feed readers to uniquely identify new posts and prevent re-downloading already seen posts. 

In this specific case we're using Huginn and it's built in RSS agent to monitor the Java Agent Release Notes RSS feed. 

The guid field in the XML feed is changing/being regenerated on a regular basis. My suspicion would be when some kind of build event occurs, but that's just a guess. 

Because the guid is changing, the RSS reader thinks there are new posts available for download. Because every single guid for every single post is changing, it re-downloads hundreds of posts each time. 

### Steps to reproduce

1. Make note of a guid for a post on the Java Agent Release Notes RSS feed
2. Wait 24-48 hours for whatever event is occurring (automated build?)
3. Check the guid for the post you made note of, it will be different

I do not know what is triggering the guid to change, but whatever it is occurring daily at some time in the evening UTC (approx 1800-2000 UTC).

### Expected behavior

Expected that guid do not change so that posts can be uniquely identified and prevent re-downloading. 

### Additional context

Link to specific feed: 
https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/feed.xml

### Environment

N/A

**Comment by jpvajda** [comment]
@dogsbody-josh thanks for the detail on this issue like @jerelmiller our team will take a look at this problem.  Do you have any work around at the moment to get around this problem?

**Comment by dogsbody-josh** [comment]
@jpvajda I have switched to using a different 'agent' in Huginn to parse the XML directly. There's no workaround in the standard Huginn RSS agent as there is no way to alter which value it uses as the 'source of truth' for uniquely identifying already seen posts. 

It may be possible to alter what other RSS readers use as the 'source of truth', perhaps to use post titles or pubDate, but that wasn't possible for us. 

Switching to parsing the XML feed 'manually' allowed us to uniquely identify on title and pubDate, so others in this position might try those same actions to work around this issue.

**Comment by jpvajda** [comment]
Adding to Sprint 1, to see if we can resolve this issue.
