### ISSUE TITLE
Issue: Version trends: Compare user adoption metrics and performance

### ISSUE THREAD

**Issue by jameschan2** [newrelic/docs-website#1273]
### Tell us what you need
I spoke with Lindsy Farina the PM and Version Trends is not currently working and needs a major overhaul. We should update the documentation to reflect the true status of this feature (alpha, beta, etc...). Some users see a screen that says "This feature needs more time to bake..." My new relic email is jchan@newrelic.com

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/version-trends-compare-user-adoption-metrics-performance/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 89.0.4389.82
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Talked to PM. This is known issue. We discussed adding a caveat in docs about this; we left it on their side to determine best case solution (docs or otherwise).
