### ISSUE TITLE
Fix broken links in Integrations ToC

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#1276]
There is a broken link on this page:
https://docs.newrelic.com/docs/infrastructure/table-of-contents/ under Types of Integrations - Amazon/AWS Integrations. 

I'm not sure where this is actually supposed to point to. We should fix this specific 404 and check to see if there are any other broken links.

**Comment by austin-schaefer** [comment]
Let's also look at the destinations for the Azure and GCP docs. All three go to different types of destinations (GCP to a list, Azure to a getting started doc)
