### ISSUE TITLE
Summarize your docs request

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#12783]
## How can we make our docs better?

* Is something inaccurate or missing?

Would be good if the information related to the function `apdex` mentioned that if not included, the value of T is by default `0.4`.

https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#func-apdex

**Comment by paperclypse** [comment]
Closed by #15817. 

Thanks for filing this issue! Turns out the default value is 0.5. We've made an update in this PR.
