### ISSUE TITLE
Improve docs on permalinks

### ISSUE THREAD

**Issue by mtjagg** [newrelic/docs-website#1280]
### Tell us what you need

There should be more documentation and explanation for Permalinks

Security - 

- I believe that the permalink still uses all of the same security/authorization that the original page uses - but that’s not explicitly discussed.
- Duration - How long are permalinks active for?  1 year - 10 years - etc?  Can I count on that link to stay the same forever?
- Mutability - does the permalink go to a specific point in time - or a specific point in time relative to the latest data points?
- Maintenance - what happens if I want to expire a permalink?  Does the end user have any access to do that?
- What happens if the linked to data / page is changed?  Is there a certain error or expected behavior that occurs?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/insights/use-insights-ui/manage-dashboards/view-organize-share-insights-dashboards/
* **OS**: Mac OS 11.2.1
* **Browser**: Chrome 89.0.4389.82
* **Device**: Unknown

**Comment by mmfred** [comment]
Hi @mtjagg - thanks so much for filing this issue and making this request. I've made a JIRA to bring into our next documentation sprint, since this will take a bit of sleuthing. As a New Relic employee, you should be able to see [that JIRA](https://newrelic.atlassian.net/browse/DOC-6636). We'll let you know when that info is added.

**Comment by camclark** [comment]
Poking this one again.
Can we at least get 'Duration', @mmfred

**Comment by camclark** [comment]
Poking this one again.

Can we at least get an explanation on:
'Duration - How long are permalinks active for?  1 year - 10 years - etc?  Can I count on that link to stay the same forever?'

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.
