### ISSUE TITLE
Enhancement:  Data Dictionary - Need attribute search.

### ISSUE THREAD

**Issue by adwetzelnr** [newrelic/docs-website#1281]
### Tell us what you need

* Please restore attribute search capability to the Data Dictionary.  In the current version you must select the event type first then choose the attribute.

### Anything else you'd like to share?

- When planning optimal NRQL, it is helpful to know which attributes are shared by which event types.  As such, attribute search very helpful.

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
Hi @adwetzelnr ! Thanks for the feedback. This is definitely on our radar, and we actually have an issue for this already at #626. Closing this one but linking the two so we know there's interest in adding this!

**Comment by adwetzelnr** [comment]
Great, thanks!  Should have searched the issues first

**Comment by austin-schaefer** [comment]
All good @adwetzelnr , really appreciate the feedback!
