### ISSUE TITLE
Feedback: Introduction to New Relic integrations

### ISSUE THREAD

**Issue by toytonto** [newrelic/docs-website#1287]
### Tell us more about your feedback

We're glad to hear this doc was helpful! We've recorded your feedback. Help us 
improve other content by telling us what worked and what didn't:

* What worked well in this doc?
* How could we make this doc even better?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/intro-integrations/get-started/introduction-new-relic-integrations-0/
* **OS**: Android 9
* **Browser**: Chrome 89.0.4389.86
* **Device**: [tablet] SMART TAB 4G e-Biz PRO

**Comment by urbiz-nr** [comment]
Thanks for your feedback!
