### ISSUE TITLE
Link to the settings items in the page

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#1289]
### Tell us what you need

* I'd like to suggest including internal links to items on the page. With a huge emphasis on the config pages of our agents.
* Eg: [this page](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/), if I want to bring the customer to the `filepath` setting there is no way to bring them straight to view the setting.

**Comment by rodrigo-corgozinho** [comment]
Note: I can find a workaround inspecting the page and checking the ID of the item, but it would be much better if the links are added by default.

**Comment by urbiz-nr** [comment]
Hi @rodrigo-corgozinho - this is a [known issue](https://github.com/newrelic/docs-website/issues/727) and we're working on it. If you comment on it it'll help prioritize it! Thanks for reaching out!

**Comment by rodrigo-corgozinho** [comment]
Hi @urbiz-nr sorry for duplicatin it. I'll comment there. thank you

**Comment by urbiz-nr** [comment]
Absolutely no problem, thanks for the feedback!
