### ISSUE TITLE
Issue: Enhance notifications using New Relic Connect | XML Link 404

### ISSUE THREAD

**Issue by josephlocascio** [newrelic/docs-website#1293]
###  Item 4 under the ServiceNow setup instructions, contains a broken link

Go to https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/new-relic-connect/#servicenow

See item 4 "Import the New Relic Connect XML files."

The link for "this XML file" in the first bullet points to https://docs.newrelic.com/sites/default/files/atoms/files/nr_standalone_combined_v1%20%282%29.xml which returns a 404

### Anything else you'd like to share?

The new docs site is great!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/new-relic-connect/#servicenow
* **OS**: Mac
* **Browser**: Chrome latest
* **Device**: Macbook Pro

**Comment by zuluecho9** [comment]
Fixed in https://github.com/newrelic/docs-website/pull/1328.
