### ISSUE TITLE
Issue: Install containerized private minions (CPMs)

### ISSUE THREAD

**Issue by josephlocascio** [newrelic/docs-website#1296]
### Tell us what you need

The icons for Kubernetes in the containerized private minions page seem to be broken, and the text displays some kind alt text preceding the correct header text.

### Anything else you'd like to share?

![image](https://user-images.githubusercontent.com/4605240/110844155-eaee7e80-825d-11eb-8e82-0c6b092841fb.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms/
* **OS**: Mac
* **Browser**: Chrome latest
* **Device**: Macbook

**Comment by bradleycamacho** [comment]
Hey @josephlocascio, thanks for reporting this! We're aware of this issue, but thought we had fixed it in a release earlier today. Let me look into this.

**Comment by zuluecho9** [comment]
Seems to have been fixed so I'm closing.
