### ISSUE TITLE
Issue: OpenTelemetry quick start

### ISSUE THREAD

**Issue by alx13** [newrelic/docs-website#1299]
### Tell us what you need

In this paragraph `example` should lead to `main` branch not `master`
> To use the collector:
> 
> Configure your OpenTelemetry collector to export data to New Relic, using our example as a guide.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 89.0.4389.72
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thank you @alx13

**Comment by zuluecho9** [comment]
Fixed.
