### ISSUE TITLE
Microsoft Teams example ist not uptodate

### ISSUE THREAD

**Issue by vcavallonr** [newrelic/docs-website#13007]
I got the feed-back from a customer that this Wenhook example https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload/#MS-Teams-example
is not uptodate.  The webhook setup requires us to use handlebars format now and some variables have changed as well.
Here an example of a working payload:
{
  "@type": "MessageCard",
  "@context": "http://schema.org/extensions",
  "themeColor": "0076D7",
  "summary": {{ json annotations.title.[0] }},
  "sections": [{
    "activityTitle": "{{eq state 'CLOSED' yes='🟩' no='🟥'}} {{ annotations.title.[0] }}",
    "activitySubtitle": "{{#each accumulations.policyName}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}",
    "activityImage": "https://one.newrelic.com/apple-touch-icon.png?v=2.1",
    "facts": [{
      "name": "Timestamp",
      "value": {{ json issueActivatedAtUtc }}
    }, {
      "name": "Account",
      "value": "{{ accumulations.tag.account.[0] }} ({{ nrAccountId }})"
    }, {
      "name": "Severity",
      "value": {{ json priority}}
    }, {
      "name": "State",
      "value": {{ json state}}
    }, {
      "name": "Duration",
      "value": {{ json issueDurationText }}
    }, {
      "name": "Impacted entities",
      "value": "{{#each entitiesData.names}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}"
    }, {
      "name": "Details",
      "value": "{{#each accumulations.conditionName}}{{this}}{{#unless @last}}, {{/unless}}{{/each}}"
    }],
    "markdown": true
  }, {
    "text": "<p><img src=\"{{ violationChartUrl }}\" alt=\"Incident Chart\"></img></p>"
  }],
  "potentialAction": [{
    "@type": "OpenUri",
    "name": "View Incident",
    "targets": [{
      "os": "default",
      "uri": {{ json issuePageUrl }}
    }]
  }, {
    "@type": "OpenUri",
    "name": "Acknowledge Incident",
    "targets": [{
      "os": "default",
      "uri": {{ json issueAckUrl }}
    }]
  }, {
    "@type": "OpenUri",
    "name": "Open Runbook",
    "targets": [{
      "os": "default",
      "uri": {{ json accumulations.runbookUrl.[0] }}
    }]
  }]
}

**Comment by x8a** [comment]
Thanks for reaching out and giving us a working example! I fixed it with PR #13008.
