### ISSUE TITLE
Lack of NPM prerequisites and installation procedures

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#13010]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)
### Prerequisites and supported SNMP versions
https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring/#prerequisites

The prerequisite Linux and Docker versions are not listed on the Prerequisites and supported SNMP versions page.

I think there should be a mention of the distribution and version of Linux, as there should be a type of package provided.

### Manual setup
https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring/#manual-setup

The Manual Setup section only describes installation with Docker.

Could you please also include the installation procedure with the Package version?

**Comment by paperclypse** [comment]
It looks like this has been addressed in recent updates to the doc. Closing this issue.  If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.
