### ISSUE TITLE
Document how an event or attribute is added to the new Data Dictionary

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1305]
### issue

it's not clear how a content writer would add a new event or attribute to the Data Dictionary. We need to answer

> How does one add a new event to the Data Dictionary?

### AC 

- So let's document how this is done and add to our contributing guide.
- pairing with @barbnewrelic will be helpful as she is in need of doing this.

**Comment by zuluecho9** [comment]
I will create a jira for this. Think below is the workflow. (Note I use 'data type' for a NRDB object although in our data dictionary codebase it is still 'event' or 'event type' sometimes.)

Process seems as simple as:
1) make a new folder in https://github.com/newrelic/docs-website/tree/develop/src/data-dictionary/events matching other data type folders in that directory (e.g., 'Transaction' folder). 
2) clone a data type entry file (like https://github.com/newrelic/docs-website/blob/develop/src/data-dictionary/events/Metric/Metric.event-definition.md) and fill it out with new info.
3) To add attributes to new data type: either add the new data type to existing attribute entries (some attributes are on multiple data types) or create new attribute entries (clone existing) and add new data type on those. Be sure to edit all fields to be accurate for new attributes.

**Comment by zuluecho9** [comment]
I did a quick rewrite of this doc https://docs.newrelic.com/docs/style-guide/article-templates/data-dictionary-style-guidelines/. Think it will do the job for now. @jpvajda if you or anyone else can additionally review it, much appreciated.

**Comment by barbnewrelic** [comment]
@zuluecho9  Even though I believe you that it's not hard, my frail learning style is that I prefer to see what to do not read what to do. Can you please set up a demo with me and the TWs as I had originally requested? We could use my Jira as a real use case in the demo. Thanks!

**Comment by jerelmiller** [comment]
@barbnewrelic feel free to put some time on my calendar as well! I helped build this feature so I'd be able to guide you through all the workings of the data dictionary.

**Comment by zuluecho9** [comment]
@jerelmiller We are actually meeting up tomorrow morning to do a walkthrough of the process. I rewrote the internal guide to reflect what I'm pretty sure is current reality. If you had time to glance through this and make sure I'm not missing anything, that'd be awesome: https://docs.newrelic.com/docs/style-guide/article-templates/data-dictionary-style-guidelines/

**Comment by jerelmiller** [comment]
Sounds good! I can do that.
