### ISSUE TITLE
Metric prefix is not correct

### ISSUE THREAD

**Issue by vcavallonr** [newrelic/docs-website#13156]
The metric prefix of the postgres metrics is not correct:
https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/postgresql/postgresql-integration/#metrics
should it be:  postgres.database  instead ?

**Comment by ashutosh887** [comment]
I would like to work on this

**Comment by paperclypse** [comment]
Thanks for the info! We're currently working to improve our OHI docs. We've pinged the writer working on this with this info and this should be addressed in docs updates in the near future. Closing this issue for now. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.
