### ISSUE TITLE
Issue: Add and manage users, groups, and roles

### ISSUE THREAD

**Issue by mtjagg** [newrelic/docs-website#1324]
### Tell us what you need
There doesn't appear to be a list of capabilities that can be assigned when a user creates a custom role.

In the product interface, it is very clear - but in the documentation, there isn't not a table or other list of potential capabilities and the ability to have view, modify, delete, or other in those specific areas.

<img width="894" alt="CleanShot 2021-03-12 at 18 40 57@2x" src="https://user-images.githubusercontent.com/76708497/111009766-849f5400-8362-11eb-9157-eefbd7a8bd54.png">

This could probably be linked to in a few areas - 

**Concepts** : https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/add-manage-users-groups-roles/#understand-concepts

And Also:

**Roles and Capabilities** : https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/add-manage-users-groups-roles/#understand-concepts

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/add-manage-users-groups-roles/
* **OS**: Mac OS 11.2.1
* **Browser**: Chrome 89.0.4389.82
* **Device**: Unknown

**Comment by zuluecho9** [comment]
I will create a jira to add screenshots from the capabilities UI to docs. Thank you.
