### ISSUE TITLE
Issue: Stream Logs from Heroku

### ISSUE THREAD

**Issue by skyshard** [newrelic/docs-website#1326]
### Tell us what you need
Is it possible to add / change attributes on logs ingested through syslog-heroku? Current it looks like only `app.name` is populated, and it is always either `app` or `heroku`, which makes it impossible to filter between logs from different apps.

### Anything else you'd like to share?
Example Heroku router log json (no level or hostname):
```json
{
  "app.name": "heroku",
  "log.timestamp": "2021-03-13T03:41:58.761854+00:00",
  "logType": "syslog-rfc5424",
  "message": "at=info method=POST path=\"/example\" host=foo.bar.com request_id=0b001234-71a5-43c6-ab01-abcdef83cf5c fwd=\"12.34.56.78\" dyno=web.1 connect=1ms service=289ms status=200 bytes=248 protocol=https",
  "plugin.type": "syslog-heroku",
  "pri": "158",
  "procid": "router",
  "timestamp": 1615606921139,
  "version": "1"
}
```

Example Heroku app log json (also has no log level or hostname):
```json
{
  "app.name": "app",
  "log.timestamp": "2021-03-13T03:41:59.517573+00:00",
  "logType": "syslog-rfc5424",
  "message": "some message here",
  "plugin.type": "syslog-heroku",
  "pri": "190",
  "procid": "worker.1",
  "timestamp": 1615606921145,
  "version": "1"
}
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/heroku-log-forwarding/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Fixed in #1450.
