### ISSUE TITLE
Issue: Introduction to AWS integrations

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#1342]
The first link on page to "AWS Integrations list" takes you to a random FSO overview page.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/get-started/introduction-aws-integrations/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Fixed in #1365 .
