### ISSUE TITLE
Issue: Understand and use data from infrastructure integrations 

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#1343]
The links in the first para to AWS and Azure fail, go to generic FSO page.

### Anything else you'd like to share?

Lots of bad links end up at FSO page, why not a 404, something that can be tracked?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/infrastructure-integrations/get-started/understand-use-data-infrastructure-integrations/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Fixed links in #1366.
