### ISSUE TITLE
Infra agent log intergration document hase logtype examples that are not present in the log parsing docs.

### ISSUE THREAD

**Issue by fw79** [newrelic/docs-website#13452]
Whiilst reviewing the documentation here (https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/) to forward winlog or winevtlog the example code shows log types of windows_application or windows_security etc.

The parsing document here (https://docs.newrelic.com/docs/logs/ui-data/parsing/) has no reference to these log types or state explicitly whether other windows_* logtypes can be used.

**Comment by ashutosh887** [comment]
I would like to work on this

**Comment by paperclypse** [comment]
Thanks for the feedback! The parsing doc isn't a reference doc for logs. Please refer to the Forward your logs doc for specific winlog and winevtlog examples.
