### ISSUE TITLE
Issue: Introduction to the Log API

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#1367]
### Tell us what you need
The link to Payload limits in the first set of bullet points takes you to the Event API limits, but the limits are actually detailed lower down on the same page (and are different)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api/
* **OS**: Mac OS 10.16
* **Browser**: Firefox 86.0
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Fixed in #1368.
