### ISSUE TITLE
Release Notes JSON endpoint returns description

### ISSUE THREAD

**Issue by cade-conklin** [newrelic/docs-website#1370]
### Is your feature request related to a problem? Please describe

The current JSON endpoint (https://docs.newrelic.com/api/agent-release-notes.json) returns a JSON with each agent, version, and attached release date.  The Release Notes Parser, a service that checks each release note to see if any changes to agent supportability, is still broken because it relies on the description of each release note to work.  This is because it uses Regexes to detect the aforementioned changes in supportability.   

### Describe the solution you'd like

I would like to have the release notes description returned for each release note in the JSON https://docs.newrelic.com/api/agent-release-notes.json.   Upon further research, the descriptions lie within the MD files in src/content/docs/release-notes/agent-release-notes in this repo.  Being able to return those with the rest of the information would give the Release Notes Parser the necessary context to do its job.

### Describe why this important to you

While this service scrapes the Release Notes to detect changes in supportability, its main purpose is to automatically detect changes we haven't accounted for in the Diagnostics CLI (a much larger service).  This is a big problem because it is hard for Software Engineers to keep up with changes in release notes, and because of that it often leads to giving our customers false-positives (a version we detect running in their system may have been EOL'd by our agent but we would still give them a confirmation that they are good to go).  In order to negate this problem, the description should be added to the JSON endpoint.

### Additional context

I am not well-versed in JS or GraphQL, but I did some digging around the repo with a suggestion from Clinton Langosch.  If there is any way that I could help any of you implement this, I would be more than open to pairing!

**Comment by jpvajda** [comment]
the release notes json was added to support a specific service’s needs that didn't  require`description`. it just required version numbers and release dates. But we can considering at that data to the JSON payload, I'll see if we can get you some pointers on how to do this @cade-conklin and perhaps you can contribute this change to the project?

**Comment by cade-conklin** [comment]
@jpvajda I just got back in for this week and I would love to see how I could contribute to this change!

**Comment by jpvajda** [comment]
Thanks @cade-conklin The team is pretty heads down in this current sprint we are in, so I'll have to see if someone can give you some pointers next week, we'd love to assist you getting this feature into the site in the near future. cc @roadlittledawn

**Comment by cade-conklin** [comment]
Awesome! We can connect about a time for next week

**Comment by jpvajda** [comment]
@cade-conklin was interested in making this change but would need some pairing time with one of us to implement, we can consider this work for `Sprint 1` if we have the bandwidth. I'll add to the list of tickets we may work on next to get a sense of how much time we need to spend paring on it.

**Comment by jpvajda** [comment]
@cade-conklin when you are ready to submit a PR for this change we'd be happy to review it. If you are intending to start work on this and need some guidance feel free to post a message in our help channel: #help-deven-websites

**Comment by roadlittledawn** [comment]
i believe this was deployed couple months ago.
