### ISSUE TITLE
Null check shall be added in the example of MS Teams notification template.

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#13790]
## How can we make our docs better?

I think it is good to update notification example for the MS teams in the following page.
https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload/#MS-Teams-example

In fact, the variable **violationChartUrl** can be null, and the notification fails by the error If it is null.
So I think null check shall be added as following;
```
{{#if violationChartUrl}} <img src="{{ violationChartUrl }}" alt="Incident Chart"> {{/if}}
```

Thanks.

**Comment by nbaenam** [comment]
I've asked @shinji-newrelic to make sure about this change through Slack and he's going to confirm it tomorrow. Meanwhile, I add this PR to the draft column. 

The replacement should be in the code inside the [Microsoft Teams example](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload/#MS-Teams-example) section. 

Replace this:
`"text": "<img src="{{ violationChartUrl }}" alt="Incident Chart">"  `
with this: 
`{{#if violationChartUrl}} <img src="{{ violationChartUrl }}" alt="Incident Chart"> {{/if}}`

**Comment by shinji-newrelic** [comment]
@nbaenam 

I found another issue in the example that double quotation (") should be escaped also.
In face, I think

Replace this:
```"text": "<img src="{{ violationChartUrl }}" alt="Incident Chart">"```
with this:
```"text": "{{#if violationChartUrl}} <img src=\"{{ violationChartUrl }}\" alt=\"Incident Chart\"> {{else}} N/A {{/if}}"```

**Comment by nbaenam** [comment]
This is the [PR:13806](https://github.com/newrelic/docs-website/pull/13806) that includes this modification.
