### ISSUE TITLE
Links to MSI not working

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/docs-website#13882]
Links to 32-bit and 64-bit MSI installer downloads on this page don't seem to work: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration/

The downloads are available, for example here:
https://download.newrelic.com/infrastructure_agent/windows/integrations/nri-mssql/nri-mssql-amd64.msi

This is happening on latest Chrome/MacOS.

**Comment by jeff-colucci** [comment]
Hi @maxlemieux! Thanks for bringing this up. This is a current bug that's affecting numerous places on the site, and the Eng team has a bug fix that's going out that should fix this.
