### ISSUE TITLE
Missing code highlighting on Azure documentation

### ISSUE THREAD

**Issue by thezackm** [newrelic/docs-website#13922]
https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/get-started/activate-azure-integrations/#get-ids

On the 2nd code block in this section, we have this note:

>The response should look similar to the response below. The subscription `id` and `tenantID` are highlighted.

However, in both light and dark mode; there is no noticeable highlighting on the code block.

<img width="1034" alt="Set up Azure monitoring integrations New Relic Documentation 2023-07-19 at 1 48 29 PM" src="https://github.com/newrelic/docs-website/assets/30831476/5ecc3b01-9613-418c-acda-e3fb2b1027b9">

<img width="1027" alt="Set up Azure monitoring integrations New Relic Documentation 2023-07-19 at 1 48 15 PM" src="https://github.com/newrelic/docs-website/assets/30831476/b896e5c8-08eb-4313-9665-d57fce599818">

**Comment by homelessbirds** [comment]
This was resolved in [this PR](https://github.com/newrelic/docs-website/pull/13946).
