### ISSUE TITLE
Issue: Upload source maps via API

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#1392]
### Tell us what you need

* Can we edit the New Relic-owned NPM package's documentation to clarify that it doesn't support changing the path for the API to the EU region? Link to: https://www.npmjs.com/package/@newrelic/publish-sourcemap

### Anything else you'd like to share?

We had a customer reach out about this request. Thank you again! 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/upload-source-maps-api/
* **OS**: Mac OS 10.14.6
* **Browser**: Chrome 88.0.4324.192
* **Device**: Unknown

**Comment by CherylFrankenfield** [comment]
Link to ticket : https://newrelic.zendesk.com/agent/tickets/450083

**Comment by urbiz-nr** [comment]
Info needs to go to README file, closing this and deleting branch.
