### ISSUE TITLE
[Improvement] Add lambda error handling into log forwarding with lambda functions

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#1404]
### Tell us what you need

The following two pages explains how to forward logs with lambda functions New Relic provides (NewRelic-log-ingestion-s3 and newrelic-log-ingestion).

https://docs.newrelic.com/jp/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/aws-lambda-sending-logs-s3/
https://docs.newrelic.com/jp/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/aws-lambda-sending-cloudwatch-logs/

In case our lambda function fails, logs won't be shipped and lost. Since AWS Lambda function has error handling feature, it could help storing logs in other places such as S3.

https://docs.aws.amazon.com/lambda/latest/dg/invocation-async.html#invocation-async-errors

Adding this feature into docs can help customers avoiding from losing logs.

### Anything else you'd like to share?

I submit the issue in aws-log-ingestion.

https://github.com/newrelic/aws-log-ingestion/issues/37

**Comment by dbarnesbrownNR** [comment]
This one looks like there might be a bit of a product change ask in here as well as a docs change. Going to investigate with the right subject matter expert so I have a better idea of what changes could be made here.

**Comment by dbarnesbrownNR** [comment]
In conversation with logging SMEs to get to the bottom of this one.

**Comment by dbarnesbrownNR** [comment]
This appears to be a product / feature request so have submitted LOG-I-433 to the team.
