### ISSUE TITLE
Include docs around entity expiration time

### ISSUE THREAD

**Issue by danielgblanco** [newrelic/docs-website#14055]
## Is your feature request related to a problem? Please describe
In Kubernetes deployments, New Relic entities are relatively ephemeral. For instance, pod entities expire after 4 hours of not sending data. This can affect navigation in the UI (i.e. an engineer trying to find a past pod) or in alerts (i.e. past alerts on pods that were deleted no longer attached to an entity).

There is a doc in Github around expiration for entities:
https://github.com/newrelic/entity-definitions/blob/main/docs/entities/lifecycle.md

And another configuring the default expiration times:
https://github.com/newrelic/entity-definitions/tree/main/entity-types

## Describe the solution you'd like

I'd love to have a doc in docs.newrelic.com that explains how entities work, what their expiration time is, and how that affects things like UI navigation or alerts.

## Describe why this important to you
It helps solve questions about entities disappearing from the UI or alerts.

## Additional context
N/A

**Comment by danielgblanco** [comment]
Hi there! The problem came mainly from two areas:

1. Alerts firing on a Kubernetes pod getting OOM killed, for example. It's super useful when an entity is attached to an alert, as it takes service owners directly into the pod view and start debugging. If the pod was killed more than 4 hours ago, the entity will not be attached, making the owner have to go to logs or other metrics via the query explorer. Not necessarily an issue with the expiration time, but it'd be good for service owners to know when entities expire.
2. When using the Kubernetes cluster view, it'd be good for service owners to know what pods they can expect to find in those views (e.g. if they go back 6 hours their pod that was not there would not be found)

**Comment by zuluecho9** [comment]
@danielgblanco Thank you, Daniel. I'm adding some info about this in this PR, if you'd like to check it out. https://github.com/newrelic/docs-website/pull/14101

**Comment by danielgblanco** [comment]
Thanks!
