### ISSUE TITLE
[nr1-help-xp] has some broken images

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#1409]
### Description

The "Install the Infrastructure Agent" article in the new relic docs app has a broken image, but this same image is fine on docs.newrelic.com

### Steps to reproduce

new relic doc link: https://one.nr/0z7wkXlGrRL
docs site: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/install-infrastructure-agent/

### Expected

The image resolves correctly and is visible in both Docs and the NR1 Help XP. 

![Screen Shot 2021-03-18 at 12 05 04 PM](https://user-images.githubusercontent.com/1395158/111675128-657d4800-87e2-11eb-8a4b-1f3750e053ab.png)

![Screen Shot 2021-03-18 at 12 05 10 PM](https://user-images.githubusercontent.com/1395158/111675166-729a3700-87e2-11eb-88bb-787aa2f7637d.png)

**Comment by caylahamann** [comment]
hello! I have some idea why this is happening. There is some caching that happens in the docs-library-service, and we add change our pages every single day. It is referring to these links that are generated by the gatsby build process, but every time the page is newly built the url changes, meaning that the cache gets stale real quick and the nr1-help-xp (which gets its data from the docs-library-service) will be referring to links that no longer exist if the page is updated.
