### ISSUE TITLE
Disable `www.` in subdomain

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#141]
## Summary

The preview site URL is www.docs-preview.newrelic.com. Can we lose the www.? Feels odd in front of a subdomain.

## Desired Behavior

Set it up to automatically direct to the non-www if we want

## Additional context

Other New Relic properties (docs, dev, forum, etc) do not use www. on sub-domains. We should address this for consistency by launch, but if we can get to it sooner that'd be great.

**Comment by jerelmiller** [comment]
Seems like something we should be able to do on amplify fairly easily. I'll take a look 👀

**Comment by jerelmiller** [comment]
This has been configured on Amplify and is now redirecting to the site without the `www` prefix.
