### ISSUE TITLE
Deployment marker release job is failing everytime on Deploy

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1410]
Relates to: #1049 

In order to resolve this issue, we'll need to decide on our approach for how we will tag our releases.  The deployment marker  is failing every time on deploy. we should look into the issue with that job.

https://github.com/newrelic/docs-website/actions/runs/664910766

```
 Invalid workflow file

The workflow is not valid. .github/workflows/release.yml (Line: 16, Col: 14): Unexpected symbol: 'GITHUB_REF:10'. 
```

This seems to be failing on line 16 of the [release.yml](https://github.com/newrelic/docs-website/blob/a84d0bb81d6585e1522e01f5ca6fd974a3762cec/.github/workflows/release.yml#L16) file 

### Acceptance Criteria

- [ ] The deployment marker doesn't fail.

**Comment by LizBaker** [comment]
Currently we don't have release versions or tags to report in our deployment marker action (causing the failure). We could supply it with a different value like the branch name, but this is less informative. We could also wait until https://github.com/newrelic/docs-website/issues/1049 comes to fruition, which is to add release versions

**Comment by jpvajda** [comment]
@LizBaker Ok, we discussed reasons why versioning the doc site may not be a great idea, however I feel it's a good standard for us to have versioning and tagging turned on, so to confirm in order for your to finish this issue, do you need a decision on how and when we'll handle #1049 ?

cc @zstix for his input on the tag/release question as we've discussed it before

**Comment by zstix** [comment]
I like utilizing releases, we just need to settle on a release version strategy:

- Do we manually create releases?
- Do we want to automatically create them?
- If so, how do we determine the release number?
- And do we also produce a changelog?

If we strictly used conventional commits, generating a release version and changelog would be trivial, but we haven't enforced them. We could still look into automation, but we'd need to make some decisions around what triggers patch, minor, and major version bumps.

**Comment by zstix** [comment]
Another option is to just increment each release (e.g. `release-274`)

**Comment by jpvajda** [comment]
Removing from Sprint as we'll need to address #1049 first before we can fix this. We decided in the short term to just remove the deployment marker job from GH actions as it won't work with release tags.
