### ISSUE TITLE
Some API docs don't have nav files

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#1417]
Many of the API docs have no table of contents. For example: 
https://docs.newrelic.com/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api/ and https://docs.newrelic.com/docs/apis/nerdgraph/examples/use-nerdgraph-manage-license-keys-user-keys/. 

For the overall API section, there should be one like the screenshot below.  

In addition, when at the bottom of the API landing page https://docs.newrelic.com/docs/apis/ and click 'view all docs' there's nothing there. 

The button link for View all docs goes here: https://docs.newrelic.com/docs/apis/table-of-contents/ but there's no table of contents.

The image below is from the docs-dev link: https://docs-dev.newrelic.com/docs/apis/rest-api-v2/get-started/introduction-new-relic-rest-api-v2

![image](https://user-images.githubusercontent.com/58010132/112220588-ab238180-8be3-11eb-852c-e3dd686421f5.png)

Is it possible to migrate those nav files?

**Comment by mmfred** [comment]
@zuluecho9 - I made this an engineering ticket because the problem is pervasive enough that I hope we can handle this through the migration tool and not by creating the files from scratch.

**Comment by zuluecho9** [comment]
Related jira https://newrelic.atlassian.net/browse/DOC-6675

**Comment by jpvajda** [comment]
This seems to be covered in several other navigation problems we are discussing @zuluecho9 Can this be closed as a duplicate and rolled into: https://github.com/newrelic/docs-website/issues/2007

**Comment by zuluecho9** [comment]
Yeah this is duplicate, closing.
