### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by barnato-v** [newrelic/docs-website#14195]
Hi this link is broken https://docs.newrelic.com/docs/apm/new-relic-apm/troubleshooting/cpu-usage-mismatch-or-usage-over-100#cause

## How can we make our docs better?

Hi this link is broken https://docs.newrelic.com/docs/apm/new-relic-apm/troubleshooting/cpu-usage-mismatch-or-usage-over-100#cause

Is there a replacement document for it?

### Doc information (don't delete this section)

It explains how to resolve the issue where there is cpu usage is showing as over 100

**Comment by ally-sassman** [comment]
Hi @barnato-v , it looks like this page was removed some time ago, so I removed it from the left nav. Thanks for letting us know!
