### ISSUE TITLE
Provide option to disable "close" button on some announcements

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#142]
## Summary

If you close the "this is a preview site" banner we remember that between sessions. That seems like it'd usually be good for announcements, but in this case I worry it means someone could forget they're on the preview site. 

Can we make this persistent/disable the close button?

## Desired Behavior

Add a flag/frontmatter attribute to disable "close" button for some announcements.

I don't think we want to disable close button for ALL announcements on docs site b/c we'll certainly have less invasive announcements in future.

**Comment by jerelmiller** [comment]
> Add a flag/frontmatter attribute to disable "close" button for some announcements.

I wonder if we create a "special case" banner on the docs-site only. The announcements configuration all live in the Gatsby theme. Unless we think we need this additional functionality everywhere and more than just this instance, I think it might be a good idea to just create an announcement banner outside of the announcement "framework" defined by the theme.

Thoughts?

**Comment by austin-schaefer** [comment]
Seems fine to me @jerelmiller —as long as we don't lose the ability to do dismissable announcements on the docs site in future, I'm fine with whatever solution.

**Comment by jerelmiller** [comment]
Totally! This would be a one-off case that lives in the docs repo itself and wouldn't interact with the announcements system, so we'd be safe.

**Comment by austin-schaefer** [comment]
Sounds good!
