### ISSUE TITLE
Remove 'Insights' from docs home page

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#1421]
I'm sure this is an easy fix but don't know how to do it. We should remove 'Insights' from docs home page; this is a deprecated product experience now that we have New Relic One query builder and we shouldn't promote it to new customers.

**Comment by dbarnesbrownNR** [comment]
@paperclypse maybe we could work on this one together tomorrow (Fri)? I think I understand the process but probably good to pair with you since it would be a first attempt for me.

**Comment by jerelmiller** [comment]
@zuluecho9 if you're talking about the Insights nav item, all you need to do is add `rootNav: false` to the yml file. You can see an example of this for the [style guide](https://github.com/newrelic/docs-website/blob/develop/src/nav/style-guide.yml#L3).

**Comment by dbarnesbrownNR** [comment]
Related PR is merged
