### ISSUE TITLE
Issue: PHP agent and Heroku

### ISSUE THREAD

**Issue by throddalmatt** [newrelic/docs-website#1441]
Seems like this page is 404'ing - not sure where it's supposed to go..

from this page: https://docs.newrelic.com/docs/agents/php-agent/advanced-installation/php-agent-heroku/

There is a link: https://docs.newrelic.com/newrelic/#plan_selector

Seems to be 404'ing - wanted to submit an issue :)

**Comment by rhetoric101** [comment]
@dbarnesbrownNR did this work in PR #1445 so I am closing this issue.
