### ISSUE TITLE
Dead link in navigation tile

### ISSUE THREAD

**Issue by thezackm** [newrelic/docs-website#14439]
https://docs.newrelic.com/docs/tutorial-dd-migration/migrating-from-dd/#migrate

Bottom of the screen; the far left (step 1) tile results in a dead end.

![Migrate from Datadog to New Relic New Relic Documentation 2023-08-31 at 1 38 26 PM](https://github.com/newrelic/docs-website/assets/30831476/517a60eb-d67f-47ec-82c5-080fa9a145e1)

current landing: https://docs.newrelic.com/docs/journey-migration/installing-monitor/
expected landing: https://docs.newrelic.com/docs/tutorial-dd-migration/installing-monitor/

**Comment by paperclypse** [comment]
This was fixed in a recent update. Closing.
