### ISSUE TITLE
Update Query Builder to fetch event information from NerdGraph

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#1443]
## Description
Currently, the _Query Builder_ within NR1 is making calls to the old _Data Dictionary Service_ REST endpoint. The old service does not have the most up-to-date information (it fetches content from the old site, which no longer exists). We need to update the Query Builder code to have it call NerdGraph directly. The new service is "stitched" in and the up-to-date information can be retrieved there.

The work needs to happen in one of our internal repositories (_insights/wanda-data-exploration_), but I wanted to make a ticket so that we could track the work on our project board. If you need additional direction, feel free to reach out.

## Screenshots
![Screen Shot 2021-03-19 at 9 32 02 AM](https://user-images.githubusercontent.com/1946433/111813077-f8c38580-8895-11eb-9612-dd39aecb92e5.png)

## Acceptance Criteria
* [x] Insights UI no longer references the old service
* [x] Insights UI makes a call to NerdGraph for the necessary attribute definitions
* [x] Code is merged and deployed to staging
* [ ] Code is merged and deployed to production
* [x] _Data Visualization_ team is updated when complete
* [x] Discuss with Paty Cuenca how that team can also use the data dictionary for the event attributes in the UI

**Comment by jpvajda** [comment]
I'll take an action to prioritize this @zstix

**Comment by jpvajda** [comment]
@austin-schaefer FYI on this. The Query Builder is still point to the old data for attributes hosted via Drupal. We are going to do the work to correct this for the Dev Team that supports the Query Builder UI, SO I was going to put that in our next sprint, if you feel this is a priority 1 issue just let me know. I feel it can wait but wanted to check with you.

**Comment by austin-schaefer** [comment]
@jpvajda : I think it's fine for this to wait for sprint 1. This would also be a good opportunity to remind that team about getting the data explorer to use the new data dictionary service, since currently I think those definitions are only visible in the old query builder.

**Comment by jpvajda** [comment]
@austin-schaefer I'm not sure if it's the same team, but i can find out.

**Comment by jpvajda** [comment]
So this is the same team and we've been talking to Paty Cuenca about getting the team involved to also make this change to use the new Data Dictionary service for the event attributes.

**Comment by jpvajda** [comment]
Maciej Smolinski has pointed us to the repos where these changes need to be made, on GH enterprise. I have the repo info for whomever needs it.

**Comment by jerelmiller** [comment]
Feel free to ask me for help as well if you need it 😄 . I helped write a lot of the original code in the query builder, so I'm pretty familiar with that codebase.

**Comment by jpvajda** [comment]
@jerelmiller Thanks! I saw your name on a lot of commits in there. 😄

**Comment by zstix** [comment]
I need to gain access to their repo so that I can PR into it, but this work is complete and ready to be reviewed by their team. For transparency, I'll post some information here:

**Before**
Notice that there is different content on the docs site vs the in-product tooltip:
![Screen Shot 2021-03-30 at 2 35 40 PM](https://user-images.githubusercontent.com/1946433/113073621-4a192200-917e-11eb-96ff-50f915516d5b.png)

**After**
This data is available via NerdGraph via our new service:
![Screen Shot 2021-03-30 at 2 42 49 PM](https://user-images.githubusercontent.com/1946433/113073657-5a310180-917e-11eb-8374-d289fc65e52a.png)

Here's the UI (running locally) making a call to NerdGraph instead:
![Screen Shot 2021-03-30 at 5 32 15 PM](https://user-images.githubusercontent.com/1946433/113073716-80ef3800-917e-11eb-9cf4-0b4de16d7934.png)

**Comment by zstix** [comment]
This has been merged into staging. A production deployment is planned for next week. I'm going to close this ticket out, since I believe the work our team needs to do is complete! 🎉
