### ISSUE TITLE
Numerous 404s in taxonomy-redirects.json

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1460]
Many, many paths in `taxonomy-redirects.json` lead to 404s. Out of 1131 lines, 208 return 404s:

* [List of all URLs that result in 404](https://gist.github.com/austin-schaefer/fe0848fe12ba13091d749757c6a3c317)
* [Spreadsheet used to create this list](https://docs.google.com/spreadsheets/d/10_Sxrg6NKOvUdF1xZn0LMMFU-zE7YDGqCih5y01ytoA/edit#gid=0) (NR ONLY)

### Acceptance criteria

For this issue to be resolved, we need:

* We know why these 404s weren't caught by the original 404-catching script, and we've updated the script to catch them in future
* We've also used the script to test all links in nav .yml files
* IDEALLY: We know what went wrong in the redirects migration script so we can see if it happened elsewhere.
* WRITER MAY BE ABLE TO DO THIS: All 404s in taxonomy-redirects.json now resolve to the correct destination 
    * For a writer to do this, we’ll need to know with confidence how to edit/work with this file and have it work reliably on local. 

### Example issue

I was not able to find much of a pattern. For example, consider lines 1155 thru 1167:

```
{
    "url": "/docs/integrations/amazon-integrations/",
    "paths": [
      "/docs/integrations/amazon-integrations/aws-integrations-list",
      "/docs/infrastructure/amazon-integrations/aws-integrations-list",
      "/docs/kubernetes-integration/amazon-integrations/aws-integrations-list",
      "/docs/integrations/new-relic-integrations/cloud-integrations/aws-integrations",
      "/docs/infrastructure-integrations/amazon-integrations/aws-integrations-list",
      "/docs/infrastructure/amazon-integrations",
      "/docs/kubernetes-integration/amazon-integrations",
      "/docs/infrastructure-integrations/amazon-integrations"
    ]
  },
```

Of these, the original `url` works, the first one under paths works but goes to the wrong place, and the others just 404:

```WORKS: https://docs.newrelic.com/docs/integrations/amazon-integrations/
RESOLVES BUT WRONG PLACE: https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list
404: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list
404: https://docs.newrelic.com/docs/kubernetes-integration/amazon-integrations/aws-integrations-list
404: https://docs.newrelic.com/docs/integrations/new-relic-integrations/cloud-integrations/aws-integrations
404: https://docs.newrelic.com/docs/infrastructure-integrations/amazon-integrations/aws-integrations-list
404: https://docs.newrelic.com/docs/infrastructure/amazon-integrations
404: https://docs.newrelic.com/docs/kubernetes-integration/amazon-integrations
404: https://docs.newrelic.com/docs/infrastructure-integrations/amazon-integrations```

**Comment by jpvajda** [comment]
After talking to @austin-schaefer  These were supposed to be handled by the migration script. They don't direct to pages, they direct to taxonomies. They also don't behave as you'd expect, so I think there's a site issue. For instance, look at the snippet I included. Some of the paths work, some don't. It's not clear why
