### ISSUE TITLE
Summarize your docs request

### ISSUE THREAD

**Issue by mahmoud-triki** [newrelic/docs-website#14635]
Hey team, we're actively using NewRelic to monitor our apps and we're glad to contribute in this great project!

## Add missing params to an aws cli command example

The documentation is about [Update Lambda Monitoring](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda/#update-sar)

In the [Update a manual Serverless application repository instal](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda/#update-sar)l section, you provided the following example:

`aws serverlessrepo create-cloud-formation-change-set \
    --application-id arn:aws:serverlessrepo:us-east-1:463657938898:applications/NewRelic-log-ingestion \
    --stack-name NewRelic-log-ingestion \
    --capabilities CAPABILITY_RESOURCE_POLICY \
    --region YOUR_REGION` 

The following param is mandatory for that command to succeed
`--parameter-overrides Name=NRLicenseKey,Value=<your-license-key>`

This is the [line](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/update-serverless-monitoring-aws-lambda.mdx#L71) that should change in the code base.

Regards,
Mahmoud.

**Comment by akristen** [comment]
Hi @mahmoud-triki ! Going to start a PR, get it reviewed by a SME, and I'll update this request here when it's merged. Thanks so much for this call out!

**Comment by akristen** [comment]
Hello @mahmoud-triki : Here is the PR that reflects your contribution! Thanks so much for taking the time to submit this to our team. https://github.com/newrelic/docs-website/pull/14741
