### ISSUE TITLE
Some pages are missing an "Edit this docs" button.

### ISSUE THREAD

**Issue by sdbedi** [newrelic/docs-website#14682]
I've noticed that the edit doc button is missing from this page:
https://docs.newrelic.com/install/java/?deployment=appServer&framework=tomcat

Other pages in the Java section appear to have the button - this appears to be a one off.

**Comment by homelessbirds** [comment]
Hi @sdbedi thanks for reaching out! Yes, this doc was built differently than our other docs so it's missing that edit this doc button. Is there anything you wanted to change?

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.
