### ISSUE TITLE
Clarification on Guided Install

### ISSUE THREAD

**Issue by sdbedi** [newrelic/docs-website#14683]
1. From this page, it appears that the Guided install of the Java Agent is intended to be a temporary measure, and a more permanent solution is to use traditional installation:
https://docs.newrelic.com/install/java/?deployment=appServer&framework=tomcat

Should we also provide guidance on removing the Guided Install of the Java APM as well? The relevant instructions appear to be here:
https://github.com/newrelic/open-install-library/blob/main/docs/uninstall/java.md

2. This page seems to directly contradict the Java APM documentation referenced above by categorically recommending guided install or manual installation - which one is correct?
https://docs.newrelic.com/docs/style-guide/writing-strategies/install-docs-guidance/

**Comment by paperclypse** [comment]
I think we should has this out with the Java APM team. We've created a Jira ticket to follow up on this. Closing this issue. In future, it's best to reach out to our hero in the documentation help channel in Slack or write a Jira ticket.
