### ISSUE TITLE
Style guide's diagram of capabilities & features is unreadable

### ISSUE THREAD

**Issue by rkbodenner** [newrelic/docs-website#14830]
## Steps to reproduce

1. Go to ['Product and capabilities: capitalization, trademarks, and usage'](https://docs.newrelic.com/docs/style-guide/capitalization/product-capability-feature-usage/#relationships-between-products-features-and-capabilities)
2. See the diagram at the bottom. The white-on-bright-green colors, combined with the low resolution, make the image unreadable. It's slightly better if you click to zoom in on the image.

## Expected behavior

The diagram and all its labels should be readable.

**Comment by bradleycamacho** [comment]
@rkbodenner oh wow that's REALLY bad haha. I'll mock something up and get that uploaded - thanks for the heads up!

**Comment by paperclypse** [comment]
@bradleycamacho What's the status on this one? Thanks!

**Comment by glitjch** [comment]
@rkbodenner if this issue is still in the back burner for you, I'd be happy to mock up a suggested fix that adheres to the Web Content Accessibility Guidelines (WCAG)!

**Comment by rkbodenner** [comment]
@glitjch Yes! Would love to see an accessible solution here 👍

**Comment by glitjch** [comment]
@rkbodenner Made a PR #16269 for your reviewing!

**Comment by rkbodenner** [comment]
#16284 fixes this, thanks!
