### ISSUE TITLE
Don't mention competitors in our page on AWS Kinesis log export

### ISSUE THREAD

**Issue by rkbodenner** [newrelic/docs-website#14891]
## Is your feature request related to a problem? Please describe

There's no particular reason to mention competitors by name in our docs :)

## Describe the solution you'd like

Blur the text in the image on this doc that mentions competitors: https://docs.newrelic.com/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose/

## Describe why this important to you

We don't want our customers thinking of competitors when they are looking for help getting their logs in to New Relic :)

**Comment by paperclypse** [comment]
Thanks for the feedback. We're going to remove the image.
