### ISSUE TITLE
Summarize your docs request

### ISSUE THREAD

**Issue by LunaticSystem** [newrelic/docs-website#14960]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

In the apache integration documentation in the VM install section it would be nice if the install instructions were not a link to another doc but in fact had the commands in a collapsable box on the main apache docs page. This would remove confusion that customers may face when they expect all of the install instructions to be in the same doc instead of having to jump to another document and back to this one. 

Link to Doc: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration/#install

For example: 
Pick your install option below, complete those steps, supplying nri-apache where it says INTEGRATION_FILE_NAME, and then return here for more instructions on [configuring your integration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration/#configuration).

[MSI](https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/install-infrastructure-host-integrations/#windows) (Windows Server)
[apt](https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/install-infrastructure-host-integrations/#apt) (Debian, Ubuntu)
[yum](https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/install-infrastructure-host-integrations/#yum) (Amazon Linuz, Centos, RHEL)
[zypper](https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/install-infrastructure-host-integrations/#zypper) (SLES)
[tarball](https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/install-infrastructure-host-integrations/#tarball)

Should instead have all of the install commands under the different package manager sections instead of linking to a generic integration installation doc that doesn't really give the customer any specifics related to the integration they are trying to install.

**Comment by rhetoric101** [comment]
@LunaticSystem thanks for your feedback. It's good for us to know that it's confusing when we send readers outside the doc to those generic installation instructions. What's challenging is that the content for all of our on-host integrations uses the same content for that part of the installation, so it would be tough for us to maintain multiple copies of that information across all of our integrations. One solution we've been exploring is to re-use content across multiple pages. That might fix your issue. At this point, that's just a proposal.

Can you think of anything else that might make it easier for you to go to the other page and come back (so you don't lose your place in the original instructions)?

**Comment by rhetoric101** [comment]
@LunaticSystem we now have an internal item to explore options to make this easier. Thanks again for pointing out this issue.
