### ISSUE TITLE
Add data retention policy for Synthetic

### ISSUE THREAD

**Issue by urbiz-nr** [newrelic/docs-website#1497]
Add data retention policies for Synthetics for new user plan.

(It's already documented for old accounts - https://docs.newrelic.com/docs/accounts/original-accounts-billing/product-based-pricing/overview-data-retention-components/#wizards-synthetics)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/manage-data/manage-data-retention/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
As requested in #documentation.

**Comment by mmfred** [comment]
requesting info from Craig Calder on this.
