### ISSUE TITLE
Issue: 404 page for v2 kubernetes on windows

### ISSUE THREAD

**Issue by svetlanabrennan** [newrelic/docs-website#15004]
## How can we make our docs better?

This page is missing: https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/install-version2-kubernetes-integration-windows/

Was it removed on purpose?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/404/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @svetlanabrennan ! @bradleycamacho is fixing this up now -- we just need to add a redirect to the new/improved k8s install experience. i'll follow up here when that PR is merged. :)
