### ISSUE TITLE
PageAction Documentation incorrect and needs revision 

### ISSUE THREAD

**Issue by aronmarden** [newrelic/docs-website#15015]
This section has a few errors that need to be addressed holistically (hence not submitting an PR) 

https://github.com/newrelic/docs-website/blob/develop/src/content/docs/browser/new-relic-browser/browser-apis/addpageaction.mdx#L27-L44

## Requirements

* Browser Pro or Pro+SPA agent (v593 or higher)
* If you're using npm to install the browser agent, you must enable the `page_action` feature when instantiating the `BrowserAgent` class. In the `features` array, add the following:

  ```js
      import { page_action } from '@newrelic/browser-agent/features/page_action';
      
      const options = {
        info: { ... },
        loader_config: { ... },
        init: {
          page_action: { enabled: true }
        }
      }
  ```

- BrowserAgent class already has all options enabled:
https://github.com/newrelic/newrelic-browser-agent/blob/1336111a250a4b70ea125c327ffde2bdd14224c0/src/loaders/browser-agent.js#L27

- And if the example was correct, page_action is not the correct import, it needs to be PageAction which you can see here: 
https://github.com/newrelic/newrelic-browser-agent/blob/main/src/features/page_action/index.js#L1

and usage example can be seen here:
https://github.com/newrelic/newrelic-browser-agent#composing-a-custom-agent-with-selected-feature-modules

**Comment by ally-sassman** [comment]
Thanks @aronmarden , I'll create a ticket to work on it this week.

**Comment by ally-sassman** [comment]
See https://github.com/newrelic/docs-website/pull/15049
