### ISSUE TITLE
Instrument the Accept cookies buttons on the Docs Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1507]
### Issue 

We currently only instrument the cookie `No` button click but not the `yes` click. 

It be cool to know how many users click on either option so we have analytics on the acceptance or denial of cookies on the docs site. 

This should be handled with a `PageAction` event, not a tessen-based event (or do we?)

### AC 

- [ ] Read this wiki on how our analytics is [instrumented](https://github.com/newrelic/docs-website/wiki/Event-Data--and--Instrumentation) 
- [ ] when a user clicks on the accept cookies button, capture that click
- [ ] store that click data on the correct NR Dashboard.

<img width="1316" alt="Screen Shot 2021-03-23 at 3 32 18 PM" src="https://user-images.githubusercontent.com/1395158/112221615-453bf780-8bed-11eb-83ba-3cd59410acb8.png">

When clicking the accept button we seem to fire the following event 

<img width="732" alt="Screen Shot 2021-03-23 at 3 32 44 PM" src="https://user-images.githubusercontent.com/1395158/112221593-3fdead00-8bed-11eb-887a-9141955a04c4.png">

**Comment by jpvajda** [comment]
I wanted to take this on as I feel it's a great way to learn about how we instrument the site.

**Comment by jpvajda** [comment]
I'm not 100% sure we actually capture the acceptance of the cookie 🤔

**Comment by jpvajda** [comment]
This may become irrelevant if we do this: https://github.com/newrelic/gatsby-theme-newrelic/issues/347

**Comment by jpvajda** [comment]
@roadlittledawn to confirm I'm reading the updated documention on how we track event data and it says


cookie_consent | occurs when a user selects No in cookie consent dialog. The event action is named opt_out.
-- | --

So it sounds like we do track the click of the `no` button, but we are clicking the the `yes` button?

**Comment by roadlittledawn** [comment]
> @roadlittledawn to confirm I'm reading the updated documention on how we track event data and it says
> 
> cookie_consent	occurs when a user selects No in cookie consent dialog. The event action is named opt_out.
> So it sounds like we do track the click of the `no` button, but we are clicking the the `yes` button?

i updated that in advance of sites actually using that from theme yet. once theme is bumped on a site, we will track clicks on `No`. i don't believe we track clicks on `Yes` currently (nor in the work i did)
