### ISSUE TITLE
Add deprecation banner to Browser REST API docs

### ISSUE THREAD

**Issue by Leels** [newrelic/docs-website#15167]
EOL has started for the REST API and has been deprecated for the Browser Agent, yet documentation remains on the site. We encourage all customers to use NerdGraph. This can be deceiving for customers. 

doc: https://docs.newrelic.com/docs/apis/rest-api-v2/browser-examples-v2/add-or-list-browser-apps-api-v2/

Is it possible to add a banner on this page that the REST API has been deprecated for Browser and that we suggest using NerdGraph? 

slack thread with API-Evolution team: https://newrelic.slack.com/archives/C0MPX17GU/p1699637353912689

Thank you!

**Comment by jeff-colucci** [comment]
Closing as we're moving this to Slack for resolution
