### ISSUE TITLE
Potential typo in incident workflow variable enum value

### ISSUE THREAD

**Issue by Tatarkow** [newrelic/docs-website#15175]
On [this docs page](https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/custom-variables-incident-workflows/) the description of `triggerEvent` variable mentions `CLOSED_TTL` trigger event. However, I have noticed that I received `CLOSE_TTL` instead.

**Comment by homelessbirds** [comment]
This has been fixed: https://github.com/newrelic/docs-website/pull/15750
