### ISSUE TITLE
Issue: .NET: Configure with NLog

### ISSUE THREAD

**Issue by sleipper** [newrelic/docs-website#1520]
The NLog advice here is to use a custom built layout, the extension provided by New Relic has a hard coded layout with set properties. We should be able to work with a NLog config file to define all this, for example:

1) Add reference to NewRelic.Agent.Api
2) Use existing layout e.g. JsonLayout but add properties specific to the the New Relic linked metadata

	
        <attribute name="entity.name" layout="${gdc:item=entity.name}" />
        <attribute name="entity.type" layout="${gdc:item=entity.type}" />
        <attribute name="entity.guid" layout="${gdc:item=entity.guid}" />
        <attribute name="hostname" layout="${gdc:item=hostname" />
3) Use Global Diagnostic Context https://github.com/NLog/NLog/wiki/Gdc-layout-renderer to add in the agent metadata

        var nrAgent = new Lazy<NewRelic.Api.Agent.IAgent>(NewRelic.Api.Agent.NewRelic.GetAgent());
        foreach (var (key, value) in nrAgent.Value.GetLinkingMetadata())
        {
			GlobalDiagnosticsContext.Set(key, value);
        }
			
Done, the logs will have the 4 pieces of metadata currently implemented https://github.com/newrelic/newrelic-logenricher-dotnet/tree/main/src/NewRelic.LogEnrichers.NLog

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/logs-context-net/net-configure-nlog/
* **OS**: Windows 10
* **Browser**: Firefox 86.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@sleipper, thanks for your input about NLog and custom-built layouts. I'll talk with our logging team to see if there's something we can add to our documentation.

**Comment by rhetoric101** [comment]
@sleipper, I am going to close this GitHub issue because we are now tracking this with our internal issue tracking system. Thanks again for your input!

**Comment by rhetoric101** [comment]
This is being tracked by Jira [doc-6714](https://newrelic.atlassian.net/browse/DOC-6714).

**Comment by austin-schaefer** [comment]
Reopening per our decision to keep GH issues open until the relevant Jira is closed

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
