### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by inderjeet-sandy** [newrelic/docs-website#15232]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/errors-inbox/version-tracking/docs/apm/agents/nodejs-agent/api-guides/guide-using-nodejs-agent-api/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 119.0
* **Device**: Unknown

**Comment by jeff-colucci** [comment]
Fixing at https://github.com/newrelic/docs-website/pull/15247
