### ISSUE TITLE
Summaries of agent release notes are too condensed

### ISSUE THREAD

**Issue by neilpdx** [newrelic/docs-website#1523]
### Tell us what you need

* It was previously possible to scroll through the release notes for each version on a single page, but now only one line is shown for each agent version, making it very difficult to compare fixes and new features between versions. It's often helpful to identify certain changes between agent versions to troubleshoot issues.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 89.0.4389.90
* **Device**: Unknown

**Comment by jpvajda** [comment]
@neilpdx  Thanks for question on this, we made a design choice to present agent release notes in a timeline like view with a summary to allow the user to quickly parse through each version and just see a highlight of that note. However your use case could be solve by using the RSS feed we provide:  https://docs.newrelic.com/docs/release-notes/agent-release-notes/go-release-notes/feed.xml

You can probably find an RSS reader or XML parser to do what you are intending to do, then you can quickly scan through the content from that feed.

Just let me know if this is reasonable for you.

**Comment by jpvajda** [comment]
@austin-schaefer adding for visibility
