### ISSUE TITLE
Clarify that Metric, Event, Log, and Trace APIs all accept License/Ingest keys

### ISSUE THREAD

**Issue by jeffreycs** [newrelic/docs-website#1525]
Our MELT (Metric, Event, Log, and Trace) APIs all accept [License keys](https://docs.newrelic.com/docs/apis/get-started/intro-apis/new-relic-api-keys/#ingest-license-key) for authentication as long as the key is supplied via the `X-License-Key` header. I see this called out in the docs on the Log API:

https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api/#json-headers

But I don't see this present in the docs on the Metric, Event, and Trace APIs:

https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/report-metrics-metric-api/
https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/introduction-event-api/
https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/trace-api/trace-api-general-requirements-limits/#headers-query-parameters

When customers write to us stating that they've received a `4xx` response from one of our MELT APIs, the issue is often that they've mistakenly used a License key with the `Api-Key` or `X-Insert-Key` header. It would be good to clarify their options within our documentation.

**Comment by rhetoric101** [comment]
@jeffreycs, thanks for your suggestion! I am working with product management to see if we can push this header information from the logging doc to the other API docs.

**Comment by rhetoric101** [comment]
@jeffreycs, I am going to close this GitHub issue because it is now in our internal tracking system. Thanks again for you input!

**Comment by austin-schaefer** [comment]
Reopening this issue per our team decision to keep GH issues open even if we have an internal ticket

**Comment by austin-schaefer** [comment]
Closing out issues older than 90 days, feel free to re-open if anyone would like us to revisit this issue!
