### ISSUE TITLE
Detail timeseries buckets and how they impact rate() and latestrate() functions

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/docs-website#15263]
## How can we make our docs better?

* We don't have a good description of timeseries buckets and how they work to impact the y-axis values.
* We don't have examples of how the `rate()` and `latestrate()` functions are impacted by the bucket width.

There are a couple things to keep in mind:

* The rate function's time interval should be less than the chart period (SINCE/UNTIL). For example, a 1 minute period should use a 1 second time interval for the `rate()` function. The y-axis values will be skewed higher and won't make sense if we try to calculate a 1 minute rate over a 1 minute period for logs that arrive every second. 

    ```
    SELECT rate(count(*), 1 second) as Logs FROM Log WHERE `labels.app` = 'my-app-name' AND `environment` = 'dev' SINCE 3 minutes ago UNTIL 2 minutes ago TIMESERIES 1 second
    ```

* The rate function sums the data points within the given time interval. The same thing can be accomplished using `count(*)` and adjusting the bucket width to the desired time interval.

    ```
    SELECT count(*) as Logs FROM Log WHERE `labels.app` = 'my-app-name' AND `environment` = 'dev' SINCE 3 minutes ago UNTIL 2 minutes ago TIMESERIES 1 second
    ```

* This is not the same as the `latestrate()` function, which provides a true rate of change for an attribute and won't work with `count(*)`. An example highlighting the difference would be helpful.
 
* On a timeseries chart, the bucket width affects y-axis values. Bucket width determins how many data points are aggregated together on a chart. This is not always obvious. More documentation is need to describe bucket width and why it should match the time interval for a `rate()` function in order to make the y-axis values make sense on a chart.

**Comment by ally-sassman** [comment]
Thanks for this suggestion, Keegan. I created a Jira ticket to be picked up in a future sprint: NR-181324

**Comment by codewithdev** [comment]
@ally-sassman and @keegoid-nr let me know i can contribute to this issue? It would be great opportunity for me to collaborate with you!

**Comment by jeff-colucci** [comment]
This should be handled in the PR that deals with the rate() function. https://github.com/newrelic/docs-website/pull/15641
