### ISSUE TITLE
CSS: Connect collapsers together, tweak appearance

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#153]
## Summary

On the preview site, collapsers are all treated as independent entities:

![image](https://user-images.githubusercontent.com/55203603/95637859-b32da180-0a47-11eb-894c-dc6de2d0dff0.png)

However, most of the time in the docs site we use collapsers to indicate related options:

![image](https://user-images.githubusercontent.com/55203603/95637876-c7719e80-0a47-11eb-8fcd-14db48b6f923.png)

## Desired Behavior

Change the CSS/layout to visually connect collapsers together. CC @djsauble

**Comment by jerelmiller** [comment]
Whether or not we keep this design long-term, I can at least explain why we chose the design we did. We are mimicking the in-product help experience, which shows these collapsers separate:

<img width="1034" alt="Screen Shot 2020-10-09 at 3 57 24 PM" src="https://user-images.githubusercontent.com/565661/95637994-259e8180-0a48-11eb-9fbf-2e9cb9a03766.png">

Would be good to get input from @djsauble for sure and might be something we'll want to coordinate with on the in-product side to keep them consistent.

**Comment by austin-schaefer** [comment]
Thanks @jerelmiller ! TBH, I'd probably suggest the same change to the in-product help. :)

**Comment by djsauble** [comment]
@austin-schaefer I'm not sure I see the difference between the docs site and the preview site. Are you concerned that we're missing a "Show all" option for each set of related collapsers?

**Comment by roadlittledawn** [comment]
yeah in the last MMF we intentionally decided to keep collapsers very basic for time being (it was last minute decision to bring them into MMF afterall). and i noted the keybinding and show all button in [issue](https://github.com/newrelic/docs-website/issues/72) / [PR](https://github.com/newrelic/docs-website/pull/98)

but thanks for filing issue to have something in our backlog :)
