### ISSUE TITLE
Metric Stream attribute quirks and features

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/docs-website#15311]
**Something missing and confusing**

When using an [AWS Metric Streams integration](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/aws-metric-stream/), attributes arrive in various dimensional metric formats. For example:

**Lambda Errors**

- `aws.lambda.Errors.byFunction`
- `aws.lambda.Errors.byAlias`
- `aws.lambda.Errors`

**Lambda Invocations**

- `aws.lambda.Invocations.byFunction`
- `aws.lambda.Invocations.byAlias`
- `aws.lambda.Invocations`

Essentially, the `.byFunction` or `.byAlias` postfix is the equivalent of writing `WHERE entity.type = `AWS_LAMBDA_FUNCTION` or `WHERE entity.type = `AWS_LAMBDA_FUNCTION_ALIAS`.

**Why is this important?**

There is a third attribute that does not include `.byXYZ`. It is not initially evident what this represents. It represents `WHERE entity.type = 'AWS_LAMBDA_REGION'`. It is regional data from CloudWatch and that is why many of the function or alias specific attributes will be NULL when viewing the data with a query like:

```sql
SELECT * FROM Metric WHERE collector.name = 'cloudwatch-metric-streams' AND aws.accountId = 'YOUR_AWS_ACCOUNT_ID' AND aws.lambda.FunctionName = 'YOUR_FUNCTION_NAME' SINCE 3 DAYS AGO
```

Another way to see just the regional data:

```sql
SELECT sum(aws.lambda.Errors) FROM Metric WHERE collector.name = 'cloudwatch-metric-streams' AND aws.accountId = 'YOUR_AWS_ACCOUNT_ID' AND displayName IS NOT NULL FACET displayName,entity.type,metricName SINCE 3 DAYS AGO
```

When querying for Lambda invocations, errors, duration, throttles, and more, it's important to use the `.byXYZ` in order to get the relevant data. Otherwise, regional data will be mixed in and skew the results.

**Existing doc**

We have an [existing doc](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/aws-integrations-metrics/) that starts to describe this and provides examples of the `.byXYZ` attributes, but does not mention what they do or what they represent. Confusion about query results when leaving off the `.byXYZ` postfix is commonplace.

**Comment by akristen** [comment]
Hi @keegoid-nr! Let me confirm the scope of the problem and your proposed fix so I can accurately convey it in a jira:

* We have an existing doc that covers different dimensional metric formats and what attributes correspond with those dim. metrics
* The problem: The doc has an incomplete list of what `.byXYZ` exist
* The problem: There is little explanation about what these attributes represent
* Solution: update docs to include the missing attribute

I have some follow up questions:

- You mention a missing attribute and that it's related to WHERE entity.type = 'AWS_LAMBDA_REGION'. I'm assuming this is another .BY attribute. Do you know what that is?
- I'm a little lost on what actions customers are meant to take to sidestep NULL. - 
- Do they need to manually add the .BY attributes? 
- Do they just 'need to know' that NULL always means `WHERE entity.type = 'AWS_LAMBDA_REGION'? 

It might be best we hop on call and go over this doc together.

**Comment by akristen** [comment]
Met with @keegoid-nr and created PR to address this confusion here: https://github.com/newrelic/docs-website/pull/15328
