### ISSUE TITLE
Localized docs lack redirect information

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#1540]
## Description
While working on moving over the translated content (#994), we noticed that the JP files did _not_ have the `redirects` frontmatter. Here's an example for one of our pages:

| Version | Description |
| - | - |
| [Website](https://docs.newrelic.com/docs/full-stack-observability/instrument-everything/get-started-new-relic-instrumentation/introduction-new-relic-integrations) | Exists in English and JP |
| [English MDX file](https://github.com/newrelic/docs-website/blame/develop/src/content/docs/full-stack-observability/instrument-everything/get-started-new-relic-instrumentation/introduction-new-relic-integrations.mdx#L10-L12) | Contains `redirects` frontmatter |
| [JP MDX file](https://github.com/newrelic/docs-website/blame/develop/src/i18n/content/jp/docs/full-stack-observability/instrument-everything/get-started-new-relic-instrumentation/introduction-new-relic-integrations.mdx) | Does not currently contain `redirects` frontmatter |

The redirects for translated pages should be the same as their english counterpart. If we move a page to a different location, we should redirect regardless of language.

## Acceptance Criteria
* [ ] All translated pages contain the same `redirects` fronmatter as their english counterpart
* [ ] Ensure that our scripts are not erroneously removing the frontmatter

**Comment by jpvajda** [comment]
I put a Sprint 1 milestone on this one as redirects are important to user expeirence, but we can discuss the effort on this one as it relates to the other work we have planned in sprint 1

**Comment by roadlittledawn** [comment]
fyi. just did quick check and it looks like we do redirect auto index pages AND any redirects in .mdx frontmatter for the locale equivalents (in this case, jp docs). we do that via:
- [auto index plugin](https://github.com/newrelic/docs-website/blob/develop/plugins/gatsby-plugin-auto-index-pages/gatsby-node.js)
- [main gatsby-node.js](https://github.com/newrelic/docs-website/blob/develop/gatsby-node.js)

**Comment by aswanson-nr** [comment]
Globbing on to what @roadlittledawn said, the redirects appear to be working properly. For example:
* [https://docs.newrelic.com/node/39691](https://docs.newrelic.com/node/39691) - redirects to "Introduction to New Relic integrations" 
* [https://docs.newrelic.com/jp/node/39691](https://docs.newrelic.com/jp/node/39691) - redirects to the Japanese version of "Introduction to New Relic integrations"

Is the goal to have those redirects listed in the front matter of the translated `.mdx` files? If so, what benefit does that give us over the current automatic process?

There's also a good chance that I'm completely missing the goal of this ticket!

**Comment by zstix** [comment]
Thanks so much for digging into this!
