### ISSUE TITLE
Issue: Fluent Bit plugin for log forwarding

### ISSUE THREAD

**Issue by cwinters8** [newrelic/docs-website#1541]
### Tell us what you need
I'm trying to follow the documentation for installing the Fluent Bit plugin, and step 1 says:

> Locate or create a `plugins.conf` file in your plugins directory.

Where exactly is plugins.conf supposed to live? I have a guess that it should be `/etc/newrelic-infra/plugins.d/plugins.conf` but it would be nice if the docs were a little clearer on this.

### Anything else you'd like to share?

OS: Amazon Linux 2 (m6g.medium instance, so ARM64 based processors)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/fluent-bit-plugin-log-forwarding/
* **OS**: Mac OS 11.2.3
* **Browser**: Chrome 89.0.4389.90
* **Device**: Unknown

**Comment by cwinters8** [comment]
I figured this out - for me, plugins.conf was at /etc/td-agent-bit, along with the td-agent-bit.conf file for updating input and output.

**Comment by urbiz-nr** [comment]
Glad you figured it out, @cwinters8. Thanks for getting it touch!

**Comment by JaggedJax** [comment]
I'm just chiming in here that the doc page is very unclear what plugin directory it is talking about or where to go about finding it. Maybe adding a link to some relevant Fluent Bit docs or at least a mention that it's in the Fluent Bit config directory. I was opening this exact same ticket when I found this issue.

**Comment by urbiz-nr** [comment]
Thanks @JaggedJax! I'm getting in touch with the team in order to improve the doc.

**Comment by urbiz-nr** [comment]
The Logging team will open a new PR with the updates.
