### ISSUE TITLE
Java Agent - Kafka Config

### ISSUE THREAD

**Issue by sdbedi** [newrelic/docs-website#15437]
The Java Agent includes custom settings to work with Kafka instrumentation: https://docs.newrelic.com/docs/apm/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues/

However, the specific config settings described on the Kafka page are missing from the general page on Java Agent configuration page: https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/

This appears to be an omission - the config page is meant to be a complete listing of publicly available config options.

**Comment by bradleycamacho** [comment]
Hi @sdbedi , thanks for reporting this! I'm going to file an internal ticket for this and close the issue out. We'll make a note to drop a message in here once we add the info. Have a great day and thanks for filing this!
