### ISSUE TITLE
Improve navigating search results by adding a more descriptive label

### ISSUE THREAD

**Issue by polfliet** [newrelic/docs-website#1545]
### Is your feature request related to a problem? Please describe
I was searching for _aws cloudwatch_ which gave me a list of results.

1. [Release note](https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/important-enhancements-gcp-aws-monitoring/)
2. [License overview](https://docs.newrelic.com/docs/licenses/product-or-service-licenses/new-relic-logs/logs-plugin-licenses/)
3. [Serverless monitoring](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/architecture/
4. [Release note](https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/new-data-aws-integrations/)

It was the 9th entry that took me to the Cloud Integrations section I was looking for. 

### Describe the solution you'd like
Of course this depends on my search term, but what I think could help navigating search results is we add a little bit more info to the labels, for example:
- Docs > Release notes
- Docs > Licenses
And probably a bunch of others. Release notes are useful but something I might want to easily filter out.

Another idea is to add a label that reflects the hierarchy of the results, something like:
- Docs > FSO > APM
- Docs > FSO > Infrastructure
Although I can see how this would become too much as well, some food for thought

### Describe why this important to you
I want to navigate search results quickly

### Additional context
![Screenshot 2021-03-26 at 08 59 36](https://user-images.githubusercontent.com/45029322/112600685-cf64a580-8e11-11eb-8f04-9974283c0511.png)

**Comment by urbiz-nr** [comment]
Thanks @polfliet ! We're releasing new docs for Cloudwatch soon, we'll be careful they appear in the results!

**Comment by jpvajda** [comment]
This would be work to optimize search within Swiftype I believe.
