### ISSUE TITLE
Quality of life: Auto-open collapsers with CMD/CTRL+F

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#155]
## Summary

On the docs site today, there's a quality of life feature that automatically expands all collapsers/collapsing exampleboxes when you hit CMD+F. This makes finding in page on long docs like (to take an extreme example) [the NET agent config doc](https://docs-preview.newrelic.com/docs/agents/net-agent/configuration/net-agent-configuration) much more effective.

This is slightly more important than it sounds because otherwise a CMD+F can miss a lot of content. Still not a drop-dead requirement, but it'd a nice thing to have by launch.

## Desired Behavior

* Pop open all the collapsers when I hit CMD+F
* Bonus: The docs site also lets you open all collapsers by hitting `s` (for show) and close them all by hitting `h` (for hide). Far less essential, but if we can get it for "free"-ish while doing the CMD+F functionality that'd be ace.

## Possible Solution

Not sure, but @roadlittledawn may know how we implemented this on the Drupal side.

**Comment by austin-schaefer** [comment]
Stalebot closed this while I was on PTO, but I'd still like to implement this.

**Comment by jerelmiller** [comment]
@austin-schaefer would you be ok with just `s` and `h`? The only reason I ask is that `CMD+F` is also the browser's "find on page" action. Does that currently confuse users who aren't expecting that?

**Comment by austin-schaefer** [comment]
Hi @jerelmiller : For this feature, I think CMD+F is actually the main use case. That lets you find content inside collapsers, for example on really large config docs like https://docs-preview.newrelic.com/docs/agents/net-agent/configuration/net-agent-configuration . At least in my experience on the current docs site, peole largely seem to be pleasantly surprised by  it rather than confused.

**Comment by jerelmiller** [comment]
That is really good to know! I'm glad I asked. Thanks for the info!
