### ISSUE TITLE
`&tvMode=true` does not work, `&tv-mode` works

### ISSUE THREAD

**Issue by kenzoarima** [newrelic/docs-website#15521]
https://github.com/newrelic/docs-website/blob/19684779d9fcbd611cd78353059aa7ae76245ed5/src/content/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard.mdx#L219

`&tvMode=true` does not work, `&tv-mode` works

**Comment by jeff-colucci** [comment]
Hi @kenzoarima, thanks for the submission! I'm going to close out this ticket and move all the work to issue 15521 above!
