### ISSUE TITLE
Issue: Use multiple accounts

### ISSUE THREAD

**Issue by mtjagg** [newrelic/docs-website#1555]
### Tell us what you need
Items are referencing old licensing models and may not be accurate any longer:

3. Configure your mission-critical hosts to use the master account's license key.
4. Use license keys from your **inexpensive** or free accounts for your remaining hosts.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/install-new-relic/account-setup/use-multiple-accounts/
* **OS**: Mac OS 11.2.1
* **Browser**: Chrome 89.0.4389.90
* **Device**: Unknown

**Comment by zuluecho9** [comment]
I'm asking around about this one. I know this is a bad doc in the new paradigm and now I'm seeing if we can just delete it with knowledge we'll soon be doing more in this area.

**Comment by zuluecho9** [comment]
We removed this. https://github.com/newrelic/docs-website/pull/1651
