### ISSUE TITLE
Add support for short titles

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#156]
## Summary

On the docs site today, many docs have two "titles":

* A "title" that is used in the HTML `<head><title>` and the H1 at the top of the page.
* A "short title" that's used, when set, in the sidebar nav instead of the "title"

This is helpful because it lets you have longer, more descriptive titles for search engines and page heads, while using pithier titles that take into account the context in the side nav.

## Desired Behavior

* Add fields for both in the page metadata
* Pull both from Drupal for existing nodes
* Use the two fields as described above

**Comment by roadlittledawn** [comment]
we could add the short title to the migration API JSON, and use that value in the .yml nav files. then there's no need to store it in frontmatter, because it's effectively set/managed in nav .yml files

**Comment by tariqahmed** [comment]
Technically we have this support, and there is a title prop in the nav, so you could have a title in the nav that's diff in the page title that's short. 

Understanding is that the goal is to have short titles in the nav....  this could be just adding instructions in the YAML file.

**Comment by tariqahmed** [comment]
Work: clarifying w/Austin what the process is. 
If there are occurrences of this happening - updating in the migration script to construct nav yaml files via such a property in the json end point.
