### ISSUE TITLE
What's New edits

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#1564]
### Tell us what you need
These revisions to published What's New articles were requested in the [Documentation channel](https://newrelic.slack.com/archives/C0DSGL3FZ/p1616703480166200).

This ticket is to keep track of that request, and any work done on it. One part of the request, to fix a duplicate page entry in the sidebar nav, was handled separately. The other requests are described in the attached files.

In working on these, I renamed some files to share them back because there were some duplicate titles. Here is the list of files we were given, and the new file names they correspond to in GH:

2:18: nerdlog-featured-weekly-releases.md
2:24: nerdlog-weekly-roundup-feb-24
3:8:  nerdlog-weekly-roundup-march-8
3:10 : nerdlog-weekly-roundup-march-11
[whatsnew.zip](https://github.com/newrelic/docs-website/files/6215932/whatsnew.zip)

**Comment by dbarnesbrownNR** [comment]
Hi @bradleycamacho and @mmfred, trying to see if I can get this one moving again. If I were to just download the zip and start making changes to the existing MDX files, would that work?

**Comment by mmfred** [comment]
finished this work: https://github.com/newrelic/docs-website/pull/1708
