### ISSUE TITLE
Issue: Get started with Incident Intelligence

### ISSUE THREAD

**Issue by hroseross** [newrelic/docs-website#1566]
### Tell us what you need

Broken Link here: https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence/#decisions

"To get started, see Decisions." - the link from "Decisions" 404s

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence/
* **OS**: Mac OS 11.2.1
* **Browser**: Chrome 89.0.4389.72
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Fixed this in https://github.com/newrelic/docs-website/pull/1567. Thank you much.
