### ISSUE TITLE
JP taxonomy list pages don't link to JP content

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1571]
### Description

Auto-generated nav pages are linking to JP content, not EN

### Steps to reproduce

1. Go to  https://docs.newrelic.com/jp/docs/agents/
2. Click on "Introduction to New Relic for Java"
3. Note that you go to EN content, even though we have a JP version

**Comment by jpvajda** [comment]
This is now fixed, 

you are now linked to the correct JP page if it exists..  

https://docs.newrelic.com/jp/docs/agents/java-agent/getting-started/introduction-new-relic-java/
