### ISSUE TITLE
Auto-generated navs are in alpha order, not taxonomy order

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1572]
### Description

Auto-generated nav pages are not using the site order. e.g. for Java on this page: https://docs.newrelic.com/docs/agents/

### Steps to reproduce

1. Go to https://docs.newrelic.com/docs/agents/
2. Notice that the categories are in alpha order
3. Notice that the docs are also in alpha order

### Expected behavior

* Use the same sort order for categories as set in the nav yml files
* Use the same sort order for docs as set in the nav yml files

### Additional context

This is a pretty severe issue because we link to these pages quite prominently—for example, the agents nav is linked from the homepage sidebar.

The order of the categories is set very intentionally—the ordering is a big part of managing user journeys, e.g. getting started naturally precedes config which naturally precedes troubleshooting.

### Screenshot example

![image](https://user-images.githubusercontent.com/55203603/112893766-f4664c00-908f-11eb-841c-2693f5936a82.png)

**Comment by austin-schaefer** [comment]
@jpvajda ^^ FYI, this is a pretty significant issue. There's a lot of weirdness to these pages, so much so I'm almost wondering if we need a small spike around these pages? I know @jerelmiller has a mega-comment somewhere talking about the complexities under the hood. :)

**Comment by jpvajda** [comment]
@austin-schaefer isn't this the same problem? https://github.com/newrelic/docs-website/issues/566

**Comment by austin-schaefer** [comment]
@jpvajda Yeah looks very similar to #566. We should figure out how we prioritize that, it's showing up in lots of places and creating lots of strange experiences.

**Comment by austin-schaefer** [comment]
Closing and rolling into #566
