### ISSUE TITLE
Wrong steps by Linux installation 

### ISSUE THREAD

**Issue by vcavallonr** [newrelic/docs-website#15826]
By the Linux Insztallation https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration/#linux Step 4 and 5 refers to nginx instead of ms-sql

**Comment by jeff-colucci** [comment]
Hi @vcavallonr, I reached out in Slack but I didn't hear anything back so I am closing this ticket for now. If you need further assistance with this issue, please reach out to the Doc help channel and the hero will be happy to get you set up with what you need. Thank you!
