### ISSUE TITLE
Auto-generated pages ignore capitalization

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1584]
### Description

Auto-generated nav pages ignore capitalization, which results in things like `AWS` becoming `Aws` or `NET` becoming `Net`. This is a problem because we need to follow our internal branding guidelines and other companies' branding guidelines.

Strangely this doesn't affect all instances. For example, `Partner API` here is `Partner API` https://docs.newrelic.com/docs/new-relic-partnerships/

### Steps to reproduce

1. Go to https://docs.newrelic.com/docs/integrations/
    * Notice that `AWS` is `Aws`
    * Notice that `Google Cloud Platform` is `Google cloud platform`
2. Go to /src/nav/integrations.yml and notice that these are correct in the yml file

```      - title: Cloud integrations
        pages:
          - title: AWS integrations
            path: /docs/integrations/new-relic-integrations/cloud-integrations/aws-integrations
          - title: Google Cloud Platform
```

### Expected behavior

Capitalization set in yml files applies to both left nav and auto-generated nav pages

### Screenshots

![image](https://user-images.githubusercontent.com/55203603/112909663-bde7fb80-90a6-11eb-83c6-0cdaf500559d.png)

**Comment by austin-schaefer** [comment]
Likely relates to #566

**Comment by jpvajda** [comment]
This doesn't seem to be an issue any longer. closing.
