### ISSUE TITLE
Vendor list does not have latest JDK version

### ISSUE THREAD

**Issue by NarenAnandan** [newrelic/docs-website#15857]
The vendor list does not show the latest JDK (java 21) versions. For example latest Amazon Corretto JDK is 21, but the list shows only until 20. 

https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent/#jvm

**Comment by jeff-colucci** [comment]
Hi @NarenAnandan, thanks for letting us know! We'll put in a ticket for getting this fixed ASAP!
