### ISSUE TITLE
Auto-generated index pages have no navigation sidebar

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1585]
### Is your feature request related to a problem? Please describe

Auto-generated navs have no sidebar, which creates some funny inconsistency.

Compare:

* https://docs.newrelic.com/docs/infrastructure/table-of-contents/

With its "child" nav:

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/

### Describe the solution you'd like

All nav pages (whether they're at the root level or deeper in the tree) have a sidebar that helps users figure out where they are in the site.

I think this would be something we could consider for the future, to have all pages just show the relative navigation for each index page as a user moves up and down the hierarchy of the page structure.

**Comment by jpvajda** [comment]
Closing in favor of this follow up nav issue #2007
