### ISSUE TITLE
OpenTelemetry metrics not conforming to semantic conventions

### ISSUE THREAD

**Issue by jmezach** [newrelic/docs-website#15870]
While reading through [this doc](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-implementation-guide/) I noticed that New Relic seems to still use the "old" metric names when using OpenTelemetry. Specifically [this list](https://github.com/newrelic/docs-website/blob/ed50f6f9a729636ee726572efeb200757170d8e8/src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-implementation-guide.mdx#L39C1-L41C21) seems to use the old names according to [this blog](https://opentelemetry.io/blog/2023/http-conventions-declared-stable/#http-server-duration-metric) from the OpenTelemetry project.

This is also apparent in the product itself and not just in the docs. For example, on the Kubernetes tab of an OpenTelemetry service there are two charts called Service throughput (rpm) and Service response time (ms). Both of these charts base their data on the `http.server.duration` metric, but our services conform to the new semantic conventions so they report a metric called `http.server.request.duration` so these charts remain empty.

**Comment by rhetoric101** [comment]
@jmezach thank you for your helpful comments! We do need to update our docs to clarify that you can send in both the old and the new names. Also, we need to make some updates to our Kubernetes UI to accommodate this.

**Comment by ally-sassman** [comment]
Hi @jmezach , I appreciate your feedback, and I'll be fitting this into an upcoming sprint.

**Comment by ally-sassman** [comment]
Closing this issue because we removed metric references and replaced them with links to the OTEL docs (for example, the `http.metrics` reference on https://docs.newrelic.com/docs/opentelemetry/get-started/apm-monitoring/opentelemetry-apm-ui/#golden-signals
