### ISSUE TITLE
Feedback: Retrieve dSYMs for Bitcode apps

### ISSUE THREAD

**Issue by lbrownell-gpsw** [newrelic/docs-website#1592]
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/configuration/retrieve-dsyms-bitcode-apps/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

About going to "iTunes Connect" to get dSYMs:
- It's no longer called iTunes Connect, it's App Store Connect.
- There is no "My Apps", it's just Apps.
- Within an app, there is no "Activity", but there is Test Flight.
- Within Test Flight, you can select a version and build, and look at the details.
- However, at best it will say "Includes symbols -- Yes", but there is no way to download them.

If you know the magic formula to download bitcode-ready dSYM files from Apple, probably via ALTOOL or the like, please provide that information, but in any case, remove this, or mention that it used to be a way to get them but it no longer works. This comes up as the default answer in a Google search, which is not good.

Thanks.

**Comment by urbiz-nr** [comment]
Thank you for your feedback, @lbrownell-gpsw, we're looking into it!

**Comment by urbiz-nr** [comment]
The mobile instrumentation team has added this to their backlog, will be fixed then.
