### ISSUE TITLE
Feedback: Notification channels: Control where to send alerts

### ISSUE THREAD

**Issue by brent-yearone** [newrelic/docs-website#1594]
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?
Make the instructions correct. I followed the instructions for getting push notifications, but no dice. Screenshots would be nice. An explanations of what the following User channel means would be even better: 

default.owner.47cb309c-da00-4068-936c-529b4ccaa5e1@fakedomain.newrelic.com

That's on my account. I didn't put it there. I certainly don't want my notifications going to fakedomain.newrelic.com. WTF???

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/notification-channels-control-where-send-alerts/
* **OS**: Mac OS 10.15.6
* **Browser**: Safari 14.0.3
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Had a slack convo about this: it's true that New Relic One user model users (v2 users) can't be chosen as users when choosing notification channels in UI, and can't be used for mobile notification pushes. The workaround is adding the user's email instead. I will add this in there soon, thanks @brent-yearone.

**Comment by zuluecho9** [comment]
Created this: https://newrelic.atlassian.net/browse/DOC-6704. Will do a little of this now, the notification channel part, as its easier.

**Comment by zuluecho9** [comment]
Closed this with PR work done here: https://github.com/newrelic/docs-website/pull/1645

**Comment by zuluecho9** [comment]
Something I sent to alerts team about the email weirdness. 

I think this would be a bug fix.
When a customer signs up for a new account in the new account/user paradigm (aka v2 user model), a dummy v1 Owner user and email address is created behind the scenes (for tech-debt reasons, v2 orgs require a v2 owner; this will eventually be fixed).
One of the limitations of the new account/user model is that these users can't use the 'user' Alerts notification channel. But apparently that initial hidden v1 Owner user is still visible in the 'user' notification channel. As you can see here, it seems it led to some confusion https://github.com/newrelic/docs-website/issues/1594
I'm wondering if we can disable that weird dummy email address from showing up.

(that's my understanding of what's happening, i could be wrong)
