### ISSUE TITLE
Issue: Synthetic monitor public minion IPs

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#1610]
>IP addresses for released locations are subject to change. If a change is needed, New Relic will attempt to proactively notify customers prior to any changes.

It is written as above, but I would like to know exactly how and with how much grace I will be notified.

**Comment by urbiz-nr** [comment]
Thanks for the feedback, @qryuu! We're looking into it.

**Comment by urbiz-nr** [comment]
@qryuu - We've updated the docs to provide further detail, it should go live within the next hours.

**Comment by urbiz-nr** [comment]
Fixed in #1619.
