### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by michel47** [newrelic/docs-website#16237]
is there a Perl Agent for New Relic ?
(I was redirected to a not-found page from the NewRelic AI chat)

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/404.html
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @michel47. We don't have a dedicated Perl agent, but Perl was supported via the C SDK: https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/c-sdk-compatibility-requirements/#language-release 

From the doc:

> The C SDK allows you to instrument any application on Linux, provided:
> 
> You must have access to the source code.
> The target language must be able to import C libraries.
> You can use the C SDK to create instrumentation for applications written in C and C++. You can also use it in languages like Perl, which are implemented in C or C++, and in any language that has a foreign function interface with C.
> 

Unfortunately it does appear that the C SDK is deprecated, so I'm going to follow up with the NR AI squad and let them know about your experience!
