### ISSUE TITLE
Broken link in "Install the ECS integration" doc page

### ISSUE THREAD

**Issue by csalvador-nr** [newrelic/docs-website#16236]
There's a broken link here: https://github.com/newrelic/docs-website/blob/701b7fc1ba83152c748d06a69797a31ddf241620/src/content/docs/infrastructure/elastic-container-service-integration/install-ecs-integration.mdx#L25

I've tried to find some alternative articles or AWS documentation where the concept of "sidecars" in ECS is defined but haven't found any. It might be worth considering deleting the reference directly.

**Comment by akristen** [comment]
https://github.com/newrelic/docs-website/pull/16242 PR addressed here
