### ISSUE TITLE
Add an RSS feed for Security Bulletins

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#1627]
### Is your feature request related to a problem? Please describe

We've had a few requests for RSS for security bulletins and What's New.

### References 

https://github.com/newrelic/docs-website/wiki/Site-Architecture#-docs-as-a-service-json-and-xml-endpoints

### Describe the solution you'd like

* Add an RSS endpoint for Security bulletin data
* Add an RSS indicator UI element to the [security bulletins category](https://docs.newrelic.com/docs/security/new-relic-security/security-bulletins/) and/or the [security bulletins doc](https://docs.newrelic.com/docs/security/security-privacy/information-security/security-bulletins/)

### Describe why this important to you

Support and solutions folks have been in touch to ask for this. I suspect users would find it helpful as well.

**Comment by roadlittledawn** [comment]
@austin-schaefer question re: where we add RSS link / icon. unlike release notes and what's new content, there's nothing in Gatsby right now that distinguishes a security bulletin page from any other basic page (it uses the standard `docPage.js` template to display its `.mdx` content). and the [security bulletins index page](https://docs.newrelic.com/docs/security/new-relic-security/security-bulletins/) is automatically generated and has no explicit / reliable way of knowing its displaying security bulletins and should display the RSS feed on it.

do you think adding the RSS link / icon somewhere on the [security landing page](https://docs.newrelic.com/docs/security/) would be sufficient? or do you think we really need it on either the security bulletins index page or each of the individual security bulletin pages?

**Comment by austin-schaefer** [comment]
@roadlittledawn : I think adding it to the two pages you linked is sufficient, particulary if we can do something with icons or tiles or similar to help it stand out a bit more. If users have trouble finding it later we can always do some work to expose it in more places. Thanks!
