### ISSUE TITLE
"Latest release" page in agent docs does not go to anything

### ISSUE THREAD

**Issue by lrafeei** [newrelic/docs-website#16279]
## Description

Within the APM configuration docs for each agent, the "Latest release" link does not go to anything.

## Steps to reproduce

On the left hand side menu of the [NR docs page](https://docs.newrelic.com/)
Monitor Your Data > 
Application performance monitoring > 
Installation and configuration > 
Python Monitoring > 
Compatibility and releases

There is a link for “Latest release” which goes to the following URL: 
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/current/

Which there is no page for.  The same issue exists for other agents as well (Ruby, .NET, et cetera). 

## Expected behavior

Either this should automatically link to the top most entry in the release notes page for the respective agent or this link should be removed

## Screenshots

<img width="1286" alt="NR_docs_latest_release_link" src="https://github.com/newrelic/docs-website/assets/84813886/34ae51ac-decd-4ac4-8764-b05f2db4882d">

**Comment by meems1996** [comment]
I checked the agents' latest release pages and they all have pages that lead to the latest release now. Should this be closed?

**Comment by lrafeei** [comment]
Oh, it seems to be going to the right area now!  I'll close the ticket.
