### ISSUE TITLE
Add RSS feed for What's new data

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1630]
### Is your feature request related to a problem? Please describe

We've had a few requests for RSS for What's New.

### References 

https://github.com/newrelic/docs-website/wiki/Site-Architecture#-docs-as-a-service-json-and-xml-endpoints

### Describe the solution you'd like

* Add an RSS endpoint for What's new data
* Add an RSS UI element to [whats new](https://docs.newrelic.com/whats-new/) for finding the RSS feed
* document this new feed [here](https://github.com/newrelic/docs-website/wiki/Site-Architecture#-docs-as-a-service-json-and-xml-endpoints) 

### Describe why this important to you

Support and solutions folks have been in touch to ask for this. I suspect users would find it helpful as well.

**Comment by paperclypse** [comment]
Our team were chatting about add RSS to what's new this morning and then I found this. We're pretty in favor of this idea and the PMM team is too. Thanks!

**Comment by austin-schaefer** [comment]
Hey @roadlittledawn , lemme know when this ships—I'd love to announce to sales, support, PMM, etc
