### ISSUE TITLE
Resolve Data Plus Edition Discrepancy

### ISSUE THREAD

**Issue by karikarshivani** [newrelic/docs-website#16326]
## How can we make our docs better?
Should this [line](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/accounts/accounts-billing/new-relic-one-pricing-billing/data-ingest-billing.mdx#L61) be changed from `Requires Pro or Enterprise` to `Requires Standard, Pro or Enterprise`?

It seems that the Data Plus option [may be available](https://newrelic.com/pricing?#pricing_plan-data) through the Standard edition.

Please let me know if I'm missing/misunderstanding something

**Comment by rhetoric101** [comment]
@karikarshivani thanks for pointing out this inconsistency! We are going to correct this in 16343.
