### ISSUE TITLE
Issue: Record and monitor deployments

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#1633]
### Tell us what you need

It needs to be clarified in the docs that Deployment markers currently are not available to standard users. It is a feature that appears to only be available to PRO + users. (If I am mistaken, please correct me!)

Please also check with product if this is how it should be. I would really prefer this to be available to all customers. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/

**Comment by urbiz-nr** [comment]
Thanks for your feedback, @dralph3344 . We're looking into it!

**Comment by urbiz-nr** [comment]
Checked with the team, this is available for all FSO users.
