### ISSUE TITLE
Issue: 404 Missing Page 

### ISSUE THREAD

**Issue by ahealy-newr** [newrelic/docs-website#16358]
## How can we make our docs better?
Missing link when opening JavaScript Errors Page link from here: https://docs.newrelic.com/docs/browser/browser-monitoring/troubleshooting/troubleshoot-your-browser-monitoring-installation/#check_js_monitors 

### Doc information (don't delete this section)

* https://docs.newrelic.com/404.html
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by ally-sassman** [comment]
Thanks for letting us know about this broken link! I've fixed it in this PR: https://github.com/newrelic/docs-website/pull/16364
