### ISSUE TITLE
kernel_modules_refresh_sec mentions CloudSecurityGroups

### ISSUE THREAD

**Issue by otteydw** [newrelic/docs-website#1639]
### Tell us what you need

At this link https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#kernel-modules-refresh-sec

The section for kernel_modules_refresh_sec actually mentions CloudSecurityGroups.  I think this was a copy/paste error from the section above.

![20210331-034455](https://user-images.githubusercontent.com/11666012/113202627-f7e90700-9238-11eb-8a2d-ae11ad6510bd.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
@otteydw Thanks for bringing this to our attention! I'll chat with our engineers and see what changes we should make to this.

**Comment by bradleycamacho** [comment]
@otteydw Sorry for the massive delay on this! I finally got the information I need and will be making an edit on this doc soon.
