### ISSUE TITLE
/etc/apt/trusted.gpg.d/newrelic-infra.gpg may need to be made readable

### ISSUE THREAD

**Issue by phillip-odam** [newrelic/docs-website#16463]
Concerning https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux/

At least for Ubuntu 22.04 (where UMASK seems to default to 027), right after executing `curl -fsSL https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/newrelic-infra.gpg` I think the command `sudo chmod a+r /etc/apt/trusted.gpg.d/newrelic-infra.gpg` is needed.

Without the read permission change when executing sudo apt-get update the following is output `W: http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease: The key(s) in the keyring /etc/apt/trusted.gpg.d/newrelic-infra.gpg are ignored as the file is not readable by user '_apt' executing apt-key`. And so attempts to install newrelic-infra fail.

**Comment by jeff-colucci** [comment]
Addressed in https://github.com/newrelic/docs-website/pull/18321
