### ISSUE TITLE
Feedback: Get app and other IDs in New Relic One

### ISSUE THREAD

**Issue by wkunker** [newrelic/docs-website#1654]
### Tell us more about your feedback

The APM: AppId section is documented as a circular button with an "i" in it, but when I actually look at the APM page for an app, it shows an icon which looks like a tag with a number next to it. Clicking the tag icon seems to open the metadata panel as expected with the "i" icon. I was unable to find the "i" icon anywhere on the page.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/rest-api-v2/get-started/get-app-other-ids-new-relic-one/
* **OS**: macOS Catalina 10.15.7
* **Browser**: Firefox 86.0.1 64-bit
* **Device**: MacBook Pro (15-inch, 2019)

**Comment by zuluecho9** [comment]
We have an existing jira for this problem. I will prioritize this jira. Thank you much @wkunker . 

jira: DOC-6666

**Comment by urbiz-nr** [comment]
@wkunker FYI this has been fixed in #1826.
