### ISSUE TITLE
Issue: 404 returned when attempting to add Heroku HTTPS drain

### ISSUE THREAD

**Issue by amleaver** [newrelic/docs-website#16595]
Following the steps outlined for Heroku HTTPS drains at https://docs.newrelic.com/docs/logs/forward-logs/heroku-log-forwarding/

1. Click "Add data" from the New Relic dashboard
2. Search for Heroku data source
3. Click "Heroku" tile

**Expected Results**

Modal opens to allow the configuration of an HTTPS drain.

**Actual Results**

I'm redirected to https://docs.newrelic.com/docs/logs/enable-logs/enable-logs which returns a 404 and prompts me to raise this issue.

Interestingly I'm able to the click the "Herokuk (syslog)" tile which does open a configuration modal.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/enable-logs/enable-logs
* **OS**: MacOS Ventura 13.2.1
* **Browser**: Chrome 122
* **Device**: MBP 16 2023

**Comment by homelessbirds** [comment]
Thanks so much @amleaver. This has been fixed!
