### ISSUE TITLE
Pull Build time data from Amplify for Docs Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1661]
Relates to #1656

In order to understand our avg build time for the Docs Site over a longer period of time we need to pull build data from Amplify.  @aswanson-nr pulled 30 build records quickly but that only resulted in a `5m and 37s` average for build times which isn't reflective of our reality using Amplify.

### Acceptance Criteria 
- [x] pull ~1000 build records from Amplify
- [x] provide that data in the raw UTC Time in a google sheet share with @jpvajda 
- [x] @jpvajda will convert the time and do some average calculations 

### Results

![Screen Shot 2021-04-13 at 5 49 05 PM](https://user-images.githubusercontent.com/1395158/114634866-bae13380-9c80-11eb-8660-a32d8e69c38e.png)

**Comment by nr-kkenney** [comment]
you can use an aws sdk like this: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/amplify.html#Amplify.Client.list_jobs

**Comment by nr-kkenney** [comment]
here is the script I wrote up for this: https://gist.github.com/nr-kkenney/87f98ee7fdacc60213dfd71496fc3ae1
didn't think it was worth committing to one of our repos 🙈

**Comment by austin-schaefer** [comment]
Histogram view I whipped up for fun:

![image](https://user-images.githubusercontent.com/55203603/114636170-39d36d80-9c7b-11eb-9166-edc4e3f00515.png)
