### ISSUE TITLE
Issue: Android agent configuration and feature flags

### ISSUE THREAD

**Issue by VladSVAssets** [newrelic/docs-website#1664]
### Tell us what you need

* If you've found something inaccurate, what is it?
At
```
NewRelic.withApplicationToken(<NEW_RELIC_TOKEN>)
        .withDefaultInteractions(false)
        .withCrashReporting(true)
        .start(this.getApplication());
```

".withCrashReporting(true)" is wrong. There is no builder method, only "withCrashReportingEnabled(boolean enabled)" which has been deprecated from versions 6.0.0+ I think.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/api-guides/android-agent-configuration-feature-flags/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@VladSVAssets, we updated the topic with your suggested change. It should be included in our first build tomorrow morning (April 6th).
