### ISSUE TITLE
Issue: indicator icons render poorly on dark mode

### ISSUE THREAD

**Issue by throck** [newrelic/docs-website#1667]
The Trace Details UI includes a table that shows Span properties and indicator icons; in dark mode, the icon in every other row is nearly indistinguishable from the background:

![image](https://user-images.githubusercontent.com/1069674/113445535-0d3e6c80-93c4-11eb-8ec4-bbb4bc67a951.png)

Looks fantastic on light mode:

![image](https://user-images.githubusercontent.com/1069674/113445586-21826980-93c4-11eb-9050-45f487602be4.png)

This doc page is the first case of this issue I've encountered, but this issue probably manifests in other pages

### Doc information

* https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/ui-data/understand-use-distributed-tracing-ui/

* **OS**: macOS Mojave
* **Browser**: Chrome 89.0.4389.114
* **Browser**: Firefox 87.0

**Comment by rhetoric101** [comment]
@throck: Yes, thanks you for noting that icons aren't showing up clearly in dark mode. We'll work with out team to improve the visibility!

**Comment by jpvajda** [comment]
It seems these pngs aren't used in other areas of the site, but it's possible we could pull svg icons from feather or from nr1 icon libraries and replace these so they are able to better support dark and light mode.

**Comment by urbiz-nr** [comment]
This has been reported again in the documentation channel.

**Comment by jpvajda** [comment]
removing stale label
