### ISSUE TITLE
Send `ajs_user_id` to Google Analytics for UVEC

### ISSUE THREAD

**Issue by zoezhou1113** [newrelic/docs-website#1668]
In order to exclude traffic from existing customers, the Docs sites need to add the customer’s user ID in `ajs_user_id`as part of the `properties{} ` in `tessen.track() `or `tessen.page() `events fired. Here is an example:
![image](https://user-images.githubusercontent.com/80297589/113451472-0a497900-93d0-11eb-9660-c17f2ea57edf.png)

After that, the GA destination needs to be updated to send customer_user_id as a custom dimension (I can help with completing this step in Segment). 

This was requested by Mark Buchanan.

### Acceptance Criteria

- [ ] The  Docs sites need to add the customer’s user ID in `ajs_user_id `as part of the `properties{} ` in `tessen.track() `or `tessen.page() `events fired.
- [ ] the GA destination needs to be updated to send `ajs_user_id` as a custom dimension. - @zoezhou1113 to assist.

**Comment by jpvajda** [comment]
@zoezhou1113 what's the urgency on this request? 

@roadlittledawn does this resonate the way it's defined? I'm not 100% clear on what we'd need to do here, but perhaps you have some insights?

**Comment by zoezhou1113** [comment]
@jpvajda Making the cookies work is more urgent. Segment and GA tracking both rely on cookies. That's probably the main reason behind a lot of issues I'm seeing in the data. When the cookies are working, this should be a relatively simple update.

**Comment by jpvajda** [comment]
@roadlittledawn pointed out that we can't do this without authentication being in place, as we don't have `customer_user_id` as a user can't login, this will be considered a future enhancement when we tackle site authentication.

**Comment by zoezhou1113** [comment]
The customer_user_id can be retrieved from the cookies. After a user lands on a product page, the customer_user_id will be appended to subsequent pageviews and events.

**Comment by roadlittledawn** [comment]
@zoezhou1113  oh interesting. should we use the cookie named `ajs_user_id`? that seems to have my NR user ID

**Comment by zoezhou1113** [comment]
@roadlittledawn Confirmed with our developer Erik Hedin, and that's the one he is using

**Comment by jpvajda** [comment]
I've update the AC to reference `ajs_user_id`
