### ISSUE TITLE
Almost all APM Browser Monitoring documentation links are broken

### ISSUE THREAD

**Issue by ChrisAtchison** [newrelic/docs-website#16756]
## Description

Most documentation links in APM agents no longer work on GitHub and docs.newrelic.com

## Steps to reproduce

Examples:
1.  .NET APM [First five links](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/apm/agents/net-agent/other-features/browser-monitoring-net-agent.mdx)
2. Python APM [First four links](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/apm/agents/python-agent/supported-features/browser-monitoring-python-agent.mdx)

## Expected behavior

Links properly lead to documentation pages

## Additional context

It seems to be present across all links leading to `docs/browser`

## Environment

Production

**Comment by ChrisAtchison** [comment]
It is the same on the docs.newrelic.com site
1. https://docs.newrelic.com/docs/apm/agents/python-agent/supported-features/browser-monitoring-python-agent/
2. https://docs.newrelic.com/docs/apm/agents/net-agent/other-features/browser-monitoring-net-agent/

**Comment by ChrisAtchison** [comment]
It seems almost all apm related documentation links are broken, I'm seeing issues with almost every link in the APM naming page for example
https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/app-naming/name-your-application/

**Comment by meotimdihia** [comment]
I confirm this problem. Please fix it.

**Comment by thevops** [comment]
Same for https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/best-practices/opentelemetry-best-practices-overview/#traces and many more

**Comment by LizBaker** [comment]
hi folks, this is fixed now for docs.newrelic.com. as far as github goes the links aren't set up to work with github's markdown because they're relative to gatsby's knowledge of our files (/docs) and not github (/src/content/docs)
