### ISSUE TITLE
Serve a subset of docs content data via a new json endpoint 

### ISSUE THREAD

**Issue by murphpdx** [newrelic/docs-website#1678]
### Is your feature request related to a problem? Please describe

This isn't a bug it's a feature request. Our team would like to request an additional document type be added to [this endpoint](https://docs.newrelic.com/api/nr1/content/nr1-announcements.json). These documents would be used by the onboarding checklist and would be displayed in a modal in NR1.  

* docsID
* learnMoreLink 
* An array of [headings and bodies]

### Describe the solution you'd like

Outlined above

### Describe why this important to you

This feature supports onboarding new customers and leveling up existing customers. 

### Additional context
![Screen Shot 2021-04-02 at 4 17 11 PM](https://user-images.githubusercontent.com/7244569/113460882-1254e900-93cf-11eb-986b-7e16fb0ac99f.png)

**Comment by jpvajda** [comment]
@murphpdx I'm not sure I understand, when you say  `request an additional document type` what type of document are you referring to? that endpoint is specifically for what's new posts only. 

Can you tell us what problem you are trying to solve from a product perspective the perhaps we'll have a better understanding of the need here:

It sounds like you are trying to pull specific parts of a document into some application based on these items you listed:


-     docsID
-    learnMoreLink
-   An array of [headings and bodies]

You may actually be interested in tapping into the docs library service for this content. but we can discuss the solution once we better understand the problem.

**Comment by zstix** [comment]
As a heads up, `docsID` is a vestige of the previous site that we don't natively support in the new setup. We special-built that for Whats new posts to support the service that fetches those docs, but I'm hesitant to build more features relying on it since it's a bit of an anti-pattern currently.

**Comment by murphpdx** [comment]
We would like to extend the service that fetches from that service. 

> @murphpdx I'm not sure I understand, when you say `request an additional document type` what type of document are you referring to? that endpoint is specifically for what's new posts only.
That's right, I guess instead of endpoint I should have said service. We would need an additional endpoint to retrieve the new document type. We don't want them to live on the announcements endpoint because we don't want these documents mixed in with What's New. 

> Can you tell us what problem you are trying to solve from a product perspective the perhaps we'll have a better understanding of the need here:
The screenshot shows what we'd like to display. We want to use the Docs cms to let internal Relics create docs that would only live on the onboarding checklist. 


> It sounds like you are trying to pull specific parts of a document into some application based on these items you listed:
> 
> * ```
>   docsID
>   ```
> * ```
>   learnMoreLink
>   ```
> * ```
>   An array of [headings and bodies]
>   ```

Yes, we would like to pull these parts of a document and put them into the frontend BUT these documents would not have any other use and would not contain any other fields.

> You may actually be interested in tapping into the docs library service for this content. but we can discuss the solution once we better understand the problem.

**Comment by jpvajda** [comment]
@polfliet Just FYI on this request. We can discuss further what is being asked for here.

 @murphpdx  Unfortunately we don't currently provide what you are looking for in any way, this type of functionality would be an entirely new "service" endpoint we'd have to build and support. This service work not on our roadmap at this time.  So if this is something your team is looking to create we'd have to align on that across our product teams and ensure we align our roadmaps. -- I'm happy to discuss this further with whomever set's PLGs product roadmap.

**Comment by jpvajda** [comment]
closing as won't do as another approach is going to be taken.
