### ISSUE TITLE
Issue: PHP agent compatibility and requirements

### ISSUE THREAD

**Issue by NiklasBr** [newrelic/docs-website#1681]
### Tell us what you need

PHP 8 was released late November 2020. PHP 8 will soon see its fourth minor patch (8.0.4) and it would be nice if New Relic [installed via these instructions](https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-ubuntu-debian/) was updated to support it.

### Anything else you'd like to share?

Current documentation says:

> New Relic supports PHP versions 5.3, 5.4, 5.5, 5.6, 7.0, 7.1, 7.2, 7.3, 7.4.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/php-agent/getting-started/php-agent-compatibility-requirements/
* **OS**: Windows 10
* **Browser**: Firefox 87.0
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @NiklasBr, we'd be more than happy to update our docs when our PHP agent does support PHP 8. However, it doesn't at this time. If you'd like, you can file this as a enhancement request issue in our newrelic-php-agent repo here: https://github.com/newrelic/newrelic-php-agent/issues/new/choose

Alternately, you could jump into the existing PHP 8 issue and mention your support for this enhancement: https://github.com/newrelic/newrelic-php-agent/issues/35

Thanks!
