### ISSUE TITLE
NRQL drop rules: Backtick clarification

### ISSUE THREAD

**Issue by GlenOFoghlu** [newrelic/docs-website#16838]
## Is your feature request related to a problem? 

Customer raised an issue with support, stating that drop rules for logs do not work if their are back ticks in the NRQL string. This is not documented in our drop rule docs -> https://docs.newrelic.com/docs/data-apis/manage-data/drop-data-using-nerdgraph/#requirements

**Comment by akristen** [comment]
I'm reviewing this now and will update with a PR that addresses this request. i've also removed the link to the Slack thread, as we try not to link to our internal comms on GH. Thanks so much for putting this on our radar!

**Comment by akristen** [comment]
Closing this issue until we receive follow up from teams.
