### ISSUE TITLE
Improve the watermark

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/docs-website#1684]
### Is your feature request related to a problem? Please describe

The current watermark has low contrast and does not stand out on the page.

### Describe the solution you'd like

An improved identifier for beta and other similar types of pages.

### Describe why this important to you

Improved readability, especially for people with trouble with picking out low contrast text.

**Comment by austin-schaefer** [comment]
Thanks for reporting @aswanson-nr ! We've got an issue for this already in #1684, closing this in favor of that one. Definitely on our radar!

**Comment by austin-schaefer** [comment]
Whoops, meant to type #1599 for that duplicate issue number!
