### ISSUE TITLE
Paragraph separation requires two blank lines when in Collapser

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#1692]
When the markdown text is within in a Collapser section, two blank lines are required to separate a new paragraph from a preceding list with its own level of indentation. In other sections of the file, only one blank line separation is needed.

Example of issue:
![image (2)](https://user-images.githubusercontent.com/70179215/113632068-52120f80-961f-11eb-9e5a-9140ae9ea1a1.png)

File: src/content/docs/distributed-tracing/ui-data/understand-use-distributed-tracing-ui.mdx

Acceptance Criteria:
- [ ] Enable only needing one blank line to separate a new paragraph following a list.

**Comment by mmfred** [comment]
@nr-kkenney - is there something the docs team should do for this issue? Or is it really an eng matter?

**Comment by nr-kkenney** [comment]
@mmfred docs team can work around this issue by using 2x newlines. engineering will have to address this if we want to just use single newlines.

**Comment by mmfred** [comment]
Okay. That's what I was getting from the issue. I'll put the eng label on it, since you all will be the ones doing this work.

**Comment by nr-kkenney** [comment]
grabbing this just to do a quick check since we updated to gatsby v3, and had to update many plugins as part of this process, so maybe its no longer an issue.

**Comment by rudouglas** [comment]
I did some digging on this and think it may be a styling issue, I found a couple of similar issues:

https://github.com/gatsbyjs/gatsby/issues/10870
https://stackoverflow.com/questions/31039189/add-line-breaks-to-nested-lists-in-markdown

It would be good to campfire this as i'm not sure how and where the styling should be applied

**Comment by jpvajda** [comment]
adding to our cases for a custom MD linter :https://github.com/newrelic/docs-website/issues/382

**Comment by rudouglas** [comment]
@mmfred I think the best recommendation we can make at the moment is to echo what Kris suggested and add `2x new lines`:

 - Inside a component
 - After a list when you want to create a new Paragraph

...and add that to the content creation workflow for the moment. As John said we will be adding this work to a broader enhancement for a Markdown linter :)
