### ISSUE TITLE
Issue: JMX monitoring integration

### ISSUE THREAD

**Issue by djaffinito** [newrelic/docs-website#1696]
### Tell us what you need

The host connection configuration example is not valid yaml

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration/#host-connection-example

![yamlvalidate](https://user-images.githubusercontent.com/12201539/113638364-868bc880-962b-11eb-9bb7-57fc95839959.jpg)

It should be updated to match the example in the github repo:

* https://github.com/newrelic/nri-jmx/blob/master/jmx-config.yml.sample

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration/
* **OS**: Big Sur
* **Browser**: Chrome
* **Device**: MBP

**Comment by urbiz-nr** [comment]
Hi @djaffinito, thanks for reporting this.

**Comment by mmfred** [comment]
https://github.com/newrelic/docs-website/pull/1714

**Comment by djaffinito** [comment]
@mmfred The issue isn't the missing element. The issue is the indentation.

**Comment by djaffinito** [comment]
Since the Infrastructure agent is written in go, we want to make sure the examples can be parsed by the [go yaml library](https://github.com/go-yaml/yaml). Here's a Go Playground link where I made a quick test to see if Go can parse the current example, and if you run it you'll see it can't:

https://play.golang.org/p/5paK8HvxLMt

```
error: yaml: line 4: mapping values are not allowed in this context--- t:
```

If you replace the data var with the yaml from the github example, it works:

https://play.golang.org/p/igFRLwJYjkT

I hope this helps clarify the issue! Thank you!

**Comment by mmfred** [comment]
yeah. Thanks. I think it's fixed now. Please take a look: https://github.com/newrelic/docs-website/pull/1714/files

**Comment by djaffinito** [comment]
Looks great! Thanks @mmfred !
