### ISSUE TITLE
Google Spreadsheet permissions are not set to public.

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#16983]
In the documentation, we are proceeding to design User permissions using a Google Spreadsheet.

However, the access rights to the linked Google Spreadsheet are restricted, and when I try to browse the sheet, I get an access rights request UI.

If it is linked from a document, shouldn't it be a public permission?
https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/account-user-mgmt-tutorial/
https://docs.google.com/spreadsheets/d/1FnguDXRUX9FGY14oV4Gx6O08v4vNC2Pv0GGCsU7Pxuw/edit?usp=sharing

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

**Comment by rhetoric101** [comment]
@qryuu thanks for the heads-up about the permissions on this file. Our team has reviewed this link and determined that it's no longer helpful. So, we're removing it. 

Thanks again for your help!
