### ISSUE TITLE
Issue: Kafka monitoring integration

### ISSUE THREAD

**Issue by djaffinito** [newrelic/docs-website#1699]
### Tell us what you need

The link for the example configs, where it says "For examples of typical configurations, see the example configurations", goes to `#config-examples` but the anchor is actually `#example-config`

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration/
* **OS**: big sur
* **Browser**: chrome
* **Device**: mbp

**Comment by urbiz-nr** [comment]
Thanks for the feedback, @djaffinito!

**Comment by urbiz-nr** [comment]
Closed in #1700.
