### ISSUE TITLE
Correct information about US data center endpoints

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#17019]
"New Relic telemetry endpoints" listed in 
APM agent ingest" is `collector.newrelic.com`.

However, the "US data center endpoints" list `collector*.newrelic.com` .

Which information is accurate?

https://docs.newrelic.com/docs/new-relic-solutions/get-started/networks/#new-relic-endpoints
https://docs.newrelic.com/docs/new-relic-solutions/get-started/networks/#us-endpoint-list

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

**Comment by rhetoric101** [comment]
@qryuu thanks for pointing out this issue. This [PR](https://github.com/newrelic/docs-website/pull/17039) should fix the problem, so I'm closing this issue.
