### ISSUE TITLE
Add callout explaining Lookout view is not currently supported

### ISSUE THREAD

**Issue by josemore** [newrelic/docs-website#1704]
### Tell us what you need

* Due to an internal limitation the feature of Lookout view in Entity Explorer is not compatible with entities created from the AWS Metric Stream integration. We are working to add compatibility in the future. 
* We should add an important callout mentioning this, at the end of this section: https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/#aws-entities

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/
* **OS**: Mac OS 11.2.3
* **Browser**: Chrome 89.0.4389.90
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @josemore, looking into this now. Is it your view that the callout should be as specific as what you write here, or could we simply say it's not currently supported but we expect to support it in the future? Trying to gauge how valuable (vs. potentially distracting/confusing) the additional detail is for docs end users.

**Comment by josemore** [comment]
Saying it's not currently supported but we expect to support it in the future it's the right message. I was not sure if we want to make this a callout since we plan to add support for this in the next few weeks.

**Comment by dbarnesbrownNR** [comment]
@josemore if we're going to add support in a couple of weeks, I would recommend that we do not add a callout unless this creates an actual blocker for our end users or will result in extra overhead for support in the form of lots of one-off questions. If it just kind of ~doesn't do the thing~ I don't think we specifically need to insert a callout about that given how soon we expect to have it fixed.

**Comment by josemore** [comment]
Though we hope to improve this soon, there's no guarantee the team owning Lookout will be able to work on this. 
Maybe we don't add a callout but a simple text note at the end of the section? I'll make sure we remove this if we manage to fix it.

**Comment by dbarnesbrownNR** [comment]
If you're uncertain as to the timeline and can keep us informed of any need to remove, I am fine with adding an actual callout, and those are generally preferable to simple text notes per our style conventions. I'll do a quick PR for that and have you review the new language @josemore.

**Comment by dbarnesbrownNR** [comment]
See https://github.com/newrelic/docs-website/pull/1750

**Comment by bradleycamacho** [comment]
@dbarnesbrownNR Can you confirm this should be closed with #1750?

**Comment by bradleycamacho** [comment]
Closed in https://github.com/newrelic/docs-website/pull/1750
