### ISSUE TITLE
Broken Internal Link When Moving from Japanese to English Page

### ISSUE THREAD

**Issue by aokabi** [newrelic/docs-website#17064]
## How can we make our docs better?
Internal link is broken after moving from the Japanese page to the English page.

## Reproduce

- Open page
  - e.g. https://docs.newrelic.com/jp/docs/new-relic-solutions/get-started/implementation-guide-intro/
- Click 「英語版」to view english page
  - <img width="613" alt="スクリーンショット 2024-04-24 14 59 01" src="https://github.com/newrelic/docs-website/assets/12667440/1340ca19-ac1d-4657-a25b-18af18941b38">
- Then, internal page link is broken
  - e.g. "our quick launch guide"
    - It links to https://docs.newrelic.com/docs-website-jp.netlify.app/docs/new-relic-solutions/get-started/quick-launch-guide
    - "Hmm... We can't find this" is displayed

**Comment by rhetoric101** [comment]
@aokabi thanks for mentioning this! We will take a look!

**Comment by rhetoric101** [comment]
@aokabi I spoke with our developers. They said that they are working on a fix for this. I'm closing because they indicated that their fix should address this soon.
