### ISSUE TITLE
Add a Copy button to the  API Headings in Docs

### ISSUE THREAD

**Issue by icpenguins** [newrelic/docs-website#1706]
When reviewing documentation and looking up function calls and other APIs, it would be great to have the ability to copy and paste the API. Having this ability is great when doing development.

<https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api/#browserTimingHeader>

![image](https://user-images.githubusercontent.com/10984551/113750437-a076eb00-96bf-11eb-9a8a-0dacbe68938a.png)

### Acceptance Criteria 

- [ ] a better approach may be to just enable the copy function on the code component so user can quickly copy and paste these code snippets directly from collasper header.
- [ ] Add a copy button to each API collapser header

### Crude mock up 😉 

<img width="919" alt="Screen Shot 2021-04-06 at 8 03 25 PM" src="https://user-images.githubusercontent.com/1395158/113800027-718a6480-9713-11eb-8576-b6f63e1389ed.png">

**Comment by jpvajda** [comment]
@icpenguins so this functionality is actually available when you expand the collapser element on an API call definition. 

<img width="915" alt="Screen Shot 2021-04-06 at 4 55 51 PM" src="https://user-images.githubusercontent.com/1395158/113787946-2f542980-96f9-11eb-8526-de9da7917f63.png">

**Comment by icpenguins** [comment]
@jpvajda hey, yeah, I know about that option IF it is available 😉 If you notice the ones I shared, both are expanded and have no inner text to copy. But, you have brought up another pet peeve of mine....expansions for documentation is not fun 😄

**Comment by jpvajda** [comment]
@icpenguins fair point indeed! I didn't realize that not every API call has an example to copy, @austin-schaefer is there a reason for that?

It seems a better approach may be to just enable the copy function on  the code component so user can quickly copy and paste these code snippets directly from collasper header

`<code> transactionHandle.ignore()</code>` 

<img width="919" alt="Screen Shot 2021-04-06 at 8 03 25 PM" src="https://user-images.githubusercontent.com/1395158/113800027-718a6480-9713-11eb-8576-b6f63e1389ed.png">

**Comment by brammerl** [comment]
So after looking at this, it appears that in order to invoke the copy method onto these code snippets - we would have to allow copying on all collapsable "headers". Not all of these collapsable headers have code snippets in them, some of them have simple headers or even 2 different lines of code.

**Comment by jpvajda** [comment]
closing as the ability to copy is embedded within the content of the collasper.
