### ISSUE TITLE
[Header] Add language toggle to global header

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#172]
## Summary
The current docs site has a language toggle in the header so a user can click over to the same current page on the Japanese site.

Short term considerations:
* we only need to display language toggle on docs site for now
* since the Japanese site pages mirror current site pages 1:1 (each path on english site resolves to same path on Japanese site), we can add link on each page to its equivalent Japanese site page. we don't need to know if a translated version exists or not (but that is available via frontmatter field `` if needed)

Long term considerations:
* eventually other New Relic sites will have translations available, so eventually we'll need to make the header aware of which sites' have which translations available for which pages.

## Acceptance criteria
- [ ] Language toggle is available in header on every page on docs site only
- [ ] Clicking on language toggle takes user to Japanese version of the site that displays Japanese or English version of the same page. _Caveat: since we're using old data from dev some pages may not resolve if prod changed and the proxy updated its cache_.

### Example: English page that has Japanese translated version
https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/get-started/introduction-alerts

and its Japanese site equivalent:
https://docs.newrelic.co.jp/docs/alerts-applied-intelligence/new-relic-alerts/get-started/introduction-alerts

### Example: English page without a Japanese translated version
https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/troubleshooting/missing-alert-notifications

and its Japanese site equivalent
https://docs.newrelic.co.jp/docs/alerts-applied-intelligence/new-relic-alerts/troubleshooting/missing-alert-notifications

**Comment by caylahamann** [comment]
Closing this out because this ticket has been recreated int he gatsby theme repo https://github.com/newrelic/gatsby-theme-newrelic/issues/181
