### ISSUE TITLE
nri-agent is outdated in the doc. the latest guided install doesn't use nri-agent

### ISSUE THREAD

**Issue by nethippo** [newrelic/docs-website#1738]
### Tell us what you need

* If you've found something inaccurate, what is it?
nri-agent is outdated in the doc. the latest guided install doesn't use nri-agent. Especially, Troubleshooting mentioning nri-agent doesn't work at all. 

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thank you for reporting this, @nethippo! We'll have a look.

**Comment by urbiz-nr** [comment]
The Infra agent and Logs teams are looking into it, will open PR with updates if necessary.
