### ISSUE TITLE
component=remote msg="Error sending samples to remote storage" count=100 err="context deadline exceeded"

### ISSUE THREAD

**Issue by Dcbate** [newrelic/docs-website#1739]
Hello,

I am trying to set up Prometheus remote write integration to the new relic. 

I have changed the yml file to include :
remote_write: 
- url: https://metric-api.eu.newrelic.com/prometheus/v1/write?prometheus_server=YOUR_DATA_SOURCE_NAME  
  bearer_token:YOUR_LICENSE_KEY

When I restart the Prometheus server I get the log :
component=remote msg="Error sending samples to remote storage" count=100 err="context deadline exceeded"

until the server dies 

Do I need to add a limit to the yml file?

Does anyone know any help?

Thank you

**Comment by urbiz-nr** [comment]
Hi @Dcbate! Thanks for reaching out. This channel is good for feedback on docs. I recommend you try the [Explorers hub]([url](https://discuss.newrelic.com/) with this question. Cheers!

**Comment by Dcbate** [comment]
Thank you @urbiz-nr
