### ISSUE TITLE
Feedback: Explore the Public API Performance dashboard

### ISSUE THREAD

**Issue by foxaal** [newrelic/docs-website#1756]
### Tell us more about your feedback

ALL I WANT IS TO CHECK THE LATENCY OF AN ENDPOINT OF INTEREST TO ME.  CAN I DO THAT OR NOT?  I WOULD HAVE THOUGHT I WOULD PASTE THE ENDPOINT INTO THE THINGIE AND DONE.  INSTEAD, IT SEEMS I NEED TO CROSS A LARGE LEARNING GAP TO DO THIS SIMPLE THING, IF I CAN EVEN DO IT.  HOW TO PROFILE A SIMPLE PYTHON PROGRAM IS WHY I CAME HERE.  AFTER HALF HOUR, I HAVE ZERO INFO ON THAT.  

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/explore-public-api-performance-dashboard/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hello @foxaal, thanks for reaching out! I suggest you post your question at the [Explorers Hub](https://discuss.newrelic.com/), I'm sure they'll be able to help.

**Comment by mmfred** [comment]
Closing as suggested to ask for help in Explorers Hub.
