### ISSUE TITLE
Issue: Get app and other IDs in New Relic One

### ISSUE THREAD

**Issue by neilcampbe11** [newrelic/docs-website#1758]
This documentation is out of date. The i button isn't available. You need to click the tag image instead. Even toggling off "Show new view" doesn't show the UI reflected in the document.

**Comment by barbnewrelic** [comment]
Thanks for reporting this! Perfect timing, because we already have an issue in our backlog (6666) to deal with this oversight.

**Comment by barbnewrelic** [comment]
I'm going to go ahead and close this PR to be consistent with the other issue. See the DOC Jira 6666 for more info.

**Comment by urbiz-nr** [comment]
@neilcampbe11 this has been fixed in #1826.
