### ISSUE TITLE
Add clarification transaction is not nested.

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#17682]
## How can we make our docs better?

[The nodejs custom instrumentation doc ](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-instrumentation.mdx) doesn't explain what happens if `startWebTransaction` or `startBackgroundTransaction` are invoked twice or mode in the same transaction.

I believe it makes nothing since a transaction can't be nested. Could you add clarification of that?

**Comment by akristen** [comment]
Hi @tanaka-takayoshi I've reached out to the Node team for some clarification about expected or unexpected behavior around a double invocation. I'll get these docs updated if they give us a recommendation on language. :)
