### ISSUE TITLE
Actually shut down old data-dictionary service: ETA May 27 - June 9

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/docs-website#1770]
# Issue
After #1582 is complete, the service needs to actually be stopped and removed from production.

### Dependency JIRA ticket

To be executed by the dashboards team

`jira` DSERVICES-1252

# AC
- [x] ensure all teams and apps using this service have migrated to the new service
- [ ] Wait for dashboard services to confirm this is shutdown.

**Comment by jpvajda** [comment]
I'm working on #1582 and I'm thinking it be wise to have the team that actually owns this old service according to treasure map to actually shut it down, so I am reach out to their EM / PM to coordinate that.  `#help-dashboard-services`

**Comment by jpvajda** [comment]
I followed up on the JIRA issue to get status...

**Comment by jpvajda** [comment]
Still waiting on the final changes to take this service offline

**Comment by jpvajda** [comment]
This is now in Review on JIRA, so moving it along 🥳

**Comment by jpvajda** [comment]
Issue is now done in JIRA
