### ISSUE TITLE
aiNotificationsTestDestination, aiNotificationsTestDestinationById command example is not valid

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#17726]
In this [file](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/apis/nerdgraph/examples/nerdgraph-api-notifications-destinations.mdx), there are some NerdGraphAPI examples for aiNotificationsTestDestinationById mutation command. However it is not valid command and error happens when executing it.

In fact, details in the error doesn't exist so far.
```
    error {
      details
    }

```

This issue also exists for aiNotificationsTestDestination mutation command.

It seems here is the valid attributes for the error block.
```
    error {
      ... on AiNotificationsConstraintsError {
        constraints {
          dependencies
          name
        }
      }
      ... on AiNotificationsDataValidationError {
        details
        fields {
          field
          message
        }
      }
      ... on AiNotificationsResponseError {
        description
        details
        type
      }
    }
```

Please consider to fix this issue.

Thanks!

**Comment by akristen** [comment]
Hi @shinji-newrelic I've created a sprint ticket to dig into this so we can validate the doc and update any additional examples as needed. thanks for filing this!

**Comment by austin-schaefer** [comment]
@shinji-newrelic : You can follow along with the internal jira ticket if you look up ticket NR-283458
