### ISSUE TITLE
Feedback on the docs: Bash Command is confusing

### ISSUE THREAD

**Issue by abhinav1602** [newrelic/docs-website#17727]
In the installation steps for springboot, '**app.jar**' in command confused me a bit while trying out the steps because for newrelic.jar it is clearly mentioning to use the full path, but for application .jar it is directly refering to it as app.jar.

https://github.com/newrelic/docs-website/blob/410886c94d4fc2ac38a4716fb61fe187af2981d0/src/install/java/frameworkInstallation/springboot.mdx?plain=1#L13

Can we edit this command to make it look like this?
```bash 
java -javaagent:/full/path/to/newrelic.jar -jar /full/path/to/{YourApplicationName}.jar
```

There are other docs related to Java as well having the same issue which needs to be updated.

**Comment by akristen** [comment]
Hi @abhinav1602 I created a PR to update this bash command, and will have the Java team verify it. You can view the progress of this PR here: https://github.com/newrelic/docs-website/pull/17740

**Comment by abhinav1602** [comment]
@akristen seems it got merged already. Thanks for the quick response.

I just searched for more such instances and found that other files might need the same change as well because the same command is present in other java related docs.

It can be reviewed here:
[search result for java -javaagent:/full/path/to/newrelic.jar -jar](https://github.com/search?q=org%3Anewrelic+%22java+-javaagent%3A%2Ffull%2Fpath%2Fto%2Fnewrelic.jar+-jar%22&type=code)

I can create the PR as well if required and if it gets approved.
