### ISSUE TITLE
NRU / learn.newrelic.com not listed on header

### ISSUE THREAD

**Issue by mtjagg** [newrelic/docs-website#1772]
### Tell us what you need
New Relic University isn't clearly linked to from the New Relic Docs header bar - which I would expect it to be there along with the other sites of major importance.

### Doc information (don't delete this section)

* https://docs.newrelic.com/
* **OS**: Mac OS 11.2.3
* **Browser**: Chrome 89.0.4389.114
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
Thanks for reporting this @mtjagg ! I've been working with the director for the Learn team on this in Slack—I'll close this issue out for now, but I'll update it depending on where we go with this!
