### ISSUE TITLE
.NET Lambda installation steps in wrong section

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/docs-website#17765]
These [installation steps](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-layerless/#dotnet) don't belong in the layerless doc. The layerless doc is meant to provide instructions on how to instrument a Lambda function without using a New Relic Lambda layer.

Same for Ruby, the installation steps should be how to [install the Ruby instrumentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-layerless/#ruby) without an agent layer (the extension-only layer is okay to mention since it is not involved in the instrumentation).

**Comment by homelessbirds** [comment]
Resolving this in another PR!
