### ISSUE TITLE
link to open telemetry collector for infrastructure is not working

### ISSUE THREAD

**Issue by gencix67** [newrelic/docs-website#17811]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/get-started/collector-infra-monitoring/opentelemetry-collector-infra-intro/
* **OS**: Windows 10
* **Browser**: Chrome 126.0.0.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@gencix67 thanks for catching this broken link. This PR should correct this: https://github.com/newrelic/docs-website/pull/17814
