### ISSUE TITLE
Issue: Tarball assisted install of the infrastructure agent for Linux 

### ISSUE THREAD

**Issue by Julien4218** [newrelic/docs-website#1785]
### Tell us what you need

There is a broken link on "compatibility and requirements" pointing to https://docs.newrelic.com/docs/Infrastructure-compatibility-requirements/ which is a 404

### Anything else you'd like to share?

![image](https://user-images.githubusercontent.com/38018054/114443487-99018700-9b82-11eb-9b2c-db0e3b51b7ae.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/tarball-assisted-install-infrastructure-agent-linux/
* **OS**: Windows 10
* **Browser**: Chrome 89.0.4389.114
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @Julien4218! It will be fixed it #1797.
