### ISSUE TITLE
Issue: Troubleshoot password, email address, and login issues

### ISSUE THREAD

**Issue by jeandriscoll** [newrelic/docs-website#1789]
If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

I setup a new user as admin user like everyone else.  When I sign in with the profile, I do not see any of our company's data.

![image](https://user-images.githubusercontent.com/15655861/114458356-f3571380-9b93-11eb-87dc-78516746557b.png)

**Comment by barbnewrelic** [comment]
@jeandriscoll  We're sorry this didn't work the way you expected! I recommend that you review the tips in our "not seeing data" doc https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/not-seeing-data/ or the tutorial on new user setup and how to view the account+user in the UI. https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/tutorial-add-new-user-groups-roles-new-relic-one-user-model/#add-users If these resources don't help, please reach out to support.newrelic.com . Hope this helps!
