### ISSUE TITLE
This is a bug! Please fix!

### ISSUE THREAD

**Issue by kaschaefer** [newrelic/docs-website#1793]
### Description

The latest Java agent's release notes seem to be missing some pretty important words.

### Steps to reproduce

1. Go to https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/
2. Scroll down to 'Java agent v6.4.2'
3. View description
4. Notice that the sentence seems incomplete:
> Fixes an issue that could cause some instrumentation modules (e.g. ) to have a and not apply properly.

### Expected behavior

The description of the release matches the description given when you click on the name of the release:

> Fixes an issue that could cause some instrumentation modules (e.g. jax-rs-1.0) to have a WeaveViolation and not apply properly

### Screenshots

![image](https://user-images.githubusercontent.com/28942464/114471301-3bcafd00-9ba5-11eb-85ea-92b447e5cd93.png)

![image](https://user-images.githubusercontent.com/28942464/114471364-543b1780-9ba5-11eb-87b2-650507e4808d.png)

### Environment

production

**Comment by urbiz-nr** [comment]
Hello @kaschaefer! Thanks for getting in touch. I've checked and I can see the sentence alright: "Fixes an issue that could cause some instrumentation modules (e.g. jax-rs-1.0) to have a WeaveViolation and not apply properly."

Perhaps there's a problem with your browser?

**Comment by urbiz-nr** [comment]
Hi @kaschaefer, thanks for reaching out. We'll have a look!
