### ISSUE TITLE
Issue: New Relic One pricing and billing 

### ISSUE THREAD

**Issue by hroseross** [newrelic/docs-website#1799]
### Tell us what you need

On this doc, I think it would be great to have a section specific to the free plan. There is a tip that includes how to sign up and mentions the 100MB ingest limit, but it's easily missed since it is in a tip and not in its own section. I also get questions from customers about how many users they can have on free account and how/when they will be billed if they exceed 100MB of data ingest. Having this information in our public docs would eliminate a number of customer inquiries.

### Anything else you'd like to share?

The docs team is rad!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Thanks for the suggestion! This is a great candidate for some deeper accounts + pricing docs work that one of the writers already has in progress. I will follow up with him to see if he is already addressing this, or if we could add it to our backlog. I'll keep you posted what I find out!

**Comment by zuluecho9** [comment]
I'll be looking into this one, thanks all.

**Comment by zuluecho9** [comment]
I implemented this here: https://github.com/newrelic/docs-website/pull/1832 Thanks @hroseross
