### ISSUE TITLE
Add self-service instructions for entering OTLP ingest pre-release program.

### ISSUE THREAD

**Issue by a-feld** [newrelic/docs-website#1800]
New Relic would like to offer all customers access to a pre-release, hosted, [OTLP](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md) ingest endpoint.

The endpoint would have support for ingesting:
* Traces
* Metrics (with certain limitations)
* Logs

OTLP stands for "OpenTelemetry Protocol".

The onboarding flow is expected to be:
1. Visit docs page with information about OTLP ingest pre-release
2. Docs page contains a link to a google form requesting information (we need a customer mailing list to notify customers of any breaking changes prior to making those changes)
3. Upon submission of the google form, a link to a private docs site page containing instructions on how to connect to the OTLP ingest endpoint will be served!

The limitations/risks of using the OTLP endpoint that must be documented:
* Billed ingested bytes **may increase** due to the current implementation of the OTLP endpoint.

**Comment by barbnewrelic** [comment]
I'm checking with the team about next steps. I'll follow up with you as quickly as I can. Thanks for your patience, and for such detailed info!

**Comment by barbnewrelic** [comment]
@rhetoric101 FYI

**Comment by rhetoric101** [comment]
This was resolved by #1852 and #43 over in the private-docs-site.
