### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by nr-jbiggley** [newrelic/docs-website#1802]
### Tell us what you need

Missing image within this link - https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/nrql-group-results-across-time/#facet-time-example

### Anything else you'd like to share?

n/a

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/nrql-group-results-across-time/
* **OS**: Mac OS 11.2.3
* **Browser**: Edge 89.0.774.75
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Fixed with 1838
