### ISSUE TITLE
Issue: Java: Configure with Log4j 1.x. Logs in context.

### ISSUE THREAD

**Issue by tbradellis** [newrelic/docs-website#1805]
The documentation for Log4j1 doesn't show the Pre-conditions that are specified on the ReadMe for the Log4j1.x extension.

https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/logs-context-java/java-configure-log4j-1x/

### Tell us what you need

We should update the user documentation so that those preconditions for configuration are known.
For example:
Our public docs show the comparable way to use a properties file for log4j 2.x but not for 1.x.  A customer has been sending time trying to get this feature to work based on what they see in our public documentation.
The log4j1.x doc states...
"The log4j environment is fully configurable programmatically. However, it is far more flexible to configure log4j using configuration files. Currently, configuration files can be written in XML or in Java properties (key=value) format."

This sounds like configuration via property file should be achievable.  However, compare that with the Pre-Conditions in the  log4j1 extension ReadMe.
https://github.com/newrelic/java-log-extensions/tree/main/log4j1#preconditions

`
...
...
log4j must be configured in code or via XML. Properties files are not supported because AsyncAppender instances can only be automatically configured via XML.
...
...
`

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/logs-context-java/java-configure-log4j-1x/

https://github.com/newrelic/java-log-extensions/tree/main/log4j1#preconditions

**Comment by barbnewrelic** [comment]
@tbradellis Thanks for reporting this! It's a known issue that the logs-in-context docs have drifted from the GitHub documentation, which is generally more reliable. I am in the middle of a project to consolidate all the logs-in-context documentation to remove the duplicated and outdated info from the Docs site. I will make sure this issue is fixed as part of that effort. Thanks for reporting this issue and 1806 too!

**Comment by barbnewrelic** [comment]
I will be working on my Jira next week, so I will go ahead and close your issue here. Thanks again, these are important fixes!
