### ISSUE TITLE
Issue: Workloads: Isolate and resolve incidents faster

### ISSUE THREAD

**Issue by RyanCopley** [newrelic/docs-website#1808]
### Tell us what you need

* "Get started with workloads" does not get me started with workloads. It explains some concepts of workloads. Perhaps rename this page to "Workload concepts" 

### Anything else you'd like to share?

This document is going over workload concepts, however it does not actually get me started with workloads. Arguably, the "Use workloads" (oddly named title) should be called "Get started with workloads". 

Also, I am a New Relic employee. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/workloads/workloads-isolate-resolve-incidents-faster/
* **OS**: Mac OS 11.2.3
* **Browser**: Chrome 89.0.4389.114
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Thanks for the feedback! I'm checking with our workloads docs expert. Will get back to you soon!

**Comment by zuluecho9** [comment]
Maybe 'Introduction to workloads' @barbnewrelic

**Comment by barbnewrelic** [comment]
@RyanCopley  The short title on the left nav now says "Intro to workloads." https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/workloads/workloads-isolate-resolve-incidents-faster/ This follows a standard naming workflow for organizing our docs and hopefully makes it easier for readers to skim what are the concepts vs. what are the actual procedures to use workloads. Thanks again for this helpful suggestion!
