### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by ryancastles** [newrelic/docs-website#18149]
## How can we make our docs better?

This link is a 404 https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/

The first hit from google is the same link as above, which has a 404.
https://www.google.com/search?q=aws+lambda+sending+cloudwatch+logs+new+relic

Also when searching inside docs for "aws lambda sending cloudwatch logs" it returns the same broken link as above.
ie. https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/?q=logs+forward-logs+aws-lambda-sending-cloudwatch-logs

Tested on 3 computers both with Chrome and one with firefox and chrome.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/
* **OS**: Windows 11
* **Browser**: Chrome/Firefox
* **Device**: Unknown

**Comment by ally-sassman** [comment]
Addressed in https://github.com/newrelic/docs-website/pull/18188. I will also manually update the internal search tool to show https://docs.newrelic.com/install/aws-logs/?service=EC2&forward_EC2=cloud_lambda when searching for "cloudwatch". Thanks for letting us know about this issue!
