### ISSUE TITLE
`TDOC_DocPageView_pageView` event data drastically dropped on Mar 25th

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1815]
### Steps to reproduce

1. Go to GA > Behavior > Events > Overview
2. See that March 25th data for this event drastically plummeted.

### Acceptance Criteria

- [ ] Determine the root cause of why we saw such a huge drop in the event
- [ ] If there is a 🐛 in the code, fix it
- [ ] Data is reported in a similar pattern to the GA data before March 25th

<img width="1643" alt="Screen Shot 2021-04-21 at 5 00 47 PM" src="https://user-images.githubusercontent.com/1395158/115631483-25b6ee00-a2c3-11eb-8452-158ac1ae4007.png">

**Comment by jpvajda** [comment]
As a note browser agent data for this same event DOES NOT show this drop....

<img width="1380" alt="Screen Shot 2021-04-21 at 4 59 57 PM" src="https://user-images.githubusercontent.com/1395158/115631437-0cae3d00-a2c3-11eb-9b4d-35adf9cbda28.png">

**Comment by roadlittledawn** [comment]
FWIW. it looks like there's a count of 813 `DocPageView` in the `Unfiltered Master View`. that number still seems low for 7 days. but does that imply some filtering in GA is part of the cause here?

**Comment by jpvajda** [comment]
@roadlittledawn perhaps! Let me see what Zoe thinks of this issue.

**Comment by zoezhou1113** [comment]
From what I can tell, the TDOC_DocPageView_pageView event is still not sending to GA:
![image](https://user-images.githubusercontent.com/80297589/115931857-e242b800-a459-11eb-8a8e-e414c80083e6.png)

**Comment by jpvajda** [comment]
So is this simply a setting things in Segment? If you go to Source / Destination / Settings there are a ton of things that can be set on the destination, perhaps we just need to flip something on @roadlittledawn /zoezhou1113 ?

`/new-relic/destinations/google-analytics/sources/docs_staging/`

**Comment by zoezhou1113** [comment]
@jpvajda No, "integrations" needs to be updated in the code. Here is the Segment documentation on filtering: https://segment.com/docs/guides/filtering-data/

**Comment by jpvajda** [comment]
@zoezhou1113 well we currently set integrations `ALL: true` [here](https://github.com/newrelic/gatsby-theme-newrelic/blob/1302b794fdebb486b35e347a546ed1ffa553553d/packages/gatsby-theme-newrelic/src/utils/createTessen.js#L52) So that's why I thought maybe it's a setting in segment.

**Comment by jpvajda** [comment]
@roadlittledawn is it possible this configuration in the theme is being override at the site level?

**Comment by roadlittledawn** [comment]
You beat me to it, @jpvajda ! That's definitely the only place we should need to set that. I'll look at network requests when I'm back at my computer to see if that's set.

**Comment by zoezhou1113** [comment]
This is the only thing I could think of. I don't see any filters applied on the Segment side.

**Comment by jpvajda** [comment]
@roadlittledawn is it possible this tessen [configuration](https://github.com/newrelic/docs-website/blob/d1f8c5f6c71227ffb2acb2d640322a38b5c52e6a/gatsby-config.js#L163) is causing the issue at the site level?

This might be a place we can ask the Tessen team for their thoughts @zoezhou1113

**Comment by roadlittledawn** [comment]
> @roadlittledawn is it possible this tessen [configuration](https://github.com/newrelic/docs-website/blob/d1f8c5f6c71227ffb2acb2d640322a38b5c52e6a/gatsby-config.js#L163) is causing the issue at the site level?
> 
> This might be a place we can ask the Tessen team for their thoughts @zoezhou1113

it looks like that integrations setting is the default in the `tessen.track()` method. i'm not actually sure why that event fires since we only seem to fire the `tessen.page()` event when the page loads (aka, route changes). the `tessen.page()` call has the integrations setting we made. do those page events not get forwarded to GA? 

also, the fact that `TDOC_DocPageView_pageView` is also added to our Browser agent `PageAction` surprised me. i'm curious if tessen detects that and adds it automatically to our Browser data (it also sends its data to the Tessens account in a `TessenAction` event)

**Comment by roadlittledawn** [comment]
Since deploying the small tessen snippet change with this yesterday, I see more of these events in GA, but def not what the amount I'd expect since it's sent with each page view. 58 of the `DocPageView` events recorded in GA yesterday.

**Comment by jpvajda** [comment]
@roadlittledawn so it's not :100 resolved yet? also can you add some points to this to account for the work in Sprint 3?

**Comment by jpvajda** [comment]
This looks resolved as there is a signifcant jump in these events from 4/26 - 4/27 from 910 - 11,126
