### ISSUE TITLE
Github release action fails

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#1819]
### Description
The `Release` workflow is [failing](https://github.com/newrelic/docs-website/runs/2338341468?check_suite_focus=true) due to an authentication error.

It looks like the work we did in #1771 assumed that the `gh` command was already authenticated.

**Comment by nr-kkenney** [comment]
the pr-triage workflow also uses gh client but authenticates using an environment variable.

```none
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

is whats in there, and the client will automagically use that.

**Comment by zstix** [comment]
This has been resolved in #1829 (forgot to link the right issue in the PR).

**Comment by zstix** [comment]
This has _not_ been resolved, unfortunately: https://github.com/newrelic/docs-website/runs/2348027306?check_suite_focus=true
