### ISSUE TITLE
Issue: 404 Cloudwatch Plugin documentation 404

### ISSUE THREAD

**Issue by jack-liu2** [newrelic/docs-website#18207]
## How can we make our docs better?

The Documentation link for AWS Cloudwatch plugin for Logs : [AWS CloudWatch plugin](https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/) is missing / unreachable (404)

Which is reference from your documentation page : https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic/

### Doc information (don't delete this section)
 Mac OS 
* https://docs.newrelic.com/404.html
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by ally-sassman** [comment]
This issue is fixed in this PR: https://github.com/newrelic/docs-website/pull/18188
