### ISSUE TITLE
docs: Prometheus integrations list is outdated

### ISSUE THREAD

**Issue by abhinav1602** [newrelic/docs-website#18210]
https://github.com/newrelic/docs-website/blob/82257bfb41f3d35fc103d212218213bfd9566f18/src/content/docs/infrastructure/prometheus-integrations/integrations-list/integrations-list-intro.mdx?plain=1#L39

Was going through this page - [Prometheus Integration](https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/integrations-list/integrations-list-intro/)

There is list in the end that shows all the integrations we did using prometheus. **Isn't that list outdated?**
**Is there any way to get this list dynamically or programtically?**

**Comment by jeff-colucci** [comment]
Hi @abhinav1602! I'm not sure that there is a way to dynamically generate the list, but if we need to update the integrations list we certainly can. If you can create a PR with the proposed changes and link it to the docs hero board, we'll be able to get you set up with a review and get the changes made live shortly after that. Please reach out to me if you have any questions. Thanks!
