### ISSUE TITLE
Encode value button not working

### ISSUE THREAD

**Issue by urbiz-nr** [newrelic/docs-website#1822]
As reported in #documentation, the "Encode value" button is no longer working in https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/handle-sites-authentication/. 

I've checked the old site and it works there (see screenshot).

<img width="738" alt="encode_value_button0" src="https://user-images.githubusercontent.com/43602284/114660904-5f518d00-9cf6-11eb-953c-8560a077c045.png">

**Comment by jpvajda** [comment]
@urbiz-nr Thanks for reporting this, what is the button supposed to do? 

We never actually built a button component to do this in the new site, it's likely why it's not working 😃  It's actually the first time I've heard that we had a button to encode a value and return a result.  but if you can define it's functionality we can look at it.

Also where else is this button located? Is it used throughout the docs site?

**Comment by urbiz-nr** [comment]
@jpvajda, [here](https://docs-dev.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/handle-sites-authentication) you can see how the encoding button works. To be honest, it's the first time I see anything like this in our site. We could reach out to the original requester for more details.

**Comment by jpvajda** [comment]
@urbiz-nr thank you! If it's a single use button, I'd propose we do away with it, we try to build components that are re-usable across all our sites, so if possible I'd suggest we remove it. It's like the encoding function that this button represents can be done either with a simple function, or some other place. 

I'm also a bit concerned that we are offering a feature to encode values that contain user names / passwords. I tested it out and it doesn't seem to actually encode the value I entered, perhaps I'm using this wrong?

But either way, I'd say we just document how you can encode these values and reference locations or code libraries that allow secure encoding vs offering a button to that on the Docs Site.

cc @zstix on this for input here.

<img width="984" alt="Screen Shot 2021-04-15 at 10 22 41 AM" src="https://user-images.githubusercontent.com/1395158/114903926-88484f80-9dd4-11eb-9919-ee4fdb58e34d.png">

**Comment by jpvajda** [comment]
After talking this through as a team, the approach I outlined is preferred @urbiz-nr just let me know what you think?

**Comment by urbiz-nr** [comment]
@jpvajda - It makes sense to just document how to do it instead of having the button in our site. I'll create a jira to make this update and will let the reporter know.
