### ISSUE TITLE
Update pages screenshots with the new Timewarp

### ISSUE THREAD

**Issue by lfons** [newrelic/docs-website#18283]
On the [service maps page](https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/ui-data/service-maps/service-maps/), the docs show screenshots and animations using the old Timewarp. We now have a new Timewarp design, which is also shown in another position.

### Old Timewarp

The old Timewarp is currently shown on the [service maps page](https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/ui-data/service-maps/service-maps/) in multiple screenshots:

<img width="217" alt="image" src="https://github.com/user-attachments/assets/68a46848-bf9c-4539-beaa-30dd0f10d8ac">

### New Timewarp

The new Timewarp design and interaction is shown below.

The Timewarp feature is now activated by a button and does not open automatically. However, if there have been any health status changes in the map's entities within the past three hours, a red notification dot will appear on the Timewarp button to let users know about it.

<img width="745" alt="image" src="https://github.com/user-attachments/assets/414dd229-fcb5-484f-9af7-1185b3b4e280">

This is how it looks when the Timewarp opens.

<img width="526" alt="image" src="https://github.com/user-attachments/assets/5e875ca6-4a58-4389-b355-ff41d34bfa64">

Please note that similar updates may be need also in this page: https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/ui-data/service-maps/uninstrumented-entities-service-maps/

Feel free to reach out to me if you need some help regarding this. Thank you!

**Comment by jeff-colucci** [comment]
Reaching out in Slack for this @lfons !
