### ISSUE TITLE
DT API required shown as not required

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#18305]
https://docs.newrelic.com/docs/distributed-tracing/trace-api/report-new-relic-format-traces-trace-api/#new-relic-guidelines

Hi there!

The page with the guidelines about our DT API shows the object `attributes` of the object `Span` as not required.

After testing, I noticed that it is required and also the attribute `duration` inside of it is also required.

<img width="1250" alt="Screenshot 2024-08-08 at 10 31 34" src="https://github.com/user-attachments/assets/a1266e39-4094-40d5-bb0b-94d40d5871b3">

**Comment by jeff-colucci** [comment]
Addressing in https://github.com/newrelic/docs-website/pull/18309
