### ISSUE TITLE
Outdated Session Tracking doc page

### ISSUE THREAD

**Issue by csalvador-nr** [newrelic/docs-website#18315]
## How can we make our docs better?
https://github.com/newrelic/docs-website/blob/9f2f9efa7165131ec6f043d12b794cb21b540180/src/content/docs/browser/browser-monitoring/page-load-timing-resources/cookie-collection-session-tracking.mdx?plain=1#L39

This section of the Session Tracking doc is outdated. It's no longer possible to enable/disable Session Tracking in the UI. Since this is 4 years old, I would consider revisit the whole page.

**Comment by jeff-colucci** [comment]
@csalvador-nr I think that given the nature of this ticket it would be best to open up a work request so that we can give it the time it needs on the revisitation. Please reach out in the hero channel if you need any help or further direction!
