### ISSUE TITLE
Confusing instructions for aws integration may lead users to wrong integration method

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#18387]
On this page: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations/

The recommended approach is to use Metric Streams (as mentioned and linked in the first paragraph) and polling as another option.

Its confusing for me that under the title "Connect AWS and New Relic" the link provided goes to _only_ the Polling option. It would be better if links to both methods were provided here. I think the link in the first pragraph is easily skipped by a someone just trying to get the answer, and we lead them too easily to the polling solution whihc is not the preferred.

**Comment by nbaenam** [comment]
Hi @jsbnr, I've added a modification. Can you take a look at it and let me know if it is okay? Thanks a lot!
