### ISSUE TITLE
Improve agent nav and add Infra agent

### ISSUE THREAD

**Issue by bpschmitt** [newrelic/docs-website#1846]
### Tell us what you need

- Left hand nav is blank.  Would be great to see a list of all agents and links to their respective docs.  
- Infrastructure agent is completely missing from the list. 

### Anything else you'd like to share?

n/a

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/
* **OS**: Mac OS 11.2.1
* **Browser**: Chrome 89.0.4389.114
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Great minds think alike! We have a DOC Jira in process to address this very thing.

**Comment by bpschmitt** [comment]
Woohoo!

**Comment by rhetoric101** [comment]
@bpschmitt, we decided to make "Agent" in the left navigation point to the introduction to APM. So the label will be "APM agents." We didn't address your concern about adding a link to the Infrastructure agent on the homepage. Users can find this under "Full-Stack Observability > Infrastructure monitoring. Still, I am creating an internal issue to see if we could add the Infrastructure agent to the home page.
