### ISSUE TITLE
Add the new data dictionary service and the content library service to `treasure map`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1870]
In order to allow internal teams to find support for these 2 internal services we should add the new data dictionary service or the content library service listed in treasure map. 

### more about hooking into  treasure map 

https://source.datanerd.us/architecture/treasure_map#contributing-to-treasure-map

### Example file

https://source.datanerd.us/nr1-dev-experience/catalog/blob/master/datanerd.yml

### Acceptance criteria 

- [x] add a datanerd.yml needs to be added to each repo
- [x] update runbook with new team info

### Repos 

https://source.datanerd.us/nr1-dev-experience/docs-library-service

https://source.datanerd.us/nr1-dev-experience/data-dictionary

**Comment by jpvajda** [comment]
PR 1: https://source.datanerd.us/nr1-dev-experience/data-dictionary/pull/38
PR 2: https://source.datanerd.us/nr1-dev-experience/docs-library-service/pull/44

Still need to confirm if I should also update the runbooks with our team info and if the grandcentral.yml file should be updated with our team name

**Comment by jpvajda** [comment]
I've updated the runbooks with our team contact info, but i'm opting to not change the grandcentral.yml file as it's not clear to me how that may impact our abillity to use grandcentral. There is some internal documentation on changing teams ownership, that perhaps someone can review to assess if this is required.

https://pages.datanerd.us/site-engineering/nr-platform-docs/grand_central/changing-service-ownership.html

**Comment by zstix** [comment]
@jpvajda  I've approved and merged the updates to our internal repositories.
