### ISSUE TITLE
Improve documentation on getField()

### ISSUE THREAD

**Issue by jeffreycs** [newrelic/docs-website#1885]
https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#func-get-field

The `getField()` function has some useful operations that aren't currently documented:

1. The documentation says it only works for "complex metrics," which I think in this context is meant to stand for dimensional metrics. However, you can actually use it to return any field in a [timeslice metric](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/query-apm-metric-timeslice-data-nrql/) too.
2. The function supports the ability to [wildcard metric names](https://newrelic.com/blog/nerdlog/nrql-empty-strings-empty-sets-wildcards) with the `%` symbol.
3. The "type" field can also be grabbed from any metric in order to return the metric's type.
4. You can use `[ ]` syntax as an alias for the function. For example, the following two queries are the functionally similar:

     ```
     FROM Metric SELECT uniques(metricName) WHERE getField(%, type) = 'gauge'
     FROM Metric SELECT uniques(metricName) WHERE %[type] = 'gauge'
     ```
5. It can also be used to return an individual percentile value from the result of a `percentile()` operation. This is especially useful with nested aggregation. For example:

     ```
     FROM (FROM PageView SELECT percentile(duration, 50, 95) FACET appName) SELECT average(percentile[50]), average(percentile[95])
     ```

I'm unsure about the best way to approach these enhancements, so I've filed an Issue. Note that I am a New Relic employee.

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @jeffreycs! Please feel free to update the doc yourself if you're comfortable, here's [some guidelines](https://docs.newrelic.com/docs/style-guide/writing-guidelines/create-edit-content/). Or we can take care of it if you prefer.

**Comment by zuluecho9** [comment]
@jeffreycs I'll make a stab at adding this to docs, thanks.

**Comment by dbarnesbrownNR** [comment]
@jeffreycs I have a few questions about this, would you mind reaching out to me via Slack when you have a few? Thank you!

**Comment by dbarnesbrownNR** [comment]
@jeffreycs and I are working on pulling together an update that will showcase these abilities better.

**Comment by dbarnesbrownNR** [comment]
Have created DOC-6863 to handle this because the ask is expanding and it could now use some sprint attention.

**Comment by dbarnesbrownNR** [comment]
Letting this hang out in the blocked lane until we get eyes on it during the upcoming sprint.

**Comment by zuluecho9** [comment]
I created a docs jira to look into this (which might actually be already solved, I'm not sure) and some related issues: DOC-7186.

**Comment by bradleycamacho** [comment]
@zuluecho9 @dbarnesbrownNR Can you two take a look at this issue and update it with the current status? Thanks!

**Comment by dbarnesbrownNR** [comment]
Jira still relevant and should be covered next sprint. Jira number has changed to DOC-7304 and it's in backlog for next sprint. Closing this issue since it's covered elsewhere.
