### ISSUE TITLE
Feedback: Group browser metrics by URLs

### ISSUE THREAD

**Issue by open768** [newrelic/docs-website#1890]
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?
reading the documentation its not clear how to create a url segment rule.
please provide specific examples to make it easier to understand how url segments work.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/configuration/group-browser-metrics-urls/
* **OS**: Windows 10
* **Browser**: Chrome 89.0.4389.128
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hello @open768. Thanks for reaching out, is there any feedback you'd like to share with us?

**Comment by austin-schaefer** [comment]
Reopening this one now that we're keeping these issues in public backlog rather than Jira

**Comment by bradleycamacho** [comment]
@urbiz-nr Could you re-triage this and edit the issue with specific action items so we can share with the GM group? Thanks!

**Comment by urbiz-nr** [comment]
@bradleycamacho - adding this back to the board so we can start over.

**Comment by rhetoric101** [comment]
@open768, I apologize for the late response to your issue. Have you figured this out already using the existing documentation? 

If you still find this unclear, could you clarify where there's a gap in these current steps? These seem pretty explicit and are followed by some examples of rules in the next section called `Create rules`:

1. Go to one.newrelic.com > Browser > (select an app) > Settings > Segment allow lists.
2. In Allow listed segments, select the plus  icon.
3. Type the segments you want to appear in groupings on the Page views and AJAX pages.
4. Enter domain segments (elements of the domain between dots) or path segments (elements of the URL path between slashes).

**Comment by open768** [comment]
Hi,  thanks for your feedback, but it's been  years after the report and I've moved on long ago . I was an operational team lead for jlp waitrose at the time. Inbetween i was a snr solution designer for o2 uk. I now work for a competitor of nr (appd)  as a professional services consultant. I only used nr briefly but I was impressed with its human centric design, which contrasted the technical ui of appd. 

Sunil - Clinical Hypnotherapist - Bracknell
Make the change for the better today
https://fb.me/EmpoweringYourGoals
07764535933 
 
  On Fri, 17 Sep 2021 at 9:15 p.m., Rob ***@***.***> wrote:   


@open768, I apologize for the late response to your issue. Have you figured this out already using the existing documentation?

If you still find this unclear, could you clarify where there's a gap in these current steps? These seem pretty explicit and are followed by some examples of rules in the next section called Create rules:
   
   - Go to one.newrelic.com > Browser > (select an app) > Settings > Segment allow lists.
   - In Allow listed segments, select the plus icon.
   - Type the segments you want to appear in groupings on the Page views and AJAX pages.
   - Enter domain segments (elements of the domain between dots) or path segments (elements of the URL path between slashes).

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
