### ISSUE TITLE
Issue: Kafka monitoring integration

### ISSUE THREAD

**Issue by rushminatorr** [newrelic/docs-website#1898]
### Tell us what you need
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

Kafka integration on K8s took the longest to configure. The docs did not have clear instructions. I am having an error: `event_queue_depth`, All other integrations seem to work except this one. There are docs on configuring the `event_queue_depth` but no instructions on how or what setting for k8s integration, is it part of configmap or env var. And no mention on the integration docs. Would really be helpful to have a section on common issues and how to address these and this could be part fo that. 

### Anything else you'd like to share?

There are couple of discussions that talk about the `event_queue_depth` setting but not listed on this integration, https://discuss.newrelic.com/t/kafka-nr-integration/145660

https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-10323/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration/
* **OS**: Ubuntu
* **Browser**: Chrome
* **Device**: Laptop

**Comment by zuluecho9** [comment]
thank you @rushminatorr. I'll ask the appropriate team about this and see how we can approve this doc. Much appreciated.

**Comment by zuluecho9** [comment]
Closing this because this will be part of a larger scope of work around improving the 'install integrations via K8s' docs.

**Comment by rushminatorr** [comment]
@zuluecho9 in the interim do you have solution for me? I am getting the "queue_depth" error and if you could please help or ask one of the engineers to comment on https://discuss.newrelic.com/t/kafka-nr-integration/145660 will really appreciate it.

**Comment by zuluecho9** [comment]
@rushminatorr I pointed that forum post out to them, hopefully someone helps you out. Good luck.
