### ISSUE TITLE
step monitors also take secure credentials

### ISSUE THREAD

**Issue by Leels** [newrelic/docs-website#18985]
[This line](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/store-secure-credentials-scripted-browsers-api-tests/#:~:text=Applicable%20monitors,test%20monitors.) should also include step monitors since they also accept secure credentials. 

Also, this [link](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/store-secure-credentials-scripted-browsers-api-tests/#:~:text=synthetic%20scripted%20browsers%20and%20API%20test%20monitors) is not longer linking to the correct document and needs to be updated. It should go to [this part](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/intro-synthetic-monitoring/#types-of-synthetic-monitors) of the documentation. 

Thank you!

**Comment by nbaenam** [comment]
Closing this because I've opened this one: [https://github.com/newrelic/docs-website/pull/19042](https://github.com/newrelic/docs-website/pull/19042)
