### ISSUE TITLE
This is a bug! Please fix! - Synthetic Tests, everything I try breaks

### ISSUE THREAD

**Issue by OZZlE** [newrelic/docs-website#1908]
### Description

Synthetics seems broken, any tests I try just fail and then nothing is saved, see screenshots.

All of those are valid CSS selectors even though they are on the advanced side of CSS but we don’t have dynamic classes that you cannot rely on no ID’s in most places.

Account id: 1122121

### Steps to reproduce

1. Go to Synthetics
2. Create Monitor
3. User step execution
4. Any name, period 15m
5. All locations
6. See below screenshot:
![Skärmavbild 2021-04-19 kl  16 43 06](https://user-images.githubusercontent.com/893783/115346793-ec8e5900-a1b0-11eb-9452-dad12cca03c4.png)
7. Save monitor

### Expected behavior

Monitor is saved or some feedback if I need to correct something.

### Actual result

Monitor isn't saved, I just lost everything I did with the following error:

![Skärmavbild 2021-04-19 kl  16 43 26](https://user-images.githubusercontent.com/893783/115347022-32e3b800-a1b1-11eb-9964-5a7e28c4e64f.png)

### Additional context

Account id: 1122121

### Environment

New Relic One Synthetics

**Comment by urbiz-nr** [comment]
Hello @OZZlE - thanks for reaching out. We are the Docs team and we handle documentation only, if you're having problems with your account you should [get in touch with Support](https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/find-help-use-support-portal/). Hope this helps!

**Comment by OZZlE** [comment]
> Hello @OZZlE - thanks for reaching out. We are the Docs team and we handle documentation only, if you're having problems with your account you should [get in touch with Support](https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/find-help-use-support-portal/). Hope this helps!

It seems we pay you a lot of money for monitoring but apparently Support is not included.. but I have created this forum issue also: https://discuss.newrelic.com/t/synthetic-tests-seem-broken-everything-i-try-leads-to-an-error-nothing-is-saved/145841

But I think this is a major issue that will affect all your customers negatively. Synthetic tests is probably the only thing we will keep NR for in the future but not if it doesn't even work...

**Comment by zuluecho9** [comment]
I hope the forum is able to help. One support person I asked about this said that "Those selectors they’ve defined don’t look valid" if that might help @OZZlE.

**Comment by OZZlE** [comment]
> I hope the forum is able to help. One support person I asked about this said that "Those selectors they’ve defined don’t look valid" if that might help @OZZlE.

You can just right click on the background of the page, inspect element, console, write: `document.querySelector('_try_each_selector_I_used_here_')` one by one an see that they are valid. But it's not CSS for newbies. In any case the whole page breaking and not saving anything without any feedback is quite unprofessional but thanks for nothing.
