### ISSUE TITLE
Feedback: external_trace (Python agent API)

### ISSUE THREAD

**Issue by brian-muse** [newrelic/docs-website#1913]
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?

The document examples are unhelpful. Is 'library' a call with a third-party SDK that I would later call in foo? It seems really unclear.  It would be good if foo could be implemented with some example code that uses 'library' in the way that you would expect it to be used. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/python-agent/python-agent-api/externaltrace-python-agent-api/
* **OS**: Mac OS 11.2.3
* **Browser**: Chrome 89.0.4389.128
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Thank you @brian-muse, I'll be looking into this with our python team.

**Comment by zuluecho9** [comment]
@brian-muse I may be mistaken, but is 'library' in this case referring to the general python 'library' definition, which says "The library contains built-in modules (written in C) that provide access to system functionality such as file I/O that would otherwise be inaccessible to Python programmers, as well as modules written in Python that provide standardized solutions for many problems that occur in everyday programming."

**Comment by brian-muse** [comment]
Yeah. I know that. I'll try to clarify more. Let's say I have an example program:

```
import library.client

def foo(a):
    client_instance = client.get_instance() 
    client_instance.get_a_page(a)
```

Can I just wrap it with 

```
import library.sum

@external_trace('library', 'http://example.com', 'get')
def foo(a):
    client_instance = client.get_instance()
    client_instance.get_a_page(a)
```

and as long as the base URL for whatever `get_a_page` is calling is `http://example.com' and it uses GET, then it will be picked up? Or do I need to import the client path? This is what I think is not clear.

**Comment by zuluecho9** [comment]
@brian-muse sorry about that delay. I got a response from the developers. They said the following, and hopefully this helps: 

"Thanks for pointing this out, we can definitely improve these docs. We have a few docs updates on the way with our upcoming release so I will get this in our backlog to fix as well. I think we can add a couple better examples with different library args that may help with some of the confusion. What the customer is saying should work. Here https://github.com/newrelic/newrelic-python-agent/blob/main/newrelic/hooks/application_gearman.py#L75 is an additional example of a use of external_trace in our code that may help provide a bit of clarification:

application_gearman.py
    with ExternalTrace('gearman', url):
"

**Comment by zuluecho9** [comment]
I'm going to close this @brian-muse. Sorry if we couldn't help you more. If you had more questions, I'd suggest trying the Explorers Hub https://discuss.newrelic.com/, to see if someone's either discussed it or else leave a new question.
