### ISSUE TITLE
Generate a preview of the document from CI in the PR

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/docs-website#1916]
### Is your feature request related to a problem? Please describe
Setting up the local environment to visualize the doc takes a bit to long. It would be super nice that the CI provides a link to a running instance of the docs compiled from the PR so we don't need to run the local environment.  

### Describe the solution you'd like

I would like to submit a PR and the CI compile the project and provide a running instance of the docs compiled from the PR so i can easily check the changes i've done.
I know that having this is not totally free and could have a living time.

### Describe why this important to you

I'm not a JS developer so I don't have and i'm not used to work with them so troubleshooting a problem it takes some time as i'm doing now.

**Comment by jpvajda** [comment]
PR previews are available in the [checks](https://github.com/newrelic/docs-website/pull/1925/checks?check_run_id=2394354467) of the PR so you'd submit a PR and when the build complete AWS Amplify provides a preview link you can click on and few the site. However, prior to submitting a PR it's best practice to test the site locally to ensure nothing you've done has broken the site, but in the case of simple markdown changes of content improvements, you could in theory rely on the the preview link provided by Amplify. 

Let us know of this works for you as what you are requesting seems to be already solved on Github. 

<img width="762" alt="Screen Shot 2021-04-20 at 3 33 13 PM" src="https://user-images.githubusercontent.com/1395158/115467049-229dfe00-a1ee-11eb-9c8b-1be22a8d4dae.png">

**Comment by gsanchezgavier** [comment]
this looks exactly what i was looking for! and just saw is mentioned in the [contribution guide](https://github.com/newrelic/docs-website/blob/develop/CONTRIBUTING.md#deploy-previews-with-amplify ) , my bad. Thanks!
