### ISSUE TITLE
Issue: RecordCustomEvent (.NET agent API)

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#1928]
### Tell us what you need
the link to reserved words is 404

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/net-agent/net-agent-api/recordcustomevent-net-agent-api/
* **OS**: Windows 10
* **Browser**: Chrome 90.0.4430.72
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Thank you much @StingyJack. Fixing with https://github.com/newrelic/docs-website/pull/1929.
