### ISSUE TITLE
Migrate Docs Site to Gatsby Cloud: `Step 1`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1933]
Once we've decided to move our Docs Site to Gatsby Cloud we'll want to move this site to Cloud.

### Helpful Links
* [Instructions for updating DNS in Gatsby Cloud](https://support.gatsbyjs.com/hc/en-us/articles/360063469873-Adding-a-Custom-Domain)

### Acceptance Criteria 

Step 1 
- [x] Create an account in Gatsby Cloud
- [x] Notify Gatsby that we've creating this account and they should enable this account for enterprise features.
- [x] Complete Vendor security review process
- [x] Ensure that the team can all log into Gatsby Cloud
- [x] Connect the account to our Github repository (Bot has access)
- [x] Set up `main` as the production branch for deployments
- [x] Get the site to build on the new platform
- [x] Set up preview builds for pull requests
- [x] Do build testing

**Comment by jpvajda** [comment]
blocked on security review...

**Comment by jpvajda** [comment]
the security will actual occur within the vendor approval process so we are still waiting on that

**Comment by jpvajda** [comment]
This is going to take ~ 7-10 business days

**Comment by jpvajda** [comment]
`jira` VRI-8985 for the security review

**Comment by jpvajda** [comment]
This is now requiring GM approvals. 🧷

**Comment by zstix** [comment]
The build process is pretty nice. A couple of thoughts we had:
* We weren't sure how to enable PR builds for a branch _other_ than the production branch
* The UI for PR builds displays the last commit message and author, not the PR title and author
* It doesn't look like there's any way to customize the PR comment that Gatsby Cloud provides

**Comment by zstix** [comment]
We've created two instances in Gatsby Cloud for the `main` site (what could be our production) and `develop` (for which we will take advantage of the PR Build Previews). I think Step 1 is now complete.
