### ISSUE TITLE
HAProxy Integration - Install Configuration Examples are incorrect

### ISSUE THREAD

**Issue by WTThomas1** [newrelic/docs-website#19378]
Multiple configuration examples in the HAProxy Integration install documentation are not correct:

[New Relic Documentation](https://docs.newrelic.com/install/haproxy/)

- [Github - default-configuration.mdx](https://github.com/newrelic/docs-website/tree/develop/src/install/haproxy/default-configuration.mdx)
  - name - references the apache integration, not haproxy
  - STATUS_URL and REMOTE_MONITORING - Both are not valid environment variables for the HAProxy integration... but are for the apache integration...
  - inventory_source - shows as `config/haproxy` in other examples but the documentation is unclear what this is supposed to reference / point to. Regardless, `config/apache` is likely not correct.

- [Github - default-install-linux.mdx](https://github.com/newrelic/docs-website/tree/develop/src/install/haproxy/default-install-linux.mdx)
  - Same issues as default-configuration.mdx

The examples further down appear to be correct so these may have just been copied from the apache page / overlooked.

**Comment by WriteMayur** [comment]
To analyze and monitor the progress of this issue, I have created a [Doc improvement](https://new-relic.atlassian.net/browse/NR-343898) JIRA ticket.
