### ISSUE TITLE
Issue: Write synthetic API tests

### ISSUE THREAD

**Issue by shazron** [newrelic/docs-website#1938]
### Tell us what you need

The link https://discuss.newrelic.com/tags/c/support-products-agents/synthetics/synthetics-script on the page https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests/ does not exist.

<img width="1409" alt="Screenshot 2021-04-21 at 6 13 46 PM" src="https://user-images.githubusercontent.com/36107/115537497-716e9500-a2cd-11eb-99db-2e6c7800c993.png">

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this @shazron, we'll fix it!
