### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by jveltd** [newrelic/docs-website#19400]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

I clicked on a link and there was no docs.

https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/report-mobile-monitoring-custom-events-attributes/

This link ([MobileRequest Examples](https://docs.newrelic.com/docs/insights/insights-data-sources/default-attributes/mobile-request-query-examples-mobilerequest/)) doesn't give any examples.

<img width="516" alt="Screenshot 2024-11-28 at 16 22 55" src="https://github.com/user-attachments/assets/a4c813c8-8c9d-4e8d-a292-5b4ea23cde49">

### Doc information (don't delete this section)

* https://docs.newrelic.com/404.html
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by WriteMayur** [comment]
Hi @jveltd 

Thanks for highlighting the missing links in our doc. I have fixed the link and raised a PR. The doc will be publish by 8AM PT.
