### ISSUE TITLE
AWS Metric Streams Links are broken

### ISSUE THREAD

**Issue by adammarshallNR** [newrelic/docs-website#19424]
On this page: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-step-functions-monitoring-integration/

The link (AWS CloudWatch Metric Streams integration) to the AWS Metrics Streams documentation is broken, pointing to https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-metric-stream/ 

It should be pointing to https://docs.newrelic.com/install/aws-cloudwatch/

It looks like this may be the case across the whole site: https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-athena-monitoring-integration/

**Comment by mlakshmiharita** [comment]
Created a [jira](https://new-relic.atlassian.net/browse/NR-353500) ticket to track the issue and make the necessary changes, hence closing this issue
