### ISSUE TITLE
Issue: Legacy manual instrumentation

### ISSUE THREAD

**Issue by keegoid-nr** [newrelic/docs-website#1944]
### Tell us what you need

Broken link in .NET Core at bottom of page called `configure CloudWatch to send those logs to New Relic`.

### Anything else you'd like to share?

It should point to:
https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/#manual-stream-logs

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy/
* **OS**: Linux x86_64
* **Browser**: Chrome 90.0.4430.72
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Fixed in #1958.
