### ISSUE TITLE
Define DevEn's `A/B Testing` process & framework

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1948]
We've had several requests to conduce A/B tests for the Docs site and this issue is to define how that process will work and setup a framework that can empower teams to do a lot of the A/B Tests themselves so DevEn can delivery on our mission to enable teams of developers to do amazing things with New Relic products. 🚀 

### Acceptance Criteria

- [x] Ensure Split.io is setup correctly on the Docs Site so A/B tests can be setup
- [x] Determine who needs to learn more about how to use Split and arrange a training session with Split in the external slack channel `shared-splitio-devex`
- [x] Setup a Split test for the [Free Account Button](https://github.com/newrelic/gatsby-theme-newrelic/issues/356)
- [x] Run this test as a "learning opportunity" for all parties interested in this process
- [x] Work with the Docs Team to properly document this process 
- [x] Setup a working agreement for how the DevEn Team will support this need.

**Comment by zstix** [comment]
Maybe something like this?

```
<Split test="docssite_paragraph" variant="a">
This is treatment A
</Split>
<Split test="docssite_paragraph" variant="b">
This is treatment B
</Split>
```

**Comment by jpvajda** [comment]
relates to: https://github.com/newrelic/docs-website/issues/1982

**Comment by jpvajda** [comment]
I've spun up a doc but had little time to spend on it today...
