### ISSUE TITLE
Deployment Marker for the Docs site is current broken

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1951]
We currently aren't able to leverage the deployment marker as it's failing on the user (personal) API Key.

### References
https://github.com/newrelic/deployment-marker-action

https://docs.newrelic.com/docs/apis/get-started/intro-apis/new-relic-api-keys/

### Expected 

The [deployment marker job](https://github.com/newrelic/docs-website/pull/1942/checks?check_run_id=2401489485) runs with great success

### ERROR

```
Run newrelic/deployment-marker-action@v1
/usr/bin/docker run --name e4ac3db81a1d4c4483b04d08cff05d4d26_37c2d4 --label 5588e4 --workdir /github/workspace --rm -e GITHUB_TOKEN -e INPUT_APIKEY -e INPUT_ACCOUNTID -e INPUT_APPLICATIONID -e INPUT_REVISION -e INPUT_REGION -e INPUT_DESCRIPTION -e INPUT_CHANGELOG -e INPUT_USER -e NEW_RELIC_API_KEY -e NEW_RELIC_ACCOUNT_ID -e NEW_RELIC_APPLICATION_ID -e NEW_RELIC_REGION -e NEW_RELIC_DEPLOYMENT_USER -e NEW_RELIC_DEPLOYMENT_REVISION -e NEW_RELIC_DEPLOYMENT_CHANGE_LOG -e NEW_RELIC_DEPLOYMENT_DESCRIPTION -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/docs-website/docs-website":"/github/workspace" 5588e4:ac3db81a1d4c4483b04d08cff05d4d26
Error:  level=error msg="401 response returned: Invalid credentials provided. Missing API key or an invalid API key was provided."
level=fatal msg="401 response returned: Invalid credentials provided. Missing API key or an invalid API key was provided."

```

### Acceptance Criteria

- [x] update Readme for Github Marker  `Deployment Markers are only supported by APM Applications.` [PR15](https://github.com/newrelic/deployment-marker-action/pull/15)
- [x] If this theory is that you can't send a deploy marker for a non-APM entity/app. then remove the marker from the code.

**Comment by jpvajda** [comment]
> it’s possible we’re using an API key that’s either wrong / doesn’t have right permissions/etc. but when i used the newrelic-cli directly i tried using the following API keys that i think were part of the Developer Experience account (which is where the docs Browser agent reports its data):

- User API key
- Browser ingest API key
- REST API key v2

**Comment by roadlittledawn** [comment]
@LizBaker and I looked closer last week. current theory is you can't send a deploy marker for a non-APM entity/app.

**Comment by jpvajda** [comment]
I can ask JT about this theory.

**Comment by jpvajda** [comment]
@jthurman42 confirmed `Deployment Markers are only supported by APM Applications.`

**Comment by jthurman42** [comment]
The docs reference an ApplicationID, which other entities wouldn't have.  Here's the docs for deployment markers, which fall under APM:

https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/
