### ISSUE TITLE
Fix build swifttype content workflow

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#1961]
Looks like the swifttype workflow has failed the last couple of runs, as can be seen [here](https://github.com/newrelic/docs-website/actions/workflows/build-with-swiftype-content.yml). [This](https://github.com/newrelic/docs-website/runs/2405537118?check_suite_focus=true) is the most recent failing run. The error in each case is `RequestError [HttpError]: Not Found`.

We can see the request url is: `https://api.github.com/repos/newrelic/docs-website/branches/main/protection`. I don't believe anything has changed on our end, but still might be possible.

Acceptance Criteria:
- [ ] workflow fixed and successfully running again

**Comment by rudouglas** [comment]
Notes:
It looks like both `branch protection` steps are failing with a **404**, they both use the same `github-token` so maybe the token is the issue? 
![Screenshot 27-04-2021 18-50-41](https://user-images.githubusercontent.com/17122543/116288584-9198cb00-a789-11eb-9b1e-bb28f47b2689.png)
The only other action that uses the same token is [Check status of translation jobs](https://github.com/newrelic/docs-website/runs/2447688692?check_suite_focus=true) which is also failing, but just before it gets to the `Create pull request` step which uses the token

**Comment by zstix** [comment]
Yeah, my guess is that the `OPENSOURCE_BOT_TOKEN` secret is no longer accurate. It looks like there are two workflows that rely on this variable being in the environment:

* [workflows/build-with-swiftype-content.yml](https://github.com/newrelic/docs-website/blob/783364dcb553db9a1d660add287c7d31f44c4729/.github/workflows/build-with-swiftype-content.yml)
* [check-translations-and-deserialize.yml](https://github.com/newrelic/docs-website/blob/783364dcb553db9a1d660add287c7d31f44c4729/.github/workflows/check-translations-and-deserialize.yml)

It looks like both workflows have been failing for a while. I've reached out to the folks in `#help-opensource` for direction.

**Comment by zstix** [comment]
This issue has been resolved and is [no longer failing](https://github.com/newrelic/docs-website/runs/2461238180)

There seems to be an issue with the _content_ of the workflow not being accurate (or present), but we have [another issue](https://github.com/newrelic/docs-website/issues/1963) to tackle that.
