### ISSUE TITLE
[Related Resources] Workflow doesn't seem to get full results

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#1963]
## Description

The [github workflow](https://github.com/newrelic/docs-website/blob/develop/.github/workflows/build-with-swiftype-content.yml) to update the [`related-resources.json`](https://github.com/newrelic/docs-website/blob/develop/.github/workflows/build-with-swiftype-content.yml) (which is used to populate the Related Resources menu in the right rail) doesn't seem to complete successfully.

The workflow started failing recently; however, when it was completing successfully it only added couple hundred lines. There's resources for only 8-9 pages on the site. I think there should be something like almost 2k pages, so that file should be much larger.

When we were initially working on this, we noticed that requests to swiftype seemed to work until network connections were reset and it didn't finish. One theory was possible rate limiting on swiftype's side.

### Expected

- [x] populate full results of swiftype queries 
- [x] the right rail should show these results through out docs pages

**Comment by LizBaker** [comment]
we're thinking maybe the swiftype api just can't always handle our number of requests in quick succession. we don't get a 429 (rate limit) so we're wondering if they're crashing before they can even rate limit us 😅 we did manage a few successful runs locally but it's intermittent. we're chatting about adding a tiny wait time (the hacky way) or refactoring everything which will be more work but less hacky
