### ISSUE TITLE
Localization On-boarding `Runbook`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#1971]
We want to ensure we structure this approach so the DevEn team can plan for these projects the best we can as we have a very full roadmap until Sept. 

Much of the details can be found on `G-drive`: in a doc called Globalization: Machine Translation for Docs Site
## Objective 

Develop a repeatable and predictable process to support the localization of new countries for the Docs Site. 

### Acceptance Criteria

- [x] assist @jmiraNR in defining our approach to machine translation. 

- [x] create a simple roadmap to get a sense of when each country may come online.

> @jmiraNR is working on budgets to help define which countries will onboard when.

- [x] Define the expectations for delivering each country. Once we learn about a country is wanting to come on line, how negotiable is the delivery date?

> there are many steps in this process that need to be done prior to Development can start but here is a general list:

1. vendor selection
2.  customization 
3. quality tests, etc. on the machine side 
4. development

- [x] Define a way to estimate the onboarding of a new country to get a sense of that effort so we know.

> if we can decide on the avg amount of effort we need to plan for to onboard a country it would help us prepare for that, as it could be an interrupt to our roadmap.  

`Note` This will come later once we break down the work for a new country. but perhaps we can at least put a timebox on what we think it could take so we know what to plan for, maybe one week of a sprint as a rough estimate?

- [x]  Build a localization `runbook` for onboarding new countries, essentially a list of things that need to be done so it's clear what the common business/  engineering tasks are. This way we know what to expect for each country. 

> We'd want to partner with @jmiraNR on that. but this can also come later when we take on the next country and plan the work out.

- [x] determine when we can slot in the MT work for Japan, the ask is JUNE but we need to do some due diligence and planning to determine when this could be slotted in to our roadmap. 

> this conversation will occur in our next deven <> docs leadership sync.

**Comment by zstix** [comment]
We might want to consider working on this issue as part of the onboarding process: https://github.com/newrelic/docs-website/issues/647

**Comment by jpvajda** [comment]
This isn't super urgent so I'm moving to sprint 4.

**Comment by nr-kkenney** [comment]
for machine translation, this probably would have come up in a google / random search, but Amazon has a service we could utilize (had some experience with it previously). since we utilize a lot of aws, aws on balance has pretty good apis / interactions, i think thats worth adding to some potential list.

**Comment by nr-kkenney** [comment]
@jmiraNR id be down to learn more. if you have a doc / info collected.

**Comment by jpvajda** [comment]
Next steps are to sync on priorities of this work in our Docs <> DevEn leadership sync.
