### ISSUE TITLE
Newrelic Sending Null Pointer Exception Alert

### ISSUE THREAD

**Issue by OE-System** [newrelic/docs-website#1988]
Hi,
Newrelic is showing transaction error as:
aggregateFacet: "WebTransaction/SpringController/login()GET::java.lang.NullPointerException"
error.class::"java.lang.NullPointerException "

And sending alert mails regarding the exception.

Is this because of a problem with agent version ?
Or what else it could be? How to troubleshoot this as the error is not so specific?

**Comment by mmfred** [comment]
Hi @OE-System - Thanks so much for filing an issue. We recommend that you visit https://discuss.newrelic.com/, where you can potentially find an answer to this question, or can raise it there, and get feedback from New Relic and other customers who might have encountered this as well. Cheers! The docs team

**Comment by OE-System** [comment]
Okay. Thank you!
