### ISSUE TITLE
[Setup] Create / Update README

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#2]
## Summary
This repository was automatically generated and we need to update the [README](https://github.com/newrelic/docs-website) with relevant information.

## Acceptance Criteria
* [x] Project name and brief description
* [x] Installation and getting started (including dependencies)
* [x] Support link

## Helpful Links
* [Developer Website README](https://github.com/newrelic/developer-website)

**Comment by caylahamann** [comment]
support link will be added later!
