### ISSUE TITLE
Feedback: Introduction to the Event API

### ISSUE THREAD

**Issue by sauhrabh** [newrelic/docs-website#2000]
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/introduction-event-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

I've done the following:

1. Register an Insert API key.
2. Before creating custom events or attributes, review New Relic's list of reserved terms used by NRQL.
3. Generate JSON for the event by instrumenting your application, querying an API, or some other method.
4. Submit a compressed JSON payload (for example, gzip or deflate) to the HTTPS endpoint using curl in a POST request.

Where do I find this data ?

What exactly is `YOUR_CUSTOM_EVENT` in the [Find Your Data](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/introduction-event-api/#find-data) section? Where is this being used in 1 to 4 ?

**Comment by bradleycamacho** [comment]
Hey @sauhrabh! In this example, `YOUR_CUSTOM_EVENT` is the event name. You set the event name as the `eventType` attribute. You can read more about it [here](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/introduction-event-api/#json-guidelines)

I also recommend that you visit https://discuss.newrelic.com/, where you can potentially find more information to this question, or can raise it there, and get feedback from New Relic and other customers who might have encountered this as well. Cheers! The docs team.
