### ISSUE TITLE
 Follow up work to improve the navigation sort order for index pages.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2007]
### Related

#1844 
#1585

###  User Story 

As a user  if I go to this[ billing page]( https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/) I should see this navigation, which is essentially the nav structure found in accounts.yml but I see the navigation “expanded” in the section I am actually in. More importantly the Index view of the page reflects the exact URLS that exist in this nav structure. In this approach, no matter where  I land on any index page, I always be shown the the primary navigation of where that page is found, where I am actually at in the navigation and the URLS for the index section.

### Mock Up

![image (1)](https://user-images.githubusercontent.com/1395158/117517852-9f550a00-af5a-11eb-87df-9bae2c65de6a.png)

### Problem 

We always want to determine the correct navigation to show on the left side and then we want to determine the correct part of the navigation to show as the main page content for that particular index page so the user has clear indicators of where they are in the navigation hierarchy. 

### Acceptance Criteria 

- [x] When a user traverses navigation, regardless of the level of navigation they are at, the navigation should always reflect what doc they are viewing so it's clear to them where they are in the Nav Hierarchy
- [x] Sort order on the index pages matches that in navigation file
- [x] Always show the correct docs in the navigation file.
- [x] Always have a 1:1 mapping between the contents of the left nav and the contents of the index pages
- [x] if a new page is added to that index directory and there is no corresponding nav item added to a yml file, then this page would NOT have a corresponding nav item. note: This is a manual process the Docs Team enforces, so we don't need to try to automate this in this ticket).
- [x] please work with @zuluecho9 for acceptance of this change as he has deep knowledge of the expected experience here
- [x] ensure documentation is updated in the style guide to explain how this works. @zuluecho9

**Comment by jpvajda** [comment]
This continues to generate a lot of issues and complaints of user experience for navigation so let's look to try to continue to improve this in Sprint 4, if we have bandwidth.

**Comment by jpvajda** [comment]
Updated the AC based on our chat with @zuluecho9 and @austin-schaefer .. cc @zstix

**Comment by jpvajda** [comment]
We need to clarify exactly how this work for a case such as: https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/

**Comment by jpvajda** [comment]
I'm working through this with a little internal doc and will update the AC when we get consensus on how to proceed.

**Comment by jpvajda** [comment]
updated AC and details based on our extensive slack convo on this subject..

**Comment by zuluecho9** [comment]
One thing we might add to the acceptance criteria is that the index view be at the appropriate level that the url folder structure is at (e.g., if it's at docs/accounts it'll show that top level view, if it's at docs/accounts/account-billing it'll show a view of a second level of docs, etc.). Maybe this can be helped by showing an example of how it would look for other url views.
