### ISSUE TITLE
Add Docs style guide content to the migration script

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#201]
### About this work

The Docs site has a lot of Style Guide content that we'd like to migrate over to GitHub so that we can start getting that content updated.

These links are to top-level style guide categories. All of the Docs should be added to the migration script.
https://docs.newrelic.com/docs/new-relic-only/basic-style-guide
https://docs.newrelic.com/docs/new-relic-only/tech-writer-style-guide
https://docs.newrelic.com/docs/new-relic-only/drupal-configuration
https://docs.newrelic.com/docs/new-relic-only/training-environment

All of this content uses the Drupal basic page content type.

### Success criteria
I'll of these docs are migrated over so that I can start work updating them on a GitHub branch.

**Comment by urbiz-nr** [comment]
Reviewed.
