### ISSUE TITLE
[Gatsby Cloud] Migrate Docs Site to Gatsby Cloud: `Step 2`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2015]
### Related

JIRA `ELB-1680` `DONE`

This is step 2 to the migration

### Acceptance Criteria 

- [x] Update architecture documentation
- [x] Update troubleshooting guide(s)
- [x] Swap the DNS to point to the new site
- [x] Disconnect Amplify from the repository
- [ ] Publish documentation changes
- [x] fix / address gatsby issues we are running into
- [x] Remove Amplify webhook
- [x] Remove GH/Amplify integration

**Comment by nr-kkenney** [comment]
picking this up to work on the documentation AC.

**Comment by nr-kkenney** [comment]
documentation updated in the wiki & sitting in `update_documentation` until the dns changes are ready to go.

**Comment by nr-kkenney** [comment]
moving this to blocked while the event is ongoing since docs are updated. additionally, we should address whatever problem the gatsby deploy is running into, otherwise we cant migrate this site to gatsby.

**Comment by jpvajda** [comment]
also blocked on the issue with sub-domains on Fastly which Gatsby is working on for June. Ticket TBD.

**Comment by aswanson-nr** [comment]
CNAME transfer ticket `ELB-1680`
