### ISSUE TITLE
Support request: add some clarification to messages after running a query

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#2026]
Cross-post from #internal-feedback: in regards to Infra queries, Support will sometimes get questions from customers asking why they're seeing a "Your metric query has been transformed..." or a "Your infrastructure query has been transformed..." message after running a query. I think it would be helpful to have a section in the Infra dimensional metrics doc and/or the general Infra querying doc that elaborates on those messages further.
https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/nrql-query-tutorials/query-infrastructure-dimensional-metrics-nrql/
https://docs.newrelic.com/docs/infrastructure/manage-your-data/data-instrumentation/default-infrastructure-monitoring-data/
docs.newrelic.comdocs.newrelic.com
Query infrastructure dimensional metrics with NRQL | New Relic Documentation
In New Relic, you can query dimensional metrics for Infrastructure.
docs.newrelic.comdocs.newrelic.com
Default infrastructure monitoring data  | New Relic Documentation
A list of the default events and attributes used by New Relic to collect and store your infrastructure monitoring and host data.

**Comment by mmfred** [comment]
Created a Jira: https://newrelic.atlassian.net/browse/DOC-6838

**Comment by bradleycamacho** [comment]
@mmfred Looks like the corresponding jira was close during introspection. I am closing this issue too, but feel free to reopen it if you believe it should stay open.
