### ISSUE TITLE
Feedback: Amazon CloudWatch Metric Streams integration

### ISSUE THREAD

**Issue by adiosspandit** [newrelic/docs-website#2042]
### Tell us more about your feedback

There is no indication of which account ID is source-accound-id ? Is this new relic account id, customers aws account id or new relic's aws account id?

* Please add description for source-account-id?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/
* **OS**: Mac OS 11.2.2
* **Browser**: Chrome 89.0.4389.114
* **Device**: Unknown

**Comment by josemore** [comment]
This is customers aws account id, let's make it clear with a proper description, thanks

**Comment by mmfred** [comment]
Thanks for helping us make the docs clearer @adiosspandit!
