### ISSUE TITLE
Issue: Security for mobile apps

### ISSUE THREAD

**Issue by StacySimmons** [newrelic/docs-website#2068]
### Tell us what you need

Our Mobile SDK does not collect IDFA (Identity For Advertisers). Please add this clarification under https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/get-started/security-mobile-apps/#identifiers in the iOS identifiers section

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/get-started/security-mobile-apps/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by mmfred** [comment]
Updated - thanks @StacySimmons!
