### ISSUE TITLE
Fix Query Builder Tool tips formatting issues

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2082]
### Issue

Now that we've hooked the query builder into the new data dictionary for attribute definitions, there are cases where the formatting of the tool tips in plain text is causing visual issues due to the length of some definitions and the formatting. 

### Steps to reproduce 

1. go to the NR1 Platform > Query your Data > Query Builder 
2. enter in a query like `SELECT * FROM PageView WHERE firstContentfulPaint`
3. view the too tip 🤔 

### Visual

<img width="844" alt="Screen Shot 2021-04-30 at 10 56 38 AM" src="https://user-images.githubusercontent.com/1395158/116741207-4530d380-a9b3-11eb-804e-8eadc4c4f9a5.png">

### Acceptance Criteria

- [ ] Resolve this so that all tool tips render correctly, perhaps by not using the plain text version of the tooltip as we have markdown and html as a format available

### Notes

- Internal PR  `wanda-data-exploration` PR 1316

**Comment by nr-kkenney** [comment]
@jpvajda what was the specific visual issue you were seeing?

**Comment by jpvajda** [comment]
@nr-kkenney perhaps that example isn't the best one to use, it seems ok now that I'm staring at in GH 😅 but I thought @zstix found a few examples of this issue.
