### ISSUE TITLE
Feedback: Glossary

### ISSUE THREAD

**Issue by berniegenerette** [newrelic/docs-website#2090]
It really shouldn't take forever to find a way to set my timezone, in the UI

**Comment by dbarnesbrownNR** [comment]
Hi there @berniegenerette, I did a quick search in our docs and it looks as though the phrase "set time zone" leads yields this docs result, which explains how to change your timezone in the UI: https://docs.newrelic.com/docs/accounts/accounts-billing/general-account-settings/default-time-zone-setting/

Hope this is helpful and do feel free to reach out by tagging me in a subsequent comment if you're still in need of assistance. 

-Diana
