### ISSUE TITLE
Issue: New Relic Priority Support

### ISSUE THREAD

**Issue by jjang-nr** [newrelic/docs-website#2094]
This page includes a link to a 404. Looks like it's supposed to link to a PDF, but that PDF can't be found.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/licenses/license-information/special-services-licenses/new-relic-priority-support/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @jjang-nr, I am working on getting an updated version of the PDF to add back in to the doc so that it no longer 404s. Thanks!

**Comment by rhetoric101** [comment]
@jjang-nr, sorry this took so long, but we finally fixed this broken link! Thanks again for catching this! The fix should go out the evening of 5/26/2021.
