### ISSUE TITLE
Determine speed improvements from Gatsby v3 upgrade

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#2098]
## Description
We should gather some information about how much faster our build times are now that we're using Gatsby v3. This effort should be timeboxed so that we're not spending too much time gathering numbers.

## Acceptance Criteria
* [x] Determine the average build time before v3
* [x] Determine the average build time after v3

## Notes
Previous build time issue: https://github.com/newrelic/docs-website/issues/1661

**Comment by nr-kkenney** [comment]
data gathered & dropped into [the spreadsheet](https://docs.google.com/spreadsheets/d/12N0YTzzh3Hzu4A0ODDSBj8jNgNfsTMgTwz4Oq30AqdU/edit#gid=420211866) from the previous ticket.

tl;dr - average build time on amplify has increased. previous average was `46.749 minutes` and the current average (after v3 gatsby update on 4/22) is `58.735 minutes`.

i'm not exactly sure how / where to account for the difference, but the current times seem consistent -- every build takes around an hour, so if there was caching or a way where some builds could run faster, we dont seem to be running into that anymore.

**Comment by nr-kkenney** [comment]
given my previous comment, im going to try and grab data from the `Build and cache site` github action, since I know for sure we utilize gatsby caching there.

**Comment by nr-kkenney** [comment]
script for collecting data from gh action is [here](https://gist.github.com/nr-kkenney/d855b4ac5160acbe819a32e34a740acd)

```none
696 runs before cutoff date
93 runs after cutoff date
Average build time before cutoff date was: 0:22:48.908046
Average build time after cutoff date is: 0:21:29.741935
difference of 0:01:19.166111
```

so after the v3 upgrade, we are faster by ~`1 minute, 20 seconds`.

**Comment by nr-kkenney** [comment]
@jpvajda if this looks good to you, and you can think of anything else to check, ill close this out.

**Comment by jpvajda** [comment]
Super cool data! @nr-kkenney let's get this into tomorrow's demo for a slide, it's good to know we saw some incremental improvements here. cc @zstix
