### ISSUE TITLE
Audit the components of the Docsite and provide guidance on new components

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#21]
### Story

We'll want to understand what existing components are available to the Doc Site, in the shared component library and what new ones will be needed so we can look to scope and define those in another MMF.

### AC 

- [Audit the components](https://www.npmjs.com/package/@newrelic/gatsby-theme-newrelic) of the Docsite / OSS site 
- Provide guidance and high level designs (if possible in this MMF cycle) on the new components that may need to be built for the new Docs site.
- This research will be used in a future MMF to start bringing over some components from the existing Docs Site.

**Comment by jpvajda** [comment]
@djsauble We've identified this work as key dependency for MMF 2, as we are going to attempt to migrate some of the Docs components in that iteration cycle, do you feel this will be done by the end of this current MMF?

**Comment by djsauble** [comment]
I haven't started the audit yet. When does the current MMF end?

**Comment by jpvajda** [comment]
@djsauble This Friday the MMF is scheduled to end.

**Comment by djsauble** [comment]
I'll give it my best shot. I'm out Friday, so likely it will happen on Thursday.

**Comment by djsauble** [comment]
@jpvajda Turns out that @austin-schaefer and @roadlittledawn already took a stab at this. 😄

https://docs.google.com/document/d/1j7hLEtBmfJdNplk_1T6r8tkBa-c_o4C96fVZu7coo7E/edit#

**Comment by jpvajda** [comment]
Thanks @djsauble I'm going to take that link to the doc and add it to the reference section of the master req docs.
