### ISSUE TITLE
Issue: NRQL operators for attributes with boolean values

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#2102]
## Description

Not quite clear to me these are officially supported NRQL operators, BUT they work and they seem to be undocumented.

I'm sending some data via `PageAction` that contains an attribute with a boolean value (true/false). When I queried for that data in NR1 in the `WHERE` clause I got an error that asked if I wanted to use the following which do indeed work. in this case `agree` is the attribute and it said to use `IS TRUE` or `IS FALSE` operators.

**Example query**

```
SELECT * FROM PageAction WHERE actionName = 'cookieConsent' and agree IS TRUE
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @roadlittledawn, yes, there are a number of things that work in NRQL but are not explicitly documented. I will kick this back to the NRQL masters peeps on the eng side and see what they think about priority on this. Likely something that would be helpful to document just not sure exactly when in the context of other things we'd like to cover.

**Comment by dbarnesbrownNR** [comment]
This looks like a good one for our NRQL eng folks to help with, consulting with them and will report back @roadlittledawn!

**Comment by dbarnesbrownNR** [comment]
@derekroller tagging you here so you can see the issue.

**Comment by bradleycamacho** [comment]
@dbarnesbrownNR This is pretty stale. Can you re-triage this and see if it's still needed?

**Comment by dbarnesbrownNR** [comment]
Ask is still relevant @bradleycamacho. I've reached out to someone on the NRQL team to get either a rec for how to update or a PR submitted. Will put back in to do for now but if there's not someone to work on it by early next week I think we can close.

**Comment by austin-schaefer** [comment]
Closing out issues older than 90 days, feel free to re-open if anyone would like us to revisit this issue!
