### ISSUE TITLE
Incident Intelligence Docs Flow Change

### ISSUE THREAD

**Issue by iazam6** [newrelic/docs-website#2105]
Hello,

Attached is a document outlining some changes to the incident intelligence technical doc. The changes represent a change of feature flow (what features are being shown first to last) and an image replacement for an image that doesn't currently represent what the docs is showing.

[https://docs.google.com/document/d/1VzAmxJIitZSm_9rRPQFUZngHc4XtysvogMM2v4a1ARI/edit]

**Comment by urbiz-nr** [comment]
Updates in #2107.
