### ISSUE TITLE
Charts in Slack alerts not in UTC

### ISSUE THREAD

**Issue by cizmazia** [newrelic/docs-website#2106]
### Tell us what you need

The Slack app New Relic Alerts posts chart thumbnails which are in the LA time zone instead of UTC as specified in the docs (below). Can the time zone be configured? Thanks!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/general-account-settings/default-time-zone-setting/

**Comment by urbiz-nr** [comment]
Thanks for reaching out, @cizmazia - I'll do some digging and get back to you!

**Comment by cizmazia** [comment]
@urbiz-nr thanks for looking into this. Getting alerts in LA timezone does not provide a very satisfactory UX. It is not in line with the docs either.
