### ISSUE TITLE
Improving Lambda documentation

### ISSUE THREAD

**Issue by retishp** [newrelic/docs-website#2110]
The AWS Lambda Nerdpack is a quick/easy way to onboard Lambdas for New Relic instrumentation. Can we have a reference to the Nerdpack (please see screenshot) in the docs?
<img width="1498" alt="NR_Lambda" src="https://user-images.githubusercontent.com/7780777/117005504-54669880-acb5-11eb-98ac-6ac06ff57991.png">

Also, the earlier version of the docs had a well laid list of different options on how to instrument Lambda for various language agents. It was more clear and simpler to follow. Please see screenshot. Can we get the same format back?

<img width="850" alt="Lambda_Options" src="https://user-images.githubusercontent.com/7780777/117005676-88da5480-acb5-11eb-9745-11bbc292589c.png">

**Comment by bradleycamacho** [comment]
Hey @retishp, thanks for the feedback! The nerdpack is a good call; we're in the process of updating the copy and I'll be sure to update the docs themselves. 

We removed those options in #1111, where the Serverless team reworked most of the installation docs. Can you expand on why the new structure is confusing? The intent was to make the entire category a procedure users could follow: 
<img width="311" alt="Screen Shot 2021-05-04 at 8 46 53 AM" src="https://user-images.githubusercontent.com/42678939/117031424-69432c00-acb5-11eb-8cd9-1d93e9f38ebe.png">

**Comment by bradleycamacho** [comment]
Hey @retishp! Just checking in on this issue again.
