### ISSUE TITLE
Script review and verification for bulk redirect updates

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#2120]
### (Not a feature request) Request for review of bulk updates routine

The problem I'm trying to solve is how to move a large number of files from one directory to another and how to create create redirects.

I'm looking for confirmation that the following routine was successful for moving the `agents` directory under the `apm` directory:

1. Before moving the files, I ran my own [shell script](https://github.com/rhetoric101/redirect-automation) to insert redirects into the front matter of all the files in the agents directory. I executed the script from inside the `agents` directory.
2. I manually moved the `agents` directory under the `apm` directory.
3. I copied the entire contents of `agents.yml` (Minus the path line at the top) and moved it into `full-stack-observability.yml` after the first section of the APM navigation tree.
4. I deleted agents.yml, which does what I wanted: it no longer appears on the homepage navigation. It is now under **Full-Stack Observability > APM**.

Could you do a code review of the [shell script](https://github.com/rhetoric101/redirect-automation) I created? I'd like to have a professional confirm that this script didn't have any unintended consequences.

You can pull down this [PR](https://github.com/newrelic/docs-website/pull/2119) to build this locally.

I completed each of the steps listed in the header of the script.

**Comment by jpvajda** [comment]
We'll do this work in the  https://github.com/newrelic/docs-website/pull/2119 👍
