### ISSUE TITLE
Instructions on workload-status-views-notifications are impossible to follow

### ISSUE THREAD

**Issue by Bikeman868** [newrelic/docs-website#2121]
On this page https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/workloads/workload-status-views-notifications/

Step 1 of these instructions says "Go to Applied Intelligence Alerts" but gives no indication at all of where this can be found.
I tried dropping down the "Explorer" button and there is an "Alerts and AI" option there, but no "Applied Intelligence Alerts" option within it. I spent a few minutes browsing around the navigation but there is nothing that has this name.

This page is pretty useless if you can't get into step 1.

**Comment by urbiz-nr** [comment]
Thanks for reading our docs, @Bikeman868. We're sorry to hear the workloads status doc was a little confusing, we've opened PR #2124 to update it and make it clearer! Thanks!
