### ISSUE TITLE
Automated release note pages from Github Releases

### ISSUE THREAD

**Issue by josemore** [newrelic/docs-website#2127]
### Problem
Most of New Relic instrumentation is now open source. Multiple products are publishing release notes in two sources: Github Releases and docs.newrelic.com. This is inconvenient since it has extra toil we could avoid with automation. 
From an engineering point of view, having release notes published on Github is ideal, this is our source of truth. 
From a product perspective, customers are used to learn about new releases from documentation. 

### Describe the solution you'd like
It'd be great to have a way to sync release notes in docs.newrelic.com by fetching the information from Github. 

### Describe why this important to you
Additional effort to submit and coordinate release notes once release is ready in Github. 
It's also very common to do quick updates to release notes based on feedback which adds additional effort for the team.

### Additional context
Infrastructure agent release notes in public docs: https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/

**Comment by jpvajda** [comment]
@josemore we totally agree! Not sure of your role at New Relic but for this type of request we'd be looking for agent teams to help build the connection between the repos, would that be something you or some of your counterparts may be interested in taking on? If so just let me know and I can help give you some guidance of how to get started.
