### ISSUE TITLE
Investigate high JS error count

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/docs-website#2129]
# Summary
Look into why our JS error alert condition is firing.

**Comment by aswanson-nr** [comment]
There were 2 main errors seen during the time range of these incidents.
1. `$ is not defined`
    * I am assuming this is a browser extension looking for JQuery. Since there is nothing we can do about this and it doesn't affect the site itself, I have set it to be ignored in the future.
2. `JSON.parse: unexpected character at line 1 column 1 of the JSON data`
    * I was unable to reproduce this error and it seems to come from a variety of Firefox versions, although the majority of errors during the incident came from Firefox 88.

**Comment by roadlittledawn** [comment]
I wonder if number 2 is when a user might be in high security mode in Firefox or other browsers and it blocks something that generates the error. i remember another error related to marketo scripts being blocked by this that i _think_ had a similar error message

**Comment by aswanson-nr** [comment]
@roadlittledawn I was thinking about that, so I tried enabling Firefox's 'strict' protection and no luck. Although I'm sure it could be an ad blocking extension.
The majority of the errors come from this URL `https://docs.newrelic.com/docs/agents/php-agent/getting-started/introduction-new-relic-php/`, but the page appears to be operating normally, even on Firefox 86 and 88.
I'm starting to wonder if this is also somehow related to a browser extension...
