### ISSUE TITLE
Issue: Our EU and US region data centers

### ISSUE THREAD

**Issue by rconto** [newrelic/docs-website#2132]
### Tell us what you need

* If you've found something inaccurate, what is it?  LogPatterns is not available in the EU domain and should be listed as such. Please check page for more info: https://docs.newrelic.com/docs/logs/log-management/ui-data/find-unusual-logs-log-patterns/#availability
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/our-eu-us-region-data-centers/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 90.0.4430.85
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @rconto, wondering if you can provide some context on the issues you observed with the two docs you link here? It's not entirely clear to me what needs attention, but I would like to help if I can. Thanks!

**Comment by zuluecho9** [comment]
@dbarnesbrownNR maybe to solve this we just add detail about log patterns not being available to https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/our-eu-us-region-data-centers/#regions-availability and call it day?

**Comment by dbarnesbrownNR** [comment]
Moving back to triage but I intend to follow up on this next week so hero can feel free to hmu if they get here first.

**Comment by mmfred** [comment]
This is now fixed - I noted that Log patterns aren't available in the EU region in two places.
