### ISSUE TITLE
Issue: User Management API -  Support 

### ISSUE THREAD

**Issue by amanborkar99** [newrelic/docs-website#2143]
# Query
Hello, I want to know that in New Relic is there any User Management API which is able to perform Create, Read ,Update and Delete User using HTTP requests, like using CURL.... and also the regarding Documentation about various POST, GET and PATCH, DELETE methods for it.

## Context
 * By searching through all available API's I was able to get the **LIST ALL USERS** API in Management [LINK IS HERE](https://docs.newrelic.com/docs/apis/rest-api-v2/account-examples-v2/listing-users-your-account/).
 
If anyone could help me know whether there is API for Create, Update and Delete the User in New Relic.
Thanks for hearing out!! :)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/find-help-use-support-portal/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@amanborkar99, sorry it took us so long to respond! We have an API for users, but it is subject to some restrictions. It's designed either for companies acting as New Relic partners or for large companies that have been given access to our account structure. We have some basic documentation here: https://docs.newrelic.com/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partner-api/

I hope this helps.

**Comment by zuluecho9** [comment]
@amanborkar99 A little more info: we currently have two different account/user models, which you can read more about here: https://docs.newrelic.com/docs/accounts/original-accounts-billing/original-product-based-pricing/overview-changes-pricing-user-model/#user-models. 

What @rhetoric101 said is correct for accounts on our original account/user model: we have some view/list functionality with our REST API (https://docs.newrelic.com/docs/apis/rest-api-v2/account-examples-v2/listing-users-your-account/) and then we have the Partnership API for user mgmt procedures, but that is only available to certain organizations. 

For organizations on our newer account/user model (New Relic One model), we don't yet have an API for user mgmt. But that is in the works. For more on doing those user mgmt procedures in the UI, see https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/introduction-managing-users/.

**Comment by amanborkar99** [comment]
Thanks that clears my doubt about User management.
