### ISSUE TITLE
Issue: Distributed tracing: Planning guide

### ISSUE THREAD

**Issue by sskilbred** [newrelic/docs-website#2157]
Is it still accurate that enabling distributed tracing for APM impacts Mobile related features now that  NR Mobile supports distributed tracing?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/distributed-tracing/concepts/distributed-tracing-planning-guide/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@sskilbred, thanks for pointing this out! We need to remove that comment about Mobile not being supported. I'm checking with the distributed tracing team to confirm about the effects on service maps and the app drill down.

**Comment by rhetoric101** [comment]
@sskilbred, sorry it took so long, but I confirmed that legacy service maps won't work with Mobile distributed tracing and the drill-down doesn't work for  legacy Mobile HTTP requests. We'll be updating the planning guide shortly.
