### ISSUE TITLE
Research Build Time Improvements

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#2158]
## Description
Building the docs site takes _a long time_ and upgrading to Gatsby v3 didn't have a significant impact on these build times. We should conduct a build time audit to determine the following:

## Acceptance Criteria

- [x] What are the different steps in the build process?
- [x] How long does each step in the build take?
- [x] Is there any way to improve each build step?
- [x] Is there any way to skip some of the build steps?
- [x] What are other large-scale Gatsby sites doing to tackle these issues?

* [x] Outline a plan to reduce the overall build times

**Comment by rudouglas** [comment]
Will do some actual tests on this tomorrow, but a couple of [Feature Flags that could help](https://www.gatsbyjs.com/docs/reference/release-notes/v2.28/#feature-flags-in-gatsby-configjs) are:

 - QUERY_ON_DEMAND - Only run queries when needed instead of running all queries upfront. Speeds starting the develop server.
 - LAZY_IMAGES - Don’t process images during development until they’re requested from the browser. Speeds starting the develop server (requires gatsby-plugin-sharp@^2.10.0). See Experimental: Lazy images in develop section for additional details.

It's also possible to restrict the number of pages built in development, so i'll look into that a bit more. ([Ref](https://www.gatsbyjs.com/docs/how-to/performance/improving-build-performance/#improving-develop-times))

**Comment by nr-kkenney** [comment]
@zstix were you thinking speed up production builds, develop builds / local running, or both?

i assume we want all the goodness if we can get it, but we might want to prioritize the effort.

**Comment by rudouglas** [comment]
@nr-kkenney no worries :P i think this ticket is just for Development, am i right in thinking a lot of the build stuff will be solved with Gatsby Cloud?

### Notes:
Gatsby gives the option of adding Tracing to the `develop` and `build` commands, so i've setup an example using [Jaeger and Docker](https://www.gatsbyjs.com/docs/performance-tracing/#local-jaeger-with-docker) with the following

https://github.com/newrelic/docs-website/tree/ruairi/buildtime-tracing
 - `yarn add jaeger-client`

 Make sure Docker Daemon is on then run:

```
docker run -d --name jaeger \
    -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
    -p 5775:5775/udp \
    -p 6831:6831/udp \
    -p 6832:6832/udp \
    -p 5778:5778 \
    -p 16686:16686 \
    -p 14268:14268 \
    -p 9411:9411 \
    jaegertracing/all-in-one:1.8
```

Then run either of these commands depending on what you're tracing:
```
gatsby develop --open-tracing-config-file node_modules/gatsby/dist/utils/tracer/jaeger-local.js
gatsby build --open-tracing-config-file node_modules/gatsby/dist/utils/tracer/jaeger-local.js
```

Once it's done you should be able to query the traces at `http://localhost:16686/search`.

I've also added tags in the `/node_modules/gatsby/dist/utils/tracer/jaeger-local.js` file to be able to differentiate between different commands and different flags/features

```
const options = {
    tags: {
      'command': 'develop',
      'flag': 'DEV_SSR'
    }
  }
```

Will post some example results soon... 🕐

**Comment by rudouglas** [comment]
Here's the initial run for `gatsby develop`:
![Screenshot 12-05-2021 14-18-20](https://user-images.githubusercontent.com/17122543/117981500-fa0cae00-b32c-11eb-84fd-e9bfbf3c5726.png)

**Comment by rudouglas** [comment]
Would it also be worth using something like [depcheck](https://github.com/depcheck/depcheck) to analyze dependencies and remove unused packages to speed up initial setup time?

**Comment by rudouglas** [comment]
`PARALLEL_SOURCING` is another flag we can test

**Comment by nr-kkenney** [comment]
this is somewhat related. i mentioned this to @aswanson-nr this morning, but in using amplify, we have to do a full build for every production deployment we do. if you look at the UI, or the data I collected in the related ticket, you can see this is the case.

once we migrate to gatsby cloud, and get things like caching & incremental builds / storage of artifacts across builds, that means we will for sure get some performance improvement for our production builds.

**Comment by rudouglas** [comment]
I've written a page in the Wiki (mostly because i didn't know where else to document this):
https://github.com/newrelic/docs-website/wiki/Benchmarking-Build-Times

I've gone some way to answering the questions above but there is a bit of research needed on each long-running step.
