### ISSUE TITLE
Issue: Amazon CloudWatch Metric Streams integration

### ISSUE THREAD

**Issue by djaffinito** [newrelic/docs-website#2177]
### Tell us what you need

Under the  ['Automated setup using CloudFormation'](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/#setup-cloudformation) section, it's implied that the CloudFormation template can automate the entire process, however it will not add the AWS account to NR as a metric stream. This step still needs to be performed manually. This is currently listed under the ['Manual setup using AWS Console, API, or calls'](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/#manual-setup-using-aws-console-api-or-calls) as step 3.

The document should be updated to add the AWS account to NR first, then do either the automated process, or steps 1 and 2 from the manual process.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-metric-stream/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for getting in touch, @djaffinito! Let me have a look!

**Comment by urbiz-nr** [comment]
Tackling this in #2178.
