### ISSUE TITLE
Issue: Transactions in New Relic APM

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#2179]
### Tell us what you need

- We are seeing in support customers asking about the "subtypes" of the transactions.
- As these subtypes are related to the instrumentation done by the APM Agent, would be necessary to have at least some docs saying from where they come and some examples. 
  - For different APM Agents I've seen common subtypes, like: `StatusCode`, the name of the language: `Java`, `PHP`, `ASP` etc.
  - This is mentioned shortly [[here]](https://discuss.newrelic.com/t/types-of-transactions-under-explorer/138620/2)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/transactions/intro-transactions/transactions-new-relic-apm/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@rodrigo-corgozinho, thanks for your input on this! I created an internal documentation Jira (doc-6882) to track our progress on this.

**Comment by urbiz-nr** [comment]
Closing via #2882.
