### ISSUE TITLE
Issue: Windows services integration

### ISSUE THREAD

**Issue by moyerky** [newrelic/docs-website#2180]
### Tell us what you need

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

My comment is on this statement here:
By default, no service is included. To include and filter services, you must edit include_matching_entities:.

I understand that I need to provide the names of the services I'm interested in capturing for though when I get to the sample file this is shown for that config:

      include_matching_entities:
        windowsService.name:
          # - regex "^*$"
          # - "ServiceNameToBeIncluded"

Notice the regex line. What is the purpose of that regex line? Can I remove it and provide a static list of service names?  Does the regex line have to be there? Can the regex line be used in isolation (i.e. no other lines specifying service names)?

Just some context and clarification around the regex line would be appreciated. Looking forward to using this integration :)

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/windows-services-integration/
* **OS**: Windows 10
* **Browser**: Chrome 90.0.4430.93
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@moyerky, I'm checking with our team to see if you can use the regex with the static list of entities or if it's one or the other.

**Comment by moyerky** [comment]
Awesome :), many thanks!

**Comment by rhetoric101** [comment]
This change is now published.
