### ISSUE TITLE
Automatically build the site

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#2192]
### Is your feature request related to a problem? Please describe

Currently the docs hero manually builds the site a few times a day to get content changes live on the site. In future, it'd be great to remove some toil and automatically build the site.

### Describe the solution you'd like

On a set schedule, open and merge a PR from develop to main. One idea for a schedule:

* 4 AM Pacific
* 8 AM Pacific
* 11 AM Pacific
* 3 PM Pacific

This would require that writers ensure we don't merge anything into develop until it's 100% ready to go (this is already our practice and standard).

There are security and reliability questions to work through here, so opening an issue as a starting point for discussion per our conversation earlier this week @jpvajda and @zstix 

### Describe why this important to you

In the long run, I'd like the build process to become completely invisible—for example, we build the site hourly or even more often. As an interim step, I'd like to remove items from the "things the hero has to remember to do" list.

**Comment by jpvajda** [comment]
this would come after gatsby cloud migration, and we still need to evaluate this approach my recommendation is we start with one automated build time / twice a week and learn from how it goes.

**Comment by austin-schaefer** [comment]
Still valid
