### ISSUE TITLE
Feedback: addPageAction (Browser agent API)

### ISSUE THREAD

**Issue by LeslieMurphy** [newrelic/docs-website#2193]
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?
TRY ME LINK IS BROKEN.

Example does not show what JS to include such that var newrelic is defined so I can use newrelic.addPageAction

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action/
* **OS**: Windows 10
* **Browser**: Edge 90.0.818.51
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
@LeslieMurphy, thanks for reporting this! We'll be fixing it soon, you can check the details in #2196.
