### ISSUE TITLE
Inconsistent behavior clicking in left nav

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#221]
### Is your feature request related to a problem? Please describe

Sidebar navigation links behave differently depending on whether there's a landing page:

1. Go here https://docs-preview.newrelic.com/docs/agents/java-agent/additional-installation/install-java-agent-using-maven
2. Click on *Java agent*. Notice that you are navigated away from the page.
3. Go back to https://docs-preview.newrelic.com/docs/agents/java-agent/additional-installation/install-java-agent-using-maven
4. Click on *API guides*. Notice that you do not navigate away from the page

It makes sense that we want to expose the landing pages, but it's confusing to have a navigation element behave differently depending on whether a landing page exists (at least without some indication for the user that the landing page navigations are "special"

### Describe the solution you'd like

Possible solutions:

* Make all navigation behave the same way
* Add a visual indicator of what's going to happen

### Describe why this important to you

I feel anxious clicking on sidebar links right now because I don't know if I'll be pulled away from my context.

**Comment by austin-schaefer** [comment]
Stalebot closed this while I was on PTO, but I think this is one we still need to solve.

**Comment by austin-schaefer** [comment]
Reopening this one again. Still an issue I'd like us to address at some point—perhaps when we fix some of the other quirkiness in the navigation behavior.

**Comment by jpvajda** [comment]
SOP API Guides doesn't have an index page, this is why it's occurring this way. To me this isn't a bug, it's how the nav works, if we want API guides to function like java agent page, we just need an index page for APi Guides. @jerelmiller  agree?

**Comment by jerelmiller** [comment]
I agree. This is a change that we'll have to consider for both dev and docs sites since this is working as intended. @jpvajda laid out a good short term fix for this particular page.

**Comment by austin-schaefer** [comment]
This was fixed incidentally in #2260. Possible we might want to do more work on this in future if users don't like the new sidebar model, but closing this for now.
