### ISSUE TITLE
Issue: Query system limits

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#2244]
### Tell us what you need

The link is broken.
[ type of limit that’s reached](https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/manage-data/view-system-limits/#violations)

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/manage-data/query-limits/
* **OS**: Windows 10
* **Browser**: Chrome 90.0.4430.212
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @qryuu - it will be fixed in PR #2245.
