### ISSUE TITLE
Issue: Introduction to querying New Relic data

### ISSUE THREAD

**Issue by mb-newrelic** [newrelic/docs-website#2254]
### Tell us what you need

Can we consider changing the title here to:
Introduction to querying data in New Relic

I found "New Relic data" in the existing title to be a little confusing and potentially misleading.

Thanks! 

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/get-started/introduction-querying-new-relic-data/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 90.0.4430.93
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Good point! I understand the nuance you are getting at. I'll change the title.
