### ISSUE TITLE
Upgrade Docs Site to Gatsby v3.5

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2255]
### References

[Release Notes](https://www.gatsbyjs.com/docs/reference/release-notes/v3.5)

### Acceptance Criteria 

- [ ] site is upgraded to Gatsby v3.5
- [ ] upgrade any dependency packages 
- [ ] Site builds and renders and passes all tests
- [ ] run build comparison analysis for local builds and GH builds to get a sense of overall improvements in build times.

**Comment by nr-kkenney** [comment]
i think well need to collect data over time to be convinced, but as a simple comparison:

the pr for this issue had:
gatsby build time: 41m 32s.
github build time: 47m, 16s.

for a pr to main (non 3.5):
gatsby build time: 42m 3s
github build time: 50m 2s

things may look faster, but i think really they are in the same ballpark, no significant improvements.
