### ISSUE TITLE
Free Account button treatment color update: Due 7/23

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2262]
Relates to: https://github.com/newrelic/gatsby-theme-newrelic/issues/356

run a new color test on this button treatment.

**A/B Test Definition**

```
blue: var(--color-teal-400)
 red: --color-red-400
```

`Test Start Date:` 7/23/21
`Test End Date: ` 8/6/21

### Acceptance Criteria 

- [x] Confirm with @austin-schaefer  if we should remove any split test code that is no longer required for a future test. 
- [x] Work with @Broseberg on a new color treatment.
- [x] finalize color treatment
- [x] update contributor guide to explain the basics on split tests.
- [ ] Implement a new color treatment

**Comment by jpvajda** [comment]
@austin-schaefer when we pick a winner for this a/b test do you want us to leave all the code in place for this test, in case we want to test again? we can either remove it (_preferred if we don't plan on executing this test again_) or leave it in for a future test. 

I'm thinking this is a type of test that may be run again, so leaving it in place could be a good idea.

**Comment by jpvajda** [comment]
as note: the code is only going to allow to change the button color in the future, if we need another type of test we'd create a new test. - @austin-schaefer

**Comment by austin-schaefer** [comment]
@jpvajda I'm fine keeping the code in place for future tests, though I'm not sure we'll be testing button color specifically soon.

**Comment by jpvajda** [comment]
I've proposed the following options to @austin-schaefer 

`1` run the test longer to get more data. `2` pick a color winner based on the data.  `3 `maybe try more colors? 🤷

**Comment by jpvajda** [comment]
marking as blocked until we direction how to proceed on this test. options are above.

**Comment by jpvajda** [comment]
Next steps:

We'll consider which blue to test against a more distinct color difference like New Relic Orange.

**Comment by jpvajda** [comment]
@Broseberg is going to follow up on this for the color selection.

**Comment by jpvajda** [comment]
I followed up in the color treatment to use next, going to mark as blocked until we hear back.

**Comment by jpvajda** [comment]
Moving out of all sprints until we get direction on the color treatment we wish to use for the next test.

**Comment by jpvajda** [comment]
```
blue: var(--color-teal-400)
red: --color-red-400
```

a suggestion from @jerelmiller 

<img width="517" alt="Screen Shot 2021-07-09 at 2 32 15 PM" src="https://user-images.githubusercontent.com/1395158/125138400-cd2a0c80-e0cb-11eb-9df0-cd011c166dd6.png">
<img width="389" alt="Screen Shot 2021-07-09 at 2 32 29 PM" src="https://user-images.githubusercontent.com/1395158/125138402-cdc2a300-e0cb-11eb-8c98-8c0f8823667f.png">

**Comment by Broseberg** [comment]
I love it! Let's do it. Jerel coming in clutch.

**Comment by jpvajda** [comment]
I was working on the issue to change our button colors for a/b split test. We've been using JSON up until this point with HEX color codes, @jerelmiller  you recommended what I think is key value pairs. It looks like you can set that in Split, but i wanted to double check the format before proceeded

<img width="844" alt="Screen Shot 2021-07-19 at 3 06 55 PM" src="https://user-images.githubusercontent.com/1395158/126227657-f1aadf2b-6a47-4635-9208-2d5809b21bc2.png">

**Comment by jerelmiller** [comment]
Those values I gave you were CSS variables. Here are the hex codes for each if you'd like to use hex directly (not sure what happens if you use CSS var values in split 😄 )

Blue: `#00b3c3`
Red: `#e56059`

In case you ever need access to the CSS vars and their values, you can right-click; "Inspect element", go to the CSS tab and look for the `:root` selector. That has all of the CSS vars listed.

<img width="1916" alt="Screen Shot 2021-07-19 at 3 19 47 PM" src="https://user-images.githubusercontent.com/565661/126234723-c3dc6756-a51a-4c06-9b16-e4334410a4b4.png">

**Comment by jpvajda** [comment]
The changes are made, Just waiting on a review from @jerelmiller before making them live in split.io

**Comment by jerelmiller** [comment]
Approved
