### ISSUE TITLE
Issue: New Relic account structure -cancel membership

### ISSUE THREAD

**Issue by sim1ne** [newrelic/docs-website#2266]
Please cancel membership. i sent you guys several emails but no response 

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-users/new-relic-account-structure/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by sim1ne** [comment]
Please cancel membership. i sent you several emails but no response

**Comment by barbnewrelic** [comment]
We are sorry you want to cancel your account. Depending on your account type, you can either delete it yourself through the UI, or contact your New Relic account rep. Hope this helps!
https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/downgradecancel-account/#cancel
