### ISSUE TITLE
Send Build Status notifications via Slack when a build check pass / fail

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#2285]
It's super useful that we get PR status updates in Slack, but it would be great if we got separate notifications specifically when a build check fails. As it is currently, there's a lot of checking and re-checking that the build checks have completed.

### Possible Approach

[Setup Gatsby Cloud to send notifications to slack](https://support.gatsbyjs.com/hc/en-us/articles/1500000480181-Outgoing-Notifications)

### Acceptance Criteria

- [ ] Build Status is communicated to #documentation slack room. 
- [ ] setup the four options for event notifications in Gatsby to send to Slack

-  build success
-  build failure
-  deploy success
-  deploy failure

- [ ] Point webhook to internal slack channel`#doc_site_deploys` & `#dev-enablement-bots`
- [ ] Remove bot from dev-en-sandbox on slack staging

**Comment by jpvajda** [comment]
Pass & Fail notifications would be cool...We can consider this after we make the move to gatsby cloud and see how much better it is for you all with builds. It may not be necessary as our testing showed more reliability in build completing.

**Comment by jpvajda** [comment]
Confirming with @paperclypse where the notifications should be sent. I assume the #documentation room.

**Comment by jpvajda** [comment]
I set up a test Slack bot and webhooks to send notifications to our dev-en sandbox account on slack. 

<img width="682" alt="Screen Shot 2021-06-21 at 4 20 43 PM" src="https://user-images.githubusercontent.com/1395158/122834917-c36f6f00-d2ac-11eb-85c9-57bcd12873b1.png">

**Comment by jpvajda** [comment]
<img width="825" alt="Screen Shot 2021-06-21 at 4 25 04 PM" src="https://user-images.githubusercontent.com/1395158/122835291-4ee90000-d2ad-11eb-970e-fc4de5c2a622.png">

**Comment by jpvajda** [comment]
Testing passed!  This looks great in slack staging so I just need to confirm where these messages should go and into which channel for the docs team. 

![Screen Shot 2021-06-22 at 10 05 58 AM](https://user-images.githubusercontent.com/1395158/122961530-b94b8000-d341-11eb-9830-8ffef55ad721.png)

**Comment by jpvajda** [comment]
Confirming with @austin-schaefer where these notifications should go, then I can set Gatsby up to point to the production slack channel of his choice.

**Comment by jpvajda** [comment]
I've request IT to move the app built on slack staging over to production...

**Comment by jpvajda** [comment]
This setup is complete! 

  if you go into the site settings in Gatsby Cloud for`Docs-Website:Main` it looks like this... as 4 events fire to  2 different slack channels, so it's 8 notifications in total.

<img width="791" alt="Screen Shot 2021-06-25 at 2 27 52 PM" src="https://user-images.githubusercontent.com/1395158/123483797-8b29a280-d5c4-11eb-81ae-79ddc95fd9fc.png">

**Comment by jpvajda** [comment]
I documented our use of Gatsby Cloud here: https://github.com/newrelic/docs-website/wiki/Site-Architecture#-hosting-and-deployment

I'll also confirm this is working once a build and deploy is made to main..
