### ISSUE TITLE
Docs feedback

### ISSUE THREAD

**Issue by jake-codes** [newrelic/docs-website#2289]
It's a shame that we got rid of the search bar in the data dictionary. Now users have to either search through all of the docs globally or toggle and scroll through every option until they find what they're looking for. 

### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for the feedback @jake-codes! This does seem like a useful feature; let me chat with the team to see what we can do.

**Comment by bradleycamacho** [comment]
Hi @jake-codes  ! Thanks for the feedback. I just realized this is already on our radar, and we actually have an issue for this at #626. Closing this one but linking the two so we know there's interest in adding this!
