### ISSUE TITLE
Issue: Query system limits

### ISSUE THREAD

**Issue by Steve24by7** [newrelic/docs-website#2297]
On this page
https://docs.newrelic.com/docs/telemetry-data-platform/manage-data/query-limits/

In this paragraph
An NrIntegrationError is generated when you experience impact and is a good way to quickly see if you’re experiencing any limit events. See View System Limits for more information.

The "View System Limits" link points here but gives a 404.
https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/manage-data/view-system-limits/

**Comment by x8a** [comment]
Thanks for spotting this, @Steve24by7! Closing this issue since we've fixed it with #2298.
