### ISSUE TITLE
Issue: New Relic One pricing: Definitions - AIOps missing?

### ISSUE THREAD

**Issue by mtjagg** [newrelic/docs-website#2306]
### Tell us what you need

I don't see any definitions of the AIOps pricing units - Incident Intelligence Events - listed.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/licenses/license-information/product-definitions/new-relic-one-pricing-definitions/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 90.0.4430.212
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for reporting this oversight @mtjagg. I'll look into this and update the doc.

**Comment by barbnewrelic** [comment]
Thanks for reporting this! I've asked one of our team members who has deeper knowledge whether this is simply an oversight and an easy fix, or whether this would require more investigation.

**Comment by zuluecho9** [comment]
I'll ask the pricing team about this.

**Comment by zuluecho9** [comment]
Submitted edit to add AI events to new pricing doc. This definition should apply for AI and II. https://github.com/newrelic/docs-website/pull/2358
