### ISSUE TITLE
Feedback: PHP agent and Heroku

### ISSUE THREAD

**Issue by BurningDog** [newrelic/docs-website#2312]
### Tell us more about your feedback

Broken link to newrelic.ini_.heroku in the [Configure the agent on Heroku](https://docs.newrelic.com/docs/agents/php-agent/advanced-installation/php-agent-heroku/#config) section - the link is https://docs.newrelic.com/sites/default/files/atoms/files/newrelic.ini_.heroku but that doesn't exist.

### Doc information

* https://docs.newrelic.com/docs/agents/php-agent/advanced-installation/php-agent-heroku/
* **OS**: Mac OS 10.14.6
* **Browser**: Firefox 88
* **Device**: Macbook Air

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @BurningDog, we'll fix it!

**Comment by urbiz-nr** [comment]
Also reported in #2327.

**Comment by paperclypse** [comment]
Hi @BurningDog! I wanted to let you know that I've fixed the broken link to that INI file. Thanks so much for letting us know.
