### ISSUE TITLE
Feedback: Transactions named /index.php or /unknown

### ISSUE THREAD

**Issue by NiklasBr** [newrelic/docs-website#2316]
### Tell us more about your feedback

The docs says:

> If the agent is not detecting your framework for some transactions, you can use our API to name your transactions.

* How can we improve this doc?

We are using a [Symfony](https://symfony.com/) application and it is unclear where in this application we should add the `newrelic_name_transaction ($controller . '/' . $action);` section.

What we are missing is a trace (at least partial) to help find where to add this code.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/php-agent/troubleshooting/transactions-named-indexphp-or-unknown/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hello @NiklasBr, thanks for letting us know! I've spoken to the PHP agent team and they'll update the doc accordingly. Cheers!

**Comment by urbiz-nr** [comment]
Fixed in #2446.
