### ISSUE TITLE
Break up extremely large markdown files to help reduce terminal errors on cold builds

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2317]
### Relates to 
#2307 

### Issue

We have several very large pages that act as an index of information that ~~could be slowing down build times~~. that are generating terminals errors on cold builds

  We'd like to request the Docs Team consider breaking these page up into smaller files. Alternatively we could look at setting Babel to not trip in 500kb limit.

### References

https://stackoverflow.com/questions/35192796/babel-note-the-code-generator-has-deoptimised-the-styling-of-app-js-as-it-exc/36880182

### Steps to reproduce & Build Test results

- run `gatsby clean`
-  run `gatsby build`
-  see errors 

- Testing to confirm actual build time improvements without these pages - `no significant improvements
- Reducing those pages cut down almost all of the build-time warnings / errors 

### Example pages

```
4358 src/content/docs/integrations/google-cloud-platform-integrations/get-started/gcp-integration-metrics.mdx
4557 src/content/docs/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
5240 src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
10865 src/content/docs/licenses/license-information/other-licenses/services-licenses.mdx
```

### Example errors 

```
ERROR 

[BABEL] Note: The code generator has deoptimised the styling of /Users/jvajda/Documents/Github/DevEn/docs-website/src/content/docs/licenses/license-information/other-licenses/services-licenses.mdx
 as it exceeds the max of 500KB.


 ERROR 

[BABEL] Note: The code generator has deoptimised the styling of
/Users/jvajda/Documents/Github/DevEn/docs-website/src/content/docs/integrations/amazon-integrations/get-started/aws-integrations-metrics.mdx as it exceeds the max of 500KB.


 ERROR 

[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.


 ERROR 

[BABEL] Note: The code generator has deoptimised the styling of
/Users/jvajda/Documents/Github/DevEn/docs-website/src/content/docs/infrastructure/manage-your-data/data-instrumentation/host-integrations-metrics.mdx as it exceeds the max of 500KB.

```
### Acceptance Criteria 

- [ ] Discuss with @austin-schaefer what approach can be taken on this page.
- [ ] Decide on approach and make necessary file changes. 
- [ ] Deploy changes. 
- [ ] 🚀

**Comment by zstix** [comment]
Unfortunately, after further research, I have invalidated my earlier findings that removing these big files sped up the build time. That said, removing the top 9 files (listed below) reduced the build-time errors to _zero_. This is something we should continue to look at, but may be less crucial than I originally thought.

```
src/content/docs/agents/java-agent/configuration/java-agent-configuration-config-file.mdx
src/content/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings.mdx
src/content/docs/infrastructure/manage-your-data/data-instrumentation/host-integrations-metrics.mdx
src/content/docs/integrations/amazon-integrations/get-started/aws-integrations-metrics.mdx
src/content/docs/integrations/google-cloud-platform-integrations/get-started/gcp-integration-metrics.mdx
src/content/docs/integrations/host-integrations/host-integrations-list/mongodb-monitoring-integration.mdx
src/content/docs/integrations/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx
src/content/docs/integrations/microsoft-azure-integrations/get-started/azure-integration-metrics.mdx
src/content/docs/licenses/license-information/other-licenses/services-licenses.mdx
```

**Comment by roadlittledawn** [comment]
Closing this in favor of https://github.com/newrelic/docs-website/issues/6130
