### ISSUE TITLE
Remove the translated MDX file when a locale is removed or file is deleted

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#2323]
## Description
When a contributor removes a locale from the `translate` frontmatter, we should remove the translated file from the repository. If we don't the translated file will get more and more out of date with it's English counterpart. This will probably require adjusting [`add-files-to-translation-queue.js`](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/add-files-to-translation-queue.js).

### Acceptance Criteria 

- [ ] When a contributor removes a locale from the `translate` frontmatter, we should automaticalluy remove the translated file from the repository.
- [ ] when the english version of a file is deleted, we want to remove the translated version of a file.
- [ ] Ensure this change is documented in our localization GDrive Doc `DevEn: Localization: how it works`

**Comment by jpvajda** [comment]
This issue relates to the corner case raised about broken links on localized due to pages being removed from the english site it's a future problem for us to consider

https://github.com/newrelic/docs-website/issues/2749
