### ISSUE TITLE
Issue: PHP agent and Heroku broken link

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#2327]
### Tell us what you need

* The link to download the `newrelic.ini.heroku` file is broken (404)
* Link for ref: https://docs.newrelic.com/sites/default/files/atoms/files/newrelic.ini_.heroku

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/php-agent/advanced-installation/php-agent-heroku/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 90.0.4430.212
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @rodrigo-corgozinho - we already have an open issue regarding this link, you can check it out in #2312.

**Comment by rodrigo-corgozinho** [comment]
Thank you @urbiz-nr
