### ISSUE TITLE
Issue: Troubleshoot password, email address, and login issues

### ISSUE THREAD

**Issue by hsue** [newrelic/docs-website#2345]
### Tell us what you need
Trouble logging in.
I have accessed new relic in the past, it's been a year or 2 but I was able to access it before.  At first I thought I forgot my password, so I tried reset password.  I was able to do that, but still failed to login after resetting the password.  I even tried resetting password twice and still got this error:

Unable to log in. Please ensure that your email and password are correct.
Please advise. 
my username is hsue@volunteermatch.org

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jpvajda** [comment]
@hsue 👋  This is actually the repository for our product documentation and we don't handle account or login issues. 

Do you have an existing account that has New Relic Support? If so I suggest contacting New Relic Support via our ticket process. If you do not have New Relic Support, I can pass this issue on to our team that handles authentication and authorization to see if there something wrong with your account.

**Comment by rudouglas** [comment]
Hi @hsue the best way to do that would be to post a topic in our [Community Accounts section](https://discuss.newrelic.com/c/new-relic-accounts/473) and one of our Support Engineers will be able to assist :)

**Comment by hsue** [comment]
I cannot post a topic because I cannot login! My issue is I cannot login.
Can you post an issue for me?

**Comment by jpvajda** [comment]
@hsue I actually contacted our auth team internally to find out who can assist you, just awaiting a reply. Also what you can do to post in the topic @rudouglas  mentioned is create a free account with a different email address on New Relic and reference your problem with you primary account. 

https://newrelic.com/signup

**Comment by jpvajda** [comment]
@hsue here is some final input from our AAA team. 

_We haven’t been able to locate his login attempts via querying, so it’s difficult for me to guess what his problem may be. I took a look at his user record and nothing stood out to me as being incorrect. Is there a chance he didn’t set his new password to the value he thought he did so he is just typing in the wrong password? It might help if he tried the password change process again._

**Comment by hsue** [comment]
I just tried to login now and it's 4:05pm PST.  I tried all 3 different
passwords, 2 of them I have recently reset.
And I just reset my password at 4:07pm PST.  and tried to login again at
4:08pm PST right now and still failed with this error:
Unable to log in. Please ensure that your email and password are correct.

There's no error on my browser console
my username/email is ***@***.***

**Comment by jpvajda** [comment]
@hsue -  Github stripes out the email address in comments for security reasons, let me pass this info onto our AAA team, did you open up a topic for help per our advise above? We apologize but our team has nothing to do with authentication or user login problems, we are trying to get you the right place though. 😄

**Comment by hsue** [comment]
yes, I just created a free account and created an issue.  thx for your help
