### ISSUE TITLE
Issue: Introduction to querying data in New Relic

### ISSUE THREAD

**Issue by antonmry** [newrelic/docs-website#2347]
It seems there is a broken link to https://docs.newrelic.com/docs/apis/get-started/intro-apis/introduction-new-relic-apis/ in
https://docs.newrelic.com/docs/query-your-data/explore-query-data/get-started/introduction-querying-new-relic-data/

It may be https://docs.newrelic.com/docs/apis/intro-apis/introduction-new-relic-apis/ ?

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @antonmry. We'll fix it in #2348.
