### ISSUE TITLE
Issue: Roles and permissions with automated user management

### ISSUE THREAD

**Issue by adiosspandit** [newrelic/docs-website#2349]
### Tell us what you need

* The document describes steps when Identity Provider groups logically map to NR groups but it does not describe next steps and guidance on what to do if Identity Provider groups **do not** logically map to NR groups
Would be good to have a section which describes what happens and what is needed in that case(when NR groups are different from Identity Provider groups).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts/automated-user-management/roles-permissions-automated-user-management/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 90.0.4430.93
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @adiosspandit! Thanks for filing this issue. I'm looking into your suggestion now.

**Comment by zuluecho9** [comment]
@adiosspandit Thanks Adi. I'm actually working on some SAML and SCIM-related edits to the docs as we speak, so I will try to address this with these upcoming edits. But long story short: we will want to point them to the new user management procedures: https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/add-manage-users-groups-roles/#understand-concepts, which describe how they'd need to create custom groups and then add users to those groups.

**Comment by bradleycamacho** [comment]
@zuluecho9 Could you take a look at this and update it with the status? Thanks!

**Comment by austin-schaefer** [comment]
Closing out issues older than 90 days, feel free to re-open if anyone would like us to revisit this issue!
