### ISSUE TITLE
Change translation submission from every week to every 2 weeks

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#2361]
### Is your feature request related to a problem? Please describe

Can we please change the submission of translation update to every 2 weeks (from the current every week)?

### Describe the solution you'd like

Content is sent to translation every 2 weeks (the current day of the week is fine).

### Describe why this important to you

This will help better manage the translation workflow.

### Acceptance Criteria 

- [ ] Cron job is changed from every week to every 2 weeks or on the 1st an 15th of the month

**Comment by jpvajda** [comment]
I'll take this one as I'm interested in how this works.

**Comment by jpvajda** [comment]
we just need to adjust the cron job in[this file](https://github.com/newrelic/docs-website/blob/f2f7b9e65a4876429ebacbf9b31642321a22e17c/.github/workflows/send-content-to-translate.yml#L7) it seems:

**Comment by jpvajda** [comment]
so 1st / 15th cron syntax is super straight forward: `0 1 1,15 * *` 

every 2 weeks is a bit outside crons comfort zone but this could work: `0 1 * * Thu [ $(expr $(date +%W) % 2) -eq 1]` which will run it every 2 weeks on thursdays.

**Comment by jpvajda** [comment]
@jmiraNR is there any reason why this has to be every 2 weeks? or can we run it on the 1st and 15th of the month to simplify it?

**Comment by jpvajda** [comment]
References: 

https://cron.help/#0_1_*_*_Thu
https://crontab.guru/#0_1_1,15_*_*

**Comment by roadlittledawn** [comment]
1st and 15th make sense to me. 

i imagine the answer is not really, but do we care at what time of day those run? seems like it can be a bit tricky getting github to run at the specified time. example: we have the `fetch-related-content.yml` in developer set to this schedule: `0 0 * * *`, but it actually runs at around 17:10 each day.

**Comment by jpvajda** [comment]
Agreed, I'll propose the 1st / 15th to @jmiraNR and confirm so we can keep the job simple.

**Comment by jmiraNR** [comment]
1st and 15th are fine. Some will be on weekends etc. but I don't believe that's a problem.
I don't have a preference on time.
