### ISSUE TITLE
There is no way to close an image once it's expanded

### ISSUE THREAD

**Issue by gfranzini321** [newrelic/docs-website#2363]
### Tell us what you need

When you click on the screen shot to enlarge it, there's no way to close that or back out of it without refreshing the page. Normally there would be an "x" in the top right corner to close the enlarged view of the image or you could hit the "back" button but for some reason neither of those expected actions happen.

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

![image](https://user-images.githubusercontent.com/68927252/118884274-3b203780-b8c4-11eb-9531-32bab40c066c.png)

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/log-management/ui-data/use-logs-ui/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jpvajda** [comment]
The only way out of this is to use the back arrow on the browser, even `esc` won't close the image. We'll take a look at this

**Comment by jpvajda** [comment]
this should be fixed temporarily in https://github.com/newrelic/gatsby-theme-newrelic/pull/402 > this will be resolved when we get our amplify deployment issue resolved .

**Comment by gfranzini321** [comment]
Thanks everyone for your time and help on this! I just checked it out and appears the image just opens in a new tab now instead of expanding like most other images. Is this the expected result for this now?

**Comment by jpvajda** [comment]
@gfranzini321 that's correct. it's our approach for now as it's simple and follows a standard seen in many other documentation sites. 😄
