### ISSUE TITLE
Issue: "Lambda@Edge" appear as mailto links

### ISSUE THREAD

**Issue by josemore** [newrelic/docs-website#2369]
### Tell us what you need

* All mentions to Lambda@Edge feature appear as mailto link

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/infrastructure-integrations/cloud-integrations/configure-polling-frequency-data-collection-cloud-integrations/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 90.0.4430.212
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
Thanks for reporting @josemore ! This should be fixed in #2402
