### ISSUE TITLE
Feedback: Configure control plane monitoring

### ISSUE THREAD

**Issue by wreckedred** [newrelic/docs-website#2375]
### Tell us more about your feedback

Sorry to hear this doc wasn't helpful, but we'd love to make it better! We've 
recorded your feedback. Help us improve this content by providing more info:

* How can we improve this doc?
Configure control plane monitoring
Configure Kubernetes with a proxy<<<--------------this link links to the control plane monitoring page
The word "proxy" doesn't appear on that page - there doesn't seem to be a "Configure Kubernetes with a proxy" page

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/configure-control-plane-monitoring/
* **OS**: Linux x86_64
* **Browser**: Chrome 88.0.4324.151
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks for letting us know, @wreckedred! It looks like we have a redirect here pointing from the Configure Kubernetes with a proxy doc to the control plane monitoring doc. I'll create a quick PR to remove that redirect so that the link works in the left nav, there.
