### ISSUE TITLE
Keyboard shortcut cheatsheet

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#2385]
## Summary

Create an affordance to make keyboard shortcuts more discoverable.

## Desired Behaviour

Many sites have an affordance where typing a question mark (`SHIFT+/`) pops up an overlay listing keyboard shortcuts. Reddit, GitHub, Gmail, for example. Adding one for the docs site would make our shortcuts more discoverable.

## Docs impact

We should create a short doc on the docs site that lists the keyboard shortcuts.

## Shortcuts to include

* Collapser controls (`s` to show, `h` to hide)
* Search controls
* ???

### Vimium

![image](https://user-images.githubusercontent.com/55203603/119039070-b63b2980-b968-11eb-98bc-f746c00733fe.png)

### Gmail

![image](https://user-images.githubusercontent.com/55203603/119030034-3e680180-b95e-11eb-8717-df4ec3fb4265.png)

### Github

![image](https://user-images.githubusercontent.com/55203603/119030126-5a6ba300-b95e-11eb-9e1e-d64b0dcb4ae8.png)

**Comment by jpvajda** [comment]
moving the docs-site repo (it was filed in the theme)  and tagging as content as this can be done with no engineering effort.

**Comment by austin-schaefer** [comment]
@jpvajda QQ on that:

* Isn't this a theme issue, since the keyboard shortcuts apply to dev site too?
* I don't think this is primarily a content issue. The main goal is to have an overlay. I'm fine separating out the work to document them separately if that's easier.

**Comment by jpvajda** [comment]
I don't think the dev site uses shortcuts, as the collasper components that contain them are only used on the docs site. the search bar is on the dev site, but the short cut is clearly called out in the search field.  But this is very low priority at the moment.

**Comment by austin-schaefer** [comment]
Still valid
