### ISSUE TITLE
[DDS] Productionize new data dictionary service

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#239]
## Description

To be production-ready, we need to ensure we are ready to handle traffic.

* [x] Setup alerts for the new service (terraform)
* [x] Dashboards
* [x] Define runbooks
* [x] Update README with helpful links
* [ ] Gamedays
* [x] Update service gateway to allow `/sync` route to be publicly available

**Comment by zstix** [comment]
We may want to ask Vince for Elixir-specific things we could alerts.

**Comment by zstix** [comment]
I've got a PR up to set up the alerts. I'd like to try setting up the dashboard [via Terraform](https://registry.terraform.io/providers/newrelic/newrelic/latest/docs/resources/dashboard) as a way to keep everything configured in one place (the repo).

**Comment by zstix** [comment]
In order to speed up this process, I manually created the dashboards [here](https://staging.one.nr/0Zw0Nonj).
