### ISSUE TITLE
Filter out pages that are in "closed beta" from the Related Resources section

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#2398]
## Description
There are some pages that are published as part of a "closed beta" but aren't ready for the broader public to consume. We would like to ensure that these docs are _not_ displayed in the "Related Resources" section in the right rail.

**Comment by zstix** [comment]
We should probably just remove these pages from Swiftype entirely.

**Comment by jpvajda** [comment]
Austin took this a content issue and will correct this beta docs page to not be present on the docs site. If this continues to be a problem we can look to put something in place where we don't allow swiftype to index these pages, perhaps on a frontmatter slug: watermark, but for now we'll let the docs team facilitate keeping these pages off the docs site as they really should only be visible on beta-docs site for customer previews.
