### ISSUE TITLE
Most recent completed job from translation vendor not PR'd back to the repo

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2404]
Most recent completed job from translation vendor not PR'd back to the repo

### Acceptance Criteria 

- [x] troubleshoot workflow failure
- [ ] Validate this is re-occurring problem.
- [ ] fix workflow failure

**Comment by zstix** [comment]
I'm still working through the issue, but here are my findings so far:
* There are 5 batch job uuids saved in the "being translated" queue
* After adding some more logging ([`zstix/fix-translation-workflow`](https://github.com/newrelic/docs-website/compare/zstix/fix-translation-workflow?expand=1)) it looks like _none_ of those batches are found for the job

I _think_ I'm using the right project ID (and the associated credentials). We may need to manually add the complete-but-not-PR'd uuids to our queue and manually trigger the workflow.

I'm going to pick this up next week when I have another engineer to look over my shoulder.
