### ISSUE TITLE
[Gatsy Cloud] Shutdown Docs Site on Amplify: ETA Aug

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2406]
After we fully migrate this site to Gatsby and the feature to allow build previews to be created by forked PRS is available we can shut down our instance of this site on Amplify 

### Acceptance Criteria 

- [x] confirm the fork PR feature is available from Gatsby 
- [x] Shutdown site on Amplify
- [x] Remove Amplify webhook & integration
- [x] Remove amplify.yml from repo

**Comment by aswanson-nr** [comment]
Removed from amplify
