### ISSUE TITLE
Output attribute definition JSON file from Gatsby that will be served from the site

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#241]
## Description

In order to pull data into the data dictionary service, we need a way to serve it from the Gatsby site. We will need to output a JSON file that will be served as a static file. This will use the data sourced from the event/attribute definitions from #250 

## Acceptance criteria

* [ ] Output the JSON file during build
* [ ] Can fetch data from the endpoint

**Comment by roadlittledawn** [comment]
Initial work for this up in https://github.com/newrelic/docs-website/tree/clinton/attribute-def-json

Relies on final .md file structure when attribute defs are migrated via #250
