### ISSUE TITLE
Can't install mssql-server-integration-installer because of language problems

### ISSUE THREAD

**Issue by antoniodesenvolvedor** [newrelic/docs-website#2412]
While installing the new relic to monitor my sql server instance I got the following error.

'''
$output = sqlcmd -S "127.0.0.1,1433" -U my_user -P "my_pass" -Q "SELECT GETDATE()"; if ( -not ($output -like "*rows
affected*") ) { Write-Error "Cannot connect to the SQL Server instance 127.0.0.1 with the provided username sa and
password."; Exit 2; } : Cannot connect to the SQL Server instance 127.0.0.1 with the provided username sa and password.
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException

==> Installing mssql-server-integration-installer...failed.

'''

I figured out that the problem is the  connectivity check logic in  
"not ($output -like "*rows affected*")"

My SqlServer Instance does not output the message in english "rows affected", so this test always fails for me,

Example of the message in portuguese
"(1 linha afetada)"

You could change the logic to check for the number "1", this way the installation process of the mssql-server-integration-installer
would be more portable across languages.

Thank you.

**Comment by rhetoric101** [comment]
@antoniodesenvolvedor, thanks for your suggestion. I mentioned this to our engineering team and will see what they say.

**Comment by rhetoric101** [comment]
@antoniodesenvolvedor, our engineering team considered this a bug, and created an internal issue to track the work (VIRTUOSO-951).

**Comment by Julien4218** [comment]
A fix is now deployed
