### ISSUE TITLE
Issue: View our UI in dark mode

### ISSUE THREAD

**Issue by SKrPl** [newrelic/docs-website#2418]
### Tell us what you need

* If you've found something inaccurate, what is it?
  * The suggested way to change theme is not accurate. There is no `Theme` option in Account drop-down.

* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.
  * Just want to change to dark theme.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).
![Screenshot from 2021-05-24 19-39-26](https://user-images.githubusercontent.com/12163892/119360249-0ba86b00-bcc8-11eb-8d9f-21fc5c166fd3.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/view-our-ui-dark-mode/
* **OS**: Ubuntu
* **Browser**: Firefox 88.0
* **Device**: Dell XPS 15

**Comment by mmfred** [comment]
Hi @SKrPl - thank you for dropping us an issue. We appreciate your feedback. It looks like you are using Firefox, which is not supported for dark mode. I'm sorry I can't give you an idea when it will be supported. 

Best,
the docs team
