### ISSUE TITLE
Docs site search exits if Return is hit quickly

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#2421]
### Description

In Chrome and Safari, when I use docs site search, if I type search and hit Return quickly, before the search results appear, it just exits search and doesn't do anything. 

### Steps to reproduce

1. Go to docs site, start typing string in search field. 
2. Hit return. 
3. Will exit back to current doc instead of doing anything. 

### Expected behavior

Would expect it to maybe bring you to a page of search results, like it used to, if it can't auto-load the first result yet.

**Comment by jpvajda** [comment]
@zuluecho9 is there anyway you can upload a quick video or screen cast of what you are seeing? I couldn't reproduce this per the steps to repro.. 🤔

**Comment by jpvajda** [comment]
closing as there is no additional info showing this issue in action and i can't reproduce
