### ISSUE TITLE
Create a UI for attribute definitions

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#243]
## Description

We will be rebuilding the UI for the data dictionary. As of now, we have individual pages for each attribute/event. This is changing with the new site by creating a single page with the event/attribute definitions. We will allow users to filter and link to specific events/attributes.

### Right rail treatment (on desktop)

NOTE: Let's pair on this, as I think we need to make it clear at a glance when a filter is active (and which fields), but showing the number of results under the apply/clear buttons is redundant and we can do better.

![82ADA701-4CF3-4DA6-A290-30F5845C7834_1_105_c](https://user-images.githubusercontent.com/186715/99600365-249b3100-29b2-11eb-8f76-f686102b30fc.jpeg)

### Inline treatment (on mobile)

![IMG_0369](https://user-images.githubusercontent.com/186715/99600612-a68b5a00-29b2-11eb-990c-6376757b4a6f.jpg)

## Helpful links

* [Current UI](https://docs.newrelic.com/attribute-dictionary)

**Comment by jpvajda** [comment]
the MMF7 doc has all  the details for how the UI needs to work for the Data Dictionary, @roadlittledawn , @djsauble and @austin-schaefer and I jammed on it today, so this work can be detailed out with more specificity for whomever picks this issue up.

**Comment by jerelmiller** [comment]
@djsauble would you mind posting the wireframes/mocks you've been working on in this issue?

**Comment by djsauble** [comment]
@jerelmiller Done
