### ISSUE TITLE
Make taxonomy-redirects.json less fagile

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#2445]
Over the past few weeks, the [taxonomy-redirects.json](https://github.com/newrelic/docs-website/blob/develop/src/data/taxonomy-redirects.json) file has been a constant pain point for the docs team. It seems that we regularly run into either broken redirects, faulty redirects, or general fragility. 

I'm not entirely sure what the solution would be, but I am creating this issue to gather possible solutions. Maybe something along the lines of a script we can run that validates all the paths and redirects?

### Acceptance criteria
- A tool or automated script that the docs or DevEn team can use to validate the contents of `taxonomy-redirects.json`
OR
- An automated check that fails on PRs with broken content in `taxonomy-redirects.json`
OR
- Any other solution that makes the file less fragile.

**Comment by austin-schaefer** [comment]
@bradleycamacho : I know #2241 was an example. Are there other recent examples we can link?

**Comment by bradleycamacho** [comment]
I know @rhetoric101 ran into a myriad of issues with the file while working on #2213 and related PRs.

**Comment by bradleycamacho** [comment]
Another instance: https://github.com/newrelic/docs-website/pull/2441

**Comment by bradleycamacho** [comment]
Someone opened an issue for a bug I assume stems from this file too: https://github.com/newrelic/docs-website/issues/2449

**Comment by bradleycamacho** [comment]
> @bradleycamacho : I know #2241 was an example. Are there other recent examples we can link?

@austin-schaefer I assume you meant #2441

**Comment by roadlittledawn** [comment]
with redirects on our brains today, was curious if we want to augment / try performing an auto search based on URL path segment if it 404s.

over time redirects become hard to manually maintain / less relevant. and as we add other languages, we add same amount of redirects we have for English pages to all locale namespace pages (which has performance / build implications)

example: 
a user requests `/docs/alerts/new-relic-alerts/notifications`. 

a 404 page is displayed saying we can't find that page, but we could suggest a handful of results for pages via a swiftype query for: [`alerts new-relic-alerts notifications`](https://docs.newrelic.com/?q=alerts+new-relic-alerts+notifications).

we could possibly apply result rankings for certain search terms, or look for specific types of content (troubleshooting, index pages, basic docs, etc).

**Comment by bradleycamacho** [comment]
@roadlittledawn That seems like a great idea!

**Comment by roadlittledawn** [comment]
there are much less fragile now that they are gone ;)
