### ISSUE TITLE
Call out REST API limitation with regards to Browser Lite agent

### ISSUE THREAD

**Issue by masenmatthews** [newrelic/docs-website#2456]
### Tell us what you need

The REST API only really works with the Browser Lite agent. In other words, it'll use the Lite agent when a Browser app is created via API. It would be helpful to have this called out in the docs since it has driven support tickets. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/rest-api-v2/browser-examples-v2/add-or-list-browser-apps-api-v2/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
After our conversation, I created PR #2646 to address this limitation and I'm closing the issue.

Thanks again for your contribution!
