### ISSUE TITLE
Error in format for forwarding syslog to TCP endpoint?

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#2458]
### Tell us what you need

A user filed this feedback in the product:

> Docs for forwarding syslog to the tcp endpoint seem to specify a format that is not correctly parsed by New Relic.
Hostnames, process names etc are missing. The examples should show the correct format

I've reached out to the user see if they want to provide any additional information, but either way I think we can work with the logs folks to see if there's a possible error in here.

### Anything else you'd like to share?

Related customer feedback: CF-6423

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/log-management/log-api/use-tcp-endpoint-forward-logs-new-relic/
* **OS**: Mac OS 10.15.7
* **Browser**: Edge 90.0.818.66
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
Emailed the user to ask for clarification on two points:

* Was this specific doc the source of their issue?
* Do they know which step specifically was not working for them?

**Comment by x8a** [comment]
We're closing the issue because we'd need more context to proceed with finding a solution. In case we get more information about the issue, we'll reopen it.
