### ISSUE TITLE
Document how to use the video component and embed videos in callouts 

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#246]
### Is your feature request related to a problem? Please describe

Occasionally we need to embed videos in the docs. We need a process for adding (like through a component).

### Describe the solution you'd like

I believe this got figured out for the developer site, and that solution might be useful for the docs site. We'd also like to be able to add videos to "tip" callouts. And we'd like a good way to highlight videos from NRU.  These might be three different things.

### Describe why this important to you

There's lots of evidence that some users prefer videos. Plus, we can use NRU content (when it's available) rather than creating new similar content.

**Comment by tariqahmed** [comment]
Video component already there.
Tip component supports video.
We believe this is mostly done.

**Comment by tariqahmed** [comment]
Update documentation on how to embed videos and leverage tips.

**Comment by jpvajda** [comment]
@mmfred  you can use video components on the docs site today and nest videos within callout components, (tips) let you can on the dev site, you can also reference youtube or wistia videos as a prop. 

Here are some references on how those work, and perhaps this is more of a how to, vs a new feature. Let me know if this helps, or if you see missing documentation on the Docs site we should add to our contributor guide.

https://github.com/newrelic/developer-website/blob/develop/COMPONENT_GUIDE.md#video

https://github.com/newrelic/developer-website/blob/develop/COMPONENT_GUIDE.md#usage-5

**Comment by roadlittledawn** [comment]
The Video component was moved to theme in a previous MMF and we have [doc there on how to use it](https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#video).

Ditto to [doc on Callout](https://github.com/newrelic/gatsby-theme-newrelic/tree/develop/packages/gatsby-theme-newrelic#callout). Callout component should render whatever is inside it, including other components like Video.
