### ISSUE TITLE
404 URL not found

### ISSUE THREAD

**Issue by Praveen787** [newrelic/docs-website#2470]
### Tell us what you need

https://docs.newrelic.com/php-agent-installation-redhat-and-centos/
 URL is not available , getting 404 page not found

### Anything else you'd like to share?

URL found on this page "https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-tar-file/"
 click on hyperlink "RPM Page" in the second line

### Doc information (don't delete this section)

* https://docs.newrelic.com/php-agent-installation-redhat-and-centos/
* **OS**: Windows 10
* **Browser**: Chrome 90.0.4430.212
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@Praveen787, thanks for telling us about this 404! We'll look into it!

**Comment by Praveen787** [comment]
same is for "Debian package" hyperlink on "https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-tar-file/"

**Comment by rhetoric101** [comment]
@Praveen787, it took us a while to get to this, but these two broken links should be fixed in PR #2501. Thanks again for your help!
