### ISSUE TITLE
[DDS] Sync attribute definitions from the docs site to the service

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#248]
## Description

Once we have a service up and running, connected to the database, we need a way to sync the definitions from the docs site to the data dictionary service. The service will read in the event/attribute definitions and add/update the database records with the data.

**Comment by zstix** [comment]
## Remaining Work
* [ ] Save attributes to the database
* [ ] Save units to the database
* [ ] Expose an endpoint that we can ping
* [ ] Set up the endpoint with a shared secret (vault via grandcentral)
* [ ] Amplify webhook (when a deploy has finished) _or_ GH Action in docs repo (on a regular interval)
