### ISSUE TITLE
Issue: Troubleshoot Metric API with NRIntegrationError events

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#2497]
### Tell us what you need

* The customers are seeing error messages to specific `RateLimit` types and there is no documentation about the different kinds of limits.
* Please let me know if there is any page (sorry if there is) 
  * Also would be great to include links to it

* The message shown is *You have exceeded your daily error group limit. Incoming error groups will be dropped for the remainder of the day and will continue as normal after UTC midnight*

### Anything else you'd like to share?

<img width="1340" alt="Screenshot 2021-05-27 at 12 14 03" src="https://user-images.githubusercontent.com/80056193/119816857-20157f00-bee5-11eb-81ae-215fc91918b4.png">

The above is one result from the query `FROM NrIntegrationError SELECT * since this month where category = 'RateLimit'`

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/ingest-apis/troubleshoot-nrintegrationerror-events/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 90.0.4430.212
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for bringing this to our attention, @rodrigo-corgozinho! I'll have a look.

**Comment by x8a** [comment]
Hi, @rodrigo-corgozinho! Currently, the error inbox functionality is limited to 75k unique error groups per day. However, this will be improved, so expect an announcement in the upcoming weeks.
I'll close the issue since the documentation will be updated together with the announcement. Thanks again!
