### ISSUE TITLE
Documentaiton linking to wrong places

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#2498]
### Tell us what you need
The headline links on this page dont go to the right places:

- Introduction to New Relic APIs
- A developer-centric look at our APIs

The first goes to an intro to NRQL rather than API's (im not sure where it should go as the nav takes you to an empty page https://docs.newrelic.com/docs/apis/intro-apis/)

The second ends up on a generic landing page.

Additionaly the first large panel "Introduction to API's" also takes you incorrectly to an intro to NRQL too.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @jsbnr! I fixed the links in this PR #2499. Thanks a lot!
