### ISSUE TITLE
Create redirects for old attribute definition pages to new UI

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#251]
## Description

As part of this migration, we are consolidating event/attribute definitions into a single page. This means that we need to route the old attribute definition URLs to their new, filtered location.

We should be able to source the data created from #250 to use as the base for these definitions.

## Helpful links

* [Sample legacy attribute definition page](https://docs.newrelic.com/attribute-dictionary/transaction/appname)
* #250  
* #243

**Comment by zstix** [comment]
We will want to do something similar to [the developer site](https://github.com/newrelic/developer-website/blob/develop/gatsby-node.js#L52-L61) except rather than pulling from the frontmatter, it will pull from the GraphQL query to generate the URLs.

**Comment by jerelmiller** [comment]
Here is a query that should help pull all event/attribute definitions!

```
query {
  allDataDictionaryEvent {
    edges {
      node {
        name
        childrenDataDictionaryAttribute {
          name
        }
      }
    }
  }
}
```
