### ISSUE TITLE
OpenTelemetry (OTEL) Integration and Documentation for Gatsby Build

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#2534]
There has been some OpenTelemetry work done for tracing Gatsby Build processes in order to send that trace data to New Relic for Observability. This work is to further enhance the Integration to make it easier to use, and to document the process for both internal and external use.

Sites
- [x] Decide where the telemetry files should live (the theme may be the most convenient)
     - `otel-config.yml`
     - `jaeger-local.js`
- [x] Create `observability pack` for Gatsby Build
- [x] Create an `Entity Type` for Gatsby Build (WIP: EIS-149 should allow us to do this)

Documentation

- [x] NerdLife Blog detailing the implementation
- [x] Potentially adapt for a Public Blog (so that other Gatsby users can easily adapt and send data to NR)

**Comment by jpvajda** [comment]
Is there a particular sprint we are committing to having this work done @rudouglas ?

**Comment by rudouglas** [comment]
Not currently no, but the Plugin is nearly finished, then just needs some testing.

For the blog post stuff I think the plan is to hold off on that and coordinate with Daniel et al to coincide with their launch, i'll get more concrete dates and such

**Comment by rudouglas** [comment]
Actually @jpvajda, this is now 2 separate projects. The original one used the OTLP Docker container to send spans, the work on that is complete so I can move ahead with the blog post (internally at least) and then decide if it's worth publicly documenting both, i think it is personally as there are pro's and cons to each

**Comment by jpvajda** [comment]
@rudouglas Let's parking lot this topic today, I have some questions.

**Comment by rudouglas** [comment]
Here is the **_!Internal_** [Blog Post](https://nerdlife.datanerd.us/new-relic/see-gatsby-shine-at-the-overlook-otel-06c3fd38-7752-4866-a4b1-1f5e2823a93b)

**Comment by jpvajda** [comment]
@rudouglas this is amazing, i'm going to share this with some folks to spread the word also  removed the direct link to nerdlife 😉
