### ISSUE TITLE
Troubleshooting Guides Nav and Landing Page

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#2535]
### Is your feature request related to a problem? Please describe

Troubleshooting docs are often difficult to find from the main landing page of the Docs site. At best they require multiple clicks from the user to surface, and often prior knowledge of the navigation path to a section of the Docs to find related Troubleshooting info.

### Describe the solution you'd like

A section similar to Release Notes would be great, so that a customer can quickly find exactly what they are looking for. This would include a Link in the left-hand navigation as well as a Troubleshooting Landing Page, see screenshots for examples.

### Describe why this important to you

I think this would create a better user experience, and also potentially deflect Support tickets from frustrated users who can't easily find the troubleshooting help they're looking for

### Additional context

![Screenshot 01-06-2021 15-40-51](https://user-images.githubusercontent.com/17122543/120343387-943e9100-c2f0-11eb-93f7-09c8fb73ec48.png)
![Screenshot 01-06-2021 15-50-22](https://user-images.githubusercontent.com/17122543/120344035-1e86f500-c2f1-11eb-93d1-90f5693d8872.png)

**Comment by roadlittledawn** [comment]
To tack on to this. We _could_ add a filter in the global search for records with `document_type` of `troubleshooting`. We used to have a filter for types of docs in the old search (and it was an often requested feature for Support peoples like you mentioned)
