### ISSUE TITLE
[Machine Translation] Create project_id column in Test Postgres tables

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#2538]
## Background

><!> This should all be done in the testing database environment. Once this is working together with the updated scripts, we have a separate ticket to actually create those changes in the production database.

Follow the instructions in the [Readme](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/translation_workflow/testing/README.md) to set up your testing environment. This sets up local docker containers for a Postgres Database and PGAdmin instance to manipulate the DB.

><!> Please use the https://github.com/newrelic/docs-website/tree/feature/machine-translation feature branch

In order to reduce code duplication and effort, we will be adding a new column called `project_id` to a couple of existing tables. This is so we don't need separate tables for each type of translation, and can re-use the same scripts with a little tweaking. 

### Edit Tables
Adding `project_id` to the following tables is necessary for us to know whether a page needs to be sent to **Machine** or **Human** translation project in Smartling, and also identify how it's been translated when we download it.

 - `translations`
 - `jobs`

We can do that in the PGAdmin console via the `Query Tool`:
<details>
  <summary>⚠️ SPOILER - Click to see image!</summary>
  <img width="818" alt="Screenshot 2021-11-05 at 10 44 39" src="https://user-images.githubusercontent.com/17122543/140509735-115e5150-0e43-4ac1-82f3-f091cae49479.png">
</details>

<details>
  <summary>⚠️ SPOILER - Click to see SQL Code!</summary>

  ```sql
ALTER TABLE IF EXISTS public.jobs
    ADD COLUMN project_id TEXT;
	
ALTER TABLE IF EXISTS public.translations
    ADD COLUMN project_id TEXT;
```
</details>

### Edit Models
We will also need to alter the Models files for both [jobs.js](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/translation_workflow/models/job.js) and [translations.js](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/translation_workflow/models/translation.js) to make sure they reflect the new table structure:

<details>
  <summary>⚠️ SPOILER - Click to see Code!</summary>

```js
project_id: {
  type: DataTypes.INTEGER,
  allowNull: false,
  references: {
     model: Projects(sequelize, DataTypes),
     key: 'projects',
     deferrable: Deferrable.INITIALLY_IMMEDIATE,
  },
},
```
</details>

### Edit Test Creation Code
We will also want to alter the query code for the testing docker container in [creation_and_cleanup.sql](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/translation_workflow/testing/creation_and_cleanup.sql), adding the following to the `CREATE TABLE translations()` and `CREATE TABLE jobs()` functions:
<details>
  <summary>⚠️ SPOILER - Click to see Code!</summary>

 - `project_id TEXT`

</details>

### Testing Existing Scripts
🛑   You can use the MT Project ID for this but only test with a 1 word change, [see here](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/translation_workflow/testing/README.md#make-a-change-to-translate)

The reason for this is we have a `2 million` word limit per year specifically for Machine Translation

>Average is about 850 words per document. total is about 1.6 million. For MT it’s a total of 2 million words can be translated over a year. we have approximately 1800 pages x 850 (avg word count per page) = 1.6 million

## Acceptance Criteria

`note:` All Deven team members should be given access to AWS. - @zstix 

- [x] Created new columns in the tables of the test environment
- [x] Edit the model files
- [x] Edit the test Creation Code
- [x] Test the current scripts do not break anything in the testing environment

#### Useful Links
 - [Current database schema](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/translation_workflow/database.js)
 - [AWS RDS Database](https://us-east-2.console.aws.amazon.com/rds/home?region=us-east-2#database:id=translations;is-cluster=false)
 - [Database Repo](https://source.datanerd.us/developer-enablement/translation_database) - the physical resources in AWS are terraformed, the database schema is manumatic. so if we a new table, or have to add a new field, need to expand the current script for that.

**Comment by jpvajda** [comment]
@rudouglas will work on AC...

**Comment by nr-kkenney** [comment]
`project_id` column should be string. i dont know for sure that the vendor uses non-integer ids, but string is a more flexible / forgiving type just in case.

**Comment by nr-kkenney** [comment]
@rudouglas that is what i meant 🙈

**Comment by rudouglas** [comment]
ah cool that makes sense 🍾
