### ISSUE TITLE
[Machine Translation] Create new project & workflow in Smartling

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#2540]
### Background
We will want to create a new project in Smartling with a machine translation workflow, as this will likely be easier to work with than a dynamic workflow. We simply point our scripts to use this project when doing machine translations using an environment variable ([current implementation](https://github.com/newrelic/docs-website/blob/9928611a1f14971062f1ed1ad6337a593dabf225/scripts/actions/send-and-update-translation-queue.js#L14)), and that should be the only change needed in our interaction with Smartling.

### Acceptance Criteria

- [x] Notify Julian we are creating a new project for this OR use this existing one : `New Relic - Tech docs MT production`
- [x] ~~If we need to create a new project & workflow for machine translation in Smartling pair with Julien on that~~

### Useful links
* [machine translation in Smartling](https://help.smartling.com/hc/en-us/articles/360051564054-Machine-Translation-MT-Profiles#h_01F2P6D14XDK8GHR99M1AMWW4Z)

Relates to: #2341

**Comment by jpvajda** [comment]
I followed up with @jmiraNR on this question

**Comment by jpvajda** [comment]
we can use this existing project, the only concern @jmiraNR was how we actually go about testing this, we don't want to send the entire site over in our test as we have limits to consider. 

- 2M words: docs estimate (main article) at 1.6M
=-Maintenance for the 4 months post luanch might eat the 400k words left

For a round trip test,  we can send 10 docs and pretend that they are 1500. That is totally safe.

**Comment by jmiraNR** [comment]
I said 10, but if it can be 5 or even 2 or 1, that's even better. ;)
