### ISSUE TITLE
Issue: Ruby agent configuration order of precedence 

### ISSUE THREAD

**Issue by linbaker** [newrelic/docs-website#2546]
### Tell us what you need

Add warning that `NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERRORS` does not follow order of precedence and Server Side Configuration does have the ability to over write this setting when configured locally. 

---

Currently, the configuration for ignoring errors does not follow the order of precedence that all other configuration settings do and that is documented:

https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/#error_collector-ignore_errors

Server Side Configuration takes precedence for this setting over all environment configuration. This goes against the documented order of precedence and all other configuration settings for the Ruby agent where env. vars take precedence over all other configuration. 

Ruby agent team is already aware of this issue:

* https://newrelic.atlassian.net/browse/GTSE-9328

And this will likely be corrected when this feature is added:

* https://github.com/newrelic/newrelic-ruby-agent/issues/454

Until then, and for those who will be running older versions of the agent, we need a warning in our documentation for this. 

Thank you! If you have any questions, I am available in #gts-ruby or our engineering team is aware of this issue as well in #ruby-agent !

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/ruby-agent/configuration/ruby-agent-configuration/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 90.0.4430.212
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
@linbaker Thanks for opening this issue! I've opened a PR that adds a warning for this config: #2551.
