### ISSUE TITLE
Issue: Introduction to .NET custom instrumentation

### ISSUE THREAD

**Issue by acrigney** [newrelic/docs-website#2559]
We need to log access to sensitive data in our applications. NR and DataDog are by default instrumenting all api calls but I only really need to instrument the api calls that access this sensitive data fields in our applications.
So maybe I need to build a custom .net attrbute that can load up the sensitive fields included in each function call. So this would mean just inheriting from your base Transaction attribute. However NR logging is only going to show that a application method has been called, not that an application method was called and these are the fields of objects or parameters passed.
Maybe I would need to build a plugin for your GUI logging?

**Comment by x8a** [comment]
Hey, @acrigney! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
