### ISSUE TITLE
Issue: NRQL syntax, clauses, and functions

### ISSUE THREAD

**Issue by naxhh** [newrelic/docs-website#2561]
### Tell us what you need

Reading abobut `UNTIL` i found that the anchor in the link to "relative time range" doesn't exist anymore.
https://docs.newrelic.com/docs/insights/new-relic-insights/managing-dashboards-data/set-time-range-insights-dashboards-widgets/#relative-range

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for the feedback, @naxhh! I fixed the content and links in PR #2562.
