### ISSUE TITLE
Issue: Pass command line options for nrdiag . Document all option values available

### ISSUE THREAD

**Issue by adiosspandit** [newrelic/docs-website#2565]
### Tell us what you need

* Options are not listed in command help
* It will be good to have options available listed in the doc 
* e.g. --suites says run this to see all options. If options are documented we can directly tell the customer what commands to run. Instead of setting up the utility and then finding out what options are available

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.77
* **Device**: Unknown

**Comment by mmfred** [comment]
@adiosspandit - Thanks very much for reporting this need. I've created a JIRA ticket and placed the request in our backlog: https://newrelic.atlassian.net/browse/DOC-6983?filter=-2 Feel free to comment there.

**Comment by bradleycamacho** [comment]
@mmfred @barbnewrelic I got a bit lost at the status of this issue and the corresponding jira. Could one of you two provide a status update?  (@barbnewrelic I'm tagging you since I see your face on the Jira)

**Comment by barbnewrelic** [comment]
The corresponding Jira was finished in July 2021. DOC-6983
