### ISSUE TITLE
Issue: Ruby attribute examples

### ISSUE THREAD

**Issue by bob-bins** [newrelic/docs-website#2567]
Some of the [examples](https://docs.newrelic.com/docs/agents/ruby-agent/attributes/ruby-attribute-examples/#ex_select_dest) are invalid yaml:

```
attributes.enabled: true
  transaction_tracer.attributes.enabled: false
  attributes.exclude: foo
```

```
transaction_tracer: none
  error_collector: bar
  transaction_events: bar
  browser_monitoring: none
```

Should these be without the indentation? Also where should this configuration be placed within the `newrelic.yml` file? Within `common` or at the top-level not as a nested property? If the latter, what if we want environment-specific settings, e.g.

```
# newrelic.yml

common: &default_settings
  ...

development:
  <<: *default_settings

production:
  <<: *default_settings
```

**Comment by mmfred** [comment]
@bob-bins - thanks for your question and for pointing out this problem. We are looking into a fix. If you need a quick reply, you might also try discuss.newrelic.com, where employees and customers might be able to more quickly provide an answer.

**Comment by amhuntsman** [comment]
@bob-bins I just took a quick look at the docs in question. It looks more like those examples aren’t meant to be YAML, but just showing what the output will be when given certain inputs and config settings. Glancing at examples from other language agents, these might have been copied over and made to look vaguely like their proper config formats, which could lead to confusion.

If it *is* meant to be proper YAML, then you're correct that the indentation should be removed. As for where it belongs in `newrelic.yml`, that would depend on the application, but settings should appear in either the `common` or one of the environment-specific sections, not at the top level.

**Comment by bob-bins** [comment]
It seems at least the `Configurations` snippets are meant to be yaml. One of them is even preceded with ` The following configuration will accomplish that:`, followed by a configuration that would be valid under the top-level `common` parameter. If that doesn't mean "here is a configuration you can add to your newrelic.yml file" then I have no idea what it means but regardless it should probably be changed to something with a non-ambiguous interpretation.

**Comment by mmfred** [comment]
I created a work item for the team to update the Ruby code in this page: DOC-6992
