### ISSUE TITLE
Issue: NRQL math using SELECT

### ISSUE THREAD

**Issue by j4zzcat** [newrelic/docs-website#2569]
Hello, I'm trying to run the following:
```
SELECT 1/custom.total/200 as hwr, custom.warmup * hwr FROM SyntheticCheck WHERE monitorName = 'Monitor Blahblah' since 24 hours ago 
```
But results come empty.

**Comment by mmfred** [comment]
Hi @j4zzcat - thank you for reaching out. Can you link me to the docs page where you found this query?

Looking at it, my first thought is that a real monitor name needs to be substituted in for `Monitor BlahBlah`, but I'd need to see the context. 

If you didn't find this query in docs.newrelic.com, I recommend asking for help on https://discuss.newrelic.com/, where you can drop in a question and New Relic employees and customers will help you find an answer. 

Cheers,
Michelle (Docs Team)

**Comment by mmfred** [comment]
Closing, as we don't have enough info.
