### ISSUE TITLE
[Gatsby Cloud] Fastly limits apex domains to one account: ETA JULY

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2576]
[Fastly limits apex domains to one account](https://support.gatsbyjs.com/hc/en-us/articles/1500003204562-I-m-receiving-an-error-from-Fastly-so-how-do-I-resolve-that-). For example: Account 1 has foo.example.com and example.com. Account 2 attempts to use bar.example.com and is unable to do so. This is because Account 1 owns *.example.com.

Gatsby is working to resolve this for us to be able to move to Gatsby 

### How To Test

- Gatsby completed the work on removing the Fastly/apex domain limit and it is ready for testing. 
- Perhaps create a test subdomain like testdocs.newrelic.com? 
- Create a DNS record testdocs.newrelic.com to point to docswebsitedevelop.gatsbyjs.io

**Comment by jpvajda** [comment]
Estimated to resolved in late July  / Early Aug

**Comment by jpvajda** [comment]
I've reached to Gatsby for an update on resolution.

**Comment by jpvajda** [comment]
from Gatsby 

> Our engineering team is testing the Apex domain issue and they will provide me an answer as to when it will be resolved by the end of the week.  I’ll provide an update by then.

**Comment by aswanson-nr** [comment]
I can confirm that Gatsby Cloud now allows you to set the domain even if the Apex is used in another fastly account. I will test it with a DNS record next

**Comment by aswanson-nr** [comment]
@jpvajda I wanted to confirm if the DNS record test is needed. The original issue had Gatsby showing us an error when the apex domain was entered and now that has been resolved. I think we can mark this as resolved as-is, without setting up a new DNS entry.

**Comment by jpvajda** [comment]
@aswanson-nr agreed, that mentioned it as a way to test, but if you deem it unnecessary we can call this done.
