### ISSUE TITLE
Issue: Configuring your SSL certificates

### ISSUE THREAD

**Issue by newtob** [newrelic/docs-website#2592]
### Tell us what you need

* i've found something hard to understand and am uncertain what to do.

some YAML is needed 

With modern JVM agents some yaml is needed, here's what the doc currently states:

**Using YAML-based configuration**

```
common:  default_settings
  ca_bundle_path: /path/to/digicert.pem
  use_private_ssl: false
```

**Two questions**

1. Where should this yaml go? Or could it be passed as a command line switch -D?
2. should the ca_bundle_path have three references to the three pem files mentioned 

```
META-INF/certs/eu-newrelic-com.pem
  META-INF/certs/eu01-nr-data-net.pem
  META-INF/certs/newrelic-com.pem
```
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/java-agent/configuration/configuring-your-ssl-certificates/
* **OS**: Windows
* **Browser**: Chrome
* **Device**: Unknown

**Comment by x8a** [comment]
hey, @newtob! I'll have a look at this and let you know.

**Comment by newtob** [comment]
Thanks Olveros,
Your response is so fast, I was expecting months not minutes!

I feel guilty now, as I got some extra pressure from my users and opened a
support ticket because if it:
#459236.

There are two applications in the bank, Deutsche Bank, who are stuck with
the same problem. I'm getting hit by both of them daily.

Many thanks for your support,

Ben

**Comment by x8a** [comment]
This is actually the Documentation repository, so support may have a faster solution than us. In the meantime, you can check the [Explorers Hub](https://discuss.newrelic.com/) to see if someone else had a problem similar to yours and whether they already found a solution. It's a community for New Relic users and experts to connect and help one another.

I'm trying to get some answers for you, but feel free to close the issue if support gives you an answer. In case you think we could improve the doc, you can edit it. [Here](https://docs.newrelic.com/docs/style-guide/writing-guidelines/create-edit-content/#edit-doc) you can read how.

Thanks!

**Comment by x8a** [comment]
Hi, @newtob! Regarding your questions:

1. Where should this yaml go? Or could it be passed as a command line switch -D?
- By default, the java agent expects the YAML file in the same directory as the newrelic agent jar. You can read further details under [Startup configuration](https://docs.newrelic.com/docs/agents/java-agent/getting-started/introduction-new-relic-java/#h2-startup). However, you can also change the file location with a system property. Read how to do it in [Java agent configuration: Config file](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file/).

2. Should the `ca_bundle_path` have three references to the three PEM files mentioned?
- The three PEM files are built into the Java agent for versions 6.2.0 - 6.4.2. Therefore, you should not need to specify a `ca_bundle_path`.
If you are using a different agent version, you might need to specify a `ca_bundle_path`, then it would be to your own certificate bundle, which should be only one file. You can put several PEM files into a bundle file, which is then referenced in the `ca_bundle_path`.
To learn how to provide SSL certificates depending on your Java agent version, see [Notice of expired SSL certificates and certificate removal](https://docs.newrelic.com/docs/agents/java-agent/configuration/configuring-your-ssl-certificates/#notice-of-expired-ssl-certificates-and-certificate-removal).

Let me know whether this helps 🙌🏻

Thanks!

**Comment by x8a** [comment]
Hi, @newtob! I'll close the issue at the end of the week if you don't need further assistance. Thank you!
