### ISSUE TITLE
Translation workflow is submitting english strings: ETA 6/15/21

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#2597]
The translation workflow is submitting english strings that replace previously translated Japanese. You can see this in the merged PR https://github.com/newrelic/docs-website/pull/2272 (check out line 32 of the first diff)
[live example](https://docs.newrelic.com/jp/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing/) These strings don't appear to come from the vendors translations

### Acceptance Criteria 

- [x] Do discovery work to assess the problem
- [x] Pause the [`send-content-to-translate.yml` workflow](https://github.com/newrelic/docs-website/actions/workflows/send-content-to-translate.yml) which is next scheduled to run on 6/15
- [x] Decide what to do with ongoing jobs in `Smartling` > `Tech Docs production` > `Jobs`
- [x] Once the ongoing jobs are all marked as completed, the affected files are PR'ed with fully translated content via the [`check-translations-and-deserialize.yml` workflow](https://github.com/newrelic/docs-website/actions/workflows/check-translations-and-deserialize.yml)

## Findings & Next steps

From Smartling's perspective, an HTML file is a bucket of strings. They save chunks of strings in translation memory and match on those chunks to apply the translation. If we upload a new version of the HTML file, it may not find matches for those strings, so it will mark them as needing translations and track their status individually. The source file contains all strings, whether they have a matched translation string or not.

If the same file was uploaded twice in two different jobs, and one job finishes first. We will download the source file and we will get English strings until the strings from the 2nd job have been applied / "published" to the file.

There doesn't seem to be a way to download the file and just get published / previously published strings if the file contains new, untranslated strings.

### Short term fix

To fix immediate issue where English strings are in translated files:
- Only mark job as complete if same file(s) in other jobs are also complete. The daily check should see those and submit PRs with the fully translated files.

### Longer term fix
https://github.com/newrelic/docs-website/issues/2655

**Comment by roadlittledawn** [comment]
note to self: i vaguely remember checking statuses of batches wasn't as straight forward as you'd think. and [this line](https://github.com/newrelic/docs-website/blob/e0e5d2c297a6717e0bb71b96d299b9410d18eaad/scripts/actions/check-job-progress.js#L55) looks like it may be only checking for `CANCELLED` status for each file. digging in now

**Comment by roadlittledawn** [comment]
looking at `check-job-progress.js` it seems like we check statuses as expected.

there's 3 statuses:
- a batch status
- a status for each file in a batch
- a job status that the batch is associated with

we go and fetch the batch of files if:
- the job status is marked as `COMPLETE`
- we filter out files from a batch if marked as `CANCELED`.

it looks like we do not check if the batch is  marked as `COMPLETED`. not sure if we need to. will check w/ Julien re: when those various statuses are set

**Comment by roadlittledawn** [comment]
i'm confused by the june 15 scheduled run. the workflow that checks the job status in smartling and fetches content is still running every day. https://github.com/newrelic/docs-website/actions/workflows/check-translations-and-deserialize.yml

**Comment by roadlittledawn** [comment]
when looking at one file in the [linked PR diff above](https://github.com/newrelic/docs-website/pull/2272/files#diff-5766dc21a92a839e02b8209a702a7389517c6e4335fe8772c68c34fc8ed92218), it looks to be a file that's been included in several jobs recently. (i can't determine which job is associated with the PR because i don't think we have a way to correlate a job ID with a PR). whenever the job completed we grab the current version of a given HTML doc in Smartling which apparently still had English characters because subsequent jobs contained strings that were not yet "authorized" to be translated.

since this file is included in multiple jobs, i'd expect the all the English text to be translated once all those jobs are completed. i'm not sure there's a way to get only the HTML for a given job, but i _think_ that's what may be causing this.

file: `src/i18n/content/jp/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing.mdx`

![2021-06-09_15-48-25](https://user-images.githubusercontent.com/2952843/121439300-8c0ed300-c93a-11eb-97b7-178f9df6464d.png)

**Comment by roadlittledawn** [comment]
just spoke w/ @jmiraNR . the plan is:
- Julien is going to chat w/Smartling to confirm our findings/understanding is correct
  - we can't download only translated strings for a file, just whatever strings are currently published/unpublished which may include english strings if the file was uploaded in a subsequent job)
- Julien is going to ensure the remaining jobs are completed, and when they are he'll let our team know in the #help_deven-websites
- Our team will watch the next workflow run for `check-translations-and-deserialize.yml` that checks job statuses and downloads / PRs the repo with the files from the job file batches to make sure we don't have english strings in them.

**Comment by jpvajda** [comment]
We discussed delaying this until Sprint 8, as the translation jobs are still in queue..

**Comment by zstix** [comment]
Here's the PR for the latest content from our translation vendor: https://github.com/newrelic/docs-website/pull/2766

Unfortunately, there are some english strings in the PR. We'll need to dig into this further.
