### ISSUE TITLE
Customer feedback: Agent overhead and performance impact

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#2600]
### How can we make our docs better?

* A user reached out asking for docs on the resource usage of the agents
* We have this [docced for infrastructure](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/manage-your-agent/infrastructure-agent-performance-overhead/) but not other agents
* I've reached out to clarify which agent they're interested in, but regardless we should reach out to agent teams about how we can provide more info about this across all our agents

### Anything else you'd like to share?

The Jira for the relevant customer feedback is CF-6623

**Comment by barbnewrelic** [comment]
Contacted Austin S. via slack to find out whether to create a DOC Jira so this can get into Tech Docs team queue, or how to handle non-DOC Jiras when the scope looks much larger than a simple hero fix. Moving this to "Waiting on SME/Blocked" while confirming next steps.

**Comment by austin-schaefer** [comment]
Assigning this to myself; I'll reach out to the agent teams this week to get a conversation rolling.

**Comment by austin-schaefer** [comment]
Talked to a number of agent experts about this (more info internally in CF-6623), and the gist is that documenting this is unfortunately harder than it seems.

Across the board, we strive for low resource usage across all agents. The actual performance impact, though, is really dependent on the specifics of the customer environment. Things like which framework someone is using, the type of workload their app is running, and what system it's running on can change usage. 

If someone does run into abnormal or excessive resource usage, though, we definitely encourage them to contact New Relic support! This is the kind of thing our agent teams want to know about and troubleshoot.
