### ISSUE TITLE
An older version of a translated doc shouldn't be able to overwrite a new version of a translation doc

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2603]
We seem to have cases where an older version of a translated doc is able to overwrite a new version of a translation doc 
we want to determine why this  occurring and we'll want to address this problem before expanding to new countries. 

### Acceptance Criteria 

- [x] Determine what the root cause of this issue may be
- [x] identify a solution(s)
- [x] Review solution(s) with team and potentially @jmiraNR for feedback.

**Comment by jpvajda** [comment]
since this work relates to #2597  I'm going to mark as blocked until we determine the resolution on that issue.

**Comment by jpvajda** [comment]
We discussed delaying this until Sprint 8, as the translation jobs are still in queue..

**Comment by nr-kkenney** [comment]
this should now be resolved with the merge of #3347
