### ISSUE TITLE
Improve GitHub check names so that it's easier to understand what they execute

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#2613]
### Issue

On the Docs team, we're pretty mystified about what some of these GitHub build checks mean. When they fail, it's tough to know if that's important or not. I'd love to reduce some confusion on the Docs team so we can drive clarity around each Github check when working with the Gatsby Docs Site.

### Example 

For example, @nr-kkenney described "Gatsby Build Service - docs-website Gatsby Build Service" as "creates release notes". That's a lot more meaningful and understandable :)

### Acceptance Criteria

- [x] obtain help from @paperclypse  to help rewrite the GitHub check names so that anyone can read them and understand what they're doing.
- [x] Review new names with the DevEn Team
- [x] Implement name changes
- [x] Ensure checks still run as expected. 
- [x] Update documentation to reflect changes.
  - [x] update wiki
  - [x] update style guide, github troubleshooting

**Comment by jpvajda** [comment]
@paperclypse do you want to propose some naming convention improvements?

**Comment by jpvajda** [comment]
I'll take this one as I'm interesting in the naming convention we'll use and also I can make these changes as it's pretty simple to change.

**Comment by jpvajda** [comment]
@jpvajda will first define what each check is doing, then @paperclypse can provide some guidance on what we call them.

**Comment by jpvajda** [comment]
Would anyone want to take this ticket on? I was really interested in going through all these checks and consider the feedback from @paperclypse paperclipse, but I don't seem to have the time. 🕐    I have a fairly detailed  markdown file with all my notes from my talks with Shawn. I'm happy to share if anyone wants to grab this from me.
