### ISSUE TITLE
Speed up local Gatsby builds

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#2615]
### Slow local builds

When I switch between branches to work on different doc issues, the local site rebuild takes around 7 minutes before I can look at a preview. I have to find other tasks to do while this is happening, but I can't switch branches to other work: the other tasks are usually in other areas.

Let's say I switch between branches a minimum of 10 times per day. That is 70 minutes (over an hour) where I have to split my attention between the local builds and other tasks. This is not just time consuming, it also adds to mental overhead as I jump between tasks.

Here are the commands I run. Honestly, the first two don't take that much time:

```
yarn
yarn clean
yarn start
```

I confess that I sometimes get my system into a bad state by trying to switch between branches without stopping first. This often works and saves time, but when it fails, I often have to run a series of trial-and-error fixes to get it running again. Of course, these additional clean-up commands also take additional time:

rm -rf .cache
rm -rf node_modules

### Describe the solution you'd like

Are there any shortcuts you can find to speed up this local build process? If you could get this down to a few minutes, that would help a lot.

If we can't find any way to speed up the builds, how about helping us set up a Slack notification to let us know when it's ready?

### Describe why this important to you

Jumping back and forth between tasks to check on builds seems like unnecessary toil, and I'd rather keep my focus closer to the task at hand instead of having to jump off while a local build is progressing.

### Additional local build lag issues

When you're working on a long document that has a breaking issue, you sometimes have to continuously change and test the page to find the problem. Each time you make a change to the page, you must wait several minutes for the local build to recognize the change and reflect it. Similar to the above, waiting on these updates greatly elongates the time to fix. The wait is long enough that you notice the time spent waiting, but not long enough that it's worth it to turn to other tasks and then come back. Plus, doing so means you might lose track of your tactic.

**Comment by jpvajda** [comment]
adding this to the build audit label and we'll share this with Gatsby when we kick off the build audit next week.

**Comment by austin-schaefer** [comment]
I'd add one more significant set of issues related to local builds: Images, redirects, and to a lesser extent taxonomy don't work reliably in local builds.

**Comment by jpvajda** [comment]
closing as we discussed a lot of this in our build audit and it's captured as issues in our theme and docs projects under the build audit label
