### ISSUE TITLE
Issue: Requirements for the infrastructure agent

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#2635]
with the release of the ARM processor support, the following line may no longer be accurate:

"The infrastructure agent supports only x86 processor architectures:”

**Comment by barbnewrelic** [comment]
Fixing this with https://github.com/newrelic/docs-website/pull/2639

**Comment by barbnewrelic** [comment]
Updated https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent/
