### ISSUE TITLE
Issue: Amazon Elasticsearch monitoring integration

### ISSUE THREAD

**Issue by otteydw** [newrelic/docs-website#2636]
### Tell us what you need

This documentation says

> You can query and explore your data using the DatastoreSample event type, with a provider value of **ElasticsearchCluster** for clusters, and with a provider value of **ElasticsearchCluster** for nodes.

![image](https://user-images.githubusercontent.com/11666012/121422746-8797e980-c93d-11eb-949e-938be3ae1f00.png)

I would expect that the provider value would be different for clusters than for nodes. But this says the provider is "ElasticsearchCluster" for both.

I'm wondering if this was a copy/paste error?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-elasticsearch-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Checking with gts-infrastructure
