### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by rajumkc** [newrelic/docs-website#2638]
404 error - https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/adding-apps-new-relic-browser/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/adding-apps-new-relic-browser/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.77
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Thanks for reporting this broken link. Looks like we need to add a redirect URL from https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/ .

**Comment by barbnewrelic** [comment]
Fixed with https://github.com/newrelic/docs-website/pull/2652
