### ISSUE TITLE
Issue: Synthetic monitoring response codes

### ISSUE THREAD

**Issue by TrawfazzzMosowski** [newrelic/docs-website#2647]
### Tell us what you need

Missing the following 
// An operation was aborted (due to user action).
NET_ERROR(ABORTED, -3). Also, need an explanation of "(due to user action)"

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/synthetic-monitoring-response-codes/
* **OS**: Mac OS 10.15.7
* **Browser**: Safari 14.1
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Checking with help-proactive-monitoring

**Comment by barbnewrelic** [comment]
Fixed with https://github.com/newrelic/docs-website/pull/2656 . The hero noted this is a chrome specific response code, it means that the script hit some sort of timeout and the runner is shutting down, and to do that the runner ends all pending requests.
