### ISSUE TITLE
Issue: Configure polling frequency and data collection for cloud integrations

### ISSUE THREAD

**Issue by otteydw** [newrelic/docs-website#2649]
The page says "Collect nodes data" (plural) but the config screen has the singular form of the word "node."

![image](https://user-images.githubusercontent.com/11666012/121562835-d8fcb300-c9e7-11eb-9456-fbddd1fc74a5.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/infrastructure-integrations/cloud-integrations/configure-polling-frequency-data-collection-cloud-integrations/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Fixed with PR 2666
