### ISSUE TITLE
☂️ Refactor translation workflows to handle status per-page, not per-job

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#2655]
## Summary

We want to update our translation workflows so we only upload a file when it isn't already being actively translated. This ensures that we get a fully translated file back when the first job finishes.

In order to support this work, we need to update how we store the status of translations on a _per-file_ basis (rather than per-batch-job).

### Update the data in our queue
- For each active job, store what files are in it
- Do not submit same file in multiple jobs at once
- When adding file to queue, first check if it's in an active job
  - If yes, add to "Next Up" queue 

### Update how we submit files to be translated
- Only upload file for a job if it's not included in an ongoing job
- When a job finishes, check for any files in that job that might be queued up for another translation and upload those for new job at some point

## Acceptance criteria
- [x] #3074
- [x] #3075
- [x] #3076
- [x] #3077
- [x] #3078
- [x] #3080
- [x] Document the workflow system!
- [x] Close out all bugs this work resolves

### Resolves

https://github.com/newrelic/docs-website/issues/2603

## Helpful links
https://github.com/newrelic/docs-website/issues/2597

**Comment by zstix** [comment]
I'm going to use this issue as an umbrella issue for this work. In order to do so, I'll need to rewrite the description a little (FYI)
