### ISSUE TITLE
Redirect not working  the same when activated from inside the file as from pasting into a browser tab

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#2674]
### Description

The file `/docs/integrations/infrastructure-integrations/get-started/introduction-infrastructure-integrations.mdx` had this link to on-host integrations list (`/docs/infrastructure/host-integrations/host-integrations-list`), which failed to redirect to `https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/`. 

However, if you paste that same document link directly in a browser, it redirects!

I worked around this by just skipping the redirect and pointing to the actual file: /docs/integrations/host-integrations/host-integrations-list/.

Still, it would be interesting to hear what is causing this behavior in case it's happening elsewhere.

### Steps to reproduce

This issue has been fixed in production with a direct link to the file, skipping the redirect. Still, you can see this error in this branch: `rhs-june-11-integration-redirects`.

1. In the local build, go to this URL: `localhost:8000/docs/integrations/infrastructure-integrations/get-started/introduction-infrastructure-integrations/`
2. Under **On-host integrations**, in the table, click **On-host integrations**, which should fail. In production, this failed with a solid white screen. When I do it locally it fails with this message: `Error in function trimPathname in ./.cache/find-path.js:17`
3. Copy the URL above the failing page (https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/) and paste it into a new browser tab. In production, this page would redirect as expected to `/docs/integrations/host-integrations/host-integrations-list/`. I have to say that this page fails in my local build with a 404 so I can't reproduce that unusual solid white screen from production.

I get similar behavior in both Chrome and Firefox.

### Expected behavior

I would expect the link in the file to redirect the same way it redirects if you were to paste it directly into a browser.

**Comment by jpvajda** [comment]
@rhetoric101 do you see this problem anywhere else?
