### ISSUE TITLE
"Intro to Log API" has scary warning (without being clear why)

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#2682]
We should look at improving the clarity of this callout, and possibly downgrading it to "Important" or moving it elsewhere. 

### How can we make our docs better?

From an engineer:

> I think a big red warning like this on the  "Intro to Logs API" page (probably the first thing you'll find when looking for docs on logs) is maybe overkill. At the very least, it deserves explanation/justification – why should we not call the Logs API from a customer facing application? Is it because of request latency? Because the request could block?

![image](https://user-images.githubusercontent.com/55203603/121922501-e3bc8e00-ccee-11eb-929d-0da1df34da71.png)

**Comment by barbnewrelic** [comment]
Whoever picks this one up: Please contact me about this. There were some valid reasons why that big red callout was added to the top of the doc. Those reasons may have changed since this issue was opened. But I'd like to give some context 1:1 before someone proceeds with this request. Thanks!

**Comment by barbnewrelic** [comment]
rhetoric fixed this with his heroing of https://github.com/newrelic/docs-website/issues/2682

**Comment by barbnewrelic** [comment]
rhetoric fixed this with his heroing of https://github.com/newrelic/docs-website/pull/2739
