### ISSUE TITLE
Issue: Azure Cosmos DB (Document DB) monitoring integration

### ISSUE THREAD

**Issue by katlimruiz** [newrelic/docs-website#2689]
### Tell us what you need
In this page, it would be appreciated syntax for terraform too

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/microsoft-azure-integrations/azure-integrations-list/azure-cosmos-db-document-db-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@katlimruiz, thanks for your request! I'm not sure if this will address the specific syntax you need, but we are working on generic Terraform document for New Relic (doc-6750).
