### ISSUE TITLE
Meet with Gatsby to review Build audit approach

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2700]
Some of the team will meet with Gatsby to kick off our build audit process. Should be about 30 - 45 mins per attendee.

### Acceptance Criteria

- [x] Discuss Build Audit Label issues
- [x] Review general pain point overview doc for context of our current challenges.
- [x] Discuss next steps of how Gatsby will conduct their build audit
- [x] Discuss how Gatsby provides feedback on our builds. 

### Ideal Build Times

`<=10min`  for cold   `<=5min` for warm  

### General  Build Feedback  

**Local Builds**

- Local builds take a long time
- Switching branch and rebuilding often takes 10 or 20 minutes, which makes reviewing PRs a chore
-  local builds: Images, redirects, and to a lesser extent taxonomy don't work reliably in local builds.
- The console outputs a lot of errors, most of which are not meaningful

**Remote Builds**

- For "remote" build/deploys, I'd say the issues are primarily:
- Long build times
- Unpredictable build times (usually quick, but a long tail of very long build times), which makes it hard to tell stakeholders when something will go live
- Lack of contributor visibility into the status of a build while it's running

**Comment by pragmaticpat** [comment]
@jpvajda thanks for writing this up - can you tell me a little more about this one? "TW"?
> Lack of TW visibility into the status of a build while it's running

**Comment by jpvajda** [comment]
@pragmaticpat I think it means technical writer, but I changed it to contributor so it's more generalized. 😄
