### ISSUE TITLE
timeline view for a release note doesn't add a space between the sentences where bullets exists in the markdown

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#2714]
### Description

When you go to the timeline view  for particular release notes, it lists the title and a blurb about what's in the release notes. That blurb appears to just be a concatenation of whatever bullets appear at the top of the notes. This concatenation doesn't alway insert a space between sentences.

### Steps to reproduce

1. Go to `https://docs.newrelic.com/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/`
2. Scroll down to **January 12 Mobile app for iOS v3.68.0** and note the missing space between the two summary sentences.

### Expected behavior

a markdown post that contains `<li>` or`<ol>` or  `<p>` should result in a timeline preview blurb that is properly formatted.

[Raw File](https://raw.githubusercontent.com/newrelic/docs-website/develop/src/content/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-3680.mdx) 

### Screenshots

![image](https://user-images.githubusercontent.com/18040274/122129946-b86b9900-cdeb-11eb-99b2-ff38d4e19c45.png)

**Comment by jpvajda** [comment]
I'm not seeing this issue here: https://docs.newrelic.com/docs/release-notes/mobile-apps-release-notes/new-relic-ios-release-notes/new-relic-ios-3680/

<img width="1080" alt="Screen Shot 2021-06-21 at 4 55 19 PM" src="https://user-images.githubusercontent.com/1395158/122837543-7fcb3400-d2b1-11eb-81ce-6fadf310f957.png">


Also the screen shot is relating to a different release.  

Finally What does this mean?

> When you go to the preview page for release notes,

**Comment by bradleycamacho** [comment]
@jpvajda I think the issues is that the "preview" blurb for any release doesn't add a space between the sentences converted from those bullets. See the blurb for that same release:

<img width="1382" alt="Screen Shot 2021-06-21 at 4 11 33 PM" src="https://user-images.githubusercontent.com/42678939/122838787-a1292180-d2ab-11eb-92a9-fe063992269c.png">

**Comment by jpvajda** [comment]
@bradleycamacho I gotcha, so the timeline view "preview" doesn't add a space between the sentences converted from those bullets. Thanks for clarifying!

**Comment by jpvajda** [comment]
I'm thinking we need to make a change to the [item.js](https://github.com/newrelic/docs-website/blob/develop/src/components/Timeline/Item.js) component to better handle bullets and paragraphs in posts.
