### ISSUE TITLE
migrate internal style guide docs to new site

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#272]
### Summary

We need to rewrite and update our internal style guide content for its new home on an open source docs site. To start working on that, I'll need that content migrated over.

Here is all of the content that needs to be brought in: https://docs.newrelic.com/docs/new-relic-only (minus the Docs for training env and drupal).

**Import**

- All docs under Basic style guide
- All docs under Tech writer style guide

**Don't Import**
- Drupal Configuration
- Training environment

**navigation**

- The new IA calls for this to exist in the navigation under a category called New Relic Only. We need to decide if this should be called something else as this content is no longer behind a login. @paperclypse 

Once imported, I'll need a place to put that content so that it doesn't get overwritten with each new migration.

**Comment by jpvajda** [comment]
I spoke to @paperclypse, he also said we can migrate all this content over and then he can purge wasn't isn't needed if that's easier.
