### ISSUE TITLE
add-files-to-translation-queue needs pagination logic for the github API

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#2727]
When a PR is made `add-files-to-translation-queue` runs and uses the github API to get a list of the files changed in the PR. The endpoint used returns paginated results with a default of 30 at a time. Our current script doesn't take pagination into account so a large PR will only have the first 30 files assessed for translation needs. We've added the logic for pagination in this particular endpoint [here](https://github.com/newrelic/docs-website/pull/2726) and can use the same logic

### Acceptance Criteria

- [ ] use the `fetchFilesFromGH` function from check-for-outdated-translations to pull `>30` files at a time

**Comment by jpvajda** [comment]
Adding this to our localization MT milestones.
