### ISSUE TITLE
Assess the use and value of auto generated Index Pages

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2743]
Determine if there are actual value in the index pages of the docs sites and if it's worth supporting longer term as index pages causes us a lot of technical challenges as well as UX challenges, there is question if there are really all the valuable to a user.

### Example Index Pages

- https://docs.newrelic.com/docs/apis/nerdgraph/
- https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/
- essentially any page that is just a bunch of links

### Common use cases 

- People like to an index page as it offers a "section" of content so it can be used as an index of information 
- People can use this page to help them find content once they click into a sub navigation of content as it reflects what is in the sub section.
- other?

### Common problems

- keeping these pages in sync with the navigation so they accurately represent each other.

### possible approaches

- tbd

**Comment by roadlittledawn** [comment]
value assessed and solution: remove them, redirect highest traffic pages.
