### ISSUE TITLE
Issue: Query and alert on billing/usage data missing examples for AI Incident Events

### ISSUE THREAD

**Issue by nedl86** [newrelic/docs-website#2753]
### Tell us what you need

* "Query and alert on billing/usage data" doc is missing examples about querying and setting up alerts for billable AI Incident Events 

### Anything else you'd like to share?

* This document shows how to query and alert on the other two billable SKUs under the New Relic One pricing plan (Data usage and User count) but doesn't list anything about AI Incident Events.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-users/usage-queries-alerts/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reaching out, @nedl86. I've added this request to our backlog, you can track it [here](https://newrelic.atlassian.net/browse/DOC-7043).

**Comment by HenryTech** [comment]
NrAiIncident simply tracks Incident (nee "violation") open and close events, so this doc doesn't really warrant examples specifically talking about what incidents would look like when alerting on usage data. They will look like incidents from any other source.

**Comment by bradleycamacho** [comment]
Closing this based on @HenryTech's thoughts. @nedl86 let me know if you disagree and want us to explore this deeper!
