### ISSUE TITLE
Add Infrastructure status API doc

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#2758]
### How can we make our docs better?

This Infrastructure release note mentions status API. 

https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1181/

The link is linked to the Infrastructure GitHub repository.

https://github.com/newrelic/infrastructure-agent/blob/master/docs/status_api.md

Could you add this explanation to the docs site? 

### Anything else you'd like to share?

Infrastructure status API is now enabled by default if users install Infrastructure Agent via New Relic One UI. We hope such features is explained in official doc stie.

**Comment by urbiz-nr** [comment]
Closed via #2907.
