### ISSUE TITLE
Issue: Adopt cloud services - bad link in first paragraph New Relic Platform

### ISSUE THREAD

**Issue by liamhurrell** [newrelic/docs-website#2760]
###  bad link 404

* bad url link to missing content 404 on this page in the docs: (https://docs.newrelic.com/docs/new-relic-solutions/new-relic-solutions/optimize-your-cloud-native-environment/adopt-cloud-services/)
* Here are the steps to using the [New Relic Platform](https://newrelic.com/products)  to monitor your modern technologies and cloud services:

### Anything else you'd like to share?

![screenshot:] (https://github.com/liamhurrell/images-misc/blob/15fdfb45a28a23165f4a36009d81ece96053cfba/Screenshot%202021-06-21%20at%2011.42.14.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/new-relic-solutions/optimize-your-cloud-native-environment/adopt-cloud-services/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting the broken link, @liamhurrell - fixing this [here](https://github.com/newrelic/docs-website/pull/2761), the updated doc will be live shortly.
