### ISSUE TITLE
Build a better terminal output/error logs

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#2763]
### Context
As a docs team, we are constantly running into blockers in the form of markdown errors. These are usually our fault by forgetting a closing tag, having an extra `'` wrapping entire sections as a string, etc. 

### issue
The issue is that the errors returned by Gatsby are extremely unhelpful. The errors can sometimes point us in the correct direction, but could benefit from a reworking.

### Specific requests:

1. **Make the error output easier to find**. The terminal outputs so much that it is difficult to find the area that's telling us the error at hand. This could be solved by colors, bolding, using asterisks to create "sections", etc. 
2. **Make the errors more helpful**. Maybe this info is already there, but I'd love if the errors could tell us if they were caused by: 

  - Invalid markdown
  - Missing markdown tags
  - Broken taxonomy
  - Actual Gatsby error

3. **Give us the line number where the error occurs**. Currently errors tell us things like "unexpected token '>'" but don't tell us WHERE. It'd be great if parsing errors would output the exact line of the error.

**Comment by bradleycamacho** [comment]
@jpvajda This might be outside the scope of your team, but Mark mentioned this might be useful info when chatting with Gatsby.

**Comment by jpvajda** [comment]
@bradleycamacho I'm not sure if this is something we can improve without the help of Gatsby but we can look into it. Could you provide some screen shots of what you are seeing?

**Comment by roadlittledawn** [comment]
@bradleycamacho Kris recently added a script to run a MDX parser on files in a given path so you can get a bit more error detail AND you don't have to run a build. 

i believe it's `yarn verify-mdx`

**Comment by bradleycamacho** [comment]
@roadlittledawn This is great! Thanks for letting me know!

**Comment by bradleycamacho** [comment]
@roadlittledawn I've been toying around with the new command and it works great. I think this actually solves 99% of our issues, so I'm going to close this issue for now. Thanks!
