### ISSUE TITLE
cumulativeLayoutShift is missing from PageViewTiming Attribute Dictionary

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#2767]
### Issue

`cumulativeLayoutShift` is missing from `PageViewTiming` Attribute Dictionary

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by mmfred** [comment]
@khickey-newrelic Thanks for filing this issue! I've added this attribute and it should publish later this afternoon.
