### ISSUE TITLE
Issue: NerdGraph tutorial: Configure cloud integrations

### ISSUE THREAD

**Issue by carrieschmid** [newrelic/docs-website#2778]
### Tell us what you need

* If you've found something inaccurate, what is it?

https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-cloud-integrations-api-tutorial/#disable-integration

is not right

There is also a problem with "unlink account" section
This works better:
mutation {
  cloudUnlinkAccount(accountId: 458665, accounts: {linkedAccountId: 77579}) {
    unlinkedAccounts {
      id
      name
    }
    errors {
      type
      message
    }
  }
}

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-cloud-integrations-api-tutorial/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @carrieschmid - we'll check it out!

**Comment by josemore** [comment]
@carrieschmid Are you referring to the wrong "</integration_slug></provider_slug>" at the end of the example or something else in the "unlink account" section?
