### ISSUE TITLE
Undocumented attribute: error

### ISSUE THREAD

**Issue by pjpscriv** [newrelic/docs-website#2779]
### Tell us what you need
Looks like `Transaction` has an undocumented attribute `error`. When I do `SELECT * FROM Transaction` this is my result:

![image](https://user-images.githubusercontent.com/16329923/122873515-f6396600-d385-11eb-9060-4b3873e8b0cb.png)

But I am not seeing `error` documented in the [data dictionary](https://docs.newrelic.com/attribute-dictionary/?event=Transaction).

Is this a default attribute of `Transaction`? If so could you add some documentation for it please.

Cheers 🙂

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Windows 10 - Version 10.0.18363 Build 18363
* **Browser**: Chrome 91.0.4472.106 
* **Device**: HP EliteBook 840 G6

**Comment by urbiz-nr** [comment]
Thanks for reaching out, @pjpscriv - we'll check it out!
