### ISSUE TITLE
Issue: Install the infrastructure monitoring agent for Linux

### ISSUE THREAD

**Issue by newtob** [newrelic/docs-website#2801]
How do we know the impact of running in unprivileged mode. Some incoming links to this page point to headings that have been removed:

> "In unprivileged mode, the nri-agent user can collect all metrics available as documented for the Infrastructure agent, but process samples will not report file descriptor counts or I/O metrics, and some inventory sources won’t be reported."

The links point to headings in this page called #mode-metrics any clues where that section may be?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by mmfred** [comment]
Taking a look now @newtob

**Comment by mmfred** [comment]
Hi @newtob - This looks like the info you need: https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/linux-agent-running-modes/#mode-metrics

Hope that helps. I'll create a redirect to this page - thanks a lot for the feedback and let us know if that isn't what you're looking for.

**Comment by mmfred** [comment]
I spoke too soon about the redirect - it won't work since the page is already there. There's a link to the running modes page in the spot where I think it's most important, so I'm going to close as can't fix.
