### ISSUE TITLE
Issue: Docker container for infrastructure monitoring

### ISSUE THREAD

**Issue by hhmahmood** [newrelic/docs-website#2816]
Hi,

`newrelic/infrastructure:latest` base image does not support `snowflakeintegration-linux`. 

Here is my docker file

```
FROM newrelic/infrastructure:latest

RUN apk add git
RUN git clone https://github.com/newrelic/newrelic-snowflake-integration.git
WORKDIR newrelic-snowflake-integration
RUN wget https://github.com/newrelic/newrelic-snowflake-integration/releases/download/v0.1.5/snowflakeintegration-linux
RUN chmod +x snowflakeintegration-linux
RUN cp flexConfigs/flex-snowflake-linux.yml /etc/newrelic-infra/integrations.d/
ENV NRIA_LICENSE_KEY=
ENV NEWRELIC_SNOWFLAKE_HOME=
ENV SNOWSQL_ACCOUNT=
ENV SNOWSQL_USER=
ENV SNOWSQL_PWD=
ENV SNOWSQL_ROLE=
```

Following is the error I see in newrelic UI events -> SnowflakeAccount -> Dimensions -> error_msg

`'Error loading shared library libstdc++.so.6: No such file or directory (needed by /newrelic-snowflake-integration/snowflakeintegration-linux)\nError loading shared library libgcc_s.so.1: No such file or directory (needed by /newrelic-snowflake-integration/snowflakeintegration-linux)\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSs7replaceEmmPKcm: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt15basic_streambufIcSt11char_traitsIcEE9pbackfailEi: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZSt19__throw_logic_errorPKc: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: __cxa_begin_catch: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSs6appendERKSsmm: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt9exceptionD2Ev: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSsC1ERKSs: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: __once_proxy: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZSt17__throw_bad_allocv: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSs6appendEmc: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt15basic_streambufIcSt11char_traitsIcEE6xsgetnEPcl: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSo9_M_insertIyEERSoT_: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt18basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _Znwm: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZSt24__throw_invalid_argumentPKc: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSs5eraseEN9__gnu_cxx17__normal_iteratorIPcSsEES2_: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt15basic_streambufIcSt11char_traitsIcEE5imbueERKSt6locale: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt13basic_filebufIcSt11char_traitsIcEE5closeEv: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSs7_M_leakEv: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: gnu_get_libc_version: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSs2atEm: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt11range_errorD1Ev: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: __cxa_demangle: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSs9push_backEc: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt9basic_iosIcSt11char_traitsIcEE7copyfmtERKS2_: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSolsEi: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZSt16__throw_bad_castv: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt16invalid_argumentD1Ev: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: __cxa_guard_acquire: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNKSs4findEcm: symbol not found\nError relocating /newrelic-snowflake-integration/snowflakeintegration-linux: _ZNSt9basic_iosIcSt11char_traitsIcEE4initEPSt15basic_streambu'`

The same case is when I use newrelic/infrastructure-k8s:2.6.0 in k8s. I get these errors.
```
Error relocating /newrelic-snowflake-integration/snowflakeintegration-linux: gnu_get_libc_version: symbol not found
Error relocating /newrelic-snowflake-integration/snowflakeintegration-linux: __register_atfork: symbol not found
Error relocating /newrelic-snowflake-integration/snowflakeintegration-linux: __strdup: symbol not found
Error relocating /newrelic-snowflake-integration/snowflakeintegration-linux: setcontext: symbol not found
Error relocating /newrelic-snowflake-integration/snowflakeintegration-linux: makecontext: symbol not found
Error relocating /newrelic-snowflake-integration/snowflakeintegration-linux: backtrace: symbol not found
Error relocating /newrelic-snowflake-integration/snowflakeintegration-linux: getcontext: symbol not found
```

**Comment by mmfred** [comment]
Thanks for filing this issue @hhmahmood - I'll look into it.

**Comment by paperclypse** [comment]
Hi @hhmahmood! I've asked around and here's what I've found. The newrelic/infrastructure image is based on Alpine Linux, which is apparently a pretty lightweight image. Sometimes this can cause problems when run directly because some things might be missing (for example, libstdc++.so.6 and libgcc_s.so.1). 

Adding gcc in the Dockerfile before adding our integration might solve your problem.

**Comment by hhmahmood** [comment]
Hi @paperclypse . Actually I had already tried this, after installing `RUN apk add --no-cache libgcc` and `RUN apk add --no-cache libstdc++` and I also installed glibc.

```
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.33-r0/glibc-2.33-r0.apk
apk add glibc-2.33-r0.apk
```

in docker file but it still complains about missing library.

`error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory`

But I could see the library is already there in the container on path.

`/usr/lib/gcc/x86_64-alpine-linux-musl/6.4.0/`

I think the path which snowflakenewrelic-linux looks for is different than the path where libstdc++.so.6 exists in the container. This is my assumption.

**Comment by paperclypse** [comment]
@hhmahmood I'm no expert on this stuff. I think you'd probably get more useful answers by doing to our Explorers Hub forum at discuss.newrelic.com.

One of our developers suggested using the standalone snowflake.js. We use flex simply to schedule it to run once an hour and send the data to New Relic. He's created a snowflake prometheus exporter, but hasn't tried it out on containerized environments: https://github.com/danifitz/prometheus_snowflake_exporter. Might be helpful?
