### ISSUE TITLE
Issue: NRQL syntax, clauses, and functions 404 link

### ISSUE THREAD

**Issue by jemisonf** [newrelic/docs-website#2826]
### Tell us what you need

In the "Required: `SELECT` Statement" section, the "attribute" link goes to a non-existent page:

> The SELECT specifies what portion of a data type you want to query by specifying an [attribute](https://docs.newrelic.com/docs/insights/new-relic-insights/decorating-events/insights-attributes/) or a [function](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#functions). It's followed by one or more arguments separated by commas. In each argument you can:

From here: https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#state-select

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.106
* **Device**: Unknown

**Comment by mmfred** [comment]
Thanks @jemisonf! I'll fix or redirect that link.

**Comment by jemisonf** [comment]
Awesome, thanks @mmfred! Not a blocker for me or anything, just wanted to make sure the issue was documented

**Comment by bradleycamacho** [comment]
Thanks for reporting this @jemisonf 👑

**Comment by jemisonf** [comment]
Thank you Bradley 🙏
