### ISSUE TITLE
Large SVG images embedded into a page extend over main column

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#2831]
### Background

When emebedding a large SVG image into a page, the image extends over the right hand side of the main column.

![Screen Shot 2021-06-24 at 5 52 59 PM](https://user-images.githubusercontent.com/70179215/123352842-092e7080-d515-11eb-86f9-673f07984a72.png)

### Describe the solution you'd like

Ideally, this would be the same as when using a PNG image -- the width of the image is limited to the width of the main column.

**Comment by jpvajda** [comment]
@nr-kkenney curious on the solution here and why an `svg` is behaving different than a `png`.

**Comment by nr-kkenney** [comment]
@jpvajda i really have no idea atm 🙈

**Comment by kaileyhaynes** [comment]
Hey y'all! The docs team was talking about this issue today. Are there any updates?

**Comment by jpvajda** [comment]
@kaileyhaynes this is currently a lower priority issue so we aren't planning on implementing a solution at the moment due to our commitments to a larger product initiative.  However if you can provide data on customer impact, like pages where this is occurring we can consider bumping the priority of it.

**Comment by rhetoric101** [comment]
@jpvajda, we do have a workaround where we have to keep the image width limited so the image doesn't run into the right gutter. We'll keep you posted on whether this workaround has side-effects.

**Comment by nr-kkenney** [comment]
this was the workaround i posted when it was brought up in the channel (just for reference):
```html
<div style="width: 100%;">
        <img alt="ALT TEXT" src="https://upload.wikimedia.org/wikipedia/commons/3/39/CoADivisions-wide.svg" title="FILENAME" style="max-width: 100%;"/>
</div>
```

![Screen Shot 2021-06-24 at 2 19 28 PM](https://user-images.githubusercontent.com/70179215/125491962-29d3a5c3-a93f-49f1-97c3-5756be992482.png)
![Screen Shot 2021-06-24 at 2 18 29 PM](https://user-images.githubusercontent.com/70179215/125491968-de7a7b05-865f-443b-84dd-986ed55c2af2.png)
![Screen Shot 2021-06-24 at 2 17 37 PM](https://user-images.githubusercontent.com/70179215/125491973-6c1c0566-0618-4c5f-9a50-9b8516bc27d1.png)
