### ISSUE TITLE
Add clarification "invitation email doesn't send when user is added to SSO group"

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#2833]
### How can we make our docs better?

Our customer asked the support team to add $title.

https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more/

When a user is added to a group that is configured for user password authentication, a notification mail is sent, which includes the link to set up a password.
The customer would like to clarify in the above doc at a notification mail was not sent when a user is added to an SSO group. 

I think we can add this behavior in the last step in [Set up SAML SSO authentication](https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more/#saml)

### Anything else you'd like to share?

The product team confirmed with our internal ticket GTSE-9937.

**Comment by zuluecho9** [comment]
@tanaka-takayoshi Do you happen to know: there are various ways to implement SSO (e.g., Okta, OneLogin, Azure, others); do you happen to know if this is a general callout that applies to all or a identity provider service-specific one? I vaguely recall seeing a slack thread about this; if this was based on a slack convo (or another resource), do you have a link to it?

**Comment by zuluecho9** [comment]
Actually, thinking about this more now, I remember a convo where someone pointed out that this was just something based on whether a customer had checked 'send email' in the auth domain UI, and wasn't linked to SSO use. Does that make sense?

**Comment by tanaka-takayoshi** [comment]
Sorry for the late response. The internal discussion tool place in GTSE-9937.
I believe this is a general callout for all identity providers as far as SAML SSO is specified.

**Comment by zuluecho9** [comment]
Someone internally told me: "We don’t send a password setting /user verification email for SSO folks because we aren’t managing the password and we are trusting the Identity Provider to have verified the user. This behavior is consistent across all Identity Providers." I will attempt to add more context about this in docs, thanks.

**Comment by zuluecho9** [comment]
Closing this out, handled in https://github.com/newrelic/docs-website/pull/3190
