### ISSUE TITLE
Bugs in the Tessen TDOC_DocPageView_pageView event

### ISSUE THREAD

**Issue by zoezhou1113** [newrelic/docs-website#2841]
### Related issues 
https://github.com/newrelic/docs-website/issues/1816

The same issues also exist in  `TDOC_DocPageView_pageView` `TOSS_DocPageView_pageView` and `TDEV_DocPageView_pageView` events for the developer and open source sites. 

### issues with the `TDOC_DocPageView_pageView` event:

1. There is a duplicate category property in the page version of the event
2. Referrer is not tracked 
3. When someone uses the search function, every time a letter is typed into the search text box, it generates an extra pageview

**Referrer**
![image](https://user-images.githubusercontent.com/80297589/123489923-0a2cd400-d5e1-11eb-9897-5d2981a17781.png)

**Category**
<img width="643" alt="Screen Shot 2021-07-08 at 2 50 19 PM" src="https://user-images.githubusercontent.com/1395158/125001672-6f84ba00-e010-11eb-83a7-bc08561994b8.png">

### Expected Behavior

for `1` ~~delete the duplicate category in the page version of the event. the Category should only exist under properties.~~
for `2` ensure we track the referrer data. [see PR](https://github.com/newrelic/gatsby-theme-newrelic/pull/424)
for `3` search should not generate pageview but still capture the search term entry for a user. see [Issue](https://github.com/newrelic/gatsby-theme-newrelic/issues/425)
for `3` capturing every letter of a search entry is not useful, and results in data such as this, is there a way where we can kjust capture they end result of what they are searching for? see [Issue](https://github.com/newrelic/gatsby-theme-newrelic/issues/425)

<img width="664" alt="Screen Shot 2021-07-08 at 2 46 58 PM" src="https://user-images.githubusercontent.com/1395158/124991147-86221580-dffe-11eb-8adb-bc046d79a28d.png">

**Comment by roadlittledawn** [comment]
taking a quick look now in live data in segment for docs site. i see `referrer` populated in many of the `page` and `track` events. looks like sometimes the referrer does not show up in both `context.page` and `properties`. and i saw only a couple that were empty.

**Comment by roadlittledawn** [comment]
as far as i can tell, that `"category": null,` is something that's set outside our code. i don't see us setting that and i looked at a couple other segment sources (`NR Account (Production)`, `NR Alerts (Production)`) and they have the same thing in their `page` events.

![2021-07-08_16-15-46](https://user-images.githubusercontent.com/2952843/125001741-36484c00-e008-11eb-9e12-a34755f12b2a.png)

**Comment by jpvajda** [comment]
@roadlittledawn can you confirm this assumption by asking in `#project-tessen` slack room? It be good to validate it.

**Comment by jpvajda** [comment]
potential ideas how to improve the search field instrumentation: 

`1` set up nested de-bouncing 
`2` only send search data when a user clicks on a link, which confirms they've completed a search.

```Debounce time is basically and amount of time that the switch doesnt register another click. Good explanation thanks! the switch use a spring and the bounce can send multiple signals when clicking.```

**Comment by zoezhou1113** [comment]
@roadlittledawn You are right about #1. I didn't realize the extra "category": null is a Tessen thing.

**Comment by zoezhou1113** [comment]
@roadlittledawn I checked the referrer again in Segment debugger, and none of the pageviews I generated are tracking the referer page.

**Comment by jpvajda** [comment]
@zoezhou1113 but every page wouldn't have a referrer link correct? That's not the expectation here?  If a user goes directly to site and just finds content via search or by traversing the nav then there is no referrer I assume.

**Comment by zoezhou1113** [comment]
@jpvajda In Tessen, "referer" is the previous page URL, it's different from the "referral" channel.

**Comment by jpvajda** [comment]
@zoezhou1113 so in my example 

> If a user goes directly to site and just finds content via search or by traversing the nav then...

the refferer url should be docs.newrelic.com?

**Comment by zoezhou1113** [comment]
The first page would not have a referrer link in this case, but all of the pages visited subsequently should have the previous page URL as the referrer. 

> @zoezhou1113 but every page wouldn't have a referrer link correct? That's not the expectation here? If a user goes directly to site and just finds content via search or by traversing the nav then there is no referrer I assume.

**Comment by jpvajda** [comment]
@zoezhou1113 so would this explain why some results in Segment don't contain a `referrer url`? I'm just questioning if there is an actual issue here as it sounds like in some cases this is expected functionality.

**Comment by zoezhou1113** [comment]
No, the issue is none of these pageviews have referrer right now.

Kind regards,
Zoe

Zoe Zhou
Web Analytics Manager
New Relic
Email: ***@***.***

**Comment by jpvajda** [comment]
@zoezhou1113 I think @roadlittledawn did see some results with referrer `url values`, so let me check with him.

**Comment by jpvajda** [comment]
I scheduled some time for us to sync on this topic. 📆

**Comment by roadlittledawn** [comment]
i suspect this may be related to what i was talking about. since our sites is a javascript bundle that loads html files and json data, requesting a new page works a little differently and is considered a route change that may not be tracked like other sites.
so i wonder if we explicitly set `properties.referrer` manually for each route change on the site (clicking on a docs link somewhere on a docs page), if that would give us the data we’d expect?

we already do this for each page that’s viewed, but we don’t send the previous URL / referrer for those events.

**Comment by roadlittledawn** [comment]
still not 💯 % sure why we see some internal URLs in `referrer` fields, but maybe those are users directly accessing pages (typing into URL bar, bookmarks, new tabs)?

**Comment by jpvajda** [comment]
breaking the search instrumentation into a seperate issue https://github.com/newrelic/gatsby-theme-newrelic/issues/425

**Comment by jpvajda** [comment]
To mark this as done we just need to bump the theme to newest version that contains this fix on both the `dev` site and `docs` site

**Comment by roadlittledawn** [comment]
developer is now using new theme version and `referrer` was being set in segment. and docs PR was just merged into `develop` and will go out in next deploy PR
