### ISSUE TITLE
Broken Link - Dashboards Introduction

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#2844]
### Tell us what you need

Hi all, I found a broken link in this doc: 
https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/

The broken link leads to a 404 error and is located in this line:

>To organize dashboards with multiple pages, see [Add pages to a dashboard](https://docs.newrelic.com/docs/dashboards/new-relic-one-dashboards/manage-your-dashboard/add-pages-dashboards/).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.114
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for letting us know! I fixed it in PR #2845.
