### ISSUE TITLE
Pages is missing not allowed

### ISSUE THREAD

**Issue by FL-K** [newrelic/docs-website#2846]
Error: 400: {"error":{"title":"Validation failed","messages":["The property '#/' contains additional properties [\"pages\"] outside of the schema when none are allowed in schema https://api.newrelic.com/v2/dashboards"]}}

If I export one newrelic dashboard that contains `pages`, I see pages array, but how can I create such dashboard via API then ?

Exported dashboard structure: (widgets are removed for privacy reason, just structure is left).
We can create fine via API dashboard with widgets, but we want to create pages for different environments same way as we can do via UI, which gives the exported structure as below

```
{
  "name": "some-service (AWS CloudWatch)",
  "description": null,
  "permissions": "PUBLIC_READ_WRITE",
  "pages": [
    {
      "name": "prod",
      "description": null,
      "widgets": []
    },
    {
      "name": "stage",
      "description": null,
      "widgets": []
    },
    {
      "name": "dev",
      "description": null,
      "widgets": []
    }
  ]
}
```

**Comment by x8a** [comment]
Hey, @FL-K! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
