### ISSUE TITLE
Issue: NGINX monitoring integration

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/docs-website#2852]
### Tell us what you need

Second link on body of page is not correct. Should probably be a link to the matching anchor https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration/#config

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/nginx-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi Max! Thanks for letting us know. I'll get this fixed shortly.
