### ISSUE TITLE
Install the browser monitoring agent - Request for one-stop shop of compatible frameworks and libraries for larger enterprises

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#2857]
### Tell us what you need

* A customer who is managing a bunch of teams at an enterprise may need to install the browser agent for a variety of different application environments. A request was made for better documentation on reviewing compatibilities all in one place. Right now, you would have to search under browser in addition to all the individual APM language agents to find out which framework works with auto-injection and which does not, so then requires manual, copy/paste of browser agent JavaScript. 

### Anything else you'd like to share?

Having one place to update and maintain a list would help elevate and surface this for customers, particularly those in larger organizations working with tons of different language agents, environments and teams. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/
* **OS**: Mac OS 10.14.6
* **Browser**: Chrome 91.0.4472.114
* **Device**: Unknown

**Comment by CherylFrankenfield** [comment]
Ticket for references and request: 
https://newrelic.zendesk.com/agent/tickets/461703

**Comment by paperclypse** [comment]
Hi @CherylFrankenfield! Thanks for filing this issue. This seems like a great suggestion. Pulling together won't be a simple task. I'll file a Docs Jira for this work so we can devote some time to this.

**Comment by paperclypse** [comment]
I've created the Jira: DOC-7074.

**Comment by austin-schaefer** [comment]
Closing out issues older than 90 days, feel free to re-open if anyone would like us to revisit this issue!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
