### ISSUE TITLE
Bad screenshots

### ISSUE THREAD

**Issue by lazyplatypus** [newrelic/docs-website#2867]
### Tell us what you need

Please fix broken images

![Screen Shot 2021-06-29 at 9 13 10 AM](https://user-images.githubusercontent.com/10321085/123832485-3c2c8780-d8ba-11eb-9f85-81046b997dc7.png)
![Screen Shot 2021-06-29 at 9 13 34 AM](https://user-images.githubusercontent.com/10321085/123832533-49e20d00-d8ba-11eb-949f-1c897f2e6738.png)
![Screen Shot 2021-06-29 at 9 13 46 AM](https://user-images.githubusercontent.com/10321085/123832559-51091b00-d8ba-11eb-99bb-bdfd9e8a77c7.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/use-charts/chart-types/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks for letting us know, @lazyplatypus! I'll look into getting those fixed.
