### ISSUE TITLE
[Docs Site UX] What's New navigation

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#287]
## Description
We would like to add a link to the top-level navigation that takes the user to a page containing a list of all the What's New posts (#288 ).

When browsing the top-level What's New page, or any What's New post, the sidebar should contain links to all of the posts in a nested structure (like the rest of the site). The navigation content should contain the 10 most recent posts, and then "buckets" of expandable sections based on the distance from the current date:

```
Most recent post
2nd most recent post
3rd
4th
5th
6th
7th
8th
9th
10th
This Month <-- expandable
  post a
  post b
  ..
Last Month <-- expandable
  post c
  post d
  ..
Older <-- expandable
  post g
  post h
  ..
```

**TBD** on the exact breakpoints for what falls into each bucket.

This will be run by a `.yml` configuration file that will be automatically generated via a GH Action.

## Acceptance Criteria
* [ ] Top-level navigation updated to add a link for the new What's New page
* [ ] Function to generate a `src/nav/whats-new.yml` based on the posts and current date
* [ ] Ability to trigger the function on a regular interval to keep the sidenav up to date (GH Action)

## Screenshot(s)
![Image from iOS](https://user-images.githubusercontent.com/1946433/99716915-8795d200-2a5d-11eb-82d3-5ec90ce73af8.jpg)

**Comment by djsauble** [comment]
My only suggestion is to drop the "This Year" bucket so we don't duplicate all the posts from the current year.

**Comment by zstix** [comment]
We should handle this via Javascript and _not_ via `YAML`.

**Comment by jerelmiller** [comment]
@djsauble I see that the mock has a badge next to the "What's new" link in the sidebar with a count. What should that count contain?

**Comment by djsauble** [comment]
@jerelmiller Yeah, ignore that. I was playing with the idea of a badge that showed people how many "What's New" posts appeared since the last time they navigated to that section. If we need to call more attention to this section we can revisit but it's fine for now.
