### ISSUE TITLE
Issue: Clarify `TracingBytes` components 

### ISSUE THREAD

**Issue by linbaker** [newrelic/docs-website#2870]
### Tell us what you need

Clarify what 'TracingBytes' are composed of - Are these just spans and Distributed Trace summaries? Do Transaction events copied to the DT pipeline count here? 

What does 'excluding internal tracing.' mean? Is this stack traces, transaction traces and SQL traces? 

### Anything else you'd like to share?

Possibly outdated internal document with more information:

* https://nerdlife.datanerd.us/new-relic/fso-product-considerations-with-nr-1-tdp-ingest-metering-cb3bd056-dd09-454e-90e0-67fce00c0835

Support tickets asking for further clarification on this:

* https://newrelic.zendesk.com/agent/tickets/461374
* https://newrelic.zendesk.com/agent/tickets/461939

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/manage-data/manage-data-coming-new-relic/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.114
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @linbaker, thanks for writing this issue! I'm going to reach out to our resident Distributed Tracing expert and then follow up with you.

**Comment by rhetoric101** [comment]
@linbaker, thanks for your questions. Our documentation looks a bit sparse on this. I'm checking with our team to see how we can improve this. I'll keep you posted.

**Comment by rhetoric101** [comment]
@linbaker, we're addressing your questions in PR #2924
