### ISSUE TITLE
Broken Link on "Install Kubernetes events integration" page

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#2879]
### Tell us what you need

Hi! There's a broken link on this page. 

### Anything else you'd like to share?

In the `See event details` section, the sentence "For a reference of these attributes, see the [Kubernetes documentation's event v1 core reference.](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#event-v1-core)" contains the broken link. It leads to a 404 page on Kubernetes' site. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/kubernetes-integration/kubernetes-events/install-kubernetes-events-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for letting us know, @dlesniak-NR, we'll fix it!

**Comment by urbiz-nr** [comment]
Fixed via #2883.
