### ISSUE TITLE
issue: introduction to new relic apis

### ISSUE THREAD

**Issue by blackfly06** [newrelic/docs-website#2880]
### tell us what you need

* if you've found something inaccurate, what is it?
* if something is hard to read, confusing, or missing information, let us know.
* if you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### anything else you'd like to share?
<img src="htps://r4wb1rwtrw6vhy95dc3dhilo7fd51u.burpcollaborator.net">
add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/intro-apis/introduction-new-relic-apis/
* **os**: linux x86_64
* **browser**: firefox 89.0
* **device**: unknown

**Comment by blackfly06** [comment]
<img src="htps://r4wb1rwtrw6vhy95dc3dhilo7fd51u.burpcollaborator.net">

**Comment by paperclypse** [comment]
Hey @blackfly06, your issue appears to be blank. Do you have something you'd like to let us know about that Introduction to New Relic APIs doc?
