### ISSUE TITLE
Issue: Upload source maps to un-minify JS errors

### ISSUE THREAD

**Issue by adarshpala-hubdoc** [newrelic/docs-website#2888]
### Tell us what you need

Hi, I would like to suggest a change to the @newrelic/publish-sourcemap module (https://www.npmjs.com/package/@newrelic/publish-sourcemap) but I can't find its GitHub repo. My suggestion is to add a `.on` handler in the `sendRequest` function to handle errors when attaching `sourcemap`. Here is the code change I would like to suggest:
```
  function sendRequest (sourcemap) {
    request
      .attach('sourcemap', sourcemap)
      .on('error', callback)
      .end(function (err, httpResponse) {
        if (err) return callback(err)
        if (httpResponse.statusCode < 200 || httpResponse.statusCode > 299) {
          var error = new Error()
          error.status = httpResponse.status = httpResponse.status
          error.response = httpResponse
          return callback(error)
        }
        return callback(null, httpResponse.body)
      })
  }
```
So I just added the `.on('error', callback)` line which handles any errors when attempting to attach the source map file. Currently if the source map file does not exist or if there's an error while reading it, an error is thrown which cannot be handled at all (`.catch`, `try/catch` and callbacks do not work). This function is in the `index.js` file in @newrelic/publish-sourcemap. Thank you for looking into this.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/browser-monitoring/browser-pro-features/upload-source-maps-un-minify-js-errors/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @adarshpala-hubdoc! Thanks for your feedback. I'll pass it along to our developers. I can't find the repo for this either, but on npm I'm seeing the license for this is listed as "New Relic proprietary", which is probably why.

**Comment by paperclypse** [comment]
@adarshpala-hubdoc I got some feedback from our developers. It sounds like any errors happening during upload should be caught and handled by the `.end()` event.
