### ISSUE TITLE
Issue: Connect AWS to New Relic infrastructure monitoring

### ISSUE THREAD

**Issue by djaffinito** [newrelic/docs-website#2896]
### Tell us what you need

Under the section "Disconnect your AWS integrations", we link to here:

* https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/installation/uninstall-infrastructure-agent/#disable-integrations

Which contains no information on how to manage your AWS services.

It should link here instead:

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/uninstall-infrastructure-integrations/#uninstall-aws

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/get-started/connect-aws-new-relic-infrastructure-monitoring/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.114
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks for letting us know, @djaffinito! I'll take care of it.
