### ISSUE TITLE
The Unified API team announced some Nerd graph changes today. that could impact teams using Nerdgraph.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#2918]
The changes announced in the #nerdgraph-announcements may not impact us at all, but we should do a quick check at what is changes and see if anything will impact us for our use of nerdgraph with the docs site. 

### Acceptance Criteria 

Go to `#nerdgraph-announcements`and review the 3 announcements from `7/1/21` There are links to blog posts that detail out the changes. `Note:` these posts are on Confluence, which not all teams have access to yet. to get access make a request in #ask-it 

Deadline for changes: `7/31/21`

- Stitched service error handling is now more transparent in Nerd Graph
- Announcing new error handling features in Nerd Graph for stitched services
- Action Required By All Teams: "downstreamResponse" is being removed from Nerd Graph error objects.
- The experimental tag is changing in Nerdgraph so we need to assess how this impacts us. in `#help-deven-websites`

- [x] Assess if these changes impact us in anyway and report findings and create the implementation tickets for `Sprint 8`

**Comment by aswanson-nr** [comment]
Both services we maintain that interact with NerdGraph do not use the `downstreamResponse` field, so there are no required changes.

The new client error messages could be worth implementing, but that would require work on our side. It could be worth looking into in the future.

**Comment by jpvajda** [comment]
@aswanson-nr what value is there in implementing the new client error messages? also, did you confirm if the experimental tag change impacts us?

**Comment by aswanson-nr** [comment]
@jpvajda, @LizBaker was able to remove the `experimental` flag from the GraphQL fields. 
The main benefit of the client error messages is that you can send an error message back for admins and one for the user. Allowing you to avoid exposing any stack traces to the user and ensuring that a developer can still debug problems.
