### ISSUE TITLE
workflow fails attempting to start a translation for document that doesnt exist

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#2931]
### Background
The current send translation content workflow / translation process allows for a doc to be queued up for translation, but not exist.

The scenario is:
1. a doc is edited. lets call it 'random.txt'.
2.  `random.txt` gets added to the translation queue.
3. before the next translation event (1st, 15th of every month) 'random.txt' is renamed (or deleted) to 'random2.txt'.
4. `random2.txt` gets added to the translation queue.
5. we will send `random.txt` and `random2.txt` for translation.

problem: we have a record in the translation queue which indicates 'random.txt' needs to be translated, but the document no longer exists.

### Acceptance Criteria

- [ ]  Don't attempt to translate the old file that was changed and only translate the new file. 
- [ ]  When sending things for translation, skip over documents that no longer exist.
- [ ]  Remove the record (from the translation queue) when a document is renamed or deleted.
- [ ]  Add tests for this scenario.

**Comment by jpvajda** [comment]
Curious wouldn't these files still need translation, regardless of the name change @nr-kkenney ? I also want to ask @jmiraNR about this case, perhaps there a way to ensure if a file name changes we updated the file in queue, so the translation workflow always has the most current file names regardless of how often they change.

**Comment by jpvajda** [comment]
Follow up question: in order to get our workflow enabled again, do these both need resolution first?

**Comment by jmiraNR** [comment]
A file name or location change should not impact the eligibility of a page.

**Comment by jpvajda** [comment]
@jmiraNR can you explain what "eligibility" means in this context?

**Comment by nr-kkenney** [comment]
@jpvajda renaming a file does not change the fact that it needs a translation, but we are running into an edge case in this process that causes the workflow to fail. 

to be clear, renaming a file "should" and most likely will result in the file being translated. to be more explicit about the problem, we are tracking known changed files so that we know what to translate. if a user edits a doc "doc1.txt" that will be saved, and on schedule, the workflow will look at that doc and send it for translation. 

the specific case we may hit is:
1. user edits "doc1.txt". now doc1.txt is queued up for translation.
2. user renames "doc1.txt" to "doc2.txt", or changes its path, or deletes it. in the case of renaming, doc2.txt is now queued up for translation.

but there is only one doc in the repository, doc2.txt -- doc1.txt no longer exists. so we think we need to translate two documents, but there is only one document that exists.

**Comment by jmiraNR** [comment]
We selected key pages to be localized based on their value. We _elected_ them to go through translation. Changing the file name does not change the value of the page.

**Comment by jpvajda** [comment]
> user renames "doc1.txt" to "doc2.txt", or changes its path, or deletes it. in the case of renaming, doc2.txt is now queued up for translation.

Then in this case, if we delete docs1.txt from the translation queue we should be go to go correct?

**Comment by nr-kkenney** [comment]
yep. that was one of the options i saw that i mentioned above.
