### ISSUE TITLE
[Gatsby Cloud] Loading a `-index` pages without a trailing slash results in UI errors

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#2933]
This seems to only occuring on pages ending `-index`

Without a trailing slash this page flashes a 404 before rendering improperly: 
https://docs.newrelic.com/docs/apm/apm-ui-pages/monitoring/view-your-applications-index

with a trailing slash all is well: 
https://docs.newrelic.com/docs/apm/apm-ui-pages/monitoring/view-your-applications-index/

### Related Issue

We fixed a very similar problem in this issue: https://github.com/newrelic/docs-website/issues/1014

### Cause

Amplify seems to treat this one type of page with`-index` in a weird way, and they drop the `/` 

### Acceptance Criteria 

- [x] any page URL that doesn't have a traiiing slash entered in the URL field should render a trailing slash and the page should appear as normal. 
- [ ] This will be resolved when we complete the docs site migration to Gatsby Cloud, so we just need to check to see if this is resolved.

**Comment by jpvajda** [comment]
Gastby Cloud does not do this, so once we move this will be resolved.

**Comment by aswanson-nr** [comment]
I have confirmed that this is no longer an issue when hosting on Gatsby Cloud.
