### ISSUE TITLE
Broken Link in: What is an entity in New Relic?

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#2935]
### Tell us what you need

Hi all, 

Found a broken link that leads to a 404 page. 

### Anything else you'd like to share?

Link exists in this section:

>An entity's GUID is reported as the attribute [entityGuid](https://docs.newrelic.com/attribute-dictionary/span/entityguid/). You can query for an entity using this attribute in the query builder.

Link: https://docs.newrelic.com/attribute-dictionary/span/entityguid/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/what-entity-new-relic/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.114
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for spotting this, @dlesniak-NR! I fixed the broken link in PR #2939.
