### ISSUE TITLE
Issue: Amazon VPC monitoring integration

### ISSUE THREAD

**Issue by DrMurx** [newrelic/docs-website#2940]
### Tell us what you need

The docs say that "By default, collection of VpcNatGateway, VpcVpnTunnel, and VpcVpnConnection data is disabled."

This can be easily missed, so I'd appreciate if it could be emphasized.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-vpc-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for the input, @DrMurx! See PR #2941 to see the requested changes.
