### ISSUE TITLE
Issue: Introduction to the Log API

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#2945]
### Tell us what you need:

* NONE of the Ingest APIs will tolerate data ingestion for data that is older than 48 hours. That is, if someone wants to forward a log that is older than 48 hours old (compared to the time of ingestion) then that log will be rejected. It will be rejected with a 202 error code. Despite the 202 code, the log file will not be written to NRDB. ]

Please update the docs to reflect the above. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.114
* **Device**: Unknown

**Comment by zuluecho9** [comment]
If this is true for all MELT APIs, might be something we add to all 'Data requirements/format' sections for each, if we're doing it for Log API. There should be pretty obvious places in those docs to place that info although it will vary a bit for each as the doc structure are a bit different.

**Comment by barbnewrelic** [comment]
ditto to zuluecho9: there was a conversation in the documentation channel yesterday about this very thing

**Comment by paperclypse** [comment]
I'm going to write up a Docs Jira for this, @dralph3344, so we can make sure we're addressing this in the right way.

**Comment by bradleycamacho** [comment]
@paperclypse Any status update on this issue?

**Comment by paperclypse** [comment]
I don't have an update. The last I did on this was to create a jira.

**Comment by austin-schaefer** [comment]
Closing out issues older than 90 days, feel free to re-open if anyone would like us to revisit this issue!
