### ISSUE TITLE
Slow page loads triggering alerts in APAC

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#2955]
We had an alert today on slow pages loads, a large percentage of which were occurring in Japan. we should investigate if there's anything we can do to mitigate this or if we need to adjust our alerts for slow load times out of our immediate control

Check out the page load times in NR `browser -> docs site -> summary` as well as session traces for july 2nd 3:30pm - 4pm pst

### Acceptance Criteria

- [x] time box research to evaluate what may have occurred
- [ ] report back findings and determine if there is any resolution we can take

**Comment by jpvajda** [comment]
@zstix to provide some pointers on what to research

**Comment by zstix** [comment]
Some possible things to look into:
* Was there any specific page(s) that attributed to the slow-down
* Was there any patterns / properties shared between the sessions (browser, location, etc.)
* Was there any outages during those times (aws, vendors, dns, etc)

**Comment by aswanson-nr** [comment]
## Findings
The majority of page loads over 6 seconds during the incident came from JP, HK, and KR. They were also all running Chrome 72 on linux. These requests were all for the base site (JP and EN) and the JP localized [alerts-best-practices](https://docs.newrelic.com/jp/docs/new-relic-solutions/best-practices-guides/alerts-applied-intelligence/alerts-best-practices). The average duration of these page loads ranges from 13.9s - 20s.

### Possible causes
1. Browser extension or outdated browser
   * The Chrome version being used for most of these requests is 72 and the current version is in the 90s. Each of these requests had a different session ID, but that could just be a single user with cookies blocked. 
   
2. Service outages
  * I could not find any references online to Amplify outages on the 2nd.

3. Serving from one region
   * We are currently only serving from one AWS region. Average load times in JP, HK, and KR are 1-3 seconds longer than in the US.


### Solution
I was unable to find an exact cause for this incident, but decreasing load times globally should prevent it from firing in the future. We can do this by deploying the site to more regions and optimizing our bundle. A first step in this direction would be creating synthetic checks for more regions, monitoring the page load times, and using that data to decide which regions to expand into.

**Comment by jpvajda** [comment]
@aswanson-nr nice research here! I'll defer to @zstix on reviewing the solution approach, and it sounds like this needs to be broken out into a new ticket for prioritization

**Comment by zstix** [comment]
After the thorough research and some discussion, we've decided that this is most likely a one-off situation. We've updated our alerts, but there doesn't seem to be any additional actions we can take. This may be even less relevant when we move to another hosting provider.
