### ISSUE TITLE
Broken Link: Introduction to the Kubernetes integration

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#2960]
### Tell us what you need

Hi all, found a dead link. If you click the link it adds "#metrics" to your URL but doesn't lead you anywhere different. 

### Anything else you'd like to share?

>In New Relic, you can build your own charts and query all your [Kubernetes data](https://docs.newrelic.com/docs/integrations/kubernetes-integration/get-started/introduction-kubernetes-integration/#metrics), which our...

Link in question found above

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/kubernetes-integration/get-started/introduction-kubernetes-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for noticing! I fixed it in PR #2961.
