### ISSUE TITLE
Issue: Troubleshoot AJAX data collection

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#2974]
### Tell us what you need

* With browser agent v1210 release, please see release notes below, Fetch calls will also be recorded as AJAX metrics, which will make them visible in the AJAX UI charts.

https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1210/

This means Fetch requests will show up in the Ajax Requests menu tab in the UI as well as queryable via Data Metric Explorer. 

### Anything else you'd like to share?

For more context: https://discuss.newrelic.com/t/relic-solution-ajax-request-data-in-browser-how-we-record-it-and-where-to-find-it/100847

I think the first dropdown at this documentation link needs to be reworked as the following two items are outdated. In this context, does this mean Browser Pro (the agent) or an old subscription? Either way, Ajax Request collection is available with both the Pro and Pro + SPA agents (not Lite). The Second bulleted item should now be reworded given the recent release. Fetch is support as mentioned below within event data (AjaxRequest events) and now also as Fetch metric data. 

* Browser monitoring: Other methods (including the newer Fetch API) currently are not supported when using browser Pro. 
* Single-page app monitoring: Fetch is supported for AJAX requests within a browser interaction with SPA monitoring. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/troubleshooting/troubleshoot-ajax-data-collection/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Thank you for reporting this! I've created a Jira so that our Observability tech writers can work with you to update the doc.

**Comment by bradleycamacho** [comment]
@barbnewrelic Can you provide an update on this issue and corresponding jira?

**Comment by barbnewrelic** [comment]
As noted in the comments, a Jira has been created for this. DOC-7177

**Comment by austin-schaefer** [comment]
Closing out issues older than 90 days, feel free to re-open if anyone would like us to revisit this issue!
