### ISSUE TITLE
Release workflow failing

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#2987]
It looks like there was a merge to main on Thursday that stalled and was restarted. The stalled run shows a failure for the Release workflow [here](https://github.com/newrelic/docs-website/runs/2967390698?check_suite_focus=true) with generic errors, but if you [look at the raw logs](https://pipelines.actions.githubusercontent.com/3WkJzDFeGWEk6Zei9RE9KFE0UTwsHx09RjPIYhekr3G7LkhigY/_apis/pipelines/1/runs/10646/signedlogcontent/3?urlExpires=2021-07-07T10%3A28%3A03.8831823Z&urlSigningMethod=HMACV1&urlSignature=wvWl3Ix6ct93IHiFtE2bxy8GNrVDsqSxnGpoPVDz6Lg%3D) it shows the workflow completed and created a new release successfully.

The stalling and restarting somehow ended up with 2 releases being created at the exact same time:

```
2021-07-01 17:31:55 +0000 release-219
2021-07-01 17:31:55 +0000 release-220
```

It looks like release-219 is deemed the more recent release which is resulting in the workflow now failing because it is fetching `219` as the most recent tag and trying to create `220` which already exists.

I've added a `while` loop to the workflow to mitigate this. It will check for the next available release number that doesn't already exist, it will keep adding `+1` to the release tag and checking it's existence. 

 - `release-(X)` - Latest Release
 - `release-(X+1)` - Already exists
 - `release-(X+2)` - Already exists
 - ...
 - `release-(X+n)` - Does not exist, available to create and tag

### Acceptance Criteria

- [x] confirm our approach with @austin-schaefer 
- [x] Simplify the logic of release numbering to reduce complexity. 
- [x] Convert format of the release tag from `release-xxx` to a Unix time stamp format such as: `release-mm.dd.yyyy-hour:min`
- [x] The release tag would then show as: `release-07.21.2021-09:35`
- [x] This change in time format doesn't need to be retroactively applied to past releases.

**Comment by nr-kkenney** [comment]
what is the scenario where a tag we want to use already exists? i think i understand the symptom, but im not quite sure i understand how this got out of sync in the first place.

the solution youve set up makes sense to me:
> I've added a while loop to the workflow to mitigate this. It will check for the next available release number that doesn't already exist, it will keep adding +1 to the release tag and checking it's existence.
but how is it we have releases that are above (potentially more than +1 above?) what we are trying to release

**Comment by jpvajda** [comment]
I've added acceptance criteria to change the time format per our discussion in standup, will review with @austin-schaefer for feedback.

**Comment by austin-schaefer** [comment]
That date+time format works for me!

**Comment by rudouglas** [comment]
@nr-kkenney ye that seems to only be due to the weirdness of both release tags getting created at the same time, which shouldn't have happened, and shouldn't even be possible 🤷 will implement the date-time format option so this shouldn't be any sort of issue going forward 🤓

**Comment by rudouglas** [comment]
I've change the release label to now be `release-mm.dd.yyyy-hour.min`  eg `release-07.21.2021-09.35` (`:` colon not an allowed char in tag) and the timezone to be PDT

**Comment by jpvajda** [comment]
@rudouglas NICE. 😎
