### ISSUE TITLE
Issue: WildFly installation for Java

### ISSUE THREAD

**Issue by shhudspethnr1** [newrelic/docs-website#2994]
### Tell us what you need

Hi, does there need to be a quote at the end of 

JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=$JBOSS_MODULES_SYSTEM_PKGS,com.newrelic

I am assuming yes. Could that be updated? Thanks. 

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/java-agent/additional-installation/wildfly-installation-java/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
@shhudspethnr1 Absolutely right! Thanks so much for letting us know. I'll get that fixed.
