### ISSUE TITLE
Finalize What's New on current site

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#30]
This is to track any remaining work related to supporting PLG's What's New / nr1-announcements content type on current site. This was work that began in March and was paused in May-ish. Most work is done, but remaining items include:
* tweak template/view for What's New content on docs site
* add JSON resource to support showing that content in NR1 Help Center
* ensure moderation workflow rules are as set

**Comment by jpvajda** [comment]
This particular issue is done, and there is a new one we can review with @roadlittledawn  when he's back. #703
