### ISSUE TITLE
Setup simple user feedback loop from Docs Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#300]
To capture feedback from users in early stages of the release of the Docs site we'll setup a simple feedback loop using github issues and later on look to align with the global New relic approach to capture user feedback. 

### Approach 

1. add a Feedback Button component to the each page on the docs site and display in  right rail (need to design input on placement)
2. setup a new issue type in GH called: ` positive feedback` that applies a label `+1 feedback`
3. setup a new issue type in GH called: ` negative feedback` that applies a label `- 1 feedback`
4. When a user interacts feedback button push the user through the GH issue flow to allow them to quickly file a feedback issue based on the sentiment they wish to report.
5. the thumb up would link the ` positive feedback` issue type and create the issue with the correct label.
6. the thumb up would link the ` negative feedback` issue type and create the issue with the correct label.

 7.  both the OSS Site and Dev Site should have this functionality as well.

**Comment by jpvajda** [comment]
To implement, we just need to know where the feedback CTA is going live on the new Site, Currently it's a feedback bar at the top of each page, which is a fine approach if we agree this works. @djsauble / @austin-schaefer 

![Screen Shot 2020-11-30 at 11 28 05 AM](https://user-images.githubusercontent.com/1395158/100649105-2d1f3000-32ff-11eb-94f4-bb104dc0f752.png)

**Comment by austin-schaefer** [comment]
Decided in our sync today that we'd put it in the right rail, @djsauble is gonna work out where the right place to incorporate it is.

**Comment by jpvajda** [comment]
@djsauble to provide a quick mock up of the placement of the feedback button

**Comment by jerelmiller** [comment]
@djsauble if you've got some time, I'd love to look at this with you.

**Comment by jpvajda** [comment]
@djsauble just need a design recommendation for this approach
