### ISSUE TITLE
Summarize your docs request

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#3005]
### How can we make our docs better?

What do you need?
------------------

When using the Rest API to create dashboards (Dashboard API), the column format defaults to 3 as was the previous layout conditions with Seldon/original UI/Insights API functions. Now, with New Relic One dashboards, the layout has a max 12 column format.

Because we are currently supporting both the original Insights functionality and the New Relic One platform, we have two systems and the issue is customers must include the attribute **"grid_column_count": 12** with their API calls to take advantage of that 12 column format in New Relic One dashboards. There have been a few Support tickets generated and we believe this would clear up confusion if we publicly include this instruction in the documentation.

Resources
---------

-   What we do have, is a Level Up in the community, though not all customers may be searching for this information here:\
    <https://discuss.newrelic.com/t/relic-solution-improving-compatibility-between-new-relic-one-and-the-insights-dashboard-api/100354>

-   It may be helpful to call this out in the Dashboard API docs here:\
    <https://docs.newrelic.com/docs/insights/insights-api/manage-dashboards/insights-dashboard-api#>

-   New doc is here <https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/dashboards-api/>

-   Please see GTSE-4605 Jira for more reference

Action items
------------

1.  Research this specific attribute ("grid_column_count":12)

2.  Figure out where to put new relevant information. Likely a dashboards doc?

3.  Work with SMEs to draft contact

4.  Peer edit

5.  Publish and contact Cheryl

### Jira migration info

Migrated from Jira DOC-6143

**Comment by bradleycamacho** [comment]
@austin-schaefer Could you update the title? Thanks!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
