### ISSUE TITLE
A link is 404-ing for some users and not others

### ISSUE THREAD

**Issue by LizBaker** [newrelic/docs-website#3006]
### Description

This link https://docs.newrelic.com/docs/full-stack-observability/instrument-everything/instrument-core-services-applications/open-source-telemetry-integrations/
results in a 404 for some users and not others (at least 4 other users including @rhetoric101). When it does occur it's in every browser

### Impact

- So far this impacts 4 Docs Team members, but can't be reproduced by DevEn on 3 different machines

### Steps to reproduce

1. Follow this link https://docs.newrelic.com/docs/full-stack-observability/instrument-everything/instrument-core-services-applications/open-source-telemetry-integrations/
2. Possibly witness a 404

### Expected behavior

The link redirects to https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/

**Comment by roadlittledawn** [comment]
this may have been related to our hosting. i'm not seeing this behavior anymore. if it crops up again, we can revisit
