### ISSUE TITLE
Synthetics Multiple Location Condition API is not listed on the REST API for Alerts Doc

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#3009]
### How can we make our docs better?

Synthetics Multiple Location Condition API is not listed on the REST API for Alerts Doc.\
<https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/rest-api-calls-alerts#synthetics-conditions>

The related doc is [here](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/multi-location-synthetic-monitoring-alert-conditions#api), if the entry could include cURL examples like the other items that would be great.

**Resources**

-   The REST API Explorer for Synthetics multiple location condition API <https://rpm.newrelic.com/api/explore/alerts_location_failure_conditions/create> ("Alerts Location Failure" = "Synthetics Multi-Location")
-   [slack thread linked from jira with more info from SME]

### example cURL command

```
curl -X POST 'https://api.newrelic.com/v2/alerts_location_failure_conditions/policies/{policy_id}.json' \
     -H 'X-Api-Key:<SNIP>' -i \
     -H 'Content-Type: application/json' \
     -d \
'{
  "location_failure_condition": {
    "name": "string",
    "runbook_url": "string",
    "enabled": "boolean",
    "entities": [
      "string"
    ],
    "terms": [
      {
        "priority": "string",
        "threshold": "integer"
      }
    ],
    "violation_time_limit_seconds": "integer"
  }
}' 
```

### Jira migration info

Migrated from docs jira DOC-6460

**Comment by rhetoric101** [comment]
I am closing this issue since it was addressed in PR #5464.
