### ISSUE TITLE
Issue: Java agent configuration: Config file

### ISSUE THREAD

**Issue by StacySimmons** [newrelic/docs-website#3018]
Conflicting information about JFR profiling needs a resolution, please.

Java release notes state JFR profiling is enabled by default: [Java Agent 7.1.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-710/)

Docs state JFR profiling is disabled by default: [JFR Real-time profiling](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file/#jfr-real-time-profiling)

**Comment by urbiz-nr** [comment]
Thanks for catching this, @StacySimmons, we'll have a look!

**Comment by paperclypse** [comment]
I reached out to @StacySimmons on Slack about this, because I had a question about it.

**Comment by paperclypse** [comment]
Looks like this one got taken care of already. :)
