### ISSUE TITLE
404 Page missing

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#3027]
Hey there! While looking on the developer site for Nerdpack config information, I came across [this section](https://developer.newrelic.com/explore-docs/nerdpack-file-structure/#launcher-file-structure) that talks about the launcher file structure. That section includes a link called "associate your application with a monitored entity" to this doc, but unfortunately this page is missing. Not sure if the page got renamed and didn't get a redirect, or if it lives somewhere else, but I'd love to have it!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/build-new-relic-one/new-relic-one-application-nerdpack-file-structure/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.114
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
@jerelmiller Sorry this fell through the cracks! I'll take a look at this this week.

**Comment by bradleycamacho** [comment]
@jerelmiller This one is a bit more complicated than it seemed at first glance. It seems that the doc never made it's way over from drupal either as an error from the migration (unlikely) or because we deleted the doc prior to the migration (more likely).

Still hunting this down.

**Comment by zuluecho9** [comment]
Fixed this https://github.com/newrelic/developer-website/pull/1529
