### ISSUE TITLE
Issue: Query the Metric data type

### ISSUE THREAD

**Issue by thezackm** [newrelic/docs-website#3030]
### Tell us what you need

The NRQL example listed [HERE](https://docs.newrelic.com/docs/telemetry-data-platform/understand-data/metric-data/query-metric-data-type/#example-list-names-host) doesn't actually match the stated goal of the section. It is a query for limiting the results of a query based on `average`; but it's listed as being a way to query for all metric names on a particular host.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/understand-data/metric-data/query-metric-data-type/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hey @thezackm, thanks for filing the issue! Do you think it would be better to update the NRQL query to match the text that's there or update the text to match the NRQL query?

**Comment by thezackm** [comment]
i think it makes sense to achieve the goal of the text that is there (update the NRQL to match)

**Comment by zuluecho9** [comment]
@dbarnesbrownNR might be in your wheelhouse

**Comment by zuluecho9** [comment]
I created a jira to look into this and some related getField issues, FYI: DOC-7186.

**Comment by bradleycamacho** [comment]
@dbarnesbrownNR @zuluecho9 Could you two please take a look and post the status of this issue? Thanks!

**Comment by dbarnesbrownNR** [comment]
@bradleycamacho @zuluecho9 there is a docs ticket but it keeps getting bumped for critical product work. Should be able to pull in to next sprint and is currently in the backlog for that sprint.
