### ISSUE TITLE
Java Agent with Docker: The reference to JAVA_OPTS is Tomcat-specfic and should be broader

### ISSUE THREAD

**Issue by Broseberg** [newrelic/docs-website#3045]
Description
-----------

We received a CSAT comment (28384) about our [Java agent in Docker|<https://docs.newrelic.com/docs/agents/java-agent/additional-installation/install-new-relic-java-agent-docker>\
] document:

"This doc is misleading because it is Tomcat-specific and it's easy to miss where it states such. Instead, it should be changed to recommend JAVA_TOOL_OPTIONS since that is picked up by most JVMs by default, instead of JAVA_OPTS which is not picked up by any JVMs by default. More info here: <https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts>"

Tech writer tasks:

-   Post a comment in the java-agent Slack channel asking if/how we should correct this.

-   Find other references to JAVA_OPTS and see if they are appropriately Tomcat-specific.

-   Make the changes.

-   Get a review by a subject matter expert.

-   Get a peer review, if necessary.

-   Publish

*Jira migration info*
Migrated from jira DOC-5706

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
