### ISSUE TITLE
Add harvest limit settings to Python agent config doc

### ISSUE THREAD

**Issue by Broseberg** [newrelic/docs-website#3046]
Description
-----------

While working on a related doc, I noticed that the [Python Agent Configuration doc](https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration "https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration") is missing definitions for harvest limit settings. These settings allow you to adjust the maximum number of events sent per harvest cycle. Similar settings are documented in a number of other agent config docs, but they are specifically missing for Python.

The hero in #python-agent (Loren Arthur) said that the documentation for these settings was originally omitted to avoid abuse, but he also noted that this thinking may have changed. Currently, we *want* customers to send in more of their data.

Resources:
----------

-   Rebecca Rodriguez, PM

-   Hero in #python-agent or #gts-python channels

-   Slack Thread for more context: <https://newrelic.slack.com/archives/C0511NL6X/p1592332236371400>

Action Items:
-------------

-   Check with PM Rebecca Rodriguez to see if adding the definitions would make sense.

If given the okay:

-   Ask an SME for definitions of the harvest limit settings.

-   Add definitions to the [Python agent config doc](https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration "https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration").

-   Add hyperlinks to the definitions where those settings appear in [this troubleshooting doc](https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/agent-nrintegrationerrors-appear-insights "https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/agent-nrintegrationerrors-appear-insights") (under the Python solution).

-   Peer edit.

-   Publish.

Migrated from JIRA
-------------

Migrated to GitHub from DOC-5769

**Comment by Broseberg** [comment]
The four settings in question:

-   for transaction events:

    `1event_harvest_config.harvest_limits.analytic_event_data`

-   for custom events:

    `1event_harvest_config.harvest_limits.custom_event_data`

-   for span events:

    `1event_harvest_config.harvest_limits.span_event_data`

-   for error events:

    `1event_harvest_config.harvest_limits.error_event_data`

**Comment by urbiz-nr** [comment]
This has been already documented.
