### ISSUE TITLE
Unclear OpsGenie payload for Incident intelligence

### ISSUE THREAD

**Issue by Broseberg** [newrelic/docs-website#3047]
Description
-----------

The IINT docs are inconsistent. The "webhook format and JSON example" section implies to be listing the fields available for the template but there are fields in the examples, like ui_name in the suggested OpsGenie template that aren't listed here. ui_name IS in the issue payload, which makes us think we can use other values in the issue payload but nothing in the docs says that's supported. The documented list of variables also mentions things like "incidents" which isn't in the issue payload. So it is unclear how much is available from the actual issue payload or if we should only be using the documented fields.

This is the doc in question: <https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/incident-intelligence-destination-examples>

Docs should at least be updated as follows:

1.  The list of supported fields should be updated to include all fields that are supported, including ui_name. If all fields from the issue payload are supported, it's probably safer to just say that and provide verbiage on how a user can see that payload in the UI (clicking the button on the issue).

2.  If all fields from the issue payload are supported, then an explanation should be provided as to why there is an explicit list given and when it is different or what is available in that list, like "incidents", that is not in the issue payload.

3.  If ui_name is not supported, then the OpsGenie example payload (and any others) should be updated to not show variables that aren't supported.

**Migrated from Jira**

This is from two tickets here: DOC-6151 and DOC-6125

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
