### ISSUE TITLE
csat feedback: Check Infrastructure on Elastic Beanstalk feedback from a user

### ISSUE THREAD

**Issue by Broseberg** [newrelic/docs-website#3048]
Description
-----------

on this page: [Configure the infrastructure agent on AWS Elastic Beanstalk](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-aws-elastic-beanstalk "https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/config-management-tools/configure-infrastructure-agent-aws-elastic-beanstalk")

Find out if this feedback is correct and if so, update the page with the correction:

> The path to the agent repo only works for Amazon Linux and not Amazon Linux 2. Had to go to the Linux Installation section to find out that the correct agent to use for Elastic Beanstalk with Linux 2 is located in the el/7 directory and not the el/6 directory like this documentation says.

Action items:\
1\. Find an SME.\
2\. Get the appropriate link.\
3\. Update the doc.\
4\. Publish.

**Migrated from JIRA**
From DOC-6147

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
