### ISSUE TITLE
[CSAT] Improve "Node.js: Configure with Winston" logs doc

### ISSUE THREAD

**Issue by Broseberg** [newrelic/docs-website#3049]
Description
-----------

<https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/logs-context-nodejs/nodejs-configure-winston> has two negative comments in less than a month:

-   Nov 25, 2020 11:09: make it more explicit that `Distributed tracing` is needed

-   Nov 20, 2020 19:14: the "Configure the Winston extension" doesn't provide a full example

Action items:
-------------

-   Get in touch with Node.js team to sync on how to improve doc

-   Draft

-   Validate with SMEs

-   Get peer edit

-   Publish

**Migrated from JIRA**

Migrated from DOC-6338

**Comment by barbnewrelic** [comment]
See CF-10298
