### ISSUE TITLE
Browser DT docs need update with TraceContext info

### ISSUE THREAD

**Issue by Broseberg** [newrelic/docs-website#3050]
The "Browser data in distributed tracing" doc talks about the custom newrelic header. It should also include TraceContext headers, which are now supported by the Browser agent and customers can choose which headers to use.\
<https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing>

**Migrated from JIRA**

Migrated from DOC-6414

**Comment by Broseberg** [comment]
Additional comment from JIRA ticket:


I'm not sure if this is part of this request, but it looks like the public docs may be misleading a bit as currently the above link mentions:

1.  *Turn on the **Distributed tracing** toggle. By default, for agent version 1173 and above, the newrelic, traceparent, and tracestate headers will be added to all same-origin AJAX requests.*

2.  *Optional: If all of your services are configured to use the w3c trace context headers, you can choose to exclude the newrelic, traceparent, and tracestate headers from requests.*

I thought the traceparent and tracestate headers were W3C so if you exclude these, you would have no headers being sent? Blog post here:

[![](https://newrelic.com/themes/custom/curio/assets/images/metadata/apple-touch-icon.png)Announcing New Relic Support for W3C Trace Context: Now Available in New Relic APM](https://newrelic.com/blog/nerdlog/w3c-trace-context-distributed-tracing-standard)

W3C Trace Context defines a pair of standardized context HTTP headers that serve to propagate context correlation information between services:

-   A traceparent header contains the data elements that every distributed tracing model requires to define and propagate context: a trace ID, a parent ID, and a sample flag.

-   A tracestate header holds vendor-specific, contextual data, typically in order to support additional functionality or optimizations associated with a particular tracing tool.

**Comment by CherylFrankenfield** [comment]
@barbnewrelic Thank you! @Broseberg And thank you! You are correct. 

We should update to clarify: 

_Optional: If all of your services are configured to use the w3c trace context headers, you can choose to exclude the newrelic header from requests._
