### ISSUE TITLE
Error example missing from the Synthetics Troubleshooting Doc

### ISSUE THREAD

**Issue by Broseberg** [newrelic/docs-website#3051]
Description
-----------

There is a Network error that is reported by Synthetics Monitors that there is no entry for in the Synthetics Troubleshooting Doc:

<https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/troubleshooting/non-scripted-monitor-errors>

`1NetworkError: Connect to (HOST) [HOST./IP ADDRESS] failed: SSL handshake timed out`

**Resources**

-   Slack channel: #help-proactive-monitoring

**Action items**

1.  Reach out to the Synthetics Minion engineering team in their slack channel about this network error. (Find a SME, basically.)

2.  Get some information about what causes this error.

3.  Add this network error to this doc.

4.  Get a peer edit.

5.  Publish.

**Migrated from JIRA**

Migrated from DOC-6461

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
