### ISSUE TITLE
"Types of conditions" section leaves a lot out, and one heading isn't even a condition type

### ISSUE THREAD

**Issue by Broseberg** [newrelic/docs-website#3053]
Doc in question: <https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-alert-conditions#condition-types>

Notice that some of the headings are subtypes of other headings or subtypes with no heading for the main type (e.g. NRQL alert conditions and Outlier alert conditions, the latter is a subset of the former), some headings don't do the topic justice (e.g. Infrastructure alert conditions have many types -- there are Process Running conditions which aren't covered, Infra Metric conditions, and the many types of Integration conditions, both on-host and cloud-based), some conditions types simply have ... nothing at all (e.g. External Services alert conditions, APM Metric alert conditions) and one heading is actually not a condition type at all (<https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-alert-conditions#dynamic-targeting-labels)>.

This list should be a comprehensive breakdown of all possible alert condition types.

Note: Given that we’re going to have to explain how to migrate each of these condition types, and it’ll be different for every one, I think we need to have a place for every one

If I have an External Services alert condition, I’m not going to look up NRQL conditions to figure out how to migrate my External Services alert condition. I’m going to try to find something in the docs about External Services conditions, and hope that there is some information there.

Even if it’s only a brief explanation of the condition type as part of a comprehensive list, we would at least have a place where we could link to some migration instructions (which would presumably be in a different part of the docs than the comprehensive list of alert condition types).

**Migrated from JIRA**

Migrated from DOC-6575

**Comment by HenryTech** [comment]
All condition types are being folded into NRQL within the next 9 months or so, and we plan to include migration tools in the UI to handle both UI- and API-driven changes.

**Comment by bradleycamacho** [comment]
@Broseberg closing this based on @HenryTech's thoughts. Let me know if you think we should re-open!
