### ISSUE TITLE
PageHide metric is missing in data dictionary for PageViewTiming event types

### ISSUE THREAD

**Issue by retishp** [newrelic/docs-website#3062]
### Tell us what you need

PageHide metric is missing in data dictionary for PageViewTiming event types
https://docs.newrelic.com/attribute-dictionary/?event=PageViewTiming

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
@retishp Thanks for reaching out. I've requested a definition from the product team and will update this shortly. Thanks!

**Comment by zuluecho9** [comment]
I'm looking into this, taking it off Bradley's hands.

**Comment by zuluecho9** [comment]
Solved in https://github.com/newrelic/docs-website/pull/3632.
