### ISSUE TITLE
Header buttons should automatically copy the anchor link to your clipboard

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#3071]
Currently, the anchor link buttons that appear when you hover over a header just make the URL point to the anchor link:

![image](https://user-images.githubusercontent.com/42678939/125359863-cf84a480-e31f-11eb-92ef-6bc45810e1d5.png)

The expected action when clicking to button is for it to copy the link to the header (doc url + anchor id) directly to my clipboard.

We should also show a message indicating it's been copied, similar to the copy button behavior:

![image](https://user-images.githubusercontent.com/55203603/125360344-9698ff80-e320-11eb-873d-15599b626bea.png)

**Comment by jpvajda** [comment]
This gets me every time as well. good suggestion 😄

**Comment by LizBaker** [comment]
We're using gatsby-remark-autolink-headers for our header linking/scrolling magic. It has a few props for customization but I can't find a way to incorporate a click event for copying. We might be able to PR the plugin but otherwise seems like we would have to write this functionality from scratch (not use the plugin) if we want a copy option

**Comment by jpvajda** [comment]
@LizBaker I'd be 💯  onboard to PR the plugin.

**Comment by jpvajda** [comment]
moving back to backlog as we are blocked due to plugin limitations.

**Comment by bradleycamacho** [comment]
Removing the stale label as it'd still be great to do this eventually when DevEn isn't being pulled in every direction possible!

**Comment by austin-schaefer** [comment]
Adding the `ui-ux-audit` label here, this would be a really great known issue to fix as part of that cleanup

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-9
