### ISSUE TITLE
Create a new relational DB to store pages and workflow jobs

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#3074]
## Description
The current Database for storing the translation workflow state is _non-relational_ (more specifically, it's a DynamoDB table). After realizing a single page may be in multiple jobs, we realized that we need a different database structure that can better support many-to-many relationships. Additionally, the information we're storing is relational in nature and may benefit from a relational database (e.g. RDS).

## Strawman Schema ™️
```
pages          pages_jobs    jobs
-------        ----------    ----
id ----------> page_id   .-> id
slug           job_id --/    job_uid
date_modified                batch_uid
                             status (enum)
                             locale (enum)
                             date_created
                             date_modified
Status (enum)
-------------
PENDING
IN_PROGRESS
IN_REVIEW
COMPLETE
```

## Acceptance Criteria
* [x] Decide on a database schema that meets our needs for storing the state of jobs _and_ pages
* [x] Create a new database in AWS
* [x] Create tables for pages, jobs, and any supporting tables needed
* [x] Create new utility functions for querying the database
* [ ] Add any additional secrets to Github environment

**Comment by aswanson-nr** [comment]
@nr-kkenney We may want to include the status of each page from the Github API as well, that way we can track when a file is deleted
