### ISSUE TITLE
Update workflow that handles completed translations (& making a PR)

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#3078]
## Description
Once we have a new database and utility functions for reading / writing to it (#3074), we need to update [the workflow](https://github.com/newrelic/docs-website/blob/main/.github/workflows/check-translations-and-deserialize.yml) that checks for the job status, downloads the new files, and makes a PR.

Much of the existing workflow should stay the same (deserializing, making the PR, etc).

## Needs Further Clarification
At some point in the workflow (and perhaps it is at this point), we need to remove any localized files that correspond to english files that were deleted (in PRs spawning this process). How we handle this is still unclear to me (-Z).

## Acceptance Criteria
* [x] Check the job status given a job ID in the new database
* [x] If a job has been completed, download the files, deserialize them, and make a PR
* [x] Update the job status in our database to be "in-review" (or something similar)
* ~Come up with a solution for english files that were deleted in the PRs related to these files (see above)~

**Comment by aswanson-nr** [comment]
Some ideas on deleted files, if we store deleted files in the translation db with a status like `DELETED`, then when we pull all the files from the translation vendor we can also pull all db file entries associated with that job. Files from the db with the `DELETED` status can then be removed and committed as part of the normal PR.

**Comment by zstix** [comment]
I'm going to close this out, since the last acceptance criteria will be handled by a process (for now) and engineering work in the future. Here's that future work ticket: https://github.com/newrelic/docs-website/issues/2749
