### ISSUE TITLE
Issue: Types of synthetic monitors

### ISSUE THREAD

**Issue by quirosfelipe** [newrelic/docs-website#3086]
### Tell us what you need
 To add a link here that redirects to  a page where we can start buildinga page  to see more info about  Step monitors:
Some things to include: 

- Propper syntax to target elements by xpath, id and class. Some examples will be also useful to have.
- Unsupported elements (i.e. shadow root element)
- How to propperly handle secure credentials
- Currently unsupported funcionalities in step monitors (i.e. switchTo().frame() is unsupported)

### Anything else you'd like to share?
https://newrelic.zendesk.com/agent/tickets/462260 
https://newrelic.zendesk.com/agent/tickets/457360
https://newrelic.slack.com/archives/C7HGFUXMH/p1623344976159400

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/types-synthetic-monitors/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.77
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey @quirosfelipe, thanks for reporting this! A stand-alone step monitor doc is something that has been on my mind lately, and this is a nice push to start work on it.

I'll set up some time to chat about specific issues GTS is observing with users and then I'll include this issue in an upcoming sprint.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
