### ISSUE TITLE
Fully document the translation workflow process on our Docs Site WIKI

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3092]
We have a really good internal document about how our Translation workflows actually work and we want to document that on our site WIKI so it's visible and easy to find. 

### Acceptance Criteria

- [x] Resolve all the issues in this ☔ https://github.com/newrelic/docs-website/issues/2655
- [x] Review the internal doc found on `G-Drive` Localization: How it works
- [x] Update our Site [WIKI](https://github.com/newrelic/docs-website/wiki/Translation) with updated technical documentation 
- [x] Use the term for `Translation Management System (TMS)` for vendor specific terminology
- [x] Add a note to internal document that it is no longer the source truth

**Comment by rudouglas** [comment]
I've written out what we currently have in the Doc here https://github.com/newrelic/docs-website/wiki/Translation-Workflow

**Comment by jpvajda** [comment]
We decided to document this functionality externally and mark the internal doc as no longer being maintained. I'll update that doc, and point readers to the WIKI page.

**Comment by jpvajda** [comment]
@nr-kkenney can do a final review and mark it done...

**Comment by nr-kkenney** [comment]
looks good to me. closing.
