### ISSUE TITLE
Issue: Install the Node.js agent

### ISSUE THREAD

**Issue by linbaker** [newrelic/docs-website#3094]
### Tell us what you need

Currently, step 5 of the installation says:

`Add require('newrelic'); as the first line of your app's main module.`

This does work, but many Node.js users compile/transpile their JavaScript and can't control the final require order or have confusion on where to place this require statement. In these cases, the work around is to load the `newrelic` module in the start script with the [Node command line option -r](https://nodejs.org/api/cli.html#cli_r_require_module). For example, the start up script would look like `node -r newrelic ./dist/server.js`. Then requiring or importing the 'newrelic' module in the application code is only necessary when using the API. 

While both methods work, the `-r` installation method is more reliable. Last month, over 30% of tickets had an instrumentation issue that was resolved by switching from using `require('newrelic');` to load the agent to `-r newrelic` in the start script.

This is a documented work around in the agent Github README:

* https://github.com/newrelic/node-newrelic#:~:text=if%20you're%20compiling%20your%20javascript%20and%20can't%20control%20the%20final%20require%20order%2C%20the%20node.js%20agent%20will%20work%20with%20node's%20-r%2F--require%20flag.

This is also the method guided install uses so it is well documented/tested. 

We discussed this in GTS/Engineering pairing, initially the thought was to include this as an alternate install method and use the same verbiage as the agent README that states what situations you should use `-r newrelic` and that every other situation you should use `require('newrelic');`. But since this is such a common issue and it is a well tested and documented 'workaround', the consensus was that we should offer the `-r newrelic` method as the primary install method with `Add require('newrelic'); as the first line of your app's main module.` as an alternative if customers are not able to use `-r newrelic` in their start script. 

Potential verbiage:

Add `-r newrelic` to your start script to load the agent with the [Node command line option -r](https://nodejs.org/api/cli.html#cli_r_require_module). For example, the start up script would look like `node -r newrelic your-program.js`.

### Anything else you'd like to share?

Since this is a change to crucial Node.js agent docs, approval from Node.js PM may be needed. Node engineering team and support team are familiar with this request so reach out to #gts-nodejs or #node-agent with any questions! Thank you Docs Team!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.114
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Thanks for reporting this so thoroughly! I'm creating a Jira for your issue so a writer can work directly with your team to update the doc and get the right approvals.

**Comment by bradleycamacho** [comment]
@barbnewrelic Can you update the status of this issue?

**Comment by barbnewrelic** [comment]
As noted in the comments, a Jira has been created for this. DOC-7178

**Comment by tytyhibye** [comment]
@barbnewrelic the JIRA for this has been closed so this GitHub issue is now a standalone. The Node documentation for adding this to the installation instructions has not been updated to reflect adding this startup script. Please have someone from your team reach out to me in Slack to collaborate on this! Thank youuuuu

**Comment by barbnewrelic** [comment]
@tytyhibye  We don't have an assigned writer to this request just quite yet. In the meantime, you can always edit the doc yourself so we are not a roadblock to your team. Hopes this help!

**Comment by tytyhibye** [comment]
@barbnewrelic it does thank you very much! I've put in the PR for the update on the install docs.
