### ISSUE TITLE
Gif Shows Wrong Clip

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#3095]
### Tell us what you need

The gif on this page shows editing the aggregation window and evaluation offset. While the lost signal threshold is visible in the video, I think this could be confusing. The actions of the gif should focus on the lost signal threshold

### Doc information (don't delete this section)

* https://docs.newrelic.com/whats-new/2020/10/alerting-loss-signal-detection-configurable-gap-filling-strategies/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey @dlesniak-NR, since this is for an announcement post almost a year old I'm going to close this issue. 

Regardless, thanks for reporting this issue - we really appreciate it! If you believe this is a higher priority and should not be closed, feel free to reopen it and ping me.
