### ISSUE TITLE
Alerts (Webhook Payload): Improve JSON example

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#310]
This is from a CSAT request: [NEW RELIC ONLY LINK] [https://docs.newrelic.com/node/5726/submission/141051](https://docs.newrelic.com/node/5726/submission/141051)

Here is the page where the user has problems: [https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/customize-your-webhook-payload](https://docs.newrelic.com/docs/alerts/new-relic-alerts/managing-notification-channels/customize-your-webhook-payload)

Here's what the user wants:

> The sample JSON in this doc doesn't work with the endpoint supplied by PagerDuty, which is [https://events.pagerduty.com/integrations/<api-key](https://events.pagerduty.com/integrations/%3Capi-key)\>/enqueue. It's missing a "source" field and a "summary" field, for one; even with those, the endpoint returns a 200 but it doesn't actually process a test notification. 
> Also, you might want to move that comment "example of a custom variable" out of the JSON sample; it is "below the fold" of the textarea and the hapless engineer is likely to copypasta their way into a broken situation with invalid JSON. You could just change that line to "my\_custom\_field": "My Custom Value"

## Action items

1. Figure out if the "source" and "summary" fields are required.
2. Reformat the example at the end of the JSON using <var\> tags and remove the comment.
3. Publish the doc.

## Jira migration details

This issue was migrated from the internal DOC jira project:

* Original reporter: @rhetoric101
* Jira ticket ID: DOC-5580
* Original priority: High
* Original component: Experience Debt
* Original product group: AI

**Comment by paperclypse** [comment]
I've removed the comment from the JSON webhook example. I've reached out to GTS to confirm that "source" and "summary" are valid fields that should be documented.

**Comment by austin-schaefer** [comment]
Closing out issues older than 90 days, feel free to re-open if anyone would like us to revisit this issue!
