### ISSUE TITLE
Attribute dictionary >  Navigation and table header change

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#3101]
Sorry if this is more a request for docs team; I'm actually not sure myself how to edit these things so I thought maybe it was a better eng request. 

This was meant to be done a while back but think it got missed. On the data dictionary page, when viewing an attribute entry (like https://docs.newrelic.com/attribute-dictionary/?event=AjaxRequest&attribute=appId), we want the right side column to read 'Data types' and not 'Events'. This is because we attempt to differentiate between our event data and the other MELT data types (Log, Metric, and Span). You'll see how we already changed this on far right, how it says 'Data types' now for dropdown instead of 'Events', so we need to follow up on this one, too. 

Another thing just noticed: top left of data dictionary page: we should change it to 'Data dictionary' and not 'Attribute dictionary'.

**Comment by jpvajda** [comment]
both are fairly simple changes if you know where to look, however the changing of the name from `Attribute Dictionary` to `Data Dictionary` does have some repercussions to consider as not only would you be changing the nav name you'd also be changing the path. See [this file](https://github.com/newrelic/docs-website/blob/b58059c2a696f736857460abe5b47fb5eb233812/src/nav/attribute-dictionary.yml)

For the change from `Events` to `Data Types` that code can be [found here](https://github.com/newrelic/docs-website/blob/2cfcdd3d486bced25a98dec208144e0965260e60/src/pages/attribute-dictionary.js#L276)

Our team is currently focused on a very high priority project, so if someone on the docs team wants to tackle these changes feel free and our hero can help out if you get stuck.

**Comment by zuluecho9** [comment]
@jpvajda I guess that's why I wanted a little help, because there are some gotchas. For more context: we refer to this thing as the 'data dictionary' so it'd be nice if it could display as 'Data dictionary' on the left, as the 'attribute dictionary' might be a bit confusing. And us changing the url to 'data-dictionary' would be fine also; that way we could just redirect the old 'attribute' URL to that one, don't you think? I realize it's not that pressing though, but if it's easy to do, maybe we can do that soon. 

I'll see if I can do the 'events' to 'data types' change.

**Comment by zuluecho9** [comment]
While we're at it, could we change the entry on the home page to 'Data dictionary'? I realize this is theoretically something docs team could do, but I think how the home page generates these may be related to the underlying files in some way, so I thought it made sense to have you all do it all at once. 
<img width="367" alt="Screen Shot 2021-07-26 at 7 36 43 AM" src="https://user-images.githubusercontent.com/9435570/127007770-78cde6d3-b910-4e37-a635-3898243c4956.png">

**Comment by bradleycamacho** [comment]
@zuluecho9 Could you take a look at this issue and make sure it's still relevant? 

@jpvajda Doesn't seem like this is a priority, but maybe this is something one of those new incoming SEs could knock out early on? Thanks!

**Comment by jpvajda** [comment]
@roadlittledawn 👋  --> TPM life. 😉

**Comment by zuluecho9** [comment]
@bradleycamacho yes, still relevant and be nice to have.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
