### ISSUE TITLE
Issue: Language agents and distributed tracing

### ISSUE THREAD

**Issue by jake-codes** [newrelic/docs-website#3102]
Hi, I'm looking for documentation to provide my customer on how to configure (both enable and disable) distributed tracing for their apm agents in kubernetes. It's a bit difficult to find this information in the docs.

The links from [this page](https://docs.newrelic.com/docs/distributed-tracing/enable-configure/language-agents-enable-distributed-tracing/), push users back into the guided install without any mention of Distributed Tracing. It's not clear if this is because Distributed Tracing is turned on by default with Guided Install, or if this is a mistake. Even if it is turned on by default, pushing to the guided install without an explanation is confusing for the user.

Can we please take a look at the user flows for docs related to setting up apm distributed tracing (in particular when they are in kubernetes and would need a Dockerfile change) to make the process more clear?

**Comment by bradleycamacho** [comment]
Hey @jake-codes, thanks for filing this issue! Userflows are something that have been on our mind a lot lately, and this is a great call out for an area we can improve. I'll explore some options and file a few follow-up internal tickets to work on this area in the next sprint or two.
