### ISSUE TITLE
Clarify an undocumented Sum Of behavior

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#311]
## What do you need?

There is a behavior regarding the "sum of query results" function that is not documented. This is the affected doc:

[https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions\#sum](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions#sum)

While this function is meant to be used for datasets that report infrequently, there is an issue if the dataset is _too_ sparse.

Specifically, we require at least two data points spanning the width of the threshold in order for us to evaluate your data. Engineering describes it like so:

> The sum function handles gaps, but it requires data that spans \>= the duration it's summing over. So for a duration of 59 minutes, it would need at least 2 data points, 1 to start the buffer and another occurring at or after 59 minutes to satisfy the duration. To further complicate things, buffers expire after 30 minutes of no data, so even if you take into account customer data that comes in later than this 59 minute duration (in this case hours later), the buffer will have expired and we start a new one and are back in the original state.

This "quirk" has driven support tickets as this information isn't known publicly.

## Resources

See engineering's response in this GTSE:

[https://newrelic.atlassian.net/browse/GTSE-311](https://newrelic.atlassian.net/browse/GTSE-311)

## Jira migration details

This issue was migrated from the internal DOC jira project:

* Original reporter: Tech Support
* Jira ticket ID: DOC-6158
* Original priority: Medium
* Original component: Experience Debt
* Original product group: GPE

**Comment by founddrama** [comment]
@austin-schaefer This is probably not worth fixing given that "sum of" conditions are being EOL'ed (sources [here](https://discuss.newrelic.com/t/big-news-for-alerts-and-applied-intelligence/161436) and [here](https://discuss.newrelic.com/t/end-of-life-for-sum-of-query-results-thresholds/177975))

**Comment by austin-schaefer** [comment]
Closing out issues older than 90 days, feel free to re-open if anyone would like us to revisit this issue!
