### ISSUE TITLE
Java agent: Good trick for setting complex environment variables

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#312]
## What do you need?

Our Java config doc says that certain configuration settings cannot be set using an environment variable. For example, transaction\_events.custom\_request\_headers or error\_collector.expected\_messages. From the doc:

> Unlike other settings, custom\_request\_headers have to be paired together and must be set in the newrelic.yml file. They can't be overwritten by Java virtual machine arguments (system property) or environment variables.

Most of these settings are tagged with the line **Cannot be specified by system property.**

However, it turns out that this is not strictly true. A developer on the Java team gave me a trick. You _can_ set these settings using an environment variable, if you format the value as a JSON. For example, this works to set the error\_collector.expected\_messages field:
    
    NEW_RELIC_ERROR_COLLECTOR_EXPECTED_MESSAGES="{\"com.example.OtherExpectedErrorClass\": [\"some expected error message\", \"another message\"], \"anotherClass\": [\"some message\"]}"

and here's how you would set error\_collector.expected\_classes _without_ specifying an error message:
    
    NEW_RELIC_ERROR_COLLECTOR_EXPECTED_CLASSES="[\"com.example.OtherExpectedErrorClass\", \"com.example.OtherExpectedErrorClass2\"]"

I think this is worth documenting, especially considering that more and more customers are specifying their config settings at the container level in cloud environments, rather than editing the agent config file directly. 

* Existing docs affected

[https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file)

* New docs needed

No new docs needed, but I think it's worth calling out this trick in the existing config doc, maybe under the **Environment\_Variables** heading. I think this may also work with system properties. 

## Action items for TW

1. Talk to SMEs if you need additional info.
2. Draft changes to [https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file)
3. Get approval from requestor, and loop in @newrelic/java-agent as needed
4. Publish, then notify requestor

## Jira migration details

This issue was migrated from the internal DOC jira project:

* Original reporter: Jesse Laughlin
* Jira ticket ID: DOC-6180
* Original priority: Medium
* Original component: Experience Debt
* Original product group: FSO

**Comment by pizzaz93** [comment]
This appears to be documented in https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#ec-expected_messages and other sections, would the syntax of without error message need to be added?

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
