### ISSUE TITLE
SINCE clause needs examples of time

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#3124]
### How can we make our docs better?

If you take a look at the SINCE clause documentation (https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#sel-since), you’ll see we don’t have examples of UTC or relative timestamps. A single example of each would help make the syntax clearer.

We probably need three types of examples:

- Relative times (days ago, minutes ago)
- Absolute times (since ‘2021-02-03')
- How timezones interact here

**Comment by austin-schaefer** [comment]
Originated as DOC-7056

**Comment by austin-schaefer** [comment]
@dbarnesbrownNR is reaching out to some NRQL experts to get some good examples here

**Comment by dbarnesbrownNR** [comment]
Sent a request to NRQL team and awaiting examples content.

**Comment by bradleycamacho** [comment]
@dbarnesbrownNR I'm assigning this to you for now and moving it to the SME/Blocked column. Feel free to unassign yourself and move it to **hero: to do** once you get the examples if you don't have the bandwidth to do it yourself.

**Comment by dbarnesbrownNR** [comment]
@derekroller could you take a look at this and help to route Docs folks to the best person to provide some examples? Thanks!

**Comment by bradleycamacho** [comment]
@dbarnesbrownNR Can you re-triage this issue and ping relevant SMEs to figure out next steps? Thanks!

**Comment by dbarnesbrownNR** [comment]
@bradleycamacho have pinged SME for recs on whether and how to address. Moving back to blocked pending hearing back from that person.

**Comment by kscaldef** [comment]
Just noting, we should correct "NRQL results are based on your system time" while we're at it, since that's not true.

**Comment by dbarnesbrownNR** [comment]
Thanks @kscaldef - they are based on time zone where query is made, yes? If not, what is the correct thing to note in place of the text above?

**Comment by dbarnesbrownNR** [comment]
FYI @austin-schaefer and @bradleycamacho I'm actively working on this but ran in to some complexities around locating the right SME and also how we explain timezones overall. To be continued as info rolls in...

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
