### ISSUE TITLE
Issue: Browser monitoring best practices guide

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3133]
### Tell us what you need

>Get more out of browser monitoring, with deeper visibility into your websites and your users. Here are 10 best practices to help you find problems faster and deliver a better experience to your customers with real user monitoring.

The link is broken.
[browser monitoring](https://newrelic.com/browser-monitoring) 
### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/best-practices-guides/full-stack-observability/browser-monitoring-best-practices-guide/
* **OS**: Windows 10
* **Browser**: Chrome 91.0.4472.124
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this @qryuu. It's fixed in #3136.
