### ISSUE TITLE
MSSQLOHI install instructions - correct steps 3 and 4 of "install and activate"

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#314]
## What do you need?

At this link: [https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration\#install](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration#install)

Steps 3 and 4 are confusing to the user. Mostly it's step 4: it gives the impression that there are 2 directories: \\integrations.d, and \\integrations. We had a customer get confused by this during an install. The confusion was multiplied by the fact that it says that the renamed file is being moved; it is already in the directory where it needs to be (\\integrations.d).

Here is some suggested language which could be used:

3\. In C:\\Program Files\\New Relic\\newrelic-infra\\integrations.d, rename mssql-config.yml.sample to mssql-config.yml.

4\. Then edit the file as described in [config](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration#config).

We could optionally offer to the user that instead of renaming mssql-config.yml.sample, they make a copy of it (still in the same directory) and name the copy to be mssql-config.yml. I did it this way and it works fine, and it enables the user to refer back to the original file as comparison to their own edited file. I don't know if that's in fact a documentation standard, but I think we describe this process the same way in other locations. To be 100% sure in this case, it might be worth checking with the team that built this OHI, just to ensure that .sample files won't be read at all by this OHI.

* Existing docs affected  

[https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration\#install](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration#install)

* New docs needed  

none

## Jira migration details

This issue was migrated from the internal DOC jira project:

* Original reporter: Solutions Consultant
* Jira ticket ID: DOC-6154
* Original priority: High
* Original component: Experience Debt
* Original product group: FSO

**Comment by mangulonr** [comment]
Hi Austin

Thanks for your feedback, I created this PR to improve step number 3.
https://github.com/newrelic/docs-website/pull/4996

Regards

**Comment by austin-schaefer** [comment]
Was fixed in #4996, looks like we forgot to close the issue
