### ISSUE TITLE
Issue: Query system limits

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3156]
### Tell us what you need

>Using three limit metrics together on a dashboard, you can quickly see detailed visuals of your Ingest Resource Request Per Minute limits, and with NrIngrationError get a view into more limits.

Probably Typo.

NrIngrationError > NrIntegrationError

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/manage-data/query-limits/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for spotting this, @qryuu - we'll fix it!

**Comment by urbiz-nr** [comment]
Closed via #3157.
