### ISSUE TITLE
Issue: CocoaPods for tvOS installation and configuration

### ISSUE THREAD

**Issue by cjmccarthy** [newrelic/docs-website#3166]
### Tell us what you need

`pod 'NewRelicAgentTVOS'` should be `pod 'NewRelicAgent'` - NewRelicAgentTVOS pod is deprecated as of almost a year ago.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/tvos/cocoapods-tvos-installation-configuration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Fixed with https://github.com/newrelic/docs-website/pull/3167 , thanks!
