### ISSUE TITLE
Azure Service Bus monitoring integration - broken link

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#3177]
Hi! The section [Find and use data](https://docs.newrelic.com/docs/integrations/microsoft-azure-integrations/azure-integrations-list/azure-service-bus-monitoring-integration/#find-and-use) has the following line:

* Topic data: [AzureServiceBusTopicSample](https://docs.newrelic.com/docs/integrations/microsoft-azure-integrations/azure-integrations-list/azure-service-bus-monitoring-integration/#topic)

That link doesn't go anywhere on the page. The section it's supposed to go towards is [Topic sample metrics](https://docs.newrelic.com/docs/integrations/microsoft-azure-integrations/azure-integrations-list/azure-service-bus-monitoring-integration/#subscription), but the link leads to "#subscription," which is what I imagine the problem is. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/microsoft-azure-integrations/azure-integrations-list/azure-service-bus-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @dlesniak-NR. It's been fixed in #3179.
