### ISSUE TITLE
Issue: Use Auto-telemetry with Pixie for instant Kubernetes observability

### ISSUE THREAD

**Issue by greenszpila** [newrelic/docs-website#3226]
### Tell us what you need

I think that it was useful to have the below details in the ### Before you begin section.

* a [Pixie account](https://work.withpixie.ai/admin/api-keys)
* a Pixie API key 

Would be helpful to add more details on where to get the API/Deploy keys. 

### Anything else you'd like to share?

This has been originaly included in the revision:
https://github.com/newrelic/docs-website/commit/f4464406e7582e949471d018ecce97c94a653f4e#diff-c1f868b1059dde1162d32d7ca07c577d29d014c016bbd26353501b642a4a5f12

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/auto-telemetry-pixie/get-started-auto-telemetry-pixie/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @greenszpila! Thanks for filing the issue, we'll have a look 🙌🏻

**Comment by mmfred** [comment]
@greenszpila - I'm waiting on a little advice on this. It sounds like the docs reflect current reality accurately, but I'm wondering if there's something we should say about manual installs not being supported at present. And we'll update as soon as anything changes.

**Comment by mmfred** [comment]
I added a note to tell existing Pixie users that they need to install via the guided install steps. So I'm going to close as fixed.
