### ISSUE TITLE
Images are broken

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#3231]
Hey all! I happened to notice images were broken on this page, which is also showing up in-product. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/whats-new/2021/07/alert-conditions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by mmfred** [comment]
Hey @jerelmiller I see images. Maybe they fixed themselves?

**Comment by jerelmiller** [comment]
Oh hey look at that! Perhaps there was a new build recently that fixed these paths. I do see the images now. Thanks so much!
