### ISSUE TITLE
Enhancement request: components for tutorial template

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#3269]
The docs team is creating tutorials. Alex Ronquillo and Jemiah Sius are creating labs. We have collaborated on design ideas for these two types of content to enhance a coherent site design and as a bonus, to reduce the ask of the DevEn team. 

This issue is to request some new components to support the new content types.

### Describe the solution you'd like

These files provide mocks of the lab and the tutorial designs for your reference. We're looking only for components, here, and not full templates. One big goal for these content types is to create a sense of encouragement and calm for users, which is really enhanced by plenty of white space. We have pages of content that provide the kind of information we're planning for, but due to the current design, they look very busy. Hence, this request. 

![lab-format](https://user-images.githubusercontent.com/58010132/127904498-c507c6de-b83f-48b8-ae7c-b371e5b6c00a.png)

![tutorial_ rough diagram (2)](https://user-images.githubusercontent.com/58010132/127041797-2bbda30e-028e-4c37-8c0a-36de54f2e8b2.png)

The components we need:
- Right and left side text boxes: If the titles for these could be flexible, that would help to support the two types of content that would use them. These will need to expand downward to handle a flexible amount of information, though in general, the info should be brief. Preferably, these boxes would _not_ have a box outline, to support that white space mention above.
- progress indicator - the line and circle progress indicator in the prototype is based on the one used for release notes on the docs site. The idea is that you would quickly see where you are in the process by the shaded bubble. We'd need to add content to the side of the bubble and lines. Ideally, the content could be of any type - headings, collapsers, screenshots or other art, regular text, etc. 

### Describe why this important to you

We see these content types as supporting company objectives around goals like quicker time to value with the product, and providing opinionated ways to accomplish tasks. 

### Additional context

In many ways, the guides on the developer site are tutorials. I thought about the components involved with the guides, but felt that the step sections were a little unwieldy to write, and the overall design doesn't provide that sense of calm and encouragement mentioned earlier.

**Comment by alexronquillo** [comment]
Could you also build stats tracking into the progress indicator? This would be really valuable for understanding what procedures users complete, where they stop tutorials/labs, etc.

**Comment by mmfred** [comment]
How do we get work like this prioritized?
