### ISSUE TITLE
Broken link to uniqueCount query in UI

### ISSUE THREAD

**Issue by josemore** [newrelic/docs-website#3279]
### Description

There's a broken link in widgets when the query uses uniqueCount(). 
The UI shows this: "This pie chart uses uniqueCount, which may result in the facet sum exceeding 100%. Learn more in our documentation."
The UI has broken (404) link to: https://docs.newrelic.com/docs/insights/nrql-new-relic-query-language/troubleshooting/pie-chart-uniquecount-adds-more-100/

### Steps to reproduce

1. Go to [this query](https://staging-one.newrelic.com/-/0nVjYPyd3R0) (Any query that uses the uniqueCount function)
2. Click on the "Documentation" link
3. Get a 404 instead of the content

### Expected behavior

Broken link (maybe URL lost in the migration)

### Screenshots

![image](https://user-images.githubusercontent.com/1753821/127116598-8fd926b0-d88c-474f-be28-7ebc93c92ea6.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by x8a** [comment]
Thanks for spotting this! The link should direct you [here](https://docs.newrelic.com/docs/query-your-data/explore-query-data/use-charts/chart-types/#widget-piechart). Our engineers will update it as soon as possible 🙌🏻.

**Comment by jpvajda** [comment]
@x8a were you working on this issue? It's actually in the NR1 product and not something my team controls. You'd want to raise this issue to `#help-entity-ui` for resolution.

**Comment by x8a** [comment]
Hi @jpvajda! Sorry, I actually meant the engineers responsible for the NRQL builder. I reached out to them and they're working on fixing it. Thanks for checking in! 👏🏻👏🏻👏🏻

**Comment by jpvajda** [comment]
That's great @x8a Thanks for taking that action!

**Comment by x8a** [comment]
I'm closing the issue, since the fix will be live early next week.
