### ISSUE TITLE
Document dropping data and logs

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#328]
## Description

We got several pieces of user feedback related to logs and dropping data:   

Related to this page: [Logs parsing: Built-in rules and custom parsing](https://docs.newrelic.com/docs/logs/log-management/ui-data/logs-parsing-built-rules-custom-parsing)  

> "Can we provide more specific examples of how to provide SaaS side custom parsing rules in the Logs UI similar to the examples we have for Drop filter rules?"

and to this page: [Drop data with drop filter rules](https://docs.newrelic.com/docs/logs/log-management/ui-data/drop-data-drop-filter-rules)  

> "The UI has now changed to create drop filters. Can we get the screenshot updated?"

And this page: [Query syntax for logs](https://docs.newrelic.com/docs/logs/log-management/ui-data/query-syntax-logs)

> "Even if I use exactly what is decribed here it either does not pass syntax check or does not work at all."

## Subject Matter Experts

See logs slack channel

## Action items:

1. You need to create a query in Logs to update the screenshot. You might need to get some help from the Logs team for that.  
2. Speak to the team about the parsing rules request.  
3. Write it.
1. Peer edit
2. Publish
3. cleanup

## Jira migration details

This issue was migrated from the internal DOC jira project:

* Original reporter: @mmfred
* Jira ticket ID: DOC-6146
* Original priority: Medium
* Original component: Experience Debt
* Original product group: TDP

**Comment by barbnewrelic** [comment]
I suspect my "Yes" in previous comment was interpreted as "Yes this is still an issue" rather than "Yes, we had done a lot of doc updates, including screenshots and procedures." See CF-10265. OK to close this issue, because upcoming updates to UI etc. will be addressed with that work.
