### ISSUE TITLE
Issue: Errors page: Find, fix, and verify problems

### ISSUE THREAD

**Issue by YogalakshmiS** [newrelic/docs-website#3298]
### Tell us what you need

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/apm-ui-pages/error-analytics/errors-page-find-fix-verify-problems/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @YogalakshmiS! Could you give us some more information about the problem you need help with?

**Comment by barbnewrelic** [comment]
Moving this temporarily to blocked while waiting for more info from requester.

**Comment by barbnewrelic** [comment]
@YogalakshmiS  for your convenience, we'll close this issue. please feel free to reopen it or submit a new issue when you have more details about how we can help. thanks again!
