### ISSUE TITLE
Testing translation workflow

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#3302]
### Background
Unit tests already exist for steps of the translation pipeline, but I would like a way to proactively test the workflow end-to-end in terms of the javascript code that comprises the translation process (versus running all the github workflows).

The thought I have is:
1. Combine the necessary input & script execution from all workflows into one testing script, or set of testing steps.
2. The script runs against a MT project instead, utilizing the speed for immediate feedback.
3. The script runs through all steps of the translation process.

### Acceptance Criteria
- [x] create the script / testing steps
- [x] confirm that translation pipeline works end-to-end for `feature/update-translation-workflow`
- [x] fix up any bugs found along the way

**Comment by jpvajda** [comment]
This looks like it's part of the current sprint, can you estimate this?
