### ISSUE TITLE
Issue: Troubleshoot cross application tracing

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3318]
### Tell us what you need

>you can also adjust the number of transaction events stored in your agent configuration.

What does adjust mean?

To reduce sampling in high throughput apps
I'm not sure if I should increase or decrease the max_samples_stored setting, and reading the documentation I'm confused about what action to take.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/transactions/cross-application-traces/troubleshoot-cross-application-tracing/
* **OS**: Windows 10
* **Browser**: Chrome 92.0.4515.107
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hello @qryuu - thanks for reaching out! The "adjust" you mention refers to "reduce or eliminate sampling", so you need to decrease the setting. Hope this helps!
