### ISSUE TITLE
Issue: Report metrics via the Metric API

### ISSUE THREAD

**Issue by StephenFarrell99** [newrelic/docs-website#3319]
Near the top of the page is the sentence "Each request is composed of one or more metric data points, which consist of a metric **name, a timestamp, and a value**."

Later in the page is the sentence "A metric data point is identified by a **name, type, and value** along with an optional set of attributes."

In between, is this:
{ 
           "name":"memory.heap", 
           "type":"gauge", 
           "value":2.3, 
           "timestamp":CURRENT_TIME, 
           "attributes":{"host.name":"dev.server.com"} ,
which suggests that both sentence should read 'name, type, value, timestamp'.

I'm new to NewRelic, so please correct me if I've missed something.

**Comment by x8a** [comment]
Hi, @StephenFarrell99! I think `timestamp` has been omitted in the second sentence because it's not as representative as the `name`, `type`, and `value` key values. Please let me know if adding it in the second sentence would make it less ambiguous. Thanks!

**Comment by StephenFarrell99** [comment]
> Hi, @StephenFarrell99! I think `timestamp` has been omitted in the second sentence because it's not as representative as the `name`, `type`, and `value` key values. Please let me know if adding it in the second sentence would make it less ambiguous. Thanks!

The most important thing is that the two sentences need to be consistent. 

Later in the document, the required parameters are listed as name, value and timestamp. Type is listed as optional, but recommended. This means the second sentence,  which omits timestamp, is definitely misleading. I would change the second sentence to be consistent with the first. Name, timestamp and value are the only ones that are required. Everything else is optional.

**Comment by x8a** [comment]
Noted! I fixed it in PR #3344. Thanks for reporting the inconsistency! 👏🏻
