### ISSUE TITLE
Issue: Private locations overview: Monitor internal sites and add new locations

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3342]
### Tell us what you need

<html>
<body>

Account access and permissions | A private location set up with a parent account can be used by the child accounts under that parent. A private location set up with a child account can only be used by that child account.
-- | --

</body>
</html>

I don't think there is a parent and child relationship in the New Relic One user model.

What is the PrivateLocation between accounts that belong to the same organization in the New Relic One user model?
### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/private-locations-overview-monitor-internal-sites-add-new-locations/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @qryuu! I'll look into this and get back to you.

**Comment by zuluecho9** [comment]
thanks @qryuu, this is a very good question and I"m going to investigate this and some other references to 'parent/child account' structure in docs for other features.

**Comment by zuluecho9** [comment]
@qryuu I'm curious if you find this PR docs edit makes sense: https://github.com/newrelic/docs-website/pull/3354. If not, I'm curious what is missing.

**Comment by zuluecho9** [comment]
Okay we're pushing out a change to docs regarding this with https://github.com/newrelic/docs-website/pull/3354 and gonna close this issue. Thanks again.
