### ISSUE TITLE
Add watermark/other way of marking an entire doc

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#335]
### Is your feature request related to a problem? Please describe

On the current docs site, we mark beta/limited release/legacy/deprecated docs with watermarks like [the one on this custom views doc](https://docs.newrelic.com/docs/plugins/plugins-new-relic/custom-dashboards-custom-views/custom-views-deprecated):

![image](https://user-images.githubusercontent.com/55203603/100797637-4eebe600-33d7-11eb-8f0b-97a0bcffdbcf.png)

The new site doesn't have an equivalent visual "tag" for an entire document.

### Describe the solution you'd like

Some way of marking the status of an entire doc. A callout doesn't work because we want it to be visible wherever you are in the doc: At the top, at the bottom, somewhere in the middle. But I'm not at all tied to the watermarking solution. A header, something in sidebar, etc could all work.

### Acceptance Criteria

1. allow a contributor to have  any easy way to mark a page as "deprecated", "beta", or "limited release" etc
2. the component should be visible at the top of a page and as a user scrolls through the page, the component should be "sticky" and always display at the top of the page.
3. This component should be part of the global theme and available to the OSS / Dev sites as well.

### Describe why this important to you

Allows users to easily determine the status of "special" docs to avoid confusion. (For example, a new user building on a legacy solution instead of a new one; or someone running a beta feature in a prod environment.)

**Comment by austin-schaefer** [comment]
cc @djsauble @jpvajda @roadlittledawn

**Comment by jpvajda** [comment]
@austin-schaefer I think we could just do a scrolling header component for something like this, but I'm curious, why do we keep live deprecated pages? I

Also is this a launch requirement, or just something we'd want to do eventually? For any deprecated pages for launch couldn't a contributor just modify the page title of each section to mark the page as deprecated?

**Comment by austin-schaefer** [comment]
@jpvajda : Not just deprecated pages to be clear, a more common use is beta/limited release docs. But for the deprecated/legacy docs: Typically features will remain usable for a long time after they're marked legacy. For example, custom views remains in active use by a few customers despite being replaced several years ago. 

I'd say it's a launch requirement, there are a good number of docs on the site using this today.

**Comment by jpvajda** [comment]
@austin-schaefer I see. so you need a way to mark a page with more than just "deprecated", this feels like a component that can be added to any page an provide the page scrolling effect that the current site does with a watermark. I think we'll need some design insights on this @djsauble , and if it's small enough perhaps we can try to do this in the catch-all MMF.

**Comment by austin-schaefer** [comment]
@jpvajda That sounds good. Totally agree it's a component, and it feels small enough we can cram it in as a ticket inside another MMF.

**Comment by jerelmiller** [comment]
From @djsauble 


https://user-images.githubusercontent.com/565661/103030928-a7fbf500-4511-11eb-98af-d97bc2eb6d8e.mov

```css
{
  position: fixed;
  color: #eeeeee;
  font-size: 10em;
  transform: rotate(-15deg);
  z-index: -1;
}
```

**Comment by jpvajda** [comment]
@jerelmiller this works!  how is it applied to a page?

**Comment by jerelmiller** [comment]
@jpvajda I'm considering making this a part of frontmatter, but this might be a good discussion topic! We have a couple options right now:

1) Make this a part of frontmatter:

```mdx
---
title: The page title
watermark: Deprecated
---

## Stuff about this doc

This is really fun!
```

2) Use a component:

```mdx
---
title: The page title
---

<Watermark text="Deprecated" />

## Stuff about this doc

This is really fun!
```

Thoughts?

**Comment by jpvajda** [comment]
@jerelmiller oh cool! I'll defer to @austin-schaefer for the final approach since he can speak for the writers, but the frontmatter slug is probably a little easier to apply for a casual user.

**Comment by jpvajda** [comment]
@jerelmiller actually I don't want you to get blocked on this as Austin is out until Jan, let's go with frontmatter. 👍
