### ISSUE TITLE
Migrate data from Dynamo to new Database

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3350]
### Background

We have some translations queued & jobs current in progress but using the Dynamo DB. To make sure we don't lose any in progress or queued up work, we need to migrate the existing data we have to our new database.

### Acceptance Criteria
- [x] create migration script
- [x] migrate in progress jobs 
- [x] migrate files queued for translation

**Comment by nr-kkenney** [comment]
EOD update: confirmed with julien that we are good to startup the workflows / do our first run on monday, so ill wait on actually doing the migration till monday. 

scripts are ready & ive tested against my local postgres instance so I can migrate first thing on monday.

**Comment by nr-kkenney** [comment]
jobs & files migrated.
