### ISSUE TITLE
Issue: Synthetic monitor public minion IPs

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3361]
### Tell us what you need

>New Relic will attempt to proactively notify customers prior to any changes via e-mail.

What email address will be notified with this email?
Is it for all registered users of New Relic, including Basic?
Or is it only for specific users such as FullUser or Admin?

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@qryuu thanks. This should be referring to all users in that account being notified. I may update this doc, thank you for that criticism.

**Comment by zuluecho9** [comment]
@qryuu And apparently those IP addresses should rarely change.
