### ISSUE TITLE
Localization Discovery w/Julien

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#337]
to get ready for localization we'll want to do some discovery work with Julien to understand the scope of our solution approach.

## Questions 

- [x] Confirm we won't need translate the OSS site and Dev Site at this time in this MMF in this launch, but we'll want to reuse the same solution in the future. 
- [x] We aren't doing any additional tooling around translation and our vendor will do all that we need for language translation needs.
- [x] When we cut over to the new Docs site, what do we do with the Drupal integration and  the jp site? Can we just take it down?
- [x] Discuss the expectations around supporting the Korean language. 
- [x] Other items @caylahamann identifies she needs to know

**Comment by jpvajda** [comment]
@caylahamann do u think this is done now? I feel pretty good about it. 🥇

**Comment by caylahamann** [comment]
Yes it is! I'm going to close this issue. :)
