### ISSUE TITLE
Issue: Muting rules: Suppress notifications

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#3371]
### Tell us what you need

* To my knowledge, not all Violation event attributes can be used for a muting rule. 

please provide an explicit list of those attributes that we can use in a muting rule, rather than a link to all violation event attributes.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 92.0.4515.107
* **Device**: Unknown

**Comment by paperclypse** [comment]
Do you have a list of supported attributes, @dralph3344?

**Comment by paperclypse** [comment]
Hi @dralph3344, I've checked with @HenryTech on this one. It looks like the docs are correct. If there are any missing violation event attributes, that's an error in our product and not in our docs. Thanks!

**Comment by dralph3344** [comment]
no i do not have the list of supported attributes. @HenryTech  should have a clarifying list as the docs are incorrect.
