### ISSUE TITLE
Update "launcher" instructions to use Guided Install UX flow

### ISSUE THREAD

**Issue by josemore** [newrelic/docs-website#3385]
### Tell us what you need

* The tiles in the "Install using the launcher" section are pointing to the "legacy UI" to install the infrastructure agent that's no longer being maintained. 
* We should rename "launcher" with "Guided Install" (in general) and have "Linux and Windows" tiles pointing to the Guided Install experience (see [Guided Install](https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview/) instructions for reference and links).
* Customers who cannot / won't use the Guided Install will need to follow the manual steps-by-steps instructions to install the infrastructure agent.  

### Anything else you'd like to share?

Please work with me and svandamme on the details as needed. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.164
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Created jira DOC-7198.

**Comment by urbiz-nr** [comment]
Closed via #3615.
