### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#340]
### Description

 “Update Infinite Tracing/Edge docs to include instructions using the New Relic CLI “

### Affected docs

* Link to affected docs
* Link to affected docs
* Link to affected docs
* Link to affected docs

### Expected outcome

A clear and concise description of the fix or change you want to the doc(s).

### Environment

Describe your environment. For example, what operating system do you use, what New Relic agents and integrations are installed, etc.

**Comment by mmfred** [comment]
This was a test issue.
