### ISSUE TITLE
Idea: Tweak left nav behavior to make browsing easier

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#3400]
### Is your feature request related to a problem? Please describe

The left nav currently only "opens" a specific menu if you click the little arrow. We did this so that category pages are discoverable. However, this comes at a cost to simple browsing: Clicking the titles of a category bounces you around in a way that's pretty disorienting.

### Describe the solution you'd like

* Make clicking on a nav name just un-collapse the menu, without navigating you away. (Like clicking the arrows today)
* Add a permalink icon that appears on hover next to menus (like we do for collapsers and headers). Clicking on the icon would navigate you to the category page, and copy a link to your clipboard. (Which is basically what clicking on a collapser/header would do.)

### Describe why this important to you

I've heard a lot of frustration with the experience of clicking around the left nav. This seems like an elegant way to still expose the nav pages, while making the experience of browsing the site more pleasant.

### Additional context

No particular rush on this—I'd like a designer's input on this. I just wanted to capture this idea so I don't lose it.

### Very rough mockup

![mockup](https://user-images.githubusercontent.com/55203603/128117782-10fb0e3c-9b47-49bd-af37-db87c6df522d.png)

**Comment by austin-schaefer** [comment]
@zuluecho9 @rhetoric101 : I know you both have had strong feelings about this. Curious on your thoughts on this idea. 

@x8a : Might be a good smaller ticket item for you at some point.

**Comment by zuluecho9** [comment]
yeah that makes sense to me. I find the fact that it takes you away bad also. But we do need a way to get those links to those category views.

**Comment by roadlittledawn** [comment]
no longer relevant since we updated left nav to only open/close collapsed items and leaf nodes are links to their pages.
