### ISSUE TITLE
Broken .NET links

### ISSUE THREAD

**Issue by vuqtran88** [newrelic/docs-website#3411]
### Description
We noticed a lot of the .net integrations link are broken on our public doc. 

### Steps to reproduce

1. Go to [https://newrelic.com/integrations?query=.net&tags=
](https://newrelic.com/integrations?query=.net&tags=)

2. Click on the first "Documentation" button 

3. See `404` error.

### Screenshots

![image](https://user-images.githubusercontent.com/56414817/128235337-0f1cce91-e11f-4cd6-8fb6-731a16f86aec.png)

### Additional context

Looks like there are some inconsistencies with the links used. Some pages are using this link https://docs.newrelic.com/docs/agents/net-agent/getting-started/compatibility-requirements-net-framework-agent, and some other pages are using this link https://docs.newrelic.com/docs/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework/

**Comment by bradleycamacho** [comment]
@vuqtran88 Thanks for reporting this. Looking into this now.

**Comment by bradleycamacho** [comment]
This should be fixed now @vuqtran88. Please let us know if this happens again :)
