### ISSUE TITLE
Only build on Gatsby, no longer use Github to build sites [DOCS]

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3415]
We setup GitHub to build the site as we had issues with Amplify not reporting back build status we no longer need to this now that we are on Gatsby Cloud. 

### Acceptance Criteria

- [ ] no longer build in Github and only build on Gatsby
- [ ] Give a select group of Docs Team members access to Gatsby Cloud so they can trouble shoot builds

**Comment by jpvajda** [comment]
The difference between preview builds & prod builds on Gatsby Cloud: Preview builds are served from our own nginx in Google Cloud. The production builds are served from Fastly CDNs.

**Comment by aswanson-nr** [comment]
We are going to hold off on these changes until after the break to ensure that there aren't any unintended side effects.

**Comment by jpvajda** [comment]
Blocked while we confirm if forks can build on this site.

**Comment by jpvajda** [comment]
Confirmed forked prs work again... 🥳
