### ISSUE TITLE
Issue: Update Item 2 for better clarity on metadata in config block for browser agent and clarifying conditions for the application id reference

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#3416]
### Tell us what you need

First Request, In #2 under **Update Using the Loader Endpoint**, we mention some metadata but not all. 

_Set your browser application ID and license key immediately after the snippet.

NREUM.info = { applicationID: "YOUR-APPLICATION-ID",
               licenseKey:    "YOUR-BROWSER-LICENSE-KEY" };_

We've seen this question come up from time to time on what our other metadata values represent. This may be a good place to add that data or somewhere else in the docs. 

This is important when it comes to using Distributed Tracing as agentId was added when we released that feature. From what I understand, the value may depend on how the browser agent is being installed (copy/paste or APM injected by a language agent). Some customers like to use environments variables when installing the browser agent in apps and a guide to what these values represent could be very useful. 

Second request, the doc here may need to be updated to better explain **applicationID: "YOUR-APPLICATION-ID",**. There is a browserAppId and APM appId and we should clarify the cases under which this displays in the config block. For example, the applicationId in the config block would be the BrowserAppId if using copy/paste install. 

### Anything else you'd like to share?

Here's an example from the community:
https://discuss.newrelic.com/t/copy-paste-browser-setup-across-different-accounts/116503/2

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/installation/update-browser-agent/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for the issue @CherylFrankenfield! I'll scope this out and try to get it into an upcoming sprint.
