### ISSUE TITLE
Easier deep-linking to individual attributes

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#343]
### Is your feature request related to a problem? Please describe

While it's possible to deep-link to an individual attribute in the new [data dictionary](https://docs-preview.newrelic.com/attribute-dictionary/), it requires some advanced sidebar-fu to do it.

### Describe the solution you'd like

A simple way to generate a permalink to any attribute. My suggestion would be to use a similar pattern to the one we settle on for #188: Probably just mousing over an attribute could pop up a little "link" icon, and then clicking that link icon would take you to a permalink page. 

### Describe why this important to you

A significant portion of traffic to the current data dictionary is links to individual attribute definitions. This is particularly useful for support sending definitions to customers.

**Comment by jpvajda** [comment]
tagged as catch all. we could use a the pattern established in the product for this, 
![Screen Shot 2020-12-03 at 12 24 47 PM](https://user-images.githubusercontent.com/1395158/101077793-8d61dc00-3562-11eb-824b-219f35ca6837.png)
