### ISSUE TITLE
Fix flashing 404, mangled page when requesting a redirected URL

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#3431]
### Description

When requesting a URL that redirects to another page on the site, you see:
* a 404 page (for 1-2 seconds)
* the destination page, but with mangled layout for 1-2 seconds (footer in upper left, main column and right rail overlapping each other on the right)
* then the destination page with correct layout / styling

### Steps to reproduce

1. Go to https://docs.newrelic.com/docs/agents/net-agent/getting-started/compatibility-requirements-net-framework-agent
2. Watch as 404 page is displayed, then the target URL page is loaded mangled, then with correct layout / styling

### Expected behavior

When requesting a redirected URL, page should not displayed until it's in correct layout / styling

### Screenshots

https://user-images.githubusercontent.com/2952843/128412014-291f6e84-29d4-4a1a-861e-fcf38e11db60.mp4

### Additional context

At first it seemed like some redirects did not do this, but when throttling network in the browser, it did same thing.

Seems to happen regardless if redirected URL has trailing slash or not.

This did not happen on Gatsby Cloud preview builds and behaved as expected.

**Comment by jpvajda** [comment]
I've raised this entire problem we faced with redirects and trailing `\`  to Gatsby and I'm seeing if we can discuss this with them soon. It may be wise to wait for input before trying to solve this particular problem.

**Comment by jpvajda** [comment]
This is now resolved 🪄
