### ISSUE TITLE
NRU link results in 404

### ISSUE THREAD

**Issue by liamhurrell** [newrelic/docs-website#3447]
### Tell us what you need

* The link to New Relic University from this page: https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/  results in a 404 - if no description content is available I am in NRU and can provide it - or the link shoudl go to https://learn.newrelic.com/ 

### Doc information (don't delete this section)

* https://docs.newrelic.com/nru/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 92.0.4515.131
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @liamhurrell. I'll update it to https://learn.newrelic.com/.

**Comment by urbiz-nr** [comment]
Fixed in #3449.
