### ISSUE TITLE
Figure out how to use stale bot in DECO site repos

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#346]
The DTK team uses a stale bot to take actions on issues that are going stale, figure out how that works and add to our OSS, DevSite and Docs Site repos.

ex:
https://github.com/newrelic/terraform-provider-newrelic/issues/1006#issuecomment-738458029

**Comment by jpvajda** [comment]
https://docs.github.com/en/free-pro-team@latest/developers/apps/installing-github-apps

https://github.com/marketplace/stale

**Comment by jpvajda** [comment]
I may need to ask someone with the right permission to our repos to add the stale bot to the integrations 

https://github.com/newrelic/developer-website/settings/installations
https://github.com/newrelic/opensource-website/settings/installations

**Comment by jpvajda** [comment]
Any repository owner or admin, can enable an integration. To enable a GitHub integration on a repository select the ‘Settings’ tab on the repository you wish to integrate with the tool. Next, from the list of options on the left hand side of the Settings page select ‘Integrations & services’.

**Comment by jpvajda** [comment]
@jerelmiller are you an admin on both the OSS / Dev site repos?

**Comment by zstix** [comment]
The [Developer Experience Team](https://github.com/orgs/newrelic/teams/developer-experience) on GitHub (which you should be a member of) are marked as admins on both sites.

This might be something that needs org-level admin access. If so, we should look into getting at least one of our team members privileges for that (or identify a request system for things like this).

**Comment by jerelmiller** [comment]
@jpvajda looks like I was able to add it to all 3 sites.

**Comment by jerelmiller** [comment]
Looks like now all we need is a `.github/stale.yml` file: https://github.com/apps/stale

**Comment by zstix** [comment]
Y'all need to stop working on the weekends :laughing:

**Comment by jpvajda** [comment]
PRs 

DevSite: https://github.com/newrelic/developer-website/pull/1026

**Comment by jerelmiller** [comment]
Looks like this is done!
