### ISSUE TITLE
Issue: Use Auto-telemetry with Pixie for instant Kubernetes observability

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#3462]
### Tell us what you need

* We need a link or an explicit list of what the REQUIREMENTS are. What are the supported environments?

for example, Pixie is not supported in ECS. This needs to be clear.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/auto-telemetry-pixie/get-started-auto-telemetry-pixie/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 90.0
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @dralph3344! This does seem like a useful thing to add. Do you have a list of requirements?

**Comment by paperclypse** [comment]
I asked the Pixie hero for info on this.

**Comment by paperclypse** [comment]
Pixie requirements are described in their own docs here: https://docs.px.dev/installing-pixie/requirements/

**Comment by dbarnesbrownNR** [comment]
@paperclypse does this issue already have an associated PR or should I create one to add the link in? Thanks!
