### ISSUE TITLE
Issue: Use Auto-telemetry with Pixie for instant Kubernetes observability

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#3463]
### Tell us what you need

* I would clarify the "Ensure you have the basic user role. You cannot be a restricted user or assigned a custom role that denies access to Auto-telemetry with Pixie." 

my concern is a user thinks a Basic role is necissary, and downgrade in order to ingest the data.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/auto-telemetry-pixie/get-started-auto-telemetry-pixie/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 90.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Created this clarification https://github.com/newrelic/docs-website/pull/3496. Thanks a lot @dralph3344, that was rather confusing. Let us know if it looks better, makes more sense.
