### ISSUE TITLE
Issue: Kubernetes integration: Recommended alert policy

### ISSUE THREAD

**Issue by mnyk** [newrelic/docs-website#3471]
Hi, I tried to set an alert in my Infra Settings from https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/kubernetes-integration-recommended-alert-policy/ - for example "Node allocatable memory utilization % is too high" but I can't find the Value: (memoryUsedBytes/memoryLimitBytes)/100.
I also found on the docs info that now it uses the new memoryWorkingSetUtilization attribute instead of (memoryUsedBytes/memoryLimitBytes)/100 but also cant find in Values choose list.
M.

**Comment by urbiz-nr** [comment]
Hello @mnyk - thanks for getting in touch with us. 

This team takes care of [New Relic public docs](https://docs.newrelic.com/), we'll have a look at the attributes on our docs that are causing trouble and update them accordingly. 

However, if you have more specific questions about how to set your settings I recommend you drop them on our Explorers Hub at [discuss.newrelic.com](https://discuss.newrelic.com/), our hero or other users may be able to help you.

Hope this helps!

**Comment by urbiz-nr** [comment]
Hi again @mnyk! The Kubernetes team says that `memoryLimitBytes` is most likely the issue here, since the queries we provide are correct. If you don't have a memory limit set in your container specs, this attribute will report with no data.

**Comment by mnyk** [comment]
Hi, thanks for your answer. Will you put an instruction with it into your docs? I think it will help more people to use this alert.
mnyk.

**Comment by urbiz-nr** [comment]
We'll be adding a note in docs in #3573, @mnyk.
