### ISSUE TITLE
Issue: Install .NET agent for Linux

### ISSUE THREAD

**Issue by neilpdx** [newrelic/docs-website#3472]
### Tell us what you need

The following statement...

If you modify your newrelic.config file, make sure it retains the default UTF-8 encoding. If your editor adds a BOM (Byte Order Mark) to the encoding, the agent will be unable to read the file and will not start up in Linux.

...can be removed since this issue has been fixed in agent version 8.39: 
https://github.com/newrelic/newrelic-dotnet-agent/compare/v8.39.0...v8.39.1

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/net-agent/installation/install-net-agent-linux/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 91.0.4472.164
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reaching out, @neilpdx - we'll update the docs!
