### ISSUE TITLE
Issue: How to use service maps

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3474]
### Tell us what you need

> You can add any service map to a dashboard. For example, if you have a dashboard showcasing performance metrics for several entities, adding a service map to the dashboard shows how all the entities are related and provides additional context about your system.

Currently, only legacy APM service maps can be added to the Dashboard, but I don't think new service maps can be added.

The description that follows is actually the procedure for adding a legacy map to the Dashboard.

This page is a description of the new Service Map.
Since the legacy APM Service Map is [linked to a separate document](https://docs.newrelic.com/docs/understand-dependencies/understand-system-dependencies/service-maps/service-maps-apm/) at the top of the page, we think that describing how to add the legacy MAP here will mislead the reader.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/understand-dependencies/understand-system-dependencies/service-maps/how-use-service-maps/
* **OS**: Windows 10
* **Browser**: Chrome 92.0.4515.131
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reaching out, @qryuu - we'll have a look!

**Comment by urbiz-nr** [comment]
Closed via #3513.
