### ISSUE TITLE
Issue: Proactive Detection with Applied Intelligence

### ISSUE THREAD

**Issue by ghost** [newrelic/docs-website#3476]
### Tell us what you need

The [webhook attribute list](https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/proactive-detection/proactive-detection-applied-intelligence/#webhook) and [json template](https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/proactive-detection/proactive-detection-applied-intelligence/#json-example-schema) are missing 2 attributes: `viewChartImageUrl` and `anomalyzerUrl`.

### Anything else you'd like to share?

Here is the schema:

```
{
  "version": "{{version}}", 
  "entity": {
    "type": "{{entity.type}}",
    "name": "{{entity.name}}",
    "link": "{{entity.link}}",
    "entityGuid": "{{entity.entityGuid}}",
    "domainId": "{{entity.domainId}}",
    "domain": "{{entity.domain}}",
    "accountId": {{entity.accountId}}
  },
  "detectionType": "{{detectionType}}",
  "category": "{{category}}",
  "data": [{{#each data}}
    {
      "value": "{{value}}",
      "unit": "{{unit}}",
      "timestamp": {{timestamp}}
    }
    {{#unless @last}},{{/unless}}
  {{/each}}],
  "viewChartImageUrl": "{{viewChartImageUrl}}",  
  "anomalyzerUrl": "{{anomalyzerUrl}}"
}
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/proactive-detection/proactive-detection-applied-intelligence/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @djaffinito, can you provide me with defs for each attribute so that I can appropriately update the attribute list table? Thanks!

**Comment by daffinito** [comment]
Sorry for the delay on this- I created a PR to fix it: https://github.com/newrelic/docs-website/pull/5133

**Comment by urbiz-nr** [comment]
Thanks for the fix, @daffinito - closing this.
