### ISSUE TITLE
Drop data using NerdGraph Broken Link

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#3477]
### Tell us what you need

I found a broken link found in the paragraph below. 

```
TIP
If you are sending data to New Relic using Prometheus remote write, you can also drop data by changing the remote_write section of your YAML config file.

For more information, see [Drop data using Prometheus remote write](https://docs/integrations/prometheus-integrations/install-configure-remote-write/remote-write-drop-data).
```

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/manage-data/drop-data-using-nerdgraph/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for letting us know, @dlesniak-NR! It's being fixed in #3485.
