### ISSUE TITLE
Parameter missing from example command

### ISSUE THREAD

**Issue by twistypigeon** [newrelic/docs-website#3478]
### Tell us what you need

The command line to call the cloudformation script is incorrect.
When running it demands another parameter value for NrAccountId.
As such the command should change to:

`aws cloudformation create-stack --stack-name NewRelicLicenseKeySecret --template-body file://license-key-secret.yaml --parameters 'ParameterKey=LicenseKey,ParameterValue=LICENSE_KEY' 'ParameterKey=NrAccountId,ParameterValue=ACCOUNT_ID'`

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/
* **OS**: Windows 10
* **Browser**: Firefox 90.0
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this @twistypigeon - it will be fixed in #3510.
