### ISSUE TITLE
Missing capabilities parameter on create-stack example

### ISSUE THREAD

**Issue by twistypigeon** [newrelic/docs-website#3479]
### Tell us what you need

The create stack script requires the `--capabilities CAPABILITY_NAMED_IAM` parameter in order to execute

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/
* **OS**: Windows 10
* **Browser**: Firefox 90.0
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @twistypigeon! Thanks for letting us know. I'll look into getting this fixed.

**Comment by dbarnesbrownNR** [comment]
Currently awaiting input from an FSO PM who can advise how best to make the update. To be continued...

**Comment by bradleycamacho** [comment]
@dbarnesbrownNR Can you update the status of this issue? Thanks!

**Comment by dbarnesbrownNR** [comment]
@bradleycamacho I got as far as labeling but not investigating as it's not a domain I traditionally cover so I am . Action items are for the assignee on docs side to seek out a SME and work with them on validating and getting a PR cooking. Let me know if you need more context!
