### ISSUE TITLE
Example Intrumentation link 404

### ISSUE THREAD

**Issue by twistypigeon** [newrelic/docs-website#3480]
### Tell us what you need

The example instrumentation link at the top of the page 404s

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/
* **OS**: Windows 10
* **Browser**: Firefox 90.0
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks for letting us know! I'll look into getting this fixed.

**Comment by urbiz-nr** [comment]
Closed via #3534.
