### ISSUE TITLE
Issue: Update Browser Docs on JavaScript Errors Global and Generic Errors piece

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#3481]
### Tell us what you need

Specifically, the header Global and generic errors needs to be reviewed by engineering and updated as applicable. 

Recap for reference: 

The docs state _Unavailable errors include: SyntaxError or Script error: These occur while the script is loading, so they do not produce a stack trace._ In Support we see some syntax errors reported and some have a stack trace. Additionally, most errors / modern browsers will report stack traces these days. Can we clarify this to better describe what a customer can expect the agent to capture? 

The docs state _Unavailable errors include: In-line JavaScript or event handler errors: These are unwrapped._ In Support, we do see inline errors being reported. Can we clarify this to better describe what a customer can expect the agent to capture? 

We understand this part was written a long time ago and modern browsers are more sophisticated now, and that this could use an update to be more specific. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/stack

### Anything else you'd like to share?

To note, this doc was updated about a year ago, though I believe the changes was to include older browsers. I'll include links to tickets and documentation history in this request for your context as well. Thank you! 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/javascript-errors-page-detect-analyze-errors/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by CherylFrankenfield** [comment]
Previous docs jiras: 
https://newrelic.atlassian.net/browse/DOC-6096
https://docs.newrelic.com/node/1911/draft

Tickets/Eng: 
https://newrelic.atlassian.net/browse/GTSE-4038
https://newrelic.zendesk.com/agent/tickets/419630
https://newrelic.zendesk.com/agent/tickets/465281

**Comment by paperclypse** [comment]
Thanks for letting us know, @CherylFrankenfield! I'll look into the best way to move forward on this one.

**Comment by urbiz-nr** [comment]
I've created a jira (DOC-7244) so we can add it to our next sprint and give it the time it deserves.

**Comment by bradleycamacho** [comment]
@urbiz-nr Can you update this issue? Thanks!

**Comment by urbiz-nr** [comment]
There's a jira tracking this, and the Browser team is working on a PR to address it. They'll ping the hero when it's ready.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
