### ISSUE TITLE
Issue: Java agent: Instrument Kafka message queues

### ISSUE THREAD

**Issue by jbotuck** [newrelic/docs-website#3483]
lots of deprecated things on this page!

**Comment by paperclypse** [comment]
Hi @jbotuck! Thanks for filing an issue. Would you like to get a little more specific? :)

**Comment by jbotuck** [comment]
https://docs.newrelic.com/docs/agents/java-agent/instrumentation/java-agent-instrument-kafka-message-queues/ references `.acceptDistributedTracePayload` which is deprecated

`class_transformer:
  kafka-clients-spans:
    enabled: true ` is also  generating deprecation warning for me

**Comment by urbiz-nr** [comment]
Hello @jbotuck! Some of it has been addressed in #3508. Let me check what's going on with `class_transformer: kafka-clients-spans: enabled: true`.
