### ISSUE TITLE
Issue: JMX monitoring integration

### ISSUE THREAD

**Issue by Julien4218** [newrelic/docs-website#3487]
### Tell us what you need

The "Quick start" section needs to be removed since we've removed the JMX installation from the Guided install.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/jmx-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks for letting us know, @Julien4218! I'll look into getting this removed soon.
