### ISSUE TITLE
Migration script doesn't account for navigation sort order

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#349]
### Description

Currently the migration script isn't automatically setting sort order for categories and pages.

### Example: Categories

![category_sort_order_issues](https://user-images.githubusercontent.com/55203603/101224564-d342a100-3643-11eb-977e-06bfaa724c27.png)

### Example: Pages

![doc_sort_order_issues](https://user-images.githubusercontent.com/55203603/101224999-2b2dd780-3645-11eb-9353-769dcf18027f.png)

### Expected behavior

Preserve the sort order from the current docs site as part of the migration script.

### Additional Notes 
- Expose the sort weight in the API and leverage that as part of the script.
- Scope: This is only for the migration script.
- We need to account for release notes nav that uses release date and time to sort items in the nav

### Related to
#381 

# MMF 9 Scope
When migration script is run we want arrange things (both .mdx content files AND the sub-directories) in the nav menus in the order that is set in Drupal. In the Drupal migration API, this order will be exposed via the `order` field. We don't currently have any API resources for taxonomy terms, but we could create them if needed to get the `order` value.

This applies to migration only. Post migration, content contributors can set the order of the nav items by directly editing the .yml files.

## Acceptance criteria
- [ ] As a content contributor, .mdx files and directories/categories in the nav files mirror the current site

**Comment by jpvajda** [comment]
@jerelmiller  FYI on this one, we noticed it today looking at some order on the agent docs pages.

**Comment by tariqahmed** [comment]
Expose the sort weight in the API and leverage that as part of the script.

**Comment by tariqahmed** [comment]
Scope: This is only for the migration script.

**Comment by roadlittledawn** [comment]
Also, need to account for release notes nav that uses release date and time to sort items

**Comment by roadlittledawn** [comment]
I just added the `order` field to the migration API JSON for the following content types:
* page
* troubleshooting_doc
* api_doc

**Comment by jerelmiller** [comment]
@roadlittledawn I'm not seeing that `order` field for any of those content types. Is there something I'm missing?

**Comment by austin-schaefer** [comment]
@jpvajda @jerelmiller @roadlittledawn : Just wanted to check on this one. I see the ticket is closed but it looks like sort order is not actually reflected in sidebar for pages. For example, compare this ordering to the order in the Drupal site:

![image](https://user-images.githubusercontent.com/55203603/103930370-78351b80-50d3-11eb-8470-3d999edb8188.png)

![image](https://user-images.githubusercontent.com/55203603/103930417-8daa4580-50d3-11eb-807e-26912c79d7f2.png)

**Comment by jerelmiller** [comment]
This is one of the items that will be released as soon as we get the build fixed and released!

**Comment by austin-schaefer** [comment]
Hey @jerelmiller @roadlittledawn , is this issue fixed? @roadlittledawn found an example where sort order is wrong:

![image](https://user-images.githubusercontent.com/55203603/107064424-568d8980-6790-11eb-931a-2b83dacc2201.png)

![image](https://user-images.githubusercontent.com/55203603/107064452-5db49780-6790-11eb-8cef-760f0d6c410b.png)

Get Started should be above Core Concepts

**Comment by roadlittledawn** [comment]
@austin-schaefer this work addressed most but not all nav sorting. i'm finishing that up as part of #587 starting today. and i have these on the radar. who can i ask to give some  👀  on the nav order next week?

**Comment by paperclypse** [comment]
I'll be reviewing the nav sort order as part of this jira: https://newrelic.atlassian.net/browse/DOC-6541

**Comment by barbnewrelic** [comment]
I've got a Jira to do some preliminary re-sorting on the Drupal side https://newrelic.atlassian.net/browse/DOC-6583 before spot-checking on the GitHub side
