### ISSUE TITLE
Issue: New Relic guided install overview

### ISSUE THREAD

**Issue by Julien4218** [newrelic/docs-website#3492]
### Tell us what you need
Remove the JMX line item with "newrelic install -n jmx-open-source-integration" since it's no longer supported in the guided install.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/full-stack-observability/observe-everything/get-started/new-relic-guided-install-overview/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks @Julien4218! I'll take care of this soon.
