### ISSUE TITLE
Confirm that the Gatsby PR builds work the same as our Github workflow builds

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3502]
### Relates to

- https://github.com/newrelic/opensource-website/issues/821
- https://github.com/newrelic/docs-website/issues/3415
- https://github.com/newrelic/developer-website/issues/1509

In order for us to take action on the above issues we need to confirm the assumption that PR builds in Gatsby will work the same as Github.

_We setup GitHub to build the site as we had issues with Amplify not reporting back build status we no longer need to this now that we are on Gatsby Cloud._

### Acceptance Criteria

- [x]  Confirm that the Gatsby PR builds work the same as our Github workflow builds. 
- [x] confirm that we get PR previews for forks.
- [x] IF true, then complete  the related issues
- [x] if false, then discuss next steps in what action we need to take (_it's assumed we need to leave github workflows in place_)

**Comment by roadlittledawn** [comment]
Submitted support ticket with Gatsby 2 days ago re: PR Previews for forks. Waiting to hear back. Moved to blocked for now
