### ISSUE TITLE
Add "data type" information to our data dictionary entries (DOC-7235)

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#3505]
Currently, the data dictionary sometimes contains units of measurement, but never contains data types. By "data types," I mean "string," "numeric," and "boolean" (there may be others I'm not thinking about now).

Data type is important because it informs how a user will query any given attribute. Knowing an attribute shows bytes is useful, but whether that is stored as a string or a number dictates how one would query on it, and if one would need to cast the value to a number before doing any math on it. 

This detail should be included for every event type in the Data Dictionary.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
