### ISSUE TITLE
Setup Gatsby Cloud for access via SSO

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3520]
`Note`: We found out in our SSO testing that Gatsby Cloud doesn't support the ability to overwrite access levels once SSO is setup. so we are not doing this until they put that feature in place, as all users are default to Editor via the SSO login. 

In order to pick this back up, we'd need to request our OKTA tile for Gatsby cloud is reactivated by requesting that from `#ask-it` 

### Acceptance Criteria 

- [x] confirm we can get our gatsby cloud setup on SSO and enable OKTA for SAML access for Relics.
- [x] ensuring a tech writer can see the logs in gatsby cloud when failures occur

> we can make any Tech's doc writer access as a read only user (viewer)

- [ ] if build fails due to stale cache, can tech docs folks clean cache and trigger re-build via gatsby cloud?

> TBD

- [x] figure out how we provision access and how that relates to the opensource bot.

- [x] we should consider having another user (either the team, or specifically one of us) as an admin / owner of the account.
 
> we'd make Zack the owner 

- [ ] consider how this may change our bot's access if at all

> it doesn't the bot still has access as an admin

**Comment by zstix** [comment]
We need to figure out how we provision access and how that relates to the opensource bot.

**Comment by nr-kkenney** [comment]
as part of this, we should consider having another user as an admin / owner of the account. this is not fully thought out on my part, but i know for demotron, we have a non-user @ newrelic.com as owner of accounts, but nobody can use sso login for a newrelic domain that is not for their user.

**Comment by jpvajda** [comment]
I followed up with Gatsby on next steps as I haven't heard back on this request.

**Comment by jpvajda** [comment]
Gatsby confirmed this isn't ready yet, so they'll keep us posted on the progress of the feature.

**Comment by jpvajda** [comment]
Still working with IT on this setup.

**Comment by jpvajda** [comment]
I scheduled a call with IT to discuss this on Monday

**Comment by jpvajda** [comment]
We are working on this setup today... Gatsby had some issues with the first attempt to enable this, as the workspace wasn't connecting to our SSO enabled accounts.

**Comment by jpvajda** [comment]
We found out in our SSO testing that Gatsby Cloud doesn't support the ability to overwrite access levels once SSO is setup. so we are not doing this until they put that feature in place, as all users are default to Editor via the SSO login.
