### ISSUE TITLE
broken link: AWS Lambda monitoring integration

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3533]
### Tell us what you need

>Additionally, if you're using AWS CloudFront to execute the functions in AWS locations closer to the clients, and have enabled the filter to collect Lambda@Edge metrics, these data will be attached to the ServerlessSample event type, with a provider value of LambdaEdgeFunction.

The link is broken.
 [Lambda@Edge](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-lambda-monitoring-integration/mailto:Lambda@Edge)

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-lambda-monitoring-integration/
* **OS**: Windows 10
* **Browser**: Chrome 92.0.4515.131
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for catching this @qryuu!

**Comment by urbiz-nr** [comment]
Fixed in #3549.
