### ISSUE TITLE
[Gatsby] Explore taking advantage of Parallel Query Running

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#3539]
## Docs

https://www.gatsbyjs.com/blog/whats-new-in-gatsby-4/

### References 
The complete build audit can be found in the directory: `G:drive: Gatsby Cloud Build Audit`

## Description
Gatsby has an experimental feature called [Parallel Query Running](https://github.com/gatsbyjs/gatsby/discussions/32389) that has been proven to improve our build time. We should look into implementing this.

### How to Use (verbatim from Gatsby thread)
Make sure that you're on `gatsby@latest`, `gatsby-plugin-mdx@latest`, `gatsby-plugin-sharp@latest`, `gatsby-transformer-sharp@latest` and that you're using Node >= 14.15.

Install lmdb-store as a dependency: `npm install lmdb-store`.

Add the PARALLEL_QUERY_RUNNING flag to your `gatsby-config.js`:
```
module.exports = {
  flags: {
    PARALLEL_QUERY_RUNNING: true
  }
}
```

Run gatsby build (as this only applies to the build step).

By default, Gatsby will use cpuCount() - 1 workers to run the queries (physical cores). So if you have 4 cores/8 threads it'll use 3 workers. You can override this number with the GATSBY_CPU_COUNT environment variable.

# Acceptance criteria
- [ ] Add / update dependencies
- [ ] Add flag to gatsby-config
- [ ] Run a cold build (trigger a cache clean) and note the build time
- [ ] If there are any build errors we can't fix, note them here

# Related issues/PRs
#4571

**Comment by roadlittledawn** [comment]
This is on by default in gatsby v4

**Comment by jpvajda** [comment]
closing
