### ISSUE TITLE
Bump `GATSBY_EXPERIMENTAL_QUERY_CONCURRENCY` to 8

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3546]
Speed up run page queries by bumping up GATSBY_EXPERIMENTAL_QUERY_CONCURRENCY from 4 to 8

| Effort  |Impact | 
|---|---|
| LOW  | LOW  |  

<img width="1384" alt="Screen Shot 2021-08-18 at 5 52 09 PM" src="https://user-images.githubusercontent.com/1395158/129986628-82de8b62-d7ee-4faa-ab8e-bc22ce696531.png">

**Comment by austin-schaefer** [comment]
May be redundant with #4571

**Comment by jpvajda** [comment]
💯
