### ISSUE TITLE
[Gatsby] Move HTML generation to custom GraphQL resolvers

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3548]
| Effort  |Impact | 
|---|---|
| HIGH | LOW  |  

### References 
The complete build audit can be found in the directory: `G:drive: Gatsby Cloud Build Audit`

### Acceptance Criteria

- [ ] Move render html out of createPages OR we remove auto index pages altogether, which we have done. But there are other places we generate HTML for JSON output, so this may still be applicable.
- [ ] Move to custom GraphQL resolvers, executes lazily, won’t be part of development bootstrap
- [ ] Alternative: use onCreateNode to render html >> [code](https://github.com/newrelic/docs-website/blob/5223fdc5fa220d6820388a6062a97e3707a58d3a/plugins/gatsby-plugin-auto-index-pages/gatsby-node.js#L170)

**Comment by roadlittledawn** [comment]
OR we remove auto index pages altogether, which we plan to do this quarter. but there are other places we generate HTML for JSON output, so this may still be applicable

**Comment by jpvajda** [comment]
We still need to look at where else this applies to determine what needs to change.
