### ISSUE TITLE
Issue: Mention agent restart required for adding tags

### ISSUE THREAD

**Issue by linbaker** [newrelic/docs-website#3558]
### Tell us what you need

For adding tags through agent config or after adding APM tags in the UI, you need to restart the agent in order to have the tags added to APM data. the tags will then only be added to new incoming data, and not apply retroactively to past data. 

I tested the agent config and APM UI methods, and a restart is required for this section:

https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/use-tags-help-organize-find-your-data/#add-tags-apm-agents

I did not test the API or other tag methods so I am not sure if a restart is required for those methods too. 

### Anything else you'd like to share?

Relevant ticket: https://newrelic.zendesk.com/agent/tickets/463882

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/use-tags-help-organize-find-your-data/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @linbaker, would you mind going ahead and completing a PR for this change? I can review and push it through promptly if you're able to make a quick update to the MDX. Thanks!

**Comment by linbaker** [comment]
Done! Thanks @dbarnesbrownNR !

Another ticket came through, this time using NerdGraph so I tested that too and it also requires a restart of the service so I made a PR to the NerdGraph docs while I was at it

* https://github.com/newrelic/docs-website/pull/3572
* https://github.com/newrelic/docs-website/pull/3571

**Comment by urbiz-nr** [comment]
Thanks @linbaker!
