### ISSUE TITLE
Issue: Add example for `noticeError` for Node.js agent API

### ISSUE THREAD

**Issue by linbaker** [newrelic/docs-website#3560]
### Tell us what you need

An example of how to implement `noticeError()` 

* https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api/#noticeError

Or it may be best to add an example in the agent code examples section here and just link the location in our docs: 

https://github.com/newrelic/node-newrelic/tree/main/examples

Or add an example in the API docs on Github here:

* https://newrelic.github.io/node-newrelic/docs/API.html#noticeError

Reach out on Slack or in #gts-nodejs for any questions! All 1st shift TSEs collaborated on the ticket that brought up the need for these examples, so feel free to ping @1st for any questions! 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/nodejs-agent/api-guides/nodejs-agent-api/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 92.0.4515.131
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @linbaker, do you have an example of implementation ready to go, or should I find a SME who can assist with this? Thanks!

**Comment by linbaker** [comment]
Hello @dbarnesbrownNR - I checked in with the Node team and filed a Github issue for the Node agent directly to get an example added: https://github.com/newrelic/node-newrelic/issues/850

**Comment by urbiz-nr** [comment]
Thanks @linbaker!
