### ISSUE TITLE
Issue: Write your first NRQL alerts condition

### ISSUE THREAD

**Issue by dbarnesbrownNR** [newrelic/docs-website#3566]
This issue relates to [this already-merged PR](https://github.com/newrelic/docs-website/pull/3557). The PR updates the text to match the values reflected in Step 2 and Step 3 screenshots, but there is a secondary issue with these screenshots whcih is that they were taken in a demo environment where CPU usage was between 0.66% and 0.7% (as in < 1.0%, so very, very low), and real-world alerting on CPU usage would likely be set to alert at > 50% and likely > 67%. So the task here is:

1. Find and screenshot real usage stats for CPU that reflect actual values a user would want to alert on, ideally in the 67-95% range
2. Swap those screenshots with the existing screenshots
3. Update text in Step 3 to reflect the actual percent usage shown in the screenshot. 

Should be pretty fast once you find a good demo account to use for screenshots, but if this is confusing or you need additional context, feel free to reach out to @HenryTech or @dbarnesbrownNR before getting started!

**Comment by barbnewrelic** [comment]
Whoever takes this one on, please be sure to use a test environment. I understand the need for robust data, but due to Security requirements for screenshots, we cannot use real New Relic or customer accounts. Our internal policy re: screenshots is in NerdLife. Thanks for understanding!

**Comment by rhetoric101** [comment]
We're going to track this work in doc-7250 for a future sprint.

**Comment by rhetoric101** [comment]
It turns out we had some SME assistance with this and were able to expedite this. This work is being done in PR #3588.
