### ISSUE TITLE
Figure out how to use renovate bot in DECO site repos

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#357]
Look into how we can benefit from using Renovate across our site repos.

https://github.com/marketplace/renovate

https://docs.github.com/en/free-pro-team@latest/developers/apps/installing-github-apps

ex pr:
https://github.com/newrelic/newrelic-cli/pull/499

**Comment by jpvajda** [comment]
@zstix i've been thinking about how we could leverage renovate in our Devex repos, any thoughts on this?

**Comment by zstix** [comment]
I'm a a little hesitant since we've accidentally broke the site by updating dependencies without reviewing the preview build in the past. I'll look into it more tho!

**Comment by jpvajda** [comment]
@zstix we could talk to DTK about how they used it, it seems really handy as go packages are constantly getting updated. I'll  add it to our transition spreadsheet, good topic.

**Comment by jpvajda** [comment]
closing as won't do for now.
