### ISSUE TITLE
Create / Update Synthetic Monitor(s) For URL(s)

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#3586]
## Description
When we migrated from AWS Amplify to Gatsby Cloud, one of the URLs into the site was not working (#3490). In order to prevent this occurring in the future, we should do the following:

* Audit and create a list f all the domains (and subdomains) that the Developer team owns
* For each domain, setup up (or modify an existing) synthetic monitor
* For each web property, set up an alert condition for synthetic failures

## Acceptance Criteria
* [ ] Identify all of the domains (and subdomains) for the sites that the Developer Enablement team owns
* [ ] Set up basic synthetic pings for each domain
* [ ] Set up alert conditions for synthetic failures

**Comment by aswanson-nr** [comment]
We have seen a lot of false positives come out of our alerting strategy. In most of these cases we see spikes in errors or drops in response, but the site continues to function fine. Moving more checks to synthetics should allow us to be more confident that a critical alert is actually critical and hopefully allow us to move away from alerting causing false positives.
Some suggested synthetics pings:
* A few pages of critical documentation
    * Attribute dictionary
    * Release notes
* A few standard redirects to ensure they are still functioning
* A click on the "Free account" to ensure it properly directs to the signup page
