### ISSUE TITLE
Create Alert Conditions for Instrumentation Statistical Outliers

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#3587]
## Description
There have been a few instances in which our instrumentation has stopped reporting (or started reporting incorrectly). When discussing it with the team, we realized that there might be some value in reporting if / when a deviation occurs in the metrics we expect. This would help us know about and respond to our instrumentation breaking. Some possible metrics to watch out for include:

* Page views
* Sign up requests
* Traffic

## Acceptance Criteria
* [ ] Identify metrics to alert on
* [ ] Determine warning and critical thresholds for each metric
* [ ] Add an alert condition for each
* [ ] Add information to troubleshooting dashboard

**Comment by roadlittledawn** [comment]
Thus far this appears to be related to the fact that since we migrated we weren't setting `GATSBY_NEWRELIC_ENV` on production builds, so the browser agent JS wasn't being added to the site. Alec and I just added those env variables in production gatsby sites for docs, developer, opensource
