### ISSUE TITLE
`PageAction` events on the docs site have stopped firing

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#3590]
### Description

Since August 4, 2021 no PageAction events on docs.newrelic.com are firing.

You can reproduce this with the following query in the team staging account:

```SELECT count(*) FROM PageAction where appName = 'docs.newrelic.com' since 28 days ago timeseries 2 hours```

### Expected behavior

We fire the necessary PageAction events to track our custom events, traffic, and other KPIs.

**Comment by jpvajda** [comment]
this seems to be related to the :gatsby: :cloud: migration, same data as the other issue

**Comment by roadlittledawn** [comment]
Thus far this appears to be related to the fact that since we migrated we weren't setting `GATSBY_NEWRELIC_ENV` on production builds, so the browser agent JS wasn't being added to the site. Alec and I just added those env variables in production gatsby sites for docs, developer, opensource
