### ISSUE TITLE
Issue: Configure control plane monitoring

### ISSUE THREAD

**Issue by dbarnesbrownNR** [newrelic/docs-website#3591]
We've received the following customer feedback on the [control plane monitoring page](https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/configure-control-plane-monitoring/): 

`I’m finding that the k8s integration fails to discover anything at all about the control-plane or the etcd since apparently it only works if you are using a k8s that runs everything as pods. I had to dig for quite a while to find that out.

At a bare minimum you should state in the documentation:
A: You don’t test or support Rancher k8s clusters (or rke either) with your nri-bundle integration
B: You don’t support monitoring the control-plane or etcd at all unless your k8s runs everything as pods. The documentation Configure control plane monitoring | New Relic Documentation 2 makes it sound like you should be able to get anything to work no problem.

Yes I get that at least some of the data can come from prometheus. I get also that you can’t support the managed solutions like GKE/AKS since they don’t let you get at control-plane at all. However there are customers out there that are not on a managed solution and yet do expect NewRelic to test and integrate with a platform like Rancher.`

To see the original feedback go to [https://discuss.newrelic.com/t/no-rancher2-control-plane-etcd-integration/158700](https://discuss.newrelic.com/t/no-rancher2-control-plane-etcd-integration/158700)

Let's update the docs to clarify this. We should connect with one of our K8s SMEs in making the update to ensure we include as many helpful details as we can.

**Comment by urbiz-nr** [comment]
I've talked to @mangulonr, he'll have a look.

**Comment by urbiz-nr** [comment]
Integrations team is on it. Removing this from board.

**Comment by bradleycamacho** [comment]
@urbiz-nr Can you update this with the status of the issue? Thanks!

**Comment by bradleycamacho** [comment]
And please add the relevant `pg` tags. Thanks!

**Comment by urbiz-nr** [comment]
@mangulonr's team will file a PR in the next few days to address this.

**Comment by mangulonr** [comment]
Hi @bradleycamacho

**Comment by urbiz-nr** [comment]
Closed via #3948.
