### ISSUE TITLE
Create a default  `set nav file` feature for mdx files when a page nav fails to load

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#3629]
Talked to @roadlittledawn about this a bit, but basically it'd be nice to be able to set the preferred nav file (or maybe even nav file section?) to use for an mdx file, in the off chance the 'auto-load of nav file for sidebar or category view' isn't working correctly. 

Instances when this may be a problem: 
• When a doc URL is used in two nav files and it's first URL segment (e.g., docs/*integrations*/doc-folder/doc-title) doesn't match the top level of an existing nav yaml file. I thought this was happening but now can't find evidence of it, so maybe it's a very one-off instance. 
• When there's an index.mdx file (a landing page) and we use that URL in multiple places in the same nav file, it can confuse the system, so that hitting 'see all docs' button on the landing page can result in it loading the wrong section of docs and not the intended section of docs. This seems to be more a problem than previous issue above; I just did a temporary fix for this in FSO category, where I replaced some of the duplicated URLs (e.g., /docs/browser) with a table of contents view (e.g., docs/browser-table-of-contents) to get it to work slightly better.

**Comment by roadlittledawn** [comment]
@zuluecho9 can you add a couple of example use cases that could benefit from this today?
