### ISSUE TITLE
Issue: Duplicate aggregator functions

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#3638]
### Tell us what you need

I've run into the issue where having multiple aggregator functions of the same type in a NRQL query will cause an issue in most chart types, unless you assign an alias using the `as` clause. So, for example if you have, `SELECT median(a_metric), median(another_metric)`,  the UI will only display one of the two medians, as it only recognizes `median()`. However, `SELECT median(a_metric) as 'med-a', median(another_metric) as 'med-b'` displays properly. 

Could we put in the "Aggregator functions" section that selecting for the same aggregator function needs an alias to display properly?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@dlesniak-NR making sure I understanding this: you're saying that it's merely by separating them a bit that it works properly? So it's not so much the 'as' clause that is required as the fact that they're being separated? If that's right, can you think of other ways to separate them? And would you consider this a NRQL bug that should be fixed?

**Comment by zuluecho9** [comment]
Created PR to attempt to fix this: https://github.com/newrelic/docs-website/pull/3710
