### ISSUE TITLE
Rest API calls to alerts  -- 404

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#3640]
### Tell us what you need

[[This page]](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/rest-api-calls-alerts/) is returning a 404 error

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/rest-api-alerts/rest-api-calls-alerts/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 92.0.4515.159
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting the broken link, @rodrigo-corgozinho. It will be fixed in #3641.
