### ISSUE TITLE
[Repository] Fork PR Process for PR reviews

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3658]
## Summary
To ensure the security of our repositories and related systems we need to take extra steps when handling pull requests submitted from a fork. This is because anyone can submit a pull request and we want to make sure that the code is vetted before allowing our workflows to run it.

### How?
Github helps to prevent this problem by not running workflows for forked pull requests that come in from a new contributor ("new" is defined as the first time they have submitted code to the repository). This allows reviewers to check for changes to workflow files before they are actually executed. When this situation arises, tech writers should defer to an engineer to review the code and approve or deny the workflows.

#### Code owners
One way we can ensure that PR's get the proper review is to setup [Code Owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) for the workflow directory.

#### Work with the docs team
We can educate the docs team on the potential security risks and what to look for in pull requests.

#### Ensure workflow jobs wait for approval
We need to make sure that any workflow that runs code from forks will wait for approval before it runs.

### AC
- [x] Ensure the docs team knows what a forked PR looks like and that they should defer to an engineer
- [x] Set up code owners so that our engineers are always required reviewers on changes to workflow files
- [x] Modify [develop] branch protection to require review from code owners
- [x] Identify the areas where we could apply code owners to other specific areas of the Docs repo( components, utils, etc) (_new ticket_)
- [x] Consider how this can be applied to the quickstarts repo (_new ticket_)
- [x] Get the fork feature request to Gatsby

**Comment by aswanson-nr** [comment]
@jpvajda Updated!

**Comment by jpvajda** [comment]
I love this idea of code owners

> Code owners are automatically requested for review when someone opens a pull request that modifies code that they own.

**Comment by nr-kkenney** [comment]
Request created: https://portal.gatsbyjs.com/gatsby-cloud/p/approvals-for-pr-previews-from-public-forks

**Comment by nr-kkenney** [comment]
some follow up links to check out for potential future work:
- [code owners - chromium](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/code_reviews.md)
- [different way to think about code ownership](https://about.sourcegraph.com/blog/a-different-way-to-think-about-code-ownership/)

The theme being different places have thought about a similar problem, and even have different solutions. In the second link, github codeowners is something they used but ultimately decide to do away with.

**Comment by jpvajda** [comment]
@nr-kkenney code owners is a great idea...

**Comment by nr-kkenney** [comment]
another potential awkwardness i just thought about is that there is no way to specify per branch ownership. because we use gitflow, there is the pr to develop that would require an owner, then the pr to main that would also require an owner -- even though these are potentially the same change set and we would feel comfortable just merging.

**Comment by jpvajda** [comment]
@nr-kkenney interesting, did we have consider a [trunkbased ](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development) workflow?

**Comment by nr-kkenney** [comment]
@jpvajda using gitflow in this repo was long before me. this also isn't a dealbreaker, i was just stream of conscious-ing my thoughts into the ticket so i don't lose em.

**Comment by nr-kkenney** [comment]
This ticket should be all wrapped up.

For this repo, I:
- added a codeowners file that has dev-enablement as the owners for .github folder, all javascript files, and the yarn.lock file.
- setup branch protection for the develop branch requiring at least one code owner approval if a pr touches a file that has a code owner.

Aside from that, met with docs team representative to discuss if they wanted to also use code owners and they did seem intrigued but wanted to look into further on their own. So at the moment, I can't think of anything else we want want to add to the CODEOWNERS file.

Follow-up, next steps:
- we might want to set up / explore [code review assignments](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team).

Here is the issue for code owners in newrelic-quickstarts: https://github.com/newrelic/newrelic-quickstarts/issues/554
