### ISSUE TITLE
translation pr follow up - specific issues / bugs

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#3677]
## Summary

This ticket is kind of a follow up to #3620. As part of that work, I had to manually fix up a couple of files which had 'invalid' content, where invalid means that the site wouldn't build based on the file we created. This implies that we have some deserialization bug(s) since we are generating content that should be valid (and builds), but actually doesn't.

### Example 1 - [src/i18n/content/jp/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx](https://raw.githubusercontent.com/newrelic/docs-website/0b5a8ed8b05b1e750375e2559f30d880c8296dff/src/i18n/content/jp/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/enable-serverless-monitoring-aws-lambda-legacy.mdx):

in japanese, the erroring line is:
```
title={<InlineCode>'dimensions(include: &#x7B;attributes}, exclude: &#x7B;attributes})'</InlineCode>}
```
and in english:
```
title={<InlineCode>{'dimensions(include: {attributes}, exclude: {attributes})'}</InlineCode>}
```

So when we deserialize the japanese content, something funky is happening to the brackets. we lose a pair of them, and also have the hex representation of the left bracket, rather than the bracket symbol itself.

### Example 2 - [src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/update-infrastructure-agent.mdx b/src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/update-infrastructure-agent.mdx](https://github.com/newrelic/docs-website/blob/0b5a8ed8b05b1e750375e2559f30d880c8296dff/src/i18n/content/jp/docs/infrastructure/install-infrastructure-agent/update-or-uninstall/update-infrastructure-agent.mdx): 

erroring lines:
```
title={<><img src={windowsServerLogoSmall} title="Windows Server" alt="Windows Server icon" style={{ height: '32px', width: '32px', verticalAlign: 'middle' }}>で更新する</img>Windows Server（32ビット）</>}
```
and
```
title={<><img src={windowsServerLogoSmall} title="Windows Server" alt="Windows Server icon" style={{ height: '32px', width: '32px', verticalAlign: 'middle' }}>で更新する</img>Windows Server（64ビット）</>}
```

what they should be:
```
title={<>で更新する<img src={windowsServerLogoSmall} title="Windows Server" alt="Windows Server icon" style={{ height: '32px', width: '32px', verticalAlign: 'middle' }}/>Windows Server（32ビット）</>}
```
and
```
title={<>で更新する<img src={windowsServerLogoSmall} title="Windows Server" alt="Windows Server icon" style={{ height: '32px', width: '32px', verticalAlign: 'middle' }}/>Windows Server（64ビット）</>}
```

In this example, the japanese text which previously lived as a sibling to the img was moved to be a child of the img tag, which is not a thing.

## Acceptance Criteria
- [ ] TBD

**Comment by aswanson-nr** [comment]
Just wanted to update and say that I'm seeing `Example 1` in this PR https://github.com/newrelic/docs-website/pull/5037
