### ISSUE TITLE
Issue: Set up network flow data monitoring

### ISSUE THREAD

**Issue by thedownwardspiral** [newrelic/docs-website#3701]
### Tell us what you need

One of the flags is incorrect and causes an error when starting the container.  "-flow_only=true results" in the error "flag provided but not defined: -flow_only".  This flag isn't listed at kentik/ktranslate.

Also, since both this and the SNMP containers are using "--net=host", you get an error "Error running meta server: listen tcp 0.0.0.0:8083: bind: address already in use" when trying to run both at the same time.  I worked around this by publishing 162/udp to the SNMP container since it should only need to receive SNMP traps and then publishing port 9995/udp for the flow container running IPFIX.

The inbound data port is listed as TCP 9995.  Netflow uses UDP.

Finally, I've been able to run a single instance of the flow container with nf.source=ipfix and it receives IPFIX and v9 flows correctly.  The documentation indicates that I have to run a separate container for each (unless I'm just misinterpreting it).

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-flow-monitoring/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Het, @thedownwardspiral! Thanks for reaching out! I'll pass on these questions and get back to you.

**Comment by nr-jbiggley** [comment]
Thanks for the excellent feedback, @thedownwardspiral. I've provided some insights and questions below to help solve these issues.

**1) -flow_only=true**
Can you paste your docker run command? Make sure your remove your API key and account ID before doing so! -flow_only is a supported flag in the YAML and _should_ be supported flag when launching the container. However, there is a mismatch. I'll get an issue created and tracked. You can use flag _-snmp_flow_only_ to start the container.

**2) Overlapping ports**
There is an [closed issue](https://github.com/kentik/ktranslate/issues/115) on this 8083 in use for multiple containers when using discovery. I will get a similar issue opened to look at the implications of using a random port for non-discovery containers. In the interim, you can set _--metalisten=""_ when launching the container to randomize the port.

**3) TCP vs UDP**
Thanks for that catch! We'll update the docs.

**4) IPFIX & Netflow v9**
You are correct. You can collect both IPFIX and NetflowV9 on the same container using this solution. However, IPFIX and NetflowV9 have slightly different schemas and changes to the fields, etc. _could_ result in a breaking change. If you are interested, here is the [line in the code](https://github.com/kentik/ktranslate/blob/7a70686d2da3b928fca78cc3b55e9a035d6eb7a8/pkg/formats/netflow/netflow.go#L91) that validates your observation.

**Comment by x8a** [comment]
@nr-jbiggley already fixed some of the issues you pointed out in #3709.

**Comment by x8a** [comment]
Hi, @thedownwardspiral! I'll close this issue later this week if you don't have any more questions. Fell free to reopen this one at any time or open a new one with new questions. Thank you for the feedback!
