### ISSUE TITLE
Issue: Write synthetic API tests

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3705]
### Tell us what you need

>New Relic uses the http-request module internally to make HTTP calls to your endpoint and validate the results.

[http-request](https://github.com/request/request)

As far as I can tell from the documentation, New Relic Synthetics' API Test Monitor uses the
The http-request module is used.
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests/

However, the Github page for the http-request module states the following
https://github.com/request/request
"As of Feb 11th 2020, request is fully deprecated. No new changes are expected to land. In fact, none have landed for some time." 

Synthetics also supports newer runtimes, so you can use
I think this page needs to be rewritten.
https://docs.newrelic.com/jp/docs/synthetics/synthetic-monitoring/using-monitors/manage-monitor-runtimes/#v06

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks @qryuu - let me get in touch with the team to clear this issue!

**Comment by urbiz-nr** [comment]
Hi again @qryuu! The team is aware of this little inconsistency and plans to replace the module sometime this fall. Since the module works we don't want to mention anything because we don't want to prevent people from using it in the meantime. We'll update the docs with the new info once it's done. Hope this helps!
