### ISSUE TITLE
404 missing content / bad link for 'Mobile Apps' from the 'Instrument Everything' page

### ISSUE THREAD

**Issue by liamhurrell** [newrelic/docs-website#3706]
### Tell us what you need

* Bad link for 'Mobile Apps' from this page: https://docs.newrelic.com/docs/full-stack-observability/instrument-everything/
* This is the missing resource: https://docs.newrelic.com/docs/mobile/table-of-contents/

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile/table-of-contents/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 92.0.4515.159
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @liamhurrell - we'll look into it.

**Comment by urbiz-nr** [comment]
Closed #3706 via #3784.
