### ISSUE TITLE
Request for ability to add h3s and collapsers to doc's right-nav  

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#3713]
### Is your feature request related to a problem? Please describe

Currently, our h2s are automatically added to the right-navigation. We used to have the ability to, on one-off basis, add specific h3s or h4s to the right nav. This often comes up for longer docs where we have to nest some h3s or h4s under a broader h2 category but would very much like to have those exposed on right nav for customers to be able to skim the content easily. 

While theoretically some of these docs could be restructured, that also is easier said than done, and I thought maybe this could be an easy fix for us in terms of having something like: `### Account management procedures [#account-mgmt] right-nav=true`. Or something.  

### Describe the solution you'd like

* Add h3s to right nav
* Add collapsers to right nav
* Nest them visually under the appropriate h2

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-10
