### ISSUE TITLE
Issue: Manage data retention

### ISSUE THREAD

**Issue by newtob-DB** [newrelic/docs-website#3724]
Hi,
The Metric Data Rollup language could be improved:
https://docs.newrelic.com/docs/telemetry-data-platform/manage-data/manage-data-retention/#metric-data-rollup

See this quote from the page:
"Then aggregated to 1-hour roll-ups for 90 days"

Oisin McColgan @newrelic suggests that it's not just 90 days their rolled up to 1-hour, he suggests this 1 hour roll up lasts for as long as the metrics are kept, most for 13 months, some indefinitely. That said, i'm not sure what these bullet points should say. Could you clarafy?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/manage-data/manage-data-retention/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for getting in touch, @newtob-DB! I'm sharing this with the team so we can work on improving and clarifying the docs.

**Comment by bradleycamacho** [comment]
@urbiz-nr @mmfred Could one of you update the status of this issue? Thanks!

**Comment by mmfred** [comment]
I'm working on this now. Kept getting pulled off to other things.

**Comment by mmfred** [comment]
@newtob-DB - Thanks again for your request. I hope the updates pushed today are a bit clearer.
