### ISSUE TITLE
Issue: How alert condition violations are closed

### ISSUE THREAD

**Issue by carrieschmid** [newrelic/docs-website#3730]
### Tell us what you need

https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/how-alert-condition-violations-are-closed/#close-automatic

My question is about this passage:

For example: If the violating behavior is "Apdex score below 0.80 at least once in 5 minutes," then the violation will automatically close when the Apdex score is equal to or higher than .80 for 5 consecutive minutes. The same applies to a "for at least x minutes" threshold: x minutes of non-violating behavior are required to automatically close the violation.

Here's my understanding: 

"at least once in" means the signal must hit the opposite threshold of the condition once in the designated period
"for at least" means the signal must hit the opposite threshold of the condition for the full duration in the designated period

### Anything else you'd like to share?

Where else is this configuration explained? Seems like it would be helpful info to have here:
https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/set-thresholds-alert-condition/

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/how-alert-condition-violations-are-closed/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @carrieschmid! Thank you so much for your question 🙌🏻.

In the case of the following violation: `Apdex score below 0.80 at least once in 5 minutes`, it means that a violation will be open when this happens. Therefore, it'll close when the opposite happens, that is,` when the Apdex score is equal to or higher than .80 for 5 consecutive minutes`. Let me know whether this is still not clear.

About adding this information in how to [set thresholds for an alert condition](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/set-thresholds-alert-condition/). Setting thresholds and how alert condition violations are closed are two different features, so they need to be in separate docs. Let me know what you think about it.

**Comment by carrieschmid** [comment]
Thanks for your message. I understand how the recovery period works. Can you explain the difference between these two configurations?
`for at least`
`at least once in`

Also, I understand this configuration impacts how violations close. But can you explain why choosing this configuration would **not** be part of setting a threshold? It's a choice made during set-up right?

**Comment by x8a** [comment]
Sure!
- `for at least`: Consistently during a period of time.
- `at least once in`: Once in a set period of time.

You need to consider that the violations will automatically close when the opposite condition to the one you configured for the violation to be open comes true.

The thresholds are directly related to the violations, but they are treated independently. That is, violations close automatically by checking the conditions configured through thresholds, but you can also manually close violations. All of this comes together previously, when you [configure a condition](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-alert-conditions/).

Let me know if you have any more questions.

**Comment by carrieschmid** [comment]
Thanks for the explanation on the difference between the thresholds.  Please consider putting this in the docs, as it would be helpful for customers and those of us doing support.
