### ISSUE TITLE
Instrument the new Tessen library version that manages the Amplitude session on the Docs site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3731]
Related [Trello Issue](https://trello.com/c/EOal4dV6/52-docsnewreliccom-instrument-the-new-tessen-library-version-that-manages-the-amplitude-session-on-the-docs-pages)

# Solution

1. We need to upgrade to the latest Tessen library and make sure the the basic page navigation events are being fired and that they get to Amplitude

2. We need to send a new Page Loaded event for every page user visits.

# Acceptance criteria

- [x] Update tessen version via a theme bump
- [x] Once completed we can ask `Luka Eterovic` to help us validate this change is working

**Comment by jpvajda** [comment]
we had one more thing to confirm with Luka...

**Comment by roadlittledawn** [comment]
just asked Luka to verify in #wizards-amplitude
