### ISSUE TITLE
Research Workflow status monitoring  for Github workflows failure

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3734]
We seem to have failures in our github workflows that suprise us from time to time. Is there a way to setup monitoring an alerting of these workflows so we know when they are failing faster then someone reporting a hero issue, or us discover it by seeing a broken site feature?

### Considerations

- [ ] Could we use [workflow status badges ](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/about-monitoring-and-troubleshooting)a simple solution to this problem? 
- [ ] Can we show the [workflow statuses](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge) on our Readme files?
- [ ] We can probably to hook up the slack channel to each workflow we care about (maybe all of them)

**Comment by roadlittledawn** [comment]
i also wonder if we could use a newrelic agent to report an error (or a custom event) and then set an alert up to notify on that. many of our workflows run node, so maybe adding the node agent in and a `newrelic.noticeError` call or something?
