### ISSUE TITLE
Add RSS feed for each agent's release notes

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#376]
## Summary
Similar to current site, each agent's (including mobile) release notes includes an RSS feed listing the 15 most recent release notes. Essentially any folder in `docs/release-notes` that contains release note files should have an RSS feed.

The feed includes the following for each item:
* title
* link
* description
* pubDate
* content:encoded
* guid

RSS icons are displayed:
* on the agent's release note index page
* on each agent's single release note page

## Acceptance criteria
- [ ] Each folder that contains release note files inside of `docs/release-notes` has an RSS feed at a dedicated URL
- [ ] Each feed is validated via [W3 feed validator](https://validator.w3.org/feed/)

## Helpful links
[RSS feed for PHP agent release notes](https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/feed)

**Comment by zstix** [comment]
💯  If we figure this out, it would be great to provide a feed for the `What's new` posts too!

**Comment by zstix** [comment]
We could take advantage of [gatsby-plugin-feed](https://www.gatsbyjs.com/plugins/gatsby-plugin-feed/) which works similar to the JSON feed.
