### ISSUE TITLE
Example images are missing from some docs pages

### ISSUE THREAD

**Issue by throck** [newrelic/docs-website#3764]
Images on this page that include working examples are incorrectly linked and do not render, for [example](https://docs.newrelic.com/docs/integrations/prometheus-integrations/view-query-data/translate-promql-queries-nrql/#prom-ql-example):

![image](https://user-images.githubusercontent.com/1069674/131863332-2ba4e352-5be8-4bc3-b33c-eba1af1afcac.png)

I see them in [docs-website](https://github.com/newrelic/docs-website/tree/develop/src/content/docs/integrations/prometheus-integrations/view-query-data/images) but they probably aren't getting published (or are being pushed to a static location?)

### Doc information

* https://docs.newrelic.com/docs/integrations/prometheus-integrations/view-query-data/translate-promql-queries-nrql/
* **OS**: Mac OS 10.14.6
* **Browser**: Chrome 92.0.4515.159
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks for letting us know, @throck! I'll look into getting these fixed.

**Comment by paperclypse** [comment]
I tried to fix this in this PR (https://github.com/newrelic/docs-website/pull/3777), but there's nothing obviously, technically wrong with the syntax for these images. There's some deeper, underlying technical issue that's worth investigating. If it's happening here, it's probably happening elsewhere on the site.

**Comment by jpvajda** [comment]
After chatting about this issue the team wants to take a look at what may be occurring here and if there is a better to programmatically prevent this from occurring. It's not clear how many pages could be impacted but we agreed it's not a P1 at the moment.

**Comment by roadlittledawn** [comment]
seems to have something to do with being inside a `Collapser`. locally, i moved the image md at the top of the file and it rendered

**Comment by roadlittledawn** [comment]
using a straight up `<img>` tag works inside a collapser as well

**Comment by paperclypse** [comment]
Since we don't really want to move the images, the guidance here would be: If an image doesn't render, try an <img> tag?

**Comment by paperclypse** [comment]
@roadlittledawn Can you answer my question please? Thanks!

**Comment by barbnewrelic** [comment]
happened again and was reported in documentation slack channel today. thanks for any suggestions what to do!

**Comment by roadlittledawn** [comment]
@paperclypse yeah i'd say give it a shot to use `img` tag inside the collapser. we can keep this issue around to try and dig deeper and hopefully fix it

**Comment by austin-schaefer** [comment]
@roadlittledawn : This would be a good one to flag for a sustaining ticket.

**Comment by roadlittledawn** [comment]
for clarity, here's what worked for me:
```jsx
import promqlImgSrc from './images/PROMQL-query-2.png';

  <Collapser
    id="prom-ql-example"
    title="PromQL-style query example"
  >
   <img src={promqlImgSrc} />
</Collapser>
```

**Comment by roadlittledawn** [comment]
@paperclypse i'm curious. do you know of an example on the site where image markdown does work inside a `Collapser`?

**Comment by paperclypse** [comment]
@roadlittledawn I don't.

**Comment by paperclypse** [comment]
Your syntax caused my local build to crash @roadlittledawn.

```
 ERROR 

unknown: Unexpected token (311:7)

  309 | <p>{`As the following chart 
shows, all the unique timeseries are 
aggregated into one unique timeseries 
by default:`}</p>
  310 | <img
> 311 |
src={./images/NRQL-example-3.png}
      |        ^
  312 |   style={{width: '100%'}}
  313 | />
  314 | <figcaption>



  SyntaxError: unknown: Unexpected toke
  n (311:7)
    309 | <  mp>{`As the follo  wing 
chart shows, all the unique time
series are aggregated into one unique  
 timeseries by default:`}<  [39m/p>  
    310 | <  mimg
  > 311 |  39m   src={.  /images/NRQL
 -example-3.  [39mpng}
        |          m^
    312 |   style=  39m{{width: '100%'
  m}}
    313 | /  m>
    314 | <  mfigcaption>
    ```

**Comment by roadlittledawn** [comment]
not sure what your MDX file looked like, but this build worked for me: https://github.com/newrelic/docs-website/pull/5303

https://build-3880db80-b527-4159-91e8-30c95fa015a8.gtsb.io/docs/infrastructure/prometheus-integrations/view-query-data/translate-promql-queries-nrql/

**Comment by paperclypse** [comment]
Maybe it's a local build issue. It crashes every time on this HTML syntax.
