### ISSUE TITLE
On this page titles in search results are clickable and link to the docs page header

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3793]
![Screen Shot 2021-09-03 at 2 20 16 PM](https://user-images.githubusercontent.com/1395158/132061904-fb6f8023-61f7-4960-9164-b96dc4748c60.png)

**Comment by roadlittledawn** [comment]
not sure this is possible in current setup. we get those section heading values from swiftype, so we don't know what the ID for each heading is
