### ISSUE TITLE
Issue: Set thresholds for an alert condition

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3803]
### Tell us what you need

The minimum time interval is listed, but
Is there any information about the Max time interval that can be set?

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/set-thresholds-alert-condition/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @qryuu! I'll ask about this and get back to you. Thanks for reaching out!

**Comment by x8a** [comment]
The maximum time interval is 120 minutes.

Please let me know whether you have any other questions.

**Comment by bradleycamacho** [comment]
@x8a Should we add that info to the doc above? If not feel free to close this issue!

**Comment by x8a** [comment]
I added the info with PR #3985. Thanks for your question again, @qryuu.
