### ISSUE TITLE
Issue: Collect custom metrics (APM, browser, mobile)

### ISSUE THREAD

**Issue by brianbegy** [newrelic/docs-website#3822]
https://docs.newrelic.com/docs/agents/manage-apm-agents/agent-data/collect-custom-metrics/

Says "Always start your metrics with Custom"

But maybe that doesn't apply in New Relic agents starting with 6?

https://docs.newrelic.com/docs/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-metrics/#metric_names

Which set of NewRelic docs is right?

**Comment by barbnewrelic** [comment]
@brianbegy  Thanks for reporting this! You're right, it is confusing! This will take a bit of digging to sort out, so I have created a Jira to resolve your question and update the docs as applicable.

**Comment by barbnewrelic** [comment]
DOC7336

**Comment by bradleycamacho** [comment]
@barbnewrelic Can you let us know the status of this issue? Thanks!

**Comment by barbnewrelic** [comment]
As noted in the comments, a Jira has been created for this work.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
