### ISSUE TITLE
Issue: Diagnostics CLI (nrdiag)

### ISSUE THREAD

**Issue by greenszpila** [newrelic/docs-website#3837]
### Tell us what you need

Would be helpful to have a section that covers Diagnostic CLI/NRDiag for Windows.

### Anything else you'd like to share?

Here are the steps that have worked for me:

1. Edit `C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yaml`
2. Add a log file path and enable verbosity by adding below two lines to the `newrelic-infra.yaml`

```   
    log_file: C:\Program Files\New Relic\newrelic-infra\newrelic-infra.log
    verbose: 1
```

 3.  [Download the latest version of New Relic Diagnostics](https://download.newrelic.com/nrdiag/nrdiag_latest.zip)  
 
```
$source  =  'https://download.newrelic.com/nrdiag/nrdiag_latest.zip'
$destination  =  'C:\Program Files\New Relic\newrelic-infra\nrdiag.zip'
Invoke-RestMethod  -Uri  $source  -OutFile  $destination
```

4. Extract the .zip file

```
Expand-Archive  -Path  'C:\Program Files\New Relic\newrelic-infra\nrdiag.zip'  -DestinationPath  'C:\Program Files\New Relic\newrelic-infra\'
```
5. `cd` to the extracted path `C:\Program Files\New Relic\newrelic-infra\nrdiag\win`
6.  Run `.\nrdiag_x64.exe  -suites  infra:debug -a ATTACHMENT_KEY`  -y

**After finishing the process, please remember to Disable verbose logging by setting  [`verbose: 0`](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/configuration/configure-infrastructure-agent/#verbose)  in  `newrelic-infra.yml`.** 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
@greenszpila will create a PR to add these steps. Thanks a lot!
