### ISSUE TITLE
Helm documentation link gives 404

### ISSUE THREAD

**Issue by doctornkz** [newrelic/docs-website#3838]
### Tell us what you need
Link gives 404 status code.

Page : https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure/#install-amazon-eks

Link : https://docs.newrelic.com/docs.newrelic.com/docs/integrations/kubernetes-integration/installation/install-kubernetes-integration-using-helm/

Link context : 

```
Use automated installer
We encourage you to use our automated installer for servers, VMs, and unprivileged environments. The automated installer can provide you either a Helm command with the required values filled, or a plain manifest if you do not wish to use Helm. It also features great customizability and full control over which features and dependencies are enabled. If you are installing our integration on a managed cloud, please take a look at these preliminary notes before proceeding.

Alternatively, we also offer fully manual instructions for deploying our integration using Helm. 
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/404.html
* **OS**: Linux
* **Browser**: Chrome
* **Device**: PC/Desktop

**Comment by x8a** [comment]
Thanks for spotting this, @doctornkz! I fixed the broken link in #3840.
