### ISSUE TITLE
Implement One Trust on Docs Site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#3848]
Relates to: https://github.com/newrelic/gatsby-theme-newrelic/issues/347

One Trust is a product that is currently going to be used by New Relic to manage cookie acceptance and GDPR compliance,  we'll need to turn this on for the Docs Site once the related issue is resolved and after the I/O Launch.

### References

https://www.onetrust.com/products/cookie-consent/

### Acceptance Criteria

- [x] Confirm with David Hwang if this vendor is selected and what the implementation timeline is
- [ ] Get access to one trust admin panel in OKTA (it may now be available, check with `ask-it`)
- [x] obtain `onetrust ID` for the Docs Site
- [x] Work with David and Analytics team: `Zoe Zhou` to validate analytics and other is still working
- [x] 🍪 🍪 testing successful

### Other considerations 🍪 

-  [x] Does the cookie tracking component just go away after a period of time, we should keep prompting a user until they accept / deny ideally?
- [X] Can we make the GDPR prompt more pronounced, and more of an overlay effect where the site isn't usable until they accept / deny.
- [X] What type of custom CSS is required to ensure the js widget matches our site design
>  if a user declines all cookies, we get no data  but we default to opting in all users unless they explicitly opt out. 
>  one set of opt in or out applies to all sites with one trust, so the user only has to do this once for all external sites.
> marketing will set the user exp. for the one trust dialog we just render whatever is provided to us.

- [x] Dark mode is cookie-dependent, how will this work impact it?

> see above about essential cookies to One Trust. 

- [x] We are also looking at using a cookie to pass pack information (identifier of pack) to the signup flow, so we’ll need to consider that as well

> see above about essential cookies to One Trust. 
> we can test this case in our system test plan.

- [x] How does this get added to the page (is there a JS snippet)?
 > yes
- [x] Do we understand the performance impact of adding this?
> we can run before an after lighthouse tests
- [x] If we add this snippet, can we remove any other cookie code (does this replace something)?
> we can remove our custom cookie component.

**Comment by roadlittledawn** [comment]
this was deployed on docs site...last week i think? we didn't run lighthouse reports and we still don't have access to OneTrust though. are we okay to close, @jpvajda ?
