### ISSUE TITLE
Automatically add a unique & consistent `docsID` attribute to what's new posts

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#385]
## Description
The Java service that consumes "what's new" posts and serves them in the product relies on each post having a unique & consistent `docsID` value (this is used for ElasticSearch purposes).

When we migrate posts, we add that field to the frontmatter, but _new_ posts (post-drupal) wont have those IDs and we shouldn't ask the user to provide them. We should find a way (perhaps with a GH action?) to generate and save these IDs so that our two endpoint (below) scan serve a `docsID` for _all_ posts.

* https://docs-preview.newrelic.com/api/nr1/content/nr1-announcements.json
* https://docs-preview.newrelic.com/api/nr1/content/nr1-announcements/ids.json

**Comment by jerelmiller** [comment]
> perhaps with a GH action?

The only problem with a GH action is that it may write those values too late in the process. Likely we'll want something that generates these IDs at build time. We will also probably want to save them in a file somewhere so that they are stable between builds.
