### ISSUE TITLE
Issue: Authentication domain settings: SAML SSO, SCIM, and more

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#3852]
Link to [Auth0](https://developers.auth0.com/newrelic) is not available.
The developer plan is might be closed but free plan is now available.

**Comment by paperclypse** [comment]
@shinji-newrelic thanks for filing this issue. Do you mind expanding a little more on what you mean? 

Are you saying that we should be removing the Auth0 link from this doc? https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more/

**Comment by paperclypse** [comment]
@zuluecho9 Do you have any thoughts on this one?

**Comment by shinji-newrelic** [comment]
@paperclypse 
Since I don't know what is shown previously, it is difficult to say how to fix it.

However I think you can user either url described in below;

- https://auth0.com/
This is top page of auth0
- https://marketplace.auth0.com/integrations/new-relic-sso
This is new relic integration page but this integration doesn't work with new account model.

**Comment by zuluecho9** [comment]
@paperclypse I'll handle this one! I

**Comment by zuluecho9** [comment]
Fixed with https://github.com/newrelic/docs-website/pull/3887.
