### ISSUE TITLE
[Translation] Have translation workflow alert stakeholders when translation PR is created

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#3853]
## Summary
Currently, when the translation workflow creates a PR as the last step of the translation process, the content team aren't alerted and aware that they have a PR they need to review. To make it clearer, the workflow should alert them when the PR is created so they can review it.

The action we currently use to generate PRs ([create-pull-request](https://github.com/peter-evans/create-pull-request)) has a `reviewers` option we can pass in to specify reviewers for the PR. It would look similar to [this line](https://github.com/newrelic/docs-website/blob/82c7feb816287c0788d0c9d567217b8bda6d25f3/.github/workflows/check-translations-and-deserialize.yml#L73), except `reviewers` rather than team.

On the feature branch, the deven team has already been added as a reviewer.

## Acceptance Criteria
- [x] ~Create a group in github and add relevant stakeholder users to it~
- [x] Translation workflow should be updated to add reviewer
  - add it to both jobs. one job is for machine translation, the other is human.

### Stakeholders
 - DevEn team
 - @jmiraNR 

<details>
  <summary>Previous Considerations</summary>

  Some quick ideas from the group:
* ~post to slack channel~
* add people as reviewers to the pr
* comment @ people in the pr
* other options not considered above

</details>

**Comment by jpvajda** [comment]
solves this https://github.com/newrelic/docs-website/issues/4153

**Comment by aswanson-nr** [comment]
If Github mentions are enough of a notification, then this https://github.com/marketplace/actions/issue-label-notifier action might be perfect!

**Comment by jpvajda** [comment]
@aswanson-nr That approach will work as github sends email notifications to users which is a good way to get notified.

**Comment by nr-kkenney** [comment]
@clarkmcadoo i think you mentioned groups in github. did you have an idea of what this would look like?

i don't see a grouping of people different to teams, and im not sure if we want another team or for julien to be added to our team.

**Comment by nr-kkenney** [comment]
going to remove the team / group acceptance criteria since julien has been added as an individual reviewer, and we don't want to create a new team of just him, or us + him.

julien did mention another hire coming onboard and being able to review translation PRs, but its easy enough to just add them individually when the time comes.
