### ISSUE TITLE
[DOCS] Referrer tracking in Tessen Events

### ISSUE THREAD

**Issue by zoezhou1113** [newrelic/docs-website#3863]
Relates to https://github.com/newrelic/docs-website/issues/2841 and https://github.com/newrelic/docs-website/issues/1816

### Description

The referrer tracking (context.page.referrer) in Tessen is only working for the signup button, but it’s not working for other links directing traffic to the other NR domains. 

It's also not working for internal links on docs.newrelic.com.

### Steps to reproduce

1. Click on Community on the navigation in the header
2. Check referrer using the Segment Chrome extension

### Expected behavior

context.page.referrer = docs.newrelic.com

### Screenshots

![image](https://user-images.githubusercontent.com/80297589/132867844-8eeeb328-aec5-47f2-82c7-834156456526.png)
### Additional context

Please make the same updates for developer and opensource

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by jpvajda** [comment]
This seems to be the 3rd case of this occurring...

**Comment by LizBaker** [comment]
we set 'no-opener no-referrer' on all links as a best practice for security purposes. this isn't really an issue if the thing we're linking to is internal which almost all of these links are, but this is why it keeps coming up, we set that by default. modern browsers are good with just no-opener which gives us the security we need, but some legacy browsers only listen to no-referrer. however.. as long as we're linking internally i think we could makeover all our link components in the theme, the danger would be if we linked to a site that had been compromised

**Comment by roadlittledawn** [comment]
also FWIW re: internal links. we do manually set a `referrer` path in `properties. referrer` when a user arrives on a docs page from a previous doc page if you wanted to use that temporarily in any queries.

**Comment by LizBaker** [comment]
@zoezhou1113 we made the change for this but it's part of a package we don't want to update in the sites until our upcoming release which is in 2 weeks. when we release, the fix will automatically get brought in

**Comment by jpvajda** [comment]
To add a little context, in the global theme we have made our changes for the new I/O nav item, so we are going to deploy that change by Sept 29th, with this change we'd also resolve this problem. So it will be resolved by the time we launch I/O @zoezhou1113
