### ISSUE TITLE
[Docs] The mdx workflow passes but the Gatsby build fails

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#3865]
### Description

We had a hero request earlier this week were a Gatsby Build was failing due to mdx formatting issues, but the `verify-mdx` workflow was passing without an issue. The error in the build logs was also misleading, as it referred to the line after the one that the issue was on which the contributor had not touched, so it was difficult to track down.

Putting up a Draft PR to show an example of this for context
#3866

### Acceptance Criteria
 - [ ] Investigate why the Build is failing but the `verify-mdx` workflow isn't
 - [ ] Fix the workflow so it catches issues like this that would otherwise cause Gatsby Build to fail

**Comment by jpvajda** [comment]
What is the urgency on this? Is there a slack convo I can look at it set priority?

**Comment by jpvajda** [comment]
@roadlittledawn might know...

**Comment by rudouglas** [comment]
I'm currently editing the Description A/C @jpvajda you're too quick 😂  i'd say p3 though

**Comment by roadlittledawn** [comment]
i have to take closer look, but i _think_ it may be because `@mdx-js/mdx` (the package used by `verify_mdx.js`) doesn't account for the frontmatter when converting to jsx.
