### ISSUE TITLE
Issue: Add users to SAML accounts (original user model)

### ISSUE THREAD

**Issue by shhudspethnr1** [newrelic/docs-website#3869]
### Tell us what you need

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

There is a dead link under Requirements. 
Clicking Auth0 goes to the site below and gets "Unknown host: developers.auth0.com" error. 
http://developers.auth0.com/newrelic

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts/saml-single-sign/add-users-saml-accounts/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
This is related to (and is a duplicate issue) #3852.

@shhudspethnr1 Thanks for letting us know. We're looking into it.

**Comment by paperclypse** [comment]
@zuluecho9 This is related to the other one you're working on, issue #3852.

**Comment by zuluecho9** [comment]
Closed with https://github.com/newrelic/docs-website/pull/3887.
