### ISSUE TITLE
Add delete entities to Remove applications from New Relic doc

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#3873]
We got this feedback in the documentation channel:

Currently, we have some issues with deleted apps still showing up in the UI, and the option that works most consistently right now is one that is not listed in our main Remove applications from New Relic (https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/remove-applications-new-relic/) doc. The option that works most consistently right now is to [Delete entities using NerdGraph](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-entities-api-tutorial/#delete-entities). Can we add that to the main doc? I have talked to the AppEx team and we agreed this would be helpful until they are able to release a fix.

**Comment by zuluecho9** [comment]
Created this PR to address this. https://github.com/newrelic/docs-website/pull/3900
