### ISSUE TITLE
Request: NRQL syntax, clauses, and functions

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3875]
### Tell us what you need

There are no in-page links for the latest( ) function.
The other functions have links, so please set a link for latest( ) as well.

>https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#func-latest 
### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/
* **OS**: Windows 10
* **Browser**: Chrome 93.0.4577.63
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for catching this, @qryuu! It will be fixed in #3876.
