### ISSUE TITLE
Question: Import, export, add, and share dashboards and charts

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3878]
### Tell us what you need

Is the URL retrieved by `Get chart link` a generic one that includes parameters such as time picker?
Or will a random URL be generated for each link retrieved, and the same parameter will be a different URL?

Can you change the time setting of the Chart link and use it around?
Or do I just share what I'm seeing?
I would like to see a clear description of the Chart link specifications so that we can consider how to use it.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/dashboards-charts-import-export-data/
* **OS**: Windows 10
* **Browser**: Chrome 93.0.4577.63
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hi @qryuu, thanks for getting in touch! 

The URL corresponds to an embedded view of the chart, you just share what you're seeing. Unfortunately, we can't change the time setting of the chart link and use it around. 

I'm reaching out to the Engineering teams to learn more.

Hope this helps.

**Comment by lucascepeda-nr** [comment]
Hi @qryuu ! 

The link generated already contains the value selected on the timepicker, but you can change it once you open the link. 
The URL changes every time to generate a new chart link, even if the timepicker selection hasn't changed. 
On the chart link URL, you can't change the NRQL query that feeds the charts, but you can select a different time range. 

You can also explore the option of using NerdGraph: https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api/

I hope that answers your questions!
