### ISSUE TITLE
Issue: Microsoft SQL Server monitoring integration

### ISSUE THREAD

**Issue by Julien4218** [newrelic/docs-website#3881]
### Tell us what you need

The NewRelic Microsoft SqlServer documentation should highlight the requirement that Sql Server Mixed authentication is required, since we need to have a username/password for the integration.

### Anything else you'd like to share?

Here is a Microsoft documentation illustrating how to change the authentication mode https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/change-server-authentication-mode?view=sql-server-ver15

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Closed with this PR: https://github.com/newrelic/docs-website/pull/3886
