### ISSUE TITLE
Kubernetes events/attributes not listed in the attribute dictionary causes confusion to customers

### ISSUE THREAD

**Issue by jake-codes** [newrelic/docs-website#3894]
Here's a quote from one team:

*Many times when we search for some column name in the attribute directory, we don’t find them but they actually exist in some table. For eg: “isReady” is the column name in one of the table(K8sPodSample) but I didn’t find that when I Searched in attribute directory. https://docs.newrelic.com/attribute-dictionary/?attributeSearch=isReady . How does the attribute dictionary actually work?*

### Tell us what you need

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for getting in touch, @jake-codes! Our data dictionary doesn't include Kubernetes at the moment, I've created a jira to add it in one of our next sprints. 

In the meantime, you can read about our Kubernetes data here: https://docs.newrelic.com/docs/integrations/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data/  - hope this helps!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
