### ISSUE TITLE
MSSQL docs seems to have the word MySQL on it instead of MSSQL

### ISSUE THREAD

**Issue by vhenriq** [newrelic/docs-website#3897]
[MySQL Instance Settings](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/microsoft-sql-server-monitoring-integration/)

 yes

### How can we make our docs better? Review the link above where say MySQL and make sure if that is correct or is just a speeling that should be MSSQL instead of MySQL 

* Is something confusing? yes 
* Is something inaccurate or missing? yes
* Were you unable to complete a task? (What task?)
Review the link above where say MySQL and make sure if that is correct or is just a speeling that should be MSSQL instead of MySQL 

### Anything else you'd like to share?nope

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

**Comment by zuluecho9** [comment]
we actually have a pending edit related to this, so it's being fixed. thank you. https://github.com/newrelic/docs-website/pull/3886
