### ISSUE TITLE
Issue: Thread profiler tool

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/docs-website#3899]
### Tell us what you need

Under the [**Start the Profiler**](https://docs.newrelic.com/docs/apm/apm-ui-pages/events/thread-profiler-tool/#starting) section, the image link for the Thread profiler tool is broken. Instead it shows this:

![This is an image of the thread profiler.](./images/thread-profiler-session.png "Thread profiler overview) 

### Anything else you'd like to share?

![Screen Shot 2021-09-14 at 10 25 23 AM](https://user-images.githubusercontent.com/87386821/133304923-711e944a-fcf8-4756-a793-6fd5c5c4b670.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/apm-ui-pages/events/thread-profiler-tool/
* **OS**: Mac
* **Browser**: Chrome
* **Device**: MacBook Pro

**Comment by zuluecho9** [comment]
fixed with https://github.com/newrelic/docs-website/pull/3938. thanks @kaylareopelle.
