### ISSUE TITLE
Migrate docs content planning & approach

### ISSUE THREAD

**Issue by djsauble** [newrelic/docs-website#39]
## Summary

Pulling from the [IA diagram](https://whimsical.com/8tBfw8Squs35bvTo5acsC6), define the steps involved in migrating content so we can be sure the content is migrated successfully.

## Desired Behavior

1. Move APM, Browser monitoring, Logs, Understand dependencies, Infrastructure monitoring, Mobile monitoring, Serverless function monitoring, Synthetic monitoring under the FSO category
2. Combine "Using New Relic",  "New Relic One", "Query your data", and "Mobile apps" under a new category "New Relic in Practice"
3. Move Infrastructure Integrations SDK to the Developer site
4. Move API category to the developer site. Move remaining API intro docs under the TDP category.
5. Remove "Open-source licensed agents" section since all agents will be made open source
6. Change "Enable log management in New Relic" to "Logs in context"
7. Append "monitoring" to the relevant categories to comply with our platform hierarchy guidelines

## Possible Solution

1. The changes mentioned above should be reflected in the metadata for each document.
2. The way we represent the actual file hierarchy on disk should be flatter. Let's start with a single level of hierarchy (e.g. everything under FSO is a flat list). When this would result in ~100+ docs under a given category (e.g. release notes has 1,500+ docs), we can add a second layer of hierarchy.

## Additional context

Even though we anticipate additional changes to the IA over time, moving files on disk is a bit painful, so it's important that we get the buckets roughly correct at the start. If the hierarchy is too flat, finding the right file to edit will be painful, and if the hierarchy is too deep, small changes to the IA will require a restructuring of files on disk to avoid drift.

**Comment by jpvajda** [comment]
@djsauble I wanted to check in on this issue, it feels like we may be able to close it, as we are handling content as on-going effort.

**Comment by jpvajda** [comment]
@austin-schaefer similar question as I asked Daniel.
