### ISSUE TITLE
Build agent API method index pages

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#390]
## Summary
Some agents have an API category where all their methods are contained (1 method per page/file). There's an index page for that category that has a slightly different look and feel from regular index pages. We'd like to essentially replicate that on new site.

During migration when creating directory indexes, we want to detect if the directory contains API docs and if so, create this special kind of `index.mdx` for the directory. Also during migration, we'll want to use the `shortDescription` field to provide a method summary on the index page.

The API method index page should contain:
* intro text at top
* list (sorted by title, alphabetically) of relevant API doc titles, their short descriptions (to be added to API doc frontmatter), link to the method's page.

These should be automatically generated so a user does not have to edit this page manually if a method is added, removed, or a summary changes.

### Caveats
* The block of content above the list of methods isn't available via JSON. Will have to figure out how to get that into migration script

## Acceptance criteria
- [ ] Each agent API directory index file uses this type of index page

## Helpful links
[Example: PHP agent API index page](https://docs.newrelic.com/docs/agents/php-agent/php-agent-api)

**Comment by jerelmiller** [comment]
@roadlittledawn how would we get the intro text that shows up for these pages? I assume these pages aren't available in the JSON API and won't be migrated correct?
