### ISSUE TITLE
Add the correct format of SystemSample style query with Cloud Integration Metadata

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#3907]
### Is your feature request related to a problem? Please describe

When we're querying the Infrastructure Agent event (e.g. SystemSample) with Cloud Integration Metadata (e.g. aws account id), some style is not working always while the other style is working well.

### Describe the solution you'd like

According to our internal discussion GTSE-11129, the following style is the correct style as far as API Polling is enabled.

```
SELECT average(cpuPercent) FROM SystemSample FACET awsAccountId, label.Name, provider.ec2InstanceId WHERE awsAccountId = 'XXX' limit MAX TIMESERIES since 1 month ago
```

The following attributes are available:

- awsAccountId
- provider.<aws_service_metadata_name>
- label.<tag_key>

### Describe why this important to you

For example, the following query doesn't work sometimes but sometimes works well.

```
SELECT average(cpuPercent) FROM SystemSample FACET aws.accountId, tags.Name, aws.ec2.InstanceId WHERE aws.accountId = 'XXX' limit MAX TIMESERIES since 1 month ago
```

This is due to our product's limitation. Therefore, we should provide a clear specification of the correct query style.

**Comment by urbiz-nr** [comment]
Hi @tanaka-takayoshi - thanks for touching base! I'm talking to the Engineering teams to figure this one out. In the meantime, could you give us more details about when the query works and when it doesn't?

**Comment by tanaka-takayoshi** [comment]
It's complicated to identify this situation when the query works and when it doesn't. Actually, the engineering team just says "please use the correct format".  Therefore, we should have to explain the correct format.

**Comment by urbiz-nr** [comment]
I see. I'll get to it! Thanks!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
