### ISSUE TITLE
Determine impacts of Dora on existing Docs site documentation and how we'll account for those changes in the new site.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#391]
Dora is a project going on to make some product changes that will require some level of documentation changes right around the time our new site is about to go live, we'll want to better understand these changes and ensure we have a plan to support the updates as it will hit several product areas at once.

**Comment by zstix** [comment]
![dora](https://media.giphy.com/media/xVHstHCAs5JtK/giphy.gif)

**Comment by jpvajda** [comment]
There is a big spec doc for this available internally.. if anyone needs it.

**Comment by jpvajda** [comment]
@austin-schaefer Cool! So do we just plan on migrating the changes over as they come in?
