### ISSUE TITLE
docs-issuesIssue: shutdown_agent (Python agent API)

### ISSUE THREAD

**Issue by leifan89** [newrelic/docs-website#3916]
### Tell us what you need

Python agent docs for "shutdown_agent" mentions that the method takes an optional timeout int, but no unit is specified. 

Is the timeout value in seconds? minutes? The rest of the doc seems to suggest that it is seconds, but it is not clear.

### Anything else you'd like to share?

N/A

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/python-agent/python-agent-api/shutdownagent-python-agent-api/
* **OS**: Mac OS 10.15.7
* **Browser**: Edge 92.0.902.84
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
