### ISSUE TITLE
It's better to describe what is supported url syntax by Synthetics monitor

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#3928]
There are some types of synthetics monitor and some of them support simple monitor without code implementation e.g. ping, simple monitor and so on.

However there is no description what is supported url syntax. for example, is the query string is supported?
Please specify supported syntax by these synthetics monitors.

https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/getting-started/types-synthetic-monitors/

**Comment by urbiz-nr** [comment]
Hello @shinji-newrelic, thanks for getting in touch. We have [this doc](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors/) on how to add monitors, does it help? What else do you think would be useful?

**Comment by shinji-newrelic** [comment]
> Hello @shinji-newrelic, thanks for getting in touch. We have [this doc](https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors/) on how to add monitors, does it help? What else do you think would be useful?

Hello.
I cannot get clear understating about what is allowed as "URL". 
I'm happy if there are some url examples including query string like 'https://domain.com/path/?type=a'.

**Comment by urbiz-nr** [comment]
@shinji-newrelic, I've added a ticket to the tech writers' backlog to update the docs with the examples you request. Thanks for the suggestion!

**Comment by urbiz-nr** [comment]
Closed via #4922.
