### ISSUE TITLE
Issue: Synthetic monitoring: Aggregate monitor metrics

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#3929]
### Tell us what you need

The Synthetics documentation describes the NRQL for calculating SLAs.
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics/#generating_sla_in_insights

However, even after running this NRQL, the Apdex Score is still 0 and
It does not match the ApdexScore on the Synthetics SLA page.

Perhaps there is a problem with NRQL.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hello @qryuu - let me check with the team!

**Comment by urbiz-nr** [comment]
Hi @qryuu - we're fixing this in #3933. As you can see, it's a units issue.
