### ISSUE TITLE
Consider how we can do daily content migrations as we get closer to launch of the new site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#393]
As we get closer to launch it may behoove us to have  daily sync / migrate process firing automatically so that we be sure to bring in the latest content changes coming from the old site. this also should be aligned with the freeze of the drupal site when we no longer take content edits to the old site.

**Comment by tariqahmed** [comment]
Move to prod readiness MMF

**Comment by jpvajda** [comment]
This feels done to me, aren't we doing this? @roadlittledawn

**Comment by jerelmiller** [comment]
I'd say lets call this done. I'd rather do this by hand than automatically just to double check that we don't spot any weird issues. We'll be sure to try and sync periodically between now and launch.
