### ISSUE TITLE
Issue: Examples for Fintech with mixed resource zones

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#3942]
NR seems to have lost all references or example of Synthetics proxy situation with mixed network resources as typical in a enterprise Fintech customer.

Please add this example to the docs:
```
var proxyRules =
  {singleProxy: {host:"http://entproxy.mycompany.com"},
   bypassList:['s3.amazonaws.com','*.localcdn.com']
  }
$network.setProxyAdvanced(proxyRules)
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/set-proxy-settings-properties-scripted-monitors/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@GaPeppy is this something that would live in the examples section in this area? https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/set-proxy-settings-properties-scripted-monitors/#setproxy-advanced Is that what you were thinking?

**Comment by zuluecho9** [comment]
@GaPeppy wanted to make sure you saw my question above.

**Comment by GaPeppy** [comment]
Yes - separate block next to the auth-credentials example.  Proxied network with mixed network zone assets.

**Comment by zuluecho9** [comment]
@GaPeppy does this addition look good? https://github.com/newrelic/docs-website/pull/3975

**Comment by GaPeppy** [comment]
Looks good!

**Comment by zuluecho9** [comment]
thank you.
