### ISSUE TITLE
custom parsing logsource=file - vague documentation

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#3953]
The documentation is fairly vague on how a customer would set up the most common logsource (`file`) with custom parsing.  While `logsource=syslog` shows a `parser` attribute; there is no mention or examples of it for `logsource=file`.

With experimentation, the only way I could get it to work is specifying everything as a native fluentbit.conf file and simply using file.yml to reference/include the native config.

**files.yml**
logs
  - name: fluentbit-include
    fluentbit:
      config_file: /etc/newrelic-infra/logging.d/fluentbit.conf

**fluentbit.conf**
[SERVICE]
    Parsers_file /etc/newrelic-infra/logging.d/parsers_file.conf

[INPUT]
    Name tail
    Path /x/y/access.log
    Parser nginx-access
    Buffer_Max_Size 128k
    Skip_Long_Lines On
    Path_Key filePath
    Tag access-log
    DB /var/db/newrelic-infra/newrelic-integrations/logging/fb.db

[FILTER]
    Name record_modifier
    Match access-log
    RECORD fb.input tail
    RECORD logtype uat2-nginx
    RECORD region east-us-2
    RECORD sourcetype nginx-plus-access
    

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@GaPeppy, thanks for the heads-up about logsource with custom parsing. I am checking with our team to see how we can improve this and will keep you posted.

**Comment by jsubirat** [comment]
Hi there @GaPeppy , thanks for your feedback! We actually provide an easy way to specify the `logType` when using the `file` log source: using the `attributes` field (documentation [here](https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/enable-log-monitoring-new-relic/forward-your-logs-using-infrastructure-agent/#attributes)). The following configuration should result in the same one you specified above:

**files.yml**
```
logs:
  - name: nginx-access-logs
    file: /x/y/access.log
    attributes:
      logtype: uat2-nginx
```

The above assumes that you have created a parser (in New Relic Logs) that matches all the incoming log records having `uat2-nginx` as logtype.

I observed, though, that you defined `Parser nginx-access` in the above configuration. Does this mean that you have your own parser in ` /etc/newrelic-infra/logging.d/parsers_file.conf`? You can do that, of course, but our recommendation is for you to define an attribute `logtype: uat2_nginx` as detailed above, and then define your own GROK parser using the New Relic Logs site.

As a side note, we also provide some out-of-the-box parsing rules that automatically match the `logtype` attribute of your incoming log records. There's one specific for NGINX access logs: `logtype: nginx`. If that's your case (you are trying to parse NGINX access logs), then I'd strongly recommend to use it. Just change the previous configuration to:

**files.yml**
```
logs:
  - name: nginx-access-logs
    file: /x/y/access.log
    attributes:
      logtype: nginx
```

Hope this helps!

PS: we are going to make this more clear in the documentation, specially the part of specifying the `logtype` via the `attributes` field.
PS2: in case you want to look at quick examples of how to use the `attributes` field, you can check the example files included in the Infrastructure Agent at: `/etc/newrelic-infra/logging.d/*.yaml.example`

**Comment by zuluecho9** [comment]
This issue addressed with PR https://github.com/newrelic/docs-website/pull/3967.
