### ISSUE TITLE
subtitle shown html named anchor

### ISSUE THREAD

**Issue by roharon** [newrelic/docs-website#3962]
### Description

named anchor is shown on subtitle

### Steps to reproduce

1. Go to [ruby-agent-installation-rails-plugin](https://docs.newrelic.com/docs/agents/ruby-agent/installation/ruby-agent-installation-rails-plugin/)

### Expected behavior

`Update the newrelic.yml file [#Updating_newrelic.yml]`

Expect to looks like `Update the newrelic.yml file`

### Screenshots
![image](https://user-images.githubusercontent.com/4939738/133879764-5fee9da1-4c93-416b-80af-8df6fc40fe83.png)

**Comment by zuluecho9** [comment]
solved with https://github.com/newrelic/docs-website/pull/3963.
