### ISSUE TITLE
This generated table of contents is duplicated

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#3982]
### Tell us what you need

The New Relic One table of contents is repeated.

### Anything else you'd like to share?

<img width="1009" alt="New Relic One toc" src="https://user-images.githubusercontent.com/7992384/134084638-ccbc054c-b67d-44f7-a3dd-0282dc76bb9c.png">

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/
* **OS**: Mac OS 10.15.7
* **Browser**: Safari 14.1.2
* **Device**: Unknown

**Comment by roadlittledawn** [comment]
this is due to the fact that this path is used twice in the `src/nav/new-relic-one.yml` file

```
/docs/new-relic-one/use-new-relic-one
```

**Comment by roadlittledawn** [comment]
Looks like this was fixed
