### ISSUE TITLE
Issue: Install the ECS integration

### ISSUE THREAD

**Issue by philn5d-ar** [newrelic/docs-website#4017]
### Tell us what you need

"For Fargate launch type:

The infrastructure agent (newrelic-infra) gets deployed as a sidecar in every task to monitor.
"

"sidecar" is confusing, what does that mean? Maybe link to the definition or have a help bubble to explain.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/installation/install-ecs-integration/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 93.0.4577.82
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@philn5d-ar  That is a great question, thanks for calling this out! I'm checking with the team for a better explanation and will update the doc ASAP.

**Comment by barbnewrelic** [comment]
@philn5d-ar  I've updated https://docs.newrelic.com/docs/integrations/elastic-container-service-integration/installation/install-ecs-integration/ with a quick description of "sidecar" and a link to the gospel according to AWS ECS. Hope this helps!
