### ISSUE TITLE
OTLP not listed in network doc

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#4038]
NR went GA with OTLP at otlp.nr-data.net:4317

Neither **OTLP** nor the root domain of **nr-data.net** is listed in the networks doc.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/networks/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by mmfred** [comment]
Thanks again @GaPeppy - this is fixed by PR 4041.
