### ISSUE TITLE
Issue: Data requirements and limits for custom event data

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#4048]
There is a description about naming syntax for event type as following but it seems there are some additional undocumented rules.

https://docs.newrelic.com/jp/docs/telemetry-data-platform/custom-data/custom-events/data-requirements-limits-custom-event-data/

> Event types (using the eventType attribute) can be a combination of alphanumeric characters, colons (:), and underscores (_).

I tried using flex integration and there are some issues as following;

1. If the name is starting with number (e.g. 1_MyEvent), New Relic one console shows error on the Data explorer view. It seems it is not supported.
2. If the name is starting with colon (:), it is removed from name. As instance, if the name is ':MyEvent', it is saved to NRDB with naming 'MyEventSample'.
3. If the name includes colon(:) except for 1st character, it replaced with underscore. If the name is 'My:Event', it is saved to MRDB with naming 'My_EventSample'

So, It seems that there are any undocumented rules. Maybe name should be start with alphabet or underscore.

Please confirm and update document.

Thanks.

**Comment by barbnewrelic** [comment]
@shinji-newrelic Thanks for reporting this! We're going to have to do a bit more digging to find the exact rules and will update the docs as soon as we can!

**Comment by barbnewrelic** [comment]
The wording in the linked PR was not quite right, so I'm checking with the help team for what exactly to say and will submit another PR
