### ISSUE TITLE
Broken link in "Errors Inbox: Now in APM"

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#4049]
### Tell us what you need

Hi all,

The [Learn more](https://docs.newrelic.com/blog/how-to-relic/errors-inbox-with-slack-and-apm/) link at the top of the page leads to a 404.

Thanks!

### Doc information (don't delete this section)

* https://docs.newrelic.com/whats-new/2021/09/whats-new-errors-inbox-slack-apm/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 93.0.4577.82
* **Device**: Unknown

**Comment by mmfred** [comment]
@dlesniak-NR - thanks for the info on the broken link. The fix will be published later this afternoon. 

We recommend joining the New Relic organization on GitHub -- that way, helps us know where information is coming from. To do that, you ask in the #help-opensource slack channel.
