### ISSUE TITLE
[DDS] Content sync is failing

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#405]
## Description

Our nightly script that syncs the data definitions to the data dictionary service is failing. It appears the connection to Postgres from Ecto is timing out when trying to run the script. This is presumably because we are inserting all of the data in a single database transaction. We should try and break up the inserts to avoid the timeout issues.

**Comment by tariqahmed** [comment]
- Instead of one mega transaction, break it into a series of smaller transactions...
- Are we ok with partial success? If it fails halfway through...everything before it succeeds, or roll back?
- Takeaway: whatever has succeeded, let it go through...

**Comment by jerelmiller** [comment]
This is done!
