### ISSUE TITLE
Issue: CocoaPods installation

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#4050]
### Tell us what you need

* Please add description about how to add prefix header and update setting if there is missing.

### Anything else you'd like to share?

Today latest Xcode doesn't add prefix header automatically (maybe it is NOT added from Xcode6). Then most of customers cannot find prefix header from their project. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/installation/cocoapods-installation/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 93.0.4577.82
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@shinji-newrelic  Thanks for pointing this out! I'm checking with our support team about what's the best way to message this. I'll update the doc as soon as I get good info.

**Comment by barbnewrelic** [comment]
Fixed with https://github.com/newrelic/docs-website/pull/4071
