### ISSUE TITLE
Issue: Create NRQL alert conditions

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#4061]
### Tell us what you need

Under the loss of signal documentation, please also clarify:

When you have a faceted query, each facet is a signal. So if _any one of those signals ends - any of the faceted signals at all (for the duration specified) - that will be considered a loss of signal._

This is to clarify that it if there are, for example, 100 entities in the facet, if any one of those 100 entities stopped emitting a signal, a loss of signal violation would occur. 

It is not commonly known that this is how faceting and loss of signal behaves. 

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by mmfred** [comment]
@dralph3344 - thank you for the request! I added the info to the NRQL doc, as you can see here: https://github.com/newrelic/docs-website/pull/4064/files

Let me know if you have further edits to this.
