### ISSUE TITLE
"Unsubscribe from New Relic emails" doc out of date

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#407]
This is the doc in question: [https://docs.newrelic.com/docs/accounts/accounts/account-maintenance/unsubscribe-new-relic-emails](https://docs.newrelic.com/docs/accounts/accounts/account-maintenance/unsubscribe-new-relic-emails#all)  
  
While working as the docs hero, this message came in: 
 
> Also the "Unsubscribe from New Relic product emails" section of the Unsubscribe help page ([https://docs.newrelic.com/docs/accounts/accounts/account-maintenance/unsubscribe-new-relic-emails\#all)](https://docs.newrelic.com/docs/accounts/accounts/account-maintenance/unsubscribe-new-relic-emails#all)) does not reflect the functionality at [https://rpm.newrelic.com/users/USERID/edit](https://rpm.newrelic.com/users/USERID/edit) (<--- Add your own account user ID to go to your User Preferences page.)

I'm filing this ticket, because the more I looked into it, the more it seemed that this doc has strayed pretty far from how unsubscribing from emails actually work.

## Action items

1. Go through this doc closely and make sure the procedures match up with current processes for unsubscribing to emails.  
2. This doc doesn't mention the Email Preference Center at all ([https://try.newrelic.com/UnsubscribePage.html)](https://try.newrelic.com/UnsubscribePage.html)). Figure out if it should.  
3. Rewrite this doc as needed.  
4. Get a peer edit, because this content seems extremely squirrely.

## Jira migration details

* Original reporter: @paperclypse
* Jira ticket ID: DOC-5701
* Original priority: Medium
* Original component: Experience Debt
* Original product group: CAP

**Comment by dbarnesbrownNR** [comment]
Update after digging around in the UI a little:

Both https://rpm.newrelic.com/users/2786627/edit and https://one.newrelic.com/launcher/user-preferences-launcher.user-preferences-launcher seem to both go to a nearly identical UI with access to email preferences. It appears that from both account types the screens can be accessed by going to user preferences in the account dropdown and then clicking where indicated in the UI to see or change email preferences. Need to figure out: is this the only two options for people logged in who go to the account dropdown? If not what are other options for what they might see? Who in UI owns these screens? First thing that gets done on this should be to find out who those owners are and get their input on whether these are the only two main workflows our clients may see at this point.

**Comment by dbarnesbrownNR** [comment]
Also, the unsubscribe link from user preferences screen goes to https://try.newrelic.com/UnsubscribePage.html but I'm not sure if that's a universal experience.

**Comment by zuluecho9** [comment]
Closing this. Got DBB to peer edit this, think we're looking good.
