### ISSUE TITLE
Evaluate our workflows to make sure that they do not run for new fork contributors

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/docs-website#4073]
## Description
To ensure the security of this repository when working with forks, we need to evaluate our workflows to make sure that they do not run for new fork contributors to the repository. This will allow us to manage the risk by reviewing the submitted code before running any workflows. Most of our workflows should follow this model already, we just need to reaffirm that they do what we expect.

## Helpful links
- [Github workflow security best practices](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)

## Acceptance Criteria

- [ ] check if this is actually in place
- [ ] are we doing it wrong? 
- [ ] is this secure enough?
- [ ] Review with @jpvajda  @roadlittledawn 

IF we are making a change THEN: 

- [ ] confirm the impacts to the docs contributor workflow 
- [ ] Can we get some numbers on how many fork PRS we'd have to be involved with?
- [ ] if a new process is required, define that and review with the docs team
- [ ] Any workflow that checks out and runs forked code is gated by maintainers

**Comment by jpvajda** [comment]
@roadlittledawn if we did this, what is the impact to the docs team?

**Comment by jpvajda** [comment]
Can we get some numbers on how many fork PRS we'd have to be involved with?
