### ISSUE TITLE
[Setup] Add filesystem sourcing & MDX

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#41]
## Summary
Set up Gatsby to source content from a `.mdx` files in the repo to generate static HTML pages.

## Acceptance criteria
- [x] Install `gatsby-source-filesystem` plugin
- [x] Install `gatsby-plugin-mdx` plugin
- [x] Configure image directory (gatsby-config.js). This may already be configured via [gatsby-theme-newrelic](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/gatsby-config.js)
- [x] Configure content directory/directories (gatsby-config.js)

## Helpful links
- [gatsby-source-filesystem](https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/)
- [gatsby-plugin-mdx](https://www.gatsbyjs.com/plugins/gatsby-plugin-mdx/)

**Comment by zstix** [comment]
We are going to combine this work with the work done in #51 

The work for this specific ticket was completed at a4ada8b
