### ISSUE TITLE
Issue: NRQL syntax, clauses, and functions

### ISSUE THREAD

**Issue by gitcos** [newrelic/docs-website#4107]
https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/

Description of the SINCE clause says that an absolute UTC time can be given, but does not describe the format (syntax) to give that time in.  Description of the UNTIL clause doesn't even clearly say you can do this, although I'm pretty sure you can.  Neither SINCE nor UNTIL show examples of absolute times, only relative times.  Therefore, this documentation leaves the user entirely to guess wildly at the syntax.

To do:
Update [the SINCE description](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#sel-since) to include the syntax for UTC time.

**Comment by bradleycamacho** [comment]
Hey @gitcos, thanks for reporting this issue! I will escalate this to our product team so we can add more context to description.

**Comment by neubarth** [comment]
FYI: I just tested with `SINCE '2021-11-26T09:59:19+00:00' UNTIL '2021-11-26T10:05:19+00:00'`, and it worked.

**Comment by paperclypse** [comment]
Addressed in current docs version.
