### ISSUE TITLE
Issue: Report metrics via the Metric API

### ISSUE THREAD

**Issue by vocatan** [newrelic/docs-website#4115]
### Tell us what you need

* The instructions at https://docs.newrelic.com/docs/telemetry-data-platform/ingest-apis/metric-api/report-metrics-metric-api/ give a recipe for ingesting data, but the supplied NRQL command to see the data within New Relic does not yield results.

``
curl -vvv -k -H "Content-Type: application/json" \
-H "Api-Key: NEW_RELIC_LICENSE_KEY" \
-X POST https://metric-api.newrelic.com/metric/v1 \
--data '[{ 
        "metrics":[{ 
           "name":"memory.heap", 
           "type":"gauge", 
           "value":2.3, 
           "timestamp":CURRENT_TIME, 
           "attributes":{"host.name":"dev.server.com"} 
           }] 
    }]'
``

When this is submitted (with a correct NEW_RELIC_LICENSE_KEY of course), 
the documentation states that we can use the NRQL query of
``
FROM Metric SELECT max(memory.heap) TIMESERIES
``
to view the data as it was stored.  This does not appear to work.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/ingest-apis/metric-api/report-metrics-metric-api/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.61
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey @vocatan, thanks for reporting this issue! I'll look into this and escalate it to our product teams. We'll update this issue once we fix the command.

**Comment by jonahaapala** [comment]
@vocatan thanks for reaching out! Just as a quick sanity check on my part, can you confirm if you replaced CURRENT_TIME with a valid timestamp. Something like ``export CURRENT_TIME=`date +%s` `` before running the curl command? If this was the issue I will make sure to update the docs to be more clear as to which parts need to be updated 😃

**Comment by vocatan** [comment]
Yes, once I replaced the CURRENT_TIME with a valid number the spice started
to flow.

Thanks for checking
Bill

**Comment by jonahaapala** [comment]
Awesome, glad you were able to get things moving.
