### ISSUE TITLE
Issue: Step 4: Instrument your own Lambda functions

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#4160]
### Tell us what you need
The action name should be updated to follow current aws console UI.

Current documentation says 'choose Stream to AWS Lambda' but 'Stream to AWS Lambda is missing today.
> Select Actions and choose Stream to AWS Lambda.

It it now in sub menu in Actions and name is changed like following.
Actions > Subscription filters > Create Lambda subscription filter

Unfortunately I cannot attach screenshot of aws console, please contact me if you need screenshot.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.61
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for the feedback, @shinji-newrelic! I fixed it with PR #4161.
