### ISSUE TITLE
Issue: Networks

### ISSUE THREAD

**Issue by sskilbred** [newrelic/docs-website#4162]
### IP range used by Cloud Integrations

The Networks doc is important for customers to understand which endpoints, domains and IP ranges they need to allow (inbound/outbound). This also applies to the cloud integrations, but there are no references to our cloud integrations on this page. After consulting with support and engineering, the correct range is specified in the #webhooks section if this page. 
The fix would simply be to make it clear that these are the IP ranges used by cloud integrations.

Suggestions:
- Title: Alerts webhooks, api.newrelic.com, cloud- and ticketing integrations
- Last sentence: These network blocks also apply to third-party ticketing integrations and the New Relic cloud integrations (eg. GCP)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/install-configure/networks/#webhooks
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.61
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for the suggestions, @sskilbred! I fixed it with PR #4164.
