### ISSUE TITLE
Break up Diagnostics doc so it has room to breathe

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#417]
Recent update: The Diagnostics doc was moved to [https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) . Rather than keeping it in the Troubleshooting sub-cat, TW could make a Diagnostics sub-cat in taxonomy for Cross-product functions and break this long doc up!

## Issue description

The good news is, the New Relic Diagnostics doc ( [https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/new-relic-diagnostics](https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/new-relic-diagnostics) ) is quite comprehensive! The bad news is, it has gotten quite long over time. Seems like it might benefit from pulling it out of the APM agents troubleshooting taxonomy ( [https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/](https://docs.newrelic.com/docs/agents/manage-apm-agents/troubleshooting/) ), esp. because you can also use Diagnostics for Synthetics and Browser.

## Action items

1. Talk to support-tools team and/or TW mob session to get their ideas about how best to break up the doc.
2. Move Diagnostics doc to cross-product L1 taxonomy.
3. Create an L2 in it for Diagnostics.
4. Create L3s for logical sub-categories.
5. Break up the standalone doc, and move the pieces into the new L3s.
6. Add relevant redirect URLs.
7. Publish, and notify support-tools SMEs.

## Resources:

* support-tools slack channel

## Jira migration details

* Original reporter: @barbnewrelic
* Jira ticket ID: DOC-5200
* Original priority: Medium
* Original component: Experience Debt
* Original product group: FSO

**Comment by barbnewrelic** [comment]
Created new taxonomy https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag . Broke up original doc into 6. Also added dummy doc link to release notes.

Diagnostics CLI (nrdiag):  https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-cli-nrdiag

Run the Diagnostics CLI (nrdiag): https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/run-diagnostics-cli-nrdiag

Pass command line options (nrdiag): https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/pass-command-line-options-nrdiag 

Validate config file settings (nrdiag): https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/validate-config-file-settings-nrdiag 

Interpret the nrdiag output: https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/interpret-nrdiag-output

Diagnostics CLI licensing and security: https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-cli-licensing-security

Diagnostics release notes: https://docs.newrelic.com/docs/release-notes/platform-release-notes/diagnostics-release-notes
