### ISSUE TITLE
Issue: Forward your logs using the infrastructure agent

### ISSUE THREAD

**Issue by sskilbred** [newrelic/docs-website#4180]
### Not applicable for manual installations

Clarify that the logging extension is not included when the infra agent is implemented using tarball (Linux) or ZIP (Windows) installation.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.61
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@sskilbred  Thanks for this important clarification! I'm in the process of making numerous edits to all the log forwarder docs, and your comment is being fixed with https://github.com/newrelic/docs-website/pull/4187
