### ISSUE TITLE
Java+Logs: Java Util Logging incompatibilities with app servers

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#419]
Based on the GTSE ticket GTSE-2073, Java Util Logging (JUL) is not a good option to use Logs in Context when the application is running on Tomcat or other application servers.

Here is an engineer's comment:

> Unfortunately, java.util.logging (JUL) is a JVM-wide logging system. JUL cannot be configured separately for different applications in the same JVM. My strong recommendation in this situation would be to migrate the app to SLF4J and use a logging framework that doesn't do classpath manipulation. Logback 1.2 and Apache Log4j 2.x are both good choices, and they don't do classpath manipulation.

Could you add an extra note not to recommend JUL as a LiC logging library when the customer is using Tomcat or other application servers?

## Action items

1. Review comment and suggestion
2. Draft some text
3. Run the new text by a Java expert and publish
4. Let original requestor know this is resolved

## Jira migration details

This issue was migrated from the internal DOC jira project:

* Original reporter: Tech Support Engineer
* Jira ticket ID: DOC-5613
* Original priority: Medium
* Original component: Experience Debt
* Original product group: FSO

**Comment by barbnewrelic** [comment]
See CF-10269. It's best practice to document what we do support rather than what we don't support. Plus, some upcoming LiC enhancements will make it even easier to instrument for Java apps.
