### ISSUE TITLE
I am not able see my project ACCUPLACE 

### ISSUE THREAD

**Issue by Jagadish-0668** [newrelic/docs-website#4190]
When i login into my account my dashboard is empty I am not able to see my project ACCUPLACER

**Comment by dbarnesbrownNR** [comment]
Hi @Jagadish-0668, since I'm not able to see your settings or history it's a bit hard for me to troubleshoot from here, but I'd suggest you go to GitHub technical/help docs to see if there's some info there, as this project does not appear to be part of New Relic. Thanks!
