### ISSUE TITLE
Issue: Hostname logic in Java

### ISSUE THREAD

**Issue by shhudspeth** [newrelic/docs-website#4198]
### Tell us what you need

could you add sample yml file copy command for process host? And with clear instructions on whether a nested stanza is needed and with an example of it in the nested stanza form. 

### Anything else you'd like to share?

could it also be added to the example yml file but commented out?
I have a customer whose servers are not picking up their server instance names and struggling to override the process_host name and needs clearer instructions. 

Thanks! 
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/agents/java-agent/configuration/hostname-logic-java/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.61
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey @shhudspeth! I am going to route this to the a product team who can assist in providing a great example here!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
