### ISSUE TITLE
[Component] Create DoNotTranslate component for content authors

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#4203]
## Summary
><!> Please use the https://github.com/newrelic/docs-website/tree/feature/machine-translation feature branch

Content authors want to be able to flag certain pieces / sections of content that should not be translated when we send it. 

You can add a class to an HTML element to tell Smartling to exclude it from translation:

```
<p class="notranslate">This paragraph won't be captured for translation</p>

<p>You have<span class="notranslate">5</span>items in cart.</p>
```

## Acceptance criteria
- [x] Verify with Julien this approach will work from his / Smartling's perspective
- [x] A new component can be used in .mdx files that outputs relevant element with the `notranslate` class
- [x] When we serialize MDX to HTML, children of the component are wrapped in relevant element with the `notranslate` class
- [x] When we deserialize HTML to MDX, it's converted to expected JSX syntax
- [x] After deserialization the convert MDX passes the `verify-mdx` script

## Helpful links
https://help.smartling.com/hc/en-us/articles/360000322914

**Comment by roadlittledawn** [comment]
Add code examples of how this would be used in MDX files: for block level elements (with one or more children), span elements

**Comment by clarkmcadoo** [comment]
PR: https://github.com/newrelic/gatsby-theme-newrelic/pull/598

**Comment by roadlittledawn** [comment]
@clarkmcadoo && @josephgregoryii && @nr-kkenney i just walked through uploading an HTML file that only added the `span` or `div` elements with the class `notranslate` (did not encode children) and it did indeed exclude the right content from human and machine translation.

**Comment by roadlittledawn** [comment]
i got both methods (nest children in an element with `notranslate` class & encode children in data attribute in element) working, buuuut i think i'm preferential to the first because it's a bit more straight forward, i verified it works in Smartling (and it's the recommended way per their docs). will chat with peeps after sprint planning today and hopefully we can get a PR up for it today

**Comment by aswanson-nr** [comment]
PR merged into feature branch
