### ISSUE TITLE
[Docs] Remove auto index pages, landing pages

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#4226]
## Summary

We want to remove index pages and landing pages from the site. This includes:
* removing the local plugin that does this
* removing all directory level links in nav YAML
* remove taxonomy-redirects.json
* remove related templates that auto index pages plugin referenced

Tech docs will also have some changes that we want in the [same feature branch](https://github.com/newrelic/docs-website/tree/feature/landing-auto-index-pages) and deployed at same time. Changes likely include:
* adding redirects for highest traffic auto index pages
* removing index.mdx files
* possibly adding MDX files

## Examples
The following types of pages to remove:
- auto index page: https://docs.newrelic.com/docs/distributed-tracing/concepts/
- landing page: https://docs.newrelic.com/docs/distributed-tracing/
- landing page table of contents: https://docs.newrelic.com/docs/distributed-tracing/table-of-contents
- api doc index page: https://github.com/newrelic/docs-website/blob/develop/src/content/docs/apm/agents/net-agent/net-agent-api/index.mdx

These types of pages should remain as is:
- release notes landing: https://docs.newrelic.com/docs/release-notes/
- agent release notes landing: https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/
- whats new landing: https://docs.newrelic.com/whats-new/

## Outstanding issues
- [x] Determine if we should update `src/content/docs/style-guide/writing-docs/article-templates/landing-page-template.mdx`
- [x] Determine what to do with several MDX files that use `landingPage` template via frontmatter? Should they just be `basicDoc`?
  - this would mean those pages would have right menu 
- [x] Apply same file changes to `i18n`
- [X] Verify no remaining landing pages View all button are removed / do not link to auto index / table of contents page
- [X] Update nav YAML files to remove auto index page paths
- [X] Determine if we need to keep top level paths in nav YAML
- [x] Ensure `root.yml` does not have broken links

## Acceptance criteria

- [x] Confirm if this is something we can do - @austin-schaefer 
- [x] remove the local plugin `gatsby-plugin-auto-index-pages`
- [x] update gatsby-config.js to remove reference to `gatsby-plugin-auto-index-pages`
- [x] remove taxonomy-redirects.json
- [x] remove related templates
- [x] Create ticket to #5465
- [x] Clean up `i18n` directory and remove erroneously saved files in `i18n/content/jp/docs/ja-JP/src/i18n/content/jp/docs`
- [x] work closely with tech docs to get their changes in the branch, add one of them as reviewer on PR

## Helpful links
- https://github.com/newrelic/docs-website/tree/feature/landing-auto-index-pages
- Docs Jira DOC-7617

**Comment by jpvajda** [comment]
This is a sprint or 2 out...

**Comment by austin-schaefer** [comment]
We have a ticket this sprint to create necessary redirects in a PR—we should be good to go in the next couple weeks

**Comment by paperclypse** [comment]
All of the work on my side of things is done in this PR: https://github.com/newrelic/docs-website/pull/5349

**Comment by roadlittledawn** [comment]
Created a script to update all nav YAML files to remove paths that:
- are not the top level path in the file
- are not leaf node paths (links to actual content pages)

We probably want to keep top level paths around since that's used to determine which nav object to attach to a page if it's referenced in more than one nav YAML file
