### ISSUE TITLE
Please add example queries for mobile/browser metrics 

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#4251]
### Tell us what you need

* Can you please add browser and mobile metrics similar to what APM already has listed in documentation? 

### Anything else you'd like to share?

All of the information tips/tricks for querying is scoped to APM and other examples for mobile/browser data would be useful. Thanks! 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/telemetry-data-platform/understand-data/metric-data/query-apm-metric-timeslice-data-nrql/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@CherylFrankenfield, thanks for this suggestion! We'll present this to our SMEs and see if they can add examples for browser and mobile.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
