### ISSUE TITLE
I can't access my account

### ISSUE THREAD

**Issue by Ampa143** [newrelic/docs-website#4255]
### Tell us what you need

* If you've found something inaccurate, what is it?
* If something is hard to read, confusing, or missing information, let us know.
* If you're having trouble completing a task or are uncertain what to do next,
  tell us what you're trying to do so we can provide more useful information.

### Anything else you'd like to share?

Add other context like screenshots, links to other docs, and information about
your environment (operating system, application framework, etc.).

### Doc information (don't delete this section)

* https://docs.newrelic.com/
* **OS**: Android 10
* **Browser**: Chrome 80.0.3987.99
* **Device**: [mobile] RMX2030

**Comment by urbiz-nr** [comment]
Hello @Ampa143! Have you tried the options here https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems/?
