### ISSUE TITLE
Setup JSON endpoints to serve content into In Product Help XP component

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#426]
When we cut the site over to the new Docs Site we need to recreate the JSON endpoints that send sends data to the in-product XP component. That component seems to render the docs site content, different then the actual site itself but it relies on the docs library service 

**Current state**
The docs library service (which is stitched into nerdgraph which the NR1 Help XP gets swiftype and docs content from) consumes JSON endpoints from Drupal.

**Comment by jpvajda** [comment]
@roadlittledawn I created this.

**Comment by tariqahmed** [comment]
- Similar to setting up the What's New JSON for each content type.
- What do we do for each of the components? Complexity is making sure we can do that, whether it's compiling to JSX, or render to HTML and use custom parsing on the In Product that knows how to render...
