### ISSUE TITLE
Add related content links to the Docs Site in the right rail

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#427]
Adding dynamic content links using our related content component in the right rail under the page header links would allow us to drive users to OSS and Dev Sites and connect users to more discoverable content. 

### Considerations

- **display logic** what about really long right rail scenarios [like this page](https://docs-preview.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file). Would we want to NOT show the related content component if a page has a very long set of navigational headers in the right rail? 

- **cost** What costs would we incur with swift type as costs would be driven up by all the docs pages needing to refresh with dynamic content links. (WIP)

- **event tracking** How can we measure if this is valuable to the end user? Perhaps track click events on the dynamic links to see if people use it? Or look at bounce rates on pages that have the dynamic links, It will likely increase bounce rates on those pages but increase traffic to our other sites. Measuring when users click on the related links would be very useful to understand when users feel they need to go to another site for content needs.

- **Localization Impacts** What about searching through a translated site like Japan? It's currently done through the proxy, so what is our approach now?  - once the related content is available via a query, it shouldn't really impact swifttype cost as we'll have the related content already from the initial query.

### Swift type impacts and approach

We refetch results per page once a day on a cron job. The data is available as part of the build: https://github.com/newrelic/developer-website/blob/develop/src/data/related-pages.json

That data gets rebuilt in this action once a day: https://github.com/newrelic/developer-website/blob/develop/.github/workflows/fetch-related-content.yml 

We can specify whatever interval we want if we go this route. When we execute a query per page each time we fetch related content for a page. We have a limit on the number of queries we can run before we are charged more.

If we fetch once a day, and we have 3000 queries we have to run, thats 3k queries thats ~90k queries per month. We could decrease the interval and instead do once a week, or once a month.

Doing so would put costs down, but means that auto related content could become stale (_maybe thats a fair tradeoff_)

### Right Rail Mockup

![Untitled Diagram](https://user-images.githubusercontent.com/1395158/102424073-9c677600-3fc7-11eb-8813-8f28f028d6fa.png)

**Comment by jpvajda** [comment]
@djsauble any thoughts on this? It's come back up again. :)

**Comment by djsauble** [comment]
I still think it's a bad idea, but the right rail is flexible enough that adding a related content section should be easy.

**Comment by jpvajda** [comment]
@markweitzel confirmed with Mark Buchanan that this approach is welcome on the Doc Site, so we'll move forward into bringing the related content into the right rail. cc @austin-schaefer

**Comment by jpvajda** [comment]
Moving back to Proposed to estimate as part of catch-all estimate process.

**Comment by jpvajda** [comment]
Before implementation I think understand the potential cost increases of using Swiftype on the Docs Site to populate related content is important.

**Comment by jerelmiller** [comment]
As of right now, the docs site has 1,374 pages that we render the right rail on. That number will go up once we are 100% migrated (likely closer to 2,000), but this should give us a ballpark range of cost. Assuming we have 2,000 pages, this means we would execute 2,000 search queries to Swiftype every time we refetch the related pages.

I'm not sure which plan we are on, but pricing is as follows:

**Basic**
50k searches   
$25/50k additional

**Pro**
100k searches  
$25/50k additional

We refetch the dev site every day. Assuming we followed suit and updated the related pages every day, this equates to about 60k searches (assuming 2k searches * 30 days), just to populate the links. This is in addition to any searches users are making as well as the dev site related pages.

Hope this helps!

**Comment by jpvajda** [comment]
@jerelmiller thank you! in Nov it looks like we executed 110,064k total searches, so this means we'd be increasing our volume by around ~60k searches if we were planning on implementing the right rail and have it run daily page updates for relate links. 

<img width="1030" alt="Screen Shot 2020-12-28 at 9 48 51 AM" src="https://user-images.githubusercontent.com/1395158/103230228-24b41800-48f2-11eb-8002-dcbebcc0567a.png">

**Comment by jpvajda** [comment]
@austin-schaefer FYI on this, we'll want to discuss this potential cost increases with the Mark(s)

**Comment by jpvajda** [comment]
Do we know why APM is triggering this many searches a month?

<img width="543" alt="Screen Shot 2020-12-28 at 9 59 05 AM" src="https://user-images.githubusercontent.com/1395158/103230727-642f3400-48f3-11eb-8c5c-6fb0486bd19e.png">

**Comment by jpvajda** [comment]
I've done some research on potential costs of implementing the related content in the right rails on all docs pages and we'll be discussing this in the new year to get approval to move forward with an approach as there is a cost increase to swiftype that we'll want to ensure people are aware of.

**Comment by zstix** [comment]
This is semi-blocked until we make a decision around how often we want to query swiftype. We can still build the functionality to populate this content.

**Comment by zstix** [comment]
We've added the custom plugin that we created for the developer site to the theme. When we pick this work back up, we should update the developer site to use the plugin via the theme and then add it to the docs site.

**Comment by jpvajda** [comment]
@zstix do you want an issue created to do that?

**Comment by zstix** [comment]
I figured this ticket would be used to track that work, so I moved it back to proposed.

**Comment by jerelmiller** [comment]
@jpvajda How many related resources are we planning to add to a page? Are we sticking with 5?

We'll also need to figure out how best to utilize this.

**Comment by jerelmiller** [comment]
Here is a screenshot with some (dummy) resources for a page. This page only has 3 table of contents links, but you can see it already takes up almost the full height of the page. This will get worse for some of the larger pages.

<img width="355" alt="Screen Shot 2021-02-04 at 12 27 03 PM" src="https://user-images.githubusercontent.com/565661/106951421-9c8d1380-66e4-11eb-83d9-ed21d7d015e4.png">

**Comment by jerelmiller** [comment]
Here is a little screen recording of what it looks like on a large page. You can see it gets buried pretty quickly and leads to a double scroll:


https://user-images.githubusercontent.com/565661/106952187-9e0b0b80-66e5-11eb-9586-98869fafd067.mov

**Comment by jerelmiller** [comment]
@djsauble not sure if you have any ideas or thoughts, but I'd love to hear them if you do :)

**Comment by jpvajda** [comment]
@jerelmiller raised some really great concerns here so we are discussing the best way to handle the experience of the right rail with related content.

**Comment by djsauble** [comment]
As I mentioned in Slack, I think the right approach here is to put "related resources" at the bottom of the content, like they are on the current docs site.

**Comment by jpvajda** [comment]
I scheduled a quick sync to align with key stakeholders on the approach to ensure we all agree.

**Comment by jerelmiller** [comment]
We've decided to go ahead and move forth with this using the following changes:

* Shorten up the "On this page" section to show 5-6 links
* Limit the "Related resources" to 3 links
* Move feedback above contributing guidelines (needs design help)
* Add a divider between the "On this page" and "Related resources" sections
* Try and tighten up the vertical spacing on the right rail

Quick mock:

<img width="382" alt="Screen Shot 2021-02-09 at 1 43 25 PM" src="https://user-images.githubusercontent.com/565661/107426885-a3959680-6ad5-11eb-8b0f-9be3c5e5d200.png">
