### ISSUE TITLE
[Setup] Create initial JSON resources

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#43]
## Summary
Create initial set of JSON resources in Drupal the team can look at, test against.

## Acceptance criteria
- [x] Review findings/PR for [issue 42](https://github.com/newrelic/docs-website/issues/42)
- [x] Set up node/content JSON resources
- [x] Store small subset / document how to access / use them

**Comment by jerelmiller** [comment]
@roadlittledawn Could we get some clarity? Is this for creating a JSON file in the docs website itself or would this be creating a JSON endpoint in the drupal site that we can use for migrating content?

**Comment by roadlittledawn** [comment]
@jerelmiller This would be for creating a JSON endpoint(s) in Drupal that we can use for migrating content

**Comment by roadlittledawn** [comment]
we created new resources based on the api/ui/content/CONTENT_TYPE/ID resources and modified them a bit for our needs this MMF. JSON resources for redirects or other Drupal data will be handled in separate issue tickets for future MMFs
