### ISSUE TITLE
Improve Gatsby local build stability

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#4320]
## Description

Anecdotally, the Gatsby local build has become so unstable as to be basically unusable by the Docs team. Which is a shame, because I got a lot of value out of it when it was more stable. (Related #3756)

I wanted to create a grab-bag issue where people on my team could add specific issues that they're experiencing (for example, today I had three sigbus crashes in a row without any kind of spike in my computer's memory usage). 

## Expected behavior

I'd love a local build that is stable and when it fails it's easy for me to understand why and resolve it myself.

**Comment by roadlittledawn** [comment]
i've been battling SIGBUS errors as well. we should be able to allocate some points to performance related tickets this quarter and hopefully soon. and some of the work we're doing for the commits may improve performance as well (removing auto index pages for example). 

definitely want to be able to run the site locally. it's been a frustrating developer experience for me as well recently
