### ISSUE TITLE
Issue: Proactive Detection with Applied Intelligence

### ISSUE THREAD

**Issue by skeemer** [newrelic/docs-website#4332]
## How can we make our docs better?

* It appears that the information for the Slack integration is completely out of date. The referenced Slack app no longer exists and doesn't explain how to fill in the fields for the Slack notification channel.
* The new New Relic Slack app just links to this page when click on the "Add to Slack" button.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/proactive-detection/proactive-detection-applied-intelligence/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by skeemer** [comment]
No, that doesn't help. It says there is supposed to be an app called "New Relic AI" which I can't find. And I already mentioned that trying to install the app "New Relic" just results in a redirect to that page.

**Comment by x8a** [comment]
Hi, @skeemer! The issue was that the name of the app has changed and it's now called `New Relic`. Here's the PR #4424 that fixes it.

Please let me know if you need further assistance. Thanks!
