### ISSUE TITLE
Use MDX components within the InProduct Help XP Component

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#434]
### The inception of Gatsby.... 

It be cool and consistent to use the same components we have on our Docs Site and available in the Global Theme within the In Product Help XP Component so there is similar look and feel for a user using Docs in the product or outside the product.

<img width="1195" alt="Screen Shot 2020-12-17 at 3 19 37 PM" src="https://user-images.githubusercontent.com/1395158/102550652-68e62380-407b-11eb-8bc1-167b69cf4602.png">

**Comment by jerelmiller** [comment]
I definitely agree that we should do what we can to provide consistency. Unfortunately, some of these components are built using a newer version of React that the platform isn't quite ready for. We'll have to think through how best to approach this.

**Comment by jpvajda** [comment]
closing as this no longer a product feature where DevEn is working.
