### ISSUE TITLE
Alters Intenlligencs

### ISSUE THREAD

**Issue by GreenStaradtil** [newrelic/docs-website#4386]
`<!--` Thanks for filing an issue on our docs! -->

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/get-started/introduction-applied-intelligence/
* **OS**: Android 11
* **Browser**: Edge 93.0.961.69
* **Device**: [mobile] Motorola moto g stylus

**Comment by x8a** [comment]
Hi, @GreenStaradtil! Could you describe your issue? Thanks!
