### ISSUE TITLE
Issue: Azure Cosmos DB (Document DB) monitoring integration

### ISSUE THREAD

**Issue by shhudspeth** [newrelic/docs-website#4392]
## How can we make our docs better?

Is there a reference to old metrics that we can see? Trying to troubleshoot what metrics we have collected for CosmosDB and the link in the yellow box goes to a 404. 

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)
clicking in the yellow box about the depreciated integration goes to a 404 page. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/microsoft-azure-integrations/azure-integrations-list/azure-cosmos-db-document-db-monitoring-integration/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.81
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @shhudspeth, thanks for reaching out! I'm looking into this for you now. Will try to get you some answers on whether that content is still available, and if so, where to find it.

**Comment by dbarnesbrownNR** [comment]
Circling back to this. It appears we've removed the content for the deprecated software, as we no longer support it. I will update the documentation so that it does not go to a dead link.

**Comment by dbarnesbrownNR** [comment]
Associated PR is now merged.
