### ISSUE TITLE
Issue: Docker container for infrastructure monitoring

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#4404]
## How can we make our docs better?

This only gives directions that use your existing image as the base. I have another image already. What has to be done differently in order to use our own image?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-container-infrastructure-monitoring/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @StingyJack! I'll ask the team whether this is possible and get back to you 🙌🏻.

Thank you!
