### ISSUE TITLE
Doc page not scrolling to correctly location until second click in right rail 

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#443]
### Description

After the first section click on the sidebar, the page no longer scrolls when you click another section unless you click twice. The URL does update.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/agents/net-agent/custom-instrumentation/add-detail-transactions-xml-net
2. Click on `Example Myinstrumentation.xml`
3. Click `Name transactions`. Notice that the doc doesn't scroll but the URL updates
4. Click `Name transactions` again. The doc scrolls. 
5. Try it with other headers

### Expected behavior

Doc scrolls to appropriate header with each click.

### Environment

* Chrome
* Edge 87.0.664.66

**Comment by austin-schaefer** [comment]
@jpvajda @jerelmiller : Just noticed I forgot to add the `launch-blocker` label on this. Definitely something we'll need to fix before go live.

**Comment by jpvajda** [comment]
verified also on Firefox 84.0.1 his is an issue we should fix.
