### ISSUE TITLE
In-product help XP content is rendering correctly

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#444]
## Summary
In previous PRs we are outputting `.json` that contains HTML. And we updated the `docs-library-service` to optionally use a slug instead of a Drupal ID to fetch the content and make it available via nerdgraph. 

Recently, a bug was reported (see details below) where results / content weren't consistently rendering in NR1 Help XP nerdlet. The PR to `docs-library-service` was rolled back.

Primary scope here is to revisit that work to get the `docs-library-service` ready for our launch.

## Acceptance criteria
- [ ] Ensure gatsby outputs the content that the docs-libarary-service depends on
- [ ] Ensure the `docs-library-service` is ready to fetch content from Gatsby at launch
- [ ] Ensure that, before launch, the `docs-library-service` and the NR1 Help XP work as expected until and after launch of new doc site (available in staging)
- [ ] deploy to staging and run user testing to confirm this is working as expected - @jpvajda 

## Helpful links
- https://source.datanerd.us/nr1-dev-experience/docs-library-service
- https://source.datanerd.us/nr1-dev-experience/nr1-help-xp

In-product help XP content is rendering correctly, including the issue that was identified in #623 where we had to back out at code change for the content-library. 

Relates to #426 and #636  and [JIRA 1556](https://newrelic.atlassian.net/browse/DEVEX-1556)

After fixing the rolled back code (see JIRA issue for roll back PR) test the following

## Test

I’m able to get results for searching such as infra agent, apm agent, PHP, build an app, but the actual search term of infrastructure agent doesn’t returns results in the XP. Im not clear what the issue is here. Search seems to be working when running the same query in the Developer site in our global search. I’ll file a GH issue with the Site Squad team to take a look today.

also New Relic One fails to return results, but new relic one doesn't.

## Steps to Reproduce
 

1.     go to the in product XP on prod
2.     run the search queries mentioned above
3.     see results
4.     run the same queries on the developer site / global search
5.     see results
6.     notice that infrastructure agents actual returns results within the site's global search, but not in the inproduct xp

**Comment by tariqahmed** [comment]
After getting the JSON end point in place, we then compare what the product side looks like...

**Comment by tariqahmed** [comment]
There are definitely some complexities...not may be much code we can share, until the platform is upgraded. So that may mean having to do some duplication. The platform only allows SASS.

**Comment by tariqahmed** [comment]
Leverage/convert to internal product components

**Comment by jpvajda** [comment]
Since we can't reproduce the issues defined in the `test` section we are moving forward that the issue we saw is no longer persisting.  relating to this issue: https://github.com/newrelic/docs-website/issues/636
