### ISSUE TITLE
my user is broken

### ISSUE THREAD

**Issue by danemacaulay** [newrelic/docs-website#4451]
my user is broken, i get the following screen on login:
![Screen Shot 2021-10-21 at 4 16 02 PM](https://user-images.githubusercontent.com/2157691/138358307-2727c693-9215-4b7a-a3f7-cb66f83299c3.png)
i cant file a ticket through your user interface because there is no account to select in the dropdown
please help!

**Comment by bradleycamacho** [comment]
Hey @danemacaulay, thanks for letting us know! I am unable to personally help out, but I've internally reached out to a few people to try and find some answers. I'll get back to you soon!
