### ISSUE TITLE
Issue: Amazon S3 monitoring integration

### ISSUE THREAD

**Issue by alaiavee** [newrelic/docs-website#4465]
## How can we make our docs better?

* Is something confusing? Yes
* Is something inaccurate or missing? Yes

Under [Amazon S3 data for request metrics](https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-s3-monitoring-integration/#provider-S3BucketRequests) we have the following:

`AllRequests` | The total number of HTTP requests made to an Amazon S3 bucket, regardless of type. If you’re using a metrics configuration with a filter, then this metric only counts HTTP requests from objects which meet the filter's requirements.
-- | --

This perhaps needs a rewrite to clarify that at least one bucket metric filter is actually required for publishing metrics to Cloudwatch, which we are then able to poll. In the AWS S3 console, when configuring bucket request metrics, the following message will show up if no metric filters have been created:

>You don't have any filters
To view request metrics, create a filter.

So the verbiage in the docs about "If you're using a metrics configuration with a filter" is off, as it's required there isn't really an "if" about it unless talking about "if it has been configured properly".

 Also, there is the possibility that a customer creates multiple bucket metric filters for bucket requests. If they have, then they will need to have one of the filters set to the scope of `This filter applies to all objects in the bucket`, and named `EntireBucket`. Otherwise, no bucket request metrics are gathered.
 
 [AWS Docs that covers creating a s3 bucket metrics config for all objects](https://docs.aws.amazon.com/AmazonS3/latest/userguide/configure-request-metrics-bucket.html)
 
 Note that maybe we should reference step 7, when creating the bucket metrics filter, that it needs to be named `EntireBucket`. It is also important to underline that this should be the ONLY metrics filter for all objects in the bucket as any additional ones may cause the metrics to not report properly (based on my testing in my lab).

Please see internal GTSE-11937 for more info, or reach out to me in Slack if further clarification is needed.

Possibly helpful for illustrating the config in s3:
![s3BucketMetricFilterEntireBucket](https://user-images.githubusercontent.com/56417646/138491343-2ad09218-1e53-4637-a3b8-4147f4e516e3.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/integrations/amazon-integrations/aws-integrations-list/aws-s3-monitoring-integration/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 93.0.4577.82
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thank you for your contribution @alaiavee. we hope the work done in https://github.com/newrelic/docs-website/pull/8295 addressed this.
