### ISSUE TITLE
Refactor issue buttons/feedback UI

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#4480]
I want to play with more concepts on how we can generate more GH issues and feedback from users through docs. 

Ideas we can play with:

- Separate the yes/no feedback buttons from the right nav, and instead put them on the top (and/or bottom) of the page as a standalone component
- Change the design of the right nav to just make the buttons more visible
- Change the copy to be clearer, or reduce the number of CTAs
- See also #4773

**Comment by roadlittledawn** [comment]
First phase of this is moving the Yes / No buttons somewhere more visible on the page. May include A/B test as well. Possibly slated for Dec

**Comment by legnaleama** [comment]
I realised I never shared the FIgma prototype. I've left a few notes for any developer working on this but feel free to DM me on Slack if you need clarification:

👉 [Figma prototype](https://www.figma.com/proto/yweKtFssdvG9esqyJFNW9M/Docs-site?page-id=825%3A61122&node-id=914%3A68198&viewport=501%2C48%2C0.56&scaling=scale-down&starting-point-node-id=911%3A58814&show-proto-sidebar=1)
