### ISSUE TITLE
[Docs] Decommission related resources

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#4481]
## Summary

Data showed low engagement in links in related resources in right menu on content pages. We want to remove that section and extend the On this page where related resources ended.

## Screenshots
<details>
<summary>Screenshot of related resources section</summary>

![2021-12-13_15-21-12](https://user-images.githubusercontent.com/2952843/145904890-e7670547-4b72-473f-b7fc-7d71172f8285.png)

</details>

## Acceptance criteria
- [x] Related resources section is not displayed in right menu UNLESS   a users has defined a url in the front matter for related resources. 
- [x] Related workflow code to fetch related resources via swiftype is removed

**Comment by rudouglas** [comment]
PR for review:
https://github.com/newrelic/gatsby-theme-newrelic/pull/619

**Comment by rudouglas** [comment]
Part 1: https://github.com/newrelic/gatsby-theme-newrelic/pull/619 `READY`
Part 2: Docs `WIP`

**Comment by rudouglas** [comment]
Removing the `relatedResources` field from the config is enough to remove these from the site, and testing `resources` in the frontmatter still works. Just a clarification on this, do we want to disable the [fetch-swiftype-content](https://github.com/newrelic/docs-website/actions/workflows/fetch-swiftype-content.yml) workflow or do we want to delete both that and the [script](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/get-related-resources.js) in the site?

**Comment by zstix** [comment]
Let's get rid of the workflow, since it's no longer being used (and the files are tracked in git).
