### ISSUE TITLE
[Docs] Decommission for more help

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#4482]
## Summary

Data showed very low engagement in the For more help sections at the bottom of content pages. We already removed most/all of the custom For more help sections in MDX files. Now we want to remove the default for more help and related code in any templates.

## Screenshots
![2021-12-13_15-03-12](https://user-images.githubusercontent.com/2952843/145903062-c33b170c-17e6-42e5-a67d-797d6686587a.png)

## Acceptance criteria
- [x] Remove `DefaultRelatedContent` component
- [x] Remove related fields in translations.json files (en, jp)
- [x] Remove references to it in [`docPage` template](https://github.com/newrelic/docs-website/blob/develop/src/templates/docPage.js)
- [x] Remove the check for custom For more help sections in [`docPage` template](https://github.com/newrelic/docs-website/blob/develop/src/templates/docPage.js)

**Comment by roadlittledawn** [comment]
@austin-schaefer do we have enough data for a do / don't do on this?

**Comment by roadlittledawn** [comment]
Austin said today this one is also ready / we have data we need

**Comment by roadlittledawn** [comment]
Unfortunately that `docPage` template still needs to use `mdxAST` for the On this page menu
