### ISSUE TITLE
[Docs I/A] Create script to generate set of separate nav YAML files

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#4527]
## Summary

Split out from #4185 . 

Create a utility script that can be run via yarn alias that generates a separate set of nav YAML files that reflect the file system in `src/content/docs`. 

## Spec: Generate nav YAML set
Create separate, standalone script (runnable on its own, via a yarn alias) to generate a separate set of nav YAML files that reflect the file system:
* Generate a separate set of nav YAML files for tech docs to use in updating `src/nav` files. Do not overwrite files in `src/nav`
* Should reflect file system. File system = everything inside of `src/content/docs`. One nav YAML file per top level dir in `src/content/docs

## Acceptance criteria
- [x] As a content author, I can run a script via yarn that generates a separate of nav YAML files
- [x] Each nav YAML file maps to a dir in `src/content/docs`

## Helpful links
https://github.com/newrelic/docs-website/issues/4185

**Comment by jpvajda** [comment]
from @roadlittledawn 

 i'd actually propose we put it in the backlog beyond that. not sure tech docs will need it soon. it may come in handy if/when we look at overhauling / simplifying nav.

**Comment by rudouglas** [comment]
@jpvajda Wondering if we should close this because the work points would get lost otherwise? Just so the effort is accounted for, we could make a follow-up with the branch in it to determine if any backlog work needs to be done?

**Comment by jpvajda** [comment]
@rudouglas well technically you can't claim points unless you release the code... 🥇 Agile rules

**Comment by rudouglas** [comment]
Aw dang did not know that 😂 that's too agile

**Comment by jpvajda** [comment]
Can we close this now? @roadlittledawn / @rudouglas 🤔
