### ISSUE TITLE
Issue: Metric API limits and restricted attributes

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#4530]
## How can we make our docs better?

It is difficult to understand about define of the timeseries.

> A timeseries is a single, unique combination of a metric name and any attributes.

It is better to add actual example with multiple attributes.
For example, if there are ten hosts and 7 attributes, this equals there are 70 unique metric timeseries.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.81
* **Device**: Unknown

**Comment by jonahaapala** [comment]
@shinji-newrelic do you think linking to [this example](https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/NRQL-high-cardinality-metrics/#dimensional-metrics) would suffice? I go into more detail about the subtleties of cardinality in that doc as it's not always as straightforward as 7 attributes and 10 hosts produces 70 unique timeseries.

**Comment by pizzaz93** [comment]
There's also some additional detail in that document in this section: https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/metric-api-limits-restricted-attributes/#violation-unique-timeseries.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
