### ISSUE TITLE
Docs bug: PDF link in license page is dead

### ISSUE THREAD

**Issue by dbarnesbrownNR** [newrelic/docs-website#4557]
Looks like the PDF link on [https://docs.newrelic.com/docs/licenses/license-information/special-services-licenses/new-relic-premium-support](https://docs.newrelic.com/docs/licenses/license-information/special-services-licenses/new-relic-premium-support) is 404ing and the file has not changed but needs to be added back to the repo. I've got an ask in to our legal content buddies for the replacement file, and whoever takes this can reach out to me for additional context as needed.

**Comment by barbnewrelic** [comment]
@dbarnesbrownNR  In documentation channel our SME confirmed that this doc is being deleted entirely, so no need to restore the PDF. I'll go ahead and close this issue for you.
