### ISSUE TITLE
[Localization] Determine how to handle existing translation PRs

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#4564]
## Summary

We have two outstanding PRs resulting from our translation workflow. The [first failed the build](https://github.com/newrelic/docs-website/pull/4334) (likely a deserialization / parsing error we've seen before). [The second](https://github.com/newrelic/docs-website/pull/4459) successfully built.

Subsequently, the docs team moved a bunch of files around for IA updates (including corresponding `i18n` files as well). So now those two translation PRs have conflicts.

We need to figure out if we should resolve conflicts and merge OR close them in favor of what comes back back in next run. 

## Acceptance criteria

- [x] Delete conflicting files seen in the translation PR. (see above)
- [x] fix any build issues on those PRs 
- [x] merge PRs in.
- [x] if the file should exist, they'd get regenerated on the next localization run automatically. 

## Helpful links
https://github.com/newrelic/docs-website/pull/4462
https://github.com/newrelic/docs-website/pull/4459
https://github.com/newrelic/docs-website/pull/4334

**Comment by nr-kkenney** [comment]
just had to merge develop into the translation branch. git knew that they were renames on the merge.
