### ISSUE TITLE
[Docs] Update release process

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#4569]
## Summary
Tech docs folks have been experimenting with improving the release process for the docs-website to reduce toil. The idea they want to implement is the use of `release` branches for merging content into the `main` branch.

Release branches would be cut from develop when merges to main are needed, and this allows for content to keep being merged into develop, but having a static / controlled branch to merge into main. The release branch will be set up as a protected branch (like develop & main) so that contributors cannot directly push to it.

This should only affect how we release / merge into main: 
- Contributors would still branch from develop & pr to develop.
- Workflows that commit directly to develop and main should not be impacted by this change assuming we set everything up correctly.

## Helpful Links
[Gitflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow)
[Meeting Notes](https://docs.google.com/document/d/1ydLTGIyz_1GnEPAZkA-AjCMwVOV_NCEtOs2OQA0MO3o)

## Acceptance Criteria
- [x] Double check workflows in the repository are unaffected by this change
- [x] Set up branch protection for release branches (look in the meeting notes)
- [x] Notify @bradleycamacho / tech docs team once previous criteria are met. This will let them know they can officially start using this process.

**Comment by zstix** [comment]
🎉
