### ISSUE TITLE
[Docs] Gatsby 4 upgrade

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#4571]
Relates to: https://github.com/newrelic/developer-website/issues/1821

[Migration docs](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/)

## Things to look for
- Update deprecated `nodeModel.runQuery()` & `nodeModel.getAllNodes()`
  - `gatsby-source-nav` & `gatsby-source-data-dictionary` 

### Acceptance Criteria 

- [ ] Upgrade site to Gatsby 4 (Locally)
- [ ] review all the fun errors and assess issues
- [ ] determine resolution and potentially create follow up tickets

**Comment by rudouglas** [comment]
Moving this to Blocked until the Machine Translation branch is merged https://github.com/newrelic/docs-website/pull/5181

**Comment by rudouglas** [comment]
For context here, the site seems to be building just fine, it's the tests that are failing due to the upgrade to `node-fetch v3.0.0` as seen here:

[3.0.0](https://github.com/newrelic/docs-website/runs/4505891434?check_suite_focus=true)

**Comment by jpvajda** [comment]
#5181 is now merged so is this unblocked? 🤞
