### ISSUE TITLE
Vague bullet point in "For more help" section on many(all?) docs pages.

### ISSUE THREAD

**Issue by coreyarnold** [newrelic/docs-website#4577]
Looks like the "For more help" section on all the pages has "Review New Relic's and and documentation." as the last bullet. The user is looking at the docs, is there something specific to point them to? Also we should clean up the "and and" grammar.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.81
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@coreyarnold  I just checked and this has been fixed. Thanks again for letting us know!
