### ISSUE TITLE
Bounce rate data in GA broken since Sep 30

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#4583]
Bounce rate data seems to have dropped off dramatically (by ~90%) since September 30. I presume this is related to OneTrust? Regardless, there's something here that we should dig into next spritn and resolve (might need input from analytics teams to understand what happened here)

**Comment by roadlittledawn** [comment]
looks like this is not a OneTrust thing, but we need to add a property to the relevant Tessen events:
```
nonInteraction: 1
```

Details in Jira ONYX-1312
