### ISSUE TITLE
Setup SLI / SLO and Lighthouse dashboards for Docs Site.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#4585]
Similar to the dashboard we made for the I/O ecosystem we'll make one for Docs Ecosystem.

### Acceptance Criteria

- [x] setup [new lighthouse synthetic check](https://newrelic.com/blog/how-to-relic/monitoring-with-google-lighthouse) for docs.newrelic.com 
- [x] set up Lighthouse scores
- [x] setup ecosystem dashboards
- [x] setup workloads to generate SLO/SLI data , like the devsite.

**Comment by jpvajda** [comment]
@rudouglas i've gotten the[ lighthouse score working](https://staging.onenr.io/0PLRENb9bja) with a new synthetic check i setup for docs. I was curious about where you stored the API key used in that query.

Also perhaps you and I can pair on the workload part of this ticket, I'm interested in that setup up.

**Comment by rudouglas** [comment]
@jpvajda that looks great, assume you're talking about the `$secure.PAGESPEED_API_KEY` in the script? That's stored as a Secure Variable which is a feature of Synthetics.

Happy to go over this with you today if you have time 🕺

**Comment by jpvajda** [comment]
@rudouglas oh great, I was curious if it was stored in a place where the entire team had access. Sounds like it is.

**Comment by jpvajda** [comment]
I have done it.. Workloads for [docs is here. ](https://staging.onenr.io/0LkjnK11XQo)

**Comment by jpvajda** [comment]
I wonder what else we can use workloads for? 🤔
