### ISSUE TITLE
Create script to find repeated links (AKA dummy docs) in navigation files

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#4589]
## Is your feature request related to a problem? Please describe

The docs team is exploring a shift to a new model where each left-navigation link is unique (never repeated across the left navigation). Currently,  we reuse left-navigation links across the site in various places, both in the same navigation file and across navigation files. 

The user experience isn't too bad if the same link is used in the same navigation file, but it isn't very positive if they are taken to a different taxonomy file. This is because readers can get confused about where they are in the taxonomy if they are suddenly taken to another navigation file. 

For example, we have the following links in two different navigation files. This case might be a bit more complex than some because it also involves a redirect:

For example, `distributed-tracing.yml`:
```
https://docs.newrelic.com/docs/distributed-tracing/enable-configure/new-relic-browser/
```
resolves to
```
https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing/ 
```
* browser.yml: [Browser data in distributed tracing](https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/browser-data-distributed-tracing/)

## Describe the solution you'd like

Could you create a script that finds all the left-navigation urls that are duplicates or resolve to duplicate URLs? Our goal is to see the extent of the duplication and perhaps use this list to migrate to this new approach (if migration is feasible).

## Austin's description of desired script behavior

The goal of this script is to find the "final" URL destination of all paths in the nav yml files.

1. Traverse all nav yml files to get a list of all paths
2. For each path, send a request to find the final resolved URL
3. Save out (CSV?) the nav file, original path, and final resolved URL

**Comment by jpvajda** [comment]
This may fit nicely into the sustaining epic we created  #4628

**Comment by jpvajda** [comment]
@roadlittledawn is this still relevant?
