### ISSUE TITLE
Replace current open image in new tab with an in-page Lightbox (or similar)

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#4590]
(related to issue #850)

## Is your feature request related to a problem? Please describe

I don't think that clicking an image and having it open in another tab is ideal. 

## Describe the solution you'd like

I'd love to click our images and see a bigger version of the image directly on the page. 

We should have a UI affordance to close the ligthbox (a close icon). Also close the lightbox with the escape key.

## Describe why this important to you

I think we can do better with how we handle images.

**Comment by roadlittledawn** [comment]
Closing in favor of https://newrelic.atlassian.net/browse/DOCENG-12
