### ISSUE TITLE
[Prototype] Add attribute definitions

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#46]
## Summary
Migrate ~5 attribute definition files to the site.

## Acceptance criteria
- [ ] Create relevant directories for each file. These should go in their directory separate from other content types.
- [ ] Copy HTML from Drupal into the .mdx file
- [ ] Add frontmatter based on [example file](https://gist.github.com/roadlittledawn/a211e47fc0596107b7b7b6bf44f0958e) and relevant field values in Drupal
- [ ] Ensure pages are successfully created on develop and build

## Helpful links
- [Docs OSS Migration: Component Inventory and Interesting/Tricky Docs](https://docs.google.com/document/d/1j7hLEtBmfJdNplk_1T6r8tkBa-c_o4C96fVZu7coo7E/edit#)
- [Drupal workbench > attribute defs pages](https://docs.newrelic.com/admin/workbench/content/all?title=&type=attribute_definition&published=1&state=All&field_page_location_tid=All&uid=&items_per_page=25)

**Comment by jerelmiller** [comment]
We should determine whether we want `.mdx` files for each attribute definition or whether we should consider storing the data in JSON and sourcing that with both the [`createPage` API](https://www.gatsbyjs.com/docs/actions/#createPage) and a template that can pull from that data.

**Comment by roadlittledawn** [comment]
Yep, agree. I think ideally it would be stored in JSON. We would just have to figure out a way to make that JSON:
* editable in a way non-technical authors can access it
* available to docs front end for users to search/filter through all available events/attributes
* available via HTTP call at an endpoint so it's still consumable in roughly the same way it is today by data dictionary
