### ISSUE TITLE
Request to document flamegraph interpretion

### ISSUE THREAD

**Issue by adiosspandit** [newrelic/docs-website#4601]
## How can we make our docs better?
* The flamegraph documentation does not give details of how to interpret the flamegraph
It mentions you can troubleshoot by finding methods that are hotspots but does not descrive how to interpret the flamegraph. 

I ran into a similar situation while helping couple customers set up for JFR. Another user on discussion forum mentions a similar challenge: https://discuss.newrelic.com/t/flamegraph-interpretation-on-jfr-screen/165840

Feel free to reach out to me for some suggestions I have.

### Doc information (don't delete this section)

* https://docs.newrelic.com/whats-new/2020/11/troubleshoot-performance-crash-issues-faster-new-relics-real-time-java-profiling/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 93.0.4577.82
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Closing due to work being done in https://github.com/newrelic/docs-website/pull/4955
