### ISSUE TITLE
Update link and remove reference 

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#4648]
## How can we make our docs better?

* Is something inaccurate or missing? - There are two, hopefully easy fixes needed here. The first, for the caption under the first image, the link needs to be update for: deprecated UI. 

_one.newrelic.com > Browser > (select an app) > JS errors: Use this page to group and filter errors, explore stack trace details, and examine trends. (If your UI page looks different, you may be using an older, deprecated UI.)_

* The second, a customer reached out in the community forum space to report no linking from JSErrors to Session Traces UI. Please remove JSErrors reference as I believe it references our older UI. 

https://discuss.newrelic.com/t/access-session-trace-from-js-error/165841

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/javascript-errors-page-detect-analyze-errors/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
@CherylFrankenfield Thanks! 

On the first point, it looks like the content at that deprecated UI link has been gone for a long time. I'm going to remove that link and reference to that.

Happy to remove the JSErrors reference.
