### ISSUE TITLE
Issue: Guide to using the Java agent API 

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#4654]
The method signatures for insertDistributedTraceHeaders() and accept DistributedTraceHeaders() reference the parameter `Header` with no information on concrete type or example of what type should be used.

Neither the NR-docs or the java-docs explain how `Header`should be constructed.

Did find an example here
[dt-kafka-example](https://github.com/newrelic/newrelic-java-examples/tree/main/newrelic-java-agent/distributed-tracing/kafka-examples)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/java-agent/api-guides/guide-using-java-agent-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hello @GaPeppy - thanks for reaching out! Since we prefer not to duplicate information, I think a good option is to link to the [doc you mention](https://github.com/newrelic/newrelic-java-examples/tree/main/newrelic-java-agent/distributed-tracing/kafka-examples) from our Java API guide. Do you think that would work? Thanks!

**Comment by GaPeppy** [comment]
Linking would be good from NR-Docs.  However the vagueness of the java docs still seems like an undesirable customer experience.


-------- Original Message --------
Subject: Re: [newrelic/docs-website] Issue: Guide to using the Java
agent API  (Issue #4654)
From: Anna Urbiztondo ***@***.***>
Date: Tue, November 02, 2021 2:31 am
To: newrelic/docs-website ***@***.***>
Cc: GaPeppy ***@***.***>,  Mention
***@***.***>

 Hello @GaPeppy - thanks for reaching out! Since we prefer not to duplicate information, I think a good option is to link to the doc you mention from our Java API guide. Do you think that would work? Thanks! —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by urbiz-nr** [comment]
Let me pass this on to the team!

**Comment by urbiz-nr** [comment]
Handling this in #4701. @GaPeppy, feel free to check it out!

**Comment by urbiz-nr** [comment]
Closed via #4701.
