### ISSUE TITLE
Issue: Add and edit monitors

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#4662]
## How can we make our docs better?

There is no timeout information for the newly added Monitor.
Monitor settings > Type
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors/#setting-type

There is no timeout information for **step monitor**,**certificate check**, and  **broken links check** 
Please add the specifications for these new monitors as well.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/using-monitors/add-edit-monitors/
* **OS**: Windows 10
* **Browser**: Chrome 95.0.4638.69
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks @qryuu - I'll pass this on to the team!

**Comment by urbiz-nr** [comment]
Closed via #4769.
