### ISSUE TITLE
Issue: PageViewTiming: Async or dynamic page details

### ISSUE THREAD

**Issue by bkucey** [newrelic/docs-website#4685]
## How can we make our docs better?

* Is something inaccurate or missing?
* `Support for Google's Core Web Vitals` requires a Pro or above Browser agent. The Lite Browser agent won't work. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/page-load-timing-resources/pageviewtiming-async-or-dynamic-page-details/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks @bkucey! Quick question, may we remove all those references to 2020? Thanks!

**Comment by urbiz-nr** [comment]
Closed via #4688.
