### ISSUE TITLE
Improvement on Scalability test article 

### ISSUE THREAD

**Issue by galloq** [newrelic/docs-website#4692]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/reports/other-performance-analysis/scalability-analysis-report/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 95.0.4638.69
* **Device**: Unknown
 
In this article, you have in a little box an explanation of each one of the different tests you can generate from the scalability tool but I would like more detail into them such as: How should a good database scalability test look like? also if it's possible to add a more detailed explanation of how the filter outliers option works and why when you unselect it the line goes flat. 

In general more detail around those tests. 

Thanks in advance.

**Comment by galloq** [comment]
Hello @dbarnesbrownNR  - Thank you in advance for taking the issue I would like to add if it's possible to add more details for the other tests (CPU and response time) as well. 
Thank you.

**Comment by dbarnesbrownNR** [comment]
Thanks @galloq - may I ask you to clarify if you are a New Relic employee not yet added to our org on GitHub or if you are an outside user of our tech? Thanks!

**Comment by dbarnesbrownNR** [comment]
Currently reaching out to SME in this area of our product to figure out how best to address this content ask.

**Comment by galloq** [comment]
Sure, I am an outside user but I just this software for work and thought the documentation for those tests could just, in general, have more information attached to it.

Also, I would like to ask if it's possible for you to indicate to me how to use the API to pull all of the data used to form the scalability test.

**Comment by dbarnesbrownNR** [comment]
Thanks for the context! And yes I agree that more examples could be good here, but running it by one of our internal SMEs to get some suggestions about how we might approach. As for the API question I am unsure but I will check on this and try to get you a good answer. :)

**Comment by galloq** [comment]
@dbarnesbrownNR  - Amazing, thank you very much for the support!

**Comment by galloq** [comment]
@dbarnesbrownNR - Hello how is this going?, just wanted to let you know I am very interested in this having some more details since I am trying to make sense of a couple of scalability tests myself but I am confused. 

Please let me know if there is any resolution date. 

Thank you very much for the support.

**Comment by dbarnesbrownNR** [comment]
Hi @galloq, if you're struggling with an aspect of the product and not sufficiently helped by docs (understandable here since info is not complete!) you can get help right now from Support (https://support.newrelic.com/), but I am also working on a more permanent update to the docs. We have a number of items in our backlog at the moment but as long as your issue is open that indicates intent to address it when we find the answers we are looking for.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
