### ISSUE TITLE
Issue: Rate limits for NRQL queries

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#4693]
## How can we make our docs better?

Are there specific rate limits? For things like the number of FACETS or queries that can be run in each tile, etc? 

I's like to know what the limits are for number of attributes etc that are used in a query

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/rate-limits-nrql-queries/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @dralph3344, I don't believe there's a relationship between number of attributes on a query and rate limiting, and afaik the limits are on total rate, not rate by clause etc, but I will investigate and fill you in on what I find out. Thanks!

**Comment by dralph3344** [comment]
Thanks @dbarnesbrownNR !

Particularly, can we do things like FACET <attribute>, and return like 100 uniques, or 1000, or 10,000?

If we facet CASES, can we manually list out 10 cases, 100 cases, 10,000 cases?

**Comment by dbarnesbrownNR** [comment]
@dralph3344 I think that could work well! Trying to resource a SME who can advise on the particulars.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
