### ISSUE TITLE
[Prototype] Add What’s New / NR1 announcement

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#47]
## Summary
Manually add the sample What's New / NR1 Announcement file to the site.

## Acceptance criteria
- [ ] Create relevant directories for each file. I think these should go in their own directory separate from other content types.
- [ ] Copy HTML from Drupal into the .mdx file
- [ ] Add frontmatter based on [example file](https://gist.github.com/roadlittledawn/d5800ee6f5bbe6707970daa8e7af568d) and relevant field values in Drupal
- [ ] Ensure pages are successfully created on develop and build

## Helpful links
- [Docs OSS Migration: Component Inventory and Interesting/Tricky Docs](https://docs.google.com/document/d/1j7hLEtBmfJdNplk_1T6r8tkBa-c_o4C96fVZu7coo7E/edit#)
- [Drupal workbench > nr1_announcement pages](https://docs.newrelic.com/admin/workbench/content/all?title=&type=nr1_announcement&published=1&state=All&field_page_location_tid=All&uid=&items_per_page=25)

**Comment by jerelmiller** [comment]
@roadlittledawn You might be able to provide some idea here, but how do we plan to surface this content? Are the announcements currently surfaced in the doc site or are they just data points that the product can use to populate the "Whats new" page?

How might we best structure this to be able to continue serving the appropriate content?

**Comment by roadlittledawn** [comment]
@jerelmiller . This is a new content type that was setup back in Feb-ish. It looks like new content was just added while I was out last week-ish. Here is an example:
https://docs.newrelic.com/docs/new-relic-one-has-dark-mode

It's going to be surfaced on both the docs site and in NR1 What's New (which I'd say is the primary channel FWIW). This content is distinct from other docs content, so I think it makes sense to put these in their own directory. I also updated the URL pattern to prepend `whats-new/` to the beginning of the URL path.
