### ISSUE TITLE
Issue: Synthetic monitoring: Troubleshoot downtime

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#4702]
## How can we make our docs better?

I'm filing this ticket on behalf of the customer via support ticket.

Please include the following "Explores Hub Post" into the document as a public specification.

https://discuss.newrelic.com/t/relic-solution-understanding-the-three-strikes-behavior-in-synthetics/113117

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-troubleshoot-downtime/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 95.0.4638.54
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Closed via #4709.
