### ISSUE TITLE
Issue: Java agent configuration: Config file

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#4704]
## How can we make our docs better?

Please unify the indent of the YAML-format configuration.

For example, the following config has four spaces indent and two spaces indent.

```
infinite_tracing:
    trace_observer:
      host: YOUR_TRACE_OBSERVER_HOST
```

I found there are a lot of similar configurations.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@tanaka-takayoshi, thank you for pointing out these indentation inconsistencies! I will get them harmonized.

**Comment by rhetoric101** [comment]
@tanaka-takayoshi, we are correcting this inconsistent spacing in this PR: https://github.com/newrelic/docs-website/pull/4741
