### ISSUE TITLE
#cli-aws-permissions poorly wrote

### ISSUE THREAD

**Issue by andrew-lozoya** [newrelic/docs-website#4721]
## How can we make our docs better? 

https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/#cli-aws-permissions

https://github.com/newrelic/docs-website/blob/main/src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx

The section on  "The CLI uses the AWS SDK to interact with AWS. The SDK will act using the same default profile as the AWS CLI. This profile needs, at a minimum, the following AWS permissions to run the CLI."

Is full of syntax issues and no standard formatting should be something like this:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "CLIAccessPolicy",
            "Action": [
                "cloudformation:CreateChangeSet",
                "cloudformation:CreateStack",
                "cloudformation:DescribeStacks",
                "cloudformation:ExecuteChangeSets",
                "iam:AttachRolePolicy",
                "iam:CreateRole",
                "iam:GetRole",
                "iam:PassRole",
                "lambda:AddPermission",
                "lambda:CreateFunction",
                "lambda:GetFunction",
                "logs:DeleteSubscriptionFilter",
                "logs:DescribeSubscriptionFilters",
                "logs:PutSubscriptionFilter",
                "s3:GetObject",
                "serverlessrepo:CreateCloudFormationChangeSet",
                "secretsmanager:CreateSecret"
            ],
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Sid": "NRLogAccessPolicy",
            "Effect": "Allow",
            "Action": [
                "serverlessrepo:CreateCloudFormationTemplate",
                "serverlessrepo:GetCloudFormationTemplate"
            ],
            "Resource": "arn:aws:serverlessrepo:us-east-1:463657938898:applications/NewRelic-log-ingestion"
        }
    ]
}
```

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

**Comment by rhetoric101** [comment]
@andrew-lozoya, we inserted your code example and will be pushing this to our site shortly (#4742). Thanks again for your contribution!
