### ISSUE TITLE
Issue: Set proxy settings and properties for scripted monitors

### ISSUE THREAD

**Issue by philhub82** [newrelic/docs-website#4737]
Hi all

The example in the section "$network.setProxyPAC" is not accurate.
It just shows the how the second parameter should look like, but not how to implement it in a script.

regards
Phil

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/set-proxy-settings-properties-scripted-monitors/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@philhub82, thanks for your comment about this example. I'll check with our developers and see if we can improve this.

**Comment by rhetoric101** [comment]
@philhub82, I am closing this because our development team is hoping to address this example next week in the docs.
