### ISSUE TITLE
Issue: Use  your charts - "Format Timestamp"

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#4764]
## How can we make our docs better?

Hello! can we have some verbiage on the site that says "Format Timestamp" ? When searching in the docs, it was very difficult to find this particular page and functionality that we needed.

Having those words on the page may make it easier to find this functionality when needed. 

Thankyou!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/use-charts/use-your-charts/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 95.0.4638.69
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@dralph3344, I just set that as the top hit for our internal search engine (Swiftype) when you search for timestamp. Is that enough, or are you thinking we need some way to improve the general SEO for this?

**Comment by dralph3344** [comment]
Hi @rhetoric101 , can we set it as the top result for "format timestamp" ? 

i'd suggest the above as "timestamp" can be a great number of things in the NR platform. But formatting of the timestamp is generally a visualization step.

**Comment by rhetoric101** [comment]
@dralph3344, I'm going to consider this resolved since the search for format timestamp now takes users to that chart page.
