### ISSUE TITLE
Issue: Kubernetes integration: install and configure

### ISSUE THREAD

**Issue by nethippo** [newrelic/docs-website#4767]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* OpenShift Daemon example command line box is empty(missing ?)
* Were you unable to complete a task? (What task?)
I failed installing new relic agent on ROSA for monitoring. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/kubernetes-integration-install-configure/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hello @nethippo - thanks for getting in touch! Have you tried checking the [Explorers Hub](https://discuss.newrelic.com/) for tips?
