### ISSUE TITLE
"Unity" link goes to a 404

### ISSUE THREAD

**Issue by aronmarden** [newrelic/docs-website#4768]
https://docs.newrelic.com/docs/apis/intro-apis/introduction-new-relic-apis/#mobile-api

"Unity" link goes to a 404

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @aronmarden! I'll check with the team, but it looks like the Unity API has been discontinued. Will keep you posted.

**Comment by urbiz-nr** [comment]
Unity has been removed from our services, so I'll be deleting the links in #4790.

**Comment by urbiz-nr** [comment]
Closed via #4790.
