### ISSUE TITLE
Issue: Create custom metrics in Go

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#4784]
## How can we make our docs better?

* can we please communicate that the best practice is now to use the Metrics ingest API, not timeslice metrics? https://docs.newrelic.com/docs/data-apis/ingest-apis/metric-api/report-metrics-metric-api/ 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/go-agent/instrumentation/create-custom-metrics-go/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Closed via #4842.

**Comment by urbiz-nr** [comment]
Finally closing via #4843.
