### ISSUE TITLE
Add 3 intercepts for the Japanese site

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#4807]
## Is your feature request related to a problem? Please describe
We need readers of the Japanese documentation to access Japanese properties when available. 

## Describe the solution you'd like
We need to add 2 redirects for these 2 properties:
- newrelic.com/security => newrelic.com/jp/security
- newrelic.com/pricing => newrelic.com/jp/pricing

## Describe why this important to you
Optimal user experience.

**Comment by roadlittledawn** [comment]
@jmiraNR not quite sure i understand "intercepts" here. can you confirm my interpretation is correct?

i _think_ what you're saying is:

1. as a user i go to a jp docs page like: https://docs.newrelic.com/jp/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring/
2. if any of the links you listed above are on that page, they are automatically modified to point to jp equivalent (as you listed)

**Comment by jmiraNR** [comment]
@roadlittledawn I thought "intercept" was a standard term as it was introduced to me that way. But yes to your thinking. It's what we do with the Sign-up link but for the 3 listed above.

**Comment by roadlittledawn** [comment]
there's only 2 listed in the issue though right? unless i'm losing it, which is possible ;)

**Comment by roadlittledawn** [comment]
## eng note
we do this with signup because signup has its own component that's pulled in via `Link` component. instead of hardcoding checks for links listed in ticket, i think it'd be best to have a more robust solution  in coordination with newrelic.com devs

**Comment by jmiraNR** [comment]
It's 2 URLs.
As for the solution, I don't know how it is implemented for sign-up but the result should be something similar where a reader sees the _local_ links and lands on the _local_ pages.
