### ISSUE TITLE
[Machine Translation] Modify script to send queued Translation Jobs to Vendor

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#4816]
## Summary

We will need to update the scripts for enabling **Machine Translation (MT)**. The way we will be interacting with the Smartling API is identical to how we do it now, we just need some tweaks to the existing scripts along with some additional functionality.

><!> We should test changes to the scripts using the Test RDS Environment updated here [#1538](https://github.com/newrelic/docs-website/issues/2538)

## Details
<details>

At the moment, in the feature branch, there is [one workflow](https://github.com/newrelic/docs-website/blob/feature/machine-translation/.github/workflows/send-content-to-translate.yml) sending translation requests for human translation, and [another workflow](https://github.com/newrelic/docs-website/blob/feature/machine-translation/.github/workflows/send-content-to-machine-translate.yml) for machine translation.

The workflows are identical except that the environment variables have different values between them (machine translation has values pointing at the machine translation project, access).

[The code](https://github.com/newrelic/docs-website/blob/feature/docs-upgrades/scripts/actions/send-and-update-translation-queue.js) that sends translations is the same in both workflows and the input (via environment variables) controls whether it goes to the human project or the machine project.

We need to:
* make sure each workflow only sends its respective translation type
  * machine translation requests are only sent by the MT workflow, HT requests are only sent by the HT workflow
* store `project_id` in jobs table.
  * when the HT workflow runs, HT project id used for batch, job creation and stored in jobs table
  * when the MT workflow runs, MT project id used for batch, job creation and stored in jobs table
</details>

<details>
  <summary>🛑 Testing Scripts</summary>

  You can use the MT Project ID for this but only test with a 1 word change, [see here](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/translation_workflow/testing/README.md#make-a-change-to-translate)

The reason for this is we have a `2 million` word limit per year specifically for Machine Translation

>Average is about 850 words per document. total is about 1.6 million. For MT it’s a total of 2 million words can be translated over a year. we have approximately 1800 pages x 850 (avg word count per page) = 1.6 million

</details>

## Acceptance Criteria
- [send-and-update-translation-queue.js](https://github.com/newrelic/docs-website/blob/feature/docs-upgrades/scripts/actions/send-and-update-translation-queue.js)  script should:
    - [x] Should add relevant `project_id` to the `jobs` table
    - [x] ~Should default to Human Translation project id if an entry in the `translations` table has no `project_id` value (current jobs in the queue)~
    - [x] Should create batches, create jobs, and upload jobs to the relevant project

### Useful links
* [Instructions for Testing](https://github.com/newrelic/docs-website/tree/develop/scripts/actions/translation_workflow/testing)
* [html in smartling, placeholder directives](https://help.smartling.com/hc/en-us/articles/360007894614-HTML)

Relates to: #2341

**Comment by nr-kkenney** [comment]
removing this acceptance criteria:
```
Should default to Human Translation project id if an entry in the translations table has no project_id value (current jobs in the queue)
```

to compensate, we will need to populate the column we eventually create with default values (of human translation project id). 

if we wanted to proceed this way, we would need 2x environment variables, and a few more code changes. i think it will be easier to just supply a default value, and its cleaner -- database doesn't have an extra value (null) and the code doesn't need to handle all these cases.
