### ISSUE TITLE
Issue: Node.js custom metrics

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#4827]
## How can we make our docs better?

* Is something confusing?

> keep the total number of unique custom metrics under 2000.

If I had a custom metric that tracked execution time of a function that is called 500 times is that going to count as 1 metric towards the 2000 or 500?

Is the 2000 cap for a single application or across all applications in the subscription/tenant/enterprise?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/nodejs-agent/extend-your-instrumentation/nodejs-custom-metrics/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@StingyJack  I'll check with support or the engineers, then will update the doc to clarify. Thanks for your patience!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
