### ISSUE TITLE
Drop downs on this page are not responding

### ISSUE THREAD

**Issue by iharika** [newrelic/docs-website#4846]
The dropdowns on the page are not expanding. This one for example - https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api/#json-content

### Doc information 

* https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api/
* **OS**: MacOS
* **Browser**: Chrome and Safari
* **Device**: Macbook

**Comment by x8a** [comment]
Hi, @iharika! Thanks for letting us know about the issue 🙌🏻.

We're tracking issue #4841, which describes the same problem. Please follow up in that issue's conversation and feel free to open a new one with other problems you encounter.
