### ISSUE TITLE
Search does not direct to this page 

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#4861]
## How can we make our docs better?

* please optimize the search so that "attribute dictionary" and "data dictionary" return this page as the primary result when searching. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Hi @dralph3344, looks like "data dictionary" was going there already but "attribute dictionary" was not so I have fixed that. Closing this as the issue seems to be resolved with that update but do reach out if you are still getting weird/misleading results from search after a couple of days.
