### ISSUE TITLE
Missing Attributes

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#4862]
## How can we make our docs better?

* Currently, there are more attributes for this eventType than are defined here in the data dictionary. 

For example:          "nr.isTrueRoot"

For those with NR-internal access, you can see the list here: https://onenr.io/09MR29by4wY 

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by dralph3344** [comment]
I can also provide some internal connections if needed.

**Comment by dbarnesbrownNR** [comment]
Hi @dralph3344, since attributes internal to NR are not visible to all users, we do not include those in the attribute dictionary. If there are any attributes on this list that are not internal-only, feel free to comment here or submit a PR with the new attributes included.

**Comment by dralph3344** [comment]
@dbarnesbrownNR, I dont believe This is not an Internal-only event type. It is public and in all accounts for customers to use.

**Comment by dralph3344** [comment]
Can we please reopen this issue, @dbarnesbrownNR ?

**Comment by jsgithub1** [comment]
Diana is correct, attributes with the "nr." prefix are only visible to NR admins.  They are not visible to customers.   By contrast, attributes that start with "newrelic." are visible to customers.  They are often used to support other customer visible features as well as for internal uses.  For example. "nr.datapointCount" is used by the customer visible "datapointCount()" function in NRQL.

**Comment by dralph3344** [comment]
I see. Are there ways to understand these relationships and attributes better? Is there a reference doc I can lean on, @jsgithub1 ?
