### ISSUE TITLE
Issue: What is an entity in New Relic?

### ISSUE THREAD

**Issue by rkbodenner** [newrelic/docs-website#4869]
Would like to see a description of why/how relationships are created from OpenTelemetry. The "External services" section/example isn't quite specific to OTel.

**Comment by bradleycamacho** [comment]
Relevant doc: https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/what-entity-new-relic/

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
