### ISSUE TITLE
Issue: Introduction to the Log API

### ISSUE THREAD

**Issue by savage-alex** [newrelic/docs-website#4889]
## How can we make our docs better?
![image](https://user-images.githubusercontent.com/25430683/141799617-d0e4559a-15f7-459a-8571-b1ab8af75eee.png)
Dropdown sections do not open in chrome or edge

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/log-management/log-api/introduction-log-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @savage-alex! Thanks for reporting this issue. 🚀

We're currently investigating the problem in this other issue #4841. Please follow the updates in that thread.

**Comment by savage-alex** [comment]
sorry about making a dupe :-(
