### ISSUE TITLE
Download link

### ISSUE THREAD

**Issue by miksh7** [newrelic/docs-website#4891]
Please add a download link as you do e.g. for .NET Agent

**Comment by x8a** [comment]
Hi, @miksh7! Could you tell us what agent is missing the install link? Thanks a lot!

**Comment by miksh7** [comment]
Any version, e.g.. latest https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/new-relic-infrastructure-agent-1207/

**Comment by miksh7** [comment]
This is how it's done for NET agent
![image](https://user-images.githubusercontent.com/1747012/141818680-ab4ec916-cfef-4385-8bd4-fefcff894897.png)

**Comment by x8a** [comment]
I see what you mean. To add the `download` link in the **Release Notes**. I'll pass it along to the team that writes the release notes. Thanks!

**Comment by x8a** [comment]
The team responsible for the infrastructure release notes let me know that they'll add the link from now on. I'll go ahead and close this issue.

Thanks again for letting us know!
