### ISSUE TITLE
Issue: Install containerized private minions (CPMs)

### ISSUE THREAD

**Issue by ferdinand-p** [newrelic/docs-website#4892]
## How can we make our docs better?

It isn't called out in the documentation, but there should be a short explanation that Docker running on Windows needs to be configured to run Linux containers in order for CPMs to work.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 95.0.4638.69
* **Device**: Unknown

**Comment by dbarnesbrownNR** [comment]
Thanks for your input @ferdinand-p! I've reached out to one of our SMEs to confirm this isn't an edge case and review the recommended change.

**Comment by dbarnesbrownNR** [comment]
This is ask handled by my recent PR 4901, which is due to publish to the site later today.
