### ISSUE TITLE
Add intro paragraphs to all Doc site index pages for SEO

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#491]
We should add an intro paragraph to all our list index pages, to help with SEO.

https://docs-preview.newrelic.com/docs/agents
https://docs-preview.newrelic.com/docs/accounts
https://docs-preview.newrelic.com/docs/create-integrations
https://docs-preview.newrelic.com/docs/release-notes

**Comment by austin-schaefer** [comment]
I like this, but I don't think we should make it a launch requirement. Given that we don't have that content today.

**Comment by jpvajda** [comment]
@austin-schaefer Well I think it benefits us to prioritize SEO / Marketing related content contributions to launch the new site, I can ask @veextee to assist here, I'm sure she'd be happy to provide some marketing related content for these pages if she's available.

**Comment by austin-schaefer** [comment]
@jpvajda Oh 100% would love to have this, I just don't think it's a launch requirement since we don't have that content today and it's not actively creating problems.

**Comment by jpvajda** [comment]
adding 1 point of effort, though there is no engineering effort it may just be some back and forth on merging a content PR

**Comment by jpvajda** [comment]
closing as this is covered in @austin-schaefer backlog with the docs-team

**Comment by austin-schaefer** [comment]
Just a heads-up, this is not in our backlog and not on my launch to-do list. There are several hundred of these pages so it's a fairly significant lift. Happy to take a ticket for it htough!

**Comment by jpvajda** [comment]
@austin-schaefer ah ok. I'll make a request. Thanks!
