### ISSUE TITLE
Issue: Use tags to help organize and find your data

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#4930]
What is unclear in this doc is when and how tags are propagated onto the telemetry data storage.

There are 3 ways to add tags for APM and Infra:  UI, API and config-file.  And today, these three paths are treated differently (afaik).  What is unclear is how the tags defined in these 3 paths are applied to the telemetry; that means **events** and **metrics**.

There is also a comment about tags being applied to apm-agents vs entity but very unclear what that statement means.

> Via agent config: These tags are applied at the agent-level, not the entity/application level.

What does that mean?  Where are agent-level tags exposed?  Are they visible in the UI and distinguished from entity-tags?  Are this concept of agent tags propagated to **events** and **metrics**?  If so, how can the customer tell them apart?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/use-tags-help-organize-find-your-data/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
