### ISSUE TITLE
Issue: MySQL monitoring integration

### ISSUE THREAD

**Issue by nethippo** [newrelic/docs-website#4938]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
   MySQL integration doc is referring nginx.yml 
   If installed on-host: edit the config in the integration's YAML config file, nginx-config.yml.

* Were you unable to complete a task? (What task?)
   Failed configuration. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mysql-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for letting us know about this! I fixed it in PR #4940.
