### ISSUE TITLE
Add external link icon to buttons that take a user to the NR1 Product

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#494]
a button that leads you into the product need an indicator that will tell a user we are taking them off the site.

 ex: Add Java Data found on this page: https://docs.newrelic.com/docs/agents/java-agent/getting-started/introduction-new-relic-java

<img width="906" alt="Screen Shot 2020-12-29 at 12 02 49 PM" src="https://user-images.githubusercontent.com/1395158/103307809-44207300-49ce-11eb-91b6-55af4876ca79.png">

**Comment by jpvajda** [comment]
We can just add the external link icon we use on the developer site to indicate a user is being taken off the site. 

<img width="57" alt="Screen Shot 2020-12-29 at 12 07 49 PM" src="https://user-images.githubusercontent.com/1395158/103307938-7b8f1f80-49ce-11eb-9e76-a55a93703f8c.png">

**Comment by jpvajda** [comment]
https://github.com/newrelic/gatsby-theme-newrelic/pull/183

**Comment by jpvajda** [comment]
From @jerelmiller   I think doing this during the  migration via the codemod is probably the way to go. I like that idea:
Here is the code for the codemod: https://github.com/newrelic/docs-website/blob/develop/codemods/buttons.js
codemods/buttons.js

**Comment by jpvajda** [comment]
The thing with this is that it is operating on an AST (abstract syntax tree) of the markdown file, which is really just a fancy way of saying its a structure for representing all of the various syntax pieces of the markdown. You can see that it adds a attribute if there is a link (line 27). We’d likely want to look at that href value, determine if its an external link, and if so, add a child to the button for the Icon


Here is some pseudo code:
```
import { mdxBlockElement, mdxAttribute } from './utils/mdxast-builder'
if (isExternalLink(href)) {
  a.children.push(mdxBlockElement('Icon', [mdxAttribute('name', 'fe-external-link')])
}
```
to apply those changes, you’ll need to re-run the migration (yarn migrate). This takes a couple min to run through everything.

**Comment by austin-schaefer** [comment]
Currently the site automatically adds an external link icon to any link that goes off of docs.newrelic.com. That's useful for links to Wikipedia or Microsoft docs, for example. 

This is automated right now. It doesn't _have_ to be in future, but it'd be nice to have it automated. Would putting it in the migration script mean we only get these added once, and any new links will need to have the icon applied manually?

**Comment by jpvajda** [comment]
@austin-schaefer good question, it be cool if we had logic that would just add the icon when a `to` reference is outside the docs-site domain.

below the 1st button has no link, but the 2nd one would. 

```
<Button
  role="button"
  as={Link}
  to="/docs/agents/java-agent/installation/install-java-agent"
  variant="link"
>
  Read the install docs
</Button>

<Button
  role="button"
  as={Link}
  to="https://one.newrelic.com/launcher/nr1-core.settings?pane=eyJuZXJkbGV0SWQiOiJ0dWNzb24ucGxnLWluc3RydW1lbnQtZXZlcnl0aGluZyJ9&cards[0]=eyJuZXJkbGV0SWQiOiJzZXR1cC1uZXJkbGV0cy5zZXR1cC1qYXZhLWludGVncmF0aW9uIiwiYWNjb3VudElkIjoyNjQwNDA5fQ==&platform[accountId]=1"
  variant="primary"
>
  Add Java data
</Button>
```

**Comment by jpvajda** [comment]
We do this on the dev site in several locations It doesn't seem like a big effort to make the buttons behave this way on the docs site here a [example](https://github.com/newrelic/developer-website/blob/4e2fe4612126310e0a050fc178bc7f5fa6645021/src/pages/nerd-bytes.js#L84) where we reference the feather icon for `external-link`

**Comment by jpvajda** [comment]
@x8a here is a ticket that may interest you. 👋
