### ISSUE TITLE
Issue: Okta SCIM/SSO application configuration

### ISSUE THREAD

**Issue by rajumkc** [newrelic/docs-website#4954]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

1. Step#5 is missing in the "On this page" section
2. "Note that the expected values for user type are Basic user and Full user" . Is that still true?. Based on the values seen in the UI, it is "Basic" and  "Full Platform" . Please confirm

Another Feedback:
Please , please provide a Version history for the documentation. It is impossible to know what changed.  AWS does an excellent job with that in their documentation w.r.t providing what changed in the documentation. Please check that out

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@rajumkc very much appreciated, thank you. yes, 'full user' is equivalent to 'full platform user'. We will attempt to make that more clear in docs. 

Can I ask you: what kinds of changes have you found confusing? We do have these release notes that we recently started https://docs.newrelic.com/docs/release-notes/org-user-mgmt-release-notes/ but they only cover some major releases. I'm curious if that is the kind of thing you're referring to or if there's something that we're missing that is confusing (and maybe you were mainly referring to the 'full user' vs 'full platform user' change).

**Comment by zuluecho9** [comment]
Made changes based on 'full user' vs 'full platform user' issue in https://github.com/newrelic/docs-website/pull/4957.
