### ISSUE TITLE
Improve Product Category Landing Page experience

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#497]
When accessing a product catagory landing page, like FSO, TDP or Alerts and Intel, a user should be presented with a more visually appealing experience then just a index page of links. 

Also some intro descriptive content would be valuable to explain each product category and add SEO capabilities to these pages.

### Category Landing Pages 

https://docs-preview.newrelic.com/docs/telemetry-data-platform

https://docs-preview.newrelic.com/docs/full-stack-observability

https://docs-preview.newrelic.com/docs/alerts-and-applied-intelligence

### Acceptance Criteria

- [x]  a design and approach is provided by @djsauble 
- [x]  the design should try to use existing components so we can build these page templates quickly 
- [ ] content is provided by the docs team

**Comment by jpvajda** [comment]
@djsauble / @austin-schaefer Let me know your thoughts on this need, I recall us discussing these pages and wanted to do something more visual, but I don't remember where we ended up with it. I would like to try to get something more visual on these pages for launch as the index page approach is not ideal for these particular pages.

**Comment by djsauble** [comment]
In terms of using existing components, the approach taken to APM, etc seems quite reasonable.

https://docs-preview.newrelic.com/docs/apm

To make them a bit more visually appealing, we could put a video or screenshot to the right of the description text (as is done on the existing APM page, come to think of it).

https://docs.newrelic.com/docs/apm

**Comment by jpvajda** [comment]
@djsauble great suggestions! would you have some time to just provide a higher level mock fore these pages? It always help to have a visual to go along with these discussions. 😄

**Comment by austin-schaefer** [comment]
@jpvajda : Are you hoping this content will be ready for launch? If so, can you file a DOC jira for writing these? Those pages like the APM one take a while to write and research.

**Comment by jpvajda** [comment]
@austin-schaefer for sure, once we have some mock design I can create that issue in the DOCS backlog. cc / @djsauble

**Comment by jpvajda** [comment]
product videos are available here: https://www.youtube.com/c/NewRelicInc

**Comment by jpvajda** [comment]
@djsauble how are things coming along for the final mock up for this page?

**Comment by djsauble** [comment]
@jpvajda I didn't get any strong pushback to the sketch I shared in Slack, so that's the plan of record as far as I'm concerned. Happy to continue iterating if there's anything else you'd like considered.

![Uploading IMG_0471.jpeg…]()

**Comment by jpvajda** [comment]
@djsauble That works for us to move forward! When we get closer to building the pages perhaps we can pair up with you as we work through the nuances. Thank you!

**Comment by jerelmiller** [comment]
@austin-schaefer the landing pages for FSO ([MDX](https://github.com/newrelic/docs-website/blob/develop/src/manual-edits/content/docs/full-stack-observability/index.mdx), [rendered](https://docs-preview.newrelic.com/docs/full-stack-observability)) and TDP ([MDX](https://github.com/newrelic/docs-website/blob/develop/src/manual-edits/content/docs/telemetry-data-platform/index.mdx), [rendered](https://docs-preview.newrelic.com/docs/telemetry-data-platform)) have been created with some lorem ipsum. Could I get some help getting content for these pages?

**Comment by jpvajda** [comment]
Issues have been filed in the Docs Team Jira project thanks to @austin-schaefer  🚀

**Comment by jpvajda** [comment]
Can this be moved out of blocked? The content is in @austin-schaefer backlog to do, so if we deployed this, I'd call it done @jerelmiller

**Comment by jerelmiller** [comment]
Ooops, meant to come back to this. Yes I'll just close this since the work is captured in Jira for the docs team. Thanks for checking back!
