### ISSUE TITLE
WN on homepage: Add dates and link to view all WN

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#5002]
@daynaslord suggested we add a button/link/CTA that links to https://docs.newrelic.com/whats-new/ from the redesigned homepage.

We should also add dates to make it easier to see at a glance what's new or changing. 

@legnaleama and I have been chatting about some design concepts for this in Slack but figured a GH issue is easier to keep track of.

**Comment by austin-schaefer** [comment]
Some example concepts from @legnaleama 

![image](https://user-images.githubusercontent.com/55203603/142919819-f9dce760-95e2-49d7-8028-4d9826e223d0.png)
![image](https://user-images.githubusercontent.com/55203603/142919837-0b579978-340a-430d-a908-6cf22f92adec.png)

**Comment by daynaslord** [comment]
Thanks for sending these over! QQ: Is it possible to do an A/B test to see
which CTA - See all news or See all updates - works best?

Dayna

**Comment by legnaleama** [comment]
I generally like to use A/B test to validate high impact approaches but I'm not sure this would qualify as one 🤔 ? I'm not saying no but I'm pretty sure the usage would be so small that it would be really hard to see conclusive results.

As for the proposals, I don't think we need to reinvent the wheel here, the main considerations I have towards each option are:

**Bottom (footer) CTA**
👍 It's the standard way of presenting this action item. The user's mental model is already there.
👎 Given the other 2 columns next to "What's new" don't have this pattern, the general appearance looks a bit wonky. 

**Header CTA**
Pretty much the opposite of the pros/cons of the previous case:
👍 We solve the layout problem
👎 It's less visible and less intuitive


As for using a link style to avoid making it as disruptive @austin-schaefer I would recommend against it the main reason being visual similarity. If we use a link after a list of links the chances of that anchor getting lost is quite high, also adding extra modifiers on top of it would just create an unnecessary singular case. 

**My recommendation**, we keep it simple, use the outline button at the bottom and revise in the future if we consider driving traffic to that page a higher priority.

**Comment by daynaslord** [comment]
@legnaleama @austin-schaefer - Let's keep track of what the traffic is like to WN w/o the 'see all' CTA on the home page for a few weeks. If it's poor, then we should do a bottom CTA. We can work to create CTAs for the 'Getting started' and 'Popular content' sections so that the appearance is even across the page. Is there a google analytics link you can share that show traffic to WN docs, specifically from the homepage?

**Comment by austin-schaefer** [comment]
@legnaleama @daynaslord : Thoughts on also including dates when we tweak the design here? Might help show users which WN posts are recent.

**Comment by daynaslord** [comment]
Love that idea - dates would be great!

**Comment by legnaleama** [comment]
Adding more content with the current layout might be a bit tricky as we'll be making the "What's New" section more and more dense in comparison to the other 2 boxes next to it. If we were to go that route, I think it would be interesting to try a more dynamic layout where we give emphasis to the "blog type" content on the page.

My only concern with this is that it changes the perception of what a Docs site is completely. My main question is, **do we want to scale the Docs site to something bigger? or do want to keep it as a up-do-date place to check guides on how to solve technical inquiries?** 
![image](https://user-images.githubusercontent.com/3636549/146991458-ac002cc4-1d74-4e17-a8c2-3d1bb4fc3cf2.png)


@austin-schaefer

**Comment by daynaslord** [comment]
@austin-schaefer @legnaleama - I think we can close this out for now, unless you think otherwise. I'd love to come back to it in the near future
