### ISSUE TITLE
[Docs] Add  gatsby-build-newrelic plugin to site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#5004]
Relates to: https://github.com/newrelic/opensource-website/issues/882

### Acceptance Criteria

- [ ] Update Gatsby config to use gatsby build new relic
- [ ] test on gatsby site for the PR branch
- [ ] Setup up Env variables required for Gatsby build new relic on docs develop site on Gatsby cloud
- [ ] Setup up Env variables required for Gatsby build new relic on docs main site on Gatsby cloud
- [ ] merge changes to develop branch
- [ ] merge develop to main
- [ ] install quickstart for gastby build on our developer enablement account
- [ ] delete test dashboard for opensource-website-gatsby-build-newrelic in New Relic
- [ ] look at some sweet dashboards

**Comment by jpvajda** [comment]
@rudouglas if you wanted to pick this up to help us with our DSG options discussions feel to free to grab it, and if you can point it and add it to the sprint that be 🆒

**Comment by jpvajda** [comment]
we de-prioritized this as we were able to get DSG to work.

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-14
