### ISSUE TITLE
[Docs] Create generic split test components 

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#5018]
## Description
The docs team would like to conduct split tests within doc files. @x8a is working on this component in the #4815 PR.
This component will be able to test a new set of components vs the default set, via an "on/off" type treatment.

## AC
- [x] Determine how to generate a click event when a user clicks on one of the splits
- [x] Determine render solution in https://github.com/newrelic/docs-website/issues/5165
- [ ] Resolve render issues in https://github.com/newrelic/gatsby-theme-newrelic/issues/616
- [ ] Make sure the component can be used within MDX doc files
- [ ] write unit tests!
- [ ] update [documentation](https://github.com/newrelic/docs-website/blob/develop/COMPONENT_GUIDE.md) for docs only components adding this new component to the documentation

**Comment by aswanson-nr** [comment]
My original thoughts on this component:

> Split testing within a doc:
> 1. Testing whether buttons or links work better
> 2. Docs have a variable number of buttons/links
> To deal with a variable number of buttons/links, let’s start with a component that doesn’t care how many children it has.
> This component will handle all of the Split.io logic, but not care what type of content is displayed. Example jsx:
> ```jsx
> const SplitTester = ({ treatmentName, eventName, testChildren, defaultChildren }) => {
>   // do split.io setup stuff
>   // click handlers for the split event
>   return (isReady && isTreatmentOn && <>{testChildren}</> || <>{defaultChildren}</>);
> }
> ```
> Now your split test only needs 2 treatments, ‘on’ or ‘off’, and it can be used on any number of children.
> It can then be used in a doc like this:
> ```jsx
> <SplitTester
>   treatmentName=“superCoolSplitTreatment”
>   eventName=“superCoolSplitTreatmentEvent”
>   testChildren={<a href=“whatevs”>Testlink</a>}
>   defaultChildren={<button to=“whatevs”>TestButton</button>}
> />
> ```

**Comment by zstix** [comment]
The idea I had rattling around in my head was something like this:

```jsx
<SplitTest name="test-name-1">

  <SplitTest.Treatment name="treatment-a">
    <span>Hello</span>
  </SplitTest.Treatment>

  <SplitTest.Treatment name="treatment-b">
    <span>Howdy</span>
  </SplitTest.Treatment>

</SplitTest>
```

**Comment by aswanson-nr** [comment]
Related [newrelic/gatsby-theme-newrelic/issues/369](https://github.com/newrelic/gatsby-theme-newrelic/issues/369)

**Comment by rudouglas** [comment]
Theme component: https://github.com/newrelic/gatsby-theme-newrelic/pull/601

I'm not sure if my approach is what we're looking for and was having trouble with translating and passing the config so i'm not sure what to there?

**Comment by jpvajda** [comment]
We are going to look to resolve https://github.com/newrelic/docs-website/issues/5165 before wrapping this up, so moving to next sprint.

**Comment by jpvajda** [comment]
I think this ticket may have to move back into tenentative next as we didn't solve the problem with #5165, we just identified a solution which we'd do in https://github.com/newrelic/gatsby-theme-newrelic/issues/616
