### ISSUE TITLE
Please provide the Java version in the Notes

### ISSUE THREAD

**Issue by rajumkc** [newrelic/docs-website#5019]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
**Please provide the Java version in the Notes**
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3053/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 95.0.4638.69
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@rajumkc, thanks for mentioning this! I'll check with our development team and see if they can add Java versions!

**Comment by rhetoric101** [comment]
@rajumkc, it turns out that you don't actually need to know the Java versions to run or operate the CPM. If you still need to know, you can log in to the CPM to see the Java version. Does that help?

**Comment by rajumkc** [comment]
@rhetoric101  - I know that. Ideally for a user, it will be good to know before a particular CPM Image version is used  what Java version it is currently supporting. If it is painful to mention the Java version, let's move on
