### ISSUE TITLE
Issue: Okta SCIM/SSO application configuration

### ISSUE THREAD

**Issue by rajumkc** [newrelic/docs-website#5023]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?

A correction is required in the below statement
"Use the User management UI to set users to basic."

I think the statement should be corrected as ""Use the User management UI to set users to **Full User**."

* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts/automated-user-management/okta-scimsso-application-configuration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks @rajumkc, yes, we'll fix that!

**Comment by zuluecho9** [comment]
Fixed w/ https://github.com/newrelic/docs-website/pull/5024
