### ISSUE TITLE
Issue: Real time streaming

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#5031]
## How can we make our docs better?

Image on the page is incredibly large / zoomed. Something might be off with how its nested on the content, or maybe we need some styling around it to limit its size.

![Screen Shot 2021-11-23 at 3 51 40 PM](https://user-images.githubusercontent.com/70179215/143146840-23466841-0836-4792-a711-103be310cdaf.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/agent-data/real-time-streaming/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hey @nr-kkenney, as I've written in #4591, in general I'd like to see some better options for styling and sizing images. What can I do to get some traction on #4591? Thanks!

**Comment by nr-kkenney** [comment]
probably start with @jpvajda @roadlittledawn for their input on priority 🙈

**Comment by jpvajda** [comment]
👋  I'll defer to @roadlittledawn on priority as he's the TPM of Docs and is taking this product decisions on but I like the ideas in #4591, perhaps we can make an image component that can have some properties that can be set to control  things mentioned in 

- Resize/scale
- Justify (left, center, right)
- More readable captions
- other common CSS properties. 

This gets a little tricky though as there are a lot of cases to consider and it would start to feel a bit like a `CMS tool` to provide some of this functionality, so perhaps @roadlittledawn has some ideas...

All in all, this would probably be more of a sustaining task, or innovation and not a full epic, but it really depends on how much functionality is required to allow a non engineer some easy ways to manipulate images on a page.

**Comment by paperclypse** [comment]
This is definitely something we want to keep after.
