### ISSUE TITLE
Issue: Install Java agent using Maven

### ISSUE THREAD

**Issue by nethippo** [newrelic/docs-website#5048]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
--> java version under dependency block should be updated with the latest version for ZIP example. Which makes the beginning customer confused. 
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/java-agent/additional-installation/install-java-agent-using-maven/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 95.0.4638.69
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hi @nethippo, thanks for getting in touch. To avoid this issue in the future, maybe a better option is to use a generic `latest_version` in the examples, instead of a specific version, which at some point will always be out of date. What do you think?

**Comment by nethippo** [comment]
it does make sense. very nice to get the great feedback. thanks

**Comment by urbiz-nr** [comment]
Hi @nethippo - check out PR #5108 for the changes. Feel free to edit it if you'd like to add any other detail. Thanks!

**Comment by urbiz-nr** [comment]
Closed via #5108.
