### ISSUE TITLE
Issue: Real time streaming

### ISSUE THREAD

**Issue by franzknupfer** [newrelic/docs-website#5064]
Image is oversized and not responsive.

**Comment by paperclypse** [comment]
Hi @franzknupfer, thanks for filing the issue. Would you mind getting a little more specific about the image you're referring to and what outcome you'd like to see? (I assume you're referring to the image in the why it matters section of this page: https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/agent-data/real-time-streaming/)

I'm not entirely sure what you mean by "not responsive". Do you mean that you expect the image to resize with the browser window size? Thanks!
