### ISSUE TITLE
Homepage 11-30-2021 no longer shows Security, Compliance, or Legal links

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#5082]
The docs site homepage is much cleaner. Unfortunately, it no longer includes links to Security landing page. Stakeholders have requested its return. Legal landing page is also missing on homepage. If nothing else, these links should appear on the left nav of homepage.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.55
* **Device**: Unknown

**Comment by Broseberg** [comment]
Perhaps can add _Security and privacy_ into the left nav between _Release notes_ and _What's new?_ sections.
