### ISSUE TITLE
Ensure data dictionary page shows in results for specific search terms only

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#5084]
## How can we make our docs better?

* can we please optimize the search so that "attribute dictionary" and "data dictionary" search strings provide this page as the top result?

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@dralph3344, it turns out that we had turned off "attribute dictionary" and "data dictionary" from our search because it loads all the attributes behind the scenes. Our developer enablement team is considering other options. This might not be a quick fix after all.

**Comment by dralph3344** [comment]
Ah, I see. Thanks for the follow up on this! 

I recommend it to NR power users as it's a great resource as one digs into data. 

In that case, I'll start describing it as a "hidden gem" in the docs, and just point people to the URL directly.

**Comment by roadlittledawn** [comment]
[note to selves] 
our global header search filters out the data dictionary's `document_type` (`views_page_content`) deliberately because by default that page shows all attributes in all events, which for any given search query, could match and add noise to search results.

need to noodle more on this to see how we might be able to surface this result for very specific search terms only (e.g., `attribute dictionary`, `data dictionary`, etc)

**Comment by roadlittledawn** [comment]
[note to selves]
when i query swiftype with recent top search terms, data dictionary shows up in some, but didn't actually seem too too noisy. perhaps we could remove that filter for the data dictionary's `document_type` and see how it goes

**Comment by dralph3344** [comment]
It would be really great to get this as an easier resource for folks. 

Instead of loading all event types/attributes, could we define just one event type? Maybe we default to Transaction event type and just limit to that one set of attributes. May not be optimal performance, but it's better than all attributes/event types.  And would still have lots of utility for users working to understand/work with their data.

**Comment by laurenchow** [comment]
Seconding sentiments on usefulness, any customers we've shared this with find it an extraordinary helpful quick reference for navigating NRDB and better understanding data, so would be great to surface this in search/UI to customers (vs. rely on communicating with each customer about the existence of a resource, which has some scale limitations, grin)

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel.
