### ISSUE TITLE
Issue: Introduction to infrastructure integrations

### ISSUE THREAD

**Issue by sri-shetty** [newrelic/docs-website#5089]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* * When I click URL link for the Microsoft Azure cloud integrations from https://docs.newrelic.com/docs/infrastructure/infrastructure-integrations/get-started/introduction-infrastructure-integrations/#cloud opens a blank page (https://docs.newrelic.com/docs/integrations/microsoft-azure-integrations/azure-integrations-list/). If I enter again the url link changes to https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/azure-integrations-list/ and I see the integration list.
* Same problem exist with the url link for the Google Cloud Platform (GCP) cloud integrations.
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/infrastructure-integrations/get-started/introduction-infrastructure-integrations/
* **OS**: Unknown
* **Browser**: Chrome, Firefox and Safari
* **Device**: Unknown

**Comment by sri-shetty** [comment]
I have created a PR for this issue. Please review and merge.

**Comment by urbiz-nr** [comment]
Closed via #5090.
