### ISSUE TITLE
Translate home page banner text

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#5098]
## Summary

Translate the copy and button text in the home page banner.

## Acceptance criteria
- [x] Add text to translations.json
- [x] Give updated json file to @jmiraNR 
- [ ] Get json file back from Julien and and update src/i18n/jp/translations.json

## Helpful links
Related to https://github.com/newrelic/docs-website/issues/5097

**Comment by jmiraNR** [comment]
Can we please include the text contained here:

<img width="1007" alt="Screen Shot 2021-11-30 at 4 56 40 PM" src="https://user-images.githubusercontent.com/71030271/144147203-644d37ec-557f-4338-88ca-7aa2a3ce2cd4.png">
