### ISSUE TITLE
Issue: Metric normalization rules

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#5112]
The current Metric Normalization Edit screen includes a control (button slider) labelled "TERMINATE".  However docs screen shot does not show this control and there is no supporting description of purpose/behavior.

Through experimentation, it appears the "TERMINATE" control determines whether the rules waterfall is exited when the associated pattern is matched.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/ui-data/metric-normalization-rules/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by GaPeppy** [comment]
![image (3)](https://user-images.githubusercontent.com/7082471/144264791-0f08cf78-3dcc-478d-afce-ba7437a8978f.png)

example screen snap shot from production

**Comment by GaPeppy** [comment]
I was not intending my sample as a replacement; just a visual pointer to the control that is missing from current docs.

**Comment by zuluecho9** [comment]
Okay, I didn't replace the screenshot but I did add a note about the 'Terminate' command in this edit https://github.com/newrelic/docs-website/pull/5116/files. Thank you !
