### ISSUE TITLE
Docs site bug: some redirected URLs cause errors & bad loads

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#5119]
Description: Some docs site URLs that are redirects will cause a bad load of the docs site, where the sidebar doesn't work and not all docs are displayed in the sidebar. For an example of this, you can search google for 'new relic style guide' and some of those will cause bad loads of the docs site. 

For a couple specific UrLs that cause this: https://docs.newrelic.com/docs/style-guide/get-started/introduction-style-guide and https://docs.newrelic.com/docs/style-guide/article-templates/agent-release-notes-template-123. Compare those with the proper working of a non-problematic URL: https://docs.newrelic.com/docs/style-guide/writing-strategies/introduction-style-guide/. And this happens with a decent # of redirected URLs. 

There's a convo in the help-deven channel about this from Dec 1 that mentions some other factors I think are involved, including: we have a lot of circular redirects errors in local builds, in the form "There are routes that match both page and redirect. Pages take precendence over redirects so the redirect will not work". It is not obvious why some of the URLs it throws errors for are there, as I can find no evidence of circular redirects for many of them. So I think this is related. I think it's possible some of those errors are related to those redirected URLs appearing in json files (like the swifttype json) but not sure. 

## Steps to reproduce

1. Go to https://docs.newrelic.com/docs/style-guide/get-started/introduction-style-guide and click around in the sidebar. Also note how it doesn't display the docs that are seen in a correct load, as shown here: https://docs.newrelic.com/docs/style-guide/writing-strategies/introduction-style-guide/. 

## Environment

This is happening to everyone I think.

**Comment by aswanson-nr** [comment]
Seeing this error when I navigate to these pages: <img width="1088" alt="Screen Shot 2021-12-01 at 8 57 42 AM" src="https://user-images.githubusercontent.com/70179303/144282067-924330b8-2595-46e9-b24e-57b3044a99e5.png">

**Comment by jpvajda** [comment]
We are going to take a look at this today, as we are seeing this behavior on all many of the pages under the style guide section

**Comment by aswanson-nr** [comment]
This appears to just be an issue related to caching. Emptying the cache and rebuilding the dev branch of the site resolved the issue. Currently doing the same on the main site, will reply here with the result.

**Comment by aswanson-nr** [comment]
The fix worked on `main` as well.
