### ISSUE TITLE
[Docs] 🏗️ Translation Scaling: Infrastructure + KO

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#5127]
**Epic Plan** 

https://docs.google.com/document/d/1R2mm4SSnwtvpuNnBHWx8tbU8tD38qKIn0uXxA-SF-Oc/edit?usp=sharing

**Comment by roadlittledawn** [comment]
This assumes we have gatsby v4 and DSG working and we're able to selectively apply DSG to relevant content (like all i18n pages)

**Comment by pachicodes** [comment]
Hi there @jpvajda, I would love to help to get the translations to PT done.

**Comment by jpvajda** [comment]
@pachicodes That's super cool! I've mentioned this to @roadlittledawn who is the TPM on this project so we'll get back to you on how you can help! We appreciate the willingness to assist.

**Comment by roadlittledawn** [comment]
@pachicodes awesome! @jmiraNR said to ping him and see how you might be able to help

**Comment by nr-kkenney** [comment]
most of the planning is researching / mapping out the terrain for how this will work. the one thing I wanted to call out that @roadlittledawn and I discussed is that we would like to confirm before we start any work is that build times will be unaffected by adding in more locales with DSG.

@josephgregoryii has a branch that implements the DSG changes and is able to build and run locally. so my current plan is to:
1. cut a testing branch from joe's branch to introduce my changes into.
2. create a new locale in the testing branch. this will likely just involve copying content to a new locale folder -- doesn't have to actually be translated content.
3. other changes I don't know about 🙈 
4. build the site a few times and record results.

**Comment by roadlittledawn** [comment]
thus far, with JP MT files now in the repo, looks like builds are taking ~21min. that's up from about ~17min, so +4min or so.
