### ISSUE TITLE
Telemetry SDK Link Broken

### ISSUE THREAD

**Issue by jcountsNR** [newrelic/docs-website#5147]
Steps

- open [telemetry SDK ](https://docs.newrelic.com/docs/data-apis/ingest-apis/telemetry-sdks-report-custom-telemetry-data/) section
- Select the link labeled [open source telemetry integrations ](https://docs.newrelic.com/docs/integrations/open-source-telemetry-integrations/)
- page is not found

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/ingest-apis/telemetry-sdks-report-custom-telemetry-data/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.55
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey @jcountsNR, thanks for reporting this! I'll get a fix up in a second.
