### ISSUE TITLE
I cant Create Metrics with 'SINCE XX minutes ago' on nrql, SINCE and UNTIL  keywords are not supported in this context.

### ISSUE THREAD

**Issue by danielalv777** [newrelic/docs-website#5161]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/convert-to-metrics/create-metrics-other-data-types/
* **OS**: Windows 10
* **Browser**: Chrome 96.0.4664.45
* **Device**: Unknown

**Comment by danielalv777** [comment]
eventsToMetricsCreateRule( ... nrql: "FROM PageAction SELECT filter(uniqueCount(cart_id), WHERE name='Pago aceptado') SINCE 15 minutes ago")

and I got the error: "description": "The SINCE and UNTIL keywords are not supported in this context.  Please modify your NRQL.".

i want to metric the event data since 15 minutes ago

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
