### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Indraaw94** [newrelic/docs-website#5164]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/release-notes/mobile-release-notes/android-release-notes/android-5230/
* **OS**: Android 11
* **Browser**: Chrome 96.0.4664.45
* **Device**: [mobile] Xiaomi Redmi Note 9 Pro

**Comment by barbnewrelic** [comment]
@Indraaw94 Please clarify what problem you noticed. Once we have more details, we will be able to triage your issue. Thanks!

**Comment by barbnewrelic** [comment]
@Indraaw94  I am closing this issue. If you have more details that will help us determine what actions to take, please don't hesitate to reopen this!
