### ISSUE TITLE
Issue: Go: Configure logs in context

### ISSUE THREAD

**Issue by panda8zcrypto** [newrelic/docs-website#5168]
## How can we make our docs better?

* Is something confusing?

the 4th step is:  Configure logs in context for Go using the Logrus extension.

Can I use github.com/uber-go/zap? and when I use github.com/uber-go/zap, how to set up the new-relic.

* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)
I don't know how to config logs in context for golang when I  use github.com/uber-go/zap.
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-go/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.55
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@panda8zcrypto Hi Panda. Can you go into more detail about what you're trying to accomplish? Are you asking if you can use Zap instead of using Logrus? Just want to make sure I'm understanding your goals so I can ask the right people (either logging-related or Go-related).

**Comment by panda8zcrypto** [comment]
>  Are you asking if you can use Zap instead of using Logrus? 

yes!

**Comment by panda8zcrypto** [comment]
> Are you asking if you can use Zap instead of using Logrus?
yes!

**Comment by zuluecho9** [comment]
@panda8zcrypto it looks like zap is not yet supported but it's in the list of requested features

**Comment by panda8zcrypto** [comment]
> @panda8zcrypto it looks like zap is not yet supported but it's in the list of requested features

Got it ，thanks @zuluecho9
