### ISSUE TITLE
Issue: Use tags to help organize and find your data

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#5187]
## How can we make our docs better?
The number of characters is listed in the tag limit, but is there a limit on the type of characters?

Is it only ASCII characters?
Can I use symbols and non-English characters?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/core-concepts/use-tags-help-organize-find-your-data/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@qryuu thanks. I think we've addressed this with this PR. https://github.com/newrelic/docs-website/pull/5385 Much appreciated! Please let us know if it's still confusing.
