### ISSUE TITLE
Issue: Forward your logs using the infrastructure agent

### ISSUE THREAD

**Issue by alejandroalv87** [newrelic/docs-website#5190]
I cannot forward logs from my servers to NR. When it comes to infrastructure logs do I need to install any log procesor? 
From https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/ I see that we need to 
Create a logging.yml configuration file, and add the parameters you need. The logging.d directory has various .yml.example files you can use as a reference or starting point. which they are as an example and I am using this:

logs:

 
 # entries for the application, system, powershell, and SCOM channels
  - name: windows-application
    winlog: 
       channel: Application
  - name: windows-system
    winlog: 
       channel: System

 # Entry for IIS logs with logtype attribute for automatic parsing
  - name: iis-log
    file: C:\inetpub\logs\LogFiles\W3SVC2\u_ex*
    attributes:
      logtype: iis_w3c

system: windows server 2016
agent version: 10.20.7

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/
* **OS**: Windows 10
* **Browser**: Chrome 96.0.4664.45
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@alejandroalv87  Our infrastructure agent works as the log forwarder. It acts as a lightweight data collector, without having to use additional software. The "System requirements" section https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/#requirements  describes the various operating system requirements, and the rest of this doc walks you through the various setup options. If you need additional help with setting up log forwarding with our infrastructure agent,  we recommend that you file a support ticket. Then, if our support or engineering teams notice any discrepancies in the documented setup requirements, they will update this doc. Hope this helps!

**Comment by barbnewrelic** [comment]
@alejandroalv87  I will assume the info we provided several weeks ago answered your question, so I am taking the liberty of closing this issue. Feel free to file docs issues here, or contact support through your standard support channels anytime!
