### ISSUE TITLE
Unable to find uninstall instructions for new relic kubernetes integration

### ISSUE THREAD

**Issue by adiosspandit** [newrelic/docs-website#5202]
## How can we make our docs better?
* Uninstall instructions for kubernetes integration are not available.
e.g. clear instructions like below will help: 
helm  --uninstall newrelic newrelic/nri-bundle
if kubectl then :
kubectl delete -f some-manifest-file.yml

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.55
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@adiosspandit  Would you please look at https://docswebsitedevelop-fix5202.gtsb.io/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm/#uninstall and let me know if this looks right? In particular any specific spacing. Thanks!
