### ISSUE TITLE
Issue: Introduction to the Amazon ECS integration

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#5219]
Most integrations have a "Find and Use Data" section.  Would be helpful that this integration educated the customer on the data-source, data collected (inventory & metrics), and the target storage location.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/elastic-container-service-integration/get-started/introduction-amazon-ecs-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @GaPeppy, do you mean content like this? https://docs.newrelic.com/docs/infrastructure/elastic-container-service-integration/understand-use-data/understand-use-ecs-data/

**Comment by GaPeppy** [comment]
There is an enumeration of the data sourced via cloudwatch on the ECS-CloudIntegration docs page.  The end-user should be able to map back the source of data and use AWS reference source docs as necessary.  There is **_no_** enumeration of the data and source on the ECS-On-Host-Integration page.

It would seem beneficial to have the same standard of documentation for each component.  In these somewhat unique cases were target-technology coverage is generated through two or more components; it would be a bonus to describe how the multiple-streams-of-telemetry are leveraged in the ingest pipeline for a total picture of operational health of the target technology.

But at a minimum, let's have a standard for integration-component documentation.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
