### ISSUE TITLE
Debian 11 compatibility

### ISSUE THREAD

**Issue by amanfredini76** [newrelic/docs-website#5224]
Hi,

can you add compatibility for debian 11?

**Comment by paperclypse** [comment]
Hi @amanfredini76, would you mind clarifying where you'd like compatibility for Debian 11? Thanks!

**Comment by amanfredini76** [comment]
> Hi @amanfredini76, would you mind clarifying where you'd like compatibility for Debian 11? Thanks!

I'd like to have them in new relic agent, especially for varnish agent and redis agent

**Comment by paperclypse** [comment]
This is useful feedback for our APM team. I'll get this forwarded along to them. Thanks!
