### ISSUE TITLE
Missing link within solution paragraph? 

### ISSUE THREAD

**Issue by jeffchiudev** [newrelic/docs-website#5242]
## How can we make our docs better?

within the first paragraph in the solution section:
> If you have **deployed the infrastructure agent** and completed the **Kubernetes installation procedure** but are not seeing any information in the Kubernetes dashboard, follow these steps:

The first link, "deployed the infrastructure agent" links back to this same page? Was just doing some troubleshooting and was hoping it would lead to another helpful article I could point a customer in. Not quite sure if it is supposed to point back on itself, but it seems like it should lead to a doc about deploying the infrastructure agent? 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/troubleshooting/kubernetes-integration-troubleshooting-not-seeing-data/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.55
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @jeffchiudev! Thanks for spotting this! I fixed it in PR #5246.
