### ISSUE TITLE
Issue: Troubleshoot password, email address, and login issues

### ISSUE THREAD

**Issue by dkthorne1** [newrelic/docs-website#5244]
We had to update our SSO certificate as the old one expired.  I uploaded the certificate but now it appears that SSO is disabled.  Can someone enable it?  I am unable to login  at all.

**Comment by x8a** [comment]
Hey, @dkthorne1! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.

**Comment by dkthorne1** [comment]
Thank you for the quick response.  Got it figured out.
