### ISSUE TITLE
Issue: Find help and use the Support portal

### ISSUE THREAD

**Issue by radiosterne** [newrelic/docs-website#5248]
## How can we make our docs better?

* Is something confusing? Yes
* Is something inaccurate or missing? Yes
* Were you unable to complete a task? (What task?) Yes, I was.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/find-help-use-support-portal/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

Guys, I can't even begin to describe my frustration,

Seemingly unrelated to the docs: I can't login to NewRelic for at least a month now. My completely normal account after logging in is redirecting me to https://one.newrelic.com/launcher/nr1-core.explorer?state=4d67c8e5-f01a-bbc1-a4f7-ec725144150d, and this page is erroring 100% of the time I hit it. I am unable to navigate to ANY working NewRelic page.

But I'm clicking on the ever-helpful «visit our support center» link, and on the «I need more support» link afterwards. On the page https://support.newrelic.com/s/support I am greeted with dropdown «select your account», which never works. It doesn't open, it doesn't provide any options, it doesn't simply work.

I even have stumbled in my quest to finally log in to my chersihed account on the page https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/find-help-use-support-portal/ . It is not helpful at all, it is 100% useless page of «lorem ipsum» text, bu-u-ut it provides a very helpful link to «file a support ticket». It leads me to URL https://support.newrelic.com/tickets. This URL is giving me, or anyone else on the Net, or any person in this beautiful world a four-oh-four error.

My question is: should I, perhaps, consider any of your competitors? Should you, maybe, revert your codebase to your pre-«NewRelic One» status, when everything worked flawlessly, as opposed to your new glorified interface, which I can't even see, because of your botched migration? Should you maybe update your own documentation to some state resembling viable, as opposed to your current state, where two random links I clicked on two random pages have lead me to error states of your own UI? Maybe you would be so kind to provide me with examples and migration docs, so that I can migrate to your competitors easily and forget about his nonsense of yours? 

Any help, suggestions and fixing your own service would be kindly appreciated.

Eagerly awaiting your reply,
almost a decade user of NewRelic, who is unable to log in into your new shiny microservice nightmare.

**Comment by barbnewrelic** [comment]
@radiosterne  I just heard back from Support. They needed your email address to contact you directly, so I gave them the email address that's on your GitHub profile page. I hope that works out for you. Good luck!

**Comment by barbnewrelic** [comment]
@radiosterne PS: Support also pinged me on Friday: "FWIW, there isn’t anything that looks to be wrong with their user. My first suggestion to them would be to clear their cache, try a different browser, and ensure that they are using one of the latest two version of the supported browsers."
