### ISSUE TITLE
Issue: Muting rules: Suppress notifications

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#5282]
## How can we make our docs better?

We need to add an explanation that we don't intend to specify the day of week option when the duration between Start and End is over one full day. This is discussed in our internal GTSE-12744.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by pizzaz93** [comment]
This might be solved or could potentially be added to https://github.com/newrelic/docs-website/pull/5567.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
