### ISSUE TITLE
Issue: Outlier detection (NRQL alert)

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#5304]
## How can we make our docs better?
This page should not be deleted yet.

However, I think it needs a note about EOL.
https://nerdlife.datanerd.us/new-relic/end-of-life-eol-nrql-outlier-alert-conditions-types-6072cba9-2e05-4959-9db7-32336b80d398

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/outlier-detection-nrql-alert/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@qryuu  Documentation about the upcoming EOLs will be coming soon. Stay tuned!

**Comment by barbnewrelic** [comment]
PR for DOC-7607 will fix this issue.

**Comment by barbnewrelic** [comment]
Fixed with PR 5377
