### ISSUE TITLE
Issue: Introduction to Alerts

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#5305]
## How can we make our docs better?
<html>
<body>

Detect outliers from group behavior | Use outlier detection to detect when one or more data sources in a defined group deviate from the behavior you expect from that group.
-- | --

</body>
</html>
This line should not be deleted yet.

However, I think it needs a note about EOL.
https://nerdlife.datanerd.us/new-relic/end-of-life-eol-nrql-outlier-alert-conditions-types-6072cba9-2e05-4959-9db7-32336b80d398
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/learn-alerts/introduction-alerts/
* **OS**: Windows 10
* **Browser**: Chrome 96.0.4664.93
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@qryuu  We are planning to provide more documentation about the upcoming EOLs, including the various alert functions. Stay tuned!

**Comment by barbnewrelic** [comment]
PR for DOC-7607 will fix this issue.

**Comment by barbnewrelic** [comment]
Fixed with PR 5377
