### ISSUE TITLE
ApplicationAgentContext Data type missing

### ISSUE THREAD

**Issue by rajumkc** [newrelic/docs-website#5321]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
ApplicationAgentContext is missing
Ref: https://github.com/newrelic-experimental/nr-find-log4j#auditing-new-relic-java-agent-usage

* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
