### ISSUE TITLE
Analyze large spike in Swiftype queries the week of Jan 8th

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#535]
we saw an EXPLOSION of search queries on the docs site on Jan 8. It's settled back down, but it was up 22x that day. We should probably look into blocking whatever the source was to prevent a surprise huge bill for this month.

**Comment by roadlittledawn** [comment]
are the numbers we're seeing reported by swiftype in the [admin UI](https://app.swiftype.com/engines/new-relic/analytics/overview) or in the email they send out?

i just queried search data for Jan 8 for docs site and i'm not seeing anything unusual so far.

**Comment by jpvajda** [comment]
Same here... the large spike is reported in the email and within the swiftype admin UI but the data doesn't actually reflect that volume. I pulled down the reports and have them on G-Drive if anyone needs to see them. @austin-schaefer 

<img width="378" alt="Screen Shot 2021-01-11 at 4 04 30 PM" src="https://user-images.githubusercontent.com/1395158/104248441-bbbabd00-5426-11eb-8665-0065f32743bf.png">

**Comment by jpvajda** [comment]
@roadlittledawn said yeah it would, but only for the sites/services that are capturing enough data to determine that AND one we have reporting access to. for Drupal we have the PHP agent and New Relic Browser reporting good amount of data where we can tell if that activity is suspicious (request header for synthetics, disproportionate volume from one IP, an obvious user agent name that’s set, etc). i don’t think you get much data via that swiftype report they generate to determine that.
we may be able to submit a support request and ask Swiftype what domains / IPs requests came from that day. i can submit that.

**Comment by jpvajda** [comment]
We think we narrowed this down to a time when we were troubleshooting the build process and it may have been caused by this troubleshooting. Therefore we can close this as it shoudn't happen again.

**Comment by jpvajda** [comment]
@jerelmiller will added context...
