### ISSUE TITLE
Issue: Request feedback on CodeStream

### ISSUE THREAD

**Issue by Zorro58** [newrelic/docs-website#5359]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/codestream/how-use-codestream/request-feedback/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @Zorro58! Thanks for filing an issue. Would you mind expanding on what kind of feedback you're requesting on CodeStream?

**Comment by paperclypse** [comment]
I'm going to go ahead and close this one. When you follow up with some more info, this issue will be re-opened. Thanks!
