### ISSUE TITLE
Color format blocks of code based on their language

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#5374]
This came in as a request in our Documentation channel.

## Is your feature request related to a problem? Please describe

Our code blocks are pretty drab, but they could be much more readable with a little bit of color added. Our code blocks currently support adding languages to them using the format:

	  ```java
	  [java code]
	  ```

For example:

![image (5)](https://user-images.githubusercontent.com/7992384/146609173-2ac59d4b-0c85-4a3c-9770-49b2ffd4d2f1.png)
![image (6)](https://user-images.githubusercontent.com/7992384/146609176-f1c84faa-b7ad-4132-a351-f1cf063f7522.png)

## Describe the solution you'd like

I've like this to use the code block format we're already using.

## Describe why this important to you

I think that adding color formatting to our blocks of code would greatly improve the code readability on our docs site.

**Comment by brnhensley** [comment]
Hi, thanks for making this Issue for me, I was the one suggesting it in the docs slack. [Here's a link to that conversation](https://newrelic.slack.com/archives/C0DSGL3FZ/p1639770259110700).

Personally I think well formatted code examples with language specific syntax highlighting goes a long way towards making the docs more user friendly for both customers and support people.
