### ISSUE TITLE
Issue: Python custom metrics

### ISSUE THREAD

**Issue by lowang** [newrelic/docs-website#5388]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)
YES - I was trying to record custom metric from simple python script, no framework, no whatsoever  
just `python3 report_custom_metric.py` with `NEW_RELIC_APP_NAME & NEW_RELIC_LICENSE_KEY` envs:
```
import newrelic.agent
application = newrelic.agent.application()
newrelic.agent.record_custom_metric('Custom/BM/properties_maps_missing/name', 22, application)
```
Then I've found following problems:
- by default NR is disabled so you have to put `NEW_RELIC_ENABLED: 'true'`
- application created like that doesn't get activated
- even if I register/activate an app it doesn't send metric at all

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/python-agent/supported-features/python-custom-metrics/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 94.0.4606.61
* **Device**: Unknown

**Comment by lowang** [comment]
on the other hand `newrelic_telemetry_sdk` works out of the box:
```
from newrelic_telemetry_sdk import GaugeMetric, MetricClient
metric_client = MetricClient(os.environ["NEW_RELIC_INSERT_KEY"], host='metric-api.eu.newrelic.com')
metric = GaugeMetric("Custom/BM/properties_maps_missing/name", 30)
response = metric_client.send_batch([metric])
response.raise_for_status()
```

**Comment by zuluecho9** [comment]
thank you @lowang, we will look into this.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
