### ISSUE TITLE
[Prototype] Add auto-generated directory index pages

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#54]
## Summary
Automatically generate directory index pages for directories that do not already have an authored index.mdx (landing page) that are super basic, roughly similar to existing index pages.

## Acceptance criteria
- [ ] In gatsby-node.js, map relationship for mdx files to directories, directories to other directories
- [ ] Create template to handle the data you pass to it and render content (likely need to use a different template than the basic one created to display other .mdx files)

## Helpful links
[Docs IA](https://whimsical.com/8tBfw8Squs35bvTo5acsC6)
[Example from my prototype](https://github.com/roadlittledawn/gatsby-netlify-cms-example/blob/master/gatsby-node.js)

**Directory index page examples**
https://docs.newrelic.com/docs/synthetics?toc=true
https://docs.newrelic.com/docs/agents/php-agent/getting-started

**Comment by zstix** [comment]
I pushed up some work-in-progress code on the branch `zack/auto-generate-index-pages`. I left some comments in the script file, but the basic gist of what's left is:
* Recursively walk through the generated directory structure
* If a directory doesn't have an index page, create one (functionality already created)

I'm also not sure if we want the index pages to show all links in _just_ the directory, or in the directory _and_ all directories under it. Might be easier to decide once we have something complete to look at.
