### ISSUE TITLE
Website Feedback

### ISSUE THREAD

**Issue by behlgaurav** [newrelic/docs-website#540]
## Description

[NOTE]: # Spelling mistake in Browser monitoring and search engine optimization - "Browwwwser" 
[TIP]: # (Do NOT give us access or passwords to your New Relic account or API keys!)

## Steps to Reproduce

[NOTE]: # Open https://docs-preview.newrelic.com/docs/browser/new-relic-browser/performance-quality/browser-monitoring-search-engine-optimization/#why-javascript

## Expected Behavior

[NOTE]: #  "Browwwwser" should be spelled as " "Browser" 

## Relevant Logs / Console output

[NOTE]: # (Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible.)

## Your Environment

[TIP]: # (Include as many relevant details about your environment as possible.)
[TIP]: # (ex: Browser name and version)
[TIP]: # (ex: Operating System and version)

## Additional context

[TIP]: # (Add any other context about the problem here.)

**Comment by paperclypse** [comment]
Hi @behlgaurav! Thanks for letting us know! This is a deliberate error that we've been using for some internal GitHub training.

**Comment by mmfred** [comment]
@behlgaurav - Thanks for taking part in our unmoderated docs test :)
