### ISSUE TITLE
Issue: NGINX monitoring integration

### ISSUE THREAD

**Issue by literakl** [newrelic/docs-website#5402]
I miss here information how to install the sample configuration: `sudo apt install nri-nginx` 
I cannot configure the config unless it is present on my system.

Context: https://discuss.newrelic.com/t/nginx-open-source-integration-unsupported/171527/3

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
