### ISSUE TITLE
Issue: Manage your dashboard

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#5404]
There is a chart type does not supported by exporter.
As instance, stacked bar chart is not supported and just printed as blank when exporting to PDF.

## How can we make our docs better?

Please add describe limitation or supported chart types.

https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard/#dash-esport
https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/manage-your-dashboard/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reaching out, @shinji-newrelic! I've spoken with the team and this is something they're working on improving. We'll assess how long before the changes take place, and update docs accordingly. Thanks!

**Comment by urbiz-nr** [comment]
Jira'd as DOC-7632.

**Comment by urbiz-nr** [comment]
Closed via #5683.
