### ISSUE TITLE
Please mention Log4J version in the documentation

### ISSUE THREAD

**Issue by rajumkc** [newrelic/docs-website#5411]
## How can we make our docs better?

* Is something confusing?
Yes, Please mention Log4J version in the documentation
* Is something inaccurate or missing?

Yes, Please mention Log4J version in the documentation

* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/release-notes/synthetics-release-notes/containerized-private-minions-release-notes/containerized-private-minion-cpm-3058/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.55
* **Device**: Unknown

**Comment by rajumkc** [comment]
Java release notes mention Log4J version explicitly.  https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/

CPM release notes also should do the same.

**Comment by paperclypse** [comment]
@rajumkc Thanks for mentioning this! I'll bring it up with our CPM team.

**Comment by paperclypse** [comment]
We'll be updating this soon, thanks!
