### ISSUE TITLE
Issue: データが表示されない（PHP）

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#5418]
Wrong page title in the left pain.
Title of this page is 'データが表示されない（PHP）' but it shows 'データが表示されない（java）'  on the left pain menu.

## How can we make our docs better?

'(java)' should be removed or replaced to '(php)'

### Doc information (don't delete this section)

* https://docs.newrelic.com/jp/docs/apm/agents/php-agent/troubleshooting/no-data-appears-php/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.110
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @shinji-newrelic - I'm passing it on to the site engineers so they can have a look.

**Comment by urbiz-nr** [comment]
@zstix - looks like this has been fixed, can you confirm? Thanks!
