### ISSUE TITLE
Issue: Data privacy with New Relic

### ISSUE THREAD

**Issue by pberryman** [newrelic/docs-website#5420]
## How can we make our docs better?

Broken links:
On the [Data Privacy page](https://docs.newrelic.com/docs/security/security-privacy/data-privacy/data-privacy-new-relic/) on the Docs site, under the Personal data transfer section, there is a link that needs to be updated. Currently points to _https://newrelic.com/content/dam/new-relic/termsandconditions/Online_New_Relic_DPA_20Jul20.pdf_ but needs to point to the latest document, _https://newrelic.com/sites/default/files/2021-09/New_Relic_GDPR_DPASCC_Sep2021.pdf_. There appears to be a redirect to the new form, but want to hard code it correctly on this page in case the redirect is removed.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/security/security-privacy/data-privacy/data-privacy-new-relic/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 95.0.4638.69
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for pointing this out, @pberryman! #5422 will update the link.
