### ISSUE TITLE
Issue: NRQL syntax, clauses, and functions

### ISSUE THREAD

**Issue by knw257** [newrelic/docs-website#5425]
The 'Since' section doesn't indicate what 'phrases' are valid. It also indicates a UTC timestamp can be used, but doesn't say *HOW* to use it. What if I want to see everything since the beginning? I can't use 'since forever', so how do I do that? None of this is properly documented

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/
* **OS**: Windows 10
* **Browser**: Chrome 96.0.4664.110
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for getting in touch, @knw257! I'll check with the team and expand the explanation. Please keep in mind it's the Holiday season so it can take a little longer than usual.

**Comment by urbiz-nr** [comment]
Closed via #5440.
