### ISSUE TITLE
Issue: PHPエージェントの互換性と要件

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#5426]
## How can we make our docs better?

Wrong text on the menu in left pain.
Page title in Japanese is **PHPエージェントの互換性と要件** but menu item name is **C SDKの互換性と要件**
**C SDK** should be corrected to **PHPエージェント**

### Doc information (don't delete this section)

* https://docs.newrelic.com/jp/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.110
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for getting in touch, @shinji-newrelic. The Engineering team noticed a few of these mistakes when analyzing your issue #5418 and they're looking into it. We'll keep you posted!

**Comment by urbiz-nr** [comment]
@zstix - looks like this has been fixed, can you confirm? Thanks!
