### ISSUE TITLE
Issue: PHP agent installation: Tar file

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#5427]
## How can we make our docs better?

I think something note is needed. If the php agent is installed to follow this steps, so file is stored in unarchived folder.
That means if .gz file is downloaded on /tmp folder and extract to same folder, so file is gone and php agent doen't work after restart machine.

for example, it should not be unarchived to /tmp folder.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-tar-file/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hi @shinji-newrelic! Would adding a note on not saving to the tmp folder suffice, then? Thanks!

**Comment by urbiz-nr** [comment]
Closed via #5460.
