### ISSUE TITLE
404 on link to list of on-host integrations

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/docs-website#5473]
The link in this page to https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/ is broken (404).

There is another broken link to the same URL on another page: https://docs.newrelic.com/docs/infrastructure/host-integrations/get-started/introduction-host-integrations/.

Conceptually, the list exists as a section on the sidebar: "On-host integrations > On-host integrations list", but the header of this section in the sidebar does not link to anything (it's not a link, just a header).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/get-started/introduction-host-integrations/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.110
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reaching out, @maxlemieux - we'll look into this!

**Comment by urbiz-nr** [comment]
Fixed via #5498.
