### ISSUE TITLE
broken links : Set up network syslog monitoring

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#5475]
## How can we make our docs better?
[Network syslog devices prerequisites](https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring/#devices-prerequisites)
Some of the vendor documents are broken links.

- The document link for Checkpoint is displayed as Not found. I think it should state that login is required as follows.

> - [Checkpoint - Security Gateway](https://sc1.checkpoint.com/documents/R80.40/WebAdminGuides/EN/CP_R80.40_LoggingAndMonitoring_AdminGuide/opics-LMG/Working-with-Syslog-Servers.htm)(You must sign in to the checkpoint User Center/PartnerMAP.)

- This link will display as 404 - Page Not Found.
> - [Palo Alto - PAN-OS](https://docs.paloaltonetworks.com/pan-os/10-1/pan-os-admin/monitoring/use-syslog-for-monitoring/onfigure-syslog-monitoring.html)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for letting us know, @qryuu - this will be fixed in #5476.
