### ISSUE TITLE
Issue: Python Agent docs 404

### ISSUE THREAD

**Issue by Greg-Myers-SB** [newrelic/docs-website#5477]
## How can we make our docs better?

Search result link to python agent from Google, bing, Duck-Duck-Go, Ecosia is a dead link.
![image](https://user-images.githubusercontent.com/86303771/148053318-8147bdf5-7d27-4f11-86f8-055f7abd9ce8.png)
Link goes to https://docs.newrelic.com/docs/apm/agents/python-agent/ which is a 404

Real link should probably be https://docs.newrelic.com/docs/apm/agents/python-agent/getting-started/introduction-new-relic-python/

### Doc information (don't delete this section)

* https://docs.newrelic.com/404.html
* **OS**: Pop_OS! 21.10
* **Browser**: Chrome
* **Device**: -

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @Greg-Myers-SB - we're looking into it!

**Comment by urbiz-nr** [comment]
Fixed via #5498.

**Comment by Greg-Myers-SB** [comment]
Thank you @urbiz-nr , hope you and team are having a great start to the year! 🎉
