### ISSUE TITLE
Issue: Set up network syslog monitoring

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#5500]
## How can we make our docs better?
The parameter-specified double-quote in the listening port change example described in the TIP is not closed.

`-syslog="0.0.0.0:514 `

I tried to create a pull request myself, but couldn't because I didn't understand how Markdown in Github interacts with Markdown in the documentation page.

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for letting us know, @qryuu - #5503 will fix this!
