### ISSUE TITLE
[SEO] Include meta description tag

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#551]
### Is your feature request related to a problem? Please describe

The meta header for docs doesn't include the meta description. This is essential for SEO and a GA blocker.

### Describe the solution you'd like

* Include the SEO description in frontmatter of file
* Include description in the header in the correct format to be picked up by search engines
* Automatically import existing meta tags from Drupal site
* Not a requirement but super handy: Enforce length limitation of 160 characters. (Descriptions longer than this commonly get cut off.)

### Describe why this important to you

Search engines and other tools rely heavily on this field. For example, Slack uses it in link previews. Google often shows it in search results when there's no precise keyword match. Swiftype uses it to build search results.

### Example

Compare source of this doc on prod and preview site:

* https://docs.newrelic.com/docs/agents/php-agent/installation/install-php-agent-shared-hosting-service
* https://docs-preview.newrelic.com/docs/agents/php-agent/installation/install-php-agent-shared-hosting-service

The preview site lacks the `description` field ("Info on PHP agent compatibility with shared hosting providers and how to determine if your host supports installing the agent.")

**Comment by austin-schaefer** [comment]
If we don't have this on the dev/OSS sites, we might want to add it at the same time. cc @jaesius @alexronquillo

**Comment by jpvajda** [comment]
removing launchblocker label as not to confuse this with mm13 blockers, it will get done as part of mmf14
