### ISSUE TITLE
Issue: 請求/使用データについてのクエリとアラート

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#5523]
## How can we make our docs better?

There is miss translation in "直近1か月のデータ使用量".

> このクエリは、現在の完全なユーザー数を示します。つまり、今すぐ請求された場合に、その月のデータに対して請求される金額が表示されます。

This sentence is confusing. Since it seems the original page has been updated, could you consider translating again to catch up on the latest doc?

https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts/#gb-exceeds-threshold

### Doc information (don't delete this section)

* https://docs.newrelic.com/jp/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @tanaka-takayoshi, we have a regular translation update every two weeks. This will translation will be updated at that time. Thanks!
