### ISSUE TITLE
AjaxRequest event collection needs to be updated in the data dictionary

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#5526]
Hey docs hero! 

The Browser agent was recently updated so that now we can collect AjaxRequest events outside of Browser interactions.  This is capture in the release notes: https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1211/

So, instead of saying something like, 
An AjaxRequest event is created automatically when an Ajax request occurs during a BrowserInteraction event. The event attributes track geographic and browser info.

we could say something like:
AjaxRequest events occur whenever an ajax request is initiated.  You can configure specific ajax requests to not be collected in the Browser settings page.

**Comment by paperclypse** [comment]
Thanks for letting us know @khickey-newrelic! I'll see if there are any quick changes I can make related to this.
