### ISSUE TITLE
RSS feed link is broken in Japanese page.

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#5541]
## How can we make our docs better?

The link of the RSS feed is broken in Japanese page. It seems it should be linked to same as english page's rss feed.

### Doc information (don't delete this section)

* https://docs.newrelic.com/jp/docs/release-notes/agent-release-notes/java-release-notes/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.110
* **Device**: Unknown

**Comment by shinji-newrelic** [comment]
This issue is not only on Java Agent page. It seems other release note pages have same issue.

**Comment by pizzaz93** [comment]
Where are the RSS values set?

**Comment by shinji-newrelic** [comment]
I don't know where is the source. However there is a RSS link on the right top of the page.
Here is the link url get from the RSS link.
https://docs.newrelic.com/jp/docs/release-notes/agent-release-notes/java-release-notes/feed.xml
