### ISSUE TITLE
Issue: Query and alert on billing/usage data

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#5542]
## How can we make our docs better?

[Month-to-date data usage](https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts/#month-gb) section says:

> This query shows the current full platform user count. In other words, it shows how much you'd be billed for your data for that month if you were billed right now.

However, Month-to-date data usage doesn't mean user count and the NRQL doesn't query user count but ingested data.

Could you fix to the correct explanation?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/usage-queries-alerts/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.110
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for letting us know, @tanaka-takayoshi. #5543 will fix it.
