### ISSUE TITLE
Issue: Kafka monitoring integration

### ISSUE THREAD

**Issue by zarafree** [newrelic/docs-website#5544]
Hello Team,

As per documentation, Kafka integration is compatible with Kafka versions 2.6 or below. We are using 2.7.0 Kafka version in Kubernetes environment and we are going to upgrade to Kafka 3.0. Just wanted to check if new relic integration supports monitoring for both versions i.e 2.7.0 and 3.0. Can you please let us know on this? If it supported then please update documentation as well. Thanks in advance.
Document Link: https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration/

**Comment by urbiz-nr** [comment]
Hi @zarafree - we'll be releasing a new version supporting 3.0 and below in the next couple of days, and we'll update the docs accordingly. Stay tuned! 

Hope this helps!

**Comment by urbiz-nr** [comment]
@zarafree - fyi here's the [PR updating the docs](https://github.com/newrelic/docs-website/pull/5601).
