### ISSUE TITLE
Issue: Issues with Git and CodeStream

### ISSUE THREAD

**Issue by chebeto** [newrelic/docs-website#5558]
I have two very very similar projects. Project B was derived from Project A with some minor changes. The detail is that if I am working on project B, codestream tries to generate the Feedbacks and Merge request towards project A

[Image](https://1drv.ms/u/s!Ah6PhgkOJ-EDg7Rii-Jyalqsc7vcLQ?e=JnBTYM)

Any ideas to fix this problem?

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/codestream/troubleshooting/git-issues/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 96.0
* **Device**: MacBook Pro M1

**Comment by urbiz-nr** [comment]
Hi @chebeto, thanks for reaching out. 

I've checked with the team, and it looks like you probably created this in the wrong GitHub issues org/repo... If possible, retrieve your CodeStream logs (directions here https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/) and email them to support@codestream.com so we can take a look. 

Hope this helps!

**Comment by urbiz-nr** [comment]
Closing this one, will reopen if necessary.
