### ISSUE TITLE
Issue: Linux agent running modes

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#5559]
The link for `data and instrumentation values` is dead.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/linux-agent-running-modes/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.71
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Thanks @GaPeppy. We'll be fixing that with https://github.com/newrelic/docs-website/pull/5571.
