### ISSUE TITLE
Create frontmatter slugs to manage localization states

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#558]
### Issue 

There is a  need to have a frontmatter slug (or something similar)  that can handle the following process used in Drupal to mark content pages for different states of localization.

There are 3 statuses to tag URLs in Drupal for translation:

- Wish Listed: for articles that might be of interest to be translated
- For Quote: articles of interest that we are quoting on
- Completed: articles that have been translated and need maintenance

Each tag then generates a dedicated XML file listing the URLs.

We need similar capabilities in the new Docs Site.

**Comment by jerelmiller** [comment]
> Completed: articles that have been translated and need maintenance

I believe our `translate` frontmatter item satisfies this. The `translate` item will determine which docs we send to Smartling on the interval.

**Comment by jpvajda** [comment]
@jerelmiller we'll have to confirm with Julien if this works for his need.

**Comment by jujuco** [comment]
~Sorry @jpvajda @jerelmiller... long read~
The idea of the 3 statuses is not to _just_ send the content to Smartling. The process ultimately is that the country decides what is translated or not.
The writers as SEM may tell me: this could be of interest to the country. I may run that list by the country and they may decide that it is worth looking into (get a quote) or not. If I am to get a quote, I use the "for quote" status. That way the vendor in the Proxy was able to separate the cost of maintenance and the cost of new content. The country would then decide if the additional cost (new content) fits their budget. If it does, i would give the green light to the vendor and ultimately move the new content to Completed and that new content would just become the normal content from now on.
The more I think about it the more, if we have these statuses, we should send the "For quote" as a separate translation request to Smartling so I can distinguish the necessary maintenance from the possible additional content.

**Comment by jpvajda** [comment]
@jerelmiller It sounds like based on the process defined by @jujuco it would be nice to have these slugs and the generated list of urls in the XML based on the tag type.

**Comment by zstix** [comment]
@jujuco Do you know if we need to include this by GA?

We're worried that this might require more time that we have available before launch.

**Comment by jujuco** [comment]
@zstix I think we can live without it for GA.

**Comment by jpvajda** [comment]
@jujuco thanks for the flexibility, we are targeting this week in our Post GA sustaining block of work, which will occur the week after GA.

**Comment by jpvajda** [comment]
We may try to do this when we take on Localization MT.

**Comment by jmiraNR** [comment]
That'd be totally fine. Thanks.
