### ISSUE TITLE
Print stylesheet has serious issues

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#5584]
## Description

The print stylesheet used to nicely remove left/right navs and fill the whole column nicely. Now, it looks like this:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/55203603/148975915-41d0ed5a-a451-4071-a907-67ae3d733082.png">

## Steps to reproduce

1. Go to a doc
2. Try to print it

## Expected behavior

* Hide top, left, and right navs.
* Use the whole column width.

## Environment

Tested in Firefox, Chrome, and Edge

**Comment by roadlittledawn** [comment]
i'm sure it does. i don't believe we explicitly generate any print style sheets that i'm aware of

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-16
