### ISSUE TITLE
forward-your-logs-using-infrastructure-agent td-agent location

### ISSUE THREAD

**Issue by andrew-lozoya** [newrelic/docs-website#5607]
https://github.com/newrelic/docs-website/blob/main/src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx

Lines 844-846

Location of TD-AGENT differs from whats stated in troubleshooting documentation: https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/#no-fb 

#2 states: If it isn't running go to /var/db/newrelic-infra/newrelic-integrations/logging and run:
./fluent-bit -i systemd -o stdout

However location of the TD-AGENT is as follows: 

/opt/td-agent-bit/bin
./td-agent-bit -i systemd -o stdout

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
