### ISSUE TITLE
Issue: Install containerized private minions (CPMs) -> Synthetics API -> Synthetic REST API -> dead_link (in sidebar navigation)

### ISSUE THREAD

**Issue by irishgordo** [newrelic/docs-website#5609]
Hey there,

Hope all is well!  Really do enjoy these docs! 🚀 🎸 💯 

I did want to reach out however.
I haven't had the chance to dig into this, but we have a dead link for the Synthetics API -> Synthetic REST API link:

Please take a peek at the screenshots 😄 

![Screen Shot 2022-01-12 at 11 47 17 AM](https://user-images.githubusercontent.com/5370752/149211755-5f2236e1-885b-437e-8ff3-4c62139036c6.png)

![Screen Shot 2022-01-12 at 11 50 54 AM](https://user-images.githubusercontent.com/5370752/149211804-ce7d1101-ee43-41a4-ad9c-2102e543b352.png)

![Screen Shot 2022-01-12 at 11 49 20 AM](https://user-images.githubusercontent.com/5370752/149211912-644edcfb-6669-4765-bb09-bf60e4457846.png)

It links to this dead link via the sidebar navigation:
https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/synthetics-api/synthetics-rest-api/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.71
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@irishgordo, it looks like the correct link should be to the APIs section: https://docs.newrelic.com/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api/

If this looks correct, I'll publish it.

**Comment by rhetoric101** [comment]
@irishgordo I am closing this because this was fixed in PR #5617.
