### ISSUE TITLE
Issue: Broken Link

### ISSUE THREAD

**Issue by linbaker** [newrelic/docs-website#5650]
## How can we make our docs better?

Broken link on the line `the [linking process](docs/integrations/amazon-integrations/get-started/connect-aws-new-relic-infrastructure-monitoring)` :

https://github.com/newrelic/docs-website/blame/develop/src/content/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking.mdx#L163

The link seems to be adding the current URL as it takes me to:

https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/docs/integrations/amazon-integrations/get-started/connect-aws-new-relic-infrastructure-monitoring

When it should be directing here:

https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/connect-aws-new-relic-infrastructure-monitoring/

Thank you!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.71
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Thanks @linbaker, we'll fix that. 

Fixed link in https://github.com/newrelic/docs-website/pull/5654.
