### ISSUE TITLE
Remove `tags` from all frontmatter

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#5652]
Many docs on the site include this `tags` section in their frontmatter:

```
tags:
  - Integrations
  - Kubernetes integration
  - Link apps and services
```

These tags used to drive Swiftype, but when we remove related resources they'll be vestigial. I often see them confuse contributors who think they're essential for SEO or search.

We should remove them programmatically.

**Comment by roadlittledawn** [comment]
One caveat: if tags are removed from these pages (and thus swiftype index records), they will likely show up much less frequently in other sites that use related resources (like developer, IO)
