### ISSUE TITLE
Issue: New Relic One pricing model details

### ISSUE THREAD

**Issue by anaesanto** [newrelic/docs-website#5659]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/new-relic-one-pricing-billing
* **OS**: Linux x86_64
* **Browser**: Chrome 96.0.4664.110
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @anaesanto! Could you let us know what you found challenging in that doc? Thanks!

**Comment by anaesanto** [comment]
Hey, my trully problem is abou a pricing information. I need to know how much is a full member access. We already have a account in New relic with a lot of users, but I can't find the price

**Comment by x8a** [comment]
I understand! Let me find you the information and get back to you 🙌🏻.

**Comment by anaesanto** [comment]
Thank you so much

**Comment by zuluecho9** [comment]
@anaesanto If you have New Relic Standard edition, that is documented here: https://newrelic.com/pricing. If you have a Pro or Enterprise edition subscription, that information should be in your billing UI (it's possible you don't have permissions to see that UI in which case I'd recommend talking to whoever in your company is the main point of contact for New Relic, or to your New Relic account rep). Hope that helps.

**Comment by anaesanto** [comment]
Thanks, thats all
