### ISSUE TITLE
Issue: Install the .NET agent on Azure Web Apps

### ISSUE THREAD

**Issue by hroseross** [newrelic/docs-website#5662]
## How can we make our docs better?

The link in the last line of this doc 404s:
Refer to additional Azure troubleshooting procedures as applicable.

It also does not work in the navigation.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 96.0.4664.93
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@hroseross Thanks for reporting this! I'll track it down.
