### ISSUE TITLE
Issue: Diagnostics CLI licensing and security

### ISSUE THREAD

**Issue by jeffchiudev** [newrelic/docs-website#5663]
## How can we make our docs better?

The *Data Storage* section says that attachments are sent to and stored on Zendesk, which as far as I know is not the case anymore.

Also, in the left handed navigation pane, the `diagnostics release notes` link appears to be broken.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/diagnostics-cli-nrdiag/diagnostics-cli-licensing-security
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.71
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@jeffchiudev  Thanks for reporting these two items! I'll fix.
