### ISSUE TITLE
Issue: Filter New Relic One dashboards by facets

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#5674]
## How can we make our docs better?

It does not mention that FACET will not work with TIMESLICE. 

Its unclear where the FACET clause should be placed in the query. If it doesnt matter it should at least be consistent. 

A more real-world example like how to reuse the same dashboard for multiple apps (like an app that is deployed in different environments/geo regions with names like MyApp_PROD_US, MyApp_PROD_EU, etc...)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/filter-new-relic-one-dashboards-facets/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
