### ISSUE TITLE
[Data Dictionary] Confirm the approach for an upgrade from alpine `3.11.3` to a FEDRAMP approve OS version by `3/18/21`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#5679]
### Acceptance Criteria

- please review this ticket on GHE: `nr1-dev-experience/data-dictionary/issues/41`for the AC
- this effort is timeboxed to confirm if moving to a new OS version is possible, or if it's better to just bump the alpine version

**Comment by rudouglas** [comment]
It looks like its relatively straight forward to alter the Dockerfile to use either Debian or Ubuntu, i've prepared a PR with the changes needed. The only other consideration we need to make is whether to use Debian or Ubuntu. Ubuntu is based on Debian so the both use the `apt` package manager and `.DEB` files. Below are some considerations on both:

## Debian
 - Stable releases every 2 years
    - 5 years support (3 by Debian Security, 2 by Volunteers)
 - Considered more stable
 - Considered more stale (often runs older versions of software)
 - Supports 32 bit and 64 and lots more `N/A`
 - Focuses primarily on FOSS (free and open source software) so proprietary drivers often not included `N/A`
 - Community project
    - Security updates normally slower
 - Image size:
     - Bullseye `54.9 MB` - (Debian 11)
     - Minimal `31.4 MB` - _bullseye-slim_ 

## Ubuntu
  - Stable releases every 2 years
    - 5 years official support
  - (Personal Package Archive) PPA (installing newer software or getting the latest software version is easier)
  - Supports 64-bit x86 and ARM platforms `N/A`
  - Backed by corporate
     - Security Updates normally day-0
 - Image size:
     - Minimal `29MB` - [ubuntu:18.04](https://ubuntu.com/blog/minimal-ubuntu-released)
     - Ubuntu 20.04 `188MB`
### Slimming Down further

We can use the flag `--no-install-recommends` to avoid installing the recommended and suggested packages, e.g.

`RUN apt-get update && apt-get install --no-install-recommends --yes python3`

**Comment by aswanson-nr** [comment]
Moving back to in progress while comments are addressed

**Comment by rudouglas** [comment]
Here is the PR for the changes:

https://source.datanerd.us/nr1-dev-experience/data-dictionary/pull/42

There is also a `build` Dockerfile that uses a strange elixir image, I think Zack mentioned this yesterday but wondering if we need to alter this too?

https://source.datanerd.us/nr1-dev-experience/data-dictionary/blob/master/build/Dockerfile
