### ISSUE TITLE
We hit an error while loading this page

### ISSUE THREAD

**Issue by kctrud** [newrelic/docs-website#5680]
## How can we make our docs better?

When try login get:
We hit an error while loading this page
To get back to your data, try the following

### Doc information (don't delete this section)

* https://one.newrelic.com/launcher/nr1-core.explorer?state=4d67c8e5-f01a-bbc1-a4f7-ec725144150d
* **OS**: Windows 10
* **Browser**: Chrome 97.0.4692.71 / Edge
* **Device**: PC

**Comment by x8a** [comment]
Hey, @kctrud! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
