### ISSUE TITLE
Issue: Browser Pro agent features

### ISSUE THREAD

**Issue by dwjohnston** [newrelic/docs-website#5681]
## How can we make our docs better?

Broken link on this page: 

https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/intro-to-browser-pro-features/

The link 'Browser pro feature docs' (https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features) appears to redirect to the same page. Doesn't take me to comparison table. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/intro-to-browser-pro-features/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for bringing this to our attention, @dwjohnston! I'll fix the link right away.

**Comment by x8a** [comment]
I fixed it with PR #5685.
