### ISSUE TITLE
How I change or remove  owner, if current owner is not available  

### ISSUE THREAD

**Issue by VarunNykaa** [newrelic/docs-website#5689]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/404.html
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @VarunNykaa! Could you let us know the doc where you found a problem? Thanks!

**Comment by VarunNykaa** [comment]
Hey, 
Need to know, How i remove the owner if current owner is not available, basically  need to change the ownership for newrelic account , can you help me on that ?

**Comment by x8a** [comment]
You can have a look at the [User management UI and common tasks](https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-ui-and-tasks/) doc to see whether you can find an answer there.

If that doesn't help, I can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.

I hope this helps you!

**Comment by VarunNykaa** [comment]
thanks ,
