### ISSUE TITLE
[Translation] Investigate and fix deserialization issues

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#5718]
## Summary

Based on findings and common MDX formatting issues from #5660 MT JP PR, there seems to be some systemic issue with some deserialization.

While this may not be as big an issue on normal operations, when adding new languages in bulk, this is very tedious and takes good amount of time to fix.

This is particularly hard to troubleshoot because while there seems to be some pattern, it doesn't always happen. And it's not clear if it's our custom handlers or some issue with the packages we use. 

## Acceptance criteria
- [ ] Identify the most common issues
- [ ] Fix rogue link issue wrapping / creating garbage elements
- [ ] Fix tbody formatting issue
- [ ] Fix dangling open tags for components/html elems

## Helpful links
- https://github.com/newrelic/docs-website/pull/5660
- [Issue filed for weird formatting that successfully built](https://github.com/newrelic/docs-website/issues/5892)

**Comment by roadlittledawn** [comment]
in this file:
```
- src/i18n/content/jp/docs/mobile-monitoring/new-relic-mobile-ios/configuration/upload-dsyms-bitcode-apps.mdx
```

The `~` char was not in a JSX expression like it was in english file. not 100% sure how to account for that, but that was a hard one to find

**Comment by jpvajda** [comment]
@roadlittledawn @LizBaker though this could be closed out as it was an issue with smartling, does that sound right to you?
