### ISSUE TITLE
Issue: Duplicate account created with same email and unable to login

### ISSUE THREAD

**Issue by wsi-ashwinis** [newrelic/docs-website#5719]

**Comment by paperclypse** [comment]
Hi @wsi-ashwinis! I'm sorry you're having trouble logging in. This doc may provide some help: https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems

If it doesn't solve your issue, I'd recommend reaching out to support (https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings/) or posting on our community forums (https://discuss.newrelic.com)
