### ISSUE TITLE
[Private docs] Create a basic template for docs content

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#572]
## Description

In the public docs site, we have templates for several content types. Some of these templates include the right rail, while others have specific formatting on the document.

For the private docs site, we don't need anything fancy, except the ability to render the doc. We do not need a right-rail or fancy formatting. Let's create a basic template that allows us to show the MDX document on the page.

NOTE: While we may not consume it in the basic template, a content contributor should be able to define all supported frontmatter for the doc. 

## Acceptance criteria
* [ ] A basic template is created and used for all MDX pages
* [ ] Use the title from frontmatter to render the page title
* [ ] Use the `MDXContainer` to wrap MDX content

**Comment by jerelmiller** [comment]
@austin-schaefer can you confirm that we only need a basic doc template? Not sure if the private repo will be used for release notes or landing pages or any other types of content that have specific doc layouts.

**Comment by austin-schaefer** [comment]
@jerelmiller : Certainly for this MMF, I don't think we need anything beyond a basic docs template.
