### ISSUE TITLE
Issue: Security policy

### ISSUE THREAD

**Issue by pberryman** [newrelic/docs-website#5735]
## How can we make our docs better?

Link in Section 4.4 to the Security Guide is incorrect. It needs to be changed to: https://docs.newrelic.com/docs/licenses/license-information/referenced-policies/security-guide 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/licenses/license-information/referenced-policies/security-policy/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for reporting this! I fixed it in PR #5737.
