### ISSUE TITLE
Unpredictable "What's new" ID creation process

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#5745]
## Description

We have made commitments to product marketing managers that their "What's new" posts will appear in the docs and in the UI in a general time window. While we don't have a very precise way to time when posts appear on the docs site or in the UI, we'd like some assurance that the "What's new" IDs are always created when we merge to main.

Today, I merged to main (`https://github.com/newrelic/docs-website/pull/5740`) and was expecting the Syslog "What's new" post (`https://github.com/newrelic/docs-website/pull/5673`) to appear in the UI somewhat after it appeared in the docs. Alas, the process to create the ID for the post was never triggered in the merge to main, for some reason. So, the post made it to our docs site, but it never made it to the UI.

Interestingly, the subsequent merge to main did kick off this ID creation commit, but this meant that there was a delay of many hours between when the post appeared in docs and when it showed up in the UI.

## Expected behavior

I would expect all merges to main to trigger an automatic process that makes a commit with new IDs for "What's new" posts.

# Eng

## Summary

Currently, when a PR (via a `daily-release/*` branch) is opened to `main`, the [`
generates in-product anncouncements`](https://github.com/newrelic/docs-website/actions/workflows/update-whats-new-ids.yml) workflow runs. It looks for new whats-new files (compares file paths in `src/data/whats-new-ids.json` with files in `src/content/whats-new`) and if it finds any, it updates that JSON file and pushes that commit to `develop`.

### Short term solution
In order to get the data for the new whats-new post into that same release PR, the submitter would want to merge `develop` into the `daily-release/*` branch before merging it into `main` (which will trigger the checks to run again including the GC build preview).

### Potential long term solutions

Not 100% yet sure what best way to do this is that doesn't require any additional attention from a PR submitter.

## Acceptance criteria
- [ ]

**Comment by LizBaker** [comment]
Just some more context on this: the whats new action did indeed get kicked off the first time but it didn't get committed into develop before the merge. it showed up in the second release but with a time stamp of around the time of the first one. 

I'm wondering if making this a required action on the release PR would help ensure it gets committed to develop before the merge. It does fail on occasion when other commits come into develop at the same time, so this could be annoying and require close/reopen of release PRs 🤷‍♀️
