### ISSUE TITLE
[Private docs] Update the README with documentation on how to contribute and use the private docs site

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#575]
## Description

To ensure success on our private docs site, we want to ensure we have detailed instructions for setting up and editing docs in the private docs repo. We can use the README to document needed instructions for the site.

## Acceptance criteria

* [ ] README is updated with detailed instructions for running the site, contributing, etc.

**Comment by caylahamann** [comment]
https://github.com/newrelic/docs-website/pull/209
