### ISSUE TITLE
Issue: OpenTelemetry quick start usage of abbreviation for OpenTelemetry OTel or OTLP

### ISSUE THREAD

**Issue by adiosspandit** [newrelic/docs-website#5765]
## How can we make our docs better?

* I have been reviewing the OpenTelemetry documentation and New Relic documentation.
* OpenTelemetry docs use the term OTel as an abbreviation for components like Libraries and Collectors.
https://opentelemetry.io/docs/

* New Relic documentation uses the convention OTLP not sure if both mean the same thing or will it make sense to switch to using the term OTel.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 94.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@adiosspandit, I haven't heard back from you, so I'll consider this issue resolved. If you still have questions about it, you can reopen it!

**Comment by adiosspandit** [comment]
Thanks @rhetoric101 for looking into this.
