### ISSUE TITLE
Issue: APM not showing any apps

### ISSUE THREAD

**Issue by ShahidRazaMirza** [newrelic/docs-website#5766]
I installed relic agenta and other dependent software on my server and  when i m going to newrelic account its showing my host and other details like CPU Usage, Drives status and all, as shown in screennshot:
![image](https://user-images.githubusercontent.com/45932921/150719354-25964fc8-f001-4733-a342-c3a0b540a1d1.png)
But when going to APM, its still shows **Start monitoring applications and services in minutes** even i take care of all necessory steps, its not showing my data under APM
![image](https://user-images.githubusercontent.com/45932921/150719024-1c42f288-6dc9-4f0b-abae-464d6e8613eb.png)

Is there anything which i am missing?

**Comment by urbiz-nr** [comment]
Hi @ShahidRazaMirza - thanks for reaching out! This is the public docs repo, and you seem to have configuration issues. I recommend you contact support or ask other users and Relics in the Explorers Hub. Find how to do this [here](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal).
