### ISSUE TITLE
Issue: Manage alert notification channels

### ISSUE THREAD

**Issue by ankit-rsystem** [newrelic/docs-website#5769]
I am trying to update alert policies from newrelic alert-policies, but when I choose an notification channel to update then there isn't any option to click and update that policy. 

Please check in below reference image:
![image](https://user-images.githubusercontent.com/96411587/150772236-a6e3ab66-957b-4417-a6af-8ff12b3bcab3.png)

**Comment by ankit-rsystem** [comment]
Hi Team, 

I have tried to add a policy from notification channel also but I faced the same issue from there as well: 

![image](https://user-images.githubusercontent.com/96411587/150772852-eea7e830-5074-49e0-b0dc-0a225dd78b2d.png)


![image](https://user-images.githubusercontent.com/96411587/150772928-7cd55574-77a6-4718-b3a9-d618a8d4db2d.png)


After selecting policy I have hit enter but it doesn't reload that page to update any thing. 

I am expecting a click option in drop down to update my channel/policy.

**Comment by urbiz-nr** [comment]
Hi @ankit-rsystem - thanks for reaching out! This is the public docs repo, and you seem to have configuration issues. I recommend you contact support or ask other users and Relics in the Explorers Hub. Find how to do this [here](https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/). Hope this helps!
