### ISSUE TITLE
Bug: putting a '%' in docs site search breaks site

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#5782]
## Description

On docs site, including a '%' character in the search bar and hitting Enter breaks site.

**Comment by roadlittledawn** [comment]
nothing obvious popped out at me. @nr-kkenney pointed out that this does not happen on developer or opensource, so perhaps something specific to docs hosing up

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-19
