### ISSUE TITLE
Issue: Tutorial: Monitor Redis running on Kubernetes

### ISSUE THREAD

**Issue by ghnethippo** [newrelic/docs-website#5785]
## How can we make our docs better?

* Is something confusing?
Yes. I got a question about the default namespace in the example because the default k8s integration uses 'newrelic' for the namespace by default. 
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)
I need additional troubleshooting steps to validate works after running kubectl by case. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/link-apps-services/tutorial-monitor-redis-running-kubernetes/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hi @ghnethippo - thanks for reaching out! We're currently working on a big revamp of k8 docs, and this issue is solved there. You can track the updates [here](https://github.com/newrelic/docs-website/pull/5715). It will go live in the next few days. Hope this helps!

**Comment by ghnethippo** [comment]
@urbiz-nr super thanks.
