### ISSUE TITLE
[Docs Site] Investigate issue with mailto links

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#5789]
## Description

It looks like the `mailto` links in the Docs site (potentially other sites too), are not working. Gatsby is treating them as internal links so they don't connect the user to their mail.

```
[personaldatarequests@newrelic.com](mailto:personaldatarequests@newrelic.com))
```
 - https://docs.newrelic.com/docs/gateway-api-import-data-other-observability-platforms/
 - https://docs.newrelic.com/docs/accounts/original-accounts-billing/product-pricing/product-based-pricing/
 - https://docs.newrelic.com/docs/mlops/integrations/comet-mlops-integration
 - https://docs.newrelic.com/docs/security/security-privacy/data-privacy/new-relic-personal-data-requests

The content team have said these were originally working, but not sure when they broke.

This could be an issue for things like billing etc where the user needs to get in touch for important account issues. There are other ways for them to do this, but broken links are never good anyway.

Initial thoughts are that this is not accounted for in serialization/deserialization of mdx.

### Options
 - Convert the links to our `<ExternalLink />` component
 - OR
 - Alter the serialization so it recognises `mailto` links and doesn't convert them to Internal links

## Acceptance Criteria

 - [ ] Investigate why Gatsby is converting mailto links to internal links
 - [ ] Decide on the best option and create a new ticket to complete the work

**Comment by pizzaz93** [comment]
I was able to generate an email from the `mailto` links on https://docs.newrelic.com/docs/security/security-privacy/data-privacy/new-relic-personal-data-requests/#submit-requests and https://docs.newrelic.com/docs/data-apis/ingest-apis/gateway-api-import-data-other-observability-platforms.
