### ISSUE TITLE
Issue: Oracle Database monitoring integration

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#5809]
In the Custom Query example; the trailing semi-colon on the SQL statement causes the integration to crash.  Please remove the trailing semi-colon in the example and add a note that adding a semi-colon to any custom sql statement is bad juju.

```
      CUSTOM_METRICS_QUERY: >-
        SELECT
          'physical_reads' AS "metric_name",
          'gauge' AS "metric_type",
          SUM(PHYRDS) AS "metric_value",
          INST_ID AS "instanceID"
        FROM gv$filestat
        GROUP BY INST_ID;
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for letting us know, @GaPeppy - we're fixing this in #5814. Feel free to comment on that PR. Cheers!
