### ISSUE TITLE
Issue: Use SPA API

### ISSUE THREAD

**Issue by oltodo** [newrelic/docs-website#5813]
The link `Browser agent and SPA API` in the page [Use SPA API](https://docs.newrelic.com/docs/browser/single-page-app-monitoring/use-spa-data/use-spa-api) sends to a 404 page.

**Comment by bradleycamacho** [comment]
Thanks for reporting this @oltodo! I have a fix in #5816, which should go live sometime today.

**Comment by oltodo** [comment]
Thanks @bradleycamacho!
