### ISSUE TITLE
[Docs: Translation Scaling] Update workflows to discard failed file data

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#5820]
## Summary

Currently we queue up files for translations for each PR and submit for human and machine translation on a schedule. There are some files that Smartling's engine doesn't quite handle well / mangles it up causing our deserializers to fail. When that happens, we record what file failed and we move on to PR with the files that successfully deserialized. We keep the records for the failed files (and their jobs) in the database with a status of `ERRORED`.

After mulling this over and knowing the Smartling engine thing may not be fixable, it makes more sense to just discard those errored files from the database. 

Advantages to this approach:
- the file paths in the database may eventually become stale (when file paths change due to moving/renaming)
- there's little cost in uploading the same files in subsequent runs (if queued up due to being included in a PR) and just letting them fail again and discarding them OR if the issue is fixed letting them successfully complete.
- reduces need for eng to manually update database / create utility script to run to update database so files can be queued up and submitted again
- simplifies workflow scripts a bit to not have to account for old records of errored files sitting around

## Acceptance criteria
- [x] Confirm that with this work we can close #5722 
- [x] Generate a list of files (full file path and file name) that are currently in `ERRORED` state
- [x] Remove all relevant records in database for errored files
- [x] Update the workflow `check-translations-and-deserialize` > `check-job-progress.js` script to discard errored files and not keep them around in the database
- [x] When the `check-translations-and-deserialize` workflow runs and some files fail, I can easily see a list of the files (full file path) that failed in the github workflow console

## Helpful links

**Comment by rudouglas** [comment]
<details>
<summary>List of Errored files in Prod Database</summary>

| id | path | status |
|------|--------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------|
| 4147 | "src/content/docs/apm/agents/net-agent/other-features/async-support-net.mdx"                                                                                 | "ERRORED" |
| 4084 | "src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/link-your-applications-kubernetes.mdx"                                      | "ERRORED" |
| 4085 | "src/content/docs/kubernetes-pixie/kubernetes-integration/advanced-configuration/monitor-services/monitor-services-running-kubernetes.mdx"                   | "ERRORED" |
| 4062 | "src/content/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/infrastructure-alerts-add-edit-or-view-host-alert-information.mdx" | "ERRORED" |
| 4089 | "src/content/docs/kubernetes-pixie/kubernetes-integration/installation/install-fargate-integration.mdx"                                                      | "ERRORED" |
| 3777 | "src/content/docs/apm/agents/python-agent/configuration/python-agent-configuration.mdx"                                                                      | "ERRORED" |
| 4098 | "src/content/docs/distributed-tracing/enable-configure/language-agents-enable-distributed-tracing.mdx"                                                       | "ERRORED" |
| 4069 | "src/content/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/alerts-conditions-api-field-names.mdx"                        | "ERRORED" |
| 4133 | "src/content/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-kinesis-data-streams-monitoring-integration.mdx"                              | "ERRORED" |
| 4146 | "src/content/docs/infrastructure/infrastructure-integrations/get-started/use-integration-data-new-relic-dashboards.mdx"                                      | "ERRORED" |
| 3812 | "src/content/docs/infrastructure/host-integrations/host-integrations-list/nagios-monitoring-integration.mdx"                                                 | "ERRORED" |
| 3725 | "src/content/docs/network-performance-monitoring/setup-performance-monitoring/network-syslog-monitoring.mdx"                                                 | "ERRORED" |
| 3854 | "src/content/docs/accounts/accounts/saml-single-sign/saml-service-providers.mdx"                                                                             | "ERRORED" |
| 3808 | "src/content/docs/infrastructure/host-integrations/host-integrations-list/hashicorp-consul-monitoring-integration.mdx"                                       | "ERRORED" |
| 3619 | "src/content/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent.mdx"                                                                        | "ERRORED" |
| 3764 | "src/content/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-troubleshooting.mdx"                                      | "ERRORED" |
| 3669 | "src/content/docs/network-performance-monitoring/advanced/snmp-profiles.mdx"                                                                                 | "ERRORED" |
| 3855 | "src/content/docs/accounts/original-accounts-billing/original-data-retention/event-data-retention-original-pricing-plan.mdx"                                 | "ERRORED" |
| 3831 | "src/content/docs/using-new-relic/welcome-new-relic/optimize-your-cloud-native-environment/establish-objectives-baselines-define-team-slos.mdx"              | "ERRORED" |
| 3622 | "src/content/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms.mdx"                                          | "ERRORED" |
| 3701 | "src/content/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/kubernetes-cluster-explorer.mdx"                                               | "ERRORED" |
| 3603 | "src/content/docs/network-performance-monitoring/advanced/advanced-config.mdx"                                                                               | "ERRORED" |
| 3954 | "src/content/docs/new-relic-partnerships/partner-integration-guide/partner-account-maintenance/partnership-accounts-users-subscriptions.mdx"                 | "ERRORED" |
| 3881 | "src/content/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring.mdx"                                               | "ERRORED" |
| 3861 | "src/content/docs/accounts/original-accounts-billing/product-pricing/product-based-pricing.mdx"                                                              | "ERRORED" |
| 3893 | "src/content/docs/infrastructure/host-integrations/host-integrations-list/vmware-vsphere-monitoring-integration.mdx"                                         | "ERRORED" |
| 3833 | "src/content/docs/logs/logs-context/java-configure-logs-context-all.mdx"                                                                                     | "ERRORED" |
| 3649 | "src/content/docs/data-apis/manage-data/manage-data-coming-new-relic.mdx"                                                                                    | "ERRORED" |
| 3653 | "src/content/docs/network-performance-monitoring/monitoring-network-data/visualize-network-data.mdx"                                                         | "ERRORED" |
| 3969 | "src/content/docs/infrastructure/amazon-integrations/troubleshooting/aws-service-specific-api-rate-limiting.mdx"                                             | "ERRORED" |
| 3880 | "src/content/docs/network-performance-monitoring/setup-performance-monitoring/aws-vpc-flow-monitoring.mdx"                                                   | "ERRORED" |
| 3945 | "src/content/docs/mobile-monitoring/mobile-monitoring-ui/crashes/crash-analysis-group-filter-your-crashes.mdx"                                               | "ERRORED" |
| 3920 | "src/content/docs/browser/browser-monitoring/troubleshooting/troubleshoot-your-browser-monitoring-installation.mdx"                                          | "ERRORED" |
| 3805 | "src/content/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch-monitoring-integration.mdx"                                          | "ERRORED" |
| 3753 | "src/content/docs/logs/forward-logs/fluent-bit-plugin-log-forwarding.mdx"                                                                                    | "ERRORED" |
| 3891 | "src/content/docs/codestream/start-here/install-codestream.mdx"                                                                                              | "ERRORED" |
| 4015 | "src/content/docs/apm/new-relic-apm/maintenance/remove-applications-new-relic.mdx"                                                                           | "ERRORED" |
| 3998 | "src/content/docs/kubernetes-pixie/kubernetes-integration/link-your-applications/link-your-applications-kubernetes.mdx"                                      | "ERRORED" |
| 4032 | "src/content/docs/distributed-tracing/troubleshooting/missing-trace-data.mdx"                                                                                | "ERRORED" |

</details>
