### ISSUE TITLE
Issue: iOS manual installation

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#5825]
## How can we make our docs better?

The link to iOS SDK release page should be updated.
It is link to [this](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/ios-release-notes) page.
But it should be [this link](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/xcframework-release-notes/) today.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/installation/ios-manual-installation
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.71
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@shinji-newrelic trying to understand this more. Does this mean that all ios-release-notes links should point to the xc-framework release notes?

**Comment by shinji-newrelic** [comment]
Yes.

As you can see in this [page](https://docs.newrelic.com/docs/release-notes/mobile-release-notes/ios-release-notes/ios-agent-700), iOS agent was deprecated and "XCFramework Agent" shall be used for iOS integration.

So, I think download link also should point to xc-framework release notes.

**Comment by zuluecho9** [comment]
fixed in https://github.com/newrelic/docs-website/pull/7334
