### ISSUE TITLE
Issue: iOS agent configuration and feature flags

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#5831]
## How can we make our docs better?
broken link in [here](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/ios-agent-configuration-feature-flags/#dt)

In fact, the link of "How New Relic distributed tracing works" is broken. It is actually "https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/ios-agent-configuration-feature-flags/docs/understand-dependencies/distributed-tracing/get-started/how-new-relic-distributed-tracing-works/#no-sampling" today. 
But it seems correct url is "https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/get-started/how-new-relic-distributed-tracing-works/#no-sampling"

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/ios-agent-configuration-feature-flags/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.71
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @shinji-newrelic. #5836 will fix it.
