### ISSUE TITLE
[i18n] Fix check job error in most recent run

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#5842]
## Summary

The most recent (and only run after the initial JP MT add to the site) [workflow run to check job statuses / download](https://github.com/newrelic/docs-website/runs/4965799308?check_suite_focus=true) failed with this error:

```
[*]1 batches ready to be deserialized
[*]batchUids: 2u7jdqthl97n
Created 1 batches of files.
using cached access token
Downloaded 1 zips
Unzipped 16 total files.
[!]Unable to check job status
TypeError: Cannot read properties of undefined (reading 'id')
    at /home/runner/work/docs-website/docs-website/scripts/actions/check-job-progress.js:170:45
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async updateTranslationRecords (/home/runner/work/docs-website/docs-website/scripts/actions/check-job-progress.js:161:3)
    at async main (/home/runner/work/docs-website/docs-website/scripts/actions/check-job-progress.js:244:5)
Error: Process completed with exit code 1.
```

At quick glance, this line looks like a possible culprit
https://github.com/newrelic/docs-website/blob/4892344bd0d26d949fca22ad4e279af5254e6c32/scripts/actions/check-job-progress.js#L170

## Acceptance criteria
- [x] Fix error so workflow run successfully to PR files
- [ ] Re-run workflow manually 

## Helpful links

**Comment by nr-kkenney** [comment]
hmm. i did update that because i know the previous shape was wrong, but looks like it might still be wrong 🙈 

so the shape could still be wrong, or maybe the query arguments aren't correct and the update calls returns 0 records so we can't do records[0].

assuming we don't have a quick answer that we can just see, we can run the whole process locally and try to debug it that way.

finally, even though it errored, the workflow should be good to run again after we commit the fix. since we haven't PR'd. anything, or deleted any DB records, another run should succeed and end in the state we expect.

**Comment by roadlittledawn** [comment]
that `records` const seems to be an empty array from `updateTranslations()`, so maybe it's just not returning anything when updating the DB?

**Comment by roadlittledawn** [comment]
yep just ran locally and what we get back from `updateTranslations()` is: 
```
[ 0, [] ]
```

so when we destructure via `const [_, translations] = await Models.Translation.update....` we get that empty array, so there's no `records[0].id`

**Comment by roadlittledawn** [comment]
just changed that `console.log` on line 170 (snippet in description) to not rely on anything returned from that `updateTranslation()` and script finishes but database is not updated, so would seem the arguments aren't quite right.

**Comment by roadlittledawn** [comment]
i also just noticed a `/.mdx` in the slug when i output `slug` instead of `records[0].id`:
```
src/content/docs/accounts/accounts/account-maintenance/change-passwords-user-preferences/.mdx marked as COMPLETED
```
