### ISSUE TITLE
Migrating Old Dashboards

### ISSUE THREAD

**Issue by jake-codes** [newrelic/docs-website#5858]
This doc page is where customers are sent when they try and import dashboards, including our official QuickStart dashboards. However, there is not any explanation as to how a user might go about migrating these dashboards.

For a better customer experience, the dashboards team should link to a relevant section of the docs that addresses this and the docs should include a section on how to migrate existing dashboards. If I have missed this, please let me know and I will speak to the dashboard team about updating the link.

Thank you

<img width="393" alt="Screen Shot 2022-01-28 at 6 44 03 AM" src="https://user-images.githubusercontent.com/53268450/151568431-6091a8f6-a1de-4d09-87cf-a2b2cc45292d.png">

<img width="469" alt="Screen Shot 2022-01-28 at 6 54 32 AM" src="https://user-images.githubusercontent.com/53268450/151568649-dccfbff6-32cf-4586-88f9-c8a9d7c25b7f.png">

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/create-widgets-dashboards-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Hi @jake-codes - thanks for reaching out! Is this https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-import-dashboards-using-api the doc you're looking for?

**Comment by urbiz-nr** [comment]
Closing. Will reopen if necessary.
