### ISSUE TITLE
Review nav instruction set

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#587]
## Description

Now that we have all content migrated (#577), we need to review the instruction set for our nav and ensure it matches what we expect. We still show quite a few warnings during a migration about nodes that are not found. Let's go over the instruction set with a fine tooth comb and update/remove any instructions to get rid of those warnings.

### Specific Nav issues 

- Remove licenses  from left nav
- Create integration should be under integrations
- NR1 > use NR1 > Get started (should be first, a la Anna)
- OpenTelemetry first in docs/integrations

**Comment by jpvajda** [comment]
@austin-schaefer if you have other navigation corrections you can add to this issue.
