### ISSUE TITLE
[Docs: Translation Scaling] Update translation workflows to support adding Korean

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#5877]
## Summary

Update translation workflows to support translation to Korean. When updating workflows, we want to make it as easy as possible to add a new language.

## Open questions
- Do we have a ready-to-use script to bulk add files to queue for a given language?
  - Yeah, kinda. We may need to adjust the CLI option to account for human translation as well
- Are we using the same projects for human and machine translation as `jp`?
  - Yep! And both are setup for `ko-KR`

## Optimzations / considerations
- Reduce all the places we need to add a language / locale code and update all parts of code to reference what it needs from one central file ( perhaps [`src/scripts/actions/utils/constants.js`](https://github.com/newrelic/docs-website/blob/develop/scripts/actions/utils/constants.js) )
- Determine what code to use for Korean frontmatter
  - We somewhat awkwardly use `jp` in frontmatter to denote japanese, when really that is the country code and `ja` is the language code

## Scripts that use language / country codes
- https://github.com/newrelic/docs-website/blob/e66edd79d9a917c7a53b483329dff896a1b79eed/scripts/actions/fetch-and-deserialize.js#L14-L16
- https://github.com/newrelic/docs-website/blob/e66edd79d9a917c7a53b483329dff896a1b79eed/scripts/actions/utils/vendor-request.js#L16-L19
- https://github.com/newrelic/docs-website/blob/8f9906afe02b7e64b246d7b1a562549e427c5f86/scripts/actions/utils/constants.js#L1-L3

Not really using locale like the instances above, but also needs to be updated for supporting multiple locales:
- https://github.com/newrelic/docs-website/blob/550efccf7b1ec8eb2b38f30f607fe3dc13cdfceb/scripts/actions/check-job-progress.js#L158-L164

## Acceptance criteria
- [x] Create a feature branch for all Korean work
- [X] Determine what two letter code we'll use for Korean: Code is `kr`
- [x] Update workflow code so references to language / locale code come from one place (instead of hard coded anywhere)
- [x] Update postgres database table `locales` to add Korean
- [x] When done the workflows can support human translating Korean

**Comment by rudouglas** [comment]
https://github.com/newrelic/docs-website/tree/feature/korean-translations
