### ISSUE TITLE
Issue: Write synthetic API tests

### ISSUE THREAD

**Issue by hroseross** [newrelic/docs-website#5883]
## How can we make our docs better?

Customer request to add an example of a test script to this page. More details in this thread in the community: https://discuss.newrelic.com/t/example-of-scripted-api-that-uses-value-from-one-response-in-subsequent-http-query/174596/4

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
I attempted to sift through that forum post but I don't know enough about writing Synthetics scripts so added the 'docs-issues-migrate' label.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
