### ISSUE TITLE
Wrong dates on Browser Release Notes page

### ISSUE THREAD

**Issue by retishp** [newrelic/docs-website#5884]
Please see screenshot
![image](https://user-images.githubusercontent.com/7780777/151886659-5a1d5b14-3a98-4e12-b032-359656b2319a.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1215
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thank you much @retishp! We are fixing that in https://github.com/newrelic/docs-website/pull/5886.
