### ISSUE TITLE
Issue: Formatting corruption by the translation system

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#5892]
## How can we make our docs better?
On a Japanese page generated by machine translation
The Format below the following TIP has been corrupted.

It is probably because the translation system does not handle Markdown and formatting symbols correctly.

TIP
For assistance with user maintenance questions, consult the Oracle documentation or contact your system or database administrator.

* https://docs.newrelic.com/jp/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration/
* **OS**: Windows 10
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

## Related issues / PRs
https://github.com/newrelic/docs-website/issues/5718

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @qryuu - I'll let the engineers know!

**Comment by jmiraNR** [comment]
@roadlittledawn Hi. There seems to be a problem on this page. It is not just the TIP box but there is an issue starting with the bullet. The files are wildly different in the repo. Is there a way to know which translation job this file was last processed? Thx

**Comment by roadlittledawn** [comment]
oh wait. this doc looks similar to another dimensional metrics doc that deserialized without a `table` element and the text from it output willy nilly. 

@jmiraNR we may want to exclude this from MT until we can figure out why these bork so bad.

https://github.com/newrelic/docs-website/blob/b45979677a5df92ae71f541201f52ab5527e28ab/src/i18n/content/jp/docs/infrastructure/host-integrations/host-integrations-list/oracle-database-monitoring-integration.mdx#L1

**Comment by jmiraNR** [comment]
How many are there?

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
