### ISSUE TITLE
Phrasing issue: Introduction to alerts and applied intelligence

### ISSUE THREAD

**Issue by ahaberkoExt** [newrelic/docs-website#5897]
## How can we make our docs better?

* Is something confusing?
The following header is a bit repetitive and possibly confusing?
**Enrich and notify your notifications with useful metadata**
Could it be:
_Enrich and notify with useful metadata_

* Is something inaccurate or missing?
In the **Alerts (classic)** section, the **Events** is separate from **Incidents**, and in the docs it looks like it's one UI section. 

* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/overview
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Closed via #5919.
