### ISSUE TITLE
Wrong icon for Query builder Issue: Create your first alert

### ISSUE THREAD

**Issue by ahaberkoExt** [newrelic/docs-website#5898]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
The arrow in the first image indicates instant observability and not the Query your data button. 
![image](https://user-images.githubusercontent.com/94530820/151957411-c61d5ad4-ce52-49b7-9e27-2fec598d9372.png)

* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/get-started/your-first-nrql-condition
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Closed via #5901.
