### ISSUE TITLE
Step missing issue: Create your first alert

### ISSUE THREAD

**Issue by ahaberkoExt** [newrelic/docs-website#5899]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
When I type in the the NRQL query, the Create alert button is disabled. I need to run the query first, and then the button gets active.

* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/get-started/your-first-nrql-condition
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Closed via #5902.
