### ISSUE TITLE
Issue:The title of the article is wrong.

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#5917]
## How can we make our docs better?

From the documentation and the actual app, I'm assuming the version number is Android v 4.2.3.
The title of the article is Mobile app for Android v4.3.2.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/release-notes/mobile-apps-release-notes/new-relic-android-release-notes/new-relic-android-423/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for catching this one, @qryuu! I'm fixing it in #5920.
