### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by terrybondy** [newrelic/docs-website#5923]
Tried to follow the "See example NRQL queries" link and it was broken

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/understand-data/event-data/events-reported-apm/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey there @terrybondy, thanks for reporting this! I have a fix for this in #5925, which should go live sometime this afternoon.
