### ISSUE TITLE
URLs with anchor params  that redirect don't carry the anchor to the redirect URL

### ISSUE THREAD

**Issue by halocameo** [newrelic/docs-website#5947]
### Relates to

#2139 

## Steps to reproduce 

1. go to https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-monitors/writing-scripted-browsers#logging 
2. and you will be redirected to https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/introduction-scripted-browser-monitors/ 
3. The "new-relic-synthetics" is replaced by "synthetic-monitoring" in that URL (along with the page name change), however the anchor param at the end is lost so the user does not get to the place on the page they are looking for.

### Expected Behavior

When a redirect URL has an anchor parameter we should carry that anchor over to the new URL and drop the users on the page in the correct location if that anchor exists on the page still.  If the anchor doesn't exist any longer, then the page won't scroll as there is nothing to scroll too.

**Comment by jpvajda** [comment]
@roadlittledawn and worked through this and clarified the bug and what is occurring here.
