### ISSUE TITLE
Issue: Networks - (Browser Domains section)

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#5950]
## How can we make our docs better?

* Is something inaccurate or missing?

In the Browser Domains section here, we do not mention the "cell" endpoint that many customers are now using. We do have references to this endpoint in other places in the docs, see here: 
https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring/

Should we also make an edit here for consistency and clarity? Thank you !

https://bam-cell.nr-data.net

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/networks/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Notes from Cheryl: Here’s a public announcement from product: https://discuss.newrelic.com/t/new-browser-csp-exception-https-bam-cell-nr-data-net/121824 I’m not sure the % of customers, but ingest teams are moving browser ingest data over to the cell endpoint (see @zuluecho9 for project name associated). Some customers are still on the other endpoint but both are being used. #dem-platform would be the engineering team you could ask more questions about this .

**Comment by barbnewrelic** [comment]
See https://issues.newrelic.com/browse/NR-37606 . Thanks for the reminder, @zuluecho9  !
