### ISSUE TITLE
let table headers scroll with big tables

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#5956]
## Is your feature request related to a problem? Please describe

Currently when you scroll in a long table, you lose sight of the table headers. That's a problem because users have to scroll back up to remind themselves what the significance of the information in the given column is, in many cases. 

## Describe the solution you'd like

Make table headers sticky? So you continue to see them, even if you're further down the table.

## Describe why this important to you

Kind of already described. But here's an example (admittedly from the style guide): https://docs.newrelic.com/docs/style-guide/capitalization/product-capability-feature-usage

We had to add "Do not use" to each entry in the fourth column because the header wasn't visible if you scrolled down a bit. And we really didn't want people to get confused and use the wrong capitalization. Which is the whole point of this page. 

While that's an internal style guide, I'm sure it comes up in the docs themselves.

**Comment by barbnewrelic** [comment]
+1 this is important! you lose context with longer tables if you can't see the header row as you scroll down
