### ISSUE TITLE
Issue: Basic platform UI: search, share, chart UI, customize navigation, and more

### ISSUE THREAD

**Issue by adhityaajie** [newrelic/docs-website#5967]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/ui-data/basic-ui-features/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @adhityaajie! Could you describe what problem did you have with the Basic platform UI doc?

**Comment by x8a** [comment]
Hi, @adhityaajie! If you don't have any further questions, I'll close this issue at the end of the week.

Feel free to open a new one with other questions you may have. Thanks!
