### ISSUE TITLE
Clarify the relationship between APM transaction traces and distributed tracing

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#5978]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

As a new APM user, how would I tell the difference between transaction traces and distributed tracing?

Could you insert an explanation in this page telling users the difference: https://docs.newrelic.com/docs/apm/transactions/transaction-traces/introduction-transaction-traces/

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
