### ISSUE TITLE
Issue: Get started with log management

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#5982]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

Maybe it's just me, but this important intro doc seems outdated and not telling a clear story for 2022 log management.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/get-started/get-started-log-management
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
