### ISSUE TITLE
Issue: Forward your logs to New Relic

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#5983]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

I love that we have a flowchart for how log forwarding works, but this illustration is several years old. And to me, it makes it appear more difficult than we intend. It also concerns me that it takes 3 paragraphs that follow to describe the illustration. Recommend a refresh of the flowchart, or maybe a video?

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/enable-log-management-new-relic
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
