### ISSUE TITLE
Retitle "Private locations overview" doc, improve screenshots

### ISSUE THREAD

**Issue by akristen** [newrelic/docs-website#5984]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

Doc: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/private-locations-overview-monitor-internal-sites-add-new-locations

This doc could be improved with a more succinct name, better screenshots, and some structure improvements. 

Action items:

- Rename doc to more succinctly describe the doc's purpose
- Add a better composed screenshot for screenshot number 2 (text is partially cut off; we should include the full words)
- Tip call out in "Create a private location" needs a space after step 2

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
