### ISSUE TITLE
Issue: Use Logs UI

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#5986]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

We originally structured this doc to focus on what problems the customer is trying to solve, but over the past couple years more and more info has been tacked onto the workflow. It's great that our log management solution provides so many options! But at this point I'm wondering if fresh eyes could suggest a way to still focus on the problem solving aspect yet make it not quite so long. For example, we have not done as much as we could in the Troubleshooting taxonomy for log management. Maybe look at those two areas together?

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/ui-data/use-logs-ui
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
