### ISSUE TITLE
Need ability to crop images to specific size

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#5991]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

Our previous (Drupal) docs site allowed us to set a specific size for images. This was particularly useful for cropping out a specific part of the UI in our screenshot but not making the remaining .png blow up. But when we moved to GitHub, unexpected results occur. Here's a doc to show you what I mean:
https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/troubleshooting/no-data-appears-prometheus-integration/

My solution since we switched over was to avoid crop images at all costs. And another writer said his solution was to pad the cropped image with extra white space in SnagIt. These workarounds are OK but not optimal. Would love to restore this functionality.

I know I filed an issue about this before we launched the GH docs site last year, but I don't know what ever happened with my request.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
