### ISSUE TITLE
Glossary has no left nav

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#5993]
The poor [glossary](https://docs.newrelic.com/docs/glossary/glossary) has no left nav:

![image](https://user-images.githubusercontent.com/55203603/152613959-61a54cb2-53f5-4b10-9a6b-676a438ea37a.png)

**Comment by zuluecho9** [comment]
Going to close this one. Going to move glossary into new improve 'guides and solutions' section.
