### ISSUE TITLE
Add meaningful content under "How it works" for Prometheus remote write

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#5996]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work

In this Prometheus topic, we have a "How it works" heading under the Prometheus remote write integration: https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/#remote-write

Unfortunately, the information under "How it works" is about how to sign up. Could you add some meaningful content there instead?

**Comment by pizzaz93** [comment]
Some content was removed in #5692 there might be content that is supposed to be there.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
