### ISSUE TITLE
Simple improvements to mobile monitoring docs

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#5997]
Update Apr 28: note that some of these problems are now fixed in https://github.com/newrelic/docs-website/pull/7357. 

Problems noticed: 
 
• For 'intro to mobile monitoring' doc https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring, recommend moving the example New Relic use case (how we use the product) to another doc and keep the intro doc more simple and high level. 
• In https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/mobile-apps-index: fix bad formatted UI pathing: `[one.newrelic.com > Explorer > Mobile applications`. Take out the reference to the Explorer; just say click 'Mobile'. Get rid of ‘standard menu functions’ information, kind of redundant and obvious. Has wrong description about how to find the metadata for a mobile app. 
• For https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/mobile-apps-overview-page - ‘Mobile Apps’ in sidebar, fix capitalization. 
• In https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/mobile-app-pages/mobile-apps-overview-page - we call it ‘Overview’ but it’s ‘Summary’ now. Sweep for use of 'overview' in that category and replace. Some wrong info about the chart titles that are on that page. 
• Many screenshots in this category show Seldon view, do a sweep to replace screenshots. (maybe make another issue for this, not sure).

**Comment by pizzaz93** [comment]
* Point #1 is about the three use case examples?
* Point #2 I'm not sure about how to remove explorer from that context, is the wrong description metadata portion resolved by removing the standard functions table?
* Point #5 I'm not sure if we should rename the page and headers to summary, if so I'd add a new redirect and update all the locations the file is referenced.

In general if I wanted to continue helping with New Relic docs is there an official way to get involved as a contributor?

**Comment by zuluecho9** [comment]
@pizzaz93 oh sorry I just pinged you in the other PR, didn't see this. I'll send you a LinkedIn message.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
