### ISSUE TITLE
Synthetics "Pages" title, image clean up

### ISSUE THREAD

**Issue by akristen** [newrelic/docs-website#6000]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

The Synthetics "Pages" could have stronger titles. Most docs begin with "Synthetic monitoring," which is redundant. Some docs titles do not correspond with the name in the left nav. 

Docs:

https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-summary
https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/pages/synthetics-results-access-individual-monitor-runs
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-understand-load-times
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-troubleshoot-downtime
https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics

Action items:

- Remove "Synthetic monitoring:" from titles.
- Change docs titles to better correspond with left nav (or left nav to correspond with titles).
- In "Synthetic monitoring: Troubleshoot downtime," first image nested under "View failures page" is flushed to the left. Other images in "Pages" docs are indented. Do we want images flushed to the left, or indented? This appears to be an inconsistency throughout the docs site.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
