### ISSUE TITLE
Issue: .Net Performance Metrics

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#6003]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

This doc could use a thorough style guide edit to fix problems including but not limited to:

- .Net s/be .NET
- Avoid using italics
- Incorrect use of capitalization in headings
- Incorrect use of bold vs. code
- Incorrect use of naming hyperlinks, esp when they go off docs site

We also recommend avoiding multiple or stacked callouts.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/net-agent/other-features/net-performance-metrics
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by pizzaz93** [comment]
* What should the italics be replaced with?
* Is bold vs. code for headers such as `**Threadpool/Worker/InUse**`?
* What are the naming hyperlink conventions and are they regarding the docs.microsoft links or the `one.newrelic.com` link?

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
