### ISSUE TITLE
Issue: Create NRQL alert conditions

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#6004]
This ticket is part of the XD bug bash, Athena initiative, and FutureStack quality work.

This doc has an awful lot of callouts. It's difficult to decide what is most important, esp. when they are stacked one after another. Also recommend taking a look at the table format. Some resizing might make the text and callouts in the right column not appear so squished.

I did not read this doc, only focused on the callouts in it. There are a lot. Do we really need this many, or could this benefit from some copyediting?

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by pizzaz93** [comment]
For the table formatting, transforming it into markdown syntax instead of HTML might fix some of the issues.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
