### ISSUE TITLE
Issue: Android agent compatibility and requirements

### ISSUE THREAD

**Issue by tmancill** [newrelic/docs-website#6017]
## How can we make our docs better?

Very minor, but the page shows (2) different months for the same discontinued functionality.   According to the [Explorers Hub post](https://discuss.newrelic.com/t/important-upcoming-changes-to-capabilities-across-browser-php-python-mobile-and-android-agents/123951), the correct date is January 2021. 

![image](https://user-images.githubusercontent.com/1195611/152820626-1f5fd165-820d-4b4f-8c5f-9a5e456d0ed1.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/get-started/new-relic-android-compatibility-requirements/

**Comment by paperclypse** [comment]
Sharp eyes @tmancill! Thanks for catching that. I'll push up a fix shortly.
