### ISSUE TITLE
Issue: missing/bad image ref

### ISSUE THREAD

**Issue by throck** [newrelic/docs-website#6036]
## missing image / broken image ref

On [this page](https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/choose-your-data-center/#partner-hierarchy), the panel `Hierarchy example for partner accounts` should show an image, but the link points to an image ref:

> https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/choose-your-data-center/images/Eu_account_hierarchy.png

...which does not exist.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/choose-your-data-center/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @throck! I'll investigate what happened with the image 👀.

**Comment by x8a** [comment]
I removed the reference to the image since we do not have it anymore. Thanks for reporting it!

**Comment by throck** [comment]
@x8a I do see the image [here](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/using-new-relic/welcome-new-relic/get-started/images/Eu_account_hierarchy.png), so maybe it's just a relocation / ref update?
