### ISSUE TITLE
Broken link for go instrumentation docs

### ISSUE THREAD

**Issue by codylandry** [newrelic/docs-website#6049]
## How can we make our docs better?

Under the 'Get New Relic for Go' heading, the '[instrumenting your Go code](https://docs.newrelic.com/docs/agents/go-agent/instrumentation)' link is broken.  

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/introduction-new-relic-go/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.80
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey there, thanks for reporting this! I have a fix in #6055 which should go out today.
