### ISSUE TITLE
[Docs] Translate link text in WelcomeTile components on home page

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#6052]
## Is your feature request related to a problem? Please describe

Content on the [home page](https://docs.newrelic.com/jp/) is not available for translation.
<img width="1034" alt="Screen Shot 2022-02-08 at 12 12 25 PM" src="https://user-images.githubusercontent.com/71030271/153059738-6009af45-2c3f-4aee-9727-6a53c37b2d21.png">

## Describe the solution you'd like

Content is being sent for translation like any other content.

## Describe why this important to you

This is the home page and is where many customers meet New Relic. Untranslated content is not ideal. We want to increase experience quality.

**Comment by jpvajda** [comment]
@roadlittledawn The team was discussing this in tech backlog review and was the resolution to this request to manually translate this content? or is there something else to consider?

**Comment by jpvajda** [comment]
We discussed that what's new isn't translated at the moment as they are markdown files not MDX so @roadlittledawn is going to think about the approach to this request.

**Comment by roadlittledawn** [comment]
Closing in favor of https://newrelic.atlassian.net/browse/DOCENG-41
