### ISSUE TITLE
Issue: Upload source maps via API

### ISSUE THREAD

**Issue by quirosfelipe** [newrelic/docs-website#6054]
## How can we make our docs better?

* Is something confusing? A recent bug has been fixed for V1 users publishing source maps via API.  There is a sentence in the docs that must be changed  because will no longer apply after this fix. This is the [GTSE](https://newrelic.atlassian.net/browse/APPEXP-3171) for more info.
* Is something inaccurate or missing? The line that reads 'A [user API key](https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys#user-api-key) (before November 20, 2020, the [Admin API key](https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys#admin) was required; that will still work if already in place)' , should be changed for 'A [user API key](https://docs.newrelic.com/docs/apis/get-started/intro-apis/types-new-relic-api-keys#user-api-key)(this key MUST be used regardless of the user type. The Admin API key will no longer work.'
* Were you unable to complete a task? (What task?) N/A

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/browser-pro-features/upload-source-maps-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by pizzaz93** [comment]
@quirosfelipe and @bradleycamacho would the new text be added to this bullet point 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/10904763/165180880-94783218-21a4-476c-9920-5a45cd712846.png">
?

**Comment by quirosfelipe** [comment]
@pizzaz93  that's correct!

**Comment by zuluecho9** [comment]
This is fixed in https://github.com/newrelic/docs-website/pull/7332. I opted to just say the user key is required (as noting that our older keys will no longer work for various tools/integrations is something that we could theoretically add in many places in docs).
