### ISSUE TITLE
Issue: Legacy New Relic OpenTelemetry Exporters

### ISSUE THREAD

**Issue by hoangj-procore** [newrelic/docs-website#6088]
## How can we make our docs better?

* Is something confusing?
In this page, there's mention of deprecated (legacy) exporters as well as the newer `New Relic OTLP endpoint`. It's not evidently clear what the links in this page represent - the legacy or newer endpoints. There's mention of the US endpoints on the page, are these the newer endpoints that are being referenced?

* Is something inaccurate or missing?
There is a link provided in the first paragraph of the New Relic Language Exporters,
> The [New Relic OTLP endpoint](https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-legacy-new-relic-exporters/#native-otlp) makes this strategy obsolete since it allows applications to export data to New Relic's proprietary endpoints.

Note that the link provided is to this same page, and to a section that doesn't exist on the public documentation page, `#native-oltl`

* Were you unable to complete a task? (What task?)
No. Reviewing the documentation to determine my codebase's configuration

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-legacy-new-relic-exporters/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@hoangj-procore  Thank you for filing this issue! I am going to forward this to engineers who can better answer your questions.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
