### ISSUE TITLE
Issue: Improve web uptime

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#6100]
## How can we make our docs better?

Let's make this page better by calling out the different reasons Synthetic monitors fail (outside of mistakes in configuration)
-Service is down
-Service is not accepting new connections (For instance, when an app server recycles threads)
-Slow page load (Greater than 60s)
-Timeouts (For scripted monitors)
-Network

Also, add a link to this page: https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/troubleshooting/troubleshoot-isolated-monitor-failures/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/customer-experience/cx-improve-web-uptime/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by khickey-newrelic** [comment]
Docs team/hero - can we add a label to this, like oma-fix?   We can use oma-fix and oma-new to route to the oma (Observability Maturity Architecture) team.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
