### ISSUE TITLE
Issue: Quality foundation implementation guide

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#6125]
## How can we make our docs better?

The link in "Once you have identified which pages to improve, improve them following these [best practices](https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/customer-experience-cx-improve-page-load)." is incorrect. 

It should be: 
https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/customer-experience/cx-improve-page-load/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/customer-experience/quality-foundation-implementation-guide
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.80
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks @khickey-newrelic. I'll change that. Just a heads up for future things you notice; you can actually quickly submit an edit to the docs site on your own, which is described here: https://docs.newrelic.com/docs/style-guide/writing-docs/processes-procedures/create-edit-content#edit-doc. No matter which way you do it though, we always appreciate all fixes and notes about problems.

**Comment by zuluecho9** [comment]
Fixed in https://github.com/newrelic/docs-website/pull/6129.
