### ISSUE TITLE
[Build Performance] Reduce size of huge files to improve build times

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#6130]
## Summary

For any given build you'll see a warning in the console re: some queries are taking longer than 15s which is due to how big a file is (or how much data they're pulling from graphql).

It would be great if we could somehow break these MDX files up so they're not as huge.

<details>
<summary>Example error</summary>

```bash
This query took more than 15s to run — which is unusually long and might indicate you're querying too much or have some unoptimized code:

File path: /usr/src/app/www/src/templates/docPage.js
URL path: /docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration/
Context: {
    "fileRelativePath": src/content/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration.mdx,
    "slug": /docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration,
    "slugRegex": /docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration/.+/,
    "disableSwiftype": false,
    "locale": "en"
}
```
</details>

Release note index pages are covered in this ticket.

## Acceptance criteria
- [ ] Check a recent build in `docs-website-develop` and get list of MDX files (non-release note) that warn re: long query
- [ ] Break file up if possible

## Helpful links
- https://github.com/newrelic/docs-website/issues/5621
- https://github.com/newrelic/docs-website/issues/5676
- https://github.com/newrelic/docs-website/issues/2317

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
