### ISSUE TITLE
use a different button style for view all docs buttons

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#614]
The view all docs button is very subtle, lets use a more prominent button style so this action is more visible. 

`variant={Button.VARIANT.PRIMARY}`

Instead of the subtle button use the style that is found on the integrations section of the home page. 

<img width="459" alt="Screen Shot 2021-01-21 at 4 57 36 PM" src="https://user-images.githubusercontent.com/1395158/105427172-ce44ab80-5c09-11eb-8db0-9d87dfc8434e.png">

**Comment by zstix** [comment]
@jpvajda / @djsauble Do you have a preference for how we go about increasing the visibility for this?

It currently has the "primary" variant applied to it.

**Comment by jerelmiller** [comment]
I think the mock is for the wrong item. I _believe_ this is meant to cover the landing page "View all docs" button which has a `normal` variant applied to it.

<img width="1237" alt="Screen Shot 2021-02-12 at 1 34 55 PM" src="https://user-images.githubusercontent.com/565661/107824962-25d0c580-6d37-11eb-912e-5f9eeb91da54.png">

**Comment by jerelmiller** [comment]
Oh the screenshot above is actually correct. I missed the language above it. This is the key part:

> use the style that is found on the integrations section of the home page.

**Comment by jpvajda** [comment]
☝️
