### ISSUE TITLE
[i18n] Fix workflow to send content to human translation

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#6150]
## Summary

The workflow to send content to human translation [failed](https://github.com/newrelic/docs-website/runs/5015066533?check_suite_focus=true). Looks like it's likely due to similar issue we fixed for machine translation where a package was updated that was switched over to ESM (which we can't support quite yet). The fix for that MT workflow was to downgrade `rehype-format`. 

It's a little confusing since this workflow uses `serialize-mdx.js` and the downgraded `rehype-format` package. Maybe a cache issue? Not sure why this would be using the newer version of `rehype-format`.

## Acceptance criteria
- [x] Apply fix (probably downgrade `rehype-format` to previous version we were using)
- [x] Test locally via [translation workflow testing](https://github.com/newrelic/docs-website/tree/develop/scripts/actions/translation_workflow/testing) to verify it works
- [x] Run tests and update any failing tests

## Helpful links
- https://github.com/newrelic/docs-website/pull/5909

**Comment by nr-kkenney** [comment]
we definitely overthought this. this workflow failed on the first of the month, before we had changes merged in to remedy the error that its seeing. 

i just ran it now, and it had mostly successes: https://github.com/newrelic/docs-website/runs/5191410610?check_suite_focus=true

two files failed:
```
Error occured during upload process for: src/content/docs/accounts/accounts-billing/new-relic-one-user-management/user-type.mdx
Error: Error: Unable to serialize component: 'sup'. You need to specify a serializer in 'scripts/actions/utils/handlers.js'
```
and
```
Error occured during upload process for: src/content/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal.mdx
Error: Error: Unable to serialize component: 'div'. You need to specify a serializer in 'scripts/actions/utils/handlers.js'
```

**Comment by roadlittledawn** [comment]
oh oops. could have sworn i got an email about the failed workflow, which is what prompted me to look at the latest run which failed. 🤦 

looking into the two failed files now. the `sup` one seems suspicious. not sure why wouldn't be able to serialize a `div` though

**Comment by nr-kkenney** [comment]
this should be good to go with @roadlittledawn PR merged. closing.
