### ISSUE TITLE
[Docs: i18n] Document how to add a new language to the site

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#6152]
## Summary

We want to document the process for adding a new language to a gatsby site that uses the theme.

I think the most suitable place for now is a new page adjacent to the [Translation workflow](https://github.com/newrelic/docs-website/wiki/Translation-Workflow) article

## Acceptance criteria
- [ ] Create a new wiki page that documents how to add a new language to the site (including info on updating theme, github action workflows, site config, and bulk adding the content via machine translation)
- [ ] Update the [Translation workflow](https://github.com/newrelic/docs-website/wiki/Translation-Workflow) as needed for current state of things

You can refer to the epic doc, since that contains all the info for adding Korean to the site, and will likely be the same for adding any language to the site.

## Helpful links
-  [Translation workflow](https://github.com/newrelic/docs-website/wiki/Translation-Workflow)
- [Theme PR](https://github.com/newrelic/gatsby-theme-newrelic/pull/640) to add support for Korean
- [Epic Doc](https://docs.google.com/document/d/1R2mm4SSnwtvpuNnBHWx8tbU8tD38qKIn0uXxA-SF-Oc/edit)

**Comment by jpvajda** [comment]
@roadlittledawn & @nr-kkenney to review.

**Comment by nr-kkenney** [comment]
@LizBaker looks good. one thing to maybe add is what we need to do on the vendor side, but if thats a julien only thing we probably dont need to add it.

**Comment by LizBaker** [comment]
@roadlittledawn do we need to add details on smartling work or should i just add a step of collaborating with our language team/vendor?
