### ISSUE TITLE
Issue: Global Technical Support offerings

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#6168]
## How can we make our docs better?

Terminology "support ticket" was changed to "support case" in the UI and auto-reply mail.
As reference, you can see current UI to file a new support case from this [page](https://discuss.newrelic.com/t/getting-help-during-the-support-portal-maintenance/175240).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.80
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @shinji-newrelic! Thanks for letting us know. I fixed it already in the above mentioned pull request.

Please feel free to make the edits yourself! You can even use GitHub to submit pull requests 🙌🏻.
