### ISSUE TITLE
Issue: RabbitMQ monitoring integration

### ISSUE THREAD

**Issue by Julien4218** [newrelic/docs-website#6174]
Please remove the Quick start documentation, we're removing the Guided Install option for now.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by Julien4218** [comment]
https://github.com/newrelic/docs-website/issues/6175

**Comment by rhetoric101** [comment]
@Julien4218, I am closing this GitHub request because I created PR #6181 that removes this.
