### ISSUE TITLE
Issue: addPageAction (browser agent API)

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6177]
Whenever I navigate to this link (from google):

https://docs.newrelic.com/docs/browser/single-page-app-monitoring/use-spa-data/spa-data-collection/

I am redirected to this page (add-page-action) which makes no sense.  I was trying to show a customer the definition of (spa-data-collection) which is now not accessible.

* https://docs.newrelic.com/docs/browser/new-relic-browser/browser-agent-spa-api/add-page-action/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.80
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting it, @GaPeppy - it's been fixed in #6197.
