### ISSUE TITLE
Use long titles on page views vs using short titles.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#618]
This was identified in our stake holder review meeting, but it seems some pages are using the long titles  and some aren't. I'm not sure on what the difference is where we saw the shorter titles being used on a page. So this issue is just to ensure we always use the data in the title slug.

`title: Optional manual Browser instrumentation with Django templates`

as the page title. 

![Screen Shot 2021-01-21 at 5 43 47 PM](https://user-images.githubusercontent.com/1395158/105430250-5332c380-5c10-11eb-9381-7caab362d376.png)

**Comment by jerelmiller** [comment]
> some pages 

In this case, the "some pages" were the table of contents pages. If you go to a landing page, then click on the "view more" button at the bottom, you'll see that the list of links there uses the short title from the nav, not the page title from the doc. We want to instead use the page title in that list of links for the table of contents pages.
