### ISSUE TITLE
Need info about metric data rollup for infra agent

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#6180]
## How can we make our docs better?

* Is something inaccurate or missing? Reported in documentation slack channel 02-15-2022:  Could somebody update the following page to include something on infra metrics and how they rollup? It is very confusing at the moment.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/manage-data/manage-data-retention/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@tpitale  This request arose in our documentation slack channel today and the person reporting it listed you as an SME. Can you please update the doc with this info? Or please add more details in this issue. Thanks!

**Comment by zuluecho9** [comment]
This work was done. Infra info was added here: https://docs.newrelic.com/docs/data-apis/manage-data/manage-data-retention/#infrastructure-data
