### ISSUE TITLE
Per DOC-7551, update APM agent screenshot

### ISSUE THREAD

**Issue by akristen** [newrelic/docs-website#6191]
From the jira:

> "screenshot in [this section](https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/agent-data/agent-attributes/#viewing) is quite out of date. To fix, the screenshot needs to be replaced and the accompanying info on how to find this information"

Tried to work through this ticket with another tw as part of onboarding, but we couldn't find a comparable section in New Relic. We came across "intrinsic attributes" when following the docs' instructions, but no one was able to answer if transaction attributes are the same as request attributes, or clarify what intrinsic attributes are. Was advised to file an issue for it.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
