### ISSUE TITLE
[Docs: Translation Scaling] Add Korean machine translations Part Deux

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#6209]
## Summary

Part 2 of https://github.com/newrelic/docs-website/issues/5882

Once all files are queued up and sent for translation, next steps are:

1. wait for first translation PR (machine translation PR) to be made. The human translation PR will likely take a long time.
2. add in code changes to enable the site to build korean pages.
3. verify content + code change builds without errors, merge content + code change feature into develop.

## Acceptance criteria
- [x] Bump theme (to at least `5.0.2`) to get support for Korean in translations PR
- [x] Add `kr` to `additionalLocales` in `gatsby-config.js` in translations PR
- [x] Verify content + code builds without errors and attempt to fix issues
  - @jmiraNR  would like to know the errors encountered. so as they are identified and fixed, keep track and at the end submit all the problems to @jmiraNR.
- [ ] File separate ticket if large amount of errors / more work required to fix workflow or failed build issues
- [ ] Merge into `develop`
- [x] Translate the homepage (human translation)

## Helpful links
https://github.com/newrelic/docs-website/issues/5882

**Comment by jmiraNR** [comment]
@roadlittledawn Can we add a distinct "Disclaimer checkbox" please? or is that included in "Content" [ Verify content + code builds without errors and attempt to fix issues] Thx

**Comment by nr-kkenney** [comment]
korean PR is: https://github.com/newrelic/docs-website/pull/6438
