### ISSUE TITLE
Gatsby Cloud builds frequently timing out

### ISSUE THREAD

**Issue by MoonlightKomorebi** [newrelic/docs-website#6213]
## Summary
Recently, it seems like we are seeing more builds that time out. Builds that time out report as failures on PR checks, but do not provide any insight as the failure is not related to any change a user makes. To run subsequent builds, most people have to push additional commits (not everyone has access to GC), and even then, there is no guarantee that the subsequent build will run w/o also timing out.

From the perspective of our team, what we can see and do about the problem is minimal. We don't have insight into why builds are queued and timing out, and can only cancel builds & trigger them -- and sometimes we can't even do that.

We need clearer instructions on how we should be using GC builds if we're using them improperly or too much, and easier ways remedy issues as we run into them.

## Build Links

<details>

- https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/add3d220-8b14-478b-b7a7-a3ac0ef4c844/details

- https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/855af51d-710c-4b24-8cd5-60a1b088fac6/details

- Build that keeps checking out repository, looping on checkout: https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/58cbd51b-94f8-4fe9-9abd-d22e0f7467ae/details#all

- Another build with looping checkout: https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/b73b0aa1-ed87-4068-8cbf-326f3f4efe3f/details

![Screen Shot 2022-02-22 at 11 39 38 AM](https://user-images.githubusercontent.com/70179215/155206444-7a2ab40e-9702-414e-bd49-c626e4ea097e.png)

- In progress build that I wanted to cancel, but had no cancel button: https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/1667e3ae-24bd-401d-9634-546cda1e513a/details

![Screen Shot 2022-02-22 at 1 49 53 PM](https://user-images.githubusercontent.com/70179215/155225502-1cf80db9-1020-4304-bb9a-2de0495a446a.png)

</details>

## Acceptance Criteria
- [x] Verify / create a support with ticket with Gatsby to summarize what we're experiencing / make them aware
- [x] Ask / verify re: build queuing and what happens when there's a time out
- [ ] Determine next steps 

## Related
https://support.gatsbyjs.com/hc/en-us/articles/4416086727059-Build-Concurrency

**Comment by bradleycamacho** [comment]
This release timed out: https://github.com/newrelic/docs-website/pull/6245

**Comment by paperclypse** [comment]
I'm getting unusual build messages here: https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/58cbd51b-94f8-4fe9-9abd-d22e0f7467ae/details

**Comment by roadlittledawn** [comment]
This isn't quite the same issue, but it's related. It's also a little confusing.

When a release PR (`daily-release/*`) is opened to `main` two Gatsby builds are triggered:
- one for `docs-website` (connected to `main`)
  - Required check to merge
- one for `docs-website-develop` (connected to `develop`)
  - Not a required check, but also why does this happen? And it sometimes times out.
  - Presumably it times out because there's another active build for `develop` and it waits for that one to finish but times out?

## Recent example
- [PR](https://github.com/newrelic/docs-website/pull/6313)
- [Gatsby build](https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/6aa273d9-9876-4483-8719-acb5fb20944f/details)

**Comment by roadlittledawn** [comment]
@x8a PR experienced a timeout today.
- [PR](https://github.com/newrelic/docs-website/pull/6329)
- [GC build history](https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/pull-requests/35552142-5c89-40dd-bc4e-861e4b6dcd2b/builds)

**Comment by roadlittledawn** [comment]
this one happened to me today when i pushed a 4th commit to a PR branch:
* [build page](https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/7711a0ab-ebb4-4a49-86ea-8207fd621421/details)
* [build history page](https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/pull-requests/6f19711e-7554-4e34-b5a2-2fa92c813c64/builds)
* [PR](https://github.com/newrelic/docs-website/pull/6407)

**Comment by bradleycamacho** [comment]
@austin-schaefer's PR had a weird one. It ran for almost three hours and then failed for what seemed to be no reason. It may be the same issue we're trying to resolve here, but it's strange because the build did start:

https://github.com/newrelic/docs-website/pull/6408

**Comment by paperclypse** [comment]
This PR timed out:
https://github.com/newrelic/docs-website/pull/6359
https://www.gatsbyjs.com/dashboard/34e708d2-68a1-48ca-b66f-d2604890b061/sites/a0b77314-cdea-4790-8fde-7d3457d590ce/builds/0ba98f30-d5a1-4756-9826-d98e59088f73/details

**Comment by zuluecho9** [comment]
This PR timed out several times in a row, with me retriggering the build with minor changes each time. https://github.com/newrelic/docs-website/pull/6509

**Comment by henrikwirth** [comment]
Experiencing timeouts too. Also a lot of times I can't cancel a build even though the Cancel Button is there. It says it cancelled it, but doesn't do it.
