### ISSUE TITLE
Issue: Compatibility and requirements for New Relic agents and products

### ISSUE THREAD

**Issue by hroseross** [newrelic/docs-website#6222]
## How can we make our docs better?

The Node agent is not included in the list of language agents

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/cross-product-functions/install-configure/compatibility-requirements-new-relic-agents-products/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.80
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@hroseross  I am a bit confused by your question. I checked the Node.js link in the APM agent section and it works. Was there something else you were expecting? Thanks for clarifying! https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/cross-product-functions/install-configure/compatibility-requirements-new-relic-agents-products/#apm-compatibility

**Comment by barbnewrelic** [comment]
Confirmed with @hroseross  that all is well, no other updates needed
