### ISSUE TITLE
[Docs] Docs Sidebar keeps localized title after switching locals via dropdown

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/docs-website#6224]
## Description

While switching locales in the [docs website](https://docs.newrelic.com/), there remains a persistent localized title in the sidebar that adds onto itself after each swap from `en` -> `ja` -> `en`. The title stays in two seperate parts of the sidebar, which seems to be the same title. Clicking the localized title on the english page does not redirect/route/do anything.

<details>
<summary>Example of bug</summary>
<img width="320" alt="Screen Shot 2022-01-25 at 4 39 02 PM" src="https://user-images.githubusercontent.com/56952981/154385593-294a0e8d-e001-4382-84b7-a9caab9f78d2.png">

</details>

<details>
<summary>Example of bug after swapping to `ja` twice, ending at english docs</summary>
<img width="317" alt="Screen Shot 2022-01-25 at 4 39 21 PM" src="https://user-images.githubusercontent.com/56952981/154386467-6bcbc015-70ef-4791-b992-712d2eeec808.png">

</details>

### The bug seems to also appear on the localize page as well.

<details>
<summary>Example of bug after swapping to `ja` twice</summary>
<img width="301" alt="Screen Shot 2022-02-16 at 5 10 52 PM" src="https://user-images.githubusercontent.com/56952981/154385729-15ee9ae9-cdd9-46b6-b712-57ecd4f24382.png">

</details>

## Steps to reproduce

1. Go to locale button dropdown in the global header and select another locale (Japanese in this case)
2. Go to locale button dropdown in the global header and select english
3. Look at the left sidebar and see the localized title in two places.
4. Clicking on title leads to nothing (even in localized page)

## Expected behavior

- Swapping between translated pages and english pages should not contain translated titles from previous selected locale.
- Clicking the title should link to something if displayed

**Comment by roadlittledawn** [comment]
the japanese text that's repeatedly added to the left nav is "section break" in japanese, so something with section break in YAML when we switch back and forth perhaps. something we can maybe filter out via the nav related components?

**Comment by roadlittledawn** [comment]
Fixed this in this commit https://github.com/newrelic/docs-website/pull/6753/commits/79fea7bef23d5894bb052cd9e68c85597bede46d

**Comment by roadlittledawn** [comment]
the PR that commit was in was just merged.
