### ISSUE TITLE
Issue: Incorrect host name reported (`override_hostname` doesn't help)

### ISSUE THREAD

**Issue by x-yuri** [newrelic/docs-website#6225]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing? `override_hostname` doesn't change the name of the host on the Infrastructure > Hosts page. What changes the host name is `display_name`.
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/troubleshooting/incorrect-host-name-reported/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by brushknight** [comment]
Hello! `override_hostname` used to override full hostname as it is written in config comment on [GitHub](https://github.com/newrelic/infrastructure-agent/blob/master/pkg/config/config.go#L229-L233). It is not the same as you can see on the Hosts tab as there used hostname or display_name if set. Display_name has a higher priority and will beat hostname in this case.
