### ISSUE TITLE
Attributes that shouldn't be in the drop down should be removed.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#623]
There are attributes that are set to published in Drupal that shouldn't be.  Once they are set to unpublished in Drupal we can do a migration update to correct those on the New Docs site.

**Comment by jpvajda** [comment]
There should be no engineering effort on this one, it can all be done in Drupal

**Comment by austin-schaefer** [comment]
@jpvajda : There's thousands of affected attributes and dozens of event types. Is it possible we can do some light automation on the Drupal side (@roadlittledawn may have ideas?) to reduce toil?

**Comment by jpvajda** [comment]
@austin-schaefer ah ok, I thought when we discussed it was something that could be done by a content editor.

**Comment by roadlittledawn** [comment]
i think bulk editing in the Attribute Explorer workbench tab (URL omitted) may be the best bet here, which is what i've used in the past to mass publish / unpublish.
