### ISSUE TITLE
Issue: Install the Kubernetes integration using Helm

### ISSUE THREAD

**Issue by Nateb1121** [newrelic/docs-website#6230]
## How can we make our docs better?

Documentation states `nri-bundle` includes [`newrelic-infrastructure-v3`](https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-infrastructure-v3) but if you examine nri-bundle's [requirements](https://github.com/newrelic/helm-charts/blob/4feb626e7fc8751bc1c256ebc665f92eee5640b6/charts/nri-bundle/requirements.yaml#L3) you'll see it actually references `newrelic-infrastructure` and not `newrelic-infrastructure-v3`. 

`newrelic-infrastructure` does not contain the same feature set as `newrelic-infrastructure-v3` so they are not interchangeable. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
for other TWs: I asked about this in the help-gts-infra slack channel.

**Comment by roobre** [comment]
Hey @zuluecho9, thanks for reporting this. Both you and the documentation are correct :)

Version 3 of the newrelic integration uses the `nri-bundle` chart v4, which is not located in the `helm-charts` repo but rather [here](https://github.com/newrelic-forks/helm-charts/blob/master/charts/nri-bundle/requirements.yaml). To avoid causing friction with users and installation helpers, we still however release versions of the chart located in the `-forks` repo in the [old one](https://github.com/newrelic/helm-charts/blob/47b3f35d9120a34b8e70128d789121f2d3976404/index.yaml#L3625). This hack allows us to keep the installation procedure simple.

This is a temporary measure while the new chart is in beta. Our intention is to GA it by end of March, in which moment the following will happen:
- The `newrelic-infrastructure` chart will stop existing and `newrelic-infrastructure-v3` will be renamed to `newrelic-infrastructure`, effectively resulting in a major version update from v2 to v3.
- The `nri-bundle` chart will be updated in the main repo and the `-forks` repo will be deleted.
- We will remove from the docs the references to `newrelic-infrastructure-v3`.

I am aware this might be a bit convoluted, but hopefully I was clear and all the weirdness will be gone soon :)

Thanks again for paying close attention to this and taking the time to report it!

**Comment by bradleycamacho** [comment]
@roobre thanks for the info, that was really useful.

If I'm reading that correctly, there are no docs changes that have to happen at this moment correct? In that case I will close this for now pending those updates in March. Thanks for reporting this @Nateb1121!
