### ISSUE TITLE
Issue: Java agent configuration: Config file

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6238]
Configuration of "Distributed tracing" in the docs is shown as defaulted to "false".

However the release notes for 7.4.0 says:

`Distributed tracing is on by default`

So are the docs behind?

* https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.102
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
@GaPeppy I confirmed this was an oversight with the Java team. Fixing this now, thanks for reporting this!
