### ISSUE TITLE
Issue: iOS SDK API guide

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6243]
It is fairly confusing that while the Android SDK breaks out in the table of contents the description of `startInteraction` and `endInteraction`; the IOS SDK obfuscates all in the single block titled "iOS SDK API guide".

There should be layout symmetry between Android and IOS for the very same logical custom instrumentation actions.  Customers should be able to location interaction handling in the toc for both Android and IOS.

Note:  It extends to more than just interaction handling but that was a convenient example that the customer stumbled through today.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/ios-sdk-api/ios-sdk-api-guide/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
