### ISSUE TITLE
Issue: Translated page of Create NRQL alert conditions

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#6253]
## How can we make our docs better?

There is no note at the top of this page indicating automatic translation, so it was probably translated manually.

In the paragraph describing the aggregation window duration, 
"You can set it to anything between 30 seconds and 120 minutes."
however,
In the Japanese page, 
"You can set it to anything between 30 seconds and 15 minutes."

### Doc information (don't delete this section)

* https://docs.newrelic.com/jp/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jmiraNR** [comment]
Thank you @qryuu for reporting this. The content is currently being updated through our translation process and the change will be applied very soon. Have a nice day.
