### ISSUE TITLE
Issue: Organization and account structure

### ISSUE THREAD

**Issue by jfairhead** [newrelic/docs-website#6254]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/account-structure/new-relic-account-structure/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.102
* **Device**: Unknown

**Comment by jfairhead** [comment]
this page links to this URL https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/ but doesn't exist

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @jfairhead - we'll fix it in #6258.
