### ISSUE TITLE
Initial Support Response SLAs do not match the in-product impact levels when opening support ticket

### ISSUE THREAD

**Issue by NRrregine** [newrelic/docs-website#6255]
## How can we make our docs better?

The docs refers only to Standard and Critical impact levels while the options when opening a support ticket are Low, Normal and High (as well as critical). Its confusing since its not clear what difference Low, Normal and High refer to in terms of expected response times. 
There should be alignment between the two elements. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/global-technical-support-offerings/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@NRrregine  I have reached out to our Support team. They are going to investigate further and will update the doc. Thanks again for bringing this to our attention!

**Comment by urbiz-nr** [comment]
Added to CF board as well.

**Comment by barbnewrelic** [comment]
@urbiz-nr  thanks for fixing the labels for me!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
