### ISSUE TITLE
on the Attribute Dictionary  right rail add a free form search field.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#626]
A user should be able to quickly search for an attribute using a free form search field, and when they execute a search it would return any matching attributes. 

<img width="384" alt="Screen Shot 2021-01-21 at 6 39 25 PM" src="https://user-images.githubusercontent.com/1395158/105434283-7b262500-5c18-11eb-9f2b-ddfd834d1619.png">

**Comment by jpvajda** [comment]
This would be useful but definitely a stretch item for our MMF13.

**Comment by austin-schaefer** [comment]
Request from duplicate issue #1281:

> Please restore attribute search capability to the Data Dictionary. In the current version you must select the event type first then choose the attribute. When planning optimal NRQL, it is helpful to know which attributes are shared by which event types. As such, attribute search very helpful.

**Comment by zuluecho9** [comment]
There is probably hidden complexity to implementing this issue. Couple reasons: 1) some attributes are redundantly documented and have multiple entries despite having the same name. 2) Ideally, searching for an entry would land you on an attribute entry page that doesn't display the definition of the data type it's attached to at top, but I think currently an attribute entry will display a data type entry above it.

**Comment by austin-schaefer** [comment]
Still very much a valid request.

**Comment by bradleycamacho** [comment]
This has been requested again in #2289.

**Comment by paperclypse** [comment]
I think this would also address this external issue that came in today #2351

**Comment by paperclypse** [comment]
Would it be possible to index the data dictionary terms in our site search? That might be an easier, interim solution.

**Comment by roadlittledawn** [comment]
@austin-schaefer || @jpvajda . if / when we add a free form search for attribute names, would we want to remove the dropdown to select a specific attribute?

**Comment by jpvajda** [comment]
@roadlittledawn I'd say we'd keep the drop down as it helps users see what is available to them, or they can enter a search query... also interested in what @austin-schaefer thinks..

**Comment by roadlittledawn** [comment]
@jpvajda i'll put a PR preview up for this so you can poke at it, BUT that attribute dropdown is only enabled when a single event is filtered on. otherwise it could potentially be a long list. and the list could have options/attributes that have the same names (because an attribute can be in multiple events OR there could be distinct attributes with same names that are because they mean something else within their event).

**Comment by roadlittledawn** [comment]
here's that preview link: https://docswebsitedevelop-clangalbaattributesearch.gtsb.io/

**Comment by austin-schaefer** [comment]
@roadlittledawn Looking good!

Couple of tweaks:

- I like removing the dropdown/filter for individual attributes. I think the search field solves for most uses cases for this dropdown. 
- Can we change the **Apply filter** header to **Search and filter**? I want to highlight search. 
- Can we also change **Apply** button label to **Search**. That feels like a more natural verb for the new options. 

I’m testing on my phone, so we probably want a writer to test this on a “real computer” too.

**Comment by jpvajda** [comment]
One other bit of feedback I had: was to allow the results of the search to return dynamically as user queries (like our global search) instead of requiring them to click the apply button. The current approach breaks a UI pattern, which I'd prefer we align the search exp across the site for all search fields so it's consistent. 💯

**Comment by roadlittledawn** [comment]
@austin-schaefer incorporated your feedback. also made a couple other small tweaks:
- update label for search to be consistent with the other filters
- add placeholder text to indicate what type of matching
- perform search when pressing `enter` key

https://docswebsitedevelop-clangalbaattributesearch.gtsb.io/attribute-dictionary/

**Comment by roadlittledawn** [comment]
@jpvajda i just added searching automatically for each keypress on the search input. it's really slow (due to the size of the data it's manipulating) and makes for a weird experience. not sure what we could do to speed that up really. maybe we mitigate it by only auto searching every 3rd keypress?  ¯\_(ツ)_/¯

i can put that up in another branch preview if you want to poke at it

**Comment by jpvajda** [comment]
@roadlittledawn yes please! I'd love to take a look at it.

**Comment by roadlittledawn** [comment]
here ya go, @jpvajda . preview is pending. https://github.com/newrelic/docs-website/pull/3087
