### ISSUE TITLE
Issue: Filter AjaxRequest events

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#6264]
## How can we make our docs better?

Due to changes deployed last week in the Browser UI, the ajax UI is now displaying event data. Previously this was metric data. 

Docs Action: remove this line or edit the last phrase: 
_Regardless of this filter, all network requests are captured as metrics and available in the AJAX page._

Or edit _available in the AJAX page_ to available in the Metric Query Explorer. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/configuration/filter-ajax-request-events/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by CherylFrankenfield** [comment]
See threads here in relaunch-browser:
https://newrelic.slack.com/archives/C0248L35VDG/p1644531497427389
 
https://newrelic.slack.com/archives/C0248L35VDG/p1643926261407459

We might also want to relay that ajax requests filtered in the deny list, will NOT appear in the UI page now, given that the UI is based on events not metrics. The deny list blocks AjaxRequest events.

**Comment by paperclypse** [comment]
Thanks for letting us know @CherylFrankenfield! I'll update this doc.

**Comment by paperclypse** [comment]
Does this work for you @CherylFrankenfield? https://github.com/newrelic/docs-website/pull/6266
