### ISSUE TITLE
Issue: SPA compatibility and requirements

### ISSUE THREAD

**Issue by premiscool1** [newrelic/docs-website#6268]
we are a new team and starting with new application client side react (SPA) app, can you please guide us on  what's the recommended process to have new Relic monitor this app ? 
2)  We don't have node.js backend. Our app is a client side react (SPA) app. So, I cannot add require('newrelic') in my code . For us, copy/paste method makes sense. For copy/paste method,  I need to get the newRelic javascript snippet that I can embed in my html. I am not able to do this from New Relic portal since I cannot locate my appId.
3).where do one get appId, licenceKey, trustKey for each environment , where do I get that information?

**Comment by paperclypse** [comment]
Hi @premiscool1! Thanks for reaching out. I'm not an expert on this, but I'm happy to give you some docs links to help you get started.

Here's some information about compatibility and requirements for browser monitoring: https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/compatibility-requirements-browser-monitoring You'll want to confirm that your app meets these requirements before you go too far. :)

2) For the JavaScript snippet, you'll need to get that from one.newrelic.com. The instructions for where to get that are here: https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/#enable

Go to [one.newrelic.com](https://one.newrelic.com/), select Browser, and then select Add more data. Then click the New Relic Browser tile. Follow the instructions on that page to generate your JavaScript snippet. When you generate the snippet, it will generate an App ID for you.

3. Here's a doc that describes how to find your App IDs: https://docs.newrelic.com/docs/apis/rest-api-v2/get-started/get-app-other-ids-new-relic-one/

And here's a doc that describes the various keys we use https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/ Most if not all of these can be found in your account dropdown in one.newrelic.com.

I hope this was helpful!
