### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by PRAVEEN-PYDIMARRI** [newrelic/docs-website#6274]
I would like to know the process of installing new relic infra agent in azure VMSS (Virtual machine scale sets). I tried to install new relic plugin in azure VMSS but I don't see neither data nor VMSS name in newrelic portal. Much appreciated for the help.

**Comment by urbiz-nr** [comment]
Hello @PRAVEEN-PYDIMARRI, thanks for reaching out! 

Did you follow [these steps for the extension](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/azure-extensions-infrastructure/)? If this doesn't work, try asking our [Explorers Hub](https://discuss.newrelic.com/), support will be able to help you there.

**Comment by PRAVEEN-PYDIMARRI** [comment]
I followed the same way to install newrelic plugin in VMSS but its not showing any data in newrelic portal.

**Comment by PRAVEEN-PYDIMARRI** [comment]
Do we have any ETC for the response of questions raised in Explorer hub?

**Comment by urbiz-nr** [comment]
Do you mean time to respond? I can check, but my experience is that you'll get some answer rather fast.

**Comment by PRAVEEN-PYDIMARRI** [comment]
Sure, looking forward for the solution if possible as soon as quickly. Thank you

**Comment by PRAVEEN-PYDIMARRI** [comment]
Would be great if you prioritise my issue please.The solution which was provided is through integration from azure services but I am looking via custom scripts. Kindly prioritise .

**Comment by urbiz-nr** [comment]
Did you post on the Explorers Hub? Can you send me the link so I can move it around? Thanks!

**Comment by PRAVEEN-PYDIMARRI** [comment]
https://discuss.newrelic.com/t/new-relic-infra-agent-installation-in-azure-vmss/177414/3?u=p.pydimarri

**Comment by PRAVEEN-PYDIMARRI** [comment]
Is there anyway that we can prioritise my issue please?

**Comment by urbiz-nr** [comment]
Portland's just waking up, ping the person who answered your post. I can't do anything else from here, I'm sorry.
