### ISSUE TITLE
Feedback on Salesforce Event Log Optimization

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#6283]
Please review the recommended updates to the Salesforce Eventlog Quickstart as linked below. 
https://docs.google.com/document/d/1Ii8lKD1cNDRLrazUVqOG5pC97GNgOlKkA6lwsW2osRU/edit#heading=h.wfeszxbfmgy0

**Comment by urbiz-nr** [comment]
Hi, @aliandersonsn - reviewed, you're good to go!
