### ISSUE TITLE
Issue: Visualize your network performance data in New Relic One

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#6319]
This page is referencing the old quickstarts catalog app that is deprecating. Could we update this page's content?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/network-performance-monitoring/monitoring-network-data/visualize-network-data/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 97.0
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@jpvajda  I'm sorry, I don't understand what you mean. Can you please clarify? Or may @x8a  knows? Thanks for any suggestions!

**Comment by jpvajda** [comment]
@barbnewrelic sure no problem, this section https://docs.newrelic.com/docs/network-performance-monitoring/monitoring-network-data/visualize-network-data/#add-dashboards

mentions using the quickstart 3rd party app that is deprecated, so I suggested we just remove it all together or perhaps just point users to https://newrelic.com/instant-observability/ for any dashboards they wish to install. 

<img width="529" alt="Screen Shot 2022-02-24 at 5 30 27 PM" src="https://user-images.githubusercontent.com/1395158/155630815-7bd2a229-3939-4376-a0da-c4711d6e92ab.png">

**Comment by x8a** [comment]
I can talk to my stakeholders about it. They must have an updated way to add the dashboards. Thanks for bringing it up!

**Comment by barbnewrelic** [comment]
Thanks so much @x8a ! I'll follow up with you next week so we can collaborate on this request.

**Comment by x8a** [comment]
I fixed it with PR #6373. 

Thanks again for letting us know, @jpvajda!

**Comment by jpvajda** [comment]
@x8a wonderful! Thank you. 🙏

**Comment by barbnewrelic** [comment]
I agree. @x8a  rocks! Always!
