### ISSUE TITLE
Issue: Introduction to AWS integrations

### ISSUE THREAD

**Issue by silentrunner888** [newrelic/docs-website#6331]
On this page:  https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations/

These two links seem to be broken:

[AWS VPC Flow Logs](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations/docs/integrations/amazon-integrations/aws-integrations-list/aws-vpc-flow-logs-monitoring-integration)

[AWS CloudFormation](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations/docs/integrations/amazon-integrations/aws-integrations-list/aws-cloudformation-integration)[](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations/#cloudwatch-billing)

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/introduction-aws-integrations/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 97.0.4692.99
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for reporting this, @silentrunner888! We'll fix it in #6332.
