### ISSUE TITLE
Issue: Install containerized private minions (CPMs)

### ISSUE THREAD

**Issue by maramaculmendes** [newrelic/docs-website#6342]
Kubernetes Install

CPM is by default too small to even complete the healthcheck that starts at creation.
Need to update documentation (or Helm chart) to increase the limit and request resources on the statefulSet in the namespace.

resolution was to go into the statefulSet config and increase the cpu and memory amounts (cpu to 1 and memory to 4G), perform a rolling restart of the statefulSet and let the pods regenerate and try again.

found solution from https://newrelic.zendesk.com/hc/en-us/articles/360059505673-Kubernetes-CPM-seeing-frequent-restarts-of-synthetic-minions-on-GKE

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/private-locations/install-containerized-private-minions-cpms/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Kubernetes

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
