### ISSUE TITLE
Freeze table headers as you scroll

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#6346]
### Issue:
I was recently reading a doc that had a very long table. By the time I reached the row that contained the info I wanted, I forgot which column was which, so I had to scroll all the way back up and then down again. 

### Ask:
**It would be really nice if we froze the headers as you scroll down so they follow you along until the end of the table.** 

### Examples:
Google Sheets do this VERY well, see the attached screenshots. They may be a bit unclear, so please let me know if this doesn't make sense

Start of table:
<img width="614" alt="Screen Shot 2022-02-25 at 3 10 23 PM" src="https://user-images.githubusercontent.com/42678939/155815261-714b4722-a5fe-4ce8-b314-c7a5c3a058c7.png">

End of table (note that the column #s:
<img width="612" alt="Screen Shot 2022-02-25 at 3 12 14 PM" src="https://user-images.githubusercontent.com/42678939/155815367-c9306675-c100-457d-ace4-1f9034cfd36a.png">

**Comment by roadlittledawn** [comment]
closed in favor of jira
