### ISSUE TITLE
Link on page under image is goes to a 404

### ISSUE THREAD

**Issue by alyssamazz** [newrelic/docs-website#6355]
## How can we make our docs better?
The link under the picture is broken.  

The cards/boxes with info and links should match the intention of the left navigation.  There should be an introductory page for each menu with a  drop-down to provide consistency for the section, like the one for OM.   Each navigational top menu element ought to have introductory info to help the user understand what they should expect.  Linking into examples from the landing page is a bit confusing, as some go right into an example.  If they went to an intro page about what they will find in the section, it would provide a good framework on how to consume the doc. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/overview
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.102
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
This is great feedback, @alyssamazz - I've created a jira (DOC-7792) to implement these changes. Thanks!

**Comment by urbiz-nr** [comment]
Closed via #6471.
