### ISSUE TITLE
image file names are sent for translation

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#6365]
## Description

a couple image files names were sent for translation (on a small drop). crop-cosmetic-label-hostname.png for src/content/docs/apm/agents/manage-apm-agents/configuration/add-rename-remove-hosts.mdx
net-config-precedence-core.png for src/content/docs/apm/agents/net-agent/configuration/net-agent-configuration.mdx

## Steps to reproduce

1. In the translation tool the strings appear among the project.

## Expected behavior

image names should not be sent for translation.

## Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by jpvajda** [comment]
We talked about this one and decided to put it into the docs eng backlog.
