### ISSUE TITLE
Issue: Incident Intelligence destination examples - Collapsers are broken.

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#6366]
## How can we make our docs better?

The collapsers on the page are broken.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/incident-intelligence-destination-examples/
* **OS**: Mac
* **Browser**: Chrome
* **Device**: MBP

**Comment by paperclypse** [comment]
@jmiraNR This doc's file has been deleted from our repo and removed from the relevant nav file. I'm not sure what's up. I've reached out to the eng team for help with this one.

**Comment by paperclypse** [comment]
This is a caching issue. The engineering team is looking into it. I'm going to update the labels to reflect that and pull it off the docs board.

**Comment by roadlittledawn** [comment]
this page shouldn't exist anymore. next time cache is cleaned this page will go away

**Comment by pizzaz93** [comment]
Navigating to this page currently returns `Hmm... We can't find this` it seems the cache has cleared this page.
