### ISSUE TITLE
Issue: Networks

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#6372]
## How can we make our docs better?

domains for codestream is missing.
maybe "**api.codestream.com**" shall be added network for codestream.
If there are any other domains used by codestream, please add them.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/networks/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.109
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for letting us know, @shinji-newrelic! I'll sync with the team and update the doc.

**Comment by urbiz-nr** [comment]
Domains added in #6386.
