### ISSUE TITLE
broken layout/styles

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#6387]
## How can we make our docs better?

It is show with suitable styles/layouts in Solution block if I check with english version. However just text without some styles/layouts (bold, anchor, highlights, tables...).
Please apply suitable style/layout to Japanese page also.

Thanks.

### Doc information (don't delete this section)

* https://docs.newrelic.com/jp/docs/infrastructure/infrastructure-troubleshooting/troubleshoot-logs/generate-logs-troubleshooting-infrastructure/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.109
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @shinji-newrelic! Thanks for letting us know. I contacted the localization team about the issue. I'll update you as soon as I hear from them.

**Comment by jmiraNR** [comment]
@roadlittledawn No sure where the formatting went. Happy to investigate with you.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
