### ISSUE TITLE
Can't find Synthetics API SLA endpoints

### ISSUE THREAD

**Issue by diogobaeder** [newrelic/docs-website#6400]
## How can we make our docs better?

* Is something confusing? Yes: I'm not finding how to get SLA report data via the Synthetics API
* Is something inaccurate or missing? Yes: I'm not finding how to get SLA report data via the Synthetics API
* Were you unable to complete a task? (What task?) I need to integrate the New Relic Synthetics SLA report data into my app, but I can't find any endpoint that could give me that - I only found endpoints to list monitors, get a specific monitor etc, just management stuff, but nothing about fetching data for daily/weekly/monthly uptime figures.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/synthetics-rest-api/monitor-examples/manage-synthetics-monitors-rest-api
* **OS**: Arch Linux x64
* **Browser**: Firefox 97.0
* **Device**: Desktop

**Comment by barbnewrelic** [comment]
@diogobaeder  I think this doc is the one you were looking for. https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics/  I'll add a cross reference in the REST API doc so that it's not so confusing. Hope this helps!

**Comment by barbnewrelic** [comment]
@diogobaeder  I also found a doc https://docs.newrelic.com/docs/apis/synthetics-rest-api/monitor-examples/payload-attributes-synthetics-rest-api that mentions the `slaThreshold` value, but it links to the UI doc, not to a REST API example. I'll check with our engineers to see if they can add a specific SLA example to the Synthetics API doc.

**Comment by diogobaeder** [comment]
Thanks a lot, @barbnewrelic ! Yeah, I've seen those pages, nothing mentioning specific endpoints for accessing SLA data via the API, unfortunately... thanks for checking with your devs, that will be immensely helpful for us in YouGov! :-)

**Comment by barbnewrelic** [comment]
I'm glad you're getting immediate help with this issue!

**Comment by diogobaeder** [comment]
I ran the same query today, but using `SINCE` and `UNTIL` pointing to those dates, and now I'm getting expected results. So I'm not sure what happened, but I'm happy that at least the numbers match now :-)

Should I close the ticket now? Or keep it open for further investigation?

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
