### ISSUE TITLE
Issue: Navigate the Kubernetes cluster explorer (icon not visible in dark mode)

### ISSUE THREAD

**Issue by egironanr** [newrelic/docs-website#6418]
## How can we make our docs better?

Pod icon is barely visible in dark mode.
![image](https://user-images.githubusercontent.com/100843681/156554952-f8991e5b-01cc-484a-a22a-20fb47b9f58a.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/kubernetes-cluster-explorer
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.109
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @egironanr! Thanks for letting us know. I'll replace it for another image.

**Comment by x8a** [comment]
I fixed it in PR #6421. Thanks for filing the issue!
