### ISSUE TITLE
Search for Observability maturity

### ISSUE THREAD

**Issue by alyssamazz** [newrelic/docs-website#6424]
If you search for Observability maturity, while the auto-selection gives you the correct page to navigate to, if you just select enter you are taken to this page - https://docs.newrelic.com/docs/distributed-tracing/infinite-tracing/set-trace-observer.  I know the OM team wants the search to return people to this page - https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/introduction/

thanks for your help.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/introduction/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.102
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for reporting this @alyssamazz! I have updated the rankings and this should now be fixed.
