### ISSUE TITLE
Issue: Query Pixie data

### ISSUE THREAD

**Issue by jake-codes** [newrelic/docs-website#6427]
[Pixie Docs - Querying your data ](https://docs.newrelic.com/docs/kubernetes-pixie/auto-telemetry-pixie/auto-telemetry-pixie-data-model#metrics-and-specifications)

Are these all of the metrics that customers can query from Pixie or just a couple examples? If these are just a couple examples, can we please add a list of the entire set of metrics collected. It would be a barrier to require folks to have expert use of the query builder to see which metrics are available to them if they are coming to the docs for help. 

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/auto-telemetry-pixie/auto-telemetry-pixie-data-model
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.109
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey @jake-codes, thanks for bringing this up! I believe that these are not the a complete list. I will confirm that, and then see what we can do about beefing this doc up. Thank you!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
