### ISSUE TITLE
Issue: AWS CloudTrail monitoring integration

### ISSUE THREAD

**Issue by Nestor10** [newrelic/docs-website#6429]
## How can we make our docs better?
* Is something inaccurate or missing?

* [Connect AWS services to New Relic](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-cloudtrail-monitoring-integration/docs/infrastructure/infrastructure-integrations/getting-started/connect-aws-integrations-infrastructure) link broken

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-cloudtrail-monitoring-integration/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.109
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey there @Nestor10 , thanks for reporting this! I will fix this right away.
