### ISSUE TITLE
Add docs site instrumentation for right pane navigation links

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#6440]
## Is your feature request related to a problem? Please describe

We would like to know more about how users interact with the right navigation pane on the docs site. 

## Describe the solution you'd like

Please instrument the right navigation pane so we can start gathering data about its usage. Would this require Tessen events?

## Describe why this important to you

We want to determine whether we should migrate these page headings over to the left navigation pane if users are not seeing them in the right pane.

**Comment by roadlittledawn** [comment]
we have this info in `PageAction` events. ask Clinton for info
