### ISSUE TITLE
[i18n] Improve monitoring for translation workflows

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/docs-website#6441]
## Summary
@jmiraNR reached out about wanting to know about failures that occur during the translation process, and perhaps even personally inspect some of the files. At the moment, we do log the failures, but it's just to console. Aside from logging them, the failures are not surfaced so the workflow still "passes" in the UI. To actually observe failures, you have to specifically look for them in the logs after a workflow has run.

We should probably have some kind of reporting into New Relic which can easily show this information.

As a rough, first pass checklist, we should report:
- [ ] files that fail to send / be uploaded
- [ ] files that fail to deserialize from vendor
- [ ] submission count for jobs

## Acceptance Criteria
- [ ] TBD

**Comment by roadlittledawn** [comment]
aside from any i18n workflows, we should consider monitoring:
* [whats-new](https://github.com/newrelic/docs-website/actions/workflows/update-whats-new-ids.yml)

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-21
