### ISSUE TITLE
Issue: Introduction to the C SDK

### ISSUE THREAD

**Issue by frahoi** [newrelic/docs-website#6450]
This page needs a link to how to download/compile/install the actual C-SDK package and library.   The section that promises this under 
"Get started with the C SDK" ... 
  "or follow the [installation and instrumentation procedures](https://docs.newrelic.com/docs/install-c-sdk-compile-link-your-code) to install the agent" is a DEAD END - it does not tell me how to install the agent.  It tells me how to use the agent libraries.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/c-sdk/get-started/introduction-c-sdk/
* **OS**: Windows 10
* **Browser**: Firefox 91.0
* **Device**: Unknown

**Comment by frahoi** [comment]
The text below that demonstrates one way to do this would be *very* helpful:

# yum install go  # NOTE: 'go' is required to build.
# mkdir /opt/newrelic

# cd /opt/newrelic
# git clone https://github.com/newrelic/c-sdk
# cd c-sdk
# make > make.out 2>&1&

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
