### ISSUE TITLE
Issue: REST API for applied intelligence

### ISSUE THREAD

**Issue by RoiBar1** [newrelic/docs-website#6453]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/rest-api-applied-intelligence/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.102
* **Device**: Unknown

Need to replace this doc with this new REST API doc
https://docs.newrelic.com/docs/data-apis/ingest-apis/event-api/incident-event-rest-api/

**Comment by RoiBar1** [comment]
@paperclypse 
Any idea why we holding this down

**Comment by pizzaz93** [comment]
https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/rest-api-applied-intelligence/ now redirects to https://docs.newrelic.com/docs/data-apis/ingest-apis/event-api/incident-event-rest-api/
