### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by kinetiq** [newrelic/docs-website#6456]
Super skeptical about New Relic now, because Azure feels like a 3rd class citizen to the point that the docs don't exist.

I had to dig pretty deep to find it at all, and ultimately the installer took me there: https://docs.newrelic.com/docs/agents/net-agent/azure-installation

And that's a 404. 

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/404/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by kinetiq** [comment]
I eventually found this: https://docs.newrelic.com/docs/apm/agents/net-agent/azure-installation/install-net-agent-azure-web-apps/

It hasn't been called 'web apps' in years. I'm out. :)

**Comment by paperclypse** [comment]
Hey @kinetiq, sorry the docs didn't meet your needs! You might try our instant observability page: https://newrelic.com/instant-observability/?search=azure&category=azure

Or maybe that's where you started?

I'll fix the 404 and see what we can do about improving these Azure docs. Thanks for the feedback!

**Comment by kinetiq** [comment]
Thanks, that is helpful. I went through all the steps (FYI: these docs are also a little out of date here and there, but it is workable) and at the end, I got an error saying to try again later. 

Created a ticket here: https://discuss.newrelic.com/t/errors-when-trying-to-set-up-azure-integration/178433

**Comment by kinetiq** [comment]
Also... .Net APM in Azure App Services is really what I'm primarily after. The document you linked me to says at the top that this process is not the same as APM, and links to the same broken 404 document mentioned above. At this point I am pretty confused and frustrated. I would love to open a support ticket but I can't find a way to do anything other than the community link above.

**Comment by paperclypse** [comment]
Thanks for following up @kinetiq! We'll send this by the appropriate team so that we can get some experts thinking about how to improve these docs.

**Comment by paperclypse** [comment]
@kinetiq You might be pleased to know that we've had a big, new release related to Azure. Check it out! https://docs.newrelic.com/docs/infrastructure/microsoft-azure-integrations/get-started/azure-native/
