### ISSUE TITLE
Issue: NRQL math using SELECT with string concatenation

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#6462]
I want a billboard that I have thats showing memory utilization as "80" to report it as "80%".  I tried these and get syntax errors.
```
SELECT  round(latest(memoryWorkingSetUtilization)) + '%'  as 'memory utilization' from K8sContainerSample where clusterName = '<clusterName>' AND containerName = '<containerName>' 
SELECT  latest(memoryWorkingSetUtilization)  + '%' as 'memory utilization' from K8sContainerSample where clusterName = '<clusterName>' AND containerName = '<containerName>' 
```
Also setting the data format type to be number didnt work. 

Is there a `string()` function like there is for number and boolean?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-math-using-select/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @StingyJack! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.

**Comment by StingyJack** [comment]
@x8a  - I asked a question about something I cant find in the documentation.  

> Is there a string() function like there is for number and boolean?
