### ISSUE TITLE
Issue: NGINX monitoring integration - Does Not List Sample Data / Attributes

### ISSUE THREAD

**Issue by jake-codes** [newrelic/docs-website#6465]
Hi, I cannot find the sample data collected by NGINX on this page. Please let me know if I missed it. Otherwise, this is definitely something that should be added so customers know whether or not it's worth it for them to spend the time installing it.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.109
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @jake-codes! Did you check the [configuration doc](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-advanced-config)? We moved all that information to another doc.

**Comment by x8a** [comment]
Hi, @jake-codes! As we discussed, I'll be making the changes to these docs in the next few days. Thanks again for reaching out!
