### ISSUE TITLE
[Frontmatter] Update `translate` jp value to conform to standard

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#647]
## Summary
Currently we use the country code `jp` to indicate a file should also be translated to Japanese. This could be misleading and in the case of Smartling's API, we need to follow a standard that specifies the language code and country code.

At very least we may just want to update `jp` (which is country code) to `ja` (which is the language code). I think, technically, since we are targeting Japan, we could use the combo of language and country code: `ja-JP`.

Smartling expects either just the language code (`ja` for universal) or language and country code (`ja-JP` for Japanese in Japan). See link below for how to get a list of supported codes.

## Acceptance criteria
- [ ] On migration, all pages that have `translate: jp` are updated to the standard above
- [ ] As a content contributor, I know what code to use if a new language is added (add documentation to readme on what our standard / convention is?)

## Helpful links
* [List of ISO-639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)
* [List of ISO-3166 language codes](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes)
* [Smartling API endpoint for supported locale data](https://api.smartling.com/locales-api/v2/dictionary/locales)

**Comment by jpvajda** [comment]
We discussed this one and removed it from our scope of the new site launch as we can handle this change when we take on a country that needs both country code + language code, (ex: switzerland / french). We currently have a process in place that converts `jp` to `ja-JP` so smartling can handle the translation request. So when we tackle another language site we can consider correcting this.

**Comment by jpvajda** [comment]
We will consider this change...when we take on our next localized country
