### ISSUE TITLE
Issue: Automap for troubleshooting entities

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#6470]
## How can we make our docs better?

I opened the Service Map for one of our apps and was shown a banner about automap
![image](https://user-images.githubusercontent.com/15381181/156909270-c390da15-8570-4290-a8ca-b47871c3acdd.png)

But I dont see where automap is on the Service Map screen, or near it in the left menu for the app.   Reading the documentation page (more than once) says this is actually available via the summary page, Why wouldnt I be shown the banner on the Summary screen? 

This is probably not a documentation issue. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/use-new-relic-one/ui-data/automaps/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @StingyJack! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.

**Comment by StingyJack** [comment]
But the actions bot says it will transfer to the appropriate team.Why isn't that happening?
