### ISSUE TITLE
Review RestSharp content optimization

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#6475]
Hi team! Thank you for reviewing this. 

SN recommended optimization for RestSharp: https://docs.google.com/document/d/1zZhHRNHwLKoPO2tx8LlO3VE_patyWitFxXE4dUuZTCw/edit#heading=h.wfeszxbfmgy0

Please review and make edits as needed.

**Comment by paperclypse** [comment]
I've finished reviewing this @aliandersonsn. Thanks!
