### ISSUE TITLE
Issue: Alerts and applied intelligence transition guide

### ISSUE THREAD

**Issue by edwalshd** [newrelic/docs-website#6482]
Image in this section has dark lines across it when viewing the docs using the dark theme:
https://docs.newrelic.com/docs/alerts-applied-intelligence/transition-guide/#nav-changes

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/transition-guide/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 98.0.4758.102
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @edwalshd! Thanks for noticing this! I fixed it in PR #6485.
