### ISSUE TITLE
Issue: Data requirements and limits for custom event data

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6488]
Use of the term 'characters' in this limit description is confusing.  Is it bytes or is it UTF-16 characters.  I'm pretty sure it is bytes.

> Attributes attached to custom events sent using the [Event API](https://docs.newrelic.com/docs/insights/insights-data-sources/custom-data/send-custom-events-event-api): 4096 characters

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/custom-data/custom-events/data-requirements-limits-custom-event-data/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Note that this is also mentioned in https://docs.newrelic.com/docs/data-apis/ingest-apis/event-api/introduction-event-api/#limits.

**Comment by GaPeppy** [comment]
These docs are waffling between saying bytes and characters ... note they are not the same.  NR should be more explicit.

**Comment by rhetoric101** [comment]
@GaPeppy I just had a discussion with SMEs on the TDP team, and they confirmed that the size of the attributes sent using the Event API is, in fact, 4096 characters. If you are an employee of New Relic, and want to join the discussion, I invite you to Slack us and we can tell you how.

**Comment by zuluecho9** [comment]
I did some work in https://github.com/newrelic/docs-website/pull/6856. Thanks again.
