### ISSUE TITLE
Change the "tip" callout component styling to look more like the old Doc site tips

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#649]
This is to change the global component for tips to look closer to the Old Docs Site tip styling as that was approved and championed by Lew. So to  align with his concern for how we present tips, we'll just go back that original style. The callout needs to match the existing callout as closely as possible, I'd still suggest we maintain the current color palette for consistency.

### Tip Styling:

- add the full border (thick border on the left, thin border on the top, right, and bottom) and leave the rest of the component the same. 
- the tip title should be the same color as the wider border line
- the tips background color should be a shade of the border line. 
- ensure both light and dark mode are considered.
- ensure we apply this style to all [callout variant types](https://github.com/newrelic/gatsby-theme-newrelic/blob/develop/packages/gatsby-theme-newrelic/src/components/Callout.js) 

<img width="868" alt="Screen Shot 2021-01-25 at 7 22 00 PM" src="https://user-images.githubusercontent.com/1395158/105791212-e470a580-5f42-11eb-889d-1eda0119cc05.png">

<img width="923" alt="Screen Shot 2021-01-25 at 7 22 09 PM" src="https://user-images.githubusercontent.com/1395158/105791224-e8042c80-5f42-11eb-8989-fcd29cbc91ad.png">

### New design  that we need to change 
![Screen Shot 2021-01-25 at 7 24 55 PM](https://user-images.githubusercontent.com/1395158/105791361-2d285e80-5f43-11eb-9e8c-e40a352e0de0.png)

![Screen Shot 2021-01-25 at 7 25 50 PM](https://user-images.githubusercontent.com/1395158/105791368-30bbe580-5f43-11eb-80ed-2490c2ddd454.png)

![Screen Shot 2021-01-25 at 7 41 33 PM](https://user-images.githubusercontent.com/1395158/105792855-5cd86600-5f45-11eb-9c82-e760a42143d8.png)

![Screen Shot 2021-01-25 at 7 41 37 PM](https://user-images.githubusercontent.com/1395158/105792866-5ea22980-5f45-11eb-94b9-3975f5df8d68.png)

**Comment by jerelmiller** [comment]
We'll need to see if we can get a dark mode style for those "old style" tips.

**Comment by jpvajda** [comment]
@jerelmiller yeah good call, perhaps @djsauble can make a recommendation, currently we just flip the background color to be a shade darker then the site background color, we could probably lighten those up to be closer to the border colors of the tips boxes. I think we can take the original tip and just add a little color to it for both modes so it has a little bit of "pop" and stands out in both modes.

**Comment by djsauble** [comment]
I wasn't in those conversations with Lew, so I don't know what exactly he cares about. However, my thinking is that we could just add the full border (thick border on the left, thin border on the top, right, and bottom) and leave the rest of the component the same.
