### ISSUE TITLE
Add Docs content type templates

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#65]
## Summary

In Drupal, there are several templates that we use to guide people (both on our team and outside of it) in writing specific types of content. (You can see most (all?) of them here: https://docs.newrelic.com/node/add)

For example, the Troubleshooting template has specific fields for Problem and Solution and Cause. What's New (or NR1 Announcement) has specific fields for including Learn more and Get started links.

We were wondering if these templates were being discussed and, if not, we wanted to raise awareness about them.

We were thinking it might be great to have some kind of CLI tool to generate blank Docs templates. Maybe there's even some more elegant solution we haven't thought of!

The current templated content types are:

- Add basic page
    - Use basic pages for most documentation.
- Add article
    - Use articles for time-sensitive content like news, press releases or blog posts.
- Add book page
    - Books have a built-in hierarchical navigation. Use for handbooks or tutorials.
- Add release notes
    - This is an article type with additional fields for release notes.
- API doc
    - This content type is used to document API calls in a given category (for example, PHP agent API). Each method has its own front-end page and the menu page displays a specially formatted page with all the calls. https://newrelic.atlassian.net/browse/DOC-2653
- Attribute Definition
    - This content type is for New Relic event attribute definitions. This content is displayed on the site and is consumed by the Insights team and displayed in the UI as the attribute dictionary service. For full details see https://newrelic.atlassian.net/browse/DOCCMS-92
- Automated release notes
    - This content type is for auto-generated release notes.
- NR1 Announcement
    - For content exposed via API to PLG What's New content. https://newrelic.atlassian.net/browse/DOCCMS-274
- Platform Release Notes
    - For SaaS-based release notes. For full details, see https://newrelic.atlassian.net/browse/DOC-3815
- Troubleshooting Doc
    - This content type is used to document troubleshooting information. https://newrelic.atlassian.net/browse/DOC-3398
- Webform
    - Create a new form or questionnaire accessible to users. Submission results and statistics are recorded and accessible to privileged users.

## Desired Behavior

According to @roadlittledawn: 

_"some fields in the various content types are authored in HTML, which isn’t really supported / intended to be in frontmatter. so those fields will likely all have to be combined into the markdown file body. example: the problem, solution, cause fields for the troubleshooting_doc content type.
other fields (like categories, timestamps, links, etc), will be migrated and stored as frontmatter.
i like the idea of a simple script you could run to create a template for each content type, or some such tooling."_

I think, ideally, we'd have a simple CLI script that we could run to generate a mostly MDX file with frontmatter and Markdown body text pre-populated. It would be nice to include Notes and Tips for writing templated content (sort of like this enhancement request). 

## Possible Solution

I don't really know the publishing process well enough to suggest a possible solution and there may be Gatsby features and functionality that I'm not aware of too.

## Additional context

Without standard templates for content, we run the risk of having writers reinvent the wheel or create content that veers of slightly from what we expect to see in our templated content.

**Comment by theletterf** [comment]
This is a great one, @paperclypse. Hugo has built-in templates, which are a breeze to customize and can be generated from the CLI (see https://gohugo.io/templates/). Not so sure about Gatsby...

**Comment by austin-schaefer** [comment]
Stalebot closed this while Shawn was on PTO, but I'd still like to implement this.

**Comment by jerelmiller** [comment]
This is more-or-less implemented. We do plan to add some documentation for the different templates and the supported frontmatter.

As far as creating new templates, its a bit trickier in this world. Templates are now React components and work inside the Gatsby ecosystem. Its likely something that might be more on the advanced end for the casual content contributor. If we need to spin up new templates we'll likely need to involve the engineers in the short term.
