### ISSUE TITLE
Issue: Login and password issues

### ISSUE THREAD

**Issue by MREED312** [newrelic/docs-website#6518]
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems/
* **OS**: Windows 10
* **Browser**: Edge
Our instance uses SSO. My AD account name has just changed and no longer allows a login as it doesn't match the email/account on the NewRelic platform. What is the best way to resolve this issue?

**Comment by x8a** [comment]
Hey, @MREED312! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
