### ISSUE TITLE
Issue: Step 4: Instrument your own Lambda functions

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6519]
To the best of my knowledge and based on past conversations; Cloudwatch-logging for telemetry upload is not a **deprecated** upload option.  It would be helpful in the documentation, that NR drew out the two telemetry upload options as equal.  I realize there is an engineering product bias for Lambda Extension; but these are two different choices with different tradeoffs:

* buffer telemetry into Lambda Extension for periodic harvest and upload
* serialize telemetry to Cloudwatch Logging and extract & forward telemetry through downstream Lambda function

Actually it would be nice that NR documented the tradeoffs of the two approaches.  The fact that the product line defaults to one of these options is fine.  But let's articulate the options clearly.

> As [mentioned previously](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/architecture#cloudwatch) we used to recommend sending your telemetry through CloudWatch Logs. This path can still work, though it is **deprecated**.

There have been conversations that the Cloudwatch logging path is still a viable/supported path for customers who do not want the potential latency delay of the Extension architecture.

i.e.
> The Invoke phase ends only when the Lambda runtime and all the extensions have signaled that they’re finished. Once again, if an extension is performing a long-running task then it can add delay to an invocation’s duration.

In the ephemeral world of Lambda, a remote call to the internet is 'a long-running task' and the customer lambda function will be held up until the remote call succeeds or timesout.

https://lumigo.io/blog/aws-lambda-extensions-what-are-they-and-why-do-they-matter/

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@GaPeppy  Thank you for your thoughtful comments and suggestions! We will forward your issue to expert engineers for additional thoughts about how to resolve your issue.

**Comment by zuluecho9** [comment]
A note: I passed this criticism to a lead in the serverless area, and also a related request that Lambda should have release notes (for learning about changes like this).

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
