### ISSUE TITLE
Issue: Introduction to New Relic for .NET

### ISSUE THREAD

**Issue by kinetiq** [newrelic/docs-website#6528]
## How can we make our docs better?
The experience of onboarding as a .NET dev using Azure App Services has been pretty rough. I actually tried this once before and decided to go with a competitor because at a glance, the docs seemed to be all over the place for App Services...  And it is true. At this point I went out and tried Raygun and Dynatrace instead, both of which have much cleaner instructions. Raygun actually had a dev meet with me to answer some questions, but they aren't ready for .NET 6 on App Services. So here I am trying New Relic again, and just wishing this part of the experience was better.

New Relic is actually the better product for what I'm doing, and I've used it before, _and_ the setup is actually not that hard, however I think what's happened is you have (a) a difficult problem because .NET has tentacles everywhere and (b) 10+ years of documentation that has had to evolve.  If you try to skim the documentation the way it's written, which is what devs do, you will get into trouble because there are often multiple options but they skim like you have to do all of them. Some aspects of the docs are out of date. The existence of a guided setup that doesn't know how to handle my scenario and gives me bad advice is very confusing. Then actual errors like this one take it from "this is a little more confusing than it has to be" to "OMG clearly nobody cares about .NET here, nobody from their team could have actually tried to use this documentation in years, I need to try something else". 

* Is something confusing?
* Is something inaccurate or missing?
On https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/introduction-new-relic-net

Under Browser instrumentation, if you click on the option for API method it takes you to a random page: https://docs.newrelic.com/docs/apm/agents/net-agent/net-agent-api/getbrowsertimingheader-net-agent-api/

* Were you unable to complete a task? (What task?)
After installing the extension, I need to manually report exceptions. Eventually I figured out that, from the 4 nuget packages you have that seem like possible matches, I need NewRelic.Agent.Api... Is that all I need? Why isn't the agent a dependency? If I install the agent and I also have the extension running, will that cause a conflict?! I still don't know. I am now just trying to set it up and having a hard time figuring out what I need to do to set the API key, which seems bizarre.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/introduction-new-relic-net
* **OS**: Windows 10
* **Browser**: Chrome 99.0.4844.51
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@kinetiq  Thank you for all your thoughtful comments! I am forwarding this to our engineers for additional research and action.

**Comment by kinetiq** [comment]
Thanks, and please don't miss the actual error that's hidden in there.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
