### ISSUE TITLE
Issue: Elasticsearch monitoring integration

### ISSUE THREAD

**Issue by otteydw** [newrelic/docs-website#6532]
https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration/

This page has some "links" to event types which don't actually open/expand or go anywhere

- [ElasticsearchClusterSample](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration/#elasticsearch-cluster-metrics)
- [ElasticsearchNodeSample](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration/#elasticsearch-node-metrics)
- [ElasticsearchCommonSample](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration/#elasticsearch-common-metrics)
- [ElasticsearchIndexSample](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/elasticsearch/elasticsearch-integration/#elasticsearch-index-metrics)

I would expect these clickable links to expand with more info, or to link off to some other page with that info.

**Comment by barbnewrelic** [comment]
@otteydw  Thanks for pointing this out! I've updated this section with the correct links that are in a separate doc.
