### ISSUE TITLE
Broken hyper link in description of organization manager role on NR1 user management concepts page

### ISSUE THREAD

**Issue by stowelll** [newrelic/docs-website#6537]
## How can we make our docs better?

https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts/#standard-roles

In role "organization manager" hyperlink on word "organization" in description is a broken link.

Link is https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-users/new-relic-account-structure/-level , unsure where it's trying to send.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-management-concepts/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Fixed with https://github.com/newrelic/docs-website/pull/6539. Thanks @stowelll
