### ISSUE TITLE
[In Product Help XP] a search term "applications" is returning error message

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#655]
### Steps to Reproduce

- Goto one.newrelic.com and enter the help system.
- Type in "application"  (works ok)
- Typie in "applications" and... "Oops! Something went wrong!"

![image](https://user-images.githubusercontent.com/1395158/105908935-18e86e00-5fe4-11eb-9917-ad15be0badec.png)

### Expected 

- the search term  applications returns results similar tot he application term

**Comment by jerelmiller** [comment]
This was fixed and deployed to all environments
