### ISSUE TITLE
Issue: Compatibility and requirements for the Java agent

### ISSUE THREAD

**Issue by sdbedi** [newrelic/docs-website#6561]
## How can we make our docs better?
According to this Doc, the latest version of the agent supported for Java 7 is 6.5.3.
However, per release notes, 6.5.4 is Java 7 compatible. 

I'm happy to edit the doc, but just wanted to bring this to attn.
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Fixed in https://github.com/newrelic/docs-website/pull/6560
