### ISSUE TITLE
[Docs Eng] Setup Pager Duty for team

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#6567]
The new account will be created by the teamstore ticket #6568 

To setup the new docs eng team we need to do the following in pager duty

- [x] Create new team and setup rotation for docs eng
- [x] add alert policies for new docs eng account from NR1 
- [x] Remove Docs Eng engineers from DevEn team

**Comment by clarkmcadoo** [comment]
I'm on call next week for stuff, so I didn't want to remove myself from DevEn just yet.
