### ISSUE TITLE
Issue: Amazon RDS monitoring integration

### ISSUE THREAD

**Issue by shhudspethnr1** [newrelic/docs-website#6570]
## How can we make our docs better?

*** Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)**

A customer is trying to get the Enhanced RDS Integration dashboards and could not find them. Are we redirecting folks to the Entity explorer to see data, metrics, and OOTB dashboards?  When following the instructions here, they do not see any RDS dashboards under the Infrastructure>>AWS >> tab. Happy to pass along customer screenshots showing how dashboards are no longer there and are now elsewhere! 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-rds-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Going to close this. We talked about this with SMEs and tech writers and are looking into solutions.
