### ISSUE TITLE
Issue: Amazon RDS monitoring integration

### ISSUE THREAD

**Issue by shhudspethnr1** [newrelic/docs-website#6571]
## How can we make our docs better?

*** Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)**
Forgot to add the confusing, inaccurate text that does not get customer to their RDS data (can't complete a task)

_Find and use data
To find your integration data, go to [one.newrelic.com](http://one.newrelic.com/) > Infrastructure > AWS and select one of the RDS integration links.

You can [query and explore your data](https://docs.newrelic.com/docs/using-new-relic/data/understand-data/query-new-relic-data) using the DatastoreSample [event type](https://docs.newrelic.com/docs/insights/use-insights-ui/getting-started/introduction-new-relic-insights#event-type), with a provider value of RdsDbInstance for DB instances, or RdsDbCluster for Aurora DB clusters.

For more on how to use your data, see [Understand and use integration data](https://docs.newrelic.com/docs/infrastructure/integrations/find-use-infrastructure-integration-data)._

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-rds-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Going to close this. We talked about this with SMEs and tech writers and are looking into solutions.
