### ISSUE TITLE
Issue: Node.js agent configuration

### ISSUE THREAD

**Issue by BobbyKostadinov** [newrelic/docs-website#6579]
Web description of 

`NEW_RELIC_ERROR_COLLECTOR_IGNORE_ERROR_CODES`

differs from Github https://github.com/newrelic/node-newrelic/blob/d5541da185332273d8a2b9bc1417a3d88a9ea745/README.md#configuring-the-module

Supplying comma-separated values worked, arrays did not so it would seem the web page is wrong saying [401] is accepted value here

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
