### ISSUE TITLE
Issue: NerdGraph tutorial: Export dashboards as files

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#6580]
## How can we make our docs better?

The (i) Icon no longer exists, the user needs to click the tag icon now.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-dashboards-pdfpng-using-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for reporting this! I fixed it with PR #6582.
