### ISSUE TITLE
Issue: Organize data with partitions

### ISSUE THREAD

**Issue by disqodesiree** [newrelic/docs-website#6592]
## How can we make our docs better?

In the first steps of this doc, it tells the reader to ensure they have the correct permissions and a partition plan but doesn't reference what those are.
[https://docs.newrelic.com/docs/logs/ui-data/data-partitions/#plan](url)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/ui-data/data-partitions/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 99.0.4844.51
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks @disqodesiree. I'll work on that in https://github.com/newrelic/docs-website/pull/6594.
