### ISSUE TITLE
Please review "synthetic link crawler" content

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#6603]
Please review the recommended updates for the synthetic link crawler IO page: https://docs.google.com/document/d/1B4UTEAaTUJTM8waWP4J1agHil8lc1Xe48hykpad8H3U/edit

Provide any feedback you find necessary and we'll make the final edits. 

Thank you!

**Comment by rhetoric101** [comment]
@aliandersonsn, I inserted some suggestions in the Google doc. I'm afraid I haven't received much training on how to provide helpful feedback for quickstarts, so my comments may be confusing and unhelpful. If you would like feedback from another member of our team, let me know, and I can see if they could offer helpful suggestions.

**Comment by rhetoric101** [comment]
I am closing this issue.
