### ISSUE TITLE
Review Azure virtual network IO page

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#6604]
Please review the updates recommended for the[ Azure virtual network quickstart](https://docs.google.com/document/d/1HcZK-2YxGFSyTeSQ2J3OVc9VuQYLNoyt0yRs5tUDSPI/edit#heading=h.cycycwptxdba)

I will review any feedback and make the final edits as requested. Thank you!

**Comment by rhetoric101** [comment]
@aliandersonsn, I inserted some suggestions in the Google doc. I'm afraid I haven't received much training on how to provide helpful feedback for quickstarts, so my comments may be confusing and helpful. If you would like feedback from another member of our team, let me know, and I can see if they could offer helpful suggestions.

**Comment by rhetoric101** [comment]
I am closing this issue.
