### ISSUE TITLE
Issue: Muting rules: Suppress notifications

### ISSUE THREAD

**Issue by deedeeshaw** [newrelic/docs-website#6610]
## How can we make our docs better?

* Were you unable to complete a task? (What task?)
* I was unable to create my muting rule because in the Build violation filter section there is only the option to pick "and" or "or for all the following sub conditions. For example the rule I want to create is something like this:
* policyName contains abc
* And
* policyName contains def
* And
* conditionName contains xyz
* Or
* conditionName contains pqr 

*However, I can only pick "and" or "or" for all the sub conditions.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications
* **OS**: Windows 10
* **Browser**: Edge 99.0.1150.39
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
