### ISSUE TITLE
Run image codemod on develop on `Apr 4, 2022 @ ~10AM PST`

### ISSUE THREAD

**Issue by josephgregoryii** [newrelic/docs-website#6613]
## Summary

Now that the work for image alias is set in place with a new image codemod, we want to run the codemod on develop to update all `mdx` files to modify the changes. 

Reference to codemod's PR can be referenced here: https://github.com/newrelic/docs-website/pull/6412

Feature is on branch `feature/image-alias-codemod`

## Acceptance Criteria

- [ ] Update feature branch with current and up to date version of develop
- [ ] Notify the Doc's content team to pause their work until these changes are addressed
- [ ] Run the image codemod on the branch and ensure it builds both in Gatsby Cloud and locally
- [ ] Once we get a build both locally and on Gatsby Cloud, commit the changes over to Develop
- [ ] Resume Docs content work and ensure the team pulls all changes from develop
- [ ] Update the [Embed images](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/style-guide/images/embed-images.mdx) doc for new info / instructions on adding block-level and inline images (see https://github.com/newrelic/docs-website/pull/6655)

**Comment by zstix** [comment]
We will estimate this retroactively after the work is done (likely next week).

**Comment by jpvajda** [comment]
@roadlittledawn how do you want to track this issue? It's post team split, and I am going to keep docs eng work off our deven board, is this going to become a JIRA issue?
