### ISSUE TITLE
[Search] Enable limited indexing of data dictionary page

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#6657]
## Summary

The filterable/searchable data dictionary page is excluded from swiftype and other search engines in order to reduce noise in search results.

From swiftype's perspective, each unique URL (including query params) is a new page and thus could create many duplicate records/results. In swiftype we can add crawl rule to only crawl certain patterns for the data dictionary (like the default page with no params). We can also tell swiftype to only index certain parts of the page (like event names and not the tables of attributes).

Google may also not be smart enough to know how to index the page and its various query params. We can tell Google what the params are via Google Search Console

## Acceptance criteria
- [ ] Update swiftype crawl rule (via UI) to only crawl base path (no query params, all events/attributes)
- [ ] Update data dictionary page to add `data-swiftype-index="false"` to attribute tables (and other elements on the page that could add noise)
- [ ] Manually add page to swiftype index and inspect record

## Helpful links
Closes https://github.com/newrelic/docs-website/issues/6584
Related to https://github.com/newrelic/docs-website/issues/5084

**Comment by zuluecho9** [comment]
@roadlittledawn I wonder if perhaps we could expose only the data type names (TransactionError, PageView, things like that). I get that the attributes would be too noisy. Do you think that's possible?
