### ISSUE TITLE
Review Azure Mysql IO Optimization

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#6671]
Please review the I/O content optimization for Azure Mysql and provide any feedback on the content. Here is the link: https://docs.google.com/document/d/1FvEOkNPauwbssL-V5cSb5Or28oUngheiQZ4eH7IxFzU/edit

Our team at Search Nurture has reviewed the keyword potential and added in the specific dashboards and alerts if they are available for that quickstart. We'd love your help making sure it's on-brand, up-to-date, and that it communicates the technology correctly. 

Thank you!

**Comment by paperclypse** [comment]
Reviewed!
