### ISSUE TITLE
Review AWS Billing IO Optimization

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#6672]
Please review the I/O content optimization for AWS Billing and provide any feedback on the content. Here is the link: https://docs.google.com/document/d/1Z2aVXppLedar82x5RUc8HM_7WS0JfoWp0TkspiJ5KTM/edit

Our team at Search Nurture has reviewed the keyword potential and added in the specific dashboards and alerts if they are available for that quickstart. We'd love your help making sure it's on-brand, up-to-date, and that it communicates the technology correctly. Additionally, if you see a chance to link to a docs page please let me know and we can add that link into the text.

Thank you!

**Comment by paperclypse** [comment]
Reviewed!
