### ISSUE TITLE
Add Discussion on APM Event Limits with extrapolate paradigm to data governance guide

### ISSUE THREAD

**Issue by JimHagan** [newrelic/docs-website#6680]
We should enhance [this section](https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing#apm-agent) by adding a detailed discussion of how customers can use sampling strategies along with extrapolated queries to manage data volume for super high volume data.

This is the doc that has the information we want to include:

https://docs.newrelic.com/docs/using-new-relic/data/understand-data/new-relic-event-limits-sampling/

**Comment by JimHagan** [comment]
@khickey-newrelic This is a placeholder.  I think I'll try to work this in over the next couple of weeks.

**Comment by urbiz-nr** [comment]
Thanks for filing this issue, @JimHagan! I'm moving it to the Blocked column in the meantime. Once you're ready to give it a go, ping the @hero in #help-documentation so we can sync and figure out next steps.

**Comment by zuluecho9** [comment]
Update: I'll put this on my plate.
