### ISSUE TITLE
Issue: Kafka monitoring integration

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#6685]
## How can we make our docs better?

The drop-downs on this page don't seem to be working. Nothing happens when I click them. Tried in chrome and Safari. Other pages work. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @dlesniak-NR, thanks for reporting this! This doc you're accessing is an older version, you can find the new and updated version, [here](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration).

I'm working with our technical support team to see what happened and fix this issue 🙌🏻.

**Comment by x8a** [comment]
I fixed the problem in PR #6704.
