### ISSUE TITLE
[Growth] Add LinkedIn ad snippet

### ISSUE THREAD

**Issue by lfirman** [newrelic/docs-website#6691]
## Is your feature request related to a problem? Please describe
Request: Add a LinkedIn Insight Tag and Twitter website tag to our docs.newrelic.com site so that we can track visitors to this site and retarget them with paid ads through LinkedIn and Twitter. This will be an experiment to test how well these audiences engage and convert on our paid ads.

**Extra Q's:**
When do you need this done by? Not an urgent request but it would be great to have the tags installed by 1st April
Is this part of a campaign that will end by some date? if so, when? No, this audience of docs website visitors will be used in ongoing campaigns.
are there any GDPR things we need to be aware of with this? No this is GDPR compliant and it is stated in our New Relic Privacy Policy that we collect data online and offline including activities on our sites and third party sources.
https://newrelic.com/termsandconditions/privacy

<details>
<summary>LinkedIn Insight Tag snippet</summary>

```js
<script type="text/javascript">
_linkedin_partner_id = "7273";
window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
window._linkedin_data_partner_ids.push(_linkedin_partner_id);
</script><script type="text/javascript">
(function(l) {
if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};
window.lintrk.q=[]}
var s = document.getElementsByTagName("script")[0];
var b = document.createElement("script");
b.type = "text/javascript";b.async = true;
b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
s.parentNode.insertBefore(b, s);})(window.lintrk);
</script>
<noscript>
<img height="1" width="1" style="display:none;" alt="" src="https://px.ads.linkedin.com/collect/?pid=7273&fmt=gif" />
</noscript>
```

</details>

<details>
<summary>Twitter Website Tag snipet</summary>

```js
<!-- Twitter universal website tag code -->
<script>
!function(e,t,n,s,u,a){e.twq||(s=e.twq=function(){s.exe?s.exe.apply(s,arguments):s.queue.push(arguments);
},s.version='1.1',s.queue=[],u=t.createElement(n),u.async=!0,u.src='//static.ads-twitter.com/uwt.js',
a=t.getElementsByTagName(n)[0],a.parentNode.insertBefore(u,a))}(window,document,'script');
// Insert Twitter Pixel ID and Standard Event data below
twq('init','o73vi');
twq('track','PageView');
</script>
<!-- End Twitter universal website tag code -->
```

</details>

## Describe the solution you'd like
To have these insight tags installed on the docs.newrelic.com website.

## Describe why this important to you
The goal of this request is that it will help us reach our consumption goals by increasing engagement within this audience. This audience will be served with paid ads that aim to educate them about new products and features. 
Audience (docs.newrelic.com website visitors located in EMEA that also have the demographics/firmographics of our target developer persona)

Why should we work on this? What use cases does it support?
Retargeting ads result in higher conversion rates than non-retargeting ads. This will help marketing to reach our sign up, MQL and consumption targets easier as it will allow us to reach a wider more engaged audience in Q1.

## Additional context

If you are the person who will be installing the website tag, download the code snippet and place it at the bottom of all pages on your website before the </body> HTML tag.

**Comment by roadlittledawn** [comment]
Moved to jira https://newrelic.atlassian.net/browse/DOCENG-23
