### ISSUE TITLE
Issue: REST API calls for alerts

### ISSUE THREAD

**Issue by carrieschmid** [newrelic/docs-website#6695]
## How can we make our docs better?

"slideby": "integer" doesn't work
it should be    "slide_by": "integer" 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks for letting us know, @carrieschmid. I'm looking into this now.
