### ISSUE TITLE
Issue: Troubleshoot a running infrastructure agent

### ISSUE THREAD

**Issue by MikhailTymchukFT** [newrelic/docs-website#6709]
## How can we make our docs better?

* Is something confusing?
  Yes. Where `newrelic-infra-ctl` puts verbose logs to?
* Is something inaccurate or missing?
  See above.
* Were you unable to complete a task? (What task?)
  I tried to enable verbose logging with `newrelic-infra-ctl`, but cannot find verbose logs and if this approach is working at all.
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/manage-your-agent/troubleshoot-running-infrastructure-agent/
* **OS**: Ubuntu 20.04

**Comment by urbiz-nr** [comment]
Thanks for getting in touch, @MikhailTymchukFT. Have you tried generating troubleshooting logs as described [here](https://docs.newrelic.com/docs/infrastructure/infrastructure-troubleshooting/troubleshoot-logs/generate-logs-troubleshooting-infrastructure#solution)?
