### ISSUE TITLE
Recommendation of improvement of attribute dictionary

### ISSUE THREAD

**Issue by albertoolivan** [newrelic/docs-website#6712]
## How can we make our docs better?

https://docs.newrelic.com/attribute-dictionary/

I like this page of attribute-dictionary but I think it is too large, it may have every field from each table collapsed like this:

https://www.w3schools.com/bootstrap/bootstrap_collapse.asp

With this a comprehensive list of tables will be displayed and then once you reach the table you want to know more, see only those details.

This is just a suggestion to improve :)

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@albertoolivan, this is an interesting suggestion for the data dictionary! I will pass this suggestion to our site engineers.
