### ISSUE TITLE
Issue: Customize your webhook payload

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#6721]
## How can we make our docs better?

Probably "Text plain output" format can be removed due to it not available  anymore.
Please refer this [thread](https://newrelic.slack.com/archives/C0DSAFF8Q/p1647908607307699).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by urbiz-nr** [comment]
Thanks for letting is know, @shinji-newrelic, I'm removing it in #6731.
