### ISSUE TITLE
New relic browser application download

### ISSUE THREAD

**Issue by jessica81hunter** [newrelic/docs-website#6744]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/browser-monitoring/troubleshooting/troubleshoot-your-browser-monitoring-installation/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey there @jessica81hunter! Is there a specific issue I can help you resolve?
