### ISSUE TITLE
Issue: NRQL syntax, clauses, and functions

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#6745]
## How can we make our docs better?

The [`uniqueCount()` description](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/#func-uniqueCount) is short on detail (and essentiallly parrots what in-product callout says). 

Any extra info/contextg about how much of an approximation this is, how it's calculated, etc might be helpful. There's a [forum post ](https://discuss.newrelic.com/t/scaling-up-observability-increasing-nrql-limits/74894)that has some extra info including the algorithm that's used (`HyperLogLog++`)

## Screenshot
![2022-03-23_10-28-33](https://user-images.githubusercontent.com/2952843/159762610-d2f998f0-e931-43ef-b9ab-7a1b4cc29cb3.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
