### ISSUE TITLE
Where can I find the definition of error_percentage

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#6791]
There are several references to it but I cant find out what defines an error that is included in this percentage.   Is it Http status code 5XX only, does it include any http code that isnt a 2XX, other errors, etc? 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/alerts-conditions-api-field-names/
* **OS**: Windows 10
* **Browser**: Chrome 99.0.4844.84
* **Device**: Unknown

**Comment by StingyJack** [comment]
Why is this getting marked as stale?

**Comment by StingyJack** [comment]
Dear NewRelic, 
If you want to avoid creating resentment and relationship problems with some of your customers/users, turn off the stale bot.  The thing does not check to see if anyone from the project (contributor, maintainer, owner, etc) has responded or not before closing the issue.  Its not the kind of behavior that humans would tolerate IRL.

**Comment by StingyJack** [comment]
Related https://github.com/TomasHubelbauer/fuck-you-stale-bot

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
