### ISSUE TITLE
Issue: Introduction to dashboards

### ISSUE THREAD

**Issue by prot23** [newrelic/docs-website#6793]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/introduction-dashboards/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 99.0
* **Device**: Unknown

**Comment by x8a** [comment]
I'll close this issue tomorrow if you don't have any further questions.

Feel free to open a new issue with other blockers you find! 💃🏻
