### ISSUE TITLE
Outdated Nevigation

### ISSUE THREAD

**Issue by michaelsync** [newrelic/docs-website#6794]
## How can we make our docs better?

This page said as below. 

> To create a custom role with custom capabilities, go to [account dropdown](https://docs.newrelic.com/docs/glossary/glossary/#account-dropdown) > **Account settings > Users and roles > Roles** and click New custom add-on rol

There are no "Account Settings" or Users and Roles under account-dropdown. 

![image](https://user-images.githubusercontent.com/192911/160318896-bf3f40a5-defe-44a4-b05e-52f94cc273b1.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model/
* **OS**: WIndows 10
* **Browser**: Chrome
* **Device**: Laptop DELL

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
