### ISSUE TITLE
Issue: Requirements for the infrastructure agent

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6802]
The link:

https://one.newrelic.com/launcher/nr1-core.settings?pane=eyJuZXJkbGV0SWQiOiJrOHMtY2x1c3Rlci1leHBsb3Jlci1uZXJkbGV0Lms4cy1zZXR1cCJ9

Labelled "Kubernetes integration" results in a 404.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks as always, @GaPeppy !
