### ISSUE TITLE
Issue: Kubernetes integration: compatibility and requirements

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6803]
Can we add to the docs here to discuss/confirm the docker orchestration environments/versions that are supported?  Specifically the customer wants to know about Containerd support and can't find anywhere.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/kubernetes-integration-compatibility-requirements
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 99.0.4844.83
* **Device**: Unknown

**Comment by zuluecho9** [comment]
i asked a qustion about this in the kubernetes slack channel, by the way. Trying to get another opinion on this. @GaPeppy

**Comment by zuluecho9** [comment]
Fix this in https://github.com/newrelic/docs-website/pull/6856. thanks
