### ISSUE TITLE
Issue: Amazon EC2 monitoring integration

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6805]
> From a live feed of changes in your environment, search for and view EC2 events.

There are no details on what "EC2 events" represent and no discussion of the schema.  Complex enterprises are unlikely to use the curated UI to any degree; they are more likely to rely on custom dashboards and NRQL Alert Conditions.  Would be helpful that NR points to the documentation source for this data (likely on AWS) and then a breakdown of the NR schema for the captured events data.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-ec2-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@GaPeppy I'm not sure of your name or else I'd slack message you, but I wanted to talk about this more if you were up for scheduling a 30 minute meeting for us. I think this relates to some other infrastructure docs issues so wanted to get your opinion on a couple things.

**Comment by zuluecho9** [comment]
Adding this one to 'docs-issue' candidates as I haven't heard any feedback from team yet on this. I think it pertains to general issue that we may need to explain more about where cloud platform 'events' come from (note: the 'events' displayed in the infra 'Events' feed, not our use of 'events' that means objects stored in NRDB) and link to that explanation when we have that use of 'events'.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
