### ISSUE TITLE
Issue: Forward logs using Cloudflare Logpush (only on Enterprise plan)

### ISSUE THREAD

**Issue by vanmash** [newrelic/docs-website#6824]
## How can we make our docs better?

It's worth mentioning that Cloudflare Logpush in only available on **Enterprise plan**

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/cloudflare-logpush-forwarding/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
