### ISSUE TITLE
Issue: StatsD monitoring integration

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6837]
The docs say:

> The default rate limit is 100,000 data points per minute (DPM).

However the default limit has been 1,000,000 DPM for some quarters now.  I question the value of copying the account-wide limits numbers into this doc.  It isn't really clear if the limit in this doc is for the nri-statsd component or the account at large.

Would be helpful that this doc illuminated the scaling capacity of nri-statsd and referred to the limits docs for account wide limits.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/statsd-monitoring-integration-version-2/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@GaPeppy i think i know what happened here. this was from a long time ago from when they first rolled out metric API and it was basically another SKU. I'm just going to delete a lot of that referenced there. If you could go into more detail about the 'scaling capacity' that'd be helpful though.

**Comment by zuluecho9** [comment]
Fixed this in https://github.com/newrelic/docs-website/pull/6856. Thanks!
