### ISSUE TITLE
Issue: Error tracking with errors inbox constains broken link

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#6848]
# Description
Under the `Connect errors inbox to CodeStream` heading, there is a "Learn more here" link. This link does not work.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/errors-inbox/errors-inbox/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 99.0.4844.83
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Looks to be fixed!
