### ISSUE TITLE
Case Studies link does not open case studies, linked to static image

### ISSUE THREAD

**Issue by gregackerman** [newrelic/docs-website#6868]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/overview/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Thanks for the issue, @gregackerman! That's a good point, we should definitely link to this case studies page from this doc. (We don't typically use images as links to other pages on our docs site.)

**Comment by paperclypse** [comment]
We addressed this one in PR https://github.com/newrelic/docs-website/pull/6876. Thanks again for letting us know!
