### ISSUE TITLE
Issue: Amazon ElastiCache monitoring integration

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#6888]
Documentation says that the integration can produce 3 different datasets:
provider = ElastiCacheRedisNode
provider = ElastiCacheRedisCluster
provider = ElastiCacheMemcachedNode

But nowhere does it mention what the schema values are for "ElastiCacheRedisCluster"

-?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-elasticache-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
