### ISSUE TITLE
Issue: OpenTelemetry quick start

### ISSUE THREAD

**Issue by reese-lee** [newrelic/docs-website#6891]
1. This drop-down section is empty: https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start/#collector
2. Clicking on "Edit this page" takes me to a broken link.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-quick-start/
* **OS**: MacOS
* **Browser**: Chrome
* **Device**: MacBook

**Comment by rhetoric101** [comment]
@reese-lee, since this was resolved with a cache refresh on the server, I am closing this. Thanks again for point out this issue!
