### ISSUE TITLE
Issue: Use NrIntegrationError event to understand data ingest problems

### ISSUE THREAD

**Issue by ElementalWarrior** [newrelic/docs-website#6909]
None of the queries on this page work. I cannot even find `NrIntegrationError` from the data explorer.

Is this no longer possible to debug logs shipped to the logging endpoint?

I receive 202 http responses for all of our logs. But the logs do not show up in the dashboard. 

From the newrelic dashboard I receive:

```
No chart data available

No events found -- do you have the correct event type and time range?
```

When running `SELECT * FROM NrIntegrationError`.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/manage-data/nrintegrationerror/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hello @ElementalWarrior - thanks for reaching out. We are the Docs team and we handle documentation only. As far as I can tell, these NRQL query examples are still correct. You may want to reach out to Support about this. Hope this helps!
