### ISSUE TITLE
"Configure New Relic as a Prometheus data source for Grafana" and "New Relic API keys" contradiction

### ISSUE THREAD

**Issue by parmsib** [newrelic/docs-website#6922]
This page:
https://docs.newrelic.com/docs/more-integrations/grafana-integrations/set-configure/configure-new-relic-prometheus-data-source-grafana/

says to set up a new Insights query key, and links to this page:
https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/

where it says "If you don't already use these keys, you should have no reason to learn about them.", referring to 
Insights query keys, among others.

This is the first guide of yours I'm following, and I'm immediately unsure of how to proceed.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @parmsib! Thanks for letting us know about this! We'll look into it and work on a way to better explain this procedure.

In the meantime, I'll contact the team to see what key you need to configure.

**Comment by x8a** [comment]
If you still need to use it, here's [the insights query key](https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#insights-query-key) that doc recommends:

> To find and manage Insights query keys: From the [account dropdown](https://docs.newrelic.com/docs/accounts-partnerships/education/getting-started-new-relic/glossary#account-dropdown), click API keys (get [a direct link to the API keys page](https://one.newrelic.com/launcher/api-keys-ui.api-keys-launcher)). Then click Insights query keys.

Also, we're looking into the confusion that doc is giving!

**Comment by x8a** [comment]
Hi, @parmsib! If you don't have any further questions, I'll close this issue in two days.

We'll work on the doc to make sure to avoid ambiguity 👌🏻.
