### ISSUE TITLE
Issue: Group browser metrics by URLs

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#6925]
## How can we make our docs better?

Hey docs team - this docs page is out of date.  Allow lists appear to have been replaced with "Metric normalization" as of about a week ago. Can we get this page updated to reflect how to organize URL grouping with the new UI?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/configuration/group-browser-metrics-urls
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 99.0.4844.84
* **Device**: Unknown

**Comment by khickey-newrelic** [comment]
As I review other web apps I see that the Segment allow lists option is available.  I know the Browser team was planning changes as to how URLs are grouped and assumed they had already made the changes.  It's worth checking in with them on this.  Sorry if I jumped to conclusions too quickly!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
