### ISSUE TITLE
Confusion - limit of license keys per account

### ISSUE THREAD

**Issue by lholota** [newrelic/docs-website#6926]
## How can we make our docs better?

Confusion between two pages mentioning the same thing:
https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/ and
https://docs.newrelic.com/docs/apis/nerdgraph/examples/use-nerdgraph-manage-license-keys-user-keys/

The first page mentions "Each key is tied to a specific account and you can create **as many as you want.**"
The NerdGraph page mentions "You can create **up to 1,000 keys** of each license key type, which allows for key rotation."

Are these two contradicting each other? Or does the limitation apply only to keys created through NerdGraph? Either way I can't unfortunately tell from the docs. 

I am currently solving a usecase where it could be possible to actually need to create more than 1000 keys so I would like to know where the truth is 😊

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/use-nerdgraph-manage-license-keys-user-keys/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
