### ISSUE TITLE
Issue: 404 New Relic Browser Application is disabled - Need to delete it

### ISSUE THREAD

**Issue by sikander-javeed** [newrelic/docs-website#6936]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/404/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@sikander-javeed, can you tell me the page that had the browser link issue?

**Comment by rhetoric101** [comment]
@sikander-javeed, I am closing this because I haven't heard back from you. You can always reopen this and provide us with details about your concerns.
