### ISSUE TITLE
Issue: Send Prometheus metric data to New Relic

### ISSUE THREAD

**Issue by np1001299** [newrelic/docs-website#6938]
## How can we make our docs better?

* Is something confusing?    Can't able to configure ForgeRock to NewRelic
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.60
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@np1001299, I'm not sure I see your question in this GitHub request. Could you clarify your concerns about Prometheus?

**Comment by rhetoric101** [comment]
@np1001299, since we haven't heard back from you, we're going to close this issue. You can always reopen it if you want to tell us more details about your Prometheus documentation questions.
