### ISSUE TITLE
Change `Sign Up` button to `Free Account` button

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#695]
### AC 
- @mb-newrelic has asked us to change the button label from `Sign Up` to `Free Account` 
- This should be done at the theme level so all DECO sites use the same language for sign up buttons 

### Describe why this important to you

We want to see if this new language increases awareness and usage of the free tier.

**Comment by austin-schaefer** [comment]
Hey @jpvajda , minor request. Not a launch blocker but should be quick and really nice to have by launch.

**Comment by jerelmiller** [comment]
@austin-schaefer I assume this is for the global header button? If so, is this something that should be docs specific, or something that should propagate across all sites? Looks like we have "Start now" on the dev site.

**Comment by jpvajda** [comment]
@austin-schaefer You may want to confirm with David Hwang, we were asked do  Sign Up on Docs and OSS and  Start now on Dev. Just want to be consistent with what we've already been asked to do.

**Comment by mb-newrelic** [comment]
@jpvajda I can check with David. This is informed by a discussion with Bill about a successful strategy he's seen used elsewhere. I'd love to launch with some of his hypotheses live right out of the gate. If instrumented we can then use data to make calls about how we iterate.

**Comment by jpvajda** [comment]
@mb-newrelic just let us know the decision we are happy to modify the buttons, it's easy fix, just wanted to ensure we had alignment.
