### ISSUE TITLE
Issue: NRQL syntax, clauses, and functions

### ISSUE THREAD

**Issue by rudouglas** [newrelic/docs-website#6978]
## How can we make our docs better?

The section on `FACET` is misleading as it suggests that the `FACET` function is executed last, after `SELECT`, which is not the case.

https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions#sel-facet

This line in particular:

```
Use FACET to separate and group your results by attribute values
```

`results` suggests there are already results from the query and FACET simply groups them, this is not the case. This could be made clearer, and explicitly say what results it is grouping. It would also be awesome if we could get a doc on the order in which sections of a NRQL query are executed, from the NRQL team.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.75
* **Device**: Unknown

**Comment by gitcos** [comment]
FYI, this made it difficult for me to solve a problem in NRQL because the right solution actually depends on knowing that FACET goes first, and SELECT works on the results of the FACET.  It would've saved me a lot of time if the documentation had been very clear about that.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
