### ISSUE TITLE
Cannot read property 'allMdx' of null

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#698]
It seems our docs writers have had trouble recently with the site. Many of them have seen the following error when trying to spin up the site:

```
Cannot read property 'allMdx' of null

  43 |
  44 | const AnnouncementBanner = () => {
> 45 |   const { allMdx } = useStaticQuery(graphql`
     |           ^
  46 |     query {
  47 |       allMdx(
```

I have tried this myself and not been able to reproduce the error. I also tried a fresh clone of the repo, installed dependencies, and started the site with no error.

The recommendation to this point has been to edit node modules directly to address this issue. The following has been recommended as a quick workaround:

Edit: `node_modules/@newrelic/gatsby-theme-newrelic/src/components/AnnouncementBanner.js`

Change these lines:

```js
  const { allMdx } = useStaticQuery(graphql`
    query {
      allMdx(
        sort: { fields: [frontmatter___startDate] }
        filter: { fileAbsolutePath: { regex: "/src/announcements/" } }
      ) {
        nodes {
          slug
          body
          frontmatter {
            startDate(formatString: "YYYY-MM-DD")
            endDate(formatString: "YYYY-MM-DD")
          }
        }
      }
    }
  `);
```

To this:

```js
  const allMdx = { nodes: [] }
```

This gets past the issue, but is very error prone since any upgrade to the Gatsby theme is going to blow this change away. This has happened to at least 3 docs writers so we may have to look into it more.

We may need to suggest cloning the repo fresh and starting there if we are unable to reproduce. As mentioned from my testing, this seemed to work fine.

**Comment by jpvajda** [comment]
these seemed to be related to an old version of gatsby. delete node_modules and doing yarn install seems to fix the issue after pulling the newest code down

**Comment by jerelmiller** [comment]
We'll keep this issue open for a bit longer to ensure [the above](https://github.com/newrelic/docs-website/issues/698#issuecomment-788077995) fixes the issue going forward. If so, we'll close this issue

**Comment by jerelmiller** [comment]
We are now 3 days post launch and I haven't seen any complaints on this. I'm going to close this for now. We can reopen if it starts popping up again.
