### ISSUE TITLE
Unclear how to reference nerd graph schema to create queries in an IDE

### ISSUE THREAD

**Issue by oliviat255** [newrelic/docs-website#6993]
## How can we make our docs better?
* it is unclear how to reference the nerd graph schema so that I can create queries in my IDE with syntax highlighting. I have the following `.graphqlconfig` and am still unable to connect to new relic and reference the schema so that i can write queries with syntax highlights. i have tried the url with and without https
```
{
"name": "Nerd Graph GraphQL Schema", 
"schemaPath": "remote-schema.graphql", 
"extensions" : {
   "endpoints" : {
      "Default GraphQL Endpoint" : {
         "url": "http://api.newrelic.com/graphiql",  
         "headers": {
            "user-agent" : "JS GraphQL",
            "API-Key" : "<KEY>"
            },
         "introspect": true 
         }
      }
   }
}
```

**Comment by barbnewrelic** [comment]
Appreciate the feedback, @oliviat255 ! I'm going to route this to the engineers to see if they have any suggestions.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
