### ISSUE TITLE
Issue: Set up SNMP data monitoring

### ISSUE THREAD

**Issue by shhudspethnr1** [newrelic/docs-website#7006]
## How can we make our docs better?

Please change the format of the boxes-- it does not make sense to click into all the boxes. I only clicked into the box I wanted (snmp), but after some toil, realized I needed to check ALL of the pre-requisites to get the SNMP polling working, especially the Docker installation and security requirements. I went through the process with a confused customer and I was also confused. Adding steps or numbers may be helpful or indenting boxes so that it's intuitive to go through all steps in the boxes would add a lot of clarity on how to get it running. 

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
good one, @shhudspethnr1, thank you.

**Comment by zuluecho9** [comment]
created PR for this: https://github.com/newrelic/docs-website/pull/7007
