### ISSUE TITLE
Issue: Introduction to New Relic NerdGraph, our GraphQL API

### ISSUE THREAD

**Issue by carrieschmid** [newrelic/docs-website#7039]
## How can we make our docs better?

Service levels | Configure and manage service levels , this link goes here
https://docs.newrelic.com/docs/apis/nerdgraph/tutorials/nerdgraph-slm

It should go here
https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-slm/#create-sli-slo

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.60
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thank you @carrieschmid, will fix!

**Comment by zuluecho9** [comment]
fixed in https://github.com/newrelic/docs-website/pull/7040
