### ISSUE TITLE
April 14 noon: Placeholder - Zach's what's-new posts 

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#7056]
A reminder that Zach has two what's new posts meant to go out noon April 14. If you're hero, please check in with him to make sure this is happening and he's got them in, please.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
