### ISSUE TITLE
$selenium not available after updating to chrome 100 in synthetic monitor

### ISSUE THREAD

**Issue by SimonSchick** [newrelic/docs-website#7057]
## How can we make our docs better?

See https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100 suggests that simply using `$selenium` should work, but this doesn't seem to be the case as the runtime errors with `$selenium` being undefined.

I've upgraded the runtime to chrome 100 but it still doesn't appear to be exposing the new version, I assume I'm somehow using a legacy monitor, can we add docs on how to update the monitors?

**Comment by rhetoric101** [comment]
@SimonSchick, thanks for asking that question! I'll pass this on to our subject matter experts and see what they say.

**Comment by rhetoric101** [comment]
@SimonSchick, could you create a support ticket so we can understand your problem better? Then, we can see if we need to update the docs. You can file a ticket here: https://support.newrelic.com/s/inbox
