### ISSUE TITLE
Issue: Change applied intelligence correlation logic with decisions

### ISSUE THREAD

**Issue by iazam6** [newrelic/docs-website#7086]
## How can we make our docs better?

The current [image](https://docs.newrelic.com/static/NRAI_Decisions_Index-8455187a0162f326d9f5cfed2f7781c0.png) in the docs that populates first is a bit outdated. 

I have attached an updated screenshot below -

![image](https://user-images.githubusercontent.com/81179945/163289906-b10c6dcc-bf89-4508-bf5a-064d704a4fdd.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/change-applied-intelligence-correlation-logic-decisions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
I updated the screenshot, thanks for letting us know! 

If you see similar issues in the future, feel free to open a PR and make the needed changes yourself. We welcome and encourage contributions 🙌🏻.
