### ISSUE TITLE
Please create a new doc page for Java dynamic attachment 

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#7090]
## How can we make our docs better?

Our guided installer for the Infrastructure agent is now installing Java Agent. It works with "dynamic attachment" way which is different from the existing Java Agent way.
It should be created as a new doc page which is discussed with GTSE-13423.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.

**Comment by tanaka-takayoshi** [comment]
Please reopen this issue since it has not been fixed and still problem.

**Comment by ashutosh887** [comment]
I would like to work on this

**Comment by paperclypse** [comment]
The docs team is reviewing old, stale GitHub issues and closing them. If you'd like us to re-open this, please comment on this issue or reach out in our docs help channel or file a Jira ticket with our team.
