### ISSUE TITLE
Documentation Issue: REST API calls for alerts

### ISSUE THREAD

**Issue by William-Luo0** [newrelic/docs-website#7091]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

The list existing conditions for policies curl command returns a missing parameter error. [Direct Link](https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts/#conditions-list)
The curl command executed:
```
curl -X GET 'https://api.newrelic.com/v2/alerts_conditions.json' -H 'X-Api-Key:<Actual API key>' -i -d 'policy_id=<Actual policy id>' -L
```
The `-L` was added to follow the redirect from the initial URL.

Response:
```
HTTP/1.1 302 Found
Proxied-By: Service Gateway
Location: https://api.eu.newrelic.com/v2/alerts_conditions.json
content-type: text/plain;charset=UTF-8
content-length: 85

HTTP/1.1 400 Bad Request
Proxied-By: Service Gateway
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Security-Policy: frame-ancestors *.newrelic.com
Cache-Control: no-cache
Content-Length: 50
Content-Type: application/json
Date: Thu, 14 Apr 2022 06:10:45 GMT
Server: nginx
Status: 400 Bad Request
X-Rack-Cache: miss
X-Request-Id: 85cd8c33a2ce71133b84bb101c184493
X-Runtime: 0.096046
X-Ua-Compatible: IE=Edge,chrome=1

{"error":{"title":"missing parameter: policy_id"}}
```

It seems like a url parameter is expected instead of being in the data body.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts/
* **OS**: MacOS 12.3.1
* **Browser**: N/A (Command line curl)
* **Device**: MacBook Pro

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
