### ISSUE TITLE
Visual studio client side log outdated

### ISSUE THREAD

**Issue by dvdlsbn** [newrelic/docs-website#7097]
Hello !

Found an quite upsetting bug in code stream with android studio:
https://github.com/TeamCodeStream/codestream/issues/950

I was sent here to grab my IDE logs after reprocuding  it but doc is too old (2017) and not for linux.

* https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/
* **OS**: Ubuntu
* **Browser**: Firefox
* **Device**: Thinkpad

**Comment by paperclypse** [comment]
Thanks for writing in @dvdlsbn! I've reached to our CodeStream team for the next steps on this one.

**Comment by bcanzanella** [comment]
hi @dvdlsbn if you're using Android Studio, you'll want to follow the instructions for JetBrains (https://docs.newrelic.com/docs/codestream/troubleshooting/client-logs/#jetbrains)
