### ISSUE TITLE
Issue: Infrastructure agent configuration verbose mode

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#7120]
## How can we make our docs better?

The behavior when verbose 3 is selected is unclear.
If I set verbose 3, will smart verbose mode logs be forwarded to New Relic Logs?
Or is the debug mode log transferred?

Also, if I select verbose 3, will local log files no longer be generated?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for pointing out this area of confusion! I'll reach out to our eng team to get clarification and then update the doc :)

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
