### ISSUE TITLE
Issue: Use $har for custom timing details

### ISSUE THREAD

**Issue by farski** [newrelic/docs-website#7146]
## How can we make our docs better?

It would be really helpful to have a complete example on this page. It says _You can use the $har library_, but there's no information on how to actually make use of that library. Clicking through all the links I could find led me to a number of different related help docs, but none included specific references to the `$har` library. It doesn't appear to be a part of the [Node.js code libraries](https://nodejs.org/docs/latest-v16.x/api/all.html), and the [monitor version comparison table](https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-monitors/scripted-monitor-runtime-environment) link doesn't take you to a table. There is a list of _Supported third-party modules_ on that page, but nothing HAR-related is listed there either.

The top of the "These custom timing use both the default node.js module and importable node.js modules.", with two links. Even after following those links, I still am not sure what that sentence means. What does it mean for a custom timing to _use_ a default node module? Does it mean they're compatible?

Also there's the sentence, "Depending on your specific scripting needs, you can pull more granular timing details into the UI through a variety of attributes", and then a list, which includes DNS. Then there's an example for how to manually add timing to a DNS query. I think what it's trying to show is that you can call `foo.dns().startTimer()`, and somehow **DNS** will be displayed as a distinct timing in the UI. This is a confusing example, because the entire timer is timing DNS, so what's the point of _also_ adding the attribute? It also could be a lot more clear how to use those attributes. Are they all just `attribute_name()` on the timer object? Do I always need to call `startTimer()` twice?

This page also says "Likewise, you stop these timers by using stopTimer().", but all the examples seem to use a method called `endTimer()`. 

I've parsed as much of this page as I can, and ultimately it seems like I should be able to just call `$har.addResource`, but that doesn't work, so I'm not really sure how this is supposed to work. I think this page may need a bit of work. I'd be happy to take a crack at it, but I don't know what the correct information should be.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/custom-timing-details/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hi @farski! Thanks for raising this issue. I think this is a great suggestion. I'm forwarding this along to our Synthetic team so that they can work up a good, complete example.

**Comment by vinodlala** [comment]
This worked for me:

```
assert(dnsResource.dns().duration <= 1000, 'Expected response time less than 1000ms')
```

**Comment by gainskills** [comment]
> This worked for me:
> 
> ```
> assert(dnsResource.dns().duration <= 1000, 'Expected response time less than 1000ms')
> ```

Could you please share that do you import any lib to make it work?
thanks,

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
