### ISSUE TITLE
Issue: Forward your logs using the infrastructure agent

### ISSUE THREAD

**Issue by kaylareopelle** [newrelic/docs-website#7155]
## How can we make our docs better?

There are a series of linked images beneath the text: "To use the following links, make sure you are logged to your New Relic account." These linked images redirect to an error page when logged in to New Relic One. 

![Screen Shot 2022-04-18 at 4 26 04 PM](https://user-images.githubusercontent.com/87386821/163892458-1b08d00f-b4b5-4e3a-b8c5-9c20cc31d3c1.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.88
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
