### ISSUE TITLE
Issue: Stream logs using Kinesis Data Firehose

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#7158]
## How can we make our docs better?

It is difficult to identify what is logs through firehose if the customer have multiple data sources.
It seems data have attribute  `newrelic.source` with the value `api.logs.awsFirehose`
So it is better to describe how to view logs coming through firehose.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/stream-logs-using-kinesis-data-firehose/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.88
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
