### ISSUE TITLE
Issue: .NET: Configure logs in context

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#7159]
## How can we make our docs better?

The doc for application logging has some contradictions.

1. The release note says application logging is introduced in 9.7.0 but the configuration page says it's available for 9.7.1 and higher.
https://docs.newrelic.com/docs/release-notes/agent-release-notes/net-release-notes/net-agent-9700
https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/#application_logging
2. The Logs in Context page says the value of `NEW_RELIC_APPLICATION_LOGGING_FOWARDING_ENABLED` should be escaped with `'` but the configuration page says it should not be escaped.
https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#1-agent
https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/#optional-environment-variables

Since the release note and configuration page are important, please write them as accurate. Even a little contradiction may impact a critical effect on customers.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
