### ISSUE TITLE
Issue: Broken link on the Kubernetes Helm integration page

### ISSUE THREAD

**Issue by RobHooper** [newrelic/docs-website#7162]
## How can we make our docs better?

Found a broken link on this page:

> See [Kubernetes integration: install and configure](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm/docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/install-kubernetes-integration-using-helm
* **OS**: Ubuntu
* **Browser**: Firefox 99.0
* **Device**: Unknown (Laptop)

**Comment by x8a** [comment]
I fixed the link with PR #7163. Thanks for reporting it!
