### ISSUE TITLE
nginx installs

### ISSUE THREAD

**Issue by pir8radio** [newrelic/docs-website#7177]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
1.    you only provide "installs" and directions for Linux users,  you know nginx runs on windows servers too..  :-)   Is there no link to the nginx-log.yml  file so we can manually add it to a windows install?  Please include a link to the example files within the directions here.   My directories do not contain the "example" files on windows. 

* Were you unable to complete a task? (What task?)
1.  get nginx logging into newrelic

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/nginx/nginx-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
