### ISSUE TITLE
Issue: Ruby: Configure logs in context

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#7179]
## How can we make our docs better?

```
application_logging:
  forwarding:
    max_samples_stored: 10_000
```

max_samples_stored: 10000
I don't think underscore is necessary for
Please confirm.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-ruby
* **OS**: Windows 10
* **Browser**: Chrome 100.0.4896.127
* **Device**: Unknown

**Comment by pizzaz93** [comment]
This seems to have been updated https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-ruby/#1-agent

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
