### ISSUE TITLE
Issue: Cloud migration: Create application baselines - broken link

### ISSUE THREAD

**Issue by sskilbred** [newrelic/docs-website#7180]
## How can we make our docs better?

The following link/page is can't be found: https://docs.newrelic.com/docs/perform-migration-acceptance-testing

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/new-relic-solutions/create-application-baselines
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.75
* **Device**: Unknown

**Comment by zuluecho9** [comment]
I think this was an OM doc. I'm asking about this now.

**Comment by zuluecho9** [comment]
I found this. it's meant to point to this doc /docs/new-relic-solutions/new-relic-solutions/optimize-cloud-architecture-spend-continuously-improve-your-modern-cloud-environment.

**Comment by pizzaz93** [comment]
May I submit a PR to update the link?

**Comment by sskilbred** [comment]
I‘m not the owner - but yes, I believe that would be helpful @pizzaz93 👍

**Comment by pizzaz93** [comment]
I think this is fixed by the mentioned PR

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
