### ISSUE TITLE
Issue: NerdGraph tutorial: Move dashboards to other accounts

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#7199]
If you arent creating a dashboard in a different account, does the account id parameter need to be specified for the create mutation?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-import-dashboards-using-api
* **OS**: Windows 10
* **Browser**: Chrome 100.0.4896.88
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for the question @StingyJack! Let me hunt this down for you and we can clarify it in the docs.

**Comment by StingyJack** [comment]
@bradleycamacho  - it actually does need to be supplied (I tried it without and got an error). I guess what I dont see are the required parameters for these mutations.  They are referenced [here](https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/dashboards-api/) but there isnt anything about what the parameters or structure are other than a few scattered examples.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
