### ISSUE TITLE
[Build] Add clamshell/collapser components

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#72]
## Summary
Add components for collapser / clamshells. These should be kept basic in style/functionality for now. NR1 Help Center is a good example to draw from.

The component should not output `<dl><dt></dt><dd></dd></dl>` elements and instead use generic elements like `<div>`.

## Acceptance criteria
- [ ] As a content author, I can add collapsers with one or more rows that, when clicked, toggle show/hide content block.

## Helpful links
[Example of basic styling in NR1 Help Center > search for `Dashboards`](https://one.newrelic.com/launcher/dashboards.launcher?pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmxpc3QiLCJlbnRpdHlEb21haW4iOiJWSVoiLCJlbnRpdHlUeXBlIjoiREFTSEJPQVJEIn0=&overlay=eyJjb250ZXh0TmVyZGxldElkIjoiZGFzaGJvYXJkcy5saXN0IiwiY29udGV4dERpc3BsYXlOYW1lIjoiRGFzaGJvYXJkcyIsIm5lcmRsZXRJZCI6Im5yMS1oZWxwLXhwLmhvbWUifQ==&platform[timeRange][duration]=3600000&platform[accountId]=1)

**Comment by jerelmiller** [comment]
Done with #98
