### ISSUE TITLE
Issue: NerdGraph tutorial: Move dashboards to other accounts

### ISSUE THREAD

**Issue by StingyJack** [newrelic/docs-website#7210]
> Copy and paste the [entity's output](https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-import-dashboards-using-api#export) into the new account. It will be copied as an entity.

What new **account** is it referring to?  Trying to make a dashboard.

Can a screenshot be posted for this step that does not have the variable naming scrolled off the visible area?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/export-import-dashboards-using-api
* **OS**: Windows 10
* **Browser**: Chrome 100.0.4896.88
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
