### ISSUE TITLE
Data governance optimize doc: problem with Android section

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#7221]
@JimHagan The Android section is pretty messed up, due to some formatting issues and broken links that make understanding what's meant to be going on there difficult. I can't link to it, as it's in a collapser, but it's in this section, under Mobile: https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing/#optimization-through-configuration

Work to do would be to review the Android section and submit edits to fix.

**Comment by pizzaz93** [comment]
I drafted https://github.com/newrelic/docs-website/pull/7264 as a potential fix, I hope it's helpful.

**Comment by JimHagan** [comment]
I recommend closing this since #7264 was merged.
