### ISSUE TITLE
Issue: Dead link & grammar issue

### ISSUE THREAD

**Issue by hannahramadan** [newrelic/docs-website#7227]
## How can we make our docs better?
Issue: Under **Collect errors not instrumented by default**, Ruby [notice_error()](http://www.rubydoc.info/github/newrelic/newrelic-ruby-agent/NewRelic/Agent#notice_error-instance_method) is a dead link. 

Suggested Fix: The link should be:
https://www.rubydoc.info/gems/newrelic_rpm/NewRelic/Agent#notice_error-instance_method

Issue: Small grammar error under **Ignore errors**: "If you don't want an error to report to **the our [collector](https://docs.newrelic.com/docs/accounts-partnerships/education/getting-started-new-relic/glossary#collector)**, you can ignore the error, and the APM agent discards the error entirely."

Suggested Fix: Remove either "the" or "our".

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Thanks for reporting these bloopers! I just made a PR to fix.

**Comment by hannahramadan** [comment]
Thanks!
