### ISSUE TITLE
Data governance optimize guide: a couple small infra-related issues

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#7229]
@JimHagan 

For https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing/: 

Issue #1: 
In the infrastructure section, it reads "There are several distinct sampling rate configurations that can be used: The other is through custom process sample filters." Request: is there a bulletpoint list that was meant to go there after the colon? Determine how to fix that. 

Issue # 2: 
One section "For example: in an environment where you have the AWS RDS integration running as well as the New Relic on-host integration". Request: can we clarify which on-host integration that's referring to?

**Comment by JimHagan** [comment]
@zuluecho9 

FYI:

https://github.com/newrelic/docs-website/pull/8250

**Comment by zuluecho9** [comment]
Thanks Jim! Closing.
