### ISSUE TITLE
DO 1 minute video "pitch" for GatsbyConf: Due 2/8

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#723]
Grace Cho from the marketing team asked for a 1 minute video of why Gatsby Conf is cool  For some context around this ask . I want to start highlighting our people and putting more faces out there as a way to humanize our brand and really talk to our devr them?

## Video criteria 

- .mp4 video format
- record with phone or a good desktop camera 
- make it fun and engaging 🥰

**Comment by jpvajda** [comment]
My video is done 🥳

**Comment by jerelmiller** [comment]
This is done
