### ISSUE TITLE
Review AWS Trusted Advisor quickstart content optimization

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#7232]
Here is the link to the doc for our optimization of the AWS Trusted Advisor quickstart (https://docs.google.com/document/d/1v_Rv8rw31OJRyrHxo7ZPKLjYBmVtVn9wqpV3bqGH1II/edit#).

We will be restructuring these to fit the updated template at a future time, but we have a few that will still be coming through in the meantime.

Please provide feedback (in the form of comments on the doc) on branding and features if needed.

Thank you!

**Comment by barbnewrelic** [comment]
@aliandersonsn  Your google doc looks fine. I made one suggested edit re: Oxford comma.
