### ISSUE TITLE
OM data governance 'Optimize': a log section issue

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#7238]
@JimHagan 

Problem: in the 'Log forwarders' section of https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing/#log-forwarders, there's some sort of bad formatting that makes it hard to understand. I'll copy that section below: 

```
If you have pre-written Fluentd configurations for Fluentbit that do valuable filtering or parsing, you can import them into our New Relic logging config. To do this, use the config_file and parsers parameters. config_file: path to an existing Fluent Bit configuration file. Any overlapping source results in duplicate messages in New Relic's log management. parsers_file: path to an existing Fluent Bit parsers file. The following parser names are reserved: rfc3164, rfc3164-local and rfc5424. Learning how to inject attributes (or tags) into your logs in your data pipeline and to perform transformations can help with downstream features dropping using New Relic drop rules. By augmenting your logs with metadata about the source, we can make centralized and easily reversible decisions about what to drop on the backend. At a minimum, make sure the following attributes are present in your logs in some form:
```

Request: Try to edit and format that section so that it reads correctly.

**Comment by pizzaz93** [comment]
The [source code](https://github.com/newrelic/docs-website/blob/develop/src/content/docs/new-relic-solutions/observability-maturity/operational-efficiency/dg-optimizing.mdx) looks to be formatted correctly for this section and others just maybe needs an extra line break.

**Comment by JimHagan** [comment]
Possible fix in this PR: https://github.com/newrelic/docs-website/pull/7297
