### ISSUE TITLE
Issue: New Relic Explorer: View performance across apps, services, hosts

### ISSUE THREAD

**Issue by savasyasam01** [newrelic/docs-website#7267]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-one/core-concepts/new-relic-explorer-view-performance-across-apps-services-hosts/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @savasyasam01! Could you describe the problem you had with the doc mentioned above? We'd love to help!

**Comment by x8a** [comment]
Hi, @savasyasam01! If you don't have more questions we can help you with, I'll close this issue tomorrow EOD.

Feel free to open a new one when you find something that should be fixed! Thanks!
