### ISSUE TITLE
Collasper sections are easy to share links to via a deep link

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#727]
### Is your feature request related to a problem? Please describe

There's no way (outside of inspect element) to get an ID for a collapser.

### Describe the solution you'd like

I'd like to show a little link icon on mouse-over, like we did in https://github.com/newrelic/docs-website/issues/188 . Then copy the link (with appropriate anchor) to the clipboard when you click, and update the current URL path as well.

As a bonus, it'd be great to be able to right-click and select *Copy link* (this is the easiest way in the Drupal site, though it's not very discoverable)

### Describe why this important to you

Deep-linking to collapsers is pretty common, especially with docs like [NRQL syntax](https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/nrql-syntax-clauses-functions) and the agent config docs.

### AC 

1. provide a `# link` that will open the collapser automatically when a user enters that url in the browser.
2.  example `/docsurl/#collaspersection
2. the collaspers element to copy and paste the reference is available `TBD` 
3. This is added to all collapsers that are not nested. 
4. In the case of a nested collasper we'd link the the primary top level collapser only.

<img width="972" alt="Screen Shot 2021-03-16 at 12 13 02 PM" src="https://user-images.githubusercontent.com/1395158/111359304-f6241e80-8650-11eb-901e-d6b4302818da.png">

**Comment by zuluecho9** [comment]
Would love to see this. I use this feature all the time and I suspect a good # of other people do, too.

**Comment by wrekone** [comment]
Support has traditionally relied on this feature to direct customer attention to specific sections of lengthy docs pages.

**Comment by jeffreycs** [comment]
I agree with @wrekone. In the original docs site, I would frequently link customers to individual concepts _within_ a document, so that I could easily reference the definitions of specific NRQL clauses and NerdGraph fields.

**Comment by rodrigo-corgozinho** [comment]
Yes, from the support perspective it is really necessary, mainly on the config pages of our agents.
Eg: [this page](https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/nodejs-agent-configuration/), if I want to bring the customer to the **filepath** setting there is no way to bring them straight to view the setting.

It is possible to do a workaround by inspecting the page and checking the ID of the item, but it would be much better if the links are added by default.

**Comment by jpvajda** [comment]
There is a lot of interest in this feature which is great! There is definitely an opportunity here for someone to contribute this feature to the Docs Site. If someone wants to take it on the Developer Enablement team would be happy to provider pointers and a code review to help get it done. cc @zstix  / @jerelmiller

**Comment by jpvajda** [comment]
There is a lot of interest in this feature so I added a `hero` label to it. and perhaps we can try to implement in our next sprint if not too much effort. Would be a good way for our new team members to learn the site functionality. cc @zstix

**Comment by HenryTech** [comment]
Linking directly to clamshells is used by support _all the time_, so being able to do it with just a single click (`Copy link`) is near-essential to us. Finding the correct HTML ID and manually modifying the URL is not an ideal workflow.

I'd love it if this could be prioritized!

**Comment by jpvajda** [comment]
too finish this work up thanks to @jerelmiller contribution I just had one question: 

what will actually add the links to the docs site? a bump in theme or do we need to make a props change to the collasper component?

**Comment by jerelmiller** [comment]
> what will actually add the links to the docs site? a bump in theme or do we need to make a props change to the collasper component?

A bump in the theme version should be all that you need! The addition keys off of the `id` prop passed to the `Collapser` component, which many of them already have. Once the theme version is bumped, you'll start seeing them show up for everything. Just make sure to add an `id` to any collapser that we want to deep link to and the link icon will automatically show up.

**Comment by jpvajda** [comment]
So this feature will go out with the next `develop` merge to `main`
