### ISSUE TITLE
Issue: New Relic API keys

### ISSUE THREAD

**Issue by ppezaris** [newrelic/docs-website#7272]
> Our monitoring solutions and APIs require one of several API keys. These keys allow only approved people in your organization to report data to New Relic, access that data, and configure features.

what does "several" refer to? several people in my org need a key, or there are several different types of keys, or each app needs a key?

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@ppezaris  The rest of the doc describes the various API keys and what they are used for. I'll reword that opening sentence. Hope this helps!
