### ISSUE TITLE
Issue: .NET: Configure logs in context

### ISSUE THREAD

**Issue by jeffchiudev** [newrelic/docs-website#7277]
## How can we make our docs better?

* I'm a NR .NET TSE and customer was having issues with enabling log forwarding via [environmental variable](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#1-agent). They were using the following:

`NEW_RELIC_APPLICATION_LOGGING_FOWARDING_ENABLED='true'`

After speaking with our .NET engineers they informed me that the docs should instead have true without single quotes:

`NEW_RELIC_APPLICATION_LOGGING_FOWARDING_ENABLED=true`

* Further down in [option 2](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#2-decorate) for letting the agent decorate logs, there is a similar issue where instead of:

`NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED='true'`

It should be: 

`NEW_RELIC_APPLICATION_LOGGING_LOCAL_DECORATING_ENABLED=true`

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.127
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@jeffchiudev  Thanks for reporting this! I've updated the doc with https://github.com/newrelic/docs-website/pull/7281
