### ISSUE TITLE
Issue: Events reported by mobile monitoring

### ISSUE THREAD

**Issue by MichaelOsowski** [newrelic/docs-website#7309]
## How can we make our docs better?

We are missing the MobileUserAction  event table

**Comment by rhetoric101** [comment]
To clarify, the docs need two changes:

* An entry in the data dictionary for `MobileUserAction`.
* An entry in the [mobile events table](https://docs.newrelic.com/docs/data-apis/understand-data/event-data/events-reported-mobile-monitoring/) that summarizes this type and links to the data dictionary.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.

**Comment by ywang-nr** [comment]
Re-open
