### ISSUE TITLE
Issue: Mobile crash event trail

### ISSUE THREAD

**Issue by cdillard-NewRelic** [newrelic/docs-website#7330]
## How can we make our docs better?

Fix broken link to https://newrelic.com/mobile-monitoring/pricing

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/mobile-monitoring-ui/crashes/mobile-crash-event-trail
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.127
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thank you @cdillard-NewRelic

**Comment by zuluecho9** [comment]
fixed in https://github.com/newrelic/docs-website/pull/7338.
