### ISSUE TITLE
Request to the way of validating the configuration for customer annotation

### ISSUE THREAD

**Issue by ghnethippo** [newrelic/docs-website#7358]
## How can we make our docs better?
I need the way of validating if the custom annotation configuration has been applied and working as well as a troubleshooting guide. newrelic-api.jar starting configuration example should be provided for the customer's conveniences. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/java-agent/api-guides/java-agent-api-instrument-using-annotation/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.127
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
