### ISSUE TITLE
Log API - 403 Forbidden

### ISSUE THREAD

**Issue by KorayBarkin** [newrelic/docs-website#7359]
Hello everyone,
I did follow the guide and got the license-key. I've entered headers and body as followed, however, keep getting 403 Forbidden Response.

Endpoint: https://log-api.eu.newrelic.com/log/v1

<img width="1242" alt="Screen Shot 2022-04-28 at 10 50 40" src="https://user-images.githubusercontent.com/70101145/165704428-53d6b105-3402-4693-a301-ad35ccc66763.png">
<img width="1262" alt="Screen Shot 2022-04-28 at 10 51 19" src="https://user-images.githubusercontent.com/70101145/165704441-570080d0-ec84-4e95-adb5-ac504a8418e5.png">

**Comment by erdzan12** [comment]
Did you try with the "X-License-Key" header and set there your license key?

Else maybe you are not using the eu servers, so remove the eu from your url

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
