### ISSUE TITLE
Alerts: animated .gif for "Create a condition from a chart" is out-of-date

### ISSUE THREAD

**Issue by founddrama** [newrelic/docs-website#7396]
## How can we make our docs better?

WHERE? Under the "Create a condition from a chart" heading on the "Create NRQL alert conditions" page: https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-nrql-alert-conditions/#create-chart

WHAT? The animated gif demonstrated the process is out-of-date; among other changes, it's showing "evaluation offset" which has been deprecated in favor of aggregation methods.

The workflow being demonstrated is largely unchanged, but **we should have the animated .gif match the UI in its current state.**

**Comment by paperclypse** [comment]
Thanks for letting us know, @founddrama!

**Comment by paperclypse** [comment]
Hi @founddrama, looks like I let this one slip through the cracks. Sorry about that! I've asked @homelessbirds to take care of this for you. Thanks!

**Comment by austin-schaefer** [comment]
Thanks @founddrama , looks like this one got missed in GH issues. Filed a issue in Jira for us to fix this in an upcoming sprint here https://issues.newrelic.com/browse/NR-67824
