### ISSUE TITLE
Adjust the design treatment to right rail header navigation elements

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#741]
We got feedback that the arrows are a little confusing to users so Daniel suggested we change the arrows to be a border on the navigation box that wraps the header name.

**OLD**
<img width="368" alt="Screen Shot 2021-02-02 at 5 46 54 PM" src="https://user-images.githubusercontent.com/1395158/106682070-f83d8c80-657e-11eb-9af0-8d9fe4c70f2a.png">

**NEW**

![image (1)](https://user-images.githubusercontent.com/1395158/106682111-0ab7c600-657f-11eb-95b4-992fb670499b.png)

**Comment by jpvajda** [comment]
@jerelmiller could you do this as part of the right rail improvements, it's a good suggestion.

**Comment by jerelmiller** [comment]
Totally!
