### ISSUE TITLE
Issue: User type: basic, core, and full platform users

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#7417]
## How can we make our docs better?
Please let's just call out the features that a Basic user does NOT have access to. Please make it clear and simple. Dont link or obfuscate the negative space - just make it clear with a delineated list. 

https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-type/#logs-capabilities

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-type/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 101.0.4951.41
* **Device**: Unknown

**Comment by zuluecho9** [comment]
made some edits to the logs section of the table
