### ISSUE TITLE
Issue: Compatibility and requirements for the Python agent

### ISSUE THREAD

**Issue by sumosolutions** [newrelic/docs-website#7422]
## How can we make our docs better?

[Web hosting mechanisms](https://docs.newrelic.com/docs/agents/python-agent/hosting-mechanisms/) link under the Requirements column is broken and needs to be updated.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/python-agent/getting-started/compatibility-requirements-python-agent
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.127
* **Device**: Unknown

**Comment by x8a** [comment]
I fixed it with PR #7424. Thanks for reporting it!
