### ISSUE TITLE
Issue: Collector with New Relic (basic setup)

### ISSUE THREAD

**Issue by sadikinfosec** [newrelic/docs-website#7479]
## How can we make our docs better?

The link to find the value of the OTLP_EXPORTER_ENDPOINT on this page just links back to the page itself - https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic/#:~:text=appropriate%20endpoint.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/collector/opentelemetry-collector-basic/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
I think we've fixed this now @sadikinfosec. thank you!
