### ISSUE TITLE
Clarify EXPECTED_STATUS_CODES Env Variable for Java agent

### ISSUE THREAD

**Issue by sdbedi** [newrelic/docs-website#7494]
## How can we make our docs better?
You can set expected status codes in the Java agent via expected_status_codes in the yml file or the NEW_RELIC_ERROR_COLLECTOR_EXPECTED_STATUS_CODES environment variable. However, the [documentation](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#ec-expected_status_codes) on this field omits the environment variable. 

By contrast, the [documentation](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#ec-expected_classes) for expected classes has both the yaml parameter and the environment variable.  

The end result is stylistically inconsistent, and is somewhat confusing; I'm happy to update the docs for expected status codes.

**Comment by bradleycamacho** [comment]
Thanks for reporting this @sdbedi! Could you take a look at https://github.com/newrelic/docs-website/pull/7505?

**Comment by sdbedi** [comment]
@bradleycamacho Thanks! I was gonna do it myself, but I thought I'd ask first.
