### ISSUE TITLE
Warn users of private GKE clusters about Admission Webhook performance implications

### ISSUE THREAD

**Issue by guhcampos** [newrelic/docs-website#7498]
## How can we make our docs better?

GKE has a [very significant and poorly documented difference](https://github.com/kubernetes/kubernetes/issues/79739#issuecomment-509813068) to other providers that [severely impacts the performance](https://github.com/newrelic/k8s-metadata-injection/issues/69) of private clusters if neglected. 

I would suggest that a **warning** type of callout should be added linking to a specific GKE page that directs the user to create the appropriate firewall rules when installing the New Relic agent on a private cluster.

The main reason this is so hard to identify is the Webhook points to a service port 443, but GKE bypasses this completely and talks directly to the service pods, which listen on port 8443, which is unexpected and impossible to figure out just by looking at New Relic's helm charts.

**Comment by bradleycamacho** [comment]
Thanks for reporting this @guhcampos! I'll get our engineers to take a look and take the appropriate action for editing the docs :)

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
