### ISSUE TITLE
Adjust padding around h2s/h3s to provide more spacing between content sections.

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#750]
I wonder if we might differentiate the padding for headings to make ends/starts of sections stand out more. You can see in current github preview docs site, it's equidistant space before and after the heading, whereas in drupal docs site, there is a little more padding at end of a section before the heading.

**Comment by jpvajda** [comment]
I like this suggestion I think we could add a bit more spacing between the page headers.  Not a launch blocker but it's a quick change and we can probably knock it out as a catch-all item.
