### ISSUE TITLE
Issue: Find and use your Kubernetes data

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#7501]
## How can we make our docs better?

Can we augment a couple definitions, please?
* apiserverRequestDelta - is a delta counter for each request verb (e.g. GET, WATCH, LIST, CREATE) and their response codes. Delta is between the current and the last polled value.
* apiserverRequestRate -  per minute

feel free to reach out if you have any questions internally. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/understand-use-data/find-use-your-kubernetes-data/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey there @dralph3344 I'm happy to make these edits! Are these entirely new attributes or just additions to existing definitions?

**Comment by zuluecho9** [comment]
Fixing in https://github.com/newrelic/docs-website/pull/8001
