### ISSUE TITLE
Missing h3s and (optional) clamshell entries in sidebar 

### ISSUE THREAD

**Issue by zuluecho9** [newrelic/docs-website#751]
Regarding docs site code: We probably want h3s to appear in sidebar content navigation by default, along with the h2s that are there. 

Also, we had ability to manually add clamshell entries in that sidebar, by adding class="freq-link" (e.g., `<h2 id="x" class="freq-link">`). I'm thinking we should probably have that ability too, but maybe separate issue. 

Example: on https://docs-preview.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-authentication-saml-sso-scim-more, we'd have 'Configure SAML SSO' in the sidebar, as shown here on drupal site: https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/authentication-domains-saml-sso-scim-more

**Comment by jerelmiller** [comment]
@djsauble do you mind weighing in here?

**Comment by jerelmiller** [comment]
I can speak to at least why this isn't here for now.

When we did the work to add the "table of contents" links in the right rail, we decided we'd only put heading level 2 in there. See [this MMF doc](https://docs.google.com/document/d/1uPSt6D3-ZoHg2LiRBPGxyfo-SShwwOjOu5KnE6vlGsU/edit#heading=h.pby4cdazqn3q) for our requirements.

**Comment by jpvajda** [comment]
marking as won't do, as we decided to stop at h2s in the right rail to not overwhelm the user.  Also the ability to add elements to the right rail is now programmatically done, it's based on the structure of the MD file, so writers shouldn't have to manually do this, it's all dictated by the structure of the MD file.
