### ISSUE TITLE
Add an inviting message to "edit" and "file an issue" area

### ISSUE THREAD

**Issue by mmfred** [newrelic/docs-website#753]
### Is your feature request related to a problem? Please describe

In an unmoderated usability test, users were asked to go to a page on the new site and suggest a change for a typo. Their process was recorded. The recordings demonstrate that:

- 2/10 users never found the buttons.
- A third person got stuck on the term "open source" in the instructions and clicked the link to the Open Source site and more easily, apparently, found the "file an issue" button there and did so.
- One person who did find and use the buttons said in his feedback that the buttons could be a little bigger.  

### Describe the solution you'd like

Can we add a call out element, similar to how  to invite changes just above the Edit and File an issue buttons (in the gray area). It's not super elegant, but could be a little more encouraging. 
![label-goes-here](https://user-images.githubusercontent.com/58010132/106811041-9fbfcb00-6622-11eb-9eff-d6acfe5c5807.png)

**ltext:**  `Suggest a change`

### Describe why this important to you

Important because we want to encourage input from customers.

**Comment by jpvajda** [comment]
good suggestion, easy to do and we can probably knock it out as a catch-all item

**Comment by jpvajda** [comment]
@mmfred would you be able to ask Toby Minton for language here? He's been really great and providing some info for these types of things. Once you have it, just add to the issue. 👍

**Comment by mmfred** [comment]
@jpvajda - sure I'll see what Toby thinks. FYI - I did some brainstorming with the docs team and got some blessings on this. But I always welcome Toby's input.

**Comment by mmfred** [comment]
@jpvajda got some input from Toby. Here's what he said, which I include because I agree and think we might have to follow up with some design tweaks:
“Suggest a change” sounds great to me, actually. It’s clear and makes the process sound lightweight.

I worry that more text won’t make the buttons more noticeable, but a label is worth a shot, and what you’re suggesting is a good one. The design makes those buttons blend in a bit. They don’t stand out as CTAs. If the label doesn’t do the trick, we might need to try a design tweak.
 
I think we probably need a separate ticket for tweaking the buttons.

**Comment by jpvajda** [comment]
How about we do this: 

<img width="380" alt="Screen Shot 2021-02-05 at 10 12 08 AM" src="https://user-images.githubusercontent.com/1395158/107066025-a8d3a800-679a-11eb-8d6c-750a8f52d8e3.png">

**Comment by jpvajda** [comment]
@mmfred we can wrap the text in a color below the buttons, TBH this is a very low priority change for us at this time, so we'll entertain a simple adjustment. we are instrumenting the buttons in MMF13, and we can then actually have data to look at it to make decisions like this, so we'll keep the buttons as is, and look to do something simple then look at the data and make the adjustments.

**Comment by jpvajda** [comment]
@mmfred agreed to put this simple change in for now, then monitor the data to see how users interact with these buttons and the contributor link.

**Comment by mmfred** [comment]
Thank you!
