### ISSUE TITLE
Issue: Add, rename, and remove hosts

### ISSUE THREAD

**Issue by slfk** [newrelic/docs-website#7532]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/configuration/add-rename-remove-hosts/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @slfk! Could you tell us more about the issue you found with the doc? Thanks!

**Comment by x8a** [comment]
Hey, @slfk! If you don't need more help for this issue, I'll be closing it tomorrow.

Feel free to open a new issue if you have any other questions. Thanks!
