### ISSUE TITLE
Issue: Page views UI has changed recently 

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#7561]
## How can we make our docs better?

* About two weeks ago, engineering released the new Page View experiences in the UI. 
* Please see blog post here: https://newrelic.com/blog/nerdlog/updates-to-browser-monitoring
* Screen shots in the public documentation should be updated to reflect changes. 
* Where applicable, some charts, names and tabs have been renamed and the docs should reflect that.  
* To note, similar to new Ajax UI, these charts are based on event data now, not metrics as previously. Underlying event queries are available in chart dropdowns. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/additional-standard-features/page-views-examine-page-performance/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by CherylFrankenfield** [comment]
I'm not sure if you can view this from Support but here's a run down of what's new in Browser UI: 

https://nerdlife.datanerd.us/new-relic/ls/community/gts-community/post/5248325313232896

Here's the engineering ticket for the Page View UI changes: 

https://newrelic.atlassian.net/browse/GTSR-182

Please feel free to reach out with any questions, thanks!

**Comment by barbnewrelic** [comment]
@CherylFrankenfield  I have a Jira to fix this! DOC-7995 I can add you as a watcher to that Jira if you'd like.

**Comment by CherylFrankenfield** [comment]
@barbnewrelic OOH thank you! I _think_ I came across that ticket in a Slack channel recently and I will follow along! Please let me know if you need anything.

**Comment by barbnewrelic** [comment]
@CherylFrankenfield  I made some very minimal updates to page views https://docs.newrelic.com/docs/browser/new-relic-browser/additional-standard-features/page-views-examine-page-performance and a few other UI docs before FutureStack. More to come!
