### ISSUE TITLE
Issue: AWS Lambda for sending logs from S3

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#7566]
## How can we make our docs better?

```
Limitations
The maximum supported log file size is 35 MB uncompressed.
```
However, the NewRelic-log-ingestion-s3 readme on AWS states

> Max log file size in the s3 bucket is 150 MB uncompressed.

Which number is more accurate?
https://serverlessrepo.aws.amazon.com/applications/us-west-2/533243300146/NewRelic-log-ingestion-s3

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-logs-s3/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by pontiphex** [comment]
Even more curious is that the code seems to define this as 400mb

https://github.com/newrelic/aws_s3_log_ingestion_lambda/blob/76acccb9dcc58c7d681c1139475c43b78f1a4e9e/src/handler.py#L37

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
