### ISSUE TITLE
Issue: NerdGraph tutorial: view, create, and rename accounts

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#7570]
spelling mistake

> Note that an organization can only use a single data center: there can't be accounts that use diffrent data centers in a single organization.

**diffrent**

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/manage-accounts-nerdgraph/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
I fixed it in PR #7571/
