### ISSUE TITLE
Links to agent release notes are returning 404s

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#758]
### Description

Links to the Agent release notes from the APM docs left nav are returning 404s. I was able to replicate this issue in three sets of APM docs and assumed that it would continue that way.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/agents/go-agent
2. In the left nav, click Get started and then click C SDK release notes (https://docs-preview.newrelic.com/docs/agents/c-sdk/get-started/c-sdk-release-notes)
3. See error

I replicated this in Go and Java as well.

### Expected behavior

I think we should see the release notes page for each agent.

**Comment by austin-schaefer** [comment]
I think those pages are dummy docs, so whatever we're doing to account for those should probably be taking this into account as well.

**Comment by jerelmiller** [comment]
Good find!
