### ISSUE TITLE
Docs site table collapsers to have show/hide all buttons + key board short cuts

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#760]
### Is your feature request related to a problem? Please describe

Currently, there's a handy feature where if you hit S and H it will show and hide the collapser content, respectively. Unfortunately, this isn't obvious. In our old site, we have a Show all/Hide all button to show and hide the collapser content.

I sort of think the new site should have this too! (You can see an example of this here: https://docs.newrelic.com/docs/agents/c-sdk/install-configure/install-c-sdk-compile-link-your-code)

### Describe the solution you'd like

I'd like the functionality to match the old site. including the keyboard short cuts if possible.

### Describe why this important to you

I like to show all/hide all the collapsers, but I have forgotten more than once that the S and H keys will do this.  - `DONE`

### Additional context

If there's a reason for not including this button, I'd love to know what that reason is. :)

<img width="1004" alt="Screen Shot 2021-02-18 at 5 29 22 PM" src="https://user-images.githubusercontent.com/1395158/108439746-1954dd00-720f-11eb-8b6a-fff641455617.png">

**Comment by jpvajda** [comment]
I like this suggestion

**Comment by jerelmiller** [comment]
FYI the keyboard shortcuts are in place. You can use `s` or `f` to show all collapsers and `h` for hiding them all.

**Comment by jpvajda** [comment]
@jerelmiller Thanks! so are you planning to put an element like the screen shot as well to show all  / hide all? That was also part of this issue.

**Comment by jerelmiller** [comment]
Yep, that would be what is remaining. I was just trying to callout that the keyboard shortcuts were already in place in case someone picks up this ticket and do the work.
