### ISSUE TITLE
A wide table is overlapping with the right nav in an unsightly way

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#764]
### Description

On this page: https://docs-preview.newrelic.com/docs/agents/c-sdk/instrumentation/guide-using-c-sdk-api, I found this wide table that overlaps with the right nav. Unfortunately, it makes the table and the right nav hard to read. I assume this is a problem for pages with other wide tables.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/agents/c-sdk/instrumentation/guide-using-c-sdk-api
2. Make your browser window wider and narrower to see the behavior of the table in this section: https://docs-preview.newrelic.com/docs/agents/c-sdk/instrumentation/guide-using-c-sdk-api#segments 
3. Scroll down to the table.
4. See how the table and the right nav overlap.

### Expected behavior

I'd love to see some elegant way for these two page elements to go together. But I think ultimately the table should go on top of the right nav.

<img width="1060" alt="Screen Shot 2021-02-03 at 4 41 02 PM" src="https://user-images.githubusercontent.com/7992384/106828262-b247fd80-663e-11eb-9133-1f363db217d8.png">

**Comment by jerelmiller** [comment]
This was fixed by https://github.com/newrelic/gatsby-theme-newrelic/pull/241. Tables are now horizontally scrollable. Now that the fix has been deployed, looking back at this page confirms the scroll fixes the overlap issue.

**Comment by paperclypse** [comment]
Cool! Thanks!
