### ISSUE TITLE
Review Tomcat quickstart content optimization

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#7640]
Our team at Search Nurture optimized some of the content for better search results for Tomcat. 

Here is the link: https://docs.google.com/document/d/1f7S4PGJLZ0HOuSSfrMQnUyjp0ZCWoKVApI6UjB0qb1c/edit#

Please check to be sure it's on-brand and let us know on the doc if there's anything you'd recommend we change. 

Thank you!

**Comment by rhetoric101** [comment]
@aliandersonsn I inserted a few comments in the Google doc and will close this. If you have any questions, feel free to reopen it.
