### ISSUE TITLE
Review Docker IO content optimization

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#7641]
Our team at Search Nurture optimized some of the content for better search results for Docker. 

Here is the link: https://docs.google.com/document/d/1PuC1U-LTRi3j6UAMPRhmuGxXC-39xLASVevq1Skgb1k/edit#

Please check to be sure it's on-brand and let us know on the doc if there's anything you'd recommend we change. 

Thank you!

**Comment by rhetoric101** [comment]
@aliandersonsn, I inserted a final suggestion in the Google doc. If you have other questions, you can reopen this.
