### ISSUE TITLE
Issue: Lambda monitoring architecture

### ISSUE THREAD

**Issue by rmclaughlin-nelnet** [newrelic/docs-website#7653]
## How can we make our docs better?
Is this https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/architecture/ still the best way to integrate with Lambda or should we use https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/aws-metric-stream

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/architecture/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by keegoid-nr** [comment]
@rmclaughlin-nelnet It depends on what you aim to achieve. If you want detailed Lambda metrics, our Lambda Monitoring is a good way to go. If you just want basic [CloudWatch metrics](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-lambda-monitoring-integration#metrics) like invocation count, error count, duration, then all you need is an integration.

There are two ways you can integrate with AWS: [api polling](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/connect-aws-new-relic-infrastructure-monitoring) and [metric streams](https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/aws-metric-stream/).

Both of the above methods get you basic data from CloudWatch and we generate entities with metadata from that.

Beyond the basics, we have [Lambda Monitoring](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/monitoring-aws-lambda-serverless-monitoring) for more detailed metrics. 

This [linking of accounts](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking) does a couple things:

1. Checks for an existing integration and uses it if found.
1. If an integration is not found, creates an api polling integration.

We don't currently have a way for our [newrelic-lambda cli](https://github.com/newrelic/newrelic-lambda-cli) to create a metric streams integration, but it will use one if one exists for your AWS account on the New Relic page at Infrastructure -> AWS.

This is a common challenge for people in determining what is required to get detailed Lambda Monitoring set up and working. This is why we have created numbered steps in the docs to better guide you through the process. The first step is creating or linking to an existing integration, then we layer on Lambda Monitoring for detailed metrics with our [Lambda layers](https://layers.newrelic-external.com/).

**Comment by rmclaughlin-nelnet** [comment]
@keegoid-nr Thank you for the answer, it was very helpful. 

We will be setting this up via terraform, so the cli is not necessary. 

Our goal is to use Lambda Monitoring with metric streams. Are those two compatible? I cannot find any information on the numbered steps you mentioned. [Step 1: Link your AWS and New Relic](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/account-linking/) This page does not mention metric stream. I only discovered metric streams by digging through other topics.

My goal with this issue is to get the docs updated so that it is clear one way or the other that lambda monitoring is or is not compatible with metric streams.

**Comment by rhetoric101** [comment]
@rmclaughlin-nelnet, I am the technical writer updating the docs to clarify this. I just created PR #7731 with information from @keegoid-nr. The revised docs will say you need either Metric Streams or API Polling to get Lambda monitoring working. It sounds like since you'll be using TerraForm that you won't be using the CLI, but if you were, our CLI looks for either Metric Streams or API Polling. If it doesn't find one of those integrations, the CLI installs the API Polling integration.
