### ISSUE TITLE
Create emergency runbooks

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#767]
## Description
We will need an emergency runbook (stored in the repo wiki) to help support on-call engineers.

## Helpful Links
* [developer website runbook](https://github.com/newrelic/developer-website/wiki/Emergency-Runbook)
* [opensource website runbook](https://github.com/newrelic/opensource-website/wiki/Emergency-Runbook)

## Acceptance Criteria
* [x] Create a runbook in the repository wiki
* [ ] Add links to dashboard(s)
* [ ] Add links to help channel
* [ ] Add basic troubleshooting steps
* [x] Update launch doc with link to runbook

**Comment by austin-schaefer** [comment]
Would also be helpful (probably already implied) for this runbook to ensure writers know how to escalate to dev team when needed.

**Comment by zstix** [comment]
The runbook will live at this location: https://github.com/newrelic/docs-website/wiki/Emergency-Runbook

We still need to create the content, but I wanted to generate the link so I could update our alerts / docs.

**Comment by zstix** [comment]
I've added the initial runbook details, which include the following:
* Helpful links
* Possible scenarios
* Resolution steps

We will continue to iterate on this as new scenarios / resolutions arise. That said, I think the acceptance criteria for this ticket has been satisfied!
