### ISSUE TITLE
Issue: Release quality management: optimize your deployment cadence and quality

### ISSUE THREAD

**Issue by jakeHinton** [newrelic/docs-website#7681]
## How can we make our docs better?

* Is something confusing? 
* Is something inaccurate or missing? Presentation template link links to AQM Session II, rather than RQM. 
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/innovation-growth/development-release-quality-guide
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 100.0.4896.127
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
