### ISSUE TITLE
[Convert] Add codemod to migrate source to CodeBlock component

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#77]
## Summary
Code blocks are an important, frequently used element on the current site. The docs site has some quirks that will likely require a codemod to ensure they're converted and handled effectively by the theme's CodeBlock component.

Things to look for include:
* the turndown package looks and parses `<pre><code>` and ignores `<pre>` elements (which then create parse errors for Gatsby because curly braces are interpreted as JSX). right now we have a custom rule via the turndown method `.addRule()` to prepend and append fences (`~~~`) to pre element content. not sure if this needs to change to reserve the first line for props?
* turndown seemed to still escape some content in the code element
* it's common to see the following parsed HTML in `<pre>` elements: `<a>`, `<var>`, `<mark>`. we need to figure out how to preserve those if possible so they render as HTML but are not in the copied content

## Acceptance criteria
- [ ] As a developer, I can run the migration script and any `<pre>` elements are converted to the CodeBlock component.
- [ ] Code block content preserves the content without `turndown` escaping anything, the relevant HTML elements are preserved (`<a>`, `<var>`, `<mark>`) and parsed as HTML, and Gatsby builds the component without errors (example: curly braces being parsed as JSX).
- [ ] The inner text of the code block is copyable (and doesn't include any of the afore-mentioned HTML tags)

## Helpful links
[Example: Code block w/var,a](https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-nrql-tutorial)

**Comment by jerelmiller** [comment]
Code blocks seem to be migrated over to our `CodeBlock` component correctly. The only thing that is not handled is the nested `<var>` and `<mark>` tags. 

We may consider filing a separate issue for that since it gets much more complex trying to handle this case, especially since our existing `<CodeBlock />` component does not handle this.

Thoughts?

**Comment by jerelmiller** [comment]
Moved the additional requirements for `<var>`, `<mark>`, etc over to https://github.com/newrelic/docs-website/issues/116. The rest of this ticket is satisfied with the migration so I'm going to go ahead and consider this issue done!
