### ISSUE TITLE
Issue: RabbitMQ monitoring integration

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#7714]
## How can we make our docs better?

> Cluster environments
> 
> In cluster environments, only one node should use METRICS=false and INVENTORY=false ; the rest should use INVENTORY=true and METRICS=false.

The documentation seems to indicate that there is not a single node that collects and prints METRICS.
Is this example setup correct?
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration/
* **OS**: Windows 10
* **Browser**: Chrome 101.0.4951.67
* **Device**: Unknown

**Comment by zuluecho9** [comment]
added link to the settings to make it more clear how those are defined: https://github.com/newrelic/docs-website/pull/7919
