### ISSUE TITLE
dead link: Overview of account settings

### ISSUE THREAD

**Issue by qryuu** [newrelic/docs-website#7717]
## How can we make our docs better?

[Other account settings](https://docs.newrelic.com/docs/accounts/accounts-billing/general-account-settings)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/general-account-settings/intro-account-settings
* **OS**: Windows 10
* **Browser**: Chrome 101.0.4951.67
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks @qryuu !

**Comment by zuluecho9** [comment]
Closing, fixing in later PR.
