### ISSUE TITLE
The dropdown menus on this page are white text on white background

### ISSUE THREAD

**Issue by brnhensley** [newrelic/docs-website#7718]
## How can we make our docs better?

The dropdown menus on this page looks to be partially updated to dark mode:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/48165493/169568245-c047a531-5dbe-4075-9697-4783964ef663.png">

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Mac OSX Montgomery 12.3.1
* **Browser**: Firefox 100.0
* **Device**: Macbook pro

**Comment by zuluecho9** [comment]
@brnhensley i'm not seeing that. Could you give me some detail about what browser you're using and if you see that in a different browser?

**Comment by brnhensley** [comment]
Hi @zuluecho9, I'm using Firefox 100.0, I just tried in Chrome & Safari and they both work properly:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/48165493/169603759-477082b9-d63f-4865-b74f-8ed51896677e.png">

**Comment by brnhensley** [comment]
The font of that dropdown also looks to get going to times new roman
