### ISSUE TITLE
Issue: Forward your logs using the infrastructure agent

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#7725]
### Description

The tiles for different linux distributions in [this section](https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent#install) link into the product, but the nerdlet returns a `404`.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 101.0.4951.67
* **Device**: Unknown

**Comment by paperclypse** [comment]
Hey @zstix, do you know what nerdlets these tiles should be pointing to?

**Comment by zstix** [comment]
Unfortunately I do not. Perhaps someone on the infrastructure team knows?
