### ISSUE TITLE
Review SNMP content optimization

### ISSUE THREAD

**Issue by aliandersonsn** [newrelic/docs-website#7726]
Please review the content optimization we recommend for the SNMP IO page. This is a request from Search Nurture. Please check for branding, correctness, etc. 

Here is the link to the doc: https://docs.google.com/document/d/1yISDT2-c6ZrVn_PeY3MOuevzeoeRd2DVAi6vjyrUnRw/edit

Please leave your comments on the doc for the Search Nurture team to review. 

Thank you!

**Comment by paperclypse** [comment]
Hey @aliandersonsn, this looks good. Feel free to publish this one. I made a couple of super minor punctuation edits.
