### ISSUE TITLE
Issue: Instrumentation for browser monitoring

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#7748]
## How can we make our docs better?

* Is something inaccurate or missing?

We don't have the harvest cycle for PageViewTiming event data. 

PageViewTiming data is sent once, 10 seconds after the load of the page, and also every 30 seconds after the load of the page.

Here is more info and/or we should update this as well: 
https://discuss.newrelic.com/t/relic-solution-understanding-bam-nr-data-net-data-transmission-its-endpoints/58535

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/page-load-timing-resources/instrumentation-browser-monitoring/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by CherylFrankenfield** [comment]
Here's a ticket with engineering: https://newrelic.atlassian.net/browse/GTSE-13880

Please see comment from March 25. Thanks!

**Comment by rhetoric101** [comment]
@CherylFrankenfield, great work figuring out Largest Contentful Paint! Would you be able to make an associated PR to insert this in our [PageViewTiming](https://docs.newrelic.com/docs/browser/new-relic-browser/page-load-timing-resources/pageviewtiming-async-or-dynamic-page-details/)? If not, maybe you could suggest where in the doc we should insert it.

**Comment by rhetoric101** [comment]
Closed by PR #7783.
