### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by Vivian002** [newrelic/docs-website#7752]
I have used react-native for developing app
the npm module from newRelic "newrelic-react-native-agent" is disappear now.
so I can't merge and deploy app.
the doc site was this.
https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/react-native-installation/
[Monitor your React Native application | New Relic Documentation](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/react-native-installation/)
Instructions for installing and configuring the New Relic React Native agent.

help me please.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/404/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@Vivian002  The original React Native module for mobile monitoring reached end of life in 2020. New Relic is in the process of developing new React Native functionality. I'll check whether previous users can use the new version.

**Comment by Vivian002** [comment]
Thank you for your kind.
I think the functions like recordBreadcrumb and recordCustomEvent don't work in react-native.
Please, let me know how to use them.

**Comment by Vivian002** [comment]
I am worried NewRelic doesn't work on React Native for windows.
So, I am wondering that new version has React Native functionality for windows.

**Comment by Vivian002** [comment]
I have a error below when I command 'pod install'

[!] CocoaPods could not find compatible versions for pod "NewRelicAgent":
  In snapshot (Podfile.lock):
    NewRelicAgent (= 7.3.5)

  In Podfile:
    NewRelicAgent (= 7.3.5)

    newrelic-react-native-agent (from `../node_modules/newrelic-react-native-agent`) was resolved to 0.0.1, which depends on
      NewRelicAgent (= 7.3.6)

Specs satisfying the `NewRelicAgent (= 7.3.5), NewRelicAgent (= 7.3.5), NewRelicAgent (= 7.3.6)` dependency were found, but they required a higher minimum deployment target.

**Comment by Vivian002** [comment]
@barbnewrelic can u help me?

**Comment by Vivian002** [comment]
doesn't support react-native any longer?

**Comment by austin-schaefer** [comment]
Hi @Vivian002 , sorry this issue fell through the cracks! Does our new React Native monitoring address your question? https://docs.newrelic.com/docs/mobile-monitoring/new-relic-monitoring-react-native/monitor-your-react-native-application/
