### ISSUE TITLE
Issue: Built-in log parsing rules (There is mismatch between grok rule and attributes list for ALB)

### ISSUE THREAD

**Issue by ktst79** [newrelic/docs-website#7776]
## How can we make our docs better?

Regarding parsing rule for ALB(Application Load Balancer), there is mismatch between grok rule and list of attributes.

In the grok rule, there is only "request" between "sent_bytes" and "user_agent".
%{NOTSPACE:sent_bytes} "%{DATA:request}" "%{DATA:user_agent}"

However, in the table,  "request" is divided into 3 attributes: "method", "url", "http_version".

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/ui-data/built-log-parsing-rules
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 101.0.4951.64
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@ktst79  Thanks for reporting this! I'll ask the engineers to clarify so we can update the doc.
