### ISSUE TITLE
Issue: OpenTelemetry setup for services

### ISSUE THREAD

**Issue by bruno-bert** [newrelic/docs-website#7799]
## How can we make our docs better?

There link to javascriptnode sends to a npm pack that is deprecated.
https://www.npmjs.com/package/@opentelemetry/exporter-collector-grpc

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
