### ISSUE TITLE
[Convert] Add codemod to migrate source to heading component

### ISSUE THREAD

**Issue by roadlittledawn** [newrelic/docs-website#78]
## Summary
Add codemod to migration script that and preserves `id` attributes from HTML to markdown.

Commonly, content authors add custom ID attributes to `<h2>` and `<h3>` elements, which are then used to direct link to that section of the page. We'd like to preserve these IDs on migration. 

## Acceptance criteria
- [ ] As a developer I can run the migrate script and headings in .mdx files retain the `id` if it exists

## Helpful links
[Example: many h2 and h3](https://docs.newrelic.com/docs/agents/net-agent/configuration/net-agent-configuration)
[Example: h4 inside collapser](https://docs.newrelic.com/docs/apis/nerdgraph/tutorials/provisions-your-subscriptions-nerdgraph)

**Comment by roadlittledawn** [comment]
FYR: the syntax for adding the id attribute to a markdown heading is:
```## Heading {#heading-id}
```

**Comment by jerelmiller** [comment]
Unfortunately MDX v2 does not currently support this syntax. I've opened 2 issues about it:

MDX: https://github.com/mdx-js/mdx/issues/1279
Gatsby: https://github.com/gatsbyjs/gatsby/issues/27120

We'll either need to create our own remark plugin to fix this, or wait until we official support from either [`gatsby-remark-autolink-headers`](https://www.gatsbyjs.com/plugins/gatsby-remark-autolink-headers/) or [`@mdx-js/mdx`](https://github.com/mdx-js/mdx). Judging by [this comment](https://github.com/mdx-js/mdx/issues/1279#issuecomment-700682399) I suspect the change will need to happen on the Gatsby end.

This change may or may not happen anytime soon (still waiting to hear back on the Gatsby side). We might consider patching this ourselves in the interim.

**Comment by jerelmiller** [comment]
Moved the custom IDs over to #111. The rest of this ticket is addressed so I'm going to go ahead and consider this done!
