### ISSUE TITLE
Issue: Acceptable use policy

### ISSUE THREAD

**Issue by lolofofo056** [newrelic/docs-website#7819]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/licenses/license-information/general-usage-licenses/acceptable-use-policy/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@lolofofo056 sorry, what was the issue with this doc? Not seeing a description of the issue. Thank you !
