### ISSUE TITLE
NR1 pay model page for data retention adjustment does not include reference that feature is limited by PRO tier or higher

### ISSUE THREAD

**Issue by stowelll** [newrelic/docs-website#7820]
## How can we make our docs better?

Our data retention page for NR1 pay model does not explain what tier level you need to edit/extend data retention, which I believe requires PRO. https://docs.newrelic.com/docs/data-apis/manage-data/manage-data-retention#requirements

Pricing tiers graphic on docs shows PRO as being required for extending retention https://newrelic.com/pricing

**Comment by zuluecho9** [comment]
thanks @stowelll. 

Fixing with PR https://github.com/newrelic/docs-website/pull/7895
