### ISSUE TITLE
Broken link Issue: Service level management: meet service level targets by defining service boundaries and setting expectations

### ISSUE THREAD

**Issue by EricCapponi** [newrelic/docs-website#7839]
This link is broken:
[Service characterization guide](https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/optimize-slm-guide/docs/new-relic-solutions/observability-maturity/operational-efficiency/sc-implementation-guide/#improvement-process).

**Comment by barbnewrelic** [comment]
@EricCapponi  Thanks for reporting this broken link! I'll try to track down where it's supposed to go.
