### ISSUE TITLE
Issue: AWS Lambda for sending CloudWatch logs

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/docs-website#7847]
## How can we make our docs better?

Confusion during setup, where a Cloudwatch log subscription was set up for the Cloudwatch log group of the ingestion function itself. 

Users should be sure that there are no log subscriptions on the ingestion function itself. 

In the docs, the process includes setting up a trigger on the log ingestion function (in Lambda console) but if a subscription was set up instead (in Lambda console), this could lead to a cascade of logs generated and logs being sent.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@maxlemieux  Thanks for pointing this out! I will ask our log SMEs for help with rewording this important clarification.
