### ISSUE TITLE
Issue: REST API calls for alerts

### ISSUE THREAD

**Issue by daffinito** [newrelic/docs-website#7854]
## How can we make our docs better?

The "[learn about NerdGraph, our preferred API](https://docs.newrelic.com/docs/infrastructure/new-relic-infrastructure/infrastructure-alert-conditions/rest-api-calls-new-relic-infrastructure-alerts)" link doesn't go to the NerdGraph docs. I think the target should be the following instead:

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/alerts-nerdgraph/nerdgraph-api-examples

Or possibly this more generic one:

* https://docs.newrelic.com/docs/apis/nerdgraph/get-started/introduction-new-relic-nerdgraph

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/rest-api-alerts/rest-api-calls-alerts/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 102.0.5005.61
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
Fixed with https://github.com/newrelic/docs-website/pull/7862
