### ISSUE TITLE
Issue: Updated public minion IP address ranges

### ISSUE THREAD

**Issue by pgalvarez-elsevier** [newrelic/docs-website#7865]
## How can we make our docs better?

* Is something confusing?
The fact that you point us to your "daily" IP ranges list at https://s3.amazonaws.com/nr-synthetics-assets/nat-ip-dnsname/production/ip.json (via https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips/) and that the IP ranges in there are out of date (in comparison with https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/administration/new-synthetic-public-minion-ips/ ) is what makes everything confusing.

* Is something inaccurate or missing?
What I highlighted above. Inaccuracy is the problem in this case.

* Were you unable to complete a task? (What task?)
Well, CloudFlare bot management is blocking New Relic public minions. Unsure if they have your IPs in their systems when responding to requests or how do they do it. That's a question for them I guess.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/administration/new-synthetic-public-minion-ips/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @pgalvarez-elsevier. Thanks for submitting this ticket. We currently have some work scheduled for the next 2 weeks to address our public minion IPs docs, namely combining our two separate docs and updating the information for accuracy. We've been eager to combine these two and this was a great reminder!
