### ISSUE TITLE
Issue: Browser Pro agent features irrelevant link

### ISSUE THREAD

**Issue by adjohn** [newrelic/docs-website#7866]
## How can we make our docs better?

There's a link to browser pro agent features which takes you to the page you're already on.

**Comment by barbnewrelic** [comment]
@adjohn  Just following up: Your issue is not linking to a specific doc. Do you happen to remember where you discovered this? Please let me know so we can proceed with fixing this issue. Thanks again!

**Comment by barbnewrelic** [comment]
@adjohn  I'm going to close this issue and see if I can find the circular link as part of other browser monitoring doc updates. But if you happen to run across it again, please provide the doc page and we'll fix asap. Thanks again!
