### ISSUE TITLE
Issue: Synthetic monitor public minion IPs

### ISSUE THREAD

**Issue by andy-at-smith** [newrelic/docs-website#7874]
It would be helpful to include a Last Modified timestamp on these pages, to allow a more educated guess at whether updates are required on our side.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips/
* **OS**: Ubuntu
* **Browser**: Firefox 100.0
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @andy-at-smith. Thanks for submitting this ticket. We currently have some work scheduled for the next 2 weeks to address our public minion IPs docs. Thanks a bunch for passing this suggestion along.
