### ISSUE TITLE
Issue: Google Cloud Run monitoring integration

### ISSUE THREAD

**Issue by pasayazici** [newrelic/docs-website#7880]
This integration yields some metrics in our Cloud Run application. 
But how do we get the metrics of the execution times of the methods or related services.
I could not find how to install the NewRelic agent. 
Because it is a serverless Google Cloud Run application. 
I'll be happy if you can help me.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/google-cloud-platform-integrations/gcp-integrations-list/google-cloud-run-monitoring-integration
* **OS**: Windows 10
* **Browser**: Chrome 102.0.0.0
* **Device**: Unknown

**Comment by pasayazici** [comment]
https://docs.newrelic.com/docs/apm/agents/net-agent/other-installation/install-net-agent-docker-container/

I followed the instructions in the link.
I hosted my .Net6 WebApi Application on Google Cloud Run(Serverless).
I saw my app is added under https://one.newrelic.com -> Services-APM.
But it does not collect any data.
When I run my application to local machine, it collects data.

**Comment by pasayazici** [comment]
You can see the Dockerfile below.

`# This example uses .NET 6.0.  For other versions, see https://hub.docker.com/_/microsoft-dotnet-sdk/
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

WORKDIR /app

# The runtime tag version should match the SDK tag version
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
COPY ./nuget.config ./


WORKDIR /src

# Restore your application
COPY ["src/LogTest.Api/LogTest.Api.csproj", "src/LogTest.Api/"]
RUN dotnet restore "src/LogTest.Api/LogTest.Api.csproj"
COPY . .

# Build your application
WORKDIR "/src/src/LogTest.Api"
RUN dotnet build "LogTest.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "LogTest.Api.csproj" -c Release -o /app/publish


FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_FORWARDEDHEADERS_ENABLED=true

# Install the agent
RUN apt-get update && apt-get install -y wget ca-certificates gnupg \
&& echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list \
&& wget https://download.newrelic.com/548C16BF.gpg \
&& apt-key add 548C16BF.gpg \
&& apt-get update \
&& apt-get install -y newrelic-netcore20-agent

# Enable the agent
ENV CORECLR_ENABLE_PROFILING=1 \
CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A} \
CORECLR_NEWRELIC_HOME=/usr/local/newrelic-netcore20-agent \
CORECLR_PROFILER_PATH=/usr/local/newrelic-netcore20-agent/libNewRelicProfiler.so \
NEW_RELIC_LICENSE_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx \
NEW_RELIC_APP_NAME=LogTest.Api

WORKDIR /app


ENTRYPOINT ["dotnet", "LogTest.Api.dll"]`

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
