### ISSUE TITLE
Issue: Understand and manage data ingest

### ISSUE THREAD

**Issue by ferdinand-p** [newrelic/docs-website#7887]
## How can we make our docs better?

* Were you unable to complete a task? (What task?)
* `Broken link for "Data Ingest Governance"`

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/manage-data/manage-data-coming-new-relic
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 102.0.5005.61
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Fixing this in a PR later.

**Comment by zuluecho9** [comment]
thank you @ferdinand-p !
