### ISSUE TITLE
Issue: Create and update key transactions

### ISSUE THREAD

**Issue by hroseross** [newrelic/docs-website#7893]
## How can we make our docs better?

Hello! In this doc, the instructions for adding key transactions do not work in the "new" view (which is also the default view now). Customers need to toggle back to the old view to be able to add key transactions. See this Slack thread for more discussion: https://newrelic.slack.com/archives/C7JF8U5P0/p1654277839242399

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/transactions/key-transactions/create-update-key-transactions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
fixed with https://github.com/newrelic/docs-website/pull/7894. thanks @hroseross
