### ISSUE TITLE
Issue: Login and password issues

### ISSUE THREAD

**Issue by ronnessim** [newrelic/docs-website#7902]
## Doc doesn't cover how to reach support if you can't log in to your account to get help logging in

This document doesn't cover the case where something can't be resolved using self-serve solutions. I can't log in to my account so I can't create a support ticket, and I can't reach anyone to help. There is a bug that showed up this week when a user has multiple accounts associated with their email. Resetting the password on the second account (one created after) results in the user only being able to log in once, then never again. 

Missing information:

- How to report an outage/problem with the service if you can't log in 
- Where to check if there is a page that indicates the status of all systems
- How to contact newrelic support if you can't log in to your account to create a ticket

Because of this I still can't log in to my account and I can't reach anyone so it's a deadlock situation, caused by the incomplete documentation that should tell me how to resolve this. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@ronnessim sorry about the trouble. I'm attempting to find you some help.

**Comment by ronnessim** [comment]
@zuluecho9 I think I have the reverse problem - I can log in to the original account but not the second account. This was working fine, but since recent changes, something broke. I can reset the password and log in once but after that first login the password which worked immediately after the reset no longer works. I suspect a code bug was introduced in the last 5-7 days. Everything was good until something was updated at NewRelic.

**Comment by ronnessim** [comment]
Note that I tried changing the email address on the 1st account so that I could separate them, but that didn't work either, and I also tried in an in-private browsing session and on a completely different PC. Neither of these worked.

**Comment by zuluecho9** [comment]
@ronnessim I'll direct you to this support email: account_recovery (at) newrelic.com. 

Sorry about the trouble. We'll look into potential fixes for this.
