### ISSUE TITLE
Issue: Simple, scripted, or scripted API (non-ping) errors

### ISSUE THREAD

**Issue by Pallav-552** [newrelic/docs-website#7913]
##  Response not in valid json format?

`{ entity: { SMS: [ [Object], [Object], [Object] ] }, warnings: [] }`

Obove response is coming from below console.log

//Define expected results using callback function.
function callback (err, response, body){
//Log JSON results from endpoint to Synthetics console.
  **console.log(body)**

   assert.ok(response.statusCode == 200, 'Expected 200 OK response');
 
}
 
//Make GET request, passing in options and callback.
$http.get(options,callback);

Please help here, I am new to synthetics.

**Comment by x8a** [comment]
Hey, @Pallav-552! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
