### ISSUE TITLE
[Dashboards] Set up dashboards for instrumentation 

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#793]
## Summary 
We want to set up similar dashboards to how we had them on the old site. We will want to recreate them using our new action names. 

There are the dashboards we would like to recreate: 
* [Docs Site Search Stats](https://one.newrelic.com/launcher/dashboards.launcher?pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmRhc2hib2FyZCIsImVudGl0eUlkIjoiTnpJM01EVTVmRlpKV254RVFWTklRazlCVWtSOE1UWTVNRFE1IiwidXNlRGVmYXVsdFRpbWVSYW5nZSI6ZmFsc2UsImlzVGVtcGxhdGVFbXB0eSI6ZmFsc2V9&platform[$isFallbackTimeRange]=false)
* [JP Site usage ](https://one.newrelic.com/launcher/dashboards.launcher?pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmRhc2hib2FyZCIsImVudGl0eUlkIjoiTnpJM01EVTVmRlpKV254RVFWTklRazlCVWtSOE9EQTNORFkwIiwidXNlRGVmYXVsdFRpbWVSYW5nZSI6ZmFsc2UsImlzVGVtcGxhdGVFbXB0eSI6ZmFsc2V9&platform[$isFallbackTimeRange]=false)
* [Customer feedback](https://one.newrelic.com/launcher/dashboards.launcher?pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmRhc2hib2FyZCIsImVudGl0eUlkIjoiTnpJM01EVTVmRlpKV254RVFWTklRazlCVWtSOE16UXlORFU0IiwidXNlRGVmYXVsdFRpbWVSYW5nZSI6ZmFsc2UsImlzVGVtcGxhdGVFbXB0eSI6ZmFsc2V9&platform[$isFallbackTimeRange]=false&platform[accountId]=727059&platform[filters]=ImB0YWdzLmNyZWF0ZWRCeWAgPSAnY2xhbmdvc2NoQG5ld3JlbGljLmNvbSci) 
* [404 route paths ](https://one.newrelic.com/launcher/dashboards.launcher?pane=eyJuZXJkbGV0SWQiOiJkYXNoYm9hcmRzLmRhc2hib2FyZCIsImVudGl0eUlkIjoiTnpJM01EVTVmRlpKV254RVFWTklRazlCVWtSOE1qUTJNREU0IiwidXNlRGVmYXVsdFRpbWVSYW5nZSI6ZmFsc2UsImlzVGVtcGxhdGVFbXB0eSI6ZmFsc2V9&platform[$isFallbackTimeRange]=false&platform[accountId]=727059&platform[filters]=ImB0YWdzLmNyZWF0ZWRCeWAgPSAnY2xhbmdvc2NoQG5ld3JlbGljLmNvbSci)

You can refer to this [spreadsheet](https://docs.google.com/spreadsheets/d/1VmgEp4n-GA3wvIjBy7rJQn3H7k_ytoqxvYG50X8xeAs/edit#gid=0) for old and new naming of actions. 

## AC 
* [ ] Create site search stats dashboard 
* [ ] Create jp site usage stats 
* [ ] Create 404 route paths dashboard 
* [ ] Create customer feedback dashboard

**Comment by jpvajda** [comment]
waiting on the instrumentation to get deployed before we could build out those dashboards

**Comment by zstix** [comment]
🎉
