### ISSUE TITLE
Issue: Guided install overview

### ISSUE THREAD

**Issue by Julien4218** [newrelic/docs-website#7935]
The code snippet is outdated, we no longer reference github but download.newrelic.com
If you could, please update the snippet, here is a more recent output example

curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=<HIDDEN> NEW_RELIC_ACCOUNT_ID=<HIDDEN> /usr/local/bin/newrelic install
Starting installation.
Installing New Relic CLI v0.50.0
Installing to /usr/local/bin using sudo

 _   _                 ____      _ _
| \ | | _____      __ |  _ \ ___| (_) ___
|  \| |/ _ \ \ /\ / / | |_) / _ | | |/ __|
| |\  |  __/\ V  V /  |  _ |  __| | | (__
|_| \_|\___| \_/\_/   |_| \_\___|_|_|\___|

Welcome to New Relic. Let's set up full stack observability for your environment.
	

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
Closing this because it was fixed in PR 7936.
