### ISSUE TITLE
Uncollapse on page collapsers when sending context to vendor 

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#795]
## Summary 
When we send our page context to the vendor, we need to make sure that all collapsers are uncollapsed so that they have full view of all the text on the page. Hopefully this can be accomplished by passing in a query parameter that will uncollapse all the collapsers and we can grab that context. 

## AC 
* [ ] collapsers all uncollapse when query parameter is sent in via url 
* [ ] send context with uncollapsed collapsers

**Comment by jerelmiller** [comment]
Collapsers should already be collapsed as its default state. Is there a bug or something not working right?

**Comment by roadlittledawn** [comment]
or maybe @caylahamann means the collapsers need to be un-collapsed and showing all their content so none of it is hidden when viewing the context in Smartling?

**Comment by caylahamann** [comment]
yes sorry they should be uncollapsed!
