### ISSUE TITLE
In some cases, outdated context will be sent to vendor

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#797]
## Summary 
When we send the context for our vendor, we take the html off of docs-preview.newrelic.com at that moment. However, if the sending to our context happens before the new content is built and deployed on amplify, we will have an outdated version of that html being sent. How do we ensure that always send the most recent html and not before amplify has deployed it?

In most cases this will not be an issue, but if there is a manual trigger of `Send content to be translated` or the cron job of `Send content to be translated` occurs really closely to a recent merge to `main`, then we will have outdated content for context. 

### Considerations 

* cron job to send content to vendor is set in the middle of the night (less likely that there was a recent merge to main that won't be captured in the context) 
* if there is a manual trigger, ensure the last release was deployed on amplify

**Comment by jpvajda** [comment]
Put this in GA-sustainment as it' not a launch blocker.

**Comment by jpvajda** [comment]
@caylahamann I was discussing this issue with Julien, and I'm curious how much effort this may be to trying get it in place before GA.

**Comment by jpvajda** [comment]
We confirmed with Julien that this is ok being a post GA thing

**Comment by jpvajda** [comment]
We discussed this in detail, and decided this is not an issue, and we have workflows in place to be sending content across for translation on an interval and also we can always kick off a request for translations manually.
