### ISSUE TITLE
`On-host` integrations are migrated as `Host` integrations

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#801]
### Description

Various taxonomy terms that contain `on-host` in them are being brought in as just `host`

For instance, compare:

* https://docs.newrelic.com/docs/integrations/host-integrations
* https://docs-preview.newrelic.com/docs/integrations/host-integrations

I suspect this is related to a silly thing Drupal does where it removes "short" words like `on` from URLs.

### Expected behavior

Migrate these taxonomies based on their title, not the URL/path.

### Additional context

Happening to several categories in https://docs-preview.newrelic.com/docs/integrations/host-integrations

**Comment by paperclypse** [comment]
It would be good to figure out if this migration issues is caused by the `-` symbol or short words like "on" so that we can look out for this issue.

**Comment by austin-schaefer** [comment]
Adding a launch-blocker label on this. Theoretically fixable after launch, but much easier to fix pre-launch so we don't have to do a bunch of cleanup.

**Comment by jerelmiller** [comment]
See [this comment](https://github.com/newrelic/docs-website/issues/566#issuecomment-769508302) as to why this is VERY difficult. This page looks like an auto generated page, which means it adheres to our rules for autogenerating content. That link will give you a good explanation as to why this is difficult to achieve.

**Comment by austin-schaefer** [comment]
Possibly related to #566?

**Comment by jpvajda** [comment]
I'm not sure what the actual issue for this now as it seems the term on host is now used in these pages. Given this came from a migration issued identified on Feb 5th, I'm going to close and any changes to these pages can be done as needed by content writers.
