### ISSUE TITLE
add a little bit more padding around buttons

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#802]
### Is your feature request related to a problem? Please describe

I think it would be great if we had a little bit of padding around the bottom of our buttons. As it is, the text and button are pretty jammed up together there.

<img width="728" alt="button padding screenshot" src="https://user-images.githubusercontent.com/7992384/107091341-7a63c600-67b6-11eb-8679-ba8403c41e9f.png">

### Describe the solution you'd like

Let's add a little padding there under our buttons.

### Describe why this important to you

It's a minor thing that nags at me a little every time I see it. :)

**Comment by austin-schaefer** [comment]
The buttons should also be centered in the column—right now they float to the left awkwardly. This is something we should prioritize soon—it's an increasingl common pattern across the site.

**Comment by jerelmiller** [comment]
@austin-schaefer if you can help me name a component for this pattern, I'll build this for you 😄

**Comment by austin-schaefer** [comment]
@jerelmiller : Hah, what's involved in component naming? How about just `stitched-path-buttons`? :)

**Comment by paperclypse** [comment]
I'm so excited about this! Thanks @caylahamann!
