### ISSUE TITLE
Network monitoring page is showing a diagram image with the old logo

### ISSUE THREAD

**Issue by egironanr** [newrelic/docs-website#8032]
## How can we make our docs better?

At the bottom of [this page](https://docs.newrelic.com/docs/network-performance-monitoring/get-started/npm-introduction/) we are showing the old logo in the diagram instead the new one ;) 

<img width="927" alt="image" src="https://user-images.githubusercontent.com/100843681/173547901-f276b127-9d7e-45d2-a80c-2d5118078e67.png">

**Comment by rhetoric101** [comment]
@egironanr thanks for pointing out the old logo. This is being fixed in PR #8042, so I am closing this.
