### ISSUE TITLE
The PHP agent API "View all methods" in the left nav returns a 404

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#804]
### Description

The PHP agent API "View all methods" left nav link is returning a 404. 

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/agents/php-agent/php-agent-api
2. In the left nav, click on **View all methods**
4. See 404 error

### Expected behavior

What's strange is that the link in step 1 has the content I expect to see after clicking **View all methods**.

**Comment by paperclypse** [comment]
I notice that this is true for the Python **View all calls** link too: https://docs-preview.newrelic.com/docs/agents/python-agent/python-agent-api

**Comment by austin-schaefer** [comment]
This might be true of all the agents that use this page type. That's a number of APM agents, iOS and Android agents, and the Browser agent.

**Comment by jerelmiller** [comment]
@austin-schaefer @paperclypse how do you feel about removing that "View all methods" link and just having the parent "Python agent API" (as well as other agent pages) be the link for that page?

**Comment by austin-schaefer** [comment]
@jerelmiller I'm fine with that.

**Comment by paperclypse** [comment]
@jerelmiller Works for me too!

**Comment by jerelmiller** [comment]
Excellent!

**Comment by jpvajda** [comment]
should be covered by : https://github.com/newrelic/docs-website/pull/851
