### ISSUE TITLE
In the left nav, an apostrophe isn't encoded correctly

### ISSUE THREAD

**Issue by paperclypse** [newrelic/docs-website#805]
On this page https://docs-preview.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/view-policies-conditions-our-products, in the left nav it looks like an apostrophe isn't being encoded right: 

**View an entity& # 0 3 9; s policies and conditions**

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-policies/view-policies-conditions-our-products
2. In the left nav, find **View an entity&#039;s policies and conditions**.

### Expected behavior

I would expect to see **entity's**.

### Screenshots

<img width="278" alt="apostrophe not encoding right" src="https://user-images.githubusercontent.com/7992384/107094927-bc900600-67bc-11eb-85ba-26890e9bee47.png">

**Comment by paperclypse** [comment]
I'm seeing this same issue here: https://docs-preview.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-violations/view-alert-violations-our-products

**View an entity&#039;s alert violations**

**Comment by austin-schaefer** [comment]
Barb noted the same issue affects https://docs-preview.newrelic.com/docs/insights/use-insights-ui/manage-dashboards/copy-chart-another-insights-accounts-dashboard

**Comment by austin-schaefer** [comment]
Possibly related to #801 ?
