### ISSUE TITLE
Issue: Introduction to mobile monitoring

### ISSUE THREAD

**Issue by Vivek-Raman** [newrelic/docs-website#8099]
## How can we make our docs better?

There's a type on this page: https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring/
The word "environment" is misspelt as "environnment".

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile/get-started/introduction-mobile-monitoring/
* **OS**: Windows 10
* **Browser**: Chrome 102.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
I fixed it with PR #8102. 

Thanks for reporting it!
