### ISSUE TITLE
Issue: Requirements for the infrastructure agent

### ISSUE THREAD

**Issue by ajmeese7** [newrelic/docs-website#8100]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

The task I was unable to complete is installation of the software. I ran the command that the site recommended to me and this is the error message that I got:

![NewRelic_error](https://user-images.githubusercontent.com/17814535/174462536-cb65a39e-c354-498c-90ef-f4e8af32e72c.png)

Note that the API key and the whole user ID have been obscured for security reasons, but I guarantee that they are correct because the entire command was copied directly from the site's installation directions on my dashboard. Zorin runs all Ubuntu software since it is a highly customized kernel fork, so the OS should be supported and I should have no issues installing this software. Any guidance on how to move forwards would be appreciated, the documentation was not very enlightening on the next steps to take in my situation.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent/
* **OS**: ZorinOS 16 (Ubuntu-like OS)
* **Browser**: Brave
* **Device**: Custom

**Comment by x8a** [comment]
Hey, @ajmeese7! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
