### ISSUE TITLE
get pullreminders installed on slack channels

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#811]
https://pullreminders.com/

to aid in us keep track of PRs lets get this installed so we can use it in our channels

**Comment by jpvajda** [comment]
I've made a request to global IT for this, so let's see what they say

**Comment by austin-schaefer** [comment]
Would be interested in this for content-side PRs as well!

**Comment by jpvajda** [comment]
so pullreminders is being depracated so I'm testing out Toast. https://datanerd-staging.slack.com/apps/AC6M092SD-toast

**Comment by jpvajda** [comment]
We are thinking of using this: https://newrelic.slack.com/apps/AC6M092SD-toast

or https://slack.com/help/articles/232289568-GitHub-for-Slack

or you could use a desktop app like this: 

https://www.gitify.io

**Comment by jpvajda** [comment]
closing as won't do for now as we are doing OK without it
