### ISSUE TITLE
Issue: .NET agent: compatibility and requirements for .NET Framework

### ISSUE THREAD

**Issue by miksh7** [newrelic/docs-website#8121]
## How can we make our docs better?

* Does NET Agent support Windows 11?
* Does NET Agent support gRPC?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/net-agent-compatibility-requirements-net-framework
* **OS**: Windows 10
* **Browser**: Chrome 102.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @miksh7! Can you please tell us what problem you found in the doc?

**Comment by miksh7** [comment]
Please indicates on the page if
if NET Agent support Windows 11 or not
if NET Agent support gRPC or not

**Comment by x8a** [comment]
I'll check with the team and get back to you!

**Comment by nr-ahemsath** [comment]
@miksh7 Can you elaborate on what you mean by "support gRPC"?  Are you asking if the .NET agent automatically instruments a specific GRPC client library?

Re: Windows 11 support, as far as I know there is no reason why the .NET agent will not work in a Windows 11 environment; however, we have not done any formal testing of the agent on Windows 11.

**Comment by miksh7** [comment]
@nr-ahemsath,  correct, if the .NET agent automatically instruments a communication using GRPC protocol. Something similar to Java Agent (https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent#http-messaging):

> The agent automatically instruments the following HTTP clients and messaging services. 
> - Akka HTTP 2.4.5 to latest
> - Akka Http Core from 0.4 to latest
> - AsyncHttpClient 2.0.0-RC1 to latest
> - **gRPC 1.4.0 to latest**

**Comment by x8a** [comment]
Thanks a lot, @nr-ahemsath!
