### ISSUE TITLE
Issue: Step 4: Instrument your own Lambda functions

### ISSUE THREAD

**Issue by Xyz426** [newrelic/docs-website#8137]
HI team, nice to meet you!

## How can we make our docs better?

For Lambda console UI configuration, Does this way also support other languages, I only see Python, NodeJs, Java from the [documentation](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/#console)

If it is not currently supported, will other languages ​​be supported in the future?

**Comment by x8a** [comment]
Hi, @Xyz426! We don't have any information about new supported languages at the moment, but for compatibility info, you can have a look at [this doc](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/get-started/compatibility-requirements-aws-lambda-monitoring).

Let me know whether that helps!

**Comment by Xyz426** [comment]
Thanks reply!
I would like to ask, the [Lambda console UI configuration](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/#console) way on the picture below only shows the handlers of three languages: python, nodejs, and java. What are the handlers of other languages?

<img width="919" alt="image" src="https://user-images.githubusercontent.com/44676710/174999724-87412bc5-2827-4faa-93a1-42d1c6abfba8.png">

**Comment by Xyz426** [comment]
Thanks, reply :), the last question:

Will .NET and Go be supported in the future? Provide no-code-change instrumentation like Java, Python, NodeJs?

Is there any way for other languages ​​like `Ruby` ​​to use work in [Lambda console UI configuration](https://docs.newrelic.com/docs/serverless-function-monitoring/aws-lambda-monitoring/enable-lambda-monitoring/instrument-your-own/#console)?

**Comment by mrickard** [comment]
@Xyz426 Go functions are compiled, so there's no way of dynamically decompiling them to redefine the handler and dependencies with instrumentation. For Go, you have to wrap the handler in your codebase before compiling. 

In the case of .NET, the language spec doesn't support dynamically redefining functions, as far as I know. If that's changed, then newer versions of the runtime would have a chance of no-code-change wrapping. 

For other languages, we're certainly open to seeing proofs of concept and PRs to support no-code-change wrapping for runtimes that support it. (That support undoubtedly varies from language to language and runtime to runtime.)

**Comment by x8a** [comment]
Hey, @Xyz426! Let us know whether you need more help. Otherwise, I'll close this issue at the end of the week.

Thanks a lot!
