### ISSUE TITLE
Issue: Synthetic scripted browser reference (Chrome 100 and higher)

### ISSUE THREAD

**Issue by tdallmann** [newrelic/docs-website#8141]
## Issue with sample code

The following code snippet does not work:

`const element = await $webDriver.wait($selenium.until.elementLocated(locator), timeout, 'Timed-out waiting for element to be located using: '+locator);`
`await $webDriver.wait($selenium.until.elementIsVisible(element), timeout, 'Timed-out waiting for element to be visible using ${element}');`
`return await $webDriver.findElement(locator);`

The problem seems to be that the first line does not actually return an element.  To correct this I changed it to this:

`await $webDriver.wait($selenium.until.elementLocated(locator), timeout, 'Timed-out waiting for element to be located using: '+locator);`
`const webElement = await $webDriver.findElement(locator)`
`await $webDriver.wait($selenium.until.elementIsVisible(element), timeout, 'Timed-out waiting for element to be visible using ${element}');`
`return await $webDriver.findElement(locator);`

_Note - this same issue is present in sample code provided in other docs on the site._

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100
* **OS**: Mac OS 10.15.7
* **Browser**: Safari 15.5
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @tdallmann. I've talked with a couple Relics on our synthetics team, and one of our GTS team members will be replying to you sometime tomorrow to get sorted. :)

**Comment by akristen** [comment]
Hi again @tdallmann. Apologies for the run-around. The support team isn't having any issues with the original code, so they think it might be something on your end. We recommend reaching out to our support team at https://support.newrelic.com/s/support, or asking our community forum: https://discuss.newrelic.com/
