### ISSUE TITLE
New Relic and Atlas MongoDB monitoring

### ISSUE THREAD

**Issue by kolesnikovaleks** [newrelic/docs-website#8143]
Help me please. How to connect New Relic to Atlas MongoDB ([MongoDB Cloud | MongoDB](https://www.mongodb.com/cloud)) for cluster monitoring?

https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb-monitoring-integration/#install
This instruction does not help me, commands for the OS are used

**Comment by barbnewrelic** [comment]
@kolesnikovaleks  If there is something inaccurate or missing in the documentation, can you please provide some more detail about what you discovered? Or, if you need help with the installation itself, it's best to file a support ticket. Hope this helps!

**Comment by kolesnikovaleks** [comment]
@barbnewrelic The documentation states the connection for physical mongodb servers, I need a cloud provider like Atlas. If this question is not for you, please close the ticket. Thank you.

**Comment by barbnewrelic** [comment]
@kolesnikovaleks  Thanks for clarifying. Yes, that would be a question for support.
