### ISSUE TITLE
Issue: Introduction to browser monitoring

### ISSUE THREAD

**Issue by manorfreeman** [newrelic/docs-website#8168]
## How can we make our docs better?

There's a small typo in this docs page that may be worth fixing in the following sentence:

```
This data can helps= you understand how users experience your site, both from visual and responsiveness standpoints.
```

![image](https://user-images.githubusercontent.com/1342871/175357583-a95c8d7d-1938-4d39-b70d-183d811ddce0.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/browser-monitoring/getting-started/introduction-browser-monitoring/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
@manorfreeman thanks for reporting this! I just queued up a fix in #8169
