### ISSUE TITLE
Search results link to old doc site. 

### ISSUE THREAD

**Issue by cmacnaug** [newrelic/docs-website#817]
### Description

When you click on link from search results it links to the old docs site. 

### Steps to reproduce

1. Go to 'https://docs-preview.newrelic.com/docs/integrations/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration?q=prometheus&size=n_10_n'
2. Click on Any of the links
3. Note that you are linked to the old docs site. 

### Expected behavior

Linked to new doc site.

**Comment by jerelmiller** [comment]
Hey @cmacnaug, thanks for opening this issue!

This is actually intended behavior for us during the migration process. We haven't indexed the docs preview site yet and wanted to maintain accuracy with the search index. We only sync once a week-ish. We wanted to avoid "bugs" where someone clicked on a search result link and saw a 404 page. 

Once the new docs site goes public, these links should work as expected.
