### ISSUE TITLE
Issue: Browser apps index

### ISSUE THREAD

**Issue by manorfreeman** [newrelic/docs-website#8171]
## How can we make our docs better?

Small typo: 
![image](https://user-images.githubusercontent.com/1342871/175369220-092fa1b4-e3ef-4d95-94e2-5aa178a23d3f.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/browser-apps-index
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 102.0.0.0
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Thanks for catching another one of these @manorfreeman !
