### ISSUE TITLE
Issue: Node.js: Configure logs in context should clarify this is only for Winston and Pino logs

### ISSUE THREAD

**Issue by brnhensley** [newrelic/docs-website#8187]
## How can we make our docs better?

* Is something confusing? 

According the Node engineers "We only support Winston and pino" logs with this feature. But this doc doesn't mention Pino or Winston until the [_Manual logs in context option_ section](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-nodejs/#configure-nodejs). Most of the doc is about the[ automatic logs in context option](https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-nodejs/#automatic) and never mentions that these steps do nothing if you don't already have Pino or Winston logging in your app.

From this post in the community: https://discuss.newrelic.com/t/log-forwarding-in-context-from-a-nodejs-docker-container-is-not-working/187145/6

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-nodejs/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
