### ISSUE TITLE
Issue: 경고 및 응용 인텔리전스 소개

### ISSUE THREAD

**Issue by mb-newrelic** [newrelic/docs-website#8197]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/kr/docs/alerts-applied-intelligence/overview
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 101.0.4951.64
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @mb-newrelic! Is there anything in the doc you found confusing? Thanks!

**Comment by x8a** [comment]
Hey, @mb-newrelic! Let us know whether you need more help. Otherwise, I'll close this issue at the end of the week.

Thanks a lot!
