### ISSUE TITLE
Mobile ingest documentation does not include MobileRequest events.

### ISSUE THREAD

**Issue by jameschan2** [newrelic/docs-website#8206]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
Yes, Mobile Data ingest is affected by the MobileRequest event type, but it is not present. This calls into question whether or not this data type is actually metered against billing.

* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/manage-data/manage-data-coming-new-relic/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Wanted to follow up with you @jameschan2. This is the PR to update that doc. We also included another event type not reflected in there. Thanks so much for catching it! https://github.com/newrelic/docs-website/pull/8259
