### ISSUE TITLE
Document the Docs site functionality

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#823]
We have needs to document how the Doc site works in terms of things like architecture, localization, github actions, etc. 

### The audience 

- New engineers that will work on the site.
- Technical contributors who need to know who things work to submit code
- Localization team members so they understand our translation process 
- Engineers leaders of New Relic who may be curious what and how we did things
- Gatsby Engineers who may be looking at our site for reference as they improve the Gatsby platform.

### Considerations

**Document in our site[wiki](https://github.com/newrelic/docs-website/wiki) things like:**

- How translation process but don’t name specific vendors, just talk about the process  for localization.
- Site architecture, but reference gatsby documentation when needed, no need to rewrite that which already exists.
- Specific technical information for how components work that's not covered already in our gatsby-theme 
- Don’t use individual names in documentation, just focus on teams.
- Share documentation with patrick sullivan  from Gatsby. 

### Final thoughts
- If the code is self explanatory we don't need to write it down in the WIKI, so just use your best judgement. 😄

**Comment by zstix** [comment]
TODO: add acceptance criteria and re-review our estimation.

**Comment by jpvajda** [comment]
I added some clarifications, but I'm sure @zstix has some ideas as well.

**Comment by caylahamann** [comment]
I'm going to work on the localization part of this, I need to write up some documentation anyway tonight

**Comment by jpvajda** [comment]
@caylahamann thank you!

**Comment by zstix** [comment]
I've taken a first-pass at documenting the site architecture here: https://github.com/newrelic/docs-website/wiki/Site-Architecture

I think this should address most of what we would like documented (externally).

**Comment by jerelmiller** [comment]
This is FANTASTIC! I really like the work you did
