### ISSUE TITLE
Issue: Transition to New Relic from Insights

### ISSUE THREAD

**Issue by Aonyiah** [newrelic/docs-website#8263]
I am trying to transition a synthetic monitor from Dev stage into Staging area but I am not sure where to configure that from. 
Please advise. 
![image](https://user-images.githubusercontent.com/13909761/176664831-6866f8cb-eead-467e-9cc6-3af6f7959bdb.png)

**Comment by x8a** [comment]
Hey, @Aonyiah! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
