### ISSUE TITLE
This is a bug! Please fix!

### ISSUE THREAD

**Issue by aulakdekush** [newrelic/docs-website#8308]
```
<!-- Please fill out each section below. This info allows our engineers to 
diagnose your issue as quickly as possible. This repo is public. Anything you 
share here is visible to the world. -->

```
## Steps to reproduce

4. See a Delivery error

## Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by x8a** [comment]
Hey, @aulakdekush! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
