### ISSUE TITLE
This is an enhancement request!

### ISSUE THREAD

**Issue by aulakdekush** [newrelic/docs-website#8309]
`<!--` Please fill out each section below. This info allows our engineers to 
diagnose your issue as quickly as possible. This repo is public. Anything you 
share here is visible to the world. -->

``
## Is your feature request related to a problem? Please describe

A clear and concise description of what the problem is.

## Describe the solution you'd like

A clear and concise description of what you want to happen. What is the expected outcome?

## Describe why this is important to you

Why should we work on this? What use cases does it support?

**Comment by aulakdekush** [comment]
Gracias

**Comment by x8a** [comment]
Hey, @aulakdekush! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
