### ISSUE TITLE
Dockerized Ruby APM documentation

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/docs-website#8312]
## How can we make our docs better?
It would be nice if there was a dedicated docs page for Ruby APM on Docker. Currently, there is only a brief mention of Docker on the [Ruby APM installation page](https://docs.newrelic.com/docs/apm/agents/ruby-agent/installation/install-new-relic-ruby-agent), and the user is expected to have an in depth knowledge of Docker in order to achieve this task.

Other APM products do have more documentation on this, for example: 
* https://docs.newrelic.com/docs/apm/agents/python-agent/installation/install-python-agent-docker/
* https://docs.newrelic.com/docs/apm/agents/java-agent/additional-installation/install-new-relic-java-agent-docker/

Users have been unable to complete the task of installing Ruby APM on their Dockerized Ruby applications: https://discuss.newrelic.com/t/help-installing-ruby/187957

**Comment by GlenOFoghlu** [comment]
Do we have any ETA on when Ruby Docker installation Docs may be present?? I have 
Case
00070680 where a customer is impacted by this.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
