### ISSUE TITLE
Issue: Introduction to pricing models and docs

### ISSUE THREAD

**Issue by Ahmed654321653** [newrelic/docs-website#8314]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/original-accounts-billing/original-product-based-pricing/overview-pricing-models
* **OS**: Windows 10
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @Ahmed654321653! What issue did you find in the docs? Thanks!

**Comment by x8a** [comment]
Hi, @Ahmed654321653! If you don't have any questions, I'll close this issue at the end of the week.

Feel free to open a new one if you find something that doesn't seem right in the documentation. Thanks!
