### ISSUE TITLE
Issue: PHP: Configure logs in context

### ISSUE THREAD

**Issue by Ahmed654321653** [newrelic/docs-website#8315]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-php/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by Ahmed654321653** [comment]
> ## How can we make our docs better?
> * Is something confusing?
> * Is something inaccurate or missing?
> * Were you unable to complete a task? (What task?)
> 
> ### Doc information (don't delete this section)
> * https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-php/
> * **OS**: Unknown
> * **Browser**: Unknown
> * **Device**: Unknown

**Comment by x8a** [comment]
Hey, @Ahmed654321653! What issue did you find in the docs? Thanks!

**Comment by x8a** [comment]
Hi, @Ahmed654321653! If you don't have any questions, I'll close this issue at the end of the week.

Feel free to open a new one if you find something that doesn't seem right in the documentation. Thanks!
