### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by Ahmed654321653** [newrelic/docs-website#8316]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-apps/new-relic-mobile-apps/authentication-alerts/user-settings-authentication
* **OS**: Windows 10
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @Ahmed654321653! What issue did you find in the docs? Thanks!

**Comment by x8a** [comment]
I fixed the issue with PR #8317. Thanks for reporting this!
