### ISSUE TITLE
Issue: Integrations and managed policies

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#8351]
My guess is that this document is missing the role details for the MQ Integration.  Enterprise customers need to the specific role details for each AWS Service.

https://docs.newrelic.com/docs/infrastructure/amazon-integrations/aws-integrations-list/aws-mq-integration/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/amazon-integrations/get-started/integrations-managed-policies/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by homelessbirds** [comment]
Hi @GaPeppy!

I just want to clarify: you’re saying we need to add a description about what Enterprise customers can do for each AWS Service for the MQ integration?

Thanks in advance!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
