### ISSUE TITLE
The Drupal content (English) and Proxy content (Japanese) to be turned into translation vendor format (serialized HTML) so I can create the Translation Memory.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#838]
Step 1: 

The latest  translated proxy maintenance (`pre-D-XXX`) will be the content published on GA.  That content will be converted to MDX for GH, tested and published on Gatbsy at the GA date.

This  recent site change is not instantaneous. The content was picked up on 2/25 (during freeze). The last maintenance was Feb 8th. So any updates (incl Dora) between the 8th and the 25th have to be processed (translated edit, tested)

It will take about 1 week from 2/25 to finish the translation updates. 

Step 2:

During the freeze, we will capture the latest Drupal content (incl. `D-XXX`) => translate it via Proxy => convert it to MDX => load it in GH => publish to Gatsby.

After the translation process I will need the English Drupal HTML and Japanese Proxy HTML to be converted to the `S-ZZZZ` serialized HTML format so I can generate the Translation Memory (TM) that will work for `S-ZZZZ` and to be used moving forward for upcoming maintenances. (I called the files MDX in the picture below but those are the serialized HTML with MDX extension)

**Comment by jpvajda** [comment]
@jmiraNR can confirm when this is ready to be executed on.

**Comment by caylahamann** [comment]
closing this because this work is now outlined in three separate tickets: 
https://github.com/newrelic/docs-website/issues/994
https://github.com/newrelic/docs-website/issues/995
https://github.com/newrelic/docs-website/issues/960
