### ISSUE TITLE
Issue: Install the browser monitoring agent - articulate which javascript files are loaded and 3rd party dependencies

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#8384]
## How can we make our docs better?

Sometimes customers want to know more about which scripts are loaded when installing the NR browser agent and which 3rd party libraries are called.  This is documented in our Github repo in the README and THIRD_PARTY_NOTICES document.  

Can we summarize this content and provide readers a link to the content on Github?  This will support customers who want to self-serve as well as NR staff supporting customers looking for assistance. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by khickey-newrelic** [comment]
Hi @akristen - it's here https://github.com/newrelic/newrelic-browser-agent

**Comment by akristen** [comment]
I've added a section of content in the linked doc alerting customers to the repo's two files. They will be reflected on the docs site at EOD!
