### ISSUE TITLE
Issue: Kafka monitoring integration

### ISSUE THREAD

**Issue by jdezego** [newrelic/docs-website#8405]
1) When I run `apt install nri-kafka` it fails and says the dependency is not met for `nrjmx`, and its says the package is not installable.

2) `apt install nrjmx` does nothing because the package is not found.

3) I have updated my apt-get repositories to include the New Relic repo and still this fails.

Customers are following this doc and it does not work.

**Comment by barbnewrelic** [comment]
@jdezego  Please provide the doc link where this issue originated. We have some PRs in process to update Kafka integration docs, and it's possible this is one of them. Thanks!
