### ISSUE TITLE
Issue: Troubleshooting H12 error from heroku

### ISSUE THREAD

**Issue by speichel** [newrelic/docs-website#8421]
Hoping I can get some direction on how to get the data from heroku site into new relic for troubleshooting an H12 error.  I'm told to use an add-on like new relic from heroku troubleshoot guide to be able to monitor the server-side slow (or failing) transactions.  I did try to follow the steps on New Relic, but the Heroku drain log I created seems to be doing nothing.  Appreciate any help!

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/original-accounts-billing/original-product-based-pricing/switch-new-models/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@speichel Tech Docs team is not a Heroku expert, but I do know we have a doc about installing the Heroku add-on: https://docs.newrelic.com/docs/accounts/install-new-relic/partner-based-installation/heroku-install-new-relic-add/ If this doesn't help, I recommend that you contact support. Hope this helps!

**Comment by speichel** [comment]
I have been following instructions, but seems to be a hang up when i get to this point... i have a paid new relic account, but it doesn't allow me to add on the php:

![image](https://user-images.githubusercontent.com/8750218/178590389-ed649614-612e-48ce-95bc-4d419e964ec9.png)

**Comment by barbnewrelic** [comment]
Please file a support ticket to resolve this issue. Based on what Support says, we would then be able to update this doc as appropriate.
