### ISSUE TITLE
Issue: Microsoft SQL Server monitoring integration

### ISSUE THREAD

**Issue by ASchneider-GitHub** [newrelic/docs-website#8427]
## How can we make our docs better?
Documentation is currently outdated, and says we only support Windows for the MSSQL integration. The `nri-mssql` integration is available through the Linux package manager, and has been confirmed to work. Documentation needs the Compatibility section updated to show Linux support. Additionally, the `Install and activate the integration` section also needs to be updated to include Linux installation steps.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/microsoft-sql/microsoft-sql-server-integration/
* **OS**: Linux
* **Browser**: N/A
* **Device**: N/A

**Comment by ASchneider-GitHub** [comment]
GitHub repo for `nri-mssql` [states](https://github.com/newrelic/nri-mssql#compatibility):
> Note: It also seems to work on Linux for the containerized Linux version of MSSQL

This is partially true. [SQL Server is supported](https://www.microsoft.com/en-us/sql-server/sql-server-downloads) on Windows, Linux, and Docker. The integration is available through Linux package managers, and works correctly.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
