### ISSUE TITLE
Issue: Muting rules: Suppress notifications with signal loss

### ISSUE THREAD

**Issue by Celinala** [newrelic/docs-website#8436]
Hi! I was wondering if I mute an alert that has signal loss turned on without filling gaps from 11pm-7am, will a violation still open if signal loss occurs during the time alert is muted?

Previously I had an alert that would exclude the hours using timestamp and NOT IN, but I received signal loss violations hours later (signal loss occurred about 16 hours before) so this behavior was unexpected.

Thank you.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-notifications/muting-rules-suppress-notifications/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@Celinala, thanks for reaching out to us about notifications! This looks like a good question for our support team, and you can reach them here: http://support.newrelic.com/

I am going to close this issue, but if you have suggestions about how we can improve our docs on this topic, feel free to reopen it.
