### ISSUE TITLE
Issue: Install the browser monitoring agent

### ISSUE THREAD

**Issue by ciufudean** [newrelic/docs-website#8440]
Re this text

> 1. Go to [one.newrelic.com](https://one.newrelic.com/), click Add more data, then click Browser and mobile.

> 2. Follow the instructions in the UI to select which data source for browser monitoring you want to use for your app, such as New Relic Browser.

Looks like some labels and names changed:
1. "Add data" instead of "Add more data"
2. "Browser monitoring" instead of "New Relic Browser"

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/browser-monitoring/installation/install-browser-monitoring-agent
* **OS**: Windows 10
* **Browser**: Chrome 102.0.5005.63
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@ciufudean  Thanks for pointing this out! We have some upcoming work related to browser monitoring installation. We'll be sure to include your issue with that Jira.

**Comment by austin-schaefer** [comment]
Looks like this was fixed recently.
