### ISSUE TITLE
Issue: Technical distributed tracing details image unreadable in dark mode

### ISSUE THREAD

**Issue by brnhensley** [newrelic/docs-website#8446]
## How can we make our docs better?

Using our doc's dark mode some text on this image becomes unreadable:

<img width="677" alt="image" src="https://user-images.githubusercontent.com/48165493/178776626-702d425d-d87f-445a-bcf4-861c917e2c90.png">

vs 

<img width="631" alt="image" src="https://user-images.githubusercontent.com/48165493/178776793-47b7b964-7420-4d90-ab01-cf121f05bfe2.png">

The image needs a background to prevent this.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/distributed-tracing/concepts/how-new-relic-distributed-tracing-works
* **OS**: Mac OS 10.15
* **Browser**: Firefox 102.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@brnhensley thanks for the heads-up on this! I just created PR #8450 to fix this! So, I'm closing this issue.
