### ISSUE TITLE
Step 1, 2, 3 improvements on Home Page

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#846]
Daniel to provide a mockup for how to approach this but the goal here is to make it more clear the 1,2,3 boxes on the home page are actually CTAs

<img width="872" alt="Screen Shot 2021-02-11 at 10 52 21 AM" src="https://user-images.githubusercontent.com/1395158/107677193-41649f00-6c57-11eb-81bc-4932b336632e.png">

### AC

- Make it more obvious that you can click the 1, 2, 3 section
- Open click on steps 1 & 2 in a new tab 
- Ensure we’ve instrumented step 1, 2 and 3 on the home page. 

### Mock up

![image (2)](https://user-images.githubusercontent.com/1395158/107822992-3a638c80-6d3c-11eb-9b16-182e3474f53f.png)

**Comment by jpvajda** [comment]
added mockup we are going to go GA with. removing unblocked label

**Comment by caylahamann** [comment]
@jpvajda does this still need the design needed label?
