### ISSUE TITLE
Issue: Workflows

### ISSUE THREAD

**Issue by jhabhar-mal** [newrelic/docs-website#8479]
I'm not able to add infrastructure condition to workflow, please help

**Comment by bradleycamacho** [comment]
Hey, @jhabhar-mal ! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
