### ISSUE TITLE
Issue: OpenTelemetry setup for services

### ISSUE THREAD

**Issue by JcolemanNR** [newrelic/docs-website#8489]
## How can we make our docs better?

The info formatted in this table doesn't look very professional. I tried changing browser zoom level but it didn't help:
![image](https://user-images.githubusercontent.com/83677148/179316875-e3b21723-7f28-4a3d-8f8b-7b77a68bcc3a.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/more-integrations/open-source-telemetry-integrations/opentelemetry/opentelemetry-setup/
* **OS**: Windows 10
* **Browser**: Chrome
* **Device**: 4k monitor laptop

**Comment by bradleycamacho** [comment]
Thanks for calling this out @JcolemanNR. I'll mess around with cell widths and see what I can do!

**Comment by austin-schaefer** [comment]
Looks like this table was removed at some point, gonna go ahead and close this out.
