### ISSUE TITLE
match the highlights with the references within the content change <code> to <mark> to align the code sections that are highlighted.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#849]
In order to make it more clear that a highlighted block of text relates to a particular value in a doc we want to use the same color treatment for `mark` tags outside of code blocks

example page: https://docs.newrelic.com/docs/agents/java-agent/async-instrumentation/java-agent-api-asynchronous-applications

### Example Visual 

![107805048-a41e6f00-6d19-11eb-930b-18475998ad72](https://user-images.githubusercontent.com/1395158/119192563-97f32d80-ba3d-11eb-8fd0-d3484c7f5901.png)

### Example Code Block

```
/**
* Example showing multi-threaded implementation of requesting data using a parallel {@link Stream}.
*/
@RequestMapping("parallel_stream")
<mark>@Trace(dispatcher = true)</mark> // starts a transaction
public ResponseEntity<String> parallelStream(@RequestParam("ids") List<Long> ids) {
   final Token token = NewRelic.getAgent().getTransaction().<mark>getToken()</mark>;
   List<item> results = ids
           .parallelStream()
           .map(id -> requestItemAsync\(id, token)) // note we're calling a different method than parallelStreamBad
           .filter(item -> item != null)
           .collect(Collectors.toList());
   <mark>token.expire()</mark>;
   return formattedResponse("parallel_stream", results);
}
```

### Example Text Block

```
The agent API calls in this sample are:

* <mark>@Trace(dispatcher = true)</mark>: Tells the agent to start a transaction. For more on this method, see the [Javadoc](http://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/Trace.html).
* <mark>getToken()</mark>: Creates the token which will link the work together. For more on this method, see the [Javadoc](http://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/Transaction.html#getToken()).
* <mark>token.expire()</mark>: Expires the token. This allows the transaction to end. For more on this method, see the [Javadoc](http://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/Token.html#expire())

```

### Acceptance Criteria 

- [ ]  mark tags whether in / or out of a code block, should display the same color.

**Comment by jerelmiller** [comment]
> we want to use the same color treatment for `code` and `mark` and `var` tags

I'm not sure I'd quite agree here, otherwise we'd just use `<code>` or `var` for everything. Mark seems to be something that is meant to really call something out, where `var` is really meant to highlight a snippet of code that a user would expect to replace. 

That being said, I do agree that from a content perspective, we should be using `mark` at the bottom of that code block so the user can better make a connection between them (in fact, this would be a nice feature enhancement. Would be nice if a user could hover over that section at the bottom and see it highlight in the code, but thats for another issue 🙂 ).

**Comment by austin-schaefer** [comment]
Just verified that `mark` is indeed used in both sections of the source doc here, it just gets lost in the migration.

![image](https://user-images.githubusercontent.com/55203603/107805048-a41e6f00-6d19-11eb-930b-18475998ad72.png)

([source doc](https://docs.newrelic.com/docs/agents/java-agent/async-instrumentation/java-agent-api-asynchronous-applications))

@jerelmiller As a longer-term fix, I love doing something with on-hover! Could work for both var and mark!

**Comment by jpvajda** [comment]
@jerelmiller oh let me  clarify it's just the <mark> tags, sorry about the confusion, this  PR example is what we'd like to do, essentially wrap the corresponding definition  in the same color mark.  https://github.com/newrelic/docs-website/pull/853

**Comment by jerelmiller** [comment]
@austin-schaefer I see. Seems that we aren't handling `mark` wrapped with a `code` tag. That seems to be the case here. Good to note that we need to handle that case.

**Comment by jpvajda** [comment]
basically `mark` tags whether in / or out of a code block, should display the same color. 

```
   ```
    /**
    * Example showing multi-threaded implementation of requesting data using a parallel {@link Stream}.
    */
    @RequestMapping("parallel_stream")
    <mark>@Trace(dispatcher = true)</mark> // starts a transaction
    public ResponseEntity<String> parallelStream(@RequestParam("ids") List<Long> ids) {
       final Token token = NewRelic.getAgent().getTransaction().<mark>getToken()</mark>;
       List<item> results = ids
               .parallelStream()
               .map(id -> requestItemAsync\(id, token)) // note we're calling a different method than parallelStreamBad
               .filter(item -> item != null)
               .collect(Collectors.toList());
       <mark>token.expire()</mark>;
       return formattedResponse("parallel_stream", results);
    }
    ```

    The agent API calls in this sample are:

    * <mark>@Trace(dispatcher = true)</mark>: Tells the agent to start a transaction. For more on this method, see the [Javadoc](http://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/Trace.html).
    * <mark>getToken()</mark>: Creates the token which will link the work together. For more on this method, see the [Javadoc](http://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/Transaction.html#getToken()).
    * <mark>token.expire()</mark>: Expires the token. This allows the transaction to end. For more on this method, see the [Javadoc](http://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/Token.html#expire())
    ```

**Comment by jpvajda** [comment]
reopening stale bot. 🤖
