### ISSUE TITLE
Issue: JMX monitoring integration

### ISSUE THREAD

**Issue by gsf** [newrelic/docs-website#8492]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

The page design, with sidebars on left and right and side-scrolling tables in the content section, make browsing difficult and information hard to find.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/jmx-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks @gsf I'll look into this. That table is displaying wrongly.

**Comment by zuluecho9** [comment]
going to close this as we created a task to look into this table issue, which is a mistake. Thank you!
