### ISSUE TITLE
Issue: Set up your Prometheus remote write integration

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#8498]
## How can we make our docs better?

* Please include the list of attributes for all metrics from RemoteWrite, as well as PROM-NRI. These attributes sometimes differ. Please include a list of ootb attributes for the metrics. 

Feel free to reach out for more info!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.5060.114
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
