### ISSUE TITLE
Ability to open images to expand an image to be more visible in another tab.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#850]
a user should be able to open images in larger view, and by doing this we'd want to indicate that an image can be expanded with an interaction icon on the image. 

### AC

1. A user should be able to open just the raw image file in full resolution (same tab or new tab) would satisfy this instead of a lightbox on the same page.

2. Enable the `linkImagesToOriginal` for the `gatsby-remark-images` plugin. Validate build works and there's no weird behavior for images 
3. test how this impact small inline images link to their original and if so are we okay with that.

**Comment by barbnewrelic** [comment]
This one will be so useful! Esp when an image is complex and has teeny tiny text. Also, for me, the caption text is harder to read in Preview site, seems to be a lighter gray or smaller or something, not sure. For example:
Click the image in https://docs.newrelic.com/docs/logs/enable-log-management-new-relic/configure-logs-context/configure-logs-context-apm-agents#why-it-matters
Then check it out in Click the image in https://docs-preview
.newrelic.com/docs/logs/enable-log-management-new-relic/configure-logs-context/configure-logs-context-apm-agents#why-it-matters

**Comment by mmfred** [comment]
We got an issue about how hard it is to read our screenshots: #1259 

It's a real readability issue.

**Comment by roadlittledawn** [comment]
i'm curious if clicking on an image to open just the raw image file in full resolution (same tab or new tab) would satisfy this instead of a lightbox on the same page.

**Comment by jerelmiller** [comment]
@roadlittledawn if we go that route, that should be super easy to do. In fact, its already built into the `gatsby-remark-images` plugin. We just disabled it for the site: https://github.com/newrelic/docs-website/blob/develop/gatsby-config.js#L230

If we want that quick solution for now, we can flip that flag which will wrap the images in an anchor tag.

**Comment by roadlittledawn** [comment]
@jerelmiller yeah exactly! was thinking that could be fairly easy to implement and solve the immediate issue at hand. looks like it's super easy to do. haha. awesome. thanks for pointing that out

**Comment by austin-schaefer** [comment]
@roadlittledawn @jerelmiller I've seen some other sites do that. I still think a full lightbox is a better user experience—it doesn't change the user's context, risk issues with popup blockers, etc. 

AND i love the iterative thinking! If there's something quick we can do and then do something fancier later, I dig it.

**Comment by jpvajda** [comment]
@mmfred the #gatsbyconf contest runs until mar 16th.

**Comment by jpvajda** [comment]
@roadlittledawn if you can estimate the effort, and recap proposed solution in the issue, then we can consider this as hero work in a future sprint. cc @zstix

**Comment by roadlittledawn** [comment]
> @roadlittledawn if you can estimate the effort, and recap proposed solution in the issue, then we can consider this as hero work in a future sprint. cc @zstix

Just added some info re: that in this issue's description

**Comment by jpvajda** [comment]
@roadlittledawn saw an opportunity to put this feature in place, so it should be deployed soon. 🚀
