### ISSUE TITLE
Issue: Create and edit content

### ISSUE THREAD

**Issue by HOALND** [newrelic/docs-website#8508]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/style-guide/writing-docs/processes-procedures/create-edit-content/
* **OS**: Windows 10
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey there @HOALND , I'm closing this issue as it seems that it was filed by mistake. Please let me know if this an error and I'm happy to assist!
