### ISSUE TITLE
Issue: PHP agent configuration

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#8526]
## How can we make our docs better?

Which is the correct default value of newrelic.transaction_tracer.max_segments_cli, 0 or 100000?
![image](https://user-images.githubusercontent.com/846156/179949775-ce14ec6e-2291-4032-a152-3b09d82b3eb0.png)

https://docs.newrelic.com/docs/apm/agents/php-agent/configuration/php-agent-configuration/#inivar-tt-maxsegcli

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/php-agent/configuration/php-agent-configuration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@tanaka-takayoshi I am closing this since it's addressed in #8550.
