### ISSUE TITLE
Issue: Write synthetic API tests

### ISSUE THREAD

**Issue by rpigneri-ml** [newrelic/docs-website#8529]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* This link at the top of the page is dead: https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-moitors/write-synthetic-api-tests-legacy.mdx.  It points to the legacy Node 10 code.
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/write-synthetic-api-tests/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@rpigneri-ml thanks for pointing this out! I'm closing this because we're going to fix this in #8556.
