### ISSUE TITLE
missing details about enrichment

### ISSUE THREAD

**Issue by npreiser** [newrelic/docs-website#8534]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?   
* 
* you can ONLY enrich(get data from) the account in which IINT environment resides in.     

A workflow sits in an IINT environment,  which sits in an account.   
*

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows/
* **OS**: Windows 10
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@npreiser could you give us some details about what you think is missing about enrichment on this page: https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows/#enrichments

**Comment by rhetoric101** [comment]
@npreiser since I haven't heard back from you about your concerns, I'm going to close this issue.  You can always reopen it if you want to clarify your concerns.
