### ISSUE TITLE
Issue: Install .NET agent for Linux - Package Name Change

### ISSUE THREAD

**Issue by Nateb1121** [newrelic/docs-website#8542]
## How can we make our docs better?

* Is something inaccurate or missing?
As of July 19th the .NET agent's package name was changed which invalidates this documentation. 

For more information on the name change please see https://docs.newrelic.com/docs/apm/agents/net-agent/getting-started/9x-to-10x-agent-migration-guide/#upgrading-from-newrelic-netcore20-agent-to-newrelic-dotnet-agent 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/net-agent/installation/install-net-agent-linux/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
This is resolved by #8545

**Comment by nr-ahemsath** [comment]
@Nateb1121 We have a docs change PR in progress that will address this: https://github.com/newrelic/docs-website/pull/8484
