### ISSUE TITLE
Issue: Manage errors in APM: Collect, ignore, or mark as expected - add Errors Inbox

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#8546]
## How can we make our docs better?

We need to mention Errors inbox and link to it here.  acuffe and mtrelles will want to have input on this.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/agent-data/manage-errors-apm-collect-ignore-or-mark-expected/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
