### ISSUE TITLE
Issue: Get started with network monitoring

### ISSUE THREAD

**Issue by Ikaberry202** [newrelic/docs-website#8557]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/network-performance-monitoring/get-started/npm-introduction/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by homelessbirds** [comment]
Hi there! Can you give me a little more insight into what you're looking to improve in this doc? 

Looking forward to helping!
