### ISSUE TITLE
Issue: Introduction to the style guide

### ISSUE THREAD

**Issue by 0937116077** [newrelic/docs-website#8559]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/style-guide/writing-strategies/introduction-style-guide/
* **OS**: Android 12
* **Browser**: Chrome 103.0.0.0
* **Device**: [mobile] M2101K7AG

**Comment by homelessbirds** [comment]
Hi there! Thanks for reaching out. What sort of additions would like made to this? Can you tell me more about your request? 

Looking forward to helping you!
