### ISSUE TITLE
Add sessionTraceId to events tables

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#8565]
## How can we make our docs better?

* The browser session traces UI now displays a new attribute sessionTraceId in the table. This value will show up across multiple browser event types so we should add this to data dictionary where applicable. 
* the sessionTraceId attribute was added to better connect session traces (real, end-user page loads) with queryable browser event data. I[n browser agent version release 1214](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1214), the agent started collecting a ptid param added to the query string of all harvests after the initial session trace harvest, if a session trace was active on the page (to note, not all page loads collect a session trace as this data is sampled. The agent makes a decision before page load to collect a session trace or not.).

This means all browser events, except PageView which is guaranteed to harvest before the first session trace harvest, should include the session trace ID if the ptid query string param is present. In most cases Initial Page Load BrowserInteraction events complete before a session trace begins and are not guaranteed to contain this ID either. The full event list should be:

BrowserInteraction
AjaxRequest
BrowserTiming
PageViewTiming
JavaScriptError
PageAction

Please see reference to new UI launches here: 
https://nerdlife.datanerd.us/new-relic/ls/community/gts-community/post/5248325313232896

Here is where you can find it: 
<img width="665" alt="Screen Shot 2022-07-22 at 9 33 14 AM" src="https://user-images.githubusercontent.com/32469854/180484077-74546d0b-98ca-4389-9311-fa1e69daadfd.png">

Here are tickets if you need more information: 

https://newrelic.atlassian.net/browse/DEMPLA-2272
https://newrelic.atlassian.net/browse/DEMPLA-2284
https://newrelic.atlassian.net/browse/DEMPLA-2356

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 102.0.5005.61
* **Device**: Unknown

**Comment by zuluecho9** [comment]
https://github.com/newrelic/docs-website/pull/8573
