### ISSUE TITLE
Issue: Node.js: Configure logs in context

### ISSUE THREAD

**Issue by meyerkev** [newrelic/docs-website#8576]
## How can we make our docs better?

https://discuss.newrelic.com/t/log-forwarding-in-context-from-a-nodejs-docker-container-is-not-working/187145/8

> So calling console.log() inside our app counts as “Outside our app” and we have to rewrite every piece of logging we do?
>
> Can I formally request that we make that documentation way way more clear because that documentation is not clear at all then.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/configure-logs-context-nodejs
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
@barbnewrelic pinging you on this as you might know the correct way to triage this issue!

**Comment by barbnewrelic** [comment]
@meyerkev  Thanks for providing this detailed background! We'll have the Node.js engineers take a look at this and update the docs accordingly.
