### ISSUE TITLE
Issue: Use TCP endpoint to forward logs to New Relic

### ISSUE THREAD

**Issue by andrew-lozoya** [newrelic/docs-website#8578]
Step 4 needs to say something to the effect of: Check whether the directives under /etc/rsyslog.conf will include the newly created newrelic.conf if not explicitly include the config:

$IncludeConfig /etc/rsyslog.d/newrelic.conf

Ref: https://www.rsyslog.com/doc/v8-stable/configuration/global/options/rsconf1_includeconfig.html

```
Explicitly include the newly created newrelic.conf to the /etc/rsyslog.d/ file:
include(file="/etc/rsyslog.conf.d/newrelic.conf")
```

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/log-api/use-tcp-endpoint-forward-logs-new-relic/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hi @andrew-lozoya, thanks for letting us know! I'm going to have the agent teams confirm and then get this PR'd in!

**Comment by andrew-lozoya** [comment]
@bradleycamacho it should also be noted in the docs as they are today. There is no path for `/etc/rsyslog.conf.d/newrelic.conf `

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
