### ISSUE TITLE
Issue: Introduction to notifications

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#8594]
## How can we make our docs better?

I had a customer asking how the credentials used in the destinations (and notification channels) are stored. They asked if they were encrypted and/or stored securely.

I got confirmation [here in this Slack thread](https://newrelic.slack.com/archives/C01AE77N010/p1658743353090159?thread_ts=1658741740.988059&cid=C01AE77N010) that they are stored securely and according to the New Relic guidelines.

Also, there are no published specific docs so I believe that including this on this page (with more details if possible) would be a great addition to the docs.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/notifications/intro-notifications
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Fixed with https://github.com/newrelic/docs-website/pull/8776

**Comment by rodrigo-corgozinho** [comment]
Thank you @zuluecho9!!!
