### ISSUE TITLE
Issue: Workflows

### ISSUE THREAD

**Issue by CraftingGamerTom** [newrelic/docs-website#8604]
## How can we make our docs better?

* Tutorial Video glitches, skips, and repeats (Condition Tags Video)
* Video is also very quiet (Condition Tags Video)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows/
* **OS**: Monterey 12.4
* **Browser**: Google Chrome | 103.0.5060.53 (Official Build) (arm64)
* **Device**: Apple M1 MacBook Pro (13-inch, M1, 2020)

**Comment by zuluecho9** [comment]
I've passed this to the video dept. thanks @CraftingGamerTom ! and sorry about that
