### ISSUE TITLE
Add the infrastructure agent docs to the Agents section

### ISSUE THREAD

**Issue by danifitz** [newrelic/docs-website#862]
### Is your feature request related to a problem? Please describe

When I click on the agents section in the docs site, I see APM agents, however I'd also expect to see Infrastructure agent (since it's an agent after all). If the section is supposed to be for APM agents only, it should be named as such or we should add the infrastructure agent docs to this section.

### Describe the solution you'd like

Include the infrastructure agent docs in the `Agents` section. This is the section I'm referring to: https://docs-preview.newrelic.com/docs/agents

### Describe why this important to you

All of our agent docs should be in the same place.

**Comment by austin-schaefer** [comment]
Hey @danifitz , just wanted to let you know we're creating an issue in our Jira backlog for this. I think the initial fix will be renaming this category to "APM agents" since it's really about APM, not about all the agents (Browser, Mobile are also not in here). 

That issue is DOC-6692 in Jira.
