### ISSUE TITLE
Issue: How do you remove a Jira Workspace and Template?

### ISSUE THREAD

**Issue by dralph3344** [newrelic/docs-website#8640]
## How can we make our docs better?

How do you REMOVE a Jira workspace and Template? 

In cases where we create a workspace/template, but then need to remove it, what are the steps to do so? Also, there doesn't appear to be a space in the UI to remove it as far as I can see. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/errors-inbox/error-external-services/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@bradleycamacho  I know you were deeply involved in errors inbox docs, so I hope you can determine whether this is an easy fix to docs or requires additional research by engineers. Thanks!

**Comment by rhetoric101** [comment]
@dralph3344 this is addressed in PR #8683.
