### ISSUE TITLE
Issue: Docker and other container environments: Install PHP agent

### ISSUE THREAD

**Issue by kderck** [newrelic/docs-website#8646]
## How can we make our docs better?

Clicking on **PHP Agent** returns Not Found.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/php-agent/advanced-installation/docker-other-container-environments-install-php-agent/
* **OS**: Mac OS 10.15.7
* **Browser**: Safari 15.6
* **Device**: Unknown

<img width="1512" alt="Screenshot 2022-07-28 at 15 28 32" src="https://user-images.githubusercontent.com/98526301/181548440-bdf7ecca-4045-47d6-b646-5319acf85eb1.png">

<img width="1512" alt="Screenshot 2022-07-28 at 15 28 35" src="https://user-images.githubusercontent.com/98526301/181548569-6c97a2fe-5539-45f5-9c53-92d6c162c929.png">

**Comment by akristen** [comment]
@kderck  Thanks for filing this issue! I'll be fixing that today, either by removing the redundant link or updating it with a functioning one. Good catch. :)

**Comment by akristen** [comment]
Hi again @kderck. you can see the resolution of this issue here: https://github.com/newrelic/docs-website/pull/8671 It'll be reflected by EOD PST. :) Thanks again!
