### ISSUE TITLE
Issue: Drop data using NerdGraph

### ISSUE THREAD

**Issue by DarrenDoyle** [newrelic/docs-website#8677]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/manage-data/drop-data-using-nerdgraph/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

Please be more specific on APM Metric Timeslice data, there needs to be more content on this topic

**Comment by rhetoric101** [comment]
@DarrenDoyle, did you see the link in that topic to the [normalization topic](https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/ui-data/metric-normalization-rules/) for timeslice data? Does this address your concerns?

**Comment by rhetoric101** [comment]
@DarrenDoyle I am going to close this since I've not heard back from you. If you find you need more than that normalization topic for timeslice metrics, then go ahead and reopen this issue.
