### ISSUE TITLE
Issue: Create and edit SLIs and SLOs

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#8684]
## How can we make our docs better?

A Workload can span accounts but Service Levels created via with Workload as the entity will not.   

So for example, let's say I have a workload with entities in account A and account B. 
In the UI, If I got to account A, create a service level in A, and use the workload as the entity, the service level will apply only to the workload's entities in account A.

A workaround for this could be to create service levels for each entity separately in UI and then let them automatically roll up in the workload. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/service-level-management/create-slm/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
Doing work on this in https://github.com/newrelic/docs-website/pull/10256.
