### ISSUE TITLE
why the transactionName change?

### ISSUE THREAD

**Issue by leonardoLiang** [newrelic/docs-website#8701]
## Description

we have release a new production ,but suddenly we found the monitor data lose,finally we found out the transaction name is change,
we change the query transaction name ,it can collect data normally,but we dont know why the transaction name change and we guess may be it realate to the framework,but i can find the supported framework in docs,so i want to fingure out why it will change ? may be we use the framwork it can not supported? we used to monitor data by request url ,but now it change to spring controller,we dont set any config,so i hope you can reply me soon,thx
## Screenshots
before release
![image](https://user-images.githubusercontent.com/7898244/182100112-3f7d82f9-daa9-4176-a2fb-9f15ee82f890.png)

after release
![image](https://user-images.githubusercontent.com/7898244/182100202-81e2028d-0582-4f7a-ba90-879be58d7cf9.png)

## Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by zuluecho9** [comment]
@leonardoLiang This sounds like more of a question for support or, if you don't have a support plan, for the public forum (discuss.newrelic.com). 

One tip we'd have is to check the compatibility doc and make sure that all looks correct first: https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent/#other-apm

**Comment by leonardoLiang** [comment]
we update the log4j from 2.14.1 to 2.17.2，and load a new jar but not in supported framework,so i want to know how java agent to detect the framework and set the name,we use default config,so if i want to change to before , but i dont want to use attribute or api call,is that possible? and i think if the framework not support in new relic agent,it should not be detect automatically instead of change the transaction name?
