### ISSUE TITLE
ServerlessSample missing from Data dictionary

### ISSUE THREAD

**Issue by khickey-newrelic** [newrelic/docs-website#8702]
Update on this from @zuluecho9 Sept 26: we recently added K8s data to data dict. Currently looking into if we have plans for adding new entries to data dict and what that process/strategy looks like. 

## How can we make our docs better?

Hey docs team! We need an entry for ServerlessSample. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
gonna close this one as we created a jira for this work NR-53211
