### ISSUE TITLE
Post GA Contributor enablement checklist

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#872]
This issue will capture any improvements we'll want to make to the contributor workflow after GA as we'll be learning what is working / not work post GA.

- Do we need a technical troubleshooting guide? (lots of little things to get tripped up when contributing do we need to mitigate those?)  > add  to troubleshooting section to [CONTRIBUTING.md](https://github.com/newrelic/docs-website/blob/develop/CONTRIBUTING.md)

- Define the branching strategy and perhaps content contributions once approved automatically Deploy via a GH action:: Merge to Develop > PR to Main

- Solve how to work on large batches of content for product releases that can’t be publicly worked on?

- Put in PR checks to enforce Markdown linting
 
- If there are needs to do content experiments after GA:, can we empower & train the Docs Team to be able to conduct those with Split.io?

### General install, compile or build problems.

1. Ensure you are using `Yarn` not `NPM`
2. When in doubt completely delete the `node_module` folder in the root project directory, and re-run `yarn install `
4. away run `git pull` whenever you intend to create a new working branch
5. aways run `Yarn install` whenever you git pull.

### Lew's issue on Apple M1 chipset build / compile

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  TOUCH Release/obj.target/libvips-cpp.stamp
  CXX(target) Release/obj.target/sharp/src/common.o
../src/common.cc:23:10: fatal error: 'vips/vips8' file not found
#include <vips/vips8>
         ^~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/sharp/src/common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/cirne/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/Users/cirne/.nvm/versions/node/v15.4.0/bin/node" "/Users/cirne/.nvm/versions/node/v15.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cirne/dev/docs-website/node_modules/sharp

```

**Solution**
https://github.com/lovell/sharp/issues/2460#issuecomment-768558230

### Problems with yarn start

```
 ERROR
[BABEL] Note: The code generator has deoptimised the styling of /Users/jmiller/code/docs-website/src/content/docs/licenses/license-information/other-licenses/services-licenses.mdx as it exceeds the max of 500KB.
```
**Solution**

ignore it, not a big issue  😉

**Comment by jpvajda** [comment]
@austin-schaefer ideas welcome.

**Comment by bradleycamacho** [comment]
We are constantly running into issues relating to `SSR` when building the site locally.

### Steps to reproduce

1. `yarn`
2. ' yarn start`
3. Sometimes the build will succeed, but sometimes we get thrown an error like the one below:

`warn The path "/" errored during SSR.
 Edit its component
node_modules/@newrelic/gatsby-theme-newrelic/src/components/AnnouncementBanner.js:45:11 to resolve the
error.`

**Comment by jpvajda** [comment]
@jerelmiller any thoughts on that issue @bradleycamacho reported?

**Comment by bradleycamacho** [comment]
I will mention that we can usually fix this by running the commands below, but it's really ineffcient to have to build the site, notice the build error, run the commands, and then rebuild. The entire process can take ~10-20 minutes at times.

`
rm -rf node_modules
yarn
yarn clean
yarn start
`

**Comment by jpvajda** [comment]
@bradleycamacho totally, that's the windows equivalent of `restarting the machine` 😄
