### ISSUE TITLE
Issue: Guided install overview

### ISSUE THREAD

**Issue by zagarskas** [newrelic/docs-website#8739]
there is nothing here that explains how to UPLOAD logs.

Consider how I got here:
"upload Apache logs" - your landing page

I sign up and create an account.
ALL of the modules tell me to run commands = thats not happening
We just got attacked, we salvaged our logs, now we need to investigate

So... I should be able to log in here, click on "add data" and upload my logs.
Select NGIX or Apache from a drop menu
and take a look...

I am left with the impression:
"Oh. Ok. No one at Newrelic ever considered that folks **may need to upload logs from an attacked server that can not be connected to** - so there is no upload option"
Is that statement true?
I feel like... it has to return false as a claim...
surely... surely... there is a way for me to upload logs here without connecting to a server and I am just looking in the wrong place via the GUI?

**Comment by bradleycamacho** [comment]
Hi @zagarskas. Apologies for the painful experience, and I'm sorry our product hasn't been able to help you with what I imagine is a stressful task!

As this isn't a specific issue with out documentation, I recommend reaching out to our [support team ](https://support.newrelic.com/s/support) or asking our [community forum](https://discuss.newrelic.com/ ) as they will be able to get you the help you will need.

With that said, I'm reaching out internally to see if this is a hole in our docs. Hope this helps!

**Comment by bradleycamacho** [comment]
Hey @zagarskas, I still recommend you reach out to support but this is what I heard back from the logging team!

> Hi Bradly! The customer could use a log forwarder like Fluent Bit or Fluentd https://docs.newrelic.com/docs/logs/forwardlogs/enable-log-management-new-relic/#forward-other, and have that forwarder forward logs from any log files they ahve

and

> If they can't use any kind of agent, they could potentially write a script to read each line and then post to logs API using curl (assuming this is a linux box).  The other caveat here is we won't accept any logs with timestamp of older than 2 days so they'd have to add a current timestamp.
