### ISSUE TITLE
Final Docs Site migration + JP Content: after Site freeze : 2/25 12pm PST

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#874]
The Old Docs Site Freeze starts: Thurs 2/25 12pm and the Team  will need to run the migration script on the same day to bring all remaining content over to the new site.

The existing Japanese language site will be frozen on 2/23 so we'll want to do one final content update from the proxy site to pull in all the JP content and ensure the new site gets the most current JP content.
XML

https://docs.newrelic.com/translation-index/content/japanese/completed <= those are the straight articles
https://docs.newrelic.com/translation-index/taxonomy/japanese/completed <= landing pages and taxonomy

**Comment by jerelmiller** [comment]
This is done and merged!
