### ISSUE TITLE
Issue: Login and password issues

### ISSUE THREAD

**Issue by northyg** [newrelic/docs-website#8758]
## How can we make our docs better?

A) The link on this page doesn't go anywhere useful [support.newrelic.com](https://support.newrelic.com/home). 
It goes to a page not found page. 

B) Customers need to know where to go if they are locked out of their account for reasons outside their control. Like a billing issue. Where can they go in emergencies?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/account-setup/troubleshoot-new-relics-password-email-address-login-problems/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thank you @northyg !

**Comment by zuluecho9** [comment]
fixed with https://github.com/newrelic/docs-website/pull/8764
