### ISSUE TITLE
Kubernetes Missing From Data Dictionary

### ISSUE THREAD

**Issue by jake-codes** [newrelic/docs-website#8774]
Kubernetes should really be included in the data dictionary. It's more than an integration.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/attribute-dictionary/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thank you @jake-codes. we were actually just talking about this, and we'll try to make this happen soon.

**Comment by austin-schaefer** [comment]
@jake-codes You can follow along for this request in our internal Jira in this issue: https://issues.newrelic.com/browse/NR-39440
