### ISSUE TITLE
Issue: New Relic data types: metrics, events, logs, and traces (MELT)

### ISSUE THREAD

**Issue by coreyarnold** [newrelic/docs-website#8777]
## How can we make our docs better?

the link "See [Get data into New Relic](https://developer.newrelic.com/use-cases/collect-data-from-any-source)." gives a 404 :sadpanda:

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/understand-data/new-relic-data-types/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks @coreyarnold. Fixing this with https://github.com/newrelic/docs-website/pull/8779
