### ISSUE TITLE
Callout text looks odd being the same size as body text

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#878]
## Description

In Drupal, callout text is smaller than body text. In preview it's not. Looks kind of weird, and the leading seems a bit excessive too.

## Steps to Reproduce

This happens across the preview site, but here's an example.
Compare Tip callout text in https://docs.newrelic.com/docs/apis/rest-api-v2/basic-functions/calculate-average-metric-values-summarize 
with
Tip callout text in https://docs-preview.newrelic.com/docs/apis/rest-api-v2/basic-functions/calculate-average-metric-values-summarize

## Expected Behavior

[NOTE]: # (Tell us what you expected to happen.)

## Relevant Logs / Console output

n/a

## Additional context

[NOTE]: # (PLEASE DO NOT DELETE THIS SECTION. This contains useful information for the team.)

### Page
https://docs.newrelic.com/docs/apis/rest-api-v2/basic-functions/calculate-average-metric-values-summarize

### Environment
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jerelmiller** [comment]
@barbnewrelic just to clarify, when you say "callout text", are you referring to the title of the callout?

<img width="905" alt="Screen Shot 2021-02-16 at 3 03 12 PM" src="https://user-images.githubusercontent.com/565661/108132711-31d6c300-7068-11eb-8143-4edba25613ee.png">

**Comment by barbnewrelic** [comment]
Sorry I wasn't more clear! No, I mean the text itself in tips, importants, and cautions. It doesn't differentiate between normal body text on the page (other than box color). Is that intentional? I was expecting the text within the callout box to be smaller, like it is on Drupal site. If this is a new style decision, I can probably learn to live with it. I can't figure out how to attach a screenshot or I'd show you what I mean.

**Comment by jerelmiller** [comment]
Attaching screenshot for reference:

<img width="1115" alt="callout-text-too-large" src="https://user-images.githubusercontent.com/565661/108137807-7c107200-7071-11eb-8744-74721cd4c5e6.png">

**Comment by jerelmiller** [comment]
> Is that intentional?

This was intentional, but I can definitely see your point. We can re-evaluate and see if we feel it needs a bit smaller text.

**Comment by jerelmiller** [comment]
I tagged this issue with "design needed" so we can get some eyes from DX on it.

**Comment by jerelmiller** [comment]
@barbnewrelic and by the way, you can attach screenshots by either dragging and dropping the image right in the text box, or you can click the "Attach files by dragging & dropping, selecting, or pasting them" bar right below the textbox to select them. Hopefully that helps!

**Comment by barbnewrelic** [comment]
d'oh! thanks for the tips!

**Comment by austin-schaefer** [comment]
Not a launch-blocker, but I'd love to get this cosmetic issue addressed by launch if possible.

**Comment by jpvajda** [comment]
@djsauble any opinions?

**Comment by djsauble** [comment]
What problem are we trying to solve with the smaller font size? Body text should be at a size which is a good balance between density and readability, and since callouts can contain sizable blocks of text, I'd be hesitant to make that text smaller than necessary.

**Comment by barbnewrelic** [comment]
OK never mind. The fact that the callout body text is the same size and leading as "normal" body text caught me by surprise. PS: IMHO a callout should be short and sweet so the color pulls your focus and the message is succinct. If a callout has a lengthy block of text, I don't think it's a callout. :-)

**Comment by austin-schaefer** [comment]
@djsauble It's a good question. For me the problem to solve is that callouts are intended as a side-note from the main text of the doc, and that generally when I see them in books or other websites I think they're slightly smaller to indicate that. But I'm honestly pretty fine won't-fix'ing this one.

**Comment by djsauble** [comment]
I played around a bit with the spacing and margin of the callout container itself. Any better?

Current:

![Screen Shot 2021-03-01 at 3 59 42 PM](https://user-images.githubusercontent.com/186715/109575731-3f983980-7aa7-11eb-90ee-a3989a64b1ec.png)

New:

![Screen Shot 2021-03-01 at 3 59 04 PM](https://user-images.githubusercontent.com/186715/109575741-43c45700-7aa7-11eb-9c4a-ef3d6bc07d5a.png)

**Comment by barbnewrelic** [comment]
I'd say just leave as is. All that extra blank space on right side of box
looks like a mistake. But thanks for playing with it!

**Comment by jpvajda** [comment]
closing as `won't fix` It seems the approach is ok for now.
