### ISSUE TITLE
Issue: Errors page: Constant displays this message "Oops! Something went wrong."

### ISSUE THREAD

**Issue by claudiomartinsinovacao** [newrelic/docs-website#8787]
Constant displays this message "Oops! Something went wrong."

At click [home]-[SLA]-[End User]

![SLA](https://user-images.githubusercontent.com/60120331/182838606-ec2426a9-4ae4-490d-8f02-d9b1310ad3a6.png)

**Comment by barbnewrelic** [comment]
@claudiomartinsinovacao  Our team does not maintain the UI. You may want to file a support ticket about this.
