### ISSUE TITLE
Issue: Java agent and Heroku

### ISSUE THREAD

**Issue by rogovskiy** [newrelic/docs-website#8788]
## How can we make our docs better?
 I think this page needs to be revised. 

* Is something confusing?
Confusing - the page is about Deploying Java agent on Heroku. But is has a section "Deploy locally" it is unclear in which case you would want to deploy locally while deploying a Heroku integration. 

"Manual configuration " section is confusing. You download agent/unzip and what? If you leave it as is Heroku isn't going to pick it up. Do you need to add to git? Not sure.

* Is something inaccurate or missing?
It would be good to understand on high level what the integration is trying to accomplish like in 2-3 bullet points before we get in in the details. 

Gradle setup would be nice.  

* Were you unable to complete a task? (What task?)
It was difficult (I am a NR employee) and I've almost given up doing it. I had to craft my own with Gradle setup.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/java-agent/heroku/java-agent-heroku/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by barbnewrelic** [comment]
@rogovskiy  Thanks for your thoughtful comments! I looked at the history of this doc, and it has not been updated for several years. I'll add your issue to our docs backlog so it can get prioritized.

**Comment by barbnewrelic** [comment]
NR-39575

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
