### ISSUE TITLE
Live tail logging 2 icons are MIA

### ISSUE THREAD

**Issue by barbnewrelic** [newrelic/docs-website#880]
## Description

I added the start and stop live tail logging icons via Font Awesome in Drupal logging doc, but they don't appear in preview.

## Steps to Reproduce

Compare https://docs.newrelic.com/docs/logs/log-management/troubleshooting/view-log-messages-real-time-live-tail#solution step 3
with
https://docs-preview.newrelic.com/docs/logs/log-management/troubleshooting/view-log-messages-real-time-live-tail#solution step 3

## Expected Behavior

The icons should appear, not just the description.

## Relevant Logs / Console output

n/a

## Additional context

[NOTE]: # (PLEASE DO NOT DELETE THIS SECTION. This contains useful information for the team.)

### Page
https://docs.newrelic.com/docs/logs/log-management/troubleshooting/view-log-messages-real-time-live-tail

### Environment
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by jerelmiller** [comment]
Hey @barbnewrelic is this still an issue? I am seeing icons show up on that page now.

When we did the final migration, we noticed a couple icons missing. If I remember correctly, these were included in that list. Seeing as this was opened before the final migration, I'm inclined to think this was fixed for the final migration. Can you confirm you see what you expect? If so, feel free to close this issue!

**Comment by jpvajda** [comment]
Closing as these seems to be resolved.
