### ISSUE TITLE
Issue: Configure the New Relic Gradle plugin

### ISSUE THREAD

**Issue by alexforrester** [newrelic/docs-website#8819]
## How can we make our docs better?

* Is something confusing?

Yes - I'm trying to get some clarity on enabling deobfuscation of crash logs and uploading mapping files in android. In my app/build.gradle I have this top level newrelic plugin extension:

```
newrelic {
    variantMapsEnabled true
    uploadMapsForVariant("Release")
    excludeVariantInstrumentation("Debug")
}
```

Does the 'Release' in the uploadMapsForVariant signify that all release buildtypes will be built or does a specific release application variant need to be defined? i.e

If I have `flavorDimensions` which result in a gradle task named `nowTVBuildFlavorEnvironmentRelease` do I have to add

uploadMapsForVariant("nowTVBuildFlavorEnvironmentRelease")

...this is from docs referenced here:

[Configure the New Relic Gradle plugin | New Relic Documentation](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-new-relic-gradle-plugin/)

* Is something inaccurate or missing?

Just requires clarifying

* Were you unable to complete a task? (What task?)

Yes - The specific task I'm working on is trying to deobfuscate crash logs for multiple release build variants. This is not supported by New Relic so I'm creating the newrelic.properties file in the app folder for individual new relic apps in the dashboard so the new gradle plugin can then upload the mapping file.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/configure-new-relic-gradle-plugin/
* **OS**: Android 12
* **Browser**: Unknown
* **Device**: Pixel 6

**Comment by akristen** [comment]
Thanks for bringing this to our attention @alexforrester. We're going to send your question to the product team best suited to help you through this!

**Comment by alexforrester** [comment]
Hi @akristen - Can you advise me on a response time and how this issue is tracked/monitored? Also, how will I receive correspondence on this issue when it is now closed?
