### ISSUE TITLE
Issue: Introduction to New Relic for Ruby

### ISSUE THREAD

**Issue by ohinton** [newrelic/docs-website#8824]
## How can we make our docs better?

The hyperlink associated with "distributed tracing" goes to a "Hmm... We can't find this" page, and should be updated to:

https://docs.newrelic.com/docs/distributed-tracing/concepts/introduction-distributed-tracing/

(Enable **distributed tracing** to understand activity in an environment that relies on many services.)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/ruby-agent/getting-started/introduction-new-relic-ruby/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @ohinton I've gone ahead and made these changes, which you can see here: https://github.com/newrelic/docs-website/pull/8844
