### ISSUE TITLE
Issue: Connect errors inbox to third-party services

### ISSUE THREAD

**Issue by ohinton** [newrelic/docs-website#8825]
## How can we make our docs better?

Typo: team-mananged -> team-managed

New Relic supports both **team-mananged** and company-managed Atlassian-Jira projects.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/errors-inbox/error-external-services/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Hi! Good catch. You can see the addressed issue here: https://github.com/newrelic/docs-website/pull/8844
