### ISSUE TITLE
Issue: High security mode

### ISSUE THREAD

**Issue by ohinton** [newrelic/docs-website#8826]
## How can we make our docs better?

The hyperlink associated with the sentence that starts: "For users on [our original user model]..."

Goes to a "Hmm... We can't find this" page.

The hyperlink should be updated to: 
https://docs.newrelic.com/docs/accounts/original-accounts-billing/original-users-roles/users-roles-original-user-model

Also, the hyperlink associated with the sentence that starts: "For users on [our newer user model]:..."

The hyperlink should be updated to:
https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/introduction-managing-users

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/configuration/high-security-mode/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by akristen** [comment]
Thanks for bringing this to our attention! I've addressed this fix in this PR: https://github.com/newrelic/docs-website/pull/8844
