### ISSUE TITLE
Issue: Install the infrastructure monitoring agent for Linux

### ISSUE THREAD

**Issue by Janusz478** [newrelic/docs-website#8829]
## How can we make our docs better?

Point 4 "Add the infrastructure monitoring agent repository:" for "Ubuntu 22.04 (Jammy Jellyfish)" doesn't work with the given link "https://download.newrelic.com/infrastructure_agent/linux/apt", but with the same link and a slash at the end "https://download.newrelic.com/infrastructure_agent/linux/apt/". WIth a browser the link without a slash contains empty directories, while the one with the slash contains non-empty directories.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/install-infrastructure-monitoring-agent-linux/
* **OS**: Windows 10
* **Browser**: Firefox 103.0
* **Device**: Unknown

**Comment by akristen** [comment]
Thanks for the catch! You can track the change to this doc in this PR: https://github.com/newrelic/docs-website/pull/8844

I've also reached out to the Infrastructure team to see if any other links need a similar update.
