### ISSUE TITLE
Issue with multiple app variants with Android agent crash reporting

### ISSUE THREAD

**Issue by alexforrester** [newrelic/docs-website#8831]
## How can we make our docs better?

The docs on the mapping.txt upload are quite confusing. Its states that: `The application's build ID changes each time an APK is generated, and the build ID in the mapping file must match the ID contained in each uploaded crash report.`

Could you confirm the application's build ID is the BUILD_ID in the NewRelicConfig? Is this also the same BUILD_ID you are referring to when you state `'the build ID in the mapping file'`. If it is this is very confusing as it makes it seem as if this is the proguard _mapping.txt_ file - The mapping.txt file only has the _pg_map_id_ which doesn't change unless the proguard-rules.pro is updated. We are having issues deobfuscating crashes as we have an app with multiple variants. We have tried some of the solutions online to dynamically create a newrelic.properties file for each release variant, but so far this isn't working. (Possibly because we are using bundles instead of .apks). So as a workaround we'd hoped to deobfuscate the logs by using the curl script to upload the mapping.txt file. When we do this for the application with the curl command below we get the uploaded fine message etc. but the crash logs are still not being obfuscated.

`curl -v -F upload=@"<some_path_to_mapping.txt>" -H "X-APP-LICENSE-KEY:<some_token>" https://mobile-symbol-upload.eu.newrelic.com/symbol `

As you would expect there are many different versions of a New Relic Mobile Application identified by its X-APP-LICENSE-KEY
Uploading a mapping.txt file which hasn't changed for all these different versions still does not deobfuscate crash logs. Is there the expectation that it should do even if the NewRelicConfig.BUILD_ID of an individual app version which is replicated in the crash logs is not available?

How do you differentiate between different versions of a New Relic Mobile Application when the mapping.txt file updates if there was an issue with the newrelic.properties file which caused the mapping file not to be uploaded? This is what we are currently experiencing.

We are endeavouring to write out the correct version of the newrelic.properties file for our different app variants which will do this automatically, but in case this fails we need to have a way to ensure crash logs get obfuscated by keeping an archive version of mapping.txt on our CI and uploading it manually. At the moment this isn't working. Any help would be very gratefully appreciated - thank you.

On this SO post there are 2 solutions for attempting to resolve the multiple app variants issue which we have tried:
https://stackoverflow.com/questions/30170163/new-relic-in-android-studio-newrelic-properties-variants

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/android-agent-crash-reporting/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @alexforrester. I've gone ahead and added this ticket to be triaged to someone on the Mobile team. They'll be able to help you out with this issue + update any documentation that needs clarification. Thanks for the contribution!

**Comment by alexforrester** [comment]
Hi @akristen - Can you advise me on a response time and how this issue is tracked/monitored? Also, how will I receive correspondence on this issue when it is now closed?
