### ISSUE TITLE
Issue: Data encryption

### ISSUE THREAD

**Issue by Fobdawg** [newrelic/docs-website#8835]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/security/security-privacy/compliance/data-encryption/
* **OS**: Windows 10
* **Browser**: Edge 103.0.1264.37
* **Device**: Unknown

**Comment by akristen** [comment]
Hello @Fobdawg. Looks like the issue you wanted to report didn't get saved in the body of the text. Was there something specific to https://docs.newrelic.com/docs/security/security-privacy/compliance/data-encryption/ you needed looked at?
