### ISSUE TITLE
Issue: Forward your logs using the infrastructure agent

### ISSUE THREAD

**Issue by vc102961** [newrelic/docs-website#8836]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/forward-logs/forward-your-logs-using-infrastructure-agent
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 104.0.5112.79
* **Device**: Unknown

**Comment by vc102961** [comment]
The Link a[[SERVICE] section](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/configuration-file#config_section), doesn't work

**Comment by akristen** [comment]
@vc102961 Thanks for catching this. I've updated the link to the new page on Fluent Bit's docs. You can track that change in this PR: https://github.com/newrelic/docs-website/pull/8844
