### ISSUE TITLE
Issue: Need a MacOS update to Requirements for the infrastructure agent

### ISSUE THREAD

**Issue by Mesverrum** [newrelic/docs-website#8846]
## How can we make our docs better?

* I believe that ARM processors are now supportable for MacOS as I have had it running on my M2 laptop for several months and everything seems to be fine.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent
* **OS**: Mac OS 10.15.7
* **Browser**: Edge 102.0.1245.39
* **Device**: Unknown

**Comment by akristen** [comment]
I've reached out to our Infra team to see if we've made an official announcement and/or if we can go ahead and update the doc with new requirements.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
