### ISSUE TITLE
Issue: Java agent configuration: Config file

### ISSUE THREAD

**Issue by Breefield** [newrelic/docs-website#8864]
## How can we make our docs better?
Something is missing:
[Grpc Configuration](https://github.com/newrelic/newrelic-java-agent/blob/72bdebce3d80ec22a674e3e33be5444c12fb2d58/instrumentation/grpc-1.40.0/src/main/java/com/nr/agent/instrumentation/grpc/GrpcConfig.java) is not documentated for Java agent: https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@Breefield thanks for your comment about gRPC. I'll check with our subject matter experts and see why our docs have this gap.

**Comment by rhetoric101** [comment]
@Breefield I spoke with our subject matter experts about gRPC in the Java agent, and it turns out that there isn't an agent spec for this yet. Have you raised this as a feature request at [https://discuss.newrelic.com](https://discuss.newrelic.com)?
