### ISSUE TITLE
Our writing should be more poetic [TEST ISSUE]

### ISSUE THREAD

**Issue by bradleycamacho** [newrelic/docs-website#887]
### Is your enhancement request related to a problem? Please describe

Our writing is friendly and inviting, but it isn POETIC. I suggest we take some time to add some poetry to our docs. Specifically, I believe that our Python docs could use some flare.

### Actions items:

1. Create a new doc in the Python category named "Poetry Break".
2. Create a section with one poem .
3. Edit another doc in the Python Category and add a quote from a book.
3. Open a PR and merge after review.

### Poem:

but they had not rested five minutes when a glare of white letters started from the dark, as vivid as spectres—the air swarmed with Catherines; and rousing myself to dispel the obtrusive name, I discovered my candle wick reclining on one of the antique volumes, and perfuming the place with an odour of roasted calf-skin.

The ledge, where I placed my candle, had a few mildewed books piled up in one corner; and it was covered with writing scratched on the paint. This writing, however, was nothing but a name repeated in all kinds of characters, large and small—Catherine Earnshaw, here and there varied to Catherine Heathcliff, and then again to Catherine Linton. In vapid listlessness I leant my head against the window, and continued spelling over Catherine Earnshaw—Heathcliff—Linton, till my eyes closed; 

### Quote
“As Gregor Samsa awoke one morning from uneasy dreams he found himself transformed in his bed into a gigantic insect.”

### Front Matter Example

```
---
title: 'Poetry Break'
contentType: page
template: basicDoc
---
```

**Comment by jpvajda** [comment]
looks a test, closing
