### ISSUE TITLE
Issue: Install infrastructure on-host integrations

### ISSUE THREAD

**Issue by ltoshev** [newrelic/docs-website#8900]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra' -> this command does not work

returns:

Error getting repository data for newrelic-infra, repository not found

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/install-infrastructure-host-integrations/
* **OS**: Cent OS 
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
