### ISSUE TITLE
Issue: View and manage data retention

### ISSUE THREAD

**Issue by maxlemieux** [newrelic/docs-website#8908]
When linking to this page from the Community Forum, a message appears in place of the usual preview widget: 

> Sorry, we were unable to generate a preview for this web page, because the following oEmbed / OpenGraph tags could not be found: description, image

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/manage-data/manage-data-retention/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 104.0.0.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thank you @maxlemieux . apparently the forum is in process of moving to a new forum platform where this preview feature won't be available anyway, so it looks like we're going to ignore this for now and keep it in mind.
