### ISSUE TITLE
Issue: Go agent EOL policy

### ISSUE THREAD

**Issue by akhanin-dnsf** [newrelic/docs-website#8912]
Did you guys intentionally make Go Agent v3.18.0 only supported for one year while all the version before it were supported for 2 years?

![image](https://user-images.githubusercontent.com/106987117/185631186-dee066d2-fc7e-41c8-bb57-8056803168e2.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/go-agent/get-started/go-agent-eol-policy/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
@akhanin-dnsf this was due to a recent policy change. if you'd like to read up more on that, it's in https://docs.newrelic.com/docs/licenses/end-of-life/notification-changes-new-relic-saas-features-distributed-software/
