### ISSUE TITLE
Add three new release notes category

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#892]
### Is your feature request related to a problem? Please describe

As part of the platform release notes content type EoL, Austin manually migrated three categories of former platform release notes over to standard release notes. These new categories need to be included in the migration script.

### Affected categories

* https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/kubernetes-integration-release-notes/
* https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/cloud-integration-release-notes/
* https://docs.newrelic.com/docs/release-notes/diagnostics-release-notes/diagnostics-cli-release-notes/

### Describe the solution you'd like

All of these categories need the following implemented and/or included in the migration script:

* Migrate the actual content
* Ensure a version number is optional in `releaseNote.js` template, graphql, etc
* Migrate the taxonomies
* Migrate redirects (for both content and taxonomy)
* Migrate existing RSS feeds
* Add these new categories to https://docs-preview.newrelic.com/docs/release-notes
* Handle the following dummy docs:
    * https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/diagnostics-cli-nrdiag/diagnostics-release-notes
    * https://docs.newrelic.com/docs/integrations/kubernetes-integration/get-started/release-notes
    * https://docs.newrelic.com/docs/integrations/infrastructure-integrations/cloud-integrations/cloud-integrations-release-notes

### Complexifiers and potential gotchas

* Some of this content is Markdown like other release notes, some is HTML
* Cloud integrations release notes *do not have version numbers*

### Additional context

Lots and lots of context and detail in Jira DOC-6550

**Comment by jpvajda** [comment]
I'm evaluating if this is actually a launch-blocker, would like to get a rough estimate on it to get a sense if we should wait to do this post GA, there are some pretty bad trade offs to waiting: 

. It will mean the content disappears and the links are broken, so I'd like to avoid if at all possible.

**Comment by austin-schaefer** [comment]
There are 108 total release notes in these categories.

**Comment by jerelmiller** [comment]
Confirmed that these pages were pulled in from the final migration!
