### ISSUE TITLE
Unable to view app

### ISSUE THREAD

**Issue by harshps08** [newrelic/docs-website#8943]
I have followed the steps of app installation(react-native) and it show app detected in the console , but when I click on the dashboard redirect button it takes me to the explorer and shows no app available in the mobile console, but my app crashes are visible in the events tab, why can't I see my app in the mobile tab please guide
<img width="1423" alt="Screenshot 2022-08-22 at 12 37 05 PM" src="https://user-images.githubusercontent.com/104058525/185860070-f3dceb3e-6308-4509-84c4-f9f6161a6864.png">
<img width="1423" alt="Screenshot 2022-08-22 at 12 37 32 PM" src="https://user-images.githubusercontent.com/104058525/185860103-a4d02037-9ac2-4e58-8a64-5b869d4d3b64.png">

**Comment by bradleycamacho** [comment]
@harshps08 This sounds like more of a question for support or, if you don't have a support plan, for the public forum (discuss.newrelic.com). Let me know if you have any more questions, thanks!
