### ISSUE TITLE
Issue: Record and monitor deployments

### ISSUE THREAD

**Issue by jamesyale** [newrelic/docs-website#8954]
## How can we make our docs better?

The curl example of setting a deployment is very complete, but omits the detail that accounts hosted by New Relic in Europe need to hit a different API endpoint - https://api.eu.newrelic.com/v2/applications/$APP_ID/deployments.json - [per this answer](https://discuss.newrelic.com/t/cant-post-deployment-notices-to-new-relic-one/120295/6?u=j.yale). 

```
curl -X POST "https://api.newrelic.com/v2/applications/$APP_ID/deployments.json" \
     -H "Api-Key:$API_KEY" \
     -i \
     -H "Content-Type: application/json" \
     -d \
'{
  "deployment": {
    "revision": "REVISION",
    "changelog": "Added: /v2/deployments.rb, Removed: None",
    "description": "Added a deployments resource to the v2 API",
    "user": "datanerd@example.com",
    "timestamp": "2019-10-08T00:15:36Z"
  }
}'
```

It would be great if the documentation mentioned this, or how to find out where you account is hosted, or even that there are two (or more?) API endpoints. I spent a while wondering why the app ID wasn't recognised:

Querying the wrong API endpoint gives the following error, which doesn't provide many clues:

```
{"error":{"title":"We didn’t find an application with the given ID: xxx"}}
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hey @jamesyale, thanks for bringing this up! This does seem like an oversight on our end. I'm going to loop in the team and see if we can get this fixed!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
