### ISSUE TITLE
Issue: Install the ECS integration on Fargate using cloud formation

### ISSUE THREAD

**Issue by caw-ishikajain** [newrelic/docs-website#8957]
## How can we make our docs better?

* Is something confusing?
* I am confused in the last step of integrations, I tried adding a container as a sidecar but AWS throws error for networkmode - bride. host, awsvpc. I was following below doc to add a sidecar https://aws.amazon.com/blogs/compute/nginx-reverse-proxy-sidecar-container-on-amazon-ecs/
![image](https://user-images.githubusercontent.com/55681862/186065513-ea49de39-7f0a-46a4-bab0-e1a9f7c4ad72.png)

* Were you unable to complete a task? (What task?)
* Install using CloudFormation (Fargate)

Let me know what I am doing wrong.
Thanks

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/elastic-container-service-integration/installation/install-ecs-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Hello @caw-ishikajain . I've moved your request to our issues-candidate label so an expert can help you with installation. If this is urgent, I recommend filing a ticket from our [NR support page](https://support.newrelic.com/s/). Click "Support cases." :)
