### ISSUE TITLE
Create a docs site contribution dashboard

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#898]
## Description
We would like a dashboard in New Relic that shows contributor activity by page, similar to [this dashboard for the existing site](https://one.nr/0X8wodXPpRx).

## Acceptance Criteria
- [x] Create a dashboard for "Docs Pages Touched"
- [x] Replicate as much of the [existing dashboard](https://one.nr/0X8wodXPpRx) as possible

**Comment by roadlittledawn** [comment]
Dashboard done and pending @austin-schaefer 's review. Closing this issue but can tweak dashboard accordingly
