### ISSUE TITLE
Issue: PHP agent installation: Ubuntu and Debian

### ISSUE THREAD

**Issue by chielboogaard** [newrelic/docs-website#8987]
## How can we make our docs better?

The repo is broken: if i use the guide of the docs. We get the following error:

```
E: The repository ‘http://apt.newrelic.com/debian focal Release’ does not have a Release file.
N: Updating from such a repository can’t be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

this is because the repo does not follow the apt standard:

```
The file "dists/$DIST/InRelease" shall contain meta-information about the distribution and checksums for the indices, possibly signed with an OpenPGP clearsign signature (for example created by "gpg -a -s --clearsign"). For older clients there can also be a "dists/$DIST/Release" file without any signature and the file "dists/$DIST/Release.gpg" with a detached OpenPGP signature of the "Release" file, compatible with the format used by the GnuPG options "-a -b -s". 
```

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-ubuntu-debian
* **OS**: Mac OS 10.15.7
* **Browser**: Safari 15.5
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@chielboogaard thanks for pointing this out! I will check with our subject matter experts to see how we can correct this document!

**Comment by rhetoric101** [comment]
@chielboogaard which command in the doc is generating this error for you?

**Comment by chielboogaard** [comment]
Hi @rhetoric101 ,

It not the documentation that is wrong. It's the repo that is wrongly setup so the documentation is not working. So it's a technical problem not a documentation issue.

**Comment by chielboogaard** [comment]
worked out a work around by downloading an old version and installing the deb file directly

**Comment by someone-1** [comment]
@chielboogaard  can you pls explain how you got the file
