### ISSUE TITLE
Issue: Set up the Amazon CloudWatch Metric Streams integration

### ISSUE THREAD

**Issue by somensari** [newrelic/docs-website#8989]
The "Instant Observability" link under "Curated Content" is broken.

(https://docs.newrelic.com/docs/using-new-relic/welcome-new-relic/get-started/new-relic-quickstarts-overview/).

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/amazon-integrations/connect/aws-metric-stream-setup/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 104.0.0.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@somensari thanks for pointing out this broken link! I wasn't able to find any curated dashboards for Amazon CloudWatch Metric Streams, so I am going to remove this section.

**Comment by rhetoric101** [comment]
Closed by #8992
