### ISSUE TITLE
Issue: Introduction to our two user models and our user management docs

### ISSUE THREAD

**Issue by nelson-marcos-olxbr** [newrelic/docs-website#8993]
## How can we make our docs better?
Is the link [Pricing and user model table](https://docs.newrelic.com/docs/accounts/original-accounts-billing/original-users-roles/overview-user-models/#pricing-user-table) working as expected?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/original-accounts-billing/original-users-roles/overview-user-models/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@nelson-marcos-olxbr, thanks for telling us about this link issue! I am fixing this in #8996, so I am closing this issue.
