### ISSUE TITLE
Issue: AWS Elastic Beanstalk installation for PHP Not working

### ISSUE THREAD

**Issue by brnrajoriya** [newrelic/docs-website#9000]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/php-agent/frameworks-libraries/aws-elastic-beanstalk-installation-php/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by homelessbirds** [comment]
Hi @brnrajoriya super excited to learn more about your needs for this doc. What do you find confusing or in need of improvement? Looking forward to helping you!
