### ISSUE TITLE
Issue: NewRelic doesn’t show browser telemetry

### ISSUE THREAD

**Issue by DanVavilov** [newrelic/docs-website#9015]
After installing Ruby NewRelic Agent, backend sends telemetry as expected, but on the browser side, newRelic api is called with debug data (POST https://bam.nr-data.net/resources/1/…), but this data cannot be access via NewRelic Web Interface for some reason. I didn't find any solutions how to configure newRelic web to show this data. Can anyone help me with that?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
@DanVavilov This sounds like more of a question for support or, if you don't have a support plan, for the public forum (discuss.newrelic.com). Let me know if you have any more questions, thanks!
