### ISSUE TITLE
Remove agent SDK from release notes tiles

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#902]
### Description

The agent SDK has been EoLed. We should remove the tile from the release notes page. We can also do this from a content perspective post-launch. We can also just delete this tile.

### Steps to reproduce

1. Go to https://docs-preview.newrelic.com/docs/release-notes
2. Look at `Agent SDK` tile, click it, and see that it leads not to release notes but to a doc

### Expected behavior

Let's remove this entry entirely

### Screenshots

![image](https://user-images.githubusercontent.com/55203603/108413814-53f35100-71e0-11eb-80b1-9b6a2fffa964.png)

**Comment by austin-schaefer** [comment]
Possibly connected to #892

**Comment by jpvajda** [comment]
will be handled manually by the Docs Team

**Comment by barbnewrelic** [comment]
I'm fine with deleting the Agent SDK release notes tile. I'll copy out the html of the actual release notes and attach them to my EOL Jira. Unfortunately Agent SDK is still not **officially** EOL. https://newrelic.atlassian.net/browse/DOC-4498
