### ISSUE TITLE
Issue: View and manage data retention

### ISSUE THREAD

**Issue by shhudspethnr1** [newrelic/docs-website#9024]
## How can we make our docs better?
Hi, Could **Network Monitoring Data** be added to the list or referenced somewhere? This would help us communicate with a few of our customers interested in our NPM offerings. 

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/manage-data/manage-data-retention/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hi @shhudspethnr1 happy to help out on this!

@zuluecho9 or @x8a either of you know where we should start on this?

**Comment by x8a** [comment]
Let me ask the SMEs!

**Comment by x8a** [comment]
PR #9083 adds them, so I'll close the issue. Thanks for reporting this!
