### ISSUE TITLE
link to rest api docs goes to nrql page

### ISSUE THREAD

**Issue by coreyarnold** [newrelic/docs-website#9105]
The [New Relic's REST APIs](https://docs.newrelic.com/docs/apis/getting-started/introduction-new-relic-apis) link direct the user to information on NRQL (https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language/), not on the REST APIs.

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/rest-api-v2/get-started/introduction-new-relic-rest-api-v2/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 104.0.5112.101
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @coreyarnold! Thanks for filing an issue!

What link isn't working? As far as I see, the link in [New Relic's REST APIs](https://docs.newrelic.com/docs/apis/getting-started/introduction-new-relic-apis) is working as it should.

<img width="878" alt="Screenshot 2022-09-01 at 10 42 26" src="https://user-images.githubusercontent.com/55247916/187871655-dc2f661b-4e98-4c13-bb44-833949e828dc.png">

Could you point me to the link that's directing you to a NRQL doc? 👀

Thank you!

**Comment by coreyarnold** [comment]
I'll slack you the screen recording :)

**Comment by rhetoric101** [comment]
@x8a I had some time, so I took a look with our other developers. They found a duplicate redirect that was intermittently capturing the link to the API overview page. I created PR #9110 to remove that spurious redirect, and I also removed that link, since it wasn't helpful.
