### ISSUE TITLE
Issue: .NET: Configure logs in context, Option 1 is innaccurate

### ISSUE THREAD

**Issue by brnhensley** [newrelic/docs-website#9112]
## How can we make our docs better?

[_Option 1, let the agent decorate and forward the logs_](https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/#1-agent) is inaccurate and should be updated. According to @jaffinito in on the .NET eng team the .NET agent only captures the log's `message` attribute (not the entire log) and that is sent up to NRDB with the additional data like `span.id` etc included. The logs themselves are not decorated.

Something like: _"Let the agent forward your log's messages"_ is a more accurate description of what's happening.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/net-configure-logs-context-all/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for the correction, @brnhensley! I opened PR #9115, would you mind heading there and reviewing my change. Also, please feel free to propose any other wording change you see could make things more accurate!

I'll close this issue!

**Comment by brnhensley** [comment]
Yes, I'll check it out. Thanks
