### ISSUE TITLE
Issue: Create anomaly alert conditions

### ISSUE THREAD

**Issue by rodrigo-corgozinho** [newrelic/docs-website#9116]
The images on this page are showing the old threshold types (Static, Baseline, and Outlier)
I'd recommend changing them in order to show the right ones.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/other-condition-types/create-anomaly-alert-conditions/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for the tip, @rodrigo-corgozinho! I'll open a ticket so we can update the screenshots!

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
