### ISSUE TITLE
Issue: PHP agent installation: Ubuntu and Debian

### ISSUE THREAD

**Issue by someone-1** [newrelic/docs-website#9127]
## How can we make our docs better?

* Is something inaccurate or missing?

```
# wget -L https://download.newrelic.com/debian/dists/newrelic/non-free/binary-amd64/
--2022-09-03 16:05:27--  https://download.newrelic.com/debian/dists/newrelic/non-free/binary-amd64/
Resolving download.newrelic.com (download.newrelic.com)... 151.101.158.137
Connecting to download.newrelic.com (download.newrelic.com)|151.101.158.137|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-09-03 16:05:28 ERROR 404: Not Found.
```

* Were you unable to complete a task? (What task?)
unable download php agent

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-ubuntu-debian/
* **OS**: ubuntu
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @someone-1! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
