### ISSUE TITLE
Issue: Synthetic's scripted browser reference (monitor versions 0.5.0 and 0.6.0)

### ISSUE THREAD

**Issue by dlesniak-NR** [newrelic/docs-website#9129]
## How can we make our docs better?

The link for [monitor version Chrome 100 and newer documentation](https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-monitors/synthetic-scipted-browser-reference-monitor-versions-chrome100) appears to be broken and doesn't lead anywhere.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 104.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks for letting us know, @dlesniak-NR! I fixed it with PR #9130.
