### ISSUE TITLE
Issue: Go agent configuration

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#9135]
Can we update this doc to have more explicit proxy examples?  Including the section `ConfigFromEnvironment` which hopefully showcases proxy environment variables similar to all other APM agents.

Most FinTech customers have proxied networks so proxy settings are fundamental to their success.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/go-agent/configuration/go-agent-configuration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Hi @GaPeppy. I've filed a jira to grab some good proxy examples for this page. Thanks so much!
