### ISSUE TITLE
SOC2 report

### ISSUE THREAD

**Issue by bbuchananMulti** [newrelic/docs-website#9147]
We need to obtain a SOC2 report for our compliance

**Comment by x8a** [comment]
Hi, @bbuchananMulti, could you describe the problem you found in our documentation? Is it related with the [SOC 2 doc](https://docs.newrelic.com/docs/security/security-privacy/compliance/certificates-standards-regulations/soc2/)?

Thanks a lot!

**Comment by bbuchananMulti** [comment]
Hello yes I can access the link but there is no link to download a pdf version of the SOC2 report

**Comment by x8a** [comment]
Hi again, @bbuchananMulti. [Here's a link](https://newrelic.com/about/contact-security-team) to get the SOC 2 certificate. 

If you don't have any further questions, I'll close this issue at the end of day tomorrow. Thanks again!
