### ISSUE TITLE
Issue: Trace API general requirements and limits 

### ISSUE THREAD

**Issue by mrytower05** [newrelic/docs-website#9150]
## Broken Link

* The link in [THIS](https://docs.newrelic.com/docs/distributed-tracing/trace-api/trace-api-general-requirements-limits/#requirements) section where it says _"If you're using an integration that uses the Trace API (for example, [these integrations](https://docs.newrelic.com/docs/understand-dependencies/distributed-tracing/enable-configure/integrations-enable-distributed-tracing)), you must configure....."_ the link taking you to "these integrations" is broken. 

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/distributed-tracing/trace-api/trace-api-general-requirements-limits/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 104.0.0.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@mrytower05 thanks for pointing out this broken link! We are fixing this in  PR #9153, so I am going to close this issue.
