### ISSUE TITLE
Python agent changelog breaks layout

### ISSUE THREAD

**Issue by gradyy** [newrelic/docs-website#9152]
## Steps to reproduce

1. Go to https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/
2. Click on [Python agent v6.4.4.161](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60404161). Both sidebar nav and link in the document have the same behavior.
3. The page renders the changelog as the full page.

## Expected behavior

[Other changelogs](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-60403160) render as an element of the docs page without hiding the sidebar, title bar, and all other elements of the page.

## Screenshots

Expected behavior of most changelogs
![docs newrelic com_expected](https://user-images.githubusercontent.com/25714375/188948969-5dbefc9d-ebb0-4f88-8e48-d4774ea7521d.png)
Erroneous behavior of v6.4.4.161
![docs newrelic com_error](https://user-images.githubusercontent.com/25714375/188948977-01989542-c66f-4bde-9573-e32e7d56e19b.png)

## Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by akristen** [comment]
Hi @gradyy. We've filed a jira for this bug! One of our Eng teammates will look into this for you. Thanks for letting us know :)

**Comment by x8a** [comment]
Hey, @akristen 👋🏼! I saw this issue in the limbo and wanted to know what to do with it. Is this already fixed? 👀

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
