### ISSUE TITLE
Issue: New Relic API keys

### ISSUE THREAD

**Issue by ktst79** [newrelic/docs-website#9160]
## How can we make our docs better?

There is the following statement in the section of "User key". However, as of now, there is no way to prevent the user from generating user api key. Permission to generate user api key is always enabled and cannot be modified.

"To restrict a user from being able to view or manage user keys, assign them a role without those capabilities:"

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#user-key
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
