### ISSUE TITLE
Issue: Workflows variables

### ISSUE THREAD

**Issue by agius** [newrelic/docs-website#9166]
## How can we make our docs better?

You've listed the available variables, but provided no examples of values those variables might contain, or what possible values are allowed. I'm trying to translate New Relic's `priority` into OpsGenie's `"priority"`, but I can't find what values `priority` might contain besides `CRITICAL` which is in the example alert. 

Another solution would be to **not drop OpsGenie support** and stop making alerts ever more convoluted and Rube-Goldberg-Esque. PagerDuty, OpsGenie, and friends' routing rules are already a labyrinth without New Relic deciding to up the ante with bad Handlebars templates and frustrating web-based editors.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/custom-variables-incident-workflows/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
