### ISSUE TITLE
Issue: Create conditions

### ISSUE THREAD

**Issue by hwilkalis-nr** [newrelic/docs-website#9168]
## How can we make our docs better?

Under the Types of Conditions > Anomaly Conditions section, the Anomaly Alerting link is broken.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/alert-conditions/create-alert-conditions
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 105.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
Thanks a lot for letting us know, @hwilkalis-nr! 

I fixed it with PR #9189 🚀.
