### ISSUE TITLE
Issue: Get started with network monitoring

### ISSUE THREAD

**Issue by devedsonbelem** [newrelic/docs-website#9191]
New Relic start

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/network-performance-monitoring/get-started/npm-introduction/
* **OS**: Linux x86_64
* **Browser**: Chrome 103.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @devedsonbelem! Could you describe the issue you found in the [Get started with network monitoring](https://docs.newrelic.com/docs/network-performance-monitoring/get-started/npm-introduction/) doc? Thanks!
