### ISSUE TITLE
Issue: Guided install overview

### ISSUE THREAD

**Issue by sriran34** [newrelic/docs-website#9195]
## How can we make our docs better?

* Is something confusing? Unable to install Grafana on Mac
* Is something inaccurate or missing? 
* Were you unable to complete a task? (What task?) unable to complete the installation

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/installation/new-relic-guided-install-overview/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by homelessbirds** [comment]
Hi there! We're looking forward to helping you with this! Can you give us a little more insight into what you're looking for?
