### ISSUE TITLE
Issue: Voice strategies for docs that sound like us

### ISSUE THREAD

**Issue by mb-newrelic** [newrelic/docs-website#9199]
Hi, fabulous docs team! Can you update the link to the UI Writing guidelines at the bottom of this "Voice strategies" doc? We now have a public-facing  UI style guide page on the docs site! Please also cut references to the internal resource and VPN requirement.  Thanks! Y'all rock!

Here's the new public docs link: https://docs.newrelic.com/docs/style-guide/ui-writing/ui-writing-style

**Comment by homelessbirds** [comment]
Thanks so much for this addition! Made the changes :)
