### ISSUE TITLE
Decide on the Doc Site Right Rail Exp.

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#92]
### User Story

As a user of the Docs Sites I should be able  to see a useful right rail on the site that aids me in my exploration the Docs Site. 

### Considerations

- show the faces of contributors on pages, maybe in the right rail, Or at least build a contributor page of all contributors, like a "leaderboard" 
- include CTAs like add data, or run this installer buttons
- Representing the navigation of page content in the right rail -- is it useful? If it is, does it need to start at H1, or can be it be deeper? 
- edit the page + create an issue is super important.
- no need to thumb up pages, it's not meaningful.. Or is? Maybe user test this as we get some good customer sentiment from the comments. Will users be ok just filing issues to share their challenges? or is that workflow to many steps?

### AC

- Create a high level mockup and get feedback from key stakeholders

**Comment by jpvajda** [comment]
Shared with @markweitzel for his input...

**Comment by jpvajda** [comment]
I'm also thinking about our limited timeline and goals, I'm starting to think we may want to keep the Right Rail approach very simple, like show the navigation header elements on the page, like we do today, then add in the edit / contribute buttons and page time stamp.  then we can revisit if it needs more sophistication.

**Comment by djsauble** [comment]
I'm okay with starting simple.

**Comment by jpvajda** [comment]
Closing and moving these details to an MMF Planning doc.
