### ISSUE TITLE
Issue: Synthetic monitoring: SLA report

### ISSUE THREAD

**Issue by mika4480** [newrelic/docs-website#9232]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

*https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/pages/synthetic-monitoring-aggregate-monitor-metrics/#understanding
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown
May you please update this section as you can no longer customized the Apdex for Synthetics:

Apdex: The average [Apdex](https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measuring-user-satisfaction) across all monitors. Monitors have a default [Apdex T](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/glossary#apdex_t) of 7 seconds, but you can customize Apdex T for individual monitors by [editing their settings](https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/using-monitors/adding-editing-monitors#editing-monitors). [Apdex F](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/glossary#apdex_f), which defines a frustrating result, is always four times Apdex T. For more information about Apdex, see [Apdex: Measuring user satisfaction](https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measuring-user-satisfaction).

For individual SLA reports, the Apdex score only includes the selected monitor.

% Satisfied: The percentage of monitor results which complete in a ["satisfying" time](https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measuring-user-satisfaction#bullet-satisfied). A satisfying time is defined as a monitor result that completes in [Apdex T](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/glossary#apdex_t) or less.

% Toleration: The percentage of monitor results which complete in a ["tolerable" time](https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measuring-user-satisfaction#bullet-tolerating). A tolerable time is greater than [Apdex T](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/glossary#apdex_t), but less than [Apdex F](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/glossary#apdex_f) (four times [Apdex T](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/glossary#apdex_t)).

% Frustrated: The percentage of monitor results which complete in a ["frustrating" time](https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measuring-user-satisfaction#bullet-tolerating). A frustrating time is greater than [Apdex F](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/glossary#apdex_f) (four times [Apdex T](https://docs.newrelic.com/docs/apm/new-relic-apm/getting-started/glossary#apdex_t)).

**Comment by akristen** [comment]
Hi @mika4480. We have received this issue request and will be following up with our synthetic experts to confirm this is something that should be removed. Thanks so much!

**Comment by akristen** [comment]
Hi @mika4480. I've actually made this a jira, as I think this page can use some love and care. I'm going to close this issue, but I've reflected in the jira to follow up with you when the changes are made :)
