### ISSUE TITLE
Issue: Service level management: successfully influence reliability decisions

### ISSUE THREAD

**Issue by mika4480** [newrelic/docs-website#9233]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/optimize-slm-guide/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown
Hello, 

Where it states: Simply adjust the duration < 1.78 portion of the second query to match the DURATION (95%) result in your original baseline copied to your notepad.

Is it supposed to have the duration for that particular transaction 1.82 or the overall transaction 1.78 for the latency baseline for the sinatra/purchase?

**Comment by akristen** [comment]
Hi @mika4480 I've gone ahead and made this a jira so we can update this doc completely. :) Thanks for bringing it to our attention!
