### ISSUE TITLE
Issue: No data appears (.NET)

### ISSUE THREAD

**Issue by aneeshwara** [newrelic/docs-website#9249]
Hi 

We have configured .net agent on the server and we are unable to get the data on the new relic console and IIS applictions also not showing the APM
installed .net infra agent
installed .net cli agent
installed .net agent
![image](https://user-images.githubusercontent.com/44406063/189836581-595315bc-6549-4bd7-b256-effddff88621.png)

**Comment by x8a** [comment]
Hey, @aneeshwara! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
