### ISSUE TITLE
dashboard is in a reload loop

### ISSUE THREAD

**Issue by ivosdc** [newrelic/docs-website#9269]
Hi, when I go to one of our NR-dashboards (e.g. https://onenr.io/xxxxx) my browser goes in a permanent reload-loop. (Browsers Edge and Chrome, MacOS 12.5.1)
So I am not able to see the dashboard. What can I do?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/solve-common-issues/find-help-use-support-portal/
* **OS**: MacOS 12.5.1
* **Browser**: Edge Version 105.0.1343.33 (Official build) (x86_64)
 and Chrome Version 105.0.5195.102 (Official Build) (x86_64)
* **Device**: macbook

https://user-images.githubusercontent.com/35397952/190154298-c4045611-b4ff-4e4d-96c0-4c307c1f08a2.mov

**Comment by ivosdc** [comment]
a HAR file from edge
[one.eu.newrelic.com.har.zip](https://github.com/newrelic/docs-website/files/9566334/one.eu.newrelic.com.har.zip)

**Comment by zuluecho9** [comment]
sorry @ivosdc, unfortunately I don't think we can help you with that. I did forward this to an internal team and hopefully they will get back to us or you, but in meantime I'd suggest either going the support route or, if you don't have support, then use the community forum: https://discuss.newrelic.com/

**Comment by zuluecho9** [comment]
@ivosdc apparently that is a known issue they're currently trying to fix.

**Comment by ivosdc** [comment]
ty for investigation
