### ISSUE TITLE
Issue: Synthetic monitor public minion IPs

### ISSUE THREAD

**Issue by xorxsan** [newrelic/docs-website#9272]
## How can we make our docs better?

The list of public minions is wrong. They are all prefixed with `AWS_`, but the terraform provider gives the following error:
```
Error: BAD_REQUEST Invalid public Location: AWS_US_WEST_1
```

If the prefix is removed, everything works.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/administration/synthetic-public-minion-ips/
* **OS**: Win x64
* **Browser**: Chrome
* **Device**: Desktop

**Comment by zuluecho9** [comment]
Closing this. thank you @xorxsan. We are adding a note that when used via API, they don't require a prefix like that.
