### ISSUE TITLE
Issue: Java: Configure logs in context

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#9285]
"logs in context" involves two distinct separate motions:

- decorating logs with meta-data
- forwarding logs to cloud collector

Automatic logs in context does both.

The section on manual logs in context is confusing and doesn't draw a clear enough distinction that it is log decoration only and the customer will have to figure out log forwarding on their own.

"you could use our manual solutions to send linking metadata."

The latter part of this statement's use of the word "send" is part of the confusion.  The original LiC solution was decorating only; there really was no sending.

So my vote is to clearly articulate the separate motions and the fact that "Manual logs in context option" is decoration only.

danke

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/logs/logs-context/java-configure-logs-context-all/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks @GaPeppy. I'll take a look at this. I'm actually working on some logs docs improvements so I might throw a meeting on for us to discuss more.

**Comment by zuluecho9** [comment]
I'm going to be working on improving these things soon, will close this.
