### ISSUE TITLE
Issue: PHP agent compatibility and requirements

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#9294]
## How can we make our docs better?
Laravel 4.x, 5.x, 6.x, and 7.x are listed as supported frameworks. However, they have already reached EOL.
https://laravelversions.com/en

So I think Laravel can be removed from the supported framework list.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/php-agent/getting-started/php-agent-compatibility-requirements/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by homelessbirds** [comment]
Hi there! Thanks for letting us know. I made the changes you suggested in this PR: https://github.com/newrelic/docs-website/pull/9319
