### ISSUE TITLE
Issue: New navigation UI transition guide

### ISSUE THREAD

**Issue by mb-newrelic** [newrelic/docs-website#9306]
Hi, love this super helpful guide and have a few thoughts:

It would be great if I could see at a scanning speed glance that I can turn on and off capabilities in the left nav. (On a close read I see that under "customize" but users are missing it and getting worried when they turn things off (unpin them) that they can't get those capabilities back. Maybe this is a small H2 edit for the "customize your experience" subhead?

It'd also be nice if the banner at the top gave us a clearer idea of when the navigation is going to change and how that's going to work. Will it be on by default soon? Will I be able to switch back after that happens?

Finally, this represents a huge change to how I am going to work in New Relic. Can the docs team help make sure this doc is prominent through the change and after for a while as users get used to the new navigation?

Thanks, y'all rock!

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/new-navigation-transition-guide/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 105.0.0.0
* **Device**: Unknown

**Comment by homelessbirds** [comment]
Hi @mb-newrelic this is part of my upcoming work and I will keep your feedback in mind as I work on our new UI launch. Thanks so much.

**Comment by homelessbirds** [comment]
This is being done this sprint! Thanks @mb-newrelic
