### ISSUE TITLE
Issue: High security mode

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#9314]
`Java | 3.7 or higher (enabled by default)`

High security mode is not 'enabled by default' on any APM agent.  So really unclear what 'enabled by default' is referring to?

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/agents/manage-apm-agents/configuration/high-security-mode/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
Pinged Java agent team to check on this one
