### ISSUE TITLE
[Bug Bash] Javascript error on attribute dictionary page

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#932]
## Description
Javascript error in console: 
```
Failed to load resource: the server responded with a status of 404 ()
https://docs-preview.newrelic.com/page-data/docs/using-new-relic/welcome-new-relic/getting-started/glossary/page-data.json/
```

## Steps to Reproduce

Just go on the page!

## Expected Behavior

Not to have the error, but it also seems like it's NOT related to the attribute dictionary page 

### Page
https://docs.newrelic.com/attribute-dictionary/

### Environment
* **OS**: macOS Catalina
* **Browser**: Chrome
* **Device**: Macbook

**Comment by mmfred** [comment]
@caylahamann - is this fixed? I couldn't reproduce.

**Comment by rudouglas** [comment]
@caylahamann this does look like it has been corrected at some point, I can't reproduce it in Chrome, it might have been related to the `docs-preview` site specifically, but if you are still seeing this please let me know :)

**Comment by roadlittledawn** [comment]
FWIW, we dug in a little bit to these `page-data.json` 404s a bit [here](https://github.com/newrelic/docs-website/issues/1874#issuecomment-824252533). the TL;DR is Gatsby will try to pre-fetch data for all Gatsby links on a given page and sometimes there is no data to fetch (ex, if a link redirects to a different page that actually has data).

**Comment by rudouglas** [comment]
@caylahamann this looks like it's part of a broader cross-site issue involving `page-data.json`, there's another ticket open for this with more information and where the bulk of the work is being done:

https://github.com/newrelic/docs-website/issues/1874#issuecomment-824252533

So i'll close this out to keep all the work in one place :)
