### ISSUE TITLE
* adds `flask_sqlalchemy` package

### ISSUE THREAD

**Issue by davincike** [newrelic/docs-website#9323]
* adds `flask_sqlalchemy` package
* updates `wsgi.py` per other repositories 

This is currently deployed on beta. There are still some problems in the staging environment that I'm investigating; there may be additional commits to this branch.

__Originally posted by @mhl10 in https://github.com/arXiv/arxiv-auth/pull/46__

**Comment by rhetoric101** [comment]
@davincike could you clarify your request for New Relic?

**Comment by rhetoric101** [comment]
@davincike I am closing this because I'm not seeing a specific request from you about how we can help you. Feel free to reopen this is you want to clarify what you need.
