### ISSUE TITLE
Issue: Docker instrumentation for infrastructure monitoring

### ISSUE THREAD

**Issue by dominic-oconnor** [newrelic/docs-website#9333]
The [docs for the EKS Fargate sidecar](https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/installation/install-fargate-integration/) include a Task Definition that has `readOnlyRootFilesystem: true` but I haven't been able to find any documentation as to whether the ECS Fargate sidecar can also run with that flag or not. I'd like to flip that flag to true but I don't know if there are limitations/ramifications.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/linux-installation/docker-instrumentation-infrastructure-monitoring/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 104.0
* **Device**: Unknown

**Comment by rhetoric101** [comment]
@dominic-oconnor, let me check with our subject matter experts about that EKS Fargate sidecar parameter.

**Comment by alvarocabanas** [comment]
Hello, @dominic-oconnor the docs you are pointing to are not the ones to install the ECS sidecar but the EKS sidecar, on ECS we don't require that flag. You should follow this steps https://docs.newrelic.com/docs/infrastructure/elastic-container-service-integration/installation/install-ecs-integration/.
And you will see that the task we use doesn't have that flag set.
Regarding EKS, we have that flag set so the sidecar has restricted access in K8s and we mount a volume to be able to write in case the agent needs to write something.

**Comment by dominic-oconnor** [comment]
Hi @alvarocabanas Yes I understand that it's not required, but using that flag is a [best practice](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#ecs-5-remediation). I want to enable the flag in order to properly lock down our container, and I want to know whether the ECS sidecar will work with that flag set to true.
