### ISSUE TITLE
[Bug Bash] Javascript error in console for svgs on release notes landing page

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#934]
## Description

Error about SVGs on release notes landing page. 

```
Error: Invalid value for <svg> attribute width="1rem" 
```
The error is sourced in react-dom.production.min.js
## Steps to Reproduce
Go to https://docs.newrelic.com/docs/release-notes in safari and open up the javascript console

## Expected Behavior
No errors!

## Relevant Logs / Console output

Already provided above! 

### Page
https://docs.newrelic.com/docs/release-notes
https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes

### Environment
* **OS**: MacOS Catalina
* **Browser**: Safari
* **Device**: Macbook Pro

**Comment by rudouglas** [comment]
Hi @caylahamann checking in `Safari 14.0.3` it doesn't look like this error is present anymore, may have been resolved by a previous change, but if you could double-check that would be great. If you are still seeing it it would be good to get a copy of the full console log :D

**Comment by rudouglas** [comment]
closing out for the moment as per conversation with Cayla
