### ISSUE TITLE
Picture is blurry

### ISSUE THREAD

**Issue by ssundarnr** [newrelic/docs-website#9348]
Please add a clear and high resolution version of the picture.

**Comment by x8a** [comment]
Hi, @ssundarnr! Can you tell me what screenshot is blurry and in what doc? Thank you!

**Comment by ssundarnr** [comment]
@x8a the picture in this doc page - https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/customer-experience/cx-improve-page-load/

**Comment by x8a** [comment]
Hey, @zuluecho9! Could you have a look at this one? 👀 

Thank you!

**Comment by zuluecho9** [comment]
thank you @ssundarnr. fixing with https://github.com/newrelic/docs-website/pull/9412
