### ISSUE TITLE
Issue: NerdGraph tutorial: Manage user groups

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#9359]
## How can we make our docs better?
It seems users can get via GraphQL doesn't include pending users even though UI shows all users including pending user.
I appreciate it if adding description about such a gaps between UI to avoid confusion.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apis/nerdgraph/examples/nerdgraph-user-mgmt
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 105.0.0.0
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
