### ISSUE TITLE
[Bug Bash] Global navigation not very visible on mobile devices

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#936]
## Description
The top-level navigation (for other New Relic sites) is barely visible on some mobile screens (see attached screenshot).

## Screenshot(s)
This is what the home page looks on a Google Pixel 4a (Google's flagship device). Notice how the menu that contains `Developers`, `Docs`, `Open Source` and `Community` is barely visible.

![Screenshot_20210223-151336](https://user-images.githubusercontent.com/1946433/108925521-a32aee80-75f1-11eb-9081-68c421e6eb1a.png)

**Comment by jerelmiller** [comment]
I'd actually advocate for this not to be a launch blocker. Our developer site has been like this for quite some time. While I agree that this is less ideal, I'm not sure its super important to fix before launch.
