### ISSUE TITLE
Issue: Metric data structure

### ISSUE THREAD

**Issue by dkoyano** [newrelic/docs-website#9366]
## How can we make our docs better?

Under the distribution metric type there should be a line (indicated below) informing the user that this is only available through the E2M rule just as the `uniquecount` category includes.

"This type is generated only via the [event-to-metrics service](https://docs.newrelic.com/docs/accounts/accounts/data-management/introduction-events-metrics-service)."

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/data-apis/understand-data/metric-data/metric-data-type/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by homelessbirds** [comment]
Thanks for bringing this to our attention!
