### ISSUE TITLE
[Bug Bash] In the Global search, the `x` does not clear the input

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#937]
## Description
The `x` icon in the search in put (in the Global Header) does not clear the input. Instead, it removes the input's focus. It should clear the input, like we do with the navigation filter.

## Screenshot(s)
![Screen Shot 2021-02-23 at 4 15 32 PM](https://user-images.githubusercontent.com/1946433/108925968-657a9580-75f2-11eb-8c88-92137cde2e40.png)

**Comment by AubreyHewes** [comment]
also this issue is not this repo but the [gatsby-theme-newrelic](https://github.com/newrelic/gatsby-theme-newrelic) see https://github.com/newrelic/gatsby-theme-newrelic/pull/307 @jerelmiller
