### ISSUE TITLE
[Bug Bash] Sidebar menu can not collapse when being filtered

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#938]
### Description
When filtering the sidebar navigation, there are down chevrons `v` that indicate the section can be collapsed, but they do not actually work. 

Remove the chevrons when filtering as collapsing seems odd, given we are filtering the results for the user based on the search term used

### Steps to reproduce
1. Go to https://docs.newrelic.com/docs/telemetry-data-platform
2. Filter the navigation by the word "data"
3. Attempt to collapse a section in the navigation (e.g. "Understand data")

### Expected behavior
We should be doing one of the following:
* Remove the chevrons when filtering

### Actual behavior
The menu appears to "flicker" when a chevron is clicked. This _may_ be the menu collapsing and then expanding again (perhaps due to a race condition with the state management).

### Screenshots
![Screen Shot 2021-02-23 at 4 20 56 PM](https://user-images.githubusercontent.com/1946433/108926373-2567e280-75f3-11eb-884d-09b25a88a140.png)

**Comment by jpvajda** [comment]
In this case, I'd think we'd want to `Remove the chevrons when filtering` as collapsing seems odd, given we are filtering the results for the user based on the search term used. @djsauble what do you think?

**Comment by djsauble** [comment]
Yeah if you can't collapse whilst filtering, there's not much point in keeping the chevrons while in that state. The indentation should be sufficient to keep the hierarchy clear.

**Comment by AubreyHewes** [comment]
Supporting collapsing of results should be available; as there may be loads of results and you want to collapse the subjects to get to your subject...?

So the issue in that case would be; why is the collapse failing?

**Comment by jerelmiller** [comment]
@AubreyHewes thats a really good point. Our navs can get pretty lengthy, so I can definitely see the use case for wanting to collapse them when filtering. My guess is this is just a weird state management issue where a computed state (i.e. I've got a search term) is overriding the collapsed state of the component.

**Comment by AubreyHewes** [comment]
also this issue is not this repo but the [gatsby-theme-newrelic](https://github.com/newrelic/gatsby-theme-newrelic) see https://github.com/newrelic/gatsby-theme-newrelic/pull/306
