### ISSUE TITLE
[Bug Bash] Missing a page for "New Relic in practice"

### ISSUE THREAD

**Issue by zstix** [newrelic/docs-website#940]
## Description
In the top-level navigation, we have a link for `New Relic in practice` that goes to our `404` page. We should either find a path for this page or remove it from the navigation.

**Comment by jerelmiller** [comment]
It doesn't look like we have a page on the current docs site for this URL, so I'd say lets go ahead and remove it from the root nav. Not sure if there is a good landing page we can point to. If not, let's just remove it from the root nav

**Comment by roadlittledawn** [comment]
looks like there's some important / higher traffic docs in the category though. what if we update that nav link to [Using New Relic](https://docs-preview.newrelic.com/docs/using-new-relic) , which is the subdir for NR in practice? @austin-schaefer or @jpvajda , any thoughts against doing this?

**Comment by jpvajda** [comment]
Works for me looks like you already made the change. 💥
