### ISSUE TITLE
Update the screenshot to alert migration

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#9423]
## How can we make our docs better?

After [the migration from notification to workflow](https://discuss.newrelic.com/t/plan-to-upgrade-alert-notification-channels-to-workflows-and-destinations/188205), the classic menu in Alerts & AI has been removed for a newly created account.

Please update the document to align these new accounts including screenshots.

**Comment by x8a** [comment]
Thanks for filing the issue, @tanaka-takayoshi!

@homelessbirds, could you have a look at this one? Thanks a lot! 🙌🏻

**Comment by homelessbirds** [comment]
@tanaka-takayoshi hi there! Thank you for this feedback. I am happy to look into this. Would you mind linking to [the doc ](https://docs.newrelic.com/) you'd like us to edit?
