### ISSUE TITLE
Issue: Get started with incident intelligence

### ISSUE THREAD

**Issue by jakeHinton** [newrelic/docs-website#9424]
## How can we make our docs better?

* Is something inaccurate or missing?
The videos are not longer accurate as the incidentIntelligenceEnvironmentCreateEnvironment NerdGraph is now deprecated. Docs need to be updated to reflect creating custom cross account environments must be requested.

* Were you unable to complete a task? (What task?)
Users attempting to follow along would get stuck with 100% single account environments 
### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/get-started-incident-intelligence/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 105.0.0.0
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
