### ISSUE TITLE
Issue: Billable users: Billing and rules

### ISSUE THREAD

**Issue by jmmoorehead** [newrelic/docs-website#9442]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-pricing-billing/user-count-billing
* **OS**: Windows 10
* **Browser**: Edge 105.0.1343.42
* **Device**: Unknown

something confusing

**Comment by x8a** [comment]
Hi, @jmmoorehead! Could you give us some details of what you found in the docs that was confusing? Thanks a lot!

**Comment by x8a** [comment]
Hey, @jmmoorehead! If you don't have any further questions, I'll close this issue at the end of the week.

Feel free to open a new one if you see something that could use some touches!
