### ISSUE TITLE
Issue: Introduction to iOS monitoring

### ISSUE THREAD

**Issue by mortenkleveland** [newrelic/docs-website#9443]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/get-started/introduction-new-relic-mobile-ios/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

I miss an explanation of why CocoaPods is recommended (over SPM, for instance) in this sentence: "We recommend you install and configure the iOS agent using the [CocoaPods installation](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/install-configure/cocoapods-installation-configuration) method."

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
