### ISSUE TITLE
New relic integration with go : I am unable to monitor my go project with new relic

### ISSUE THREAD

**Issue by urvesh-educloud** [newrelic/docs-website#9446]
**I am unable to monitor my go project with the new relic**

**I am able to monitor using JAVA**

I have follows the documentation steps: https://docs.newrelic.com/docs/apm/agents/go-agent/installation/install-new-relic-go/

1. **From [github.com/newrelic/go-agent](https://github.com/newrelic/go-agent), use your preferred process; for example:**
    bash command `go get github.com/newrelic/go-agent/v3/newrelic`

2. **Import the github.com/newrelic/go-agent/v3/newrelic package in your application.**
   `  import github.com/newrelic/go-agent/v3/newrelic`

3. **Initialize the Go agent by adding the following in the main function or in an init block:**
      ```
      app, err := newrelic.NewApplication(
          newrelic.ConfigAppName("Your Application Name"),
          newrelic.ConfigLicense("YOUR_NEW_RELIC_LICENSE_KEY")
      )
      ```

**NOTE: I have follows all the trouble shooting as well.**

**main.go**
```
package main

import (
	"fmt"
	"io"
	"net/http"

	"github.com/newrelic/go-agent/v3/newrelic"
)

var newrelicApp *newrelic.Application

func main() {
	app, err := newrelic.NewApplication(
		newrelic.ConfigAppName("MyAppMain"),
		newrelic.ConfigLicense("280d644a5b4fc4859d5fa75b8897f4422bb5NRAL"),
		newrelic.ConfigAppLogForwardingEnabled(true),
	)
	if err != nil {
		fmt.Printf("error is " + err.Error())
	} else {
		newrelicApp = app
		http.HandleFunc(newrelic.WrapHandleFunc(app, "/test", customEvent))
	}
}

func customEvent(w http.ResponseWriter, req *http.Request) {
	io.WriteString(w, "recording a custom event")

	newrelicApp.RecordCustomEvent("MyAppMainEvent", map[string]interface{}{
		"text":      "Hello VP",
		"env":       "go_local",
		"alertType": "error",
		"priority":  "Critical",
		"source":    "MyAppMain",
	})
}
```

**Comment by x8a** [comment]
Hey, @urvesh-educloud! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
