### ISSUE TITLE
Too much space between nested list items

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/docs-website#945]
### Description

Visit the following page: https://docs-preview.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/view-your-opentelemetry-data-new-relic#explorer

You'll notice the space between the list items is too large. Here is a screenshot:

<img width="903" alt="Screen Shot 2021-02-23 at 10 13 30 PM" src="https://user-images.githubusercontent.com/565661/108956416-80fe9400-7624-11eb-98ba-c0915f061b9c.png">

**Comment by AubreyHewes** [comment]
@jerelmiller the docs-preview url quoted in this and other issues are a 404 ; 

e.g. (this issue) https://docs-preview.newrelic.com/docs/integrations/open-source-telemetry-integrations/opentelemetry/view-your-opentelemetry-data-new-relic#explorer

Removing the `-preview` gets the current doc...

**Comment by jerelmiller** [comment]
Hey @AubreyHewes good catch! We were hosting our site at docs-preview up until yesterday when we launched our docs site public! As you mentioned, removing the `-preview` should get you to the right place. Thanks for mentioning that! We should probably do a quick audit on some of our open issues to make sure they link to the right place.

**Comment by AubreyHewes** [comment]
@jerelmiller or a redirect from docs-preview; maybe easier that rewriting X issues ? ;-)

**Comment by jerelmiller** [comment]
@AubreyHewes Haha good point! Normally I'd say yes, but we are repurposing docs-preview for some other things in the future, so the 404 will actually be the correct behavior. Growing pains 😬

**Comment by jerelmiller** [comment]
Opening back up for now. After more discussion in #1110, we might opt for an update to our styles to account for this.
