### ISSUE TITLE
Issue: "Copy" button not working (Instructions to create What's New posts)

### ISSUE THREAD

**Issue by rkbodenner** [newrelic/docs-website#9455]
When I click the "Copy" button next to the example Markdown for a What's New post, my clipboard doesn't change. It's difficult to select only the example text using the mouse for manual copying. Cmd-A doesn't work to select the example text only, it grabs all the text on the page.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/style-guide/writing-docs/article-templates/whats-new-template/
* **OS**: Mac OS
* **Browser**: Chrome
* **Device**: Mac

**Comment by akristen** [comment]
We were able to work through this issue on a Zoom call. :)
