### ISSUE TITLE
Add workloads tile to homepage

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#948]
### Tell us what you need

* The current docs homepage has a workloads tile under FSO
* The preview site doesn't
* We should add it

### Anything else you'd like to share?

![image](https://user-images.githubusercontent.com/55203603/109063014-80eeaa80-769d-11eb-8ad7-6f23c332f859.png)

**Comment by austin-schaefer** [comment]
@mmfred : Can we add the broken "Serverless" tile link on the homepage to this?

**Comment by jerelmiller** [comment]
For whoever picks up this ticket, homepage is here: https://github.com/newrelic/docs-website/blob/develop/src/pages/index.js (I'm also happy to do this work if need be)

**Comment by mmfred** [comment]
Okay. Here's the PR @jerelmiller and @jpvajda 

https://github.com/newrelic/docs-website/pull/1026
