### ISSUE TITLE
Issue: Set up SNMP data monitoring

### ISSUE THREAD

**Issue by Sridhar-v-n** [newrelic/docs-website#9484]
## How can we make our docs better?

* Is something confusing?
* Yes, We have configured the SNMP on the devices and docker. But i am not able to see those devices and logs/alerts on the NewRelic UI. What additional steps are needed for fixing this.
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/network-performance-monitoring/setup-performance-monitoring/snmp-performance-monitoring/
* **OS**: Windows 10
* **Browser**: Firefox 105.0
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @Sridhar-v-n! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
