### ISSUE TITLE
Issue: Transaction are not getting recorded to APM dashboard only for one env.

### ISSUE THREAD

**Issue by sauravBB** [newrelic/docs-website#9487]
**Errors in newrelic_agent.log** that i can see:-

{"v":0,"level":30,"name":"newrelic","hostname":"${hostname}","pid":18,"time":"2022-09-14T09:01:11.190Z","msg":"Not adding native metric sampler.","component":"sampler","error":{"message":"Module did not self-register: '/usr/src/app/node_modules/@newrelic/native-metrics/build/Release/_newrelic_native_metrics-8_0_0-native_metrics-93-linux-x64.node'.","stack":"Error: Module did not self-register: '/usr/src/app/
 (node:internal/modules/cjs/loader:981:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n    at Function.wrappedLoad [as _load] (/usr/src/app/node_modules/newrelic/lib/shimmer.js:307:24)\n    at Module.require (node:internal/modules/cjs/loader:1005:19)\n    at require (node:internal/modules/cjs/helpers:102:18)\n    at Object.load (/usr/src/app/node_modules/@newrelic/native-metrics/lib/pre-build.js:52:10)\n    at Object.<anonymous> (/usr/src/app/node_modules/@newrelic/native-metrics/index.js:11:24)\n    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)"}}

**Other details:-**
"newrelic": "9.1.0",
"@newrelic/next": "0.3.0",

**Comment by x8a** [comment]
Hey, @sauravBB! Thanks a lot for your question. Unfortunately, this is a documentation repository and we cannot provide with a technical solution such as the one you need.
However, we can point you to the [Explorers Hub](https://discuss.newrelic.com/), a community of New Relic users and experts where you can ask questions and find answers to problems similar to yours.
