### ISSUE TITLE
Issue: Customize your webhook payload

### ISSUE THREAD

**Issue by dkoyano** [newrelic/docs-website#9492]
## How can we make our docs better?

The line below can be clarified under Webhook Values:
You may also add custom variables by using your own key/value pairs.

To clarify:
You may also add custom variables by using your own static key/value pairs. (ie. "Error Type": "Some Error").

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/new-relic-alerts/advanced-alerts/advanced-techniques/customize-your-webhook-payload/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 105.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
I closed it with PR #9504.

Thanks for pointing us to this mismatch with the UI 💃🏻! Feel free also to edit docs yourself if you see issues such as this 🙌🏻.
