### ISSUE TITLE
Issue: createTracer (browser SPA API)

### ISSUE THREAD

**Issue by CherylFrankenfield** [newrelic/docs-website#9493]
## How can we make our docs better?

Under #2: From Page views, select a browser interaction, then select the **Breakdowns** tab.

This should read: 
From Page views, select a browser interaction, then select the **Ajax requests** tab.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/browser/new-relic-browser/browser-agent-spa-api/createtracer-browser-spa-api/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
I closed the issue with PR #9503. 

Thanks for pointing us to this mismatch with the UI 💃🏻! Feel free also to edit docs yourself if you see issues such as this 🙌🏻.
