### ISSUE TITLE
Please add Tessen instrumentation for stitched path buttons

### ISSUE THREAD

**Issue by rhetoric101** [newrelic/docs-website#95]
newrelic/developer-website#352 # Is your feature request related to a problem? Please describe

The documentation team is trying to track customer usage of buttons on the Drupal doc site that take users into installation assistants within the product. To do this, we'd like to request some Tessen instrumentation that captures when users click these buttons.

We're not sure if the solution applies to all pages in the docs site, or whether it will require the instrumentation of every page that contains these special buttons. Here are some links to pages that have these buttons (but there are more):

* ~https://docs.newrelic.com/docs/integrations/kubernetes-integration/get-started/introduction-kubernetes-integration~
* ~https://docs.newrelic.com/docs/integrations/kubernetes-integration/installation/kubernetes-integration-install-configure~
* https://docs.newrelic.com/docs/integrations/prometheus-integrations/get-started/send-prometheus-metric-data-new-relic
* ~https://docs.newrelic.com/docs/integrations/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration~
* ~https://docs.newrelic.com/docs/agents/c-sdk/install-configure/install-c-sdk-compile-link-your-code~
* ~https://docs.newrelic.com/docs/agents/go-agent/installation/install-new-relic-go~
* ~https://docs.newrelic.com/docs/agents/java-agent/installation/install-java-agent~
* https://docs.newrelic.com/docs/agents/net-agent/installation/introduction-net-agent-install
* https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent
* https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-overview
* https://docs.newrelic.com/docs/agents/python-agent/installation/standard-python-agent-install
* https://docs.newrelic.com/docs/agents/ruby-agent/installation/install-new-relic-ruby-agent

### Describe the solution you'd like

We would like a Tessen event generated when users click on these buttons.

### Describe why this important to you

We hope this will help us assess the effectiveness of these buttons for driving users to the installation assistants.

**Comment by jpvajda** [comment]
@roadlittledawn was going to estimate this so we can prioritize it.
