### ISSUE TITLE
Issue: Configure Prometheus OpenMetrics integrations

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#9517]
The number one issue with metric ingestion for large enterprises is cardinality problems.  So the number one need of large enterprise with POMI is the ability to filter or remove dimensions/tags.

This configuration example documentation does not cover that use-case.

Please provide example of configuration for cardinality pruning.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-openmetrics/configure-prometheus-openmetrics-integrations/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by homelessbirds** [comment]
@x8a is this something you work with? If not, feel free to hand it back to me!

**Comment by x8a** [comment]
I'd say we need the help from our friends in TDP here 🙌🏻.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
