### ISSUE TITLE
Add Prometheus operator to guide: Set up your Prometheus remote write integration

### ISSUE THREAD

**Issue by nserrino** [newrelic/docs-website#9521]
NR has a great guide to setting up Prometheus remote write.

However, it is lacking instructions on how to set up remote write when using the Prometheus operator. 

The instructions are different, and I struggled for a while trying to orient myself before identifying that the operator needed a different set of steps.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/install-configure-remote-write/set-your-prometheus-remote-write-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by htroisi** [comment]
Fixed by https://github.com/newrelic/docs-website/pull/9867

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
