### ISSUE TITLE
Issue: Incorrect examples on "Translate PromQL queries to NRQL"

### ISSUE THREAD

**Issue by nserrino** [newrelic/docs-website#9523]
There are examples for equivalent NRQL queries to a given PromQL query. 

Unfortunately, many of the examples are not actually equivalent.

For example, this "latest" NRQL query is not equivalent to the "sum" query performed in the PromQL comparison.

![image](https://user-images.githubusercontent.com/5460125/192866011-791efc57-3422-439c-ac75-ef0b182fd89a.png)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/view-query-data/translate-promql-queries-nrql/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
@jeff-colucci : Can you take a look at this querying-related ticket?

**Comment by jeff-colucci** [comment]
No problem, I'll get this looked at and fixed up as soon as I can!

**Comment by kscaldef** [comment]
@nserrino While i agree with you that in general NRQL's `latest` is not at all the same as PromQL's `sum`, I think that for the narrow use case described here they are.  The critical words in the use case are "current" and "unique".  If it's the case that `id` is sufficient to define a unique metric time series than any of the PromQL aggregators `sum`, `avg`, `max`, or `min` will produce the same result and that result is the same as NRQL `latest`.  But, I agree that this example could probably use better explanation.  Do you have any suggestions about language which would help clarify it?

**Comment by ealbright-nr** [comment]
@jeff-colucci we updated this doc last week to use `sum` for NRQL in the example above. Can we close, or was it reopened for another reason?

https://docs.newrelic.com/docs/infrastructure/prometheus-integrations/view-query-data/translate-promql-queries-nrql/
