### ISSUE TITLE
Issue: Request queue server configuration examples

### ISSUE THREAD

**Issue by lsaunitti** [newrelic/docs-website#9545]
## How can we make our docs better?
Add how do in GCP Load Balancer

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/applications-menu/features/request-queue-server-configuration-examples/

**Comment by akristen** [comment]
Hi @lsaunitti. I'm not sure what you mean by "Add how do in GCP Load Balancer". Do you mean having more direction with GCP load balancer? Can you reply with more details?

**Comment by akristen** [comment]
I'm going to go ahead and close this, but can reopen it whenever! :)
