### ISSUE TITLE
Issue: Alert quality management: optimize your alerts and reduce alert fatigue

### ISSUE THREAD

**Issue by sskilbred** [newrelic/docs-website#9563]
## How can we make our docs better?

Now that an AQM Quickstart was added to I/O, the process of adding the dashboard has become much easier. It would be great if the docs can reflect that :) 
Link to AQM Quickstart: https://newrelic.com/instant-observability/alert-quality-management

PS! I don't know for sure if the 2 dashboards (quickstart vs repo) are exactly the same, that should be verified.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/observability-maturity/uptime-performance-reliability/alert-quality-management-guide/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by akristen** [comment]
Thanks for sending in this issue! I'll connect with our I/O team and the alerts & AI team to see if there's any work we can do. I'll update you here when a jira ticket has been made.

**Comment by akristen** [comment]
Hi @sskilbred you can follow this issue as it relates to roadmap work here: https://issues.newrelic.com/browse/NR-54159
