### ISSUE TITLE
Issue: Cassandra monitoring integration

### ISSUE THREAD

**Issue by tanaka-takayoshi** [newrelic/docs-website#9580]
## How can we make our docs better?

It looks incorrect troubleshooting step in the Cassandra integration document since JMXTerm is a tool for JMX.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/cassandra-monitoring-integration/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
I fixed it in PR #9582. Thanks for letting us know!
