### ISSUE TITLE
[Localization] Update translation vendor secret in localization actions

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#960]
## Summary 
We need to update a few things in our Github Actions AFTER these two tickets are completed #994 #995. 
* [x] Update the translations secrets (talk to Julien for the new destination for translation jobs) 
* [x] Update the cron jobs: *Send content to be translated* will execute every Thursday at 1am (1am because of issues of sending the context and timing with Amplify deployments) and *Check for translated content* daily at 12pm

**Comment by jpvajda** [comment]
I've asked @jmiraNR to confirm if we can work on this in Sprint 0

**Comment by jmiraNR** [comment]
@jpvajda I have work to do for this (if i understand correctly). But this task is dependent on [issue #995](https://github.com/newrelic/docs-website/issues/995) and additional work off the serialized HTML files.

**Comment by jpvajda** [comment]
@jpvajda that's correct it sounds like we need to confirm the following:

>  talk to Julien for the new destination for translation jobs

**Comment by zstix** [comment]
## Acceptance Criteria
* [ ] @jmiraNR will give us the name of the project in our translation vendor
* [ ] Add the corresponding secret to our GitHub secrets (consumed in actions)
