### ISSUE TITLE
Provide a JSON endpoint for release notes data

### ISSUE THREAD

**Issue by jpvajda** [newrelic/docs-website#961]
a JSON endpoint for release notes will provide teams the ability to reference release note data in NerdGraph. In the old Docs world, a scrapper was pulling in agent release note data and making that data available in the Nerdgraph customer schema. So we'll want to provide a publically facing JSON endpoint that will provide similar data.

### References

- @erabug inquired about this as she wrote the code for the [scrapper](https://source.datanerd.us/agents/agent-releases)
- We currently offer [release notes data in XML format](https://docs-preview.newrelic.com/docs/release-notes/agent-release-notes/nodejs-release-notes/feed.xml)for our RSS feeds 💯 so the same data would be provided in JSON format.
- The new endpoint should be added to the WIKI and explaination of how it can be used should also be documented. 

### Use case(s)

[Agent grounds keeper pulls in this data](https://discuss.newrelic.com/t/groundskeeper-nerdpack/84168) seems to be using this[query](https://github.com/newrelic/nr1-groundskeeper/blob/main/nerdlets/groundskeeper-nerdlet/queries.js)

```
in the last week it looks like agent groundskeeper had 32 active users. so it's definitely an app some users find useful
but a very small % of our 1, 270 weekly app users over the same week
```

Support Innovation has a  Release Notes Parser.  Cade Conklin developed that against the docs site, and now needs to migrate it to work with the new Open Source docs  >  @cade-conklin

**Comment by jpvajda** [comment]
We need to decide on level of effort and approach

**Comment by zstix** [comment]
We've got a couple of options for how we could go about handling this:
* Create an endpoint that functions exactly like the old / existing endpoint (`sp:8`)
* Create a JSON endpoint that returns all the data, would require updates to how it's consumed (`sp:3`)
* Do nothing and update the consumer to fetch the content from the repo (no work for docs devs)

**Comment by jerelmiller** [comment]
> Create an endpoint that functions exactly like the old / existing endpoint

To add to this, what makes this option particularly difficult is the fact we are writing JSON files, which are served statically, not via a server. Because of this, query params are especially hard to do. We may or may not be able to add a redirect rule in Amplify to handle this, but we would need some time to figure out how best to use query params for static assets.

**Comment by jpvajda** [comment]
@jerelmiller / @zstix I like option 2. It's then up to the consumer to define how the data is consumed.

> Create a JSON endpoint that returns all the data, would require updates to how it's consumed (sp:3 - sp:5)

**Comment by jpvajda** [comment]
@erabug any opinions?

**Comment by jpvajda** [comment]
@erabug confirmed  > Create a JSON endpoint that returns all the data, would require updates to how it's consumed (sp:3 - sp:5)

will work

**Comment by jpvajda** [comment]
@cade-conklin is also interested in this endpoint 🎈
