### ISSUE TITLE
Issue: RabbitMQ monitoring integration

### ISSUE THREAD

**Issue by tcgbrett** [newrelic/docs-website#9611]
## How can we make our docs better?

EOL Note has a link to an Explorer's Hub post that returns a 404. 
> As of April 2022, we're discontinuing support for several capabilities, including the RabbitMQCluster entity. For more details, including how you can easily prepare for this transition, see our [Explorers Hub post](https://discuss.newrelic.com/t/q1-bulk-eol-announcement-fy23/181744).

**Comment by homelessbirds** [comment]
Hi @tcgbrett thanks for flagging this! Can you let us know which specific doc you're referring to? Thank you!

**Comment by paperclypse** [comment]
@homelessbirds I think it's this doc https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/rabbitmq-monitoring-integration/

**Comment by paperclypse** [comment]
@homelessbirds It looks like the Explorers Hub post doesn't exist anymore. Let's just delete that sentence with the link.

**Comment by akristen** [comment]
@paperclypse @homelessbirds @tcgbrett I went ahead and just made this change, so am closing this issue~ https://github.com/newrelic/docs-website/pull/9734
