### ISSUE TITLE
Issue: Scripted browser examples

### ISSUE THREAD

**Issue by Leels** [newrelic/docs-website#9614]
The scripted browser reference hyperlink no longer works in this sentence:

"For a detailed guide to all the available functions, see [Synthetic's scripted browser reference](https://docs.newrelic.com/docs/synthetics/new-relic-synthetics/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050)."

This was changed with the new runtime. I believe it should be https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetic-scripted-browser-reference-monitor-versions-chrome-100 for the new runtime.

There is also still the reference for versions 0.5.0 and 0.6.0. https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/synthetics-scripted-browser-reference-monitor-versions-050
### Doc information (don't delete this section)

Thanks!

* https://docs.newrelic.com/docs/synthetics/synthetic-monitoring/scripting-monitors/scripted-browser-examples
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 105.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @akristen! Could you have a look at this one? Thanks!

**Comment by akristen** [comment]
Hi @Leels you can check the updated link at this PR! https://github.com/newrelic/docs-website/pull/9763
