### ISSUE TITLE
Issue: 404

### ISSUE THREAD

**Issue by andrew-lozoya** [newrelic/docs-website#9629]
https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/basic-alerting-concepts
Click path: (Issues and Incident management and response) from left hand menu

https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/Issues-and-Incident-management-and-response.mdx

Recieved 404

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-intelligence/Issues-and-Incident-management-and-response.mdx
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 106.0.0.0
* **Device**: Unknown

**Comment by x8a** [comment]
Hi, @andrew-lozoya! This has been fixed in PR #9625, it'll be live later today 🙌🏻.
