### ISSUE TITLE
Japanese header Free account button should send to Japanese Sign-up page

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#964]
### Description

The Free account button on the Japanese header sends the reader to the English sign-up page and not the Japanese one.

### Steps to reproduce

1. Go to Japanese Docs home page
2. Click on Free account button
3. Link lands you on newrelic.com/signup

### Expected behavior

Link from Japanese header lands you on [https://newrelic.com/jp/signup](url)

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

**Comment by austin-schaefer** [comment]
@jpvajda @zstix Another one that would be good to knock out.

**Comment by jpvajda** [comment]
What is the destination URL for this? @jmiraNR  Where do we send japanese users to sign up?

**Comment by jpvajda** [comment]
actually i found it: https://newrelic.com/jp/signup
