### ISSUE TITLE
All Japanese sign-up/free account links throughout the Docs site need to send to Japanese sign-up page

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#965]
### Description

All the links within the Japanese Docs site are currently sending the user to the US sign-up page instead of sending the user to the Japanese sign-up page page.

### Steps to reproduce

1. Go to /docs/telemetry-data-platform/ingest-manage-data/get-started/get-know-telemetry-data-platform
2. Toggle to Japanese
3. Click on [Sign-up] ([サインアップ]) in the Tip box.

### Expected behavior

The link on the Japanese docs site should send the user to: https://newrelic.com/jp/signup
This behavior should happen throughout the site. The translation process does not edit URL so if this could be done programmatically that would be best.

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

**Comment by jpvajda** [comment]
@jmiraNR what is the japanese sign up url ?

**Comment by jmiraNR** [comment]
@jpvajda 
The link on the Japanese docs site should send the user to: newrelic.com/jp/signup.

**Comment by jpvajda** [comment]
sorry didn't see the url in the issue as it's not formatted, https://newrelic.com/jp/signup now it's there.
