### ISSUE TITLE
Some system strings need to be translated on the Japanese site

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#966]
### Description

A few strings show in English and need to be translated.

### Steps to reproduce

1. Go to any article in Japanese
2. [Filter navigation] and [On this page] are not translated

### Expected behavior

All system strings are translated.

### Screenshots

N/A

### Additional context

N/A

### Environment

N/A

**Comment by jmiraNR** [comment]
I have the translations. Please advise on best way to share.

**Comment by jerelmiller** [comment]
@jmiraNR could you just add them here and I can get this updated accordingly?

**Comment by jmiraNR** [comment]
@jerelmiller 
On this page
このページの目次
-----------------------------------------
Filter navigation
ナビゲーションの絞り込み
-----------------------------------------
Free account
無料アカウント

**Comment by jerelmiller** [comment]
Thank you!
