### ISSUE TITLE
Fix English on JP home page

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#9673]
## Description

The JP home page has a lot of English strings. These strings should be translated so the JP home looks more like the KR home.

## Steps to reproduce

1. Go to ['...'](https://docs.newrelic.com/jp/)

## Expected behavior

Strings/text is in Japanese

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
