### ISSUE TITLE
New Relic in banner sends to English site not local sites

### ISSUE THREAD

**Issue by jmiraNR** [newrelic/docs-website#9674]
## Description

The New Relic logo in the top banner of the JP or KR sites send the user to the English newrelic.com site and not the respective local sites (newrelic.com/jp and newrelic.com/kr)

## Steps to reproduce

1. Go to ['...'](https://docs.newrelic.com/jp) or https://docs.newrelic.com/kr
2. Click on New Relic log (top banner)

## Expected behavior

JP docs site should send to: newrelic.com/jp
KR docs site should send to: newrelic.com/kr

## Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
