### ISSUE TITLE
Issue: Apdex: Measure user satisfaction

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#9710]
## How can we make our docs better?

There is following description today.  

> APM monitors the performance of these apps. To [define their Apdex settings](https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/change-your-apdex-settings), use the APM UI. You can find Apdex on the [APM Summary](https://docs.newrelic.com/docs/apm/applications-menu/monitoring/apm-overview-page) page and the [browser Summary](https://docs.newrelic.com/docs/browser/new-relic-browser/getting-started/browser-overview-page-website-performance-summary) page.

However the customers need to disable "Show new view" toggle to see Apdex in the browser application page as of today.
I think it is better to remove description about browser application page and recommend to see Core Web Vitals instead of Apdex.

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/apm/new-relic-apm/apdex/apdex-measure-user-satisfaction/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by x8a** [comment]
Hey, @bradleycamacho, can you have a look at this one? Thanks!
