### ISSUE TITLE
Issue: Automated user management: SCIM API

### ISSUE THREAD

**Issue by GaPeppy** [newrelic/docs-website#9757]
This doc page doesn't address the expected value for the array elements:
- groups          (GUIDs or DisplayName or either)
- members      (GUIDs or EmailAddress or either)

Also PUT for most of the REST universe is a full object replacement; not a partial update.  But the docs infer that PUT supports partial update.  Can we explicitly call out PUT's support or partial update?

The examples for PUT on **Group** and PUT on **User** do not reference groups and members.

Helpful detail in the GET calls:
- Get Group example shows no members
- Get User example shows no groups

thanks

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/accounts/accounts/automated-user-management/scim-support-automated-user-management
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 105.0.0.0
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
