### ISSUE TITLE
Incorrect curl command

### ISSUE THREAD

**Issue by jsbnr** [newrelic/docs-website#9769]
The curl command has a -0(zero)  but it should be -O (captial "oh")

Spot the difference:
curl -0 https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip
curl -O https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip

### Doc information (don't delete this section)

* https://docs.newrelic.com/install/java/
* **OS**: Mac OS 10.15
* **Browser**: Firefox 105.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
thanks @jsbnr, yeah that's an important spot

**Comment by zuluecho9** [comment]
fixing with https://github.com/newrelic/docs-website/pull/9778
