### ISSUE TITLE
Issue: Introduction to NRQL, New Relic's query language

### ISSUE THREAD

**Issue by mb-newrelic** [newrelic/docs-website#9781]
Loving the updates to NRQL and the NRQL docs! Wonding if it might it be helpful to add:

* Set up sophisticated alerts 

To:

Reasons to use NRQL include:
* To answer a question for the purpose of troubleshooting or business analysis
* To create a new chart
* To make API queries of New Relic data (for example, using our [NerdGraph](https://docs.newrelic.com/docs/apis/graphql-api/tutorials/nerdgraph-graphiql-nrql-tutorial) API)

## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/introduction-nrql-new-relics-query-language
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 106.0.0.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
good idea. we need to do more to tie together NRQL alerts w/ NRQL alerts and this is good small step

**Comment by zuluecho9** [comment]
fixing with https://github.com/newrelic/docs-website/pull/9782
