### ISSUE TITLE
"What's new" content chopped off in some circumstances

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#979]
### Description

In certain circumstances (possibly involving videos or headers), What's New posts are getting chopped off and crammed into small containers. With the new nerdlog program, these kinds of videos will be a weekly occurence.

### Steps to reproduce

compare this page: https://docs.newrelic.com/whats-new/nerdlog-featured-weekly-releases with three embedded wistia videos, to this page: https://docs-preview.newrelic.com/whats-new/2021/02/nerdlog-featured-weekly-releases  Something funky happened to the size of the first video, and the subsequent sections are missing.

Compare this page: https://docs-preview.newrelic.com/whats-new/2020/12/recap-top-10-new-observability-features-you-need-know to this page: https://docs.newrelic.com/whats-new/recap-top-10-new-observability-features-you-need-know

**Comment by zstix** [comment]
There is also a bizarre scrolling situation that's happening on this page too.
