### ISSUE TITLE
Issue: Metric normalization rules

### ISSUE THREAD

**Issue by brnhensley** [newrelic/docs-website#9830]
## How can we make our docs better?

This doc's image is out of date, there is a field called `Order` now [see image]. Order sets the precedence of the rules.

Here is the the JIRA issue discussing the adding of  `Order`: https://newrelic.atlassian.net/browse/GTSE-11234

<img width="651" alt="image" src="https://user-images.githubusercontent.com/48165493/196223214-5ad85bd5-4c04-41ee-980b-77de919a651c.png">

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/new-relic-solutions/new-relic-one/ui-data/metric-normalization-rules/
* **OS**: Unknown
* **Browser**: Unknown
* **Device**: Unknown

**Comment by bradleycamacho** [comment]
Hi @brnhensley , we're actually doing a large sweep of all screenshots on the site this week. I'm going to close this issue as this image will 100% be touched. Thanks!
