### ISSUE TITLE
Fix a few MIA images from the migration script

### ISSUE THREAD

**Issue by austin-schaefer** [newrelic/docs-website#984]
### Description

Per @jerelmiller :

> We had a handful of images that didn't download correctly during the final migration. We have a record of these, so we'll check to make sure this is one of them and get those downloaded.

### Expected behavior

Find and include missing images in such a way they show up correctly in their original location.

**Comment by jerelmiller** [comment]
Thanks for opening this! I have already fixed and merge this change in https://github.com/newrelic/docs-website/pull/970. These include the images from the migration script that had a warning that could not be downloaded. I'm going to close this for now as this should satisfy the images that didn't sync from the earlier migration.
