### ISSUE TITLE
Issue: iOS manual installation

### ISSUE THREAD

**Issue by bornforlamp** [newrelic/docs-website#9879]
## How can we make our docs better?

* Is something confusing?
> bash script needs a small change
* Is something inaccurate or missing?
> bash script needs a small change
* Were you unable to complete a task? (What task?)
> In Build Phase when add the bash script and try to run the app the app fails, the bash script should add `echo` to it so it should look like this:
`SCRIPT=`/usr/bin/find "${SRCROOT}" -name newrelic_postbuild.sh | head -n 1`
echo /bin/sh "${SCRIPT}" "PUT_NEW_RELIC_APP_TOKEN_HERE"`

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-ios/installation/ios-manual-installation/
* **OS**: iOS 16
* **Browser**: Unknown
* **Device**: iPhone

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
