### ISSUE TITLE
Issue: NRQL subquery limitations missing maximum member limit

### ISSUE THREAD

**Issue by kennytrytek-wf** [newrelic/docs-website#9886]
## How can we make our docs better?

* Is something confusing?
* Is something inaccurate or missing?
    * This error can occur, but there is no mention of this limit in the documentation: `Subquery may have reached the maximum result member limit, which may cause an incomplete result.`
* Were you unable to complete a task? (What task?)

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/query-your-data/nrql-new-relic-query-language/get-started/subqueries-in-nrql
* **OS**: Mac OS 10.15
* **Browser**: Firefox 105.0
* **Device**: Unknown

**Comment by zuluecho9** [comment]
made an edit based on this in https://github.com/newrelic/docs-website/pull/10109

**Comment by zuluecho9** [comment]
thanks @kennytrytek-wf
