### ISSUE TITLE
Issue: Infrastructure monitoring agent EOL policy

### ISSUE THREAD

**Issue by shinji-newrelic** [newrelic/docs-website#9904]
## How can we make our docs better?

The latest version of the infrastructure agent is 1.32.0.
https://docs.newrelic.com/docs/release-notes/infrastructure-release-notes/infrastructure-agent-release-notes/

However this page only lists versions 1.27.5 and prior versions and there is following description.
`Any versions not listed in the following table are no longer supported.`

This means 1.28.x and other new versions are NOT supported.

Please add 1.28.x and other new versions in this list.

Thanks!

### Doc information (don't delete this section)

* https://docs.newrelic.com/docs/infrastructure/infrastructure-monitoring/get-started/infrastructure-agent-eol-policy/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 106.0.0.0
* **Device**: Unknown

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
