### ISSUE TITLE
Issue: NerdGraph tutorial: Alert notification channels

### ISSUE THREAD

**Issue by msummers-nr** [newrelic/docs-website#9934]
Docs need to be updated to reflect migration to `aiNotifications` `Channel` and `Destinations` .

The old style Channels are blocked for new and migrated accounts, these samples won't work there.

**Comment by austin-schaefer** [comment]
We're closing out all issues from 2022 and earlier. Feel free to re-open, or you can leave feedback via the "Was this doc helpful?" form in the right nav of any doc.
