### ISSUE TITLE
[Localization] Serialize all Japanese docs and corresponding English docs for Translation Memory

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#995]
## Summary 
In order for Julien to recreate the translation memory, he will need the serialized html for both the japanese docs and their corresponding english docs. We can utilize our serialization scripts in order to produce this content. This needs to happen AFTER we have completed this ticket: #994 

They file formats should have the samename, followed by the underscore of the locale (ex: `XXXXXXXXX_jp` and `XXXXXXXXX_en`) 

For more information:
https://newrelic.slack.com/archives/C017ZNASGUX/p1614363782141100

**Comment by jpvajda** [comment]
I've asked @jmiraNR to confirm if we can work on this in Sprint 0

**Comment by jmiraNR** [comment]
@jpvajda Content being translated tomorrow 03/17 should enable work to start.

**Comment by zstix** [comment]
* We have english and JP content from ~ feb 12
* During our Github actions workflow, we send the english page (as HTML) and the context
* We need to send the _translation memory_ to the vendor

## Acceptance Criteria
* [ ] Download HTML for all pages that are being translated, in the format that we send to our vendor - English
* [ ] Download the HTML for all pages that are being translated, in the format we bet back from our vendor - JP
* [ ] Send the content to @jmiraNR

**Comment by zstix** [comment]
We have delivered a `.zip` containing the serialized HTML for all JP (and corresponding english) pages. Gonna mark this ticket as done 🎉
