### ISSUE TITLE
Permissions Detail

### ISSUE THREAD

**Issue by GlenOFoghlu** [newrelic/docs-website#9959]
## How can we make our docs better?

Quickstart dashboards are a part of the [New Relic Instant Observability](https://newrelic.com/instant-observability) (I/O) and it looks like based on the permissions, indicated [here](https://docs.newrelic.com/docs/accounts/accounts-billing/new-relic-one-user-management/user-type/#user-type-comparison-table), that full users have the ability to view Quickstart dashboards but basic users do not. This seems to be a permissions limitation with Quickstart dashboards specifically. This needs to be clearer so that our customers do not raise tickets for this based on access rights.

**Comment by zuluecho9** [comment]
fixing with note in https://github.com/newrelic/docs-website/pull/10039
