### ISSUE TITLE
Remove unnecessary console logs / fix warnings for development mode

### ISSUE THREAD

**Issue by caylahamann** [newrelic/docs-website#997]
While helping a content contributor today, I realized that it's pretty difficult to find errors in the console. I thought it would be a good idea to clean this up!

**Comment by austin-schaefer** [comment]
I'd love this! Definitely a lot of cruft running locally today.

**Comment by jpvajda** [comment]
@caylahamann definitely, addded to GA:Sustainment.

**Comment by bradleycamacho** [comment]
@jpvajda Not a priority at all, but I did want to surface this again since it's been a bit of a pain recently to find what errors matter. I know #1385 will solve a bit of this, but just wanted express interest in this.

**Comment by jpvajda** [comment]
@bradleycamacho for sure. there are lot of little things we can do to make the contributing process smoother so we'll consider where this all fits into our upcoming sprints of work.

**Comment by bradleycamacho** [comment]
@jpvajda Thanks, I'm pumped to see this worked on in the future!

**Comment by jpvajda** [comment]
@caylahamann could you provide some more explicit information about what you intended do with this issue?
